### ISSUE TITLE
Restore dependencies on creating a C# project

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#10047]
### Description

The problem is that when a new C# project is created and a C# LS is initialized (open a file), the LS does not have dependencies available. Dependencies have to be there before LS is initialized.

It makes sense to run `dotnet restore` once a project is created.

**Comment by eivantsov** [comment]
@dkuleshov @azatsarynnyy we should probably explore a possibility to restore deps in a custom location  (say, somewhere in the project itself so that they are persisted). However, in this case, it is not clear how to configure LS to make sure it knows how to pick'em up from this custom location.
We should probably take a look at what VS Code plugin does.

**Comment by azatsarynnyy** [comment]
I've tried to restore the dependencies in a project's subfolder to see how much space it takes. More than 200 MB for dotnet-web-simple project.

**Comment by azatsarynnyy** [comment]
closed by https://github.com/eclipse/che/pull/10405
