### ISSUE TITLE
Move eclipse/che-dependencies/pom.xml to eclipse/che-parent/dependencies/pom.xml module

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10216]
### Description
The motivation to have distinct eclipse/che-dependencies and eclipse/che-parent repositories were to separate maven configuration and dependency management into the separate places.  However, after talks with @NickBoldt and @riuvshin  I think we may achieve this goal in a single repository. This idea is supposed to keep the separation between maven configuration and dependency management and allow to simplify CI/CD since we don't nee one extra repository.

**Comment by nickboldt** [comment]
+1 for merging repos (**che-parent**, **che-dependencies**, **che-dev**) into a single repo. If you want to merge pom files too, I'm +1 to that but that's less important from my end (productization) since I'm just trying to reduce the number of _JOBS_, not the number of _ARTIFACTS_.

Putting everything in one repo means I can build all the che-* repos in one operation, and that can include all 4 of the current artifacts, or can include fewer if we merge them.

Note that I haven't looked carefully at the **che-lib** repo to know if those artifacts still need to be maintained as forks of upstream (or why) but for now I'll assume you have been unable to push your forks/changes upstream, and need to maintain these. Since it's forked 3rd party code, it might be better to keep it in a separate repo to address things like different license terms. Also might be worth exploring if Che works correctly against the non-forked versions found in RHEL.

**Comment by skabashnyuk** [comment]
>BTW I would say to move it to eclipse/che-parent/dependencies (we don't need extra che-) before dependencies

Ok.
>and we could as well merge both pom.xml from che-parent and che-dependencies instead of having another pom.xml elsewhere

I still think that separation is useful for two reasons.
1. Backward-compatibility.  We don't need to change anything. We will keep groupid and artifactid.
2. Supportability. Both pom.xml files are huge, I don't want to make it bigger.

**Comment by nickboldt** [comment]
Note that when I proposed merging che-dev into che-parent repo, I also kept the same GAV values rather than switching to new groupIds for the same reason (backward compatibility, more incremental changes).

**Comment by skabashnyuk** [comment]
>+1 for merging repos (che-parent, che-dependencies, che-dev) into a single repo.

I'm not sure that is technically possible to merge che-parent and che-dev

**Comment by nickboldt** [comment]
Sure it is. See PRs above. Built fine here :D

**Comment by skabashnyuk** [comment]
>Sure it is. See PRs above. Built fine here :D

Don't want to brake your happines. But it's not. see [1] in  https://github.com/eclipse/che-parent/pull/57#issuecomment-399649513

**Comment by skabashnyuk** [comment]
>che-parent still depends on che-dev

That's right. But that che-dev doesn't depend on old version of che-parent. It is indepdented artifact.

>So merging che-dev and che-parent into the same repo would make them buildable at the same time, right?

Did you saw that in your PR che-eclipse-license-resource-bundle doesn't reference che-parent as a parent? That is can cause a potential problem during release.  
BTW can we move this concrete discussion to your PR?
