### ISSUE TITLE
Fail of cloning a "Che" project to workspace which based on "Eclipse Che" stack

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#10286]
### Reproduction Steps
 - Go to dashboard 
 - Click on "Workspaces" -> "Add Workspace"
 - On the opened page select the "Eclipse Che" stack
 - Click on "Add or Import Project" button
 - In the opened form click on "Git" button
 - Paste the "Che" git URL ("https://github.com/eclipse/che.git")
 - Click on "Add" button
 - Start workspace and open IDE
 - Wait until "Che" project is cloned
 - Pay attention to error popup

**Expected behavior:**
The "Che" project will be successfully  cloned

**Observed behavior:**
Cloning of the "Che" project is failed

**Attachment:**
![kljkljklj l](https://user-images.githubusercontent.com/22724619/42324811-f38546a0-806c-11e8-97fe-3c807cdbc50f.png)

* We have a similar behavior for import from the IDE: 
   - the _Import project_ form does not close
   - the _Project Configuration_ form is not appeared 
   - there are errors in the browser console
* See the screenshot:
 
![import-eclipse-che-from-ide](https://user-images.githubusercontent.com/5408906/42698033-6e74f6b8-86c5-11e8-87fe-18baddbbbe39.png)

**OS and version:**    
Che 6.8.0 ; Chrome 67.0 ; Fedora 25

**Comment by sleshchenko** [comment]
As far as I see, Import project request failed due to 504 Error after 30 seconds
![projectimport](https://user-images.githubusercontent.com/5887312/42377631-b5308598-812c-11e8-9857-7b2efea992ad.png)
I've checked and as far as I understand this request imports project synchronously.
I think the request is failed after 30 seconds because it may be a default value for request timeout on OCP haproxy router. https://docs.openshift.com/container-platform/3.5/install_config/configuring_routing.html
A possible solution is to do import method asynchronous.
As an alternative solution - increase timeout by adding a custom annotation to each workspace timeout, but I prefer the first way.

**Comment by vparfonov** [comment]
I can confirm your idea @sleshchenko, we will switch import process to the JSON_RPC backend
