### ISSUE TITLE
Question: How is a dockerfile used with a stack? Can we use the --privileged notion or the --device?

### ISSUE THREAD

**Issue by agnesagnes** [eclipse-che/che#1031]
I launch eclipse che in docker thanks to this command:
 docker run -ti --net=host -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces  -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage codenvy/che

Then, I have defined a new custom stack based on a custom docker image that installs Intel OpenCL drivers, here no problem. But for Nvidia OpenCL drivers, we need to authorize device access thanks to --device if the image was run with a docker run --device command.  
How is the image run in order to create the workspace? How can we authorize the devices (in /dev).   Yes, I obviously don't completely undestand the use of the stacks!

**Comment by TylerJewell** [comment]
Hi @agnesagnes.  When you create a workspace, that workspace is creating a container. The container is a runtime that comes from an image.  A stack is just a configuration file that Che uses to define which image(s) should be used in the making of a container. It can either reference an image ID from a registry, or if you provide a Dockerfile, it will build an image from that Dockerfile and then create the container from that image.

We then create special user accounts and inject software into the container.  Your projects are the injected into the container.  To the end user, this feels like localhost, but behind the scenes the user is now working within a container that is powering the workspace.

If the user in his workspace wants to launch his own Docker container, it will fail because this is docker in docker.  However, we **just** committed a change into master that lets you configure che so that --privileged mode will work.  You set this property once with Che and then users can launch docker containers from within their workspace.

https://eclipse-che.readme.io/docs/configuration#running-projects-that-run-docker

You will have to build Che from master repository to get this. It will be part of Che 4.2 which will release within a couple weeks here.

**Comment by ghost** [comment]
@agnesagnes in your case it is better to run Che natively and use privileged-true property in Che configuration. However, Che in Docker use case works as well.

**Comment by ghost** [comment]
Since --privileged is in master, I am closing the issue. Setting this property's value to true will launch a container in a privileged mode.
