### ISSUE TITLE
Create exclude rules for jwtproxy

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10312]
### Description
In some cases, we might allow the unauthenticated request. Such as.
 - CORS preflight request.
 - Health check request.
 - Application loader pages.

**Comment by mshaposhnik** [comment]
Since jwtproxy is just a handler bound to `coreos/goproxy`, (for all incoming requests) it can be also bind under  any of the standart rules available [https://github.com/coreos/goproxy/blob/master/dispatcher.go](here)
In short, it can be:
- UrlHasPrefix(prefix string) - checks URL is prefixed by some string;
- UrlIs(urls ...string)  - url matching;
- ReqHostMatches(regexps ...*regexp.Regexp) - match tost by regex
- ReqHostIs(hosts ...string) - matches whole host
- UrlMatches(re *regexp.Regexp) - URL rexeg matcher 
- DstHostIs(host string), SrcIpIs(ips ...string) - destination host and origin IP
and 
 - Not(r ReqCondition) to invert any of those conditions.

**Comment by mshaposhnik** [comment]
The inital idea was to do something like that
```
listen_addr: localhost:4471
    verifier:
       upstream: http://localhost:4401
       audience: http://xxxxx"
       **bind_regex: ^(?!.*(/liveness)$).*"**
       max_skew: 1m"
       max_ttl: 3h"
       key_server:"
```this examnple should verity anything except the `/liveness` requests. But since regex support in Go is reduced, negative lookaheads isn't supported, so writing regexes can becase very tricky.  Need to look for another possible way.

**Comment by mshaposhnik** [comment]
I have tested and can confirn that following exclusion scheme can be implemented:

1) You can optionally add any number of exact path excludes. 
2) You can optionally add ONE (due to goproxy api  :( )  path_prefix exclude.  In the example above, it means that all paths starting with `/process/` will be excluded, like `/process/1?token=....`, `/process/2?token=...` etc.

```
verifier:
                        upstream: http://localhost:4401
                        audience: http://xxxxxxxx
                        max_skew: 1m
                        max_ttl: 3h
--->                  excludes:
--->                       - /api/liveness
--->                  prefix_exclude: /process/
                        key_server:
                        ....
```
@skabashnyuk It that looks sufficient for thr beginning?

**Comment by sleshchenko** [comment]
@mshaposhnik This excludes will be configured in [server configuration attributes](https://github.com/eclipse/che/blob/c711293ffd8138fd2f7f0588bc2afc8e737a4dba/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/ServerConfig.java#L66). Please elaborate more about how it should be configured there and how it will be mapped into jwtproxy config. Will it be something like the following example
```
{
    "servers": {
    "terminal": {
      "port": "4411/tcp",
      "protocol": "ws",
      "path" : "/pty",
      "attributes": {
        "secure": "true",
        "unsecuredPaths": "/api/liveness, /api/other/exclude, /process/*"
      }
    }
  }
}
```
?

**Comment by mshaposhnik** [comment]
yes it can be that way

**Comment by mshaposhnik** [comment]
3rd option: use excludes regexp list. Example:
```
verifier:
         upstream: http://localhost:4401
         audience: http://xxxxxxxx
         max_skew: 1m
         max_ttl: 3h
--->     excludes:
--->       - ^(/api/liveness)$
--->       - ^(/api/other/.*)$
             ....
         key_server:
        ....
```
It still have issue with look-aheads, but in this case they are needed much more rarely. So if you need to skip all except one methods of some service, you need to enumetare all skipped methods explicitly.

**Comment by mshaposhnik** [comment]
This issue covers jwtproxy only. Another one will be created to pass excludes from server configuration into  the proxy conf.
