### ISSUE TITLE
A lot of failing Selelnium tests with jwtproxy auth enabled

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#10490]
With jwtproxy auth enabled, the percentage of successfull tests only about 40%. Need to find reasons and do fixes to make that percentage  maximally close to the master.

**Comment by mshaposhnik** [comment]
A berare token fix allowed to imrpove result to the 80% success. Investigating the rest.

**Comment by mshaposhnik** [comment]
The rest seems to be caused by 2nd machine when tests written for the single-macheni environment.
Unexpected machine selection dialog causes the fails:
![org eclipse che selenium debugger changevariablewithevaluatingtest changevariabletest_uqw315i5](https://user-images.githubusercontent.com/1651062/43002745-8ca23926-8c32-11e8-8006-8599ddba1fcd.png)

**Comment by sleshchenko** [comment]
I think @vparfonov's team can be asked to take a look on that, because jwt-proxy doesn't have terminal, or exec-agent servers. How is command supposed to work in `jwtproxy` machines?

@l0rd @gazarenkov @garagatyi 
Maxim described an interesting issue. Maybe it makes sense to introduce like tooling machines which will be hidden by default? Because for a user it may look a bit strange that he has one machine in his recipe, during a runtime start new machine appear and he is not able to do anything with that.

**Comment by mshaposhnik** [comment]
One more problem - saving APP states failed due to missing `bearer` identificator.
Patch will be included in the main PR.
![screenshot_20180720_170618](https://user-images.githubusercontent.com/1651062/43006859-71842a5c-8c3f-11e8-9b48-84f79a25e22c.png)

**Comment by mshaposhnik** [comment]
It seems that only UI issues left due to additional machine tab.  Not sure there is much sense in trying to fix them in GWT client since it is coming to EOL, so probably we can merge the PR, keeping jwtproxy auth disabled by default. @skabashnyuk is OK for you ?
