### ISSUE TITLE
Fail "create project" after "inject and start workspace agent" on create workspace sequence

### ISSUE THREAD

**Issue by kazusa-qooq** [eclipse-che/che#1050]

**Comment by TylerJewell** [comment]
Hi!  Can you provide full bug report.  Please see CONTRIBUTING.md for the information we need to help diagnose.

**Comment by kazusa-qooq** [comment]
Sorry, I mistaked to press enter...

I fail to create my first workspace.
The phase is "create workspace" and after start at once.
Error is failing to resolve github.
Additionally, the "create workspace" console on browser is empty
and the "inject and start workspace" has last message like a "OAuth Authentication unsupported site: github.com" as Error.

I try to use bash and success git clone from github on docker.
How I get other hints?

Unfortunately, I don't have a detail log in my hand now.
Therefore, if need other information, I'll write next week.
Thanks for your helping.

**Comment by kazusa-qooq** [comment]
Sorry to I don't have also environment details in my hand now.
But maybe latest because I created environment from installing OS with centos7 on hyper-v.
I'll also put in next week.

**Comment by ghost** [comment]
If github.com cannot be resolved inside a running container, this is a connectivity issue. You may want to destroy your VM and start anew. Alternatively, you may ssh into a VM and run any docker image, exec into it and ping github.com:

`docker run -ti ubuntu bash`
`ping github.com`

**Comment by kushalmokashi** [comment]
@eivantsov Hi, I am also facing the same problem. To give you the little background, I feel there is issue with the networking. Because when I do exec into the container and if I ping 8.8.8.8 then I am bale to access this. But when I do google.com then it gives host not found. That means there is some problem in the name space lookup. the details of my system are described in the issue #979 .
The other extra details of the system are as follows: 
the $ipconfig /all of my host system is:
 C:\Users\kumo>ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : PCUHM04
   Primary Dns Suffix  . . . . . . . : eur.ad.sag
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : eur.ad.sag
                                       ame.ad.sag
                                       apa.ad.sag
                                       hq.sag
                                       ad.sag
                                       ams.sag
                                       webmethods.com

Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . : eur.ad.sag
   Description . . . . . . . . . . . : Intel(R) Ethernet Connection I217-LM
   Physical Address. . . . . . . . . : F8-B1-56-C7-56-2E
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 10.22.19.202(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Lease Obtained. . . . . . . . . . : Freitag, 15. April 2016 12:34:57
   Lease Expires . . . . . . . . . . : Samstag, 23. April 2016 12:34:57
   Default Gateway . . . . . . . . . : 10.22.16.1
   DHCP Server . . . . . . . . . . . : 10.20.90.88
   DNS Servers . . . . . . . . . . . : 10.20.90.10
                                       10.22.90.10
   Primary WINS Server . . . . . . . : 10.22.90.77
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter VMware Network Adapter VMnet1:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : VMware Virtual Ethernet Adapter for VMnet
1
   Physical Address. . . . . . . . . : 00-50-56-C0-00-01
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.244.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter VMware Network Adapter VMnet8:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : VMware Virtual Ethernet Adapter for VMnet
8
   Physical Address. . . . . . . . . : 00-50-56-C0-00-08
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.91.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter
   Physical Address. . . . . . . . . : 0A-00-27-00-00-00
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.56.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter VirtualBox Host-Only Network #2:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter #2
   Physical Address. . . . . . . . . : 0A-00-27-00-00-00
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.99.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   NetBIOS over Tcpip. . . . . . . . : Enabled

$ifconfig of the VM
kumo@kumo-VirtualBox:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:06:01:74:31  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:6ff:fe01:7431/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:403 errors:0 dropped:0 overruns:0 frame:0
          TX packets:323 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:38128 (38.1 KB)  TX bytes:45191 (45.1 KB)

eth0      Link encap:Ethernet  HWaddr 08:00:27:04:b1:b0  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe04:b1b0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:14225 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8772 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:9467721 (9.4 MB)  TX bytes:1465090 (1.4 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:4687 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4687 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:490132 (490.1 KB)  TX bytes:490132 (490.1 KB)

vethbce9ef9 Link encap:Ethernet  HWaddr f6:41:b3:e6:6d:e5  
          inet6 addr: fe80::f441:b3ff:fee6:6de5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:137 errors:0 dropped:0 overruns:0 frame:0
          TX packets:146 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:16057 (16.0 KB)  TX bytes:20958 (20.9 KB)

$more /etc/resolv.conf of the VM is:
kumo@kumo-VirtualBox:~$ more /etc/resolv.conf

# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)

# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

nameserver 127.0.1.1
search eur.ad.sag

$ifconfig of the container 
user@4974717824fa:/$ ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:02  
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:146 errors:0 dropped:0 overruns:0 frame:0
          TX packets:137 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:20958 (20.9 KB)  TX bytes:16057 (16.0 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

$more /etc/resolv.conf of the container is:
user@4974717824fa:/$ more /etc/resolv.conf

# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)

# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

search eur.ad.sag

nameserver 8.8.8.8
nameserver 8.8.4.4

When I do docker run using --dns=10.20.90.10
then I am able to access the google.com 
i.e. name space server is working.

So what changes/configure I should do when I run che.sh and it should start working given the above specification of the system.?

**Comment by kazusa-qooq** [comment]
Thanks @eivantsov and sorry late response.
I'll do what you said but may fail because the proxy doesn't allow ICMP.
By the way, I can't export detail logs and environment information under security policy. Sorry.
Could you tell me how get more info?

**Comment by kazusa-qooq** [comment]
@eivantsov  @kushalmokashi 
Hi, I succeed to launch IDE.
I mounted workspace with -v option.
First, same error occered.
But retry as open workspace, the create project phase was skiped and launched IDE.
Now, I'll leave this issue.
Please continue or close if you need or not.
Thanks for taking your time.

**Comment by kushalmokashi** [comment]
@kazusa-qooq @eivantsov The issue is resolved for me. I had to explicitly configure the --dns="IP_Addr" in the docker file, which is located in the /etc/default/ folder. Now it works.
You can close the issue. Thanks for your time and the help.
