### ISSUE TITLE
Machine token can be used to access master

### ISSUE THREAD

**Issue by Ido-Itz** [eclipse-che/che#10682]
### Description
As was presented yesterday (7/8/18) in the Che Dev Community Call:
I have noticed an unexpected behavior with the way that machine tokens can be used based on how we (SAP) understood them so far.

Here is what I presented in the call:

**Our assumptions:**
- User token (JWT) is used to access **che-master** APIs.
- Machine token is granted per workspace and is used to access **workspace-agent** (and other agents) APIs.

**Our findings:**
- Machine token of workspace X can be used to access workspace master APIs with the privileges of the original user.
    - Can start/stop/delete **any workspace** of the original user.
    - Machine token cannot be used to directly access workspace Y.
- Machine token of workspace X can be used on che-master to request machine token of **workspace Y**.
    - Using workspace X token, I can now gain access to workspace Y.

### Reproduction Steps
Simply use the machine token that is granted for any workspace to access the workspace master APIs.

**OS and version:** 
Kubernetis multi-user installation of che 6.7.1

@skabashnyuk 
My main question is whether or not this behavior is intentional. If it is, then what is the purpose of the machine-token and user-token separation? I can use a machine token to perform the same operations as the user-token.
If it isn't intentional, then I suppose this is an actual issue.

Thanks!
Ido

**Comment by skabashnyuk** [comment]
>My main question is whether or not this behavior is intentional. 

yes, it was made intentional

>If it is, then what is the purpose of the machine-token and user-token separation?

Basically for two things.
1. In case if a machine token would be stolen, the worst thing that can happen is limited of Che scope. In case if your Identity provider generates the same tokens for different services with stolen user-token attackers can do some actions outside of Che.
2. For particular Keycloak use-case, we would need to generate individual clients for separate workspaces. With very high probability keycloak are not designed to have hundreds or thousands of simultaneous clients.

>I can use a machine token to perform the same operations as the user-token.
>If it isn't intentional, then I suppose this is an actual issue.

We thought about limiting of scopes of API available for machine-token. However, we never estimate that risk as high, that is why they have the same power as user-toke. 
Can you elaborate why do you think this is an issue for you?

**Comment by skabashnyuk** [comment]
Scope limited https://github.com/eclipse/che/issues/10710
