### ISSUE TITLE
Do not wait loadBalancer of ingresses if servers host is known

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#10767]
### Description
Some of ingresses backends do not update Ingress objects with loadBalancer's IP. Because of it, workspace start gets stuck because of reaching timeout while waiting for loadBalancer's IP. 
There are three servers exposing strategies in Kubernetes infrastructure: default-host, single-host, multi-host. And loadBalancer's IP is needed only for `default-host` exposing strategies while the other two have predefined `host` name for server.

So, it is needed to improve Kubernetes Infrastructure not to wait loadBalancer of ingresses if servers host is known: 
- for `single-host` strategy it is value of `che.host` configuration property;
- for `multi-host` strategy it is {SERVER_SPECIFIC_PREFIX} + `che.infra.kubernetes.ingress.domain`

### Reproduction Steps
1. Deploy Che on Kubernetes where `Azure AKS` is used as ingresses backend.
2. Try to start a workspace.
Expected: the workspace is started successfully.
Actual: the workpace fails to start with an error: 
> Waiting for ingress {INGRESS_NAME} reached timeout

**OS and version:**    

**Diagnostics:** 

Related issues: https://github.com/eclipse/che/issues/10300, https://github.com/eclipse/che/issues/10751

**Comment by guydaichs** [comment]
Hi, 

We've seen similar issues, that are related to the nginx ingress controller:
* https://github.com/kubernetes/ingress-nginx/issues/2509
* https://github.com/kubernetes/ingress-nginx/issues/2690 

In general, it would be best to wait for the ingress controller to update the status, so that we know that the routing rules were really applied. Otherwise, the server checkers can start polling agents too early, and timeout before the agents are available. So, timeout should be reasonable...

However, we've also seen behavior where the agent ingress routes are responsive very quickly, long before the ingress controller notifies that routes are updated. The current wait blocks the whole workspace bootstrap, so replacing it may also improve overall performance of workspace loading.

**Comment by tarioch** [comment]
This also happens in bare metal installations that don't use loadbalancer (e.g. with nginx ingress running on host network).

**Comment by mingfang** [comment]
My Ingress Controller is using NodePort and am experiencing this same problem.

**Comment by mingfang** [comment]
Can we add a flag to bypass this check?
It is a show stopper for me.
