### ISSUE TITLE
Integrating Yang Based Theia IDE into Eclipse Che

### ISSUE THREAD

**Issue by amirsaad2015** [eclipse-che/che#10795]
### Description
Hello. I am trying to integrate this open source Yang based Theia IDE into Eclipse Che, and was wondering the necessary steps on how to do it via the Eclipse Che dashboard. 

Here is a link to the repository: https://github.com/theia-ide/yangster

**OS and version:**    
macOS High Sierra
Version: 10.13.5

**Diagnostics:**

**Comment by eivantsov** [comment]
@amirsaad2015 you need to builld a Docker image with the IDE inside it. Once done, you can create a custom stack, just like this one - https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L3 but reference your custom image instead of https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L53

**Comment by amirsaad2015** [comment]
@eivantsov I have created the Docker image with the IDE inside. However, I am not sure how to create a custom stack, and where to create the custom the stack.

**Comment by eivantsov** [comment]
@amirsaad2015 https://www.eclipse.org/che/docs/creating-starting-workspaces.html#creating-workspaces

**Comment by Rijul5** [comment]
@eivantsov 
Hello, in reference to this issue, I am able to create a Docker image and then replacing the image in this [stack](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L53), I am unable to load the image when running this stack in a new workspace. I am getting the below error:
![image](https://user-images.githubusercontent.com/32622151/47954709-ab177e00-df63-11e8-86ae-53958337cc03.png)

Just to understand the correct process,
a. We go to "Add Stack" option
b. Then a window "Build stack from recipe" gets opened, with three tabs {Compose, Docker Image, Docker File}.
c. Now, since I am using docker, I am good to select Docker Image tab as I also have my customized theia yangster docker image.

### 1. Now my **first question** is what to input in the editor space when I select Docker image tab as I can simply go to next step and input my stack information in raw configuration. But without entering anything in the editor space, I am unable to go to the next step. (The current [documentation](https://www.eclipse.org/che/docs/creating-starting-workspaces.html#creating-workspaces) is not very clear)

![image](https://user-images.githubusercontent.com/32622151/47954772-a7382b80-df64-11e8-93c7-09536197c852.png)

### 2. Now my second question is on these three different tabs, as I believe the [current stack](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L63) for theia ide as its content type as "Compose" and then we are providing the image "eclipse/che-theia:plugin-id-nightly". So if I replace this image with my image, should it work? Also, should we select our recipe as "Compose" or "Docker Image"?

I would appreciate your further advice on this.
