### ISSUE TITLE
No didChangeWatchedFiles notification for existing files in the LSP? 

### ISSUE THREAD

**Issue by es13b1018** [eclipse-che/che#10794]
Hi,

I am using Che 6.6.0 version and have a local repo mounted. I have contributed to project types and file types and have an LSP for various language features.

In Che plugin I have extended `LanguageServerConfig` and added the following code to watch some set of filetypes:

```
private static final String REGEX = ".*\\.(cls|p|i)$";

@Override
  public RegexProvider getRegexpProvider() {
    return new RegexProvider() {
      @Override
      public Map<String, String> getLanguageRegexes() {
        return ImmutableMap.of(ProjectAttributes.ABL_ID, REGEX);
      }

      @Override
      public Set<String> getFileWatchPatterns() {
        return ImmutableSet.of("regex:" + REGEX);
      }
    };
  }
```
I get call backs (on change, delete, etc) for the watched files (`REGEX `) while the workspace is running and a new file is created.

But if I **stop and start a workspace**, the LSP is initialized again and I stop getting call backs for those existing files. Only the newly created files is being watched from this point.

Can someone help me with this? Is this a bug or can I configure something else to make this work?

**Comment by eivantsov** [comment]
@dkuleshov  probably knows

**Comment by dkuleshov** [comment]
Could you please clarify where in the code you get those callbacks, because I'm not sure I follow you here. In general the idea that stands behind that `REGEX` field is to associate a file with a corresponding language server and editor when we open it, so I don't see direct relation to change, delete, etc. callbacks.

**Comment by es13b1018** [comment]
@dkuleshov 
I have a Language Server Installer, where I am using (extended `LanguageServer`, `TextDocumentService` and `WorkspaceService`. (`LSP4j`)

The callbacks I am talking about is in the `didChangeWatchedFiles` (org.eclipse.lsp4j.services.WorkspaceService)

**Comment by es13b1018** [comment]
@dkuleshov
I have a Language Server Installer, where I am using `LSP4j` to implement various services.
The callbacks I am talking about is in the `didChangeWatchedFiles` method (`org.eclipse.lsp4j.services.WorkspaceService`): 
```
@Override
  public void didChangeWatchedFiles(DidChangeWatchedFilesParams params) {
  //Some code
 }
```

**Comment by dkuleshov** [comment]
Understood, thank you. I'll need some time to check it on my side.

**Comment by es13b1018** [comment]
Thanks @dkuleshov. Is there any update?

**Comment by dkuleshov** [comment]
@es13b1018 Yes, sorry for the delay, I've checked the use case and seems like it is a bug.

**Comment by tsmaeder** [comment]
I suepect this is caused by https://github.com/eclipse/che/issues/11282

**Comment by tsmaeder** [comment]
Maybe we should register with the FileTreeWalker directly instead of using the native file watcher service. Being informed late of changes is a normal occurrence in IDEs. Also, for example registering for all *.java files for jdt.ls may very well overload the native file watcher service on Linux.

**Comment by dkuleshov** [comment]
Actually `FileWatcherManager` which is used in `LanguageServerFileWatcher` was initially designed to get near real time responses from file system and it is not expected to track great amounts of files (because of the limitations of inotify linux kernel subsystem).

But in your case if you're saying that latency is not an issue, we obviously should use `FileTreeWalker` which is exactly designed to track big number of files with a longer response time.
