### ISSUE TITLE
Command process ids in the Command Toolbar begin from 2

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10809]
**Reproduction Steps:**
1. Create and start workspace through **Dashboard** based on **Java** stack with "**web-java-spring**" project. 
2. Select project in the **Project Explorer**.
3. Start "**web-java-spring:build**" command from project context menu.

**Expected result:**
The command started and "**dev-machine: web-java-spring:build**" process is visible in the **Command Toolbar** with "**1**" id.

**Actual result:**
The process ids begin from "**2**".
 
**Che version**: 6.10.0-SNAPSHOT
**OS and version:** Fedora 28
**Failed selenium test:** CheckIntelligenceCommandFromToolbarTest

**Additional information:**
* Issue reproduced randomly
* See the attachment:

**Screenshot:**
![selection_084](https://user-images.githubusercontent.com/7760565/44208529-4a00bb00-a169-11e8-85ed-ff39b6d177c0.png)

**Screencast:**
![screencast-172 19 20 234-8080-2018 08 16-15-27-46](https://user-images.githubusercontent.com/7760565/44208577-64d32f80-a169-11e8-8590-112baa57036c.gif)

**Comment by azatsarynnyy** [comment]
The first running process' ID is 2 because the exec-agent can be used not by IDE users only but it may be called programmatically by the extensions.
Currently, the `plugin-machine` [injects the SSH keys](https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/plugins/plugin-machine/che-plugin-machine-ext-server/src/main/java/org/eclipse/che/ide/ext/machine/server/ssh/KeysInjector.java#L130) into a machine on workspace start. So this is the first running process. I'd say it's a normal behavior.
