### ISSUE TITLE
Workspace Agent uses org.eclipse.xtend.lib SNAPSHOT version

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#11028]
### Description

I noticed that the ws-agent.war is using snapshot versions of xtend (org.eclipse.xtend.lib-2.15.0-SNAPSHOT.jar and org.eclipse.xtend.lib.macro-2.15.0-SNAPSHOT.jar).
Obviously in terms of build-stability that should be avoided.

We are still using Che 6.7.0 but I verified that in Che 6.10.0: same thing.

I'm not sure why this dependency is pulled in. I noticed org.eclipse.lsp4j.generator-0.3.0.jar depends on a dependency range xtend.lib [2.11.0,3), but this should get the latest release I assume.

I would suggest to pin the version to the latest released xtend (2.14.0)

**Comment by eivantsov** [comment]
@skabashnyuk @vparfonov can you comment please?

**Comment by eivantsov** [comment]
@tsmaeder it looks like you are more knowledgeable

**Comment by skabashnyuk** [comment]
@tsmaeder would you like to comment. AFAIK lsp-0.3.0 was introduced in this pr https://github.com/eclipse/che-dependencies/pull/93

**Comment by tsmaeder** [comment]
We are already excluding the node org.eclipse.xtend.lib in che-plugin-languageserver-ide because we need to grab a gwt-specific version of the runtime libraries (xbase). 
Generally, I have no immediate idea what the right way to solve this is: a library attracting a snapshot version of one of it's dependencies is a thing that might happen at any time in any dependency. The only way to solve this in general is to fix the versions of all transitive dependencies. Maybe there is a way to limit the projects that can have snapshot versions? I don't know.

**Comment by apupier** [comment]
in this case, the projects are not declaring SNAPSHOTS dependencies explicitly.
A range is specified and a SNAPSHOT version is available in the available repositories which is the version picked by Maven.
I think that we don't need to search "a way to limit the projects that can have snapshot versions" but a way to limit the Maven resolution to pick snapshots version for some specific artefacts

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
