### ISSUE TITLE
Why didn't I javascript Code highlighting

### ISSUE THREAD

**Issue by Zephylaci** [eclipse-che/che#11027]
The effect for javascript:

but css and html there is no problem

why? and what shoud i do?

**Comment by eivantsov** [comment]
@Tarhyru does it happen to particular .js files or all of them?

**Comment by Tarhyru** [comment]
@eivantsov 
No,all js file，all not line
I also tried loading the sample project
js file Again, no highlights

**Comment by eivantsov** [comment]
@Tarhyru i cannot reproduce the issue:

![image](https://user-images.githubusercontent.com/5337267/44970111-c3b1ea80-af58-11e8-83ba-393cf916d564.png)

Can you perhaps share your .js file as github gist? Maybe contents or Chinese characters can have impact

**Comment by Tarhyru** [comment]
emmmm...
I've recreated the workspace...
Only the sample file is loaded at the same time..
![tim_top](https://user-images.githubusercontent.com/13960592/44974373-080dac80-af92-11e8-8d89-dd7b064058d0.png)
So I don't think it's the influence of Chinese annotation....At the same time only comments have Chinese..
Because I'm starting a new workspace, I'm just going to create a new js file and it doesn't work..
Javascript highlighting Are there any Settings?

**Comment by eivantsov** [comment]
@Tarhyru are there any errors in browser dev console?

**Comment by Tarhyru** [comment]
@eivantsov 
I think I saw the plugin of JavaScript being wrong.
![qq 20180904210104](https://user-images.githubusercontent.com/13960592/45032986-c3633d80-b085-11e8-89b9-08259f9459fa.png)
What should we do about this situation?

**Comment by eivantsov** [comment]
@Tarhyru the last error is what has probably caused it. I'd restart Che and try in an incognito mode

**Comment by Tarhyru** [comment]
@eivantsov 
incognito mode?
emmmm....
active clear browser cache after
I finally saw the highlight of JavaScript...
Thank you for the answer
