### ISSUE TITLE
 Improve naming for wsnext tooling containers

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#11031]
### Description
When using ws.next workspaces, containers coming from plugins are named in my case:
- toolingqtm22ewy
- toolingtv4icpyu

it would be nice if the name could contain more details like the name of the plugin
![image](https://user-images.githubusercontent.com/436777/44903853-e8fee880-ad0d-11e8-88f4-dfac8cac979e.png)

it would help for example when you need to go to a terminal

**Comment by sleshchenko** [comment]
@benoitf There is another issue to use sidecar container name (but not plugin name)  as container name https://github.com/eclipse/che/issues/11096. If you are OK with such containers naming please close the issue as duplicate.

**Comment by sleshchenko** [comment]
So, the scope of this issue is to implement using container name from sidecar definition instead of generating one. Note that collision issue should not be covered here and there may be cases when two plugins provide the same containers with the same name and it will lead to workspace start failure.

**Comment by benoitf** [comment]
plugin's id as prefix/suffix shouldn't make it collide (could be a way to solve collision)

**Comment by sleshchenko** [comment]
> plugin's id as prefix/suffix shouldn't make it collide (could be a way to solve collision)

@garagatyi WDYT?

**Comment by garagatyi** [comment]
The problem would be the signs used in the ID - k8s is very restrictive in that.
Previously, I implemented random names and @l0rd  suggested moving to the names from the sidecar definition, so would be nice to hear his opinion on that. But since this name is needed to just identify where the container is belong I'm ok with such an approach.
Since @AndrienkoAleksandr is working on matching containers on k8s infra for the exec/terminal plugins it make sense to involve him as well

**Comment by sleshchenko** [comment]
@l0rd Could you please confirm that you are OK with naming containers in workspaces as `{PLUGIN_NAME}` + `-` + `{CONTAINER_NAME}`?
But then we have to limit possible characters for plugins and their containers names 
I think here is describe naming convention https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
> By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions.

**Comment by sleshchenko** [comment]
I believe it should be fixed by https://github.com/eclipse/che/pull/11465
