### ISSUE TITLE
Rolling update of che server  version resulted in `CrashLoopBackOff`

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#11087]
Rolling update of rh-che from `6.9.0` to `6.10.0` went well and the new version was released on both prod and prod-preview osio osd clusters. However, when the new rolling update was performed after the next commit [1] to rh-che it resulted in `CrashLoopBackOff`:

![image](https://user-images.githubusercontent.com/1461122/45022213-ec5ae280-b033-11e8-963b-96d10a3ff617.png)
   

NOTE: upstream che-version was not changed - it is still 6.10.0. The full log is available here [2] and  the real  problem seem to be related to NPE in `SignatureKeyManager`:

`java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.NullPointerException\n\tat org.eclipse.che.multiuser.machine.authentication.server.signature.SignatureKeyManager.toJavaKeyPair(SignatureKeyManager.java:178)\n\tat org.eclipse.che.multiuser.machine.authentication.server.signature.SignatureKeyManager.loadKeyPair(SignatureKeyManager.java:139)\n\tat org.eclipse.che.multiuser.machine.authentication.server.signature.SignatureKeyManager$1.load(SignatureKeyManager.java:96)\n\tat org.eclipse.che.multiuser.machine.authentication.server.signature.SignatureKeyManager$1.load(SignatureKeyManager.java:93)\n\tat com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)\n\tat com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)`

[1] https://github.com/redhat-developer/rh-che/commit/414a44ffa3da05d8a765305429777c4732bb031b
[2] https://paste.fedoraproject.org/paste/h4-9NfOH8Oee5qvVM5hbug

**Comment by skabashnyuk** [comment]
### What happened. 
During the implementation of this issue https://github.com/eclipse/che/issues/10074
"Make public/private signing keys pair per-workspace and synch with workspace runtime (renew pair on each workspace restart)" in
https://github.com/eclipse/che/pull/10761 we made an SQL migration that is supposed to allow not to stop all workspaces during hot update.
This migration was made in a wrong way. As a result in case if you have running workspaces during hot-update you database may go in 
a state when you can't restart your workspace master.

### Who is affected.
Affected only ws-master who was hot-updated with running workspaces from 6.9.0 to 6.10.0


### How it happened.
table structure before update 6.9.0 to 6.10.0
```
CREATE TABLE che_sign_key (
    id                    BIGINT       NOT NULL,
    algorithm             VARCHAR(255) NOT NULL,
    encoding_format       VARCHAR(255) NOT NULL,
    encoded_value         BYTEA        NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE che_sign_key_pair (
    id                  VARCHAR(255) NOT NULL,
    public_key          BIGINT       NOT NULL,
    private_key         BIGINT       NOT NULL,

    PRIMARY KEY (id)
);
```
after 
```
-- Create new key pair table
CREATE TABLE che_sign_key_pair (
    workspace_id        VARCHAR(255) NOT NULL,
    public_key          BIGINT       NOT NULL,
    private_key         BIGINT       NOT NULL,

    PRIMARY KEY (workspace_id)
);
```
In a normal situation in 6.9.0, we had 1 record in che_sign_key_pair and two records in che_sign_key for the public and private key.
To avoid requirement to stop all workspaces we made 
1. a backup of che_sign_key_pair
```
ALTER TABLE che_sign_key_pair RENAME TO che_sign_key_pair_old;
```
2.  Populate che_sign_key_pair with data for running workspaces and reference for existed keys
```
INSERT  INTO che_sign_key_pair
SELECT r.workspace_id, k.public_key, k.private_key
FROM che_k8s_runtime AS r,
(SELECT public_key, private_key FROM che_sign_key_pair_old LIMIT 1) AS k;
```
3. We removed database  table made on stage [1]
```
DROP TABLE che_sign_key_pair_old CASCADE;
```


This leads as to a situation when:
1. After 6.9.0 -> 6.10.0 hot updated, all running workspaces are referencing to the same pair of public/private key.
2. We lost foreign key from che_sign_key_pair.public_key - > che_sign_key.id and che_sign_key_pair.private_key - > che_sign_key.id
   Now it's possible that records from che_sign_key_pair referencing for non-existed records from che_sign_key.
3. After stopping of the first workspace that was running during hot update records from che_sign_key_pair and che_sign_key was removed.
   Including records that still have references in che_sign_key_pair.
4. After [3] master can't be restored because on inconsistencies between    che_sign_key_pair and che_sign_key tables.





### Quick and durty fix.
1. 
```
DELETE * FROM che_sign_key
DELETE * FROM che_sign_key_pair
```
2. Restart master 
3. Restart existed workspaces

### Can we have general automated fix.
In general no. Because after stopping of the first lucky workspace we lost data from che_sign_key.
And It can't be recovered in no other way except restore from backup.




### What next.
1. In 6.11 we are planning to restore foreign keys between che_sign_key_pair che_sign_key tables. That is why we will develop some procedure that has to be followed.
2. ????
