### ISSUE TITLE
Don't ask Java compiler options during workspace starting

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#11091]
### Description
 
When workspace has status RUNNING we ask jdt.ls to get Java compiler options, but at this time jdt.ls has not ready yet and we got some exceptions in browser console.
On the another way this request (to ask Java compiler options) initiate initialization of jdt.ls, so need to find another way to initialize jdt.ls when workspace has started.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by tsmaeder** [comment]
I'm really not sure we're handling this the right way. The problematic assumption here is that we have access to the user preferences as part of workspace startup. However, stuff managed by a language server is not supposed to be available.
Maybe compiler options should simply not be part of "preferences".

**Comment by tsmaeder** [comment]
Just discussed this with @svor . The exception shown in the browser log comes from org.eclipse.che.api.languageserver.LanguageServerInitializer.initialize(String), line 136 (in master).
The problem is that it treats finding no language server to initialize as an error. However, this is wrong: if you turn off the installer for the php language server, you will not find a language server for PHP files. This is not an error, but an expected outcome of trying to initialize language servers for a particular file. We could handle this either by returning LS capabilities with everything turned off, or we could explicitly return null. I would chose the first option.
