### ISSUE TITLE
Clean up workspace hanging in the starting state when Che master forcefully restarts during the workspace start

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11364]
### Description
Now if Che master restarts when a workspace is starting we might have a situation when the workspace doesn't work and hangs in a starting state.
Next trial of that WS start would clean it up, but we can improve it by automatically clean up of such workspaces.

Related to https://github.com/redhat-developer/rh-che/issues/899, https://github.com/redhat-developer/rh-che/issues/898
### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
There is one more similar issue for `STOPPING` workspaces. Locally it may be reproduced in the following way:
1. Create a workspace.
2. Start a workspace.
3. Set up debug breakpoint at the following line https://github.com/eclipse/che/blob/174e1aea9b5fc68815da7e7a485b6ff51b38ba15/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java#L324
4. Go to OpenShift console and remove Che Server Pod immediately without waiting for the processes 
to terminate gracefully
As result, the workspace is considered as STOPPING forever and it's not possible to remove it or stop forcibly. So, this case it even more critical because the only way to repair a workspace is remove runtime start in database directly.

And this case is even more

**Comment by garagatyi** [comment]
This is a nice way to reproduce the problem easily. With this approach we can also reproduce the bug when Che gets killed on a workspace start.

**Comment by garagatyi** [comment]
@skabashnyuk @ibuziuk FYI
We should consider taking this issue in the next sprint of either team

**Comment by garagatyi** [comment]
@skabashnyuk looks you are approaching the end of your team backlog for the EclipseCon epic. So, maybe you would have capacity to take it.

**Comment by sleshchenko** [comment]
I'm working on the following solution: new Che Server after successful recovering of STARTING|STOPPING K8s/OS runtime will track its status and if status doesn't become RUNNING|STOPPED after a timeout, Che Server will interrupt start or clean up STOPPING workspace resources.
