### ISSUE TITLE
An Editor swapping example ( with Jupyter for example demo and blog post should be enough)

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11383]
### Description
We need to create a demo of swapping different IDEs in Che 7 workspace for the EclipseCon talk.
We can also do a blog post about that.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
There is merged a PR with sample `jupyter` editor https://github.com/eclipse/che-plugin-registry/pull/39
But Workspace Loader is not able to load `Jupyter Editor` correctly just after workspace start and it is needed to refresh a browser page after workspace start
![jupyter-editor](https://user-images.githubusercontent.com/5887312/46295598-253d9700-c5a1-11e8-9694-ae7065024f62.gif)
I think it works in this way because there is no checking and propagating of Jupyter server status and Workspace Loader tries to open it when it is not ready yet

**Comment by skabashnyuk** [comment]
done in https://github.com/eclipse/che-plugin-registry/pull/39
