### ISSUE TITLE
Is it possible to start many che instances on a server?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#115]
Since we didn't find the way to allow users to have their custom workspace, I want to start many che instances on a server, so everyone can get its own che instance to set its own workspace.

But I have a problem that the server has only 4G ram, and there are more than 20 students. If I install che on the server directly, the memory is not enough if I start many che, since to start a tomcat, it requires at least 512M(or more).

Can I resolve this problem by starting the che from docker containers? Is the memory used by docker container dynamic and shared? (Since most of the time the users are just typing code, the real used memory should be less then 4G)

Could you give me some advices on this, or any solution that users can have their custom workspaces?

**Comment by TylerJewell** [comment]
If you are going to give each user their own workspace, recognize that each
workspace is powered by its own Docker container within Che 4.  So if you
allow 500MB for the server itself, and then you give 1 workspace to each
student, you have to spread 20 workspaces across 3.5GB of RAM, so powering
each one with about 175MB of RAM.  It's tiny, but not impossible.

The best way to do this would be to set up Che with 20 workspaces that you
create.  Each workspace will be given its own name, url, and powered by its
own docker container.  You can then size each workspace down to 175MB of
RAM and run Che with about 500MB of RAM itself.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by freewind** [comment]
@TylerJewell thanks for the quick answer, how to "set up Che with 20 workspaces"? Do you mean I need to start 20 Che instances so I get 20 workspaces?

**Comment by TylerJewell** [comment]
1. Start a single che instance.
2. In that instance create multiple workspaces each with their own name.
   They will each get their own unique URL that you can assign to different
   people.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by freewind** [comment]
Is that a feature for eclipse-che 4.x only? Or is available in 3.x?

I'm trying 3.x, but can't find it

**Comment by TylerJewell** [comment]
It's in both, but the way to do it in both is different.

In 3.x, you have to run the /dashboard, which is a JavaScript application
that let's you manage workspaces.  We will have /dashboard added to 4.x
within the next two weeks.

Substantially, you will get better performance and more flexibility with
4.0, but it's pre-alpha, so you may run into some stability issues from
time to time.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by freewind** [comment]
Thanks again, but with the 3.x built-in dashboard, the only thing that related to "workspace" is a "workspace filter". No workspace management, no workspace creation.

Is the "dashboard" you mentioned an external plugin? Do I need to install it?

**Comment by TylerJewell** [comment]
Hi.  Sorry I couldn't response sooner.  It's been one of those days.

You got tripped up because the terminology changes between 3 & 4 and I forget about this.  In Che 3, a "project" is the same as a workspace.  And each project (after you create it) is given its own unique URL.  It's a managed separate entity.  So creating multiple projects through the dashboard (or directly in the IDE) achieves the affect of having multiple objects that you can give to different users.

In Che 4, we use "workspace" as this entity that gets its own special URL and is a single space to do a lot of work.  We do this because a single workspace can have many projects, each with their own project type and modules that can be individually built & run.  So in Che 4 the concept of a workspace is a personal environment for managing projects with a dedicated runtime.  It's a broader definition and more flexible.

For Che 3, in the dashboard, there is a "plugins" view.  This is not what you need.  Ignore this page.  You just need projects.

**Comment by freewind** [comment]
@TylerJewell Thanks so much, I will try 4.x later
