### ISSUE TITLE
Che plugin broker should support ephemeral mode

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11554]
### Description

It is now possible to configure workspace to run in ephemeral mode (i.e. PVs will be of type `EmptyDir`) setting `persistVolumes` attribute to false.

```json
"attributes": {
  "persistVolumes": "false"
}
```

But Che 7 plugin brokers are still started with PVCs (`broker-config-volume` and `claim-che-workspace`). Can we fix that?

**Comment by garagatyi** [comment]
@l0rd Since broker is running in a pod separate from workspace pods how would we deliver plugins into the workspace? Looks like we would need to redesign the flow to achieve this. WDYT?

**Comment by l0rd** [comment]
@garagatyi yes. That's what I am worried about. But in the new theia-plugin-broker we should not need to deliver plugins anymore don't we?

**Comment by garagatyi** [comment]
Actually, we need it. Theia reads metadata from the plugins `package.json` files.

**Comment by garagatyi** [comment]
@benoitf could you comment whether I am correct.

**Comment by amisevsk** [comment]
From a brief look at this yesterday, one issue that has to be addressed before anything else is https://github.com/eclipse/che/issues/11653.

Apart from that, it seems like the task of getting the plugin broker to work with ephemeral workspaces will be rather difficult; since the broker runs separate from the workspace pod, it's impossible to share storage between the two at the moment. After discussion with @garagatyi I've got a few leads and will work towards a proof-of-concept PR to see if we can implement this.

**Comment by amisevsk** [comment]
Opened PR #11657 to address #11653.

**Comment by garagatyi** [comment]
@amisevsk can we close this issue?
