### ISSUE TITLE
The editor tab closes after performing refactor/move action in the editor by context menu

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11697]
**Note:**
 - Actual for openshift assembly
 - This bug is randomly reproduced
 - Related test "ContextMenuEditorTest"

### Reproduction Steps
 - Start default "Java" stack with default "spring" project
 - In the started workspace go to the "org.eclipse.che.examples" package and create "Test1" java class
 - Open the "Test1" java class
 - In the opened editor open context menu and click on  "Refactoring" -> "Move" item
 - In the opened move "Move Item" form select the "org.eclipse" package
 - Click on the "OK" button
 - Pay attention that class has been moved but editor tab has been closed 
 
**Expected behavior:**
The java class is moved and editor tab is still opened

**Observed behavior:**
 The java class is moved but editor tab is closed

**OS and version:**    
Che 6.13.0 ; Fedora 28 ; Chrome 68.0

**Workspace logs:**
[catalina.log](https://github.com/eclipse/che/files/2501510/catalina.log)
[localhost-access.log](https://github.com/eclipse/che/files/2501512/localhost-access.log)

**Browser log:**
[browser.log](https://github.com/eclipse/che/files/2501518/browser.log)

**Comment by SkorikSergey** [comment]
This issue is still reproduced in CHE 6.16.0-SNAPSHOT.

Selenium tests report - https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/462/Selenium_20tests_20report/

Browser and Eclipse CHE network logs - https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/462/Selenium_20tests_20report/webdriver-logs/org.eclipse.che.selenium.editor.ContextMenuEditorTest.checkRefactoring_time-1544996912136-millis.log.

**Comment by vinokurig** [comment]
@SkorikSergey Can it be reproduced manually?

**Comment by SkorikSergey** [comment]
I will check ContextMenuEditorTest test.

**Comment by sleshchenko** [comment]
@SkorikSergey Have you checked `ContextMenuEditorTest` isn't it a time to close it as can't reproduce or finally provide needed info?

**Comment by SkorikSergey** [comment]
This is Che6 issue, so I will close it
