### ISSUE TITLE
Feature Request : Hot deploy for Spring Boot Application

### ISSUE THREAD

**Issue by hsgwd** [eclipse-che/che#11991]
We are developing Spring Boot application.
When we modify application source code for debugging, we need re-build application and restart Web Server.
I hope tool support for hot swap or hot code replace without restarting the Server for debugging Spring Boot appclication.

Thank you.

**Comment by ibuziuk** [comment]
@hsgwd Could you please clarify your use-case ? AFAIK hot-deploy of spring boot could be enabled on the project level by adding dev tools dependency:

>     
>     <dependency>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-devtools</artifactId>
>         <optional>true</optional>
>     </dependency>

in order to make hot deployment work in general there should be a possibility of updating project's classpath [1] (In eclipse it is done automatically (`Project -> Build Automatically`) and in InteliJ one needs to either change a few build properties in IDE or manually run `Build -> Make Project`. And in Che you could do the following:

- add `spring-boot-devtools` dependency
- execute run command
- change the file
- execute build command which updates classpath
- SUCCESS: hot deployment works for run command 

![spring-boot-hot-deployment](https://user-images.githubusercontent.com/1461122/31444126-92e2983c-ae9b-11e7-9971-ac452797f57e.gif)

[1]  https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-restart

**Comment by vinimonteiro** [comment]
Hi,
Sorry, I know this post is closed.
But I was looking for an answer from a different perspective for hot deployment.
When an application is deployed as a .war, I just need to copy the .war file to webapps folder in remote server (ex: Linux) and if Tomcat is configured with hot deployment, the application is reloaded.
I was looking for similar way with a standalone spring boot .jar. Is there a way to just copy the .jar file to a desired location in remote server and automatically have the application reloaded, or even the embedded tomcat restarted (that would also be fine)?
I was looking for some existing tool / library for that. or perhaps I'll need to implement a custom solution.
The application is a REST service. 

Thank you
