### ISSUE TITLE
Browser tab with opened WorkspaceLoader hangs when Che Server is unreachable

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12063]
### Description
Browser tab with opened WorkspaceLoader hangs when Che Server is unreachable.

To reproduce it do the following actions:
1. Start a workspace.
2. Scale Che Deployment down to 0 replicas while workspace is starting.
3. Check Browser Tab: requests number grows very fast because of tries to establish WebSocket connection.
![wsloader-websocket](https://user-images.githubusercontent.com/5887312/49139286-05ed8c80-f2fa-11e8-952f-88264a32d334.gif)
Usually after some time tab is crashed or hanged completely.
![screenshot_20181128_121909](https://user-images.githubusercontent.com/5887312/49145704-0e00f880-f309-11e8-8b85-8f7f114696ba.png)

As a possible solution workspace loader should retry to establish WebSocket connection with some period like 1 second(Dashboard does something like that).

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
I also suffered from that a lot!

**Comment by monaka** [comment]
Same here. And I'm trying to fix for a couple of weeks. There have some unhandled promises and unsuitable recovery code. I think it should be almost re-written.

**Comment by sleshchenko** [comment]
Looks like it is still actual even after merging https://github.com/eclipse/che/pull/12421 =(

**Comment by garagatyi** [comment]
Still actual. Here is screenshot with the trace of component that fires requests
![image](https://user-images.githubusercontent.com/1851863/56802470-caafa500-6828-11e9-89d1-49e870e754b0.png)
And after just a couple of minutes it makes my PC hang, not only browser tab. I couldn't actually close the tab because it was that overloaded that browser no longer responded at all. 
Just a couple of minutes that there are HUNDREDS of THOUSANDS of requests fired (see bottom left corner for the counter)
![image](https://user-images.githubusercontent.com/1851863/56802089-cc2c9d80-6827-11e9-9eff-7c9aaddc5256.png)

**Comment by garagatyi** [comment]
This is really nasty bug that can cause huge confusion for a Che user.  @ashumilova  since @evidolob is out of reach at the moment, could you check if your team could fix this bug? It is long-running bug that caused a lot of troubles for Che maintainers, so fixing it could improve overall performance of the contributors. Thanks!

**Comment by ashumilova** [comment]
Added to High Priority Fixes for the next sprint plan.

**Comment by garagatyi** [comment]
Thanks! I think that @sleshchenko will be way happier when fix lends
