### ISSUE TITLE
Workspace configuration should be saved automatically (remove SAVE button)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#12136]
To improve the UX of editing the workspace configuration - there is a proposal to enable autosave and remove Save button.

**Comment by sleshchenko** [comment]
My strong +1 to do it. Because now save button leads to issues with missing unsaved workspace configuration. It caused by two reasons:
1. Dashboard needs like 1-2 seconds to detect workspace config changes before he shows `Save button`. So, need to make sure that the new approach won't work in the same way.
2. Dashboard doesn't show alert window when there are any unsaved changes.
