### ISSUE TITLE
Run Yaml VSCode plugin as Che7 plugin

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12142]
Package vscode-yaml extension as a Che 7 plugin and publish it to the plugin registry.

Write down the necessary steps as part of Che 7 documentation. I believe @l0rd would know where to put the doc.
Once we have the last vscode languages API's implemented, running vscode-yaml in Theia "should just work" :-)

**Comment by tsmaeder** [comment]
Infos from @NikolasKomonen:


Steps for Theia/lsp4xml:
```
open command palette, search for "deploy plugin id" and insert "vscode:extension/redhat.vscode-xml" it will deploy your vscode extension
```

If it doesn't work:
```
could you try to put vsix file in a folder like /tmp/foo

and before starting theia

export THEIA_PLUGINS=local-dir:///tmp/foo
```
and Command Palette is the F1 key

**Comment by NikolasKomonen** [comment]
Would like to add on, that each VSCode extension has a 'Unique Identifier' which can be found on the marketplace eg: the XML Language server is "vscode:extension/redhat.vscode-xml" and can be found [here](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml) under 'Unique Identifier'

And for YAML it is: "redhat.vscode-yaml"

This identifier is the thing you paste into the 'deploy plugin id' command

**Comment by JPinkney** [comment]
I've been exploring VSCode-YAML in Theia and it looks like a few features aren't working. 

The language server currently supports validation, format, auto completion, hover, document outlining, and automatically loading schemas from JSON schema store. However, it looks like only document outlining is working despite the languages api being implemented for those features IIRC.

The first step to verifying validation, autocompletion, and hover would be to fix https://github.com/theia-ide/theia/issues/3892 so that we are able to set schemas.

For formatting it looks like [this PR](https://github.com/redhat-developer/yaml-language-server/pull/116/files) should fix this

I'm still looking into it but I don't have a direct inclination as to why JSON schemas aren't automatically being pulled from the schema store.

**Comment by invincibleJai** [comment]
first of all thanks for the info, this is what I was looking for 

```
could you try to put vsix file in a folder like /tmp/foo

and before starting theia

export THEIA_PLUGINS=local-dir:///tmp/foo
```


forgive my ignorance, not sure shall i build https://github.com/eclipse/che from source or do i need to build https://github.com/theia-ide/theia in order to achieve it @tsmaeder @NikolasKomonen
