### ISSUE TITLE
Integrating the che-sample with the che-master

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#12153]
### Description
I have created a custom plugin wizard using the given sample and I want to add it to the che-master. This is because I have created a custom stack and i want to integrate it to the che-core-ide-stacks and run with the sample che-plugin-wizard.

Is there a way that i can achieve this?

**OS and version:**    Windows 10

**Comment by skabashnyuk** [comment]
So you want to enable custom plugin or custom stack. Or both?

**Comment by LahiruT94** [comment]
I want to enable both.

**Comment by mkuznyetsov** [comment]
@LahiruT94 if you want to add custom stacks to your assembly, you will need to create two modules:
- a module for your stacks, with identical to structure of `che-core-ide-stacks` (https://github.com/eclipse/che/tree/master/ide/che-core-ide-stacks), where you will place your stacks in a similar fashion.
- a module of repackaging of WS-Master (similarly to how repackaging of WS-Agent happens in Wizard sample), where you will add your artifact with stacks as dependency.
- and make sure to edit `assembly-main` to use your WS Master assebly

**Comment by LahiruT94** [comment]
@mkuznyetsov what do you mean by repackaging? Is it the creation of the module (ws-master) in the same way as in the master? If it is different can you please explain how to do it too. Will be a great help.

**Comment by mkuznyetsov** [comment]
like the same way in Wizard sample, there is a packaging of WS Agent: https://github.com/che-samples/che-plugin-wizard/blob/master/assembly/assembly-wsagent-war/pom.xml
So in it, as dependency there is an original `assembly-wsagent-war` from Che, as well as wizard plugin. And this is what I call by _repackaging_ of WS Agent, which is later used in your `assembly-wsagent-server` instead of original Che WS Agent assembly (and subsequently, your `assembly-wsagent-server` is packaged in `assembly-main`).

So you need to create a similar module in your `assembly` directory, `assembly-wsmaster-war`
which would repackage original `assembly-wsmaster-war`, and add your `your-stacks-module` jar to it.

You may also take a look at this example from our old sample archetypes, where original Che stack module is being replaced with custom stack module
https://github.com/eclipse/che-archetypes/blob/master/stacks-archetype/src/main/resources/archetype-resources/assembly-che/assembly-wsmaster-war/pom.xml

**Comment by LahiruT94** [comment]
Thanks for the help :D
I created the repackaging according to the instructions and also created the stack and linked to the created wsmater-war. When I run the ws-master module it gives me this error.

```
[ERROR] Failed to execute goal on project assembly-wsmaster-war: Could not resolve dependencies for project org.eclipse.che.sample:assembly-wsmaster-war:war:6.15.0: Failed to collect dependencies at org.eclipse.che.sample:che-core-ide-stacks:jar:6.15.0: Failed to read artifact descriptor for org.eclipse.che.sample:che-core-ide-stacks:jar:6.15.0: Failure to find org.eclipse.che.sample:ide:pom:6.15.0 in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of ossrh has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project assembly-wsmaster-war: Could not resolve dependencies for project org.eclipse.che.sample:assembly-wsmaster-war:war:6.15.0: Failed to collect dependencies at org.eclipse.che.sample:che-core-ide-stacks:jar:6.15.0
```

- I have build the `che-core-ide-stacks` module as well

And in the pom.xml file of `assembly-wsmaster-war` , build-helper-maven-plugin doesnt take the generated source directiry correctly.

![1](https://user-images.githubusercontent.com/34393074/49864976-b21a9180-fe29-11e8-8e0e-a7ea136392fe.PNG)

Is that what causes the error? How can i fix it?

**Comment by makandre** [comment]
Hi did you figured this out?  I think you need to exclude the built-in stacks as was pointed out here: https://github.com/eclipse/che-archetypes/blob/master/stacks-archetype/src/main/resources/archetype-resources/assembly-che/assembly-wsmaster-war/pom.xml#L79
