### ISSUE TITLE
Add selenium tests to check that Theia remote/local plugins works 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12160]
### Description
We have Theia remote plugins that are provisioned by a plugin broker. The same broker provisions local Theia plugins added to a workspace. 
We need to test both types of plugins. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@rhopp @l0rd FYI

**Comment by l0rd** [comment]
@garagatyi @rhopp a couple of comments here:

1. I am not sure that selenium/graphical tests are needed here: this is something that can and should be tested using REST APIs rather than graphical UI
2. If we really need it to be a graphical test, the test framework may be cypress.io: it depends on https://github.com/eclipse/che/issues/12204 outcome
