### ISSUE TITLE
Potential memory leak in ProbeScheduler

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12187]
### Description
On one of the Che master instances, I've noticed potentially high memory consumption.
![15 29 58](https://user-images.githubusercontent.com/1614429/49941721-04bc8200-feec-11e8-82f7-5f481f25497c.png)
Heap dump shows one object with ~ 1.2G.
![15 21 16](https://user-images.githubusercontent.com/1614429/49941774-2453aa80-feec-11e8-9c63-72df73ad302a.png)
Deep dive show that this is  15139 TimterTask in ProbeScheduler
![15 22 11](https://user-images.githubusercontent.com/1614429/49941808-3b929800-feec-11e8-974a-571729c6d32e.png)
AFAIK this probes should be ~ NUM of workspecase * num of servers.

From what I can find number of workspaces ~500-700
![15 23 00](https://user-images.githubusercontent.com/1614429/49941894-7399db00-feec-11e8-978d-1dbf30a15f25.png)

The goal of this task is to
- study if that was expected to see TimterTask in ProbeScheduler can take 1.3 G
- Make sure that fields ```probeThread``` and ```httpUrlConnection``` in HttpProbe are not cousing any leak and should/can be dereferenced. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by ibuziuk** [comment]
@garagatyi could you please take a look ?

**Comment by ibuziuk** [comment]
according to metrics there have never been more than 30 running workspaces simultaneously for the last couple of days.

**Comment by garagatyi** [comment]
Problem might be [here](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/ProbeScheduler.java#L213)
It is supposed that cancel task is not needed when we reached this line https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/probe/ProbeScheduler.java#L215.
So we can cancel the cancel task :-).
We can also schedule a purge call on the Timer that processes these tasks to dereference canceled cancel tasks and allow them to be ripped by the GC.

**Comment by garagatyi** [comment]
I edited my previous comment to fix confusion in tasks namign

**Comment by sleshchenko** [comment]
@garagatyi I assume that there is one more problem.
`Task` may be run several times until server won't be available.
Each time when `Task` is run it creates new `TimeoutProbeTask` with new `Probe` inside.
And then `TimeoutProbeTask` cancels `Probe` but not `Task`.
I assume that as result running of `TimeoutProbeTask` has no effect since it will cancel already used probe.
So, `TimeoutProbeTask` should be registered once for each `Task` and cancel `Task` but not `Probe`.

Hope description is clear enough.

**Comment by ibuziuk** [comment]
@l0rd we talked with @skabashnyuk and decided that fixing is crucial for 6.16.0 release, so I'm going to drag it into our sprint backlog

**Comment by l0rd** [comment]
@ibuziuk that makes sense to me cc @slemeur

**Comment by garagatyi** [comment]
@ibuziuk If it is TimeoutTask that bugs the memory then something like this diff should help https://github.com/eclipse/che/compare/master...garagatyi:probeMemoryLeak?expand=1 
But if it is not only that task but something else in addition then we would need to investigate additionally.

**Comment by garagatyi** [comment]
BTW I think that it is intended that probes run even after the start of a workspace - they continue checking the state of servers in a workspace to detect servers failures.
At the same time, all this code is out of date since we would rather use native containers probes in Che 7. But we don't have this feature implemented yet.

**Comment by ibuziuk** [comment]
> BTW I think that it is intended that probes run even after the start of a workspace 

@garagatyi in this case it looks like probes would be created for all workspace marked as "Running" in db, right ? As  I recall ~600 workspaces are recovered every time during rolling update, due to issue like ghost deployments and in this case queue size would be ~ 600 * 3 = 1800 (and according to heap dump it is ~ 15 100). So, it looks like applying the patch and fixing https://github.com/eclipse/che/issues/12207 
would sufficiently reduce the  queue with TimeoutProbeTask size from `~15000` to `~100`

[1] https://github.com/eclipse/che/compare/master...garagatyi:probeMemoryLeak?expand=1

**Comment by garagatyi** [comment]
> > BTW I think that it is intended that probes run even after the start of a workspace
> 
> @garagatyi in this case it looks like probes would be created for all workspace marked as "Running" in db, right ? As I recall ~600 workspaces are recovered every time during rolling update, due to issue like ghost deployments and in this case queue size would be ~ 600 * 3 = 1800 (and according to heap dump it is ~ 15 100). So, it looks like applying the patch and fixing #12207
> would sufficiently reduce the queue with TimeoutProbeTask size from `~15000` to `~100`
> 
> [1] https://github.com/eclipse/che/compare/master...garagatyi:probeMemoryLeak?expand=1

Could you elaborate on how you came up with the number 100? Not sure I'm on the same page. 

> I have not included scheduled cleanup of probe task since this is smth. that should not be required in the general case if probe scheduler works as expected and could be treated like a reinsurance

OK

**Comment by ibuziuk** [comment]
> Could you elaborate on how you came up with the number 100? Not sure I'm on the same page.

@garagatyi ~30 workspaces that are *really* `Running` * 3  probes (wsagent, exec, terminal) = ~100 TimeoutProbeTasks

**Comment by ibuziuk** [comment]
Merged into master and part of 6.16.0 release. Closing
