### ISSUE TITLE
Vendor-friendly White-labeling Che

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#12195]
Related issues:
- redhat-developer/rh-che#1145
- #8421

While in Che <5 its possible to whitelabel, Che 6 and above has overlooked the whitelabeling.

I believe we should allow whitelabeling either through a custom assembly,  just like OpenShift.io Che's style, or through an admin console.

**Comment by skabashnyuk** [comment]
@slemeur @ashumilova can you comment?

**Comment by l0rd** [comment]
@sr229 I have commented on https://github.com/redhat-developer/rh-che/issues/1145 as well (do we need 2 issues by the way?). We are considering reworking the dashboard right after Che 7 release (first part of 2019). I am afraid we won't be able to support dashboard white labeling before that date but this issue is something we need to consider when we will start designing the new dashboard.

**Comment by sr229** [comment]
@l0rd this is initially opened for RH Che since based on my heavily outdated Che docs knowledge, Whitelabeling is possible. This isn't the case for Che 6+ AFAIK. @ibuziuk recommended me to open the issue here since this might need upstream attention.

**Comment by slemeur** [comment]
@sr229 : I have commented on issue: https://github.com/eclipse/che/issues/8421 

Would it be something you would be interested into contributing?

**Comment by sr229** [comment]
@slemeur would be interesting to see how RH Che overrides some things (from what I see, is via a assembly), which I might look into

**Comment by gorkem** [comment]
I am closing this as it has been properly reported on other issues
