### ISSUE TITLE
Dashboard factory: Remove mandatory aspect from workspace.projects[x].type property when creating a factory from a workspace

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#12217]
### Description
In Che dashboard, when creating a workspace, in some case we can end up with a project without any 'type' defined (create a workspace, and import project later).
When creating a factory from this kind of workspace, Dashboard is preventing user to create it because the fields `workspace.projects[x].type` are mandatory.

![capture d ecran 2018-12-17 a 15 55 09](https://user-images.githubusercontent.com/650571/50147902-7e22ee80-02b7-11e9-8e01-0c16c59cdf1e.png)

The type is not mandatory for the user who is not using the GWT based editor (for instance Theia Editor)
GWT based editor will still work (propose to select a type at start up of the factory)

The goal of the issue is to be able to create a Factory from a workspace with 'untyped' projects

**Comment by sleshchenko** [comment]
@sunix Dashboard is not a guy who throws this exception
It is shown by Che Server because the type field is marked as `mandatory`
https://github.com/eclipse/che/blob/57c43ac8cdd7111649414545a6ee9d156392d249/wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/ProjectConfigDto.java#L53
Or I missed something.

**Comment by mshaposhnik** [comment]
Hey @sunix you can close this because it was done in #12232

**Comment by sunix** [comment]
thanks :+1:
