### ISSUE TITLE
Cache and persist workspaces subjects to allow performing workspace operations by service thread when user token is used to access k8s/OS API

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12304]
### Description
We have several cases when workspaces subjects are lost after restart of Che master:
- update of Che
- OOM of Che master 
In these cases, with some auth configuration, Che master is no longer able to stop workspace and cleanup resources.
This happens because of loss of a subject of a user that started a workspace.
Actually, Che needs to cache subjects even when no Che master restart happens because inactivity thread could not perform deployments removal.
All of this leads us to a situation when we need to add a possibility to cache and persist subjects of workspaces.

Here is an example of caching subjects in RhChe https://github.com/redhat-developer/rh-che/blob/master/plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/WorkspaceSubjectsRegistry.java
But it lacks persisting subjects and caches them only on workspace start.

Fixes: https://github.com/eclipse/che/issues/12174, https://github.com/redhat-developer/rh-che/issues/756, https://github.com/redhat-developer/rh-che/issues/755

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@ibuziuk I created issue upstream since now it is actual for different installations of Che. Not sure which team should work on this issue.

@sleshchenko @skabashnyuk FYI

**Comment by garagatyi** [comment]
Updated description with an example of the solution.

**Comment by skabashnyuk** [comment]
We've discussed this issue with @sleshchenko  @garagatyi @ibuziuk @davidfestal 
We think that che should not persist subjects/user token.
Because token can expire and because storing it without encryption is not the safest thing to do.
The main idea is that maintenance operation like inactivity stop or another operation initialized by Che Server without user interaction MUST BE made using special Che Server credentials. It may be Service Account with needed right or configured OpenShift user by specifying Token/Credentials for Che Server.
If Che Server is not configured with such special credentials then maintenance operations should be disabled, otherwise, they won't work correctly
