### ISSUE TITLE
Investigate possible ways of adaptation of Resource API to sidecars machines 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12334]
### Description
Study possible ways to resolve:
- Include sidecars memory into total memory of workspace on dashboard https://github.com/eclipse/che/issues/11801
- Workspace RAM limit doesn't work with sidecar-based workspaces https://github.com/eclipse/che/issues/11424

**Comment by sleshchenko** [comment]
The possible solution that I see for Resource API to make it respecting sidecars memory: add an additional check of available memory after plugin brokering phase before an effective workspace environment start(recipe + plugins containers).
It should works and keep system in consistent state (users won't use more memory than they have) but there are UX issues

1. Client (Dashboard) is not able to tell a user if he has enough memory to start workspace or not.

2. The user may face `no enough memory` error during starting of workspace but not before, like:
- a user starts Che 7 workspace;
- user see that workspace is starting, plugin broker is run and publishes logs about plugins to install, downloading plugins configuration;
- when plugin broker finishes (like after 20 sec up to a couple of minutes) user see that workspace fails to start because he doesn't have enough available memory.

<details>

<summary>To improve a bit UX we may introduce `estimated` memory for workspaces</summary>

**Simpler solution**:
After plugin broker phase store plugins needed memory into workspace attributes, then Dashboard may use this value to check if user is albe to start workspace before start. After updating plugins list estimated memory should be reset, then dashboard may show `-` with tooltip like `workspace should be started to evaluate needed memory`. Note that estimated memory still can contain wrong value since plugin needed memory is stored on third party services (GitHub releases, any file hosting service, etc.) and may be updated there.

**Advanced solution**:
Che Server may cache plugins configuration and use it for checking needed memory before start of workspace. It is harder to implement and it would provide better UX like if two workspace has the same plugins list then we don't need to start each of them to estimate needed memory - start of one is enough. Another workspace may reuse previously cached info for resources checks.
</details>

As alternative solutions:
`memory-limit` may be placed in `meta.yaml` in Che Plugin Registry instead of `che-plugin.yaml`. Then dashboard and Che Server may quickly evaluate memory that workspace needs before start. But I personally see a conceptual issue in puttion plugin configuration part as `memory-limit` to `meta.yaml` file that supposed be contains only meta information of plugin like name, description, puslisher, tags.

Also there is Plugin Brokers Improvements - part 2 [[1](https://github.com/eclipse/che/issues/12398)] issue  that could help to implement good solution for Resource API and sidecars. As result of improvements Plugin Registry will host plugin configuration and then Dashboard and Che Server would be able to check resources limits before start of a workspace. The difference with presious solution that we don't move any plugin configuration attributes to `meta.yaml` file but reworking Plugin Registry in this way may take much more time.

There is a discussion which of ways is the most suitable/acceptable for us. The result will be provided later.

[1] https://github.com/eclipse/che/issues/12398

**Comment by garagatyi** [comment]
The reason why we have this situation is that initially, we decided to allow a user to host plugins configuration anywhere which is powerful but creates technical issues now. 
Reworking plugin registry to cache plugin sidecar configuration is the right way to go on my opinion. But this would be a complex and long-living task.
I like the idea that Serhii provided - we can estimate it on server side after a start of a workspace and update the attribute. This would definitely improve UX comparing to what we have now and implementation on UI would be very simple.

Implementation tips to Serhii:
- JWT sidecar is not part of brokering process and it still consumes memory. We will need to ensure that this and possible other sidecars (that could be brought by a downstream project) are involved in memory calculation
- We expect to mostly use Theia and VS Code plugins which don't have a memory-limit field. Since they can consume a lot of memory (e.g. JDT.LS) we might need to add an ability to put `memory-limit` into meta.yaml file, which might change our strategy with this issue.

**Comment by garagatyi** [comment]
@l0rd @slemeur We don't have a way for a user to set memory-limit for a VS Code or Theia plugin in Che 7. Since plugin can be an LS and it can consume quite a lot of RAM should we address that?

**Comment by sleshchenko** [comment]
The results of the investigation are posted here https://github.com/eclipse/che/issues/12334#issuecomment-458506854
