### ISSUE TITLE
Che 7 plugin: vscode-java

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12436]
Create a Che 7 plugin (following up on  theia-ide/theia#3778) and add it to the plugin registry.
* create a base image for jdt.ls-based tooling
* make a PR against https://github.com/eclipse/che-plugin-registry with a che 7 plugin containing vscode-java

**Comment by svor** [comment]
- The Che7 yaml was prepared: https://github.com/eclipse/che-plugin-registry/blob/java/plugins/redhat.java/0.0.1/meta.yaml;
- As a base image we can use https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-runner-java8/Dockerfile

But we can't test it as a Che plugin because che-theia-remote-extension has old version of Theia (it should be fixed by https://github.com/eclipse/che-theia/pull/42) and we need to update Theia image to the newer version (https://github.com/eclipse/che-theia/issues/39)
