### ISSUE TITLE
[Instruction-Information Request / Not an Issue] Creation of Custom Multi-Machine Stacks and WorkSpaces

### ISSUE THREAD

**Issue by mustafa-yilmaz-zz** [eclipse-che/che#12474]
Hi to all,

In order to install ".NET CORE 2.2 SDK" and "MSSQL Server", for a while, I have been trying to create a custom multi(double)-machine stack by directly copying (duplicating) the existing "BLANK UBUNTU" stack.

I am able to update and run that stack with CentOS 7 inside it (by just changing the expression in the recipe from "quay.io/openshiftio/che-ubuntu_jdk8" to "quay.io/openshiftio/che-centos_jdk8") but I could not create the additional second machine or make both machines run at the same time (when I am able to create-add the second one) so far.

Any help is much appreciated. Thanks very much.

**OS and version:**    CentOS 7
**Eclipse Che version:**    6.16.0

![centos](https://user-images.githubusercontent.com/878471/51434641-10cbfa00-1c77-11e9-8e9a-c90e530496d8.png)

![multimachine](https://user-images.githubusercontent.com/878471/51434642-17f30800-1c77-11e9-9d64-94b428fa7e8d.png)

**Comment by mustafa-yilmaz** [comment]
If needed, here is the "**Raw Configuration** (JSON Definition)" of the stack.  

I probably need to update/change the "**type**" (instead "**dockerimage**" it should be "**openshift**" I think - since it does not already allow me to change it as "**compose**") and "**content**" parameters of the "**recipe**"  but I could not find what to write.

Thanks once again.

------------------------------------

{
  "creator": "226724ee-5a8e-48f5-a115-4ddb6b0f3681",
  "workspaceConfig": {
    "projects": [],
    "commands": [],
    "defaultEnv": "default",
    "environments": {
      "default": {
        "**recipe**": {
          "**type**": "dockerimage",
          "**content**": "quay.io/openshiftio/che-centos_jdk8",
         "contentType": "application/x-yaml"
        },
        "machines": {
          "db-machine": {
            "servers": {},
            "installers": [
              "org.eclipse.che.terminal"
            ],
            "volumes": {},
            "env": {},
            "attributes": {
              "memoryLimitBytes": "1073741824"
            }
          },
          "dev-machine": {
            "servers": {},
            "installers": [
              "com.redhat.oc-login",
              "com.redhat.bayesian.lsp",
              "org.eclipse.che.ls.csharp",
              "org.eclipse.che.ws-agent",
              "org.eclipse.che.terminal",
              "org.eclipse.che.exec"
            ],
            "volumes": {},
            "env": {},
            "attributes": {
              "memoryLimitBytes": "1073741824"
            }
          }
        }
      }
    },
    "name": "default",
    "attributes": {},
    "links": []
  },
  "components": [],
  "description": "Default Blank Stack.",
  "scope": "general",
  "tags": [
    "Blank",
    "Git",
    "Subversion",
    "CentOS"
  ],
  "name": "Blank-CentOS",
  "id": "stack8x4y10ow0l98gtqf"
}
