### ISSUE TITLE
Should we add an ability for plugins of types `Theia, Theia remote, VS Code extension` to bring a volume to a workspace? 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12497]
### Description
We have 4 types of plugins in Che 7:
- Common
- Theia
- Theia remote
- VS Code extension

Only plugins of a common type have sidecars configuration where they can declare volumes.
Other 3 can't declare a volume. 
But for some cases having a volume is quite important to make plugins faster as they would not have to re-download some dependencies or other resources on each workspace restart.
For JDT.LS it is m2 folder.

Should we add an ability for plugins of types `Theia, Theia remote, VS Code extension` to bring a volume to a workspace?

**Comment by garagatyi** [comment]
@tsmaeder @l0rd WDYT?

**Comment by tsmaeder** [comment]
Yes, that is a huge problem: we need .m2 and the eclipse workspace directory to be persistent in order to have reasonable performance at workspace startup.

**Comment by l0rd** [comment]
@tsmaeder your scenario (enable persistance of .m2 and workspace directories) is already working. These volumes can be setup at workspace config level (as in Che 6). We can define a Java stack for example that has the volumes already pre-configured.

@garagatyi proposal is, I think, for allowing to define those volumes at the plugin level. A plugin  developer could decide what folders will be persisted. 

So If my interpretation of this issue is right I consider it a nice UX improvement but we it's something we should think better about before starting implementing it. I mean there is no urgent need for it and we should answer some questions:

- How could a user override those folders paths? 
- How 2 distinct plugins could use the same volume (e.g. .m2)? 
- How can we check if a workspace config is using too many volumes (e.g. oso allows only 2)?

**Comment by garagatyi** [comment]
I don't say it is urgent )
I agree that we need to understand what we want to see in the end before start implementing it. 

FYI even when a user defines several volumes it is Che who controls it, so even on OSIO user can use several volumes which we map to subpaths of a single PVC

**Comment by l0rd** [comment]
> FYI even when a user defines several volumes it is Che who controls it, so even on OSIO user can use several volumes which we map to subpaths of a single PVC

Agree but this volume check could theoretically be done at dashboard level right now. If we allow volumes to be declared at che-plugin.yaml level we would have the same problem we currently have with memory limits...

**Comment by garagatyi** [comment]
https://github.com/eclipse/che/issues/12908 should address this issue
