### ISSUE TITLE
Incorrect buld & run instructions on  http://eclipse.org/che

### ISSUE THREAD

**Issue by kuzp** [eclipse-che/che#125]
Currenly mainpage of the progect says:

``` bash
# <...>
git clone https://github.com/codenvy/che 
git checkout 4.0 
cd assembly-sdk
mvn clean install

cd ..
./che run
http://localhost:8080
```

These script doesnt work for 4.0 at least
1) (minor)  add  "cd ./che" after clonning
2) there is no che.bat/che.sh neither in root nor assembly-sdk
Please, update the mainpage

**Comment by TylerJewell** [comment]
Sorry about this.  A major branch was just merged this morning and haven't had a chance to rewrite the docs.  Will do this afternoon.
But the Che.bat is now in assembly-sdk target sub folder.  

-Tyler

On Wed, Dec 16, 2015 at 12:58 PM -0800, "Paul" notifications@github.com wrote:

Currenly mainpage of the progect says:

# <>

git clone https://githubcom/codenvy/che 
git checkout 40 
cd assembly-sdk
mvn clean install

cd 
/che run
http://localhost:8080

These script doesnt work for 40 at least

1) (minor)  add  "cd /che" after clonning

2) there is no chebat/chesh neither in root nor assembly-sdk

Please, update the mainpage

**Comment by TylerJewell** [comment]
Hi.  Please see updated instructions on home page of eclipse.org/che.  We have rearranged the assembly so that it should be easier to navigate.  After you build from source, the assembly will be located in assembly-sdk/target/eclipse-che<version>/eclipse-che-<version>.  This folder will contain the bundle that will be packaged into ZIP, Jar and other installer.

The executable files are located in the bin\ folder.  

Please note that we have a temporary issue on Windows. You need to do an additional step to configure the system on Windows, as documented here.

https://eclipse-che.readme.io/v4.0/docs/installation
