### ISSUE TITLE
Publish Devfile documentation on http://redhat-developer.github.io/devfile

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12524]
### Description
followup of this comment https://github.com/eclipse/che/issues/12272#issuecomment-457552948
In this issue, we have an experiment with different  https://github.com/eclipse/che/issues/12272 ways to generate documentation from devfile json-spec. The goal of the current issue would be: generate documentation and set up a process of publishing this documentation to http://redhat-developer.github.io/devfile

**Comment by mshaposhnik** [comment]
Here is the first doc version that i build manually after some enhancements in schema:  https://github.com/mshaposhnik/mshaposhnik.github.io/blob/master/devfile.md
There is an idea to host it somewhere, until we establish fully authomated build & deploy,
but need to find right place for it. @l0rd do you think that http://redhat-developer.github.io/devfile is the best place for that? Since it is weakly related with Che and it is may be hard to find it here for users? WDYT?

**Comment by l0rd** [comment]
I think the `devfile` format should be Che agnostic as much as we can. Other projects should use it the same format to define/persist/configure/export their development environment. So it should not be too coupled with eclipse/che.

In eclipse/che we should document how to use a devfile to define a Che workspace. The format description should go in https://redhat-developer.github.io/devfile

**Comment by mshaposhnik** [comment]
Issue is done, first deployments with Ci job is tested and works OK. Next deployments will be performed on each new tag creation.
