### ISSUE TITLE
Support mountSources for non-plugin tools in devfile

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#12554]
The che plugins can now specify whether or not they want to have the root of source directories mounted
to their containers using the `mountSources` attribute (which causes the volume with sources to be mounted into the container on location specified by the `CHE_PROJECTS_ROOT` env variable available to the container).

We should also add this functionality to devfile to support the same mechanism for tools that are not implemented using a che plugin.

- [x] dockerimage tool: This should be easy for `dockerImage` type (all it has to understand is the `CHE_PROJECTS_ROOT` variable). 
- [x] Kubernetes/OpenShift tool: Not sure how to exactly apply it to kubernetes list though. Reference devfile example: https://github.com/redhat-developer/devfile/blob/master/Devfile.yaml

**Comment by sleshchenko** [comment]
It is already implemented for dockerimage tool in the following PR https://github.com/eclipse/che/pull/12649

**Comment by sleshchenko** [comment]
The issue with `mountSources` for k8s/os components is the following:
Currently `mountSources` is a boolean and may be specified for `dockerimage` component only.
For k8s/os component, true/false `mountSources` would mean that it is/isn't needed to mount sources to all containers of component (there can be multiple pods, with multiple containers inside). 
And a user may need more flexibility and it would be nice to provide an ability to specify containers where projects sources are needed. For example, this Devfile[[1](https://github.com/sleshchenko/NodeJS-Sample-App/blob/master/devfile.yaml)] contains k8s component that has two containers - mongo and nodejs-app, and only nodejs-app needs projects sources.
The solution here might be introducing a format that is similar to entrypoints:
```yaml
  - type: kubernetes
    alias: employee-manager
    reference: deploy_k8s.yaml
    sourcesMounts:
    - parentName: podName
      parentSelector:
        labelKey: labelValue
      containerName: nodejs-app
```
The issue with such format - it is not clear how to specify sourceMounts for all containers of a component.

The possible resolutions of this issue that I see:
1. Implement `mountSources: true/false` for k8s/os component and mount projects PVC into all containers of k8s/os component. It's easy to implement and use solution but it may slow down some workspaces since undeeded volumes may be used.
2. Investigate more about a possible format that would give an ability to mount projects sources to all containers or specified ones (I assume with `parentName`, `parentSelector`, `containerName` fields).

@skabashnyuk @metlos @mshaposhnik @l0rd WDYT?

[1] https://github.com/sleshchenko/NodeJS-Sample-App/blob/master/devfile.yaml

**Comment by l0rd** [comment]
@sleshchenko I would not change that now. Your issue makes sense but the solution you propose is still complicated. And I don't consider it urgent because multi-pod workspaces are still not supported currently and for multi-container components we can just continue mounting sources on all containers (or splitted the multi-container component in multiple components with a single container).
