### ISSUE TITLE
Proxy settings for fabric8 client: no_proxy isn't respected

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#12562]
### Steps to reproduce

1. Add ` -Dhttps.proxyHost=squid.corp.redhat.com -Dhttps.proxyPort=8080 -Dhttps.nonProxyHosts='kubernetes.default.svc' ` to JAVA_OPTS for Che master.
2. Start a workspace.
3. No proxy isn't respected and the request to `https://kubernetes.default.svc` goes through `squid.corp.redhat.com` and of course this proxy cannot resolve an internal DNS.

There should be a way to configure https_proxy for wsmaster but make sure it can communicate with kube API.

**Comment by sleshchenko** [comment]
duplicates https://github.com/eclipse/che/issues/12097

**Comment by mshaposhnik** [comment]
So, the following changes needed:
- Use `-Dhttp.nonProxyHosts` instead of `-Dhttps.nonProxyHosts` (see https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html for details, https inherits http property)
- Use value of `KUBERNETES_SERVICE_HOST` variable in non-proxy property, e.g
`-Dhttp.nonProxyHosts=172.30.0.1` 
- Optional - if deployed using ocp.sh, it sets master URL to another value (typically host machine IP), in this case pthe NoProxy should points to it.

**Comment by eivantsov** [comment]
@mshaposhnik thanks, works like a charm!
