### ISSUE TITLE
Automatic saves when editing config pages is too frequent and makes Dashboard page unresponsive

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#12570]
### Description
There were annoying popups appearing in Dashboard in time of changing configuration of workspace.
It made page unresponsive.
![screenshot from 2019-01-31 18-16-07](https://user-images.githubusercontent.com/1197777/52072066-922f6080-2584-11e9-82c6-28150b3015f6.png)

### Reproduction Steps
1. Open Dashboard.
2. Add workspace.
3. Open workspace config tab and start typing...

### Reference
https://github.com/eclipse/che/issues/12136

**OS and version:**    
Eclipse Che 6.17.1.

**Comment by nickboldt** [comment]
Perhaps the issue here could be entitled "automatic saves when editing config pages is too frequent - should not respond to every single keypress" so that the solution would be to "reduce responsiveness of automatic saves when editing config pages" to a more reasonable threshhold (10 characters or 5 seconds) ?

**Comment by dmytro-ndp** [comment]
Good advice, Nick. Thanks!

**Comment by dmytro-ndp** [comment]
Also, we might re-consider automatic save and allow user not to save automatically intermediate changes which could break workspace.
