### ISSUE TITLE
Link "Add my own editor" on the plugins tab

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-che/che#12667]
As a "team lead", I'd like to evaluate Che and see how it can integrate with our team workflows and custom tools. In my case, I have a heavily customized Eclipse IDE package or RCP application that I'd like to be able to leverage as Editor in Che.
When I get to the "Plugins" tab, I see the list of editors. But I see no assistance (at least a link to documentation) explaining me how I can add my own custom editor to that list for my team to be able to use it.
I think Che should provide a "Add my own editor" link which would link to some documentation on how to implement this task.

**Comment by sleshchenko** [comment]
It is related to https://github.com/eclipse/che/issues/12444

**Comment by sleshchenko** [comment]
To add your own editor to plugins tab you should deploy your own plugin registry, I hope all needed information you can find here https://github.com/eclipse/che-plugin-registry.
And then you should configure Che Server to use that registry instead of default one, the corresponding environment variable with the default value is `CHE_WORKSPACE_PLUGIN__REGISTRY__URL=https://che-plugin-registry.openshift.io`
The detailed instructions should be added somewhere in scope of the following issue https://github.com/eclipse/che/issues/12444

**Comment by mickaelistria** [comment]
Note that it's not really a question, but more a feature request to make sure documentation is available (that's #12444 ) and that it's linked from the plugins/editors tab so users can see it's possible.
