### ISSUE TITLE
Feature request: Pascal support

### ISSUE THREAD

**Issue by pakLebah** [eclipse-che/che#12672]
Please add support for Pascal programming using [Free Pascal](http://freepascal.org). I manage a local Pascal community with thousands of members, including students, which desperately need a free app hosting that supports Pascal programming language.

Thank you.

**Comment by azatsarynnyy** [comment]
Hello @pakLebah 
with Che7 you’re able to plug any language services and the developer tooling you want into your workspace thanks to new extensibility model.
Since Che7 provides Theia as one of the code editors, it can be extended with [Pascal VSCode extension](https://marketplace.visualstudio.com/items?itemName=alefragnani.pascal), for example.
[Here's](https://www.youtube.com/watch?v=HbTKDlOL1eo) short demo of installing SonarLint VSCode extension. You can use the same steps to install and evaluate the Pascal extension with Theia in Che7.

**Comment by azatsarynnyy** [comment]
I'm not an expert in Pascal but after trying the extension on my side, at least I see that syntax highlighting and code completion have been added for the *.pas files.
![pascal](https://user-images.githubusercontent.com/1636395/52856230-88812d80-312c-11e9-8949-24d20069fe30.png)

**Comment by pakLebah** [comment]
Could you please test it using [Omni Pascal](http://marketplace.visualstudio.com/items?itemName=Wosi.omnipascal) extension, please? Thank you.

**Comment by l0rd** [comment]
@pakLebah we can test that for you of course and add the extension in the Che plugin registry as well.

At this stage however we are looking for some feedback and early testers of the new feature we are going to introduce with Che 7 (i.e. the ability to use VS Code extensions) and would really appreciate if you could look at the process to install a VS Code extension and provide us some feedback.

**Comment by azatsarynnyy** [comment]
@pakLebah I've tried OmniPascal extension and I see the same features working: syntax highlighting and code autocompletion

**Comment by pakLebah** [comment]
Where can I test it? I'd like to use it in a cloud environment such as on codenvy.io where I just login and the IDE is there ready to be used. I don't want to install whatever beta apps in my personal server just for testing.

**Comment by azatsarynnyy** [comment]
@pakLebah you can test it on https://che.openshift.io
