### ISSUE TITLE
[Traces] Study if there is a way to track container start phases

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12740]
### Description
 Study if there is a way to track container start phases and report it to Jaeger. 
Interesting phases:
- Pod assigning
- Image pulling
- Image pulled
- Container starting
- Container starter
- etc.

**Comment by skabashnyuk** [comment]
@garagatyi  Does you PR https://github.com/eclipse/che/pull/12655 covered something from this issue list?

**Comment by fche** [comment]
This information would best come from openshift itself.

**Comment by garagatyi** [comment]
@skabashnyuk no, but I have an idea how to implement this and where the exact location of the code to change. I wanted to do this as part of my PR but since it was my own cleanups and improvements that wasn't planned for my team I ended up cutting this part from the PR as unfinished. 

@fche yes, we watch pod events on workspace start, so we could add traces when we detect events mentioned in the issue description.

**Comment by amisevsk** [comment]
@garagatyi Agreed on watching pod events -- for the timing stuff from awhile ago I did similar and it worked fairly well.

**Comment by ibuziuk** [comment]
We were not able to take this issue in our Sprint 164 Backlog.

**Comment by skabashnyuk** [comment]
out of date
