### ISSUE TITLE
Java extension doesn't see java-debug extension

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#12755]
### Description
 
When run **vscode-java** and **vscode-java-debug** extensions together as remote plugins, **vscode-java** doesn't see **vscode-java-debug** and it can't grep jdt.ls bundle which provides custom commands.

**Comment by garagatyi** [comment]
If extensions are running as remote plugins they got into different containers. We have an issue to be able to put several plugins into the same container for such a case

**Comment by svor** [comment]
@garagatyi Can you link that issue please?

**Comment by tsmaeder** [comment]
I have discussed this issue a while ago with @benoitf and @l0rd : we need to see the other plugins on disk in order to make the Java debug story work.

**Comment by garagatyi** [comment]
@svor can not find the issue now. Weird

**Comment by l0rd** [comment]
There was a che-dev thread about this (look at "Discussion about the execution of commands inside Theia remote plugins" for more details)

@garagatyi https://github.com/eclipse/che/issues/12395?

@tsmaeder last comment on that issue was a question for you. Please help us setting priority of this issue.

**Comment by garagatyi** [comment]
@l0rd yes, thanks!\
