### ISSUE TITLE
Clean Eclipse IP Log of obsolete dependencies

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#12781]
With the release Che 7 Beta1, it's time to audit the **Eclipse Che IP Log** [1] to remove all the entries that are no longer being used.

[1] https://projects.eclipse.org/projects/ecd.che/iplog/preview

**Why is this important?**

Updating the IP log will help keep the project clean and make it easier to do release reviews. It will also make the Red hat Product Security Team folks happier as they won't need to report CVE issues against Che dependencies that are no longer involved in building Che and downstream products.

**What do we need to do?**

Dependencies with multiple versions should be audited to determine if in fact multiple versions are still NEEDED & USED, or if the old ones can be removed.

For example, here are some duplicate dependencies w/ 2 or more versions in the IP log:

```
* Apache Lucene Queryparser 7.0.1 (and other Lucene bundles)
* lucene-queryparser Version: 5.2.1
  
* Google Guava 27.0.1-jre
* Google Guava Version: 20.0	
* Google Guava Version: 18.0
  
* Apache Tomcat 8.5.35	
* Apache Tomcat Version: 8.0.38	
* Apache Tomcat Version: 8.0.37	
* Apache Tomcat Version: 8.0.32	

* jackson-databind Version: 2.7.7	(and all jackson bundles)
* jackson-databind Version: 2.5.0	
* jackson-databind Version: 2.3.0	
  
* logback-core 1.2.1	(and other logback bundles)
* Logback Core Module (logback-core-1.1.2.jar) Version: 1.1.2	
  
* slf4j-api Version: 1.7.24	
* SLF4J API Version: 1.7.6	
```

Here's a dependency that I think is no longer even used, since we moved from bower to yarn months ago in https://github.com/eclipse/che/issues/10881

```
* bower-angular-aria Version: 1.4.8
* bower-angular-aria version 1.4.7	
```

Downstream issue: https://issues.jboss.org/browse/CRW-163

**Comment by l0rd** [comment]
Thank you Nick for this issue. I think that's important as well but the initial assumption ("With the release of Che 7 Beta1, and the removal of GWT in favour of Theia") is not correct. Che 7 doesn't mean GWT removal:

1. Che 7 goal is to have, for Theia workspaces, at least the same set of features as for GWT workspaces. In other words we won't work on GWT decommissioning until Theia doesn't support all GWT languages and features and we may release Che 7 GA and postpone GWT decommissioning right after it. The reason is that GWT decommissioning may take time and doesn't provide real user value.

2. We want to continue supporting GWT based editor as an alternative to Theia editor. Probably in a separate eclipse repository (as Theia).
