### ISSUE TITLE
Investigate MS C# Plugin Capabilities

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12794]
Read up on (and try)  the [Microsoft VS Code plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) and document what it offers beyond standard language server and debugger capabilities. This would include any custom views, wizards, commands, etc.
Document the findings in this issue.

**Comment by svor** [comment]
The [C# for Visual Studio Code (powered by OmniSharp)](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) extension was tested in VS Code.

There are a few notes which i was detected:

- Need to install [.NET SDK (Software Development Kit)](https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install) to start building .NET apps.
- The extension is using custom output console for logging:
![screenshot from 2019-03-01 11-22-35](https://user-images.githubusercontent.com/1271546/53720624-de164380-3e69-11e9-821e-fc0561354cd5.png)
- The extension provides a task to build the application:
```json
{
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/myapp.csproj"
            ],
            "problemMatcher": "$msCompile"
}
```
-  It also provides debug configurations:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.2/myapp.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}
```
 Just one issue I was faced: property `preLaunchTask` doesn't supported in debug configuration https://github.com/theia-ide/theia/issues/3409.

I also tried this extension as a Theia plugin. Language server functionality works fine without any problems but debugger can't be used because it is licensed to only run in the official version of VS Code.

**Comment by tsmaeder** [comment]
Does the extension provide any views, actions, etc. beyond what is provided by a simple language server contribution?

**Comment by svor** [comment]
I wasn't faced some special/custom views. But the extension registers list of custom commands and provides implementations of some providers:

**Commands:**
- To generate tasks.json and launch.json assets
- Register command for remote process picker for attach
- To pick up project and restore dotne
- To show output
- To restart dotnet ls

**Providers:**
- DiagnosticsProvider	
- DefinitionProvider
- CodeActionProvider
- CodeLensProvider (Run/Debug tests, resolve References)
- CompletionItemProvider
- DocumentHighlightProvider
- DocumentRangeFormattingEditProvider
- HoverProvider
- ImplementationProvider
- ReferenceProvider
- RenameProvider
- SignatureHelpProvider
- FoldingRangeProvider
- WorkspaceSymbolProvider
