### ISSUE TITLE
Che 7 plugin: PHP Debugger

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12795]
Build and test a Che 7 plugin based on https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug

As always, this involves testing the extension inside Theia and filing any issues found and then finding or creating an appropriate image to run the sidecar and creating the plugin metadata for the plugin repo.

**Comment by vrubezhny** [comment]
It is possible to install (and I believe to launch) the `felixfbecker.php-debug` extension in theia together with `bmewburn.vscode-intelephense-client` extension (requires the PR https://github.com/theia-ide/theia/pull/4772 to be applied). 
The extension requires `php`, `php-devel` and `php-pecl-xdebug` to be installed on the system and have `php` to be configured to use `Xdebug` Zend extension in `php.ini`:
```
; Use Zend extension with Xdebug:
zend_extension="xdebug.so"

[XDebug]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
```
However I currently I can't run a test php script in debuger as it complains on not recognized debug type `php` which I've used to create a launch configuration:
```
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
```

**Comment by vrubezhny** [comment]
Well, I can start the `felixfbecker.php-debug` extension and the degugger works on my simple test php file:
![php-debug-in-theia](https://user-images.githubusercontent.com/620781/55802759-2d8b0780-5ad9-11e9-94f7-2812a69c6031.png)

But in order to make it possible I had to modify the `package.json` of the extension by adding `"main": "./out/extension",` attribute into it.
The problem is that the original extension doesn't have neither `main` attribute in its `package.json`, nor the `extension.js` file, and, as such, it is not activated in Theia.

**Comment by davidwindell** [comment]
@vrubezhny I'd appreciate your input on #15740 if you have a moment
