### ISSUE TITLE
Che 7 plugin: PHP Language Server

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12797]
Build a Che 7 plugin based on the VS Code extension chosen as a result of #12796.

**Comment by tsmaeder** [comment]
including testing and building the plugin metadata.

**Comment by vrubezhny** [comment]
As the `https://marketplace.visualstudio.com` is currently the only source for the PHP Intelephense extension `vsix` archives, we face the `VS Code marketplace rate limit error` [1] error when creating the Che7 plugin. 
The issue [2] is reported against `https://github.com/bmewburn/vscode-intelephense` in order to add `vsix` files to the project GitHub `Releases` page [3].

[1] https://github.com/eclipse/che/issues/12840
[2] https://github.com/bmewburn/vscode-intelephense/issues/465 
[3] https://github.com/bmewburn/vscode-intelephense/releases
