### ISSUE TITLE
Launch runInTerminal request in a sidecar container

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#12845]
### Reproduction Steps

When user starts Python debugger it send a `runInTerminal` request which run a command in  Theia container [1]. In case of running Python plugin in a side car it leads to an error, because python isn't installed in Theia container.

**OS and version:**    
* Minikube
* `abazko/che-theia:nightly` (latest che-theia image without python extension)
* `abazko/che-remote-plugin-python-3.7.2:nightly` (image for remote container)
* Python plugin [2]

**Diagnostics:** 

### Is needed for
https://github.com/eclipse/che/issues/12771

[1] https://github.com/theia-ide/theia/blob/master/packages/debug/src/browser/debug-session.tsx#L369
[2] https://raw.githubusercontent.com/eclipse/che-plugin-registry/ab/python/plugins/ms-python.python/2019.2.5433/meta.yaml

**Comment by benoitf** [comment]
hello,

The "container awareness" of terminal has been added to Plugin API mechanism (all the code run in `start()`method is adding the sidecar in which it is running.
Here we have the issue because the client is not using "plugin API"

About solving the issue, for now I don't know yet how to do that because, as you can see, the code calling the terminal
```
https://github.com/theia-ide/theia/blob/master/packages/debug/src/browser/debug-session.tsx#L369
```
run on the client side and not inside a sidecar.
So I don't know how to tell which container pick-up in that case ?

Is there a way to know on this client for which sidecar it is targeting ?

**Comment by benoitf** [comment]
After discussing with Anatolii

When registering debugConfiguration or debugProvider, we should add the CHE_MACHINE_NAME env as an attribute

and when client will initiate the creation of terminal, it will be able to use in Terminal attributes the attribute CHE_MACHINE_NAME (need to find the correct location for that)

then the terminal will be aware on which container to send the request
