### ISSUE TITLE
I want to create a cpp IDE of Che-Theia.

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#12855]
### Description
I would like to create a cpp development environment in eclipse che with theia.
Currently, the base image of theia that is included in eclipse che is Alpine Linux.
Do you have plan to extend the base image to other linux such as ubuntu, debian
or provide a cpp development environment?

For example I would like to use [this](https://github.com/theia-ide/theia-apps/tree/master/theia-full-docker) if possble.

**Comment by l0rd** [comment]
@wonjooncho I am not sure why you want a distinct base image but in Che 7 the language support is provided as a service that runs in an isolated container (sidecar). Hence you can use a dedicated container for C++ dev tools. The Theia container hosts the Che editor component.

**Comment by sunix** [comment]
IMHO, to have cpp support we should have https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools working in Theia remotely running with a dedicated sidecar container (FROM https://hub.docker.com/r/eclipse/che-theia-endpoint-runtime + cpp dependencies)

**Comment by wonjooncho** [comment]
@l0rd Thank you for your advice.
I’m sorry for my late reply due to my long vacation. I am not 100% understood about the ‘isolated container(sidecar)’, but what I want is to establish the latest C++ build environment by installing the part which theia github provides. (see the link image below)
![theia cpp install](https://user-images.githubusercontent.com/31722848/56024652-6df1bc00-5d4b-11e9-9b09-215853ac15cc.JPG)

If establishing isolated container is possible just like you said, could you introduce me how to do? 

@sunix  Thank you for your opinion. I am currently using [https://github.com/eclipse/theia-cpp-extension.git](eclipse/theia-cpp-extension.git). However, I am not sure about how to manifest sidecar.
