### ISSUE TITLE
How to run sidecar containers/plugins that require additional Kube permissions

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#12972]
### Description
I created a basic sidecar container that looks up a Kubernetes service using `kubectl` and tries to talk with it. However, when the sidecar tries to look up the service, it errors out saying:
```
Error from server (Forbidden): services is forbidden: User "system:serviceaccount:workspacexu4oaf59bar3q13r:che-workspace" cannot list resource "services" in API group "" in the namespace "workspacexu4oaf59bar3q13r"
```

This seems to be because the `che-workspace` service account can only list pods, and not services or other Kube resources : https://github.com/eclipse/che/blob/a9b952297af636c8a58099e24cccc9a38929b99d/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesWorkspaceServiceAccount.java#L123 Furthermore, if I modify the `workspace-view` role to add `services` to the list of permitted resources, the sidecar runs fine.

My question is, is there any current way in which I can specify the necessary roles that a sidecar requires? It seems that the Kubernetes plugin doesn't have this issue, so there appears to be some way.

**Comment by garagatyi** [comment]
We limited permissions in the workspace to make Che workspaces run on secure clusters where users are not allowed to change stuff in cluster.
Allowing viewing of services should not be harmful. We can consider how to add this to Che and whether we should make it default or pluggable.
@l0rd @sleshchenko @ibuziuk WDYT?

**Comment by sleshchenko** [comment]
> We limited permissions in the workspace to make Che workspaces run on secure clusters where users are not allowed to change stuff in cluster.

We create a special service account for workspace to make sure that a mounted token provides a minimal set of abilities.
Previously, we relied on a default service account which usually (on test installation) provides more permissions than enough for workspace (`admin` role), which is not good too because every plugin has admin role in a namespace. It is critical when Che Server and workspace, multiple workspaces are run in the same namespace.

`view-services` can be not enough for other cases. 
I think it makes sense to introduce some configuration that would allow defining any role,rolebindings for workspace-service account. But it will be configuration per Che Server but not per plugin.
Now it is possible to configure workspace service account name only https://github.com/eclipse/che/blob/79487708319a2aa68a2ecc4157ae8a1fe2ee5356/deploy/kubernetes/helm/che/values.yaml#L54. If the value is `NULL` or empty - then default service account will be used.

@azatsarynnyy Could you please provide information about token `Kubernetes plugin` uses?

**Comment by azatsarynnyy** [comment]
Hello. It's assumed that the user of the K8s Che Plugin provides its own `kubeconfig` with all the required information for accessing the clusters.

**Comment by l0rd** [comment]
@johnmcollier it looks like you fixed this issue with #12983 (good job by the way!). Should we close it?

**Comment by johnmcollier** [comment]
@l0rd It's partially resolved, I'd say. 

The initial issue I had (unable to list Kube services) is now fixed, but there's still the larger question of how to accommodate custom/additional roles for Che workspaces/sidecars (running in individual namespaces)

**Comment by johnmcollier** [comment]
Closing out now. @l0rd Thanks a ton for merging!!! Sorry for repeatedly following up about it, just wanted to make sure I wasn't forgetting any steps.
