### ISSUE TITLE
[Kubernetes Plugin] Kubernetes: Diff command doesn't open diff view when running in a sidecar

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#13044]
### Description
`Kubernetes: Diff` command of the K8s Tooling plugin shows the difference between a local copy of the object, and that which is deployed to the cluster.

When the plugin running in a sidecar, the command doesn't open a diff viewer.

**Comment by vzhukovskii** [comment]
Investigation shows, that there is an offbeat use case.

Kubernetes plugin invokes native command

```
$kubectl get -o yaml objet/name
```
and saves output into temporary file. Since plugin runs in side car, it has belongs to dedicate file system. Then it calls VSCode plugin api to show diff, as an argument it pass' file path only, then API call goes through the RPC protocol to Theia container and then IDE tries to open diff viewer. First file, that has been opened in editor exists on file system, but the second one, come as an argument from plugin doesn't, because it exists on different file system.

Based on this, possible solution is to share `/tmp` volume across all sidecars and Theia container, but on the other hand this has to be tested to find out whether we can get file collisions.

**Comment by azatsarynnyy** [comment]
See https://github.com/eclipse/che/issues/13614. That may help with reading a file in another sidecar.
