### ISSUE TITLE
problem with eclipse che terminal in ubuntu

### ISSUE THREAD

**Issue by FariborzN** [eclipse-che/che#13073]
Hi
i need to run some codes with eclipse che on ubuntu .
for this code i need a library its name is OpenFpm 
my user name in ubuntu is Fariborz
the library instal and compile on Fariborz (my username)
when run eclipse che and wanna compile my code ny terminal in eclipse che the terminal can not verify and find the path of library because eclipse make another user in ubuntu and run 
see this pic
[https://imgur.com/VFIv6OQ](url)
[https://imgur.com/qTkWv74](url)
[https://imgur.com/mC84Yrt](url)

**Comment by amisevsk** [comment]
Hi @FariborzN 

How are you running Che (i.e. locally in docker, etc.)? 

Che workspaces run inside of docker containers; nothing from your local system is available inside the workspace unless you mount it and your user account is inaccessible by design. The filesystems are entirely separate.

If you would like to compile code, you would need to import it into your Che workspace and compile it there.
