### ISSUE TITLE
Python Extension active failed in eclipse/che-theia:0.5.0 version

### ISSUE THREAD

**Issue by akosyakov** [eclipse-che/che#13072]
Moved from https://github.com/theia-ide/theia/issues/4817

### Description
1.the theia images is eclipse/che-theia:0.5.0, i put the python extension ms-python.python-2019.3.6352.vsix at /default-theia-plugins/ folder and build new theia image.
2. I create a new che workspace based on eclipse/che-theia:0.5.0 with python extension
3. it shows 
![image](https://user-images.githubusercontent.com/31875988/55601564-10320280-5794-11e9-867a-4040065a0c5a.png)
![image](https://user-images.githubusercontent.com/31875988/55601575-1922d400-5794-11e9-9cba-acea6bc4b9ac.png)
![image](https://user-images.githubusercontent.com/31875988/55601605-42436480-5794-11e9-9b8b-6713ae485cbc.png)

The python extension is not working. 
I tried build  che-theia image with dockerfile.But i faced the same issue.
I tried to build theia with source code. And the python extension is worked.
I install python extension with plugin id, and it is worked. i cannot explain why
I add a issue , it fixed at a master version last than 0.4.0, but it not work at 0.5.0,It is kind of emergency, please responded me.

**OS and Theia version:**
theia 0.5.0 

**Diagnostics:**

**Comment by tolusha** [comment]
@113xiaoji

From my understanding there are not  dependencies in che-theia container for Python extension.
It is supposed to work in dedicated container and here is a `Dockerfile` for the image 

https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-python-3.7.2/Dockerfile

**Comment by 113xiaoji** [comment]
@tolusha Thank you for your answer, could you introduce how to use remote-plugin-python-3.7.2 more specificly? I change the 
https://github.com/eclipse/che-theia/tree/master/dockerfiles/theia dockefile, add python environment install, such as python3 pip, python language server and so on ,so i can code in new che-theia, but i cannot use the python extension with new theia version.  Because the python extension is loading all the time , and the python commands do not register。 Hope for your answer

**Comment by 113xiaoji** [comment]
@tolusha Thank you for your answer, could you introduce how to use remote-plugin-python-3.7.2 more specificly? I change the 
https://github.com/eclipse/che-theia/tree/master/dockerfiles/theia dockefile, add python environment install, such as python3 pip, python language server and so on ,so i can code in new che-theia, but i cannot use the python extension with new theia version.  Because the python extension is loading all the time , and the python commands do not register。 Hope for your answer





At 2019-04-05 15:59:32, "Anatoliy Bazko" <notifications@github.com> wrote:


@113xiaoji

From my understanding there are not dependencies in che-theia container for Python extension.
It is supposed to work in dedicated container and here is a Dockerfile for the image

https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-python-3.7.2/Dockerfile

**Comment by tolusha** [comment]
@113xiaoji 
It works in minishift or minikube environment
If you would like to run Python extension in a container, pls follow these steps:
1. Install minishift and deploy Che [1]
2. Build and deploy plugin registry [2]

[1] https://www.eclipse.org/che/docs/che-7/che-quick-starts.html#using-minishift-to-set-up-openshift
[2] https://github.com/eclipse/che-plugin-registry/blob/master/README.md

Here is public channel, you are welcome to ask any questions:
https://mattermost.eclipse.org/eclipse/channels/eclipse-che
