### ISSUE TITLE
Provide curated list of containers to run tasks

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13390]
### Description
When running a tasks, the user is asked on which container to run the tasks while he has not idea of what are all the containers (especially those for plugins).

<img width="793" alt="Capture d’écran 2019-05-22 à 12 13 00" src="https://user-images.githubusercontent.com/1636769/58167261-d5c0ee00-7c8b-11e9-931c-93285115ff27.png">

We should currate the list of containers where to execute the tasks to only the user's runtime ones and use a similar mechanism than for opening a terminal.
 
<img width="768" alt="Capture d’écran 2019-05-22 à 12 19 34" src="https://user-images.githubusercontent.com/1636769/58167277-e1141980-7c8b-11e9-8eb2-faf41ea9d6df.png">

Update: behavior should be the same when select container dialog appears.

**Comment by vzhukovskii** [comment]
@slemeur, we can't assign hotkey to switch display machine list, due to following flow. Hotkey assigns to specific command, command then executes code. With new terminal item this is easy to implement. There is a boolean flag which just switch displaying of elements. But with machine list for the exec commands its a bit tricky. Tricky in that way, that we first call run task menu item, task list may contains of not only _che_ task type, but _shell_ and _exec_. Then, when user pick che task, we show machine list. We can assign hotkey to show the list of machines and switch display, but we need to update the whole mechanism of displaying task list. Because theoretical, user can call hotkey from any place and machine list will be showing. I think it will be not obvious for the end user.

So I propose a bit different approach. At first step show to user non-tooling containers and display the option to show all containers.

![machine-picker](https://user-images.githubusercontent.com/1968177/61118789-27bf0c80-a4a2-11e9-9b35-9813bfe7ada6.gif)

**Comment by sunix** [comment]
@l0rd @vzhukovskii @vparfonov this is not part of the endgame anymore right ?

**Comment by vzhukovskii** [comment]
@sunix this issue is not mentioned in endgame plan

**Comment by slemeur** [comment]
@vzhukovskii : How the issue is related to hotkeys? I think you are mis-interpreting the description.

Also, I'd like to understand why this issue has been added to the sprint, while it's not part of the endgame and we have a busy list of other issues to address...
cc @vparfonov @l0rd

**Comment by vzhukovskii** [comment]
> How the issue is related to hotkeys?

_and use a similar mechanism than for opening a terminal_

In opening terminal when user opens machine picker he can see only user runtimes and after pressing the hotkey, he can observe all containers. So I've tried to align the same mechanism and for the task execution part.

> I think you are mis-interpreting the description.

It's not a problem to update the behavior. Should we display the only user's runtimes and not display plugin containers?

**Comment by vzhukovskii** [comment]
I propose such flow to display containers. There is the same flow to separate user developer containers and tooling containers. The same flow is used when user call action `Find command`:

When `Find command` is executed:
<img width="826" alt="Снимок экрана 2019-11-04 в 14 34 15" src="https://user-images.githubusercontent.com/1968177/68121756-37f76d80-ff11-11e9-880a-317662f47455.png">

When new terminal opens:
<img width="873" alt="Снимок экрана 2019-11-04 в 14 34 23" src="https://user-images.githubusercontent.com/1968177/68121764-3f1e7b80-ff11-11e9-9d89-38a8cd013e44.png">

When new task starts:
<img width="848" alt="Снимок экрана 2019-11-04 в 14 34 41" src="https://user-images.githubusercontent.com/1968177/68121773-45145c80-ff11-11e9-8ea2-1d34d172645b.png">

**Comment by vparfonov** [comment]
@slemeur Please take a look

**Comment by slemeur** [comment]
Good for me!
