### ISSUE TITLE
When editing the pre-defined tasks, all tasks should be displayed in the tasks.json file

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13392]
### Description
When the user is going to edit one of the pre-defined tasks, but the tasks.json does not exist, there is a new tasks.json that is created with only the selected task added to the file. 
This behavior is confusing, the user would expect to see all the tasks that are available when doing "Run tasks".

We should make sure that when ever the user is going to edit the tasks, there is only a single source to edit all of them - so this way, the user knows where to go to find all of them and it stays consistent.

**Comment by RomanNikitenko** [comment]
@slemeur 
All Che tasks are available on plugin side, so we can copy them to tasks.json file.  
However we need [add plugin API](https://github.com/theia-ide/theia/issues/5342) to have ability copy all tasks provided by plugins to tasks.json file.
Is it OK for you if I copy all Che tasks within this issue and in a separate issue tasks provided by plugins (when we have [required API](https://github.com/theia-ide/theia/issues/5342))?

**Comment by slemeur** [comment]
When you say "copy" how do you envision managing the task from the plugin and its copy?
- Is it overhidding it?
- Is it duplicating it?

(Ack for the API)

**Comment by RomanNikitenko** [comment]
Actually, I think we don't need to copy the tasks from all plugins to tasks.json file.
It makes sense to provide Che commands as 'configured' tasks (copy them to tasks.json) because we want to provide way how user can edit them and sync with devfile.
Why we need to copy all tasks from plugins to tasks.json file - it's still question for me.
User has ability to click on 'configure' icon of any task and the configuration will be copied to tasks.json file, then user can edit it.

About overriding/duplicating.
When I added ability to configure tasks, I provided behavior that 'configured'(from tasks.json file) tasks have higher priority than 'detected'(from plugins) https://github.com/theia-ide/theia/pull/4714#issue-264432073.
So, for example, we have a task which comes from plugin. User wants to customize it => go to 'Run Task' menu, click on 'configure' action => the configuration is copied to tasks.json file => user edits it. From now on,  'Run Task' menu displays only overrided task - 'configured' task (from tasks.json file).
