### ISSUE TITLE
Che 7 stacks should use version "latest" of plugins

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13426]
### Description

That's about updating the devfiles in the che-devfile-registry to use version `latest` of the plugins. That's important for at least the following reasons:

- Users will expect that the latest and greatest versions of the plugins are used in the default stacks
- We don't want to update the stacks everytime there is a new version of a plugin
- We should test our stacks against the latest versions of plugin as soon as possible (fail fast)

**Comment by ibuziuk** [comment]
@l0rd @skabashnyuk just to make sure we are on the same page with this task. Atm, there is a script [1] for the latest folder (version) generation on the plugin registry side and it is expected that "latest" version would be defined explicitly in the `plugins` attribute. The PR [2] for falling back on the "latest" version if no version is specified was considered to be optional for Che 7 GA since it was highly-conflicting with https://github.com/eclipse/che/pull/13297 

Please, comment if there are any concerns with the current approach

[1] https://github.com/eclipse/che-plugin-registry/blob/master/scripts/setup_latest_dirs.sh
[2] https://github.com/eclipse/che/pull/13414

**Comment by mshaposhnik** [comment]
#13297 is merged so i see no much problems to rebase 13414 on top of it (it even should became simpler)

**Comment by ibuziuk** [comment]
we can potentially take it to the next sprint and try to finalize by GA, but our capacity is pretty low atm, so it mainly matter of priority. @l0rd wdyt should we work on finalization of #13414 in the upcoming sprint or can we postpone it after GA and potentially improve the parsing of the attributes to make is less error-prone - https://github.com/eclipse/che/issues/13385  ?

**Comment by l0rd** [comment]
@ibuziuk let's postpone after GA
