### ISSUE TITLE
User should be automatically authenticated on OpenShift in his workspaces

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13449]
### Description
When Eclipse Che is deployed on OpenShift, he should automatically be authenticated from his workspaces to his OpenShift namespace.

### Linked Issues
https://github.com/redhat-developer/rh-che/issues/541
https://github.com/eclipse/che/issues/13447

**Comment by sleshchenko** [comment]
Just wanted to mention that previously it was done using OSIO installer https://github.com/redhat-developer/rh-che/blob/master/plugins/fabric8-multi-tenant-manager/src/main/resources/installers/1.0.0/com.redhat.oc-login.script.sh
And in Che 7 installers mechanism is deprecated. It is needed to find another way to implement it.

We are able to mount service account token with `namespace admin` rights, but not on every installation user is able to create such. And even if he has - he will have a token only to current namespace but not all his workspaces.

AFAIK There is no way to grant workspace access to all user's namespace except injecting user token( but it's needed to find a proper way to do it), but it may expire (for OSIO it's not so critical since expiration time is very long, but in general for any OpenShift installation it may be an issue).

Also, wanted to clarify: in which containers of workspace it should be done? In everyone that has `oc client`?

**Comment by slemeur** [comment]
Will be solved by https://github.com/eclipse/che/issues/15261
