### ISSUE TITLE
'?' folder is created when building console-java-simple project using java-maven Che 7 stack

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#13451]
### Description
When `console-java-simple` is built in **non-Ephemeral** namespace against java-maven Che 7 stack '?' folder with `m2` folder is created:

![image](https://user-images.githubusercontent.com/1461122/58641009-00055200-8303-11e9-90f2-c5ff9e5fc1eb.png)

### Reproduction Steps
Create Non-Ephemeral Che 7 java-maven workspace with `console-java-simple` and build it with mvn.

ERROR: '?' folder with `.m2` folder 

**OS and version:**    
7 beta 5

**Comment by amisevsk** [comment]
The issue here is that OpenShift runs containers with a (mostly) random UID. Since this UID is not defined at container creation time, it does not have an entry in `/etc/passwd` and so *any* program that depends on getting a username will have some sort of issue.

In the case of maven, the issue is that it cannot figure out where to put the `${HOME}/.m2` directory.

**Comment by ibuziuk** [comment]
PRs sent:
- https://github.com/eclipse/che-devfile-registry/pull/6
- https://github.com/eclipse/che/pull/13453

**Comment by ibuziuk** [comment]
We need a PR for che.openshift.io and than can close this issue

**Comment by ibuziuk** [comment]
rh-che PR https://github.com/redhat-developer/rh-che/pull/1448

**Comment by ibuziuk** [comment]
Closing as done
