### ISSUE TITLE
Clarify names of default stacks

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13592]
### Description
![Capture d’écran 2019-06-20 à 14 13 20](https://user-images.githubusercontent.com/1636769/59848579-cfdf2b00-9365-11e9-8559-e38292bc5592.png)

- We should remove from the name "Theia IDE". the default stacks are all provided with Theia IDE.
- Also there are 2 pythons stacks. I would rename the one for Django just being "Django"

### Reproduction Steps
**OS and version:**    
Che 7 RC2

**Comment by themr0c** [comment]
I was about to create the same issue :). I would add that the Che 7 mention is maybe not necesary in "Apache Camel based projects on Che 7".

**Comment by themr0c** [comment]
Additionally (because it appears in the same screen at Workspace creation), I would suggest to unify the descriptions of the Sample projects. Would "A simple project in <lang>" make sense?

On 7.0.0-RC-2.0 we have:

- A blank project example.
- A Ceylon 'Hello World' project example that runs on all supported backends.
- The app will print Hello World to the console.
- Simple Ruby Project.
- Simple Go Hello World.
- Simple Rails Project.
- A simple Hello World in C.
- ASP.NET Core backend implementation for RealWorld https://realworld.io
- A simple .NET 2.0 web sample.
- Go Real World Sample.
- Go Web Sample.
- Simple Go Hello World.
- A simple Che extension that brings a new UI menu item
- A simple Che extension that brings a new UI menu item and REST service
- A hello world Java application.
- Fuse booster.
- Simple Android Hello World.
- Simple Android Project.
- Spring Boot Guide to build a RESTful web service
- Quickstart to demonstrate OpenShift health probes working with Spring Boot Actuator
- Quickstart to expose a REST Greeting endpoint using SpringBoot and Apache Tomcat in embedded mode
- Booster demonstrating health checks and recovery
- HTTP Vert.x Booster
- Petclinic app using MySQL as persistent storage
- A basic example using Spring servlets. The app returns values entered into a submit form.
- Quickstart to expose a REST Greeting endpoint using Wildfly Swarm
- Angular PatternFly Starter Project.
- Express app with Postgres database
- Simple NodeJS Project.
- Yeoman Starter project.
- Exemplary real world backend API built with Laravel https://realworld.io
- Code for the simple PHP and MySQL database app tutorial. https://www.taniarascia.com/create-a-simple-database-app-connecting-to-mysql-with-php/
- Symfony Demo Application https://symfony.com/
- A hello world PHP script to deploy to GAE.
- A hello world PHP script.
- Simple Python3.5 Project.
- Django Real World Example.
- Python Hello World Project.
- TypeScript greeter sample

And then the list could be ordered?

**Comment by themr0c** [comment]
Another note: "Simple Python3.5 Project." is not an accurate description, the sample is based on python 3.6. I see 'pulling image "centos/python-36-centos7:1"'.

**Comment by sparkoo** [comment]
I've created PR for this. Let's discuss details there https://github.com/eclipse/che-devfile-registry/pull/25

**Comment by sparkoo** [comment]
@themr0c what about sample projects? Are there even gonna be there? Or are they deprecated and will be removed? As it is now, it does not make much sense to e.g. choose .NET stack and then add java sample project.

**Comment by sparkoo** [comment]
@slemeur ^^

**Comment by themr0c** [comment]
@sparkoo I don't know. @slemeur should definitively know better than myself.

**Comment by slemeur** [comment]
You are right. The default stack will be provided with a sample project:
https://github.com/eclipse/che/issues/13529

It is still valuable to cleanup the description of the sample project as it will be displayed on the dashboard.

**Comment by ashumilova** [comment]
Sample's description is displayed this way just for the additional information: 
![Screenshot from 2019-07-08 12-23-44](https://user-images.githubusercontent.com/1611939/60799171-52942280-a17b-11e9-8cfd-95cb7a947690.png)
Project object in devfile doesn't have any description field - so the description displayed for samples is not going to be set for project created from it.

**Comment by skabashnyuk** [comment]
Due to the changes that are coming with samples https://github.com/eclipse/che/issues/13529
https://github.com/eclipse/che/issues/13665 I think cleaning up their names deserve for a separate issue.

**Comment by sparkoo** [comment]
I've created an issue for that. See #13793.
