### ISSUE TITLE
"/project" is not mount into the runtime container of the default python stacks

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13594]
### Description
All default stacks are provided with runtime container.

In this runtime container the "/project" is not mount. So the default tasks are also not working.

![Capture d’écran 2019-06-20 à 15 10 05](https://user-images.githubusercontent.com/1636769/59851686-88f53380-936d-11e9-916a-09991468769a.png)

### Reproduction Steps
- Create workspace from stack "Python"
- Add project "console-python"
- open a terminal in "python" runtime container
- check how to 

**OS and version:**    
Che 7 RC 2

**Comment by sleshchenko** [comment]
@slemeur As far as I see console python Devfile contains another project https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/python/devfile.yaml#L10
Maybe outdated stack from stacks.json is used? Can you made a screenshot of Dasboard when you choose this stack?

**Comment by slemeur** [comment]
![Capture d’écran 2019-06-20 à 16 11 43](https://user-images.githubusercontent.com/1636769/59855875-1fc5ee00-9376-11e9-8fa4-c410248e4df9.png)

**Comment by sleshchenko** [comment]
@slemeur Ah, I got it. Actually, projects volume is mount but you created a workspace with project that you choose from `samples.json` but not that is provided by devfile. And project name is hardcoded in command, it's why it's failed.
As far as I know, Ann is reworking UI: UD should not propose projects from `stacks.json` but it should show some info about project that is built-in. See Mario's mockup https://github.com/eclipse/che/issues/13529

**Comment by sleshchenko** [comment]
Note if you not chosen a project - then workspace will be created without projects. Ann's fixing it as well.

@slemeur I see two issues here, would you reformulate this issue/create new:
- project from devfile is not respected by UD during workspace creation;
- commands in python devfile have hard-coded project path, replace it with macros it if is available;

**Comment by l0rd** [comment]
Looks related to https://github.com/eclipse/che/issues/13454

**Comment by sleshchenko** [comment]
I see it's more related to `${current.project.path}` https://github.com/eclipse/che/issues/13636

**Comment by amisevsk** [comment]
@slemeur Aside from #13636, can we confirm that this issue is still actual?

Checking the current `eclipse-che/nightly-centos` image with https://che-devfile-registry.prod-preview.openshift.io/ as the devfile registry gives a functional Python workspace (with the `python-hello-world` project). The other project (console-python) appears to not be available in the default UI.

As it stands, I've created https://github.com/eclipse/che/issues/13936 to track the fixes coming from what @sleshchenko described.

The default command in the devfile is still hard-coded to `"workingDir": "${CHE_PROJECTS_ROOT}/python-hello-world"`, but that may be acceptable for 7.0.0 (and unavoidable, since #13636 is currently not prioritized for 7.0.0)

**Comment by l0rd** [comment]
Closing it because we are not using `sample.json` anymore and this issue should be solved now.
