### ISSUE TITLE
Default java-maven stack terminal lack of functionalities

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13602]
### Description
The terminal is not providing any completion and capabilities that are usually provided.

![terminal-missing-features](https://user-images.githubusercontent.com/1636769/59903225-b63ef180-9400-11e9-8472-10a70a3917b6.gif)

- Impossible to do "up" key to get the previous command

### Reproduction Steps
- Create a workspace with java-maven
- add project spring-boot-http-booster
- get a terminal in the container "maven"
- try to navigate through the files and use "tab" on your keyboard to get completion

**OS and version:**    
Che 7 RC 2
minikube with chectl

**Comment by sleshchenko** [comment]
It caused by default shell in container which is `sh`. 
@slemeur You can type `bash` and then you should get autocompletion, it worked for me.
But thanks for reporting of this issue, I agree that it's not good UX and it would be better if we configure default shell to bash, not sure it is possible with `dockerimage` or `kubernetes` component without modifying official maven image. It needs to be investigated.
