### ISSUE TITLE
Default projects provided with sample stack is not building 

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13608]
### Description
All default projects and samples provided with Che out-of-the-box must be building properly without having the user doing anything more than just invoking the task "Build"

<img width="1758" alt="Capture d’écran 2019-06-21 à 11 02 40" src="https://user-images.githubusercontent.com/1636769/59911502-58b4a000-9414-11e9-8041-9c0e0bcfaebc.png">

### Reproduction Steps
- Create workspace from the stack "java-maven"
- Add the project "spring-boot-http-booster"
- Open Command palette
- Invoke task "maven build"
- See outputs of the build failure

**OS and version:**    
Che 7 RC 2 on minikube 1.1.1 with chectl

**Diagnostics:**

**Comment by l0rd** [comment]
Looks related to https://github.com/eclipse/che/issues/13454

**Comment by ibuziuk** [comment]
@l0rd @slemeur I believe the issue is fixed due to the following fixes:
- `arbitrary-users-patch` for images used in devfiles
- UD changes related to 1:1 mapping between devfile and project

Basically, now when `java-maven` stack is selected on the workspace creation screen the only default project is `console-java-simple` which builds & runs just fine (verified against OpenShift v3.11)

![image](https://user-images.githubusercontent.com/1461122/61730116-02bb7b00-ad79-11e9-85a8-9b68edc39c05.png)

**Comment by slemeur** [comment]
Excellent! This issue can be closed
