### ISSUE TITLE
che-theia minibrowser preview view should allow the user to edit the URL

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13616]
### Description
Having a devfile that setup an developer workspace environment for a web application,

When the user is running the app, Che-theia is proposing to expose the port and open the url in the theia mini browser. However user can't edit the path.

### Reproduction Steps
I face that issue running my Quarkus demo on minikube with this devfile: https://github.com/sunix/che-quarkus-demo/blob/master/devfile.yaml

![Selection_304](https://user-images.githubusercontent.com/650571/59942914-34cb7b80-9461-11e9-8f6b-7b71c52c31e8.png)

**Comment by sleshchenko** [comment]
I faced the same issue with Django sample: django requires `admin` path to access console and since Devfile does not support preview URL that we used to have (see deprecated samples.json https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json#L1525) and it's not possible to edit preview view - it's impossible to access Django within Theia, it's needed to open it in new browser tab and edit path there.
