### ISSUE TITLE
Improve the way of storage runtime info for Che tasks

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#13722]
Currently runtime info for Che tasks is available till we refreshing the page.
I guess the problem is related to how we store runtime info.
[CheTaskImpl](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts#L15) is created every time the page is reloaded, so task map is empty for this case and lose runtime info for Che tasks.
So we should consider another way of storage.

**Comment by l0rd** [comment]
@RomanNikitenko @vparfonov this is an issue created 6 months ago. Is it still relevant? Is it related to stable Che-Theia (branch 7.0.0) or to upstream Theia (master branch)?

**Comment by vparfonov** [comment]
> @RomanNikitenko @vparfonov this is an issue created 6 months ago. Is it still relevant? Is it related to stable Che-Theia (branch 7.0.0) or to upstream Theia (master branch)? Is it related to #14098?

Yes, it sill actual, but we can't fix it for 7.0.0 so we will focused on master branch

**Comment by sunix** [comment]
Reading at the description

> so task map is empty for this case and lose runtime info for Che tasks.

it sounds like a bug. But I don't think i have faced that one so far. What is the impact for the user ?

**Comment by vinokurig** [comment]
`taskMap` is a map with `Task` objects. `Task` contains handlers:
```
export interface Task {
        /** Terminates the task. */
        kill(): Promise<void>;
        /** Returns runtime information about task. */
        getRuntimeInfo(): TaskInfo;
    }
```
that are implemented in the plugin side by registering a runner with task implementation:
`async registerTaskRunner(type: string, runner: TaskRunner): Promise<Disposable> {` :
https://github.com/eclipse/che-theia/blob/b94aadc789b15bef3d85ea9dd1fb3d154ff28cd3/extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts#L23.

We store Task implementation in the plugin side because we cannot transfer handlers to theia side. We transfer only the handlers id but the implementation is set to `taskMap` in the plugin side.
The problem is that the plugin side ([CheTaskImp](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts#L15)) is reloaded each time the browser refreshes and the map is cleaned. According to the current Plugin-Api model it is impossible to save functions in the plugin side, but the handler ids are registered in the theia's backend, so when the page is refreshed `taskMap` in the `CheTaskImp` is cleaned but it can receive requests https://github.com/eclipse/che-theia/blob/b94aadc789b15bef3d85ea9dd1fb3d154ff28cd3/extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts#L41-L54 from theia's backend.
@benoitf @evidolob **WDYT?**

**Comment by sunix** [comment]
What is the impact for the user ?
or is it just refactoring ?

**Comment by vinokurig** [comment]
When we run a long task that is implemented in the plugin, we cannot get it's run-time info or stop it after page refresh

**Comment by vparfonov** [comment]
@sunix Impact fro user described in initial comment for issue:
User will lost context for running task if refresh the page

**Comment by sunix** [comment]
OK @vparfonov i am a user, I run the task and I have refreshed the page and "lost context". What does it mean ?
Does it mean that I won't see the previously run tasks terminals, or content ? or what ?

**Comment by vinokurig** [comment]
@sunix user will not be able to stop the task

**Comment by vparfonov** [comment]
@benoitf @evidolob Any ideas, looks like we need your help

**Comment by sunix** [comment]
`Ctrl-c` ?

**Comment by RomanNikitenko** [comment]
@sunix 
[The comment](https://github.com/eclipse/che/issues/13722#issuecomment-520437999) describes the cause of the issue:
> According to the current Plugin-Api model it is impossible to save functions after closing the plugin in the plugin side

So, this is not question of **way** how we are going to stop the task, this is question of **architecture**.
