### ISSUE TITLE
feature request:  support of .net core enviroment. (dnx is deprecated)

### ISSUE THREAD

**Issue by mercuriete** [eclipse-che/che#1373]
In the github page of dnx they said that is deprecated:
https://github.com/aspnet/dnx

the new toolkit for developing ASP.NET application is .NET core
https://github.com/dotnet/cli

There are some instruction to know how install .NET core
https://www.microsoft.com/net/core#ubuntu

and the docker image is:
https://www.microsoft.com/net/core#docker
https://hub.docker.com/r/microsoft/dotnet/

tutorial for create an aspnet core webapp:
https://docs.asp.net/en/1.0.0-rc2/getting-started.html

tutorial for create a simple MVC aspnet core webapp
https://github.com/aspnet/cli-samples/tree/master/HelloMvc

Your work is awesome!

PS: do you accept pull requests?
how i could do a template of workspace to do a pull request?

**Comment by TylerJewell** [comment]
Hi @mercuriete - yes we absolutely love to accept pull requests.  If you'd like to work on our standard .NET stack and the templates that are embedded within, we'd very much appreciate the update.

A few pointers on how to get started:
1. We talk about the steps you need to take to add in custom stacks / templates to che in the CUSTOMIZING.md page that is in the root of the repository.  Stacks and templates are just JSON files, so you can configure the system to use the updated configuration.
1. It seems that the technology that goes into Che's standard .NET Docker image may be out of date. Due to certain configuration issues, those Dockerfiles are in github.com/codenvy/Dockerfiles, so you would need to issue a matching pull request to that repository.  All of the files in both repositories are EPL licensed.  We will eventually move all of the Dockerfiles into the Che repository, but there are certain hurdles that we have to undertake.  When our standard dockerfiles are added into that repository, our CI systems build them and place them into the Codenvy Docker Hub repository, which makes them accessible from the stacks that you write above.

Tyler

**Comment by mercuriete** [comment]
ok, im am trying to create a Dockerfile to do a pull request to codenvy/dockerfiles :)
please leave this bug/ticket open until me or someone else do the work :)

As i stated before, eclipse che is amazing and your work is amazing.

**Comment by TylerJewell** [comment]
What is your use case that you are designing for?  We like to hear stories from the community.   I see that you built a cloud 9 compose file - are you comparing the products?

**Comment by mercuriete** [comment]
I'm a java developer and I am trying to learn devops tools.

My use case is just for fun or learning.

I wanted to create a small ASP.NET application in order to learn .NET running in linux.
But i read today that microsoft releases the new tool called dotnet (dotnet core) and I want to get working inside eclipse che.

I'm not comparing products, I am only trying to understand how containers works.
I just learn the existence of docker a month ago. And i want to learn docker creating something useful for other people.

By the way, i finished doing the dockerfile, i will create the pull request :)

**Comment by TylerJewell** [comment]
Really fantastic .  Please make sure you fill out the cla for eclipse before doing the pull request.  Our engineers may also have standards checks for you.

**Comment by mercuriete** [comment]
https://github.com/codenvy/dockerfiles/pull/40

**Comment by mercuriete** [comment]
https://github.com/codenvy/dockerfiles/pull/41

**Comment by ghost** [comment]
Merged! Thanks for your contribution. I have added a few minor things, but otherwise the Dockerfile looks beautiful :)

**Comment by mercuriete** [comment]
@eivantsov Thanks! It was my first time doing a pull request.
I'm glad that you merged my code :D
