### ISSUE TITLE
Clarify names of Sample projects

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#13793]
### Description
Follow up of #13592. We should clean up sample projects names and descriptions. This list should also be sorted alphabetically so samples should be named according to that (e.g. all java samples will start with `java-` to have them close together).

![che_samples](https://user-images.githubusercontent.com/1160903/60813458-13be9680-a194-11e9-9aaf-857b1760b643.png)

_dev note: sample projects are defined here: https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json_

### Reproduction Steps
"Add new Workspace" screen > click button "Add or import project" > see list of samples

**OS and version:**    
latest 7.0.0-rc-4.0-SNAPSHOT
**Diagnostics:**

**Comment by l0rd** [comment]
@sparkoo samples are in the devfile registry now. I don't think we should use samples.json anymore.

**Comment by l0rd** [comment]
There is no project description in devfile registry. But is that worth using sample.json and cross-matching it with the devfile registry just to get a description? And some projects in the devfile registry don't have a corresponding entry in sample.json. How are we going to deal with them?

**Comment by sparkoo** [comment]
@l0rd could you please then point me, what exactly is source of sample projects? I can see this list in devfile registry https://github.com/eclipse/che-devfile-registry/tree/master/devfiles which AFAIK is stack list. However, I can't see sample projects there. I've discussed this with @ashumilova who gave me a bit different info than you, or I don't understand something here (which is highly possible). @ashumilova could you please comment on this?

**Comment by l0rd** [comment]
@sparkoo no worries that's absolutely new stuff and it may be possible that I am missing something.

Every devfile in the devfile registry has a project sample (e.g. [here](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/angular/devfile.yaml#L7) for the angular stack). When a user will select a stack (e.g. the angular stack) the only sample he will see will be the one included in the devfile whereas before he could the list of all the samples in samples.json.

Now the problem is that, in the dashboard, every sample has a name and a description but, in the devfile format specification, projects don't have a description.

To fix that I would proceed in 3 iterations:
1. Samples in the dashboard are shown without any description
2. Samples all have the same description ("Sample project for Che $(stack-name) stack")
3. Add a new field in the stack meta.yaml (`sampleDescription`) and use that on the dashboard

And I am perfectly ok if we do only iteration 1 for Che 7 GA but I think we should not use sample.json anymore. But @ashumilova is working on it and may have better ideas

**Comment by ashumilova** [comment]
Maybe this will make it more clear:
![workspace_creation](https://user-images.githubusercontent.com/1611939/60867346-49ff2300-a233-11e9-8330-de8239cbacef.gif)
Changing the stack - displays the sample inside. And leaves opportunity to add more samples beside that one.
I removed project description from edit project section.

**Comment by sparkoo** [comment]
thanks @l0rd and @ashumilova 
So, as I understand it now, there will be just devfiles (che-devfile-registry repo), no `samples.json`. I guess that one devfile can have multiple sample projects, so all these will be loaded from devfile, once user select stack in Stacks selection. Thus, it does not make sense to clean-up names/descriptions of current sample projects in `samples.json` as they are being step-by-step replaced with devfiles.
Is this in plan for 7.0.0 GA, to fully replace `samples.json` with devfiles?

**Comment by l0rd** [comment]
@ashumilova what's not clear is from where the second sample (the real world app sample) come from, is it defined in the devfile or in the samples.json?

**Comment by ashumilova** [comment]
Reworked that part. In this [PR](https://github.com/eclipse/che/pull/13825) samples.json is not used at all. Samples page displays projects defined in devfile as well. On workspace details page - adding project widget will not have samples tab - only git and github.

**Comment by sparkoo** [comment]
ok. I'm closing this one as `samples.json` is not used anymore.
