### ISSUE TITLE
Artik IDE not reuseable

### ISSUE THREAD

**Issue by yogeshg39** [eclipse-che/che#1381]
Hello,

I am running the artik ide using the vagrant. Everything works fine. But if the system is booted without saving VM state using the vagrant suspend then, when I try to do vagrant up next time it gets stuck at ARTIK IDE: BOOTING ECLIPSE CHE and the IDE never starts. What has to be done in such case?

**Comment by TylerJewell** [comment]
@yogeshg39 Hi!  Well, this is a very odd circumstance. There are a few things:
1. We recently made a commit into the master of the code repository to change the Vagrantfile.  Can you inspect your Vagrantfile to let us know whether Che is starting from a server or from a Dockerfile?  The Dockerfile syntax is the latest syntax.  If it's doing Dockerfile, you should see the following at line 139: 

```
    docker run --net=host --name=che --restart=always --detach `
              `-v /var/run/docker.sock:/var/run/docker.sock `
              `-v /home/user/che/lib:/home/user/che/lib-copy `
              `-v /home/user/che/workspaces:/home/user/che/workspaces `
              `-v /home/user/che/storage:/home/user/che/storage `
              `-v /home/user/che/che.properties:/container/che.properties `
              `-e CHE_LOCAL_CONF_DIR=/container `
              `codenvy/artikide:${CHE_VERSION} --remote:${IP} --port:${PORT} run &>/dev/null
```
1. The Dockerfile syntax is more reliable than the normal server run. So we recommend that you upgrade to this format. Inside of your VM, Docker is launched as a daemon, so anytime you stop / restart the VM, the container will automatically be restart.
2. The Vagrant VM is really just there for convenience to get people started quickly. There are ways to mount your project files from inside to outside the VM so that you can save them over a long period of time. However, it's actually easier to just run Che as a native server or as a Docker container outside of the VM.  There are a couple more steps you have to take, but then you are in control of the product.  The VM is there so that the most people can get started in the fastest way.  What OS are you using and we can offer some additional guidance.

**Comment by yogeshg39** [comment]
@TylerJewell  Che is starting from the Dockerfile. And I am using Ubuntu 14.04.

**Comment by TylerJewell** [comment]
@yogeshg39 - I have a suspicion of what is happening.  Need a few hours to test various scenarios and reproduce the issue.

**Comment by TylerJewell** [comment]
@yogeshg39 Found the issue and issued a pull request for a fix.  It's rather a silly issue that was missed in the testing scenarios.  The launch of the Docker container that runs the IDE should not happen in the second provisioner, which executes on every execution, both the suspend and the up commands.  `docker run` should only run once. The server is started in daemon mode.  Moving this command into the one-time only provisioner solves the problem.

https://github.com/codenvy/artik-ide/pull/59

**Comment by ghost** [comment]
PR merged
@yogeshg39 can you give it a try now? Run `vagrant destroy` and, get a new Vagrantfile and `vagrant up` again

**Comment by ghost** [comment]
Checked it on Windows. Works for me. Closing the issue, but feel free to reopen if the problem persists.
