### ISSUE TITLE
[Regression] Apache Camel devfile not starting on Hosted Che

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#13832]
### Description
When starting Che 7 workspace based on `Apache Camel based on Spring Boot`, the workspace is not started saying `Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspacevd196kj996eb1v7b.maven-85dcd48884-55sdr" is forbidden: [maximum cpu usage per Pod is 6, but limit is 6424m., maximum memory usage per Pod is 3Gi, but limit is 3450109952.]', 'workspacevd196kj996eb1v7b.maven-85dcd48884'"`.
Screenshot:
![image](https://user-images.githubusercontent.com/29278800/61126465-cc464c00-a4ac-11e9-8da9-1d39bd52b6cd.png)

### Reproduction Steps
Log in to https://che.prod-preview.openshift.io. Click `Add Workspace`, click `Apache Camel based on Spring Boot` and hit the button `CREATE & OPEN`.

**OS and version:**    
https://che.prod-preview.openshift.io with version 7.0.0-rh-3.0

**Comment by ibuziuk** [comment]
cc: @tsmaeder it looks like apache camel requires more than 3 GB of RAM, will it be possible to meet 3 GB requirement for this devfile

@l0rd @slemeur in general in order to have all the devfiles supported on che.openshift.io we need to make 3 GB of RAM as a limitation for all the devfiles in the registry

**Comment by rhopp** [comment]
@l0rd @slemeur So far I've put milestone 7.1 to this, as this is not working only on che.openshift.io (due to memory limits). If you think otherwise, feel free to change this. 
btw. Do we **need** this devfile for che 7.0 GA? That may be the simplest and safest solution.

**Comment by apupier** [comment]
it was working before on che.openshift.io. I spent a large amount of time to tweak memory limits to be able to do it. Why is it not working anymore? Which memory limits are no more correct?

**Comment by apupier** [comment]
Maybe it is because the apache camel plugin has no more memory limit specified in devfile 

https://github.com/eclipse/che-devfile-registry/blob/91f5b9bc220ceb6105ba17aaa7b6a7361367e880/devfiles/apache-camel-springboot/devfile.yaml#L16-L18

and that the default value for plugin is set to 512M

https://github.com/eclipse/che-plugin-registry/blob/603ff3819b973b138f806e9f7c0bb8c6ddcb5c4d/v3/plugins/camel-tooling/vscode-apache-camel/0.0.14/meta.yaml#L17

although in initial proposal, it was 128M

https://github.com/eclipse/che/issues/13146#issuecomment-492171279

i'm nto sure how I can test as i cannot access https://che.prod-preview.openshift.io/dashboard/
and i'm also no more able to connect to http://che.openshift.io so cannot test it withthem.
I installed Che 7 locally. how can i set the workspace limit for workspace the same way?

**Comment by apupier** [comment]
there is also the Java extension which is now 1500M by default https://github.com/eclipse/che-plugin-registry/blob/603ff3819b973b138f806e9f7c0bb8c6ddcb5c4d/v3/plugins/redhat/java/latest/meta.yaml#L16-L18
although using 1280M in the initial stack
https://github.com/eclipse/che/issues/13146#issuecomment-492171279
