### ISSUE TITLE
Deprecate and remove /api/devfile method

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13867]
### Is your task related to a problem? Please describe.
This is an outdated method to create a workspace. The correct one is ```/api/workspace/devfile```
And some users might be confused when using it.  Like this onehttps://github.com/eclipse/che/issues/13860

### Describe the solution you'd like

We should.
- Deprecate it with some good message first.
- Remove DevfileService completely

### Describe alternatives you've considered
none

### Additional context
none

**Comment by skabashnyuk** [comment]
CC @rhopp @l0rd

**Comment by l0rd** [comment]
I am ok to add to 7.0.0 but please wait tomorrow approval of others issue "curators" before merging the related PR.

**Comment by slemeur** [comment]
Can the issue say which will be the replacement API?

**Comment by skabashnyuk** [comment]
@l0rd @slemeur ok

**Comment by nickboldt** [comment]
+100 to remove old API `/api/devfile` and replace with `/api/workspace/devfile` in 7.0.0.GA release.

But if this was introduced **NEW** in 7.0, you should be able to just remove it entirely without the need to deprecate, since anything 7.0.0.[pre-GA] is not supported and subject to change, even in a for-real RC. 

If it isn't removed before 7.0.0.GA, **THEN** you would have to deprecate it in 7.1 and remove it in some future release (7.4?) so people have time to adapt to the new API path.

**Comment by skabashnyuk** [comment]
I thought that this pr would be part of RC next week and in a next GA we will remove this API at all.
