### ISSUE TITLE
Embed minishift addon into chectl

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13889]
### Is your task related to a problem? Please describe.
There is always a chicken/egg problem with the minishift addon
Che is updated then some templates are updated into minishift (for the addon) but we need to wait a release of minishift
For example one month ago registry URL has been updated to v3 but only a couple of days ago a new maintenance release of minishift has been released

### Describe the solution you'd like
Like we do for helm of che-operator, chectl should embed the minishift addon and use that when deploying the addon instead of the 'internal' minishift addon provided inside minishift

### Describe alternatives you've considered
none

### Additional context
minishift is in end-of-life so it should only include a stable version of che server (and not nightly image)

**Comment by tsmaeder** [comment]
If minishift is end-of-life, why have a minishift addon at all? Also, the operator works for minishift, so again, why not just kill the addon?

**Comment by benoitf** [comment]
it's because for now operator is not providing single-user mode (while minishift addon is providing it)

**Comment by amisevsk** [comment]
Another concern is if we have a copy of the addon in chectl, there could be confusion in *which* minishift addon is being used. Is it possible for chectl to check for an addon update or something?

**Comment by benoitf** [comment]
@amisevsk hi, could you be more explicit of what you expect on the confusion

**Comment by l0rd** [comment]
@amisevsk we would not duplicate the code but just reference the code that's in the minishift repository

**Comment by l0rd** [comment]
Basically @tsmaeder this issue is to avoid that https://github.com/eclipse/che/issues/13584 happens again.

**Comment by tsmaeder** [comment]
I see this as a maintenance issue. AFAIC, I would welcome less variants of our installer.

**Comment by l0rd** [comment]
That means that we release the installer for single user on minishift with the kind of problems that you faced on the issue above. Who ever uses an old version of minishift will be impacted. 

@tsmaeder the fix is a 2 hours fix and avoids long hours of frustration for a minishift users (you should know the kind of frustration). And that's a temporary solution until we implement the right solution https://github.com/eclipse/che/issues/13420.

**Comment by tsmaeder** [comment]
If it's a trivial and safe change I don't object.

**Comment by nickboldt** [comment]
If there's time for this to be done for 7.0, sure. But since minishift is now updated to 1.34.1 with the fixes we requested last month, and since we're in code freeze for 7.0, there should really be no more urgent fixes for the minishift che add on at this point. So... I guess what I'm saying is this COULD be a 7.0.0 milestone target, but I'd mark it P3 behind more urgent stuff.

**Comment by benoitf** [comment]
issue is there if ppl are still using their previous versions of minishift.

**Comment by l0rd** [comment]
Moving this to `7.0.0` since we had another case of user not able to deploy on minishift because of this particular problem.
