### ISSUE TITLE
Devfiles in registry should not hard-code project name (when appropriate)

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#13936]
### Is your task related to a problem? Please describe.
All of the currently deployed devfiles in the registry hard-code their project's path, e.g.
```
${CHE_PROJECTS_ROOT}/angular-realworld-example-app
```
This means that if a user adds any project to their workspace, the commands do not work (see #13594)

### Describe the solution you'd like
Commands should be improved (where it is applicable) to use `${current.project.path}`

For some devfiles this does not make sense, but it's worthwhile for "general" stacks such as python, java-maven, etc.

### Describe alternatives you've considered
Leave it as-is, and treat devfiles in registry as "toy" samples that are difficult to modify.

### Additional context
Depends on #13636

**Comment by l0rd** [comment]
@amisevsk note that we agreed with @ashumilova that if a user select a different project the commands should be dropped as well. 

In other words, even if we do not hardcode the project path, there are good chances that the sample commands don't work for arbitrary users projects.

And the annoying issue with the macro `${current.project.path}` is that it works only if the user select the project in the file explorer: commands fail otherwise. That's confusing for users.
