### ISSUE TITLE
apache-camel-springboot devfile having too many runners

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#14005]
## Summary

For some reason the Apache Camel Springboot devfile image is starting too many runners in the maven container, also there is Java8 and Java11 being mixed together.

Is this an expected behavior? It's eating memory like crazy and it's preventing this image from being able to be run at OSIO

## Relevant information

"maven " eclipse/che-java8-maven : 150
"che-machine-exec" eclipse/che-machine-exec : 256
"theia" eclipse/che-theia : 512
"vscode-xml" eclipse/che-remote-plugin-runner-java11 : 128
"vscode-apache-camel" eclipse/che-remote-plugin-runner-java11 : 1024
"vscode-java" eclipse/che-remote-plugin-runner-java8 : 1024

![Screenshot_2019-07-24 OpenShift Web Console](https://user-images.githubusercontent.com/16451875/61802286-7d939d00-ae30-11e9-8c09-30d6a7bf7793.png)

**Comment by ibuziuk** [comment]
@apupier could you please comment?

**Comment by apupier** [comment]
Can you precise what you mean by "too many runners"?

There is a known memory issue in constrained environments ( <3G) with a PR available to fix the regression https://github.com/eclipse/che-devfile-registry/pull/46

Fuse requires Java 8 to be launched with. i think it is explaining the vscode-java and maven sidecar beng on Java 8.
The VS Code Apache Camel extension can run on Java 11, so seem sfair to use it.

For vscode-xml, I don't know but I guess that it is running fine with Java 11 that's why it is using it.

cc @sleshchenko which has migrated the stack to the devfile format and @tolusha which created the stack on Che 7 to be sure that I understood well.

**Comment by ScrewTSW** [comment]
@apupier Nevermind. I understand the purpose of the images.

I've been able to get the devfile to run successfully, do a successful build and deployment and I've adjusted the consumption based on what I've seen happening with the deployment pods during the execution.
