### ISSUE TITLE
php devfiles `Stop Apache Web Server` gets error

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14011]
### Describe the bug
When running `Stop Apache Web Server` task, it writes `[FAIL] Stopping Apache httpd web server: apache2 failed!` to terminal. It looks like apache server was stopped though.

### Che version
 - [x] nightly

### Steps to reproduce
1. run workspace from php devfile https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/php-web-simple
1. run `Start Apache Web Server` task
1. run `Stop Apache Web Server`
1. see error in terminal
1. check whether apache server really stopped

### Expected behavior
apache should be properly stopped, without errors

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

**Comment by slemeur** [comment]
this could be related to a problem with the terminal @AndrienkoAleksandr or tasks @RomanNikitenko

**Comment by RomanNikitenko** [comment]
I tested the described use case and got the same error.
Also I tried to execute the same commands from terminal and got the same output, so I think the problem is not related to tasks.
![stoping_apache](https://user-images.githubusercontent.com/5676062/61857227-60aca780-aecc-11e9-86c4-71aa60562ae7.png)

**Comment by AndrienkoAleksandr** [comment]
+1 . I think the problem maybe content of the stop command or something else.
