### ISSUE TITLE
Keep in sync README.MD description in che docs with chectl 

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14054]
### Is your task related to a problem? Please describe.
At https://www.eclipse.org/che/docs/che-7/che-quick-starts.html#che-deployment-options-using-chectl there is a description of README of chectl but it's not up-to-date

### Describe the solution you'd like
As README is generated and using some placeholders, we could have jobs that automatically update the documentation by taking README content from `chectl` repository
So online documentation could be always up-to-date

**Comment by l0rd** [comment]
@benoitf thanks for raising it. I have set milestone `7.1.0` because your proposal doesn't seem straightforward. In the meantime (for `7.0.0`) we can replace the outdated content with a link to the github `README.md`. What do you think?

Anyway what worries me is the `RELEASE` env variable in the [installation section](https://www.eclipse.org/che/docs/che-7/che-quick-starts.html#installing-the-chectl-management-tool) that is outdated as well and results in an even worst problem: installing 4+ months old `chectl`. Since you were working on the installation using the `tar` packaged chectl you may have already a plan don't you?

**Comment by themr0c** [comment]
Hi @benoitf the verbatim copy of the result of the `--help` command probably doesn't make much sense in the documentation, and a link to the accurate section of the chectl README should probably be sufficient anyway.  The dedicated guides (for AWS, GCP, Azure, Openshift etc.) should be the right place to develop examples around the available options. Would you agree with that?

**Comment by benoitf** [comment]
hello @themr0c 
yes I agree

**Comment by themr0c** [comment]
@benoitf I am closing this issue because I believe we have addressed it already.
https://www.eclipse.org/che/docs/che-7/installing-the-chectl-management-tool/ is pointing to `chectl` README for additional informations. Please feel free to reopen if the current state is not satisfactory.
