### ISSUE TITLE
Support plugin brokering in offline mode

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14115]
### Is your enhancement related to a problem? Please describe.

Most of (all?) the plugins included in che-plugin-registries refers to vsix files published on remote online servers.

When a Che workspace is started in an offline scenario it fails to start, even if all the container images are available offline, because the servers that host the vsix files are unreachable.

### Describe the solution you'd like

- [ ] DOWNLOAD BINS - Implement a bash script that parses the links to the vsix and svg files and downloads them locally. The script should use `jq` and `yq` to parse index.json and meta.yaml files. The script should be called `download_plugin_binaries.sh` and use `${LOCAL_BIN_PATH:resources/}` as a parameter to specify where the binaries should be downloaded. That's pretty similar to [this PR](https://github.com/eclipse/che-plugin-registry/pull/195/files#diff-a318211b75a21108ed46b1103483a55d).

- [ ] SET URLS - Implement a bash script that updates vsix and svg URLs hostnames in meta.yaml files. The new hostname value should be `${CHE_WORKSPACE_PLUGIN__REGISTRY__URL}`. The script should be called `set_plugins_url.sh`.

- [ ] REGISTRIES BASE IMAGE - Create a new container image (`quay.io/eclipse/che-registry`) that has `httpd`, `python`,`jq`, `yq`. It could be ubi8 based (from registry.access.redhat.com) or registry.centos.org/centos/httpd-24-centos7. The related `Dockerfile` should be in the `che-plugin-registry` repo and called `Dockerfile.base`. #14113

- [ ] DOCKERFILE - Update current che-plugin-registry Dockerfile to:
  - [ ] Use `quay.io/eclipse/che-registry` as base image
  - [ ] Remove using a multi-stage build: scripts are copied and run during the "prod" image build
  - [ ] The script `download_plugin_binaries.sh` is executed (at build time) only if the environment variable `OFFLINE_READY` is set: `RUN test [[ ! -z "$OFFLINE_READY" ]] && ./download_plugin_binaries.sh`. For example the offline image can be built using the command: `docker build --build-arg OFFLINE_READY=true`.

- [ ] INSTALLERS - Add `offline` option to helm and che-operator. If the option is set `set_plugins_url.sh` should be executed as soon as the plugin registry is started.

- [ ] DOCS - Update the doc section about "custom che plugin registries" with the instructions to build and run the che-plugin-registry image for offline usage

**Comment by benoitf** [comment]
I don't see why multi-stage build should be removed. It's a real benefit for upstream.
--> `Remove using a multi-stage build: scripts are copied and run during the "prod" image build`

**Comment by amisevsk** [comment]
I've created issue https://github.com/eclipse/che/issues/14163 as an alternative for the second option above.

**Comment by l0rd** [comment]
@benoitf the multi-stage build benefit I see is it make it possible to use some scripts and tools in the intermediate "build" image without the need to have them in the target "prod" image  (`yq` for example). That's fine in theory but in practice those scripts and tools are useful at runtime as well to update the index.json, meta.yaml and devfiles.yaml. At least until the registries don't have a proper CRUD web API.

**Comment by l0rd** [comment]
@amisevsk that's a good alternative indeed.

**Comment by benoitf** [comment]
@l0rd
>>  That's fine in theory but in practice those scripts and tools are useful at runtime as well to update the index.json, meta.yaml and devfiles.yaml.

the image is already built and index.json / meta.yaml and devfiles.yaml are never changed at runtime so I don't see where `in practice` you're using it.

**Comment by l0rd** [comment]
@benoitf for example to add a new plugin or editor folder to a plugin registry without rebuilding the registry container image. Or adding a new stack to a devfile registry without the need to rebuild a new container image.

**Comment by benoitf** [comment]
well as there is no persistent volume, all the changes are lost.
If you're talking for development mode,  to add a new plugin folder I think it's faster to use vi and copy paste the last lines of plugin-registry of index.json than to use jq

Also adding a folder is not so easy from scratch so you'll probably as well copy an existing folder so no need to use yq as well, you'll edit the files directly.

The remaining problem is that if at the end it works, you'll need to extract all the files and copy them to the plugin-registry and create a PR but git is not installed as well. so you'll have to copy files to /projects folder, etc.

so I would say that for me the issue for the developer is not about yq tool being missing (and on production you will never edit files on live)

**Comment by l0rd** [comment]
>  I think it's faster to use vi and copy paste the last lines of plugin-registry of index.json than to use jq

I am not talking about running `jq` but running the script `index.sh` (that uses `jq`). And no it's not about using `vi` or `git` neither. The flow is pretty straightforward and I described it in [this documentation section](https://www.eclipse.org/che/docs/che-7/editing-a-devfile-and-plug-in-at-runtime/) where steps 4 are currently broken because index.sh is not included in the target image.

These instructions for updating a registry at runtime are much easier compared to the one for building and deploying a custom registry ([the doc section](https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/)) and we should make it easy for users to use this flow.

**Comment by benoitf** [comment]
I think we're not sharing the same view.
You want to have runtime and build tools in the same image while I think tools and runtime are separate images. (like we have theia-dev and theia images)
Runtime is minimalistic and work for 99% of the time where you only need 1% of using a build command like index.sh

**Comment by amisevsk** [comment]
An update on this issue:

- [x] DOWNLOAD BINS - Implemented as a **build time** script in https://github.com/eclipse/che-plugin-registry/pull/211

- [x] SET URLS - Implemented as a **build time** script that leverages broker `relative:extension/` support in https://github.com/eclipse/che-plugin-registry/pull/211

- [ ] REGISTRIES BASE IMAGE -  #14113 is blocked by there not being a convenient `httpd` ubi8 container; do we really want to build + maintain a `ubi8-httpd` container ourselves? Where would such an image live (since it would be shared between the devfile and plugin registries)

- [ ] DOCKERFILE - Update current che-plugin-registry Dockerfile to:
  - [ ] Use `quay.io/eclipse/che-registry` as base image 
    - **blocked** by above
  - [ ] Remove using a multi-stage build: scripts are copied and run during the "prod" image build 
    - **not required** as downloading bins is done at build time
  - [ ] The script `download_plugin_binaries.sh` is executed (at build time) only if the environment variable `OFFLINE_READY` is set: `RUN test [[ ! -z "$OFFLINE_READY" ]] && ./download_plugin_binaries.sh`. For example the offline image can be built using the command: `docker build --build-arg OFFLINE_READY=true`. 
    - **Insufficient** as an "offline" broker would not be able to download the bins at startup

- [ ] INSTALLERS - **blocked** as I don't think an offline runtime option makes sense (if the broker is offline it cannot cache the `.thiea` and `.vsix` files -- this effectively only enables local caching)
- [ ] DOCS - **Not started** as there are still open questions about implementation. PR https://github.com/eclipse/che-plugin-registry/pull/211 updates plugin registry README.md with relevant information

The [script](https://github.com/eclipse/che-plugin-registry/pull/211/files#diff-350e65500157d522cff06e874f7ab48e) that is responsible for caching artifacts at build time only depends on `wget` and `sed`, so it would be possible to add it to the contianer image without additional modification to enable a "cache artifacts at startup" option as requested in the fourth item above. This does not satisfy the "offline" use case, but could still be useful on some deployments.
