### ISSUE TITLE
Che reset to default after unexpected reboot (Openshift / Multiuser)

### ISSUE THREAD

**Issue by donenocode** [eclipse-che/che#14133]
## Summary
After an unexpected restart of a single node openshift 'cluster' running Eclipse Che multiuser.
The installation has reset to defaults. The default admin password for Che, all workstations/organizations have gone.
The Che/Keycloak/Postgres containers have all started (apparently correctly).

## Relevant information
Docker images:
Che-server: eclipse/che-server:6.15.0
Keycloak: eclipse/che-keycloak:latest
Postgress: eclipse/che-postgres:nightly

Openshift v3.11, all 'local' storage

##
Started a terminal on the postgres pod and did a 'pg_dumpall'.
All of the data is in there as expected.
I added a new workspace to the now default Che and 'pg_dumpall' again and that appears with the other data also. This makes me think that the database connection is ok??

Im not sure exactly where to look for the error here, but I assume the database as both Keycloak and Che are reset to defaults.

Any pointers in the correct direction??

Thanks,

**Comment by donenocode** [comment]
Further to this I think the issue is related to keycloak as using the Che api I can query and see the user details.
However they do not appear in keycloak.
I continue to look.

**Comment by benoitf** [comment]
cc @ibuziuk @skabashnyuk

**Comment by skabashnyuk** [comment]
@donenocode 
Looks like you reporting a bug. Could you please provide additional information?


### Describe the bug


### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

**Comment by donenocode** [comment]
Thanks for the response.
I have tracked the issue to be the Keycloak postgres database.
It appears to have be initialised when the system rebooted.
I've restored backup data to it now which is a bit out-of-date but good enough to get going and to manually fix the new stuff.

**For reference however:**
Che Version: 6.15.0
Runtime: OpenShift 3.11.0 (Kubernetes v1.11.0)
Che Installation method: via the openshift deploy script 'deploy_che.sh'
Environment: Linux (CentOS 7)

**Steps taken:**
1. Unexpected reboot on single node openshift 'cluster'
2. Openshift brought back online
3. Che applications (Che,Keycloak,Postgres) started

During keycloak and postgres startup they likely pulled later versions of the container build.
Eclipse Che is set to 6.15.0 specifically so did not pull a later version.


**Issue:**
Keycloak reset to defaults, postgres database mostly empty (Che Database is OK)
Che login is reset to default (as keycloak has been reset)
All users missing from Keycloak
