### ISSUE TITLE
AMI for che?

### ISSUE THREAD

**Issue by khatchad** [eclipse-che/che#1416]
[This page](https://eclipse-che.readme.io/docs/configuration-che-on-ec2) has instructions on installing che on an AMS EC2 instance. Why not just create an AMI for che?

**Comment by TylerJewell** [comment]
@khatchad Because there are some maintenance challenges with it.  We just inked a partnership with Bitnami, however, which will be publishing installers for various cloud vendors.  I think it will launch within the next month or so.  This was a better approach as it allows us to target many cloud providers all at once.

**Comment by khatchad** [comment]
Thanks, @TylerJewell. Sounds great.
