### ISSUE TITLE
Implement Language Server Metrics

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14245]
In #13270 we are asked to provide the following metrics:

The % of Language Servers requests that get a successful response
The % of Language Servers requests that get a successful response in under N seconds

Let's implement this as far as we can (see also https://github.com/eclipse/che/issues/13375). We need to ensure that metrics have no negative impact on performance (e.g. no potentially blocking calls, etc.).

as we investigaged in https://github.com/eclipse/che/issues/14017, our approach will be to instrument the plugin API, as this is our preferred way of implementing language support.

**Comment by JPinkney** [comment]
Because of https://github.com/microsoft/vscode-languageserver-node/issues/517 there are a few more steps we will need to do before providing full metrics.

Currently, in https://github.com/JPinkney/theia-plugin-extension-metrics we can collect the number of errors that occur in a particular vscode extension by inspecting the output channel and using a regex to abstract the method that is erroring. Then we can keep track of the number of times this method inside of that output channel has errored.

A Prometheus metric would look something like:
`language_server_error_metrics{id="YAML Support", method="textDocument/documentSymbol"} 3`

where `3` is the number of times `textDocument/documentSymbol` failed inside of `YAML Support`.

Although this doesn't necessarily give us all the information we need it is a stepping stone towards future work for full support of these language metrics. In order to achieve full support we need to do a few things that can be done in a few different ways.

No matter what we will have to work on https://github.com/theia-ide/theia/issues/6151 so that we can get the number of successful language requests that happen from a vscode extension id/particular output channel id. 

Next we have two options on what we can do:
1. Connect the output channel id from the output channel with the output channel id that we have from the previous step, allowing us to get all the metrics we want.

Or

2. Provide a mapping from vscode extension id's to their output channel so that we can connect the vscode extension id to a particular channels output id, allowing us to get all the metrics we want.

Obviously 1 is ideal because we don't have to manually provide a static mapping but it all depends on the implementation we can have for https://github.com/theia-ide/theia/issues/6151.

**Comment by JPinkney** [comment]
From what I can tell theres only a few things that need to be finished for this task:
[ ] https://github.com/eclipse-theia/theia/pull/6214 needs to be merged
[ ] https://github.com/JPinkney/theia-plugin-extension-metrics needs to be published to npm
[ ] The published npm module as well as `@theia/metrics` need to be added to che-theia

Once those are done https://github.com/eclipse/che/issues/13375 needs to be completed to be able to get the metrics to prometheus

**Comment by tsmaeder** [comment]
PR has been merged.
