### ISSUE TITLE
Merge devfile and plugin registries

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#14268]
devfile and plugin registries needs a rehab. Our quick and dirty implementation is causing problems. 

- [ ]  Merge devfile and plugin registries to be a single container. 
- [ ]  Add programmable REST backend so that we can keep backwards compatibility.

**Comment by rhopp** [comment]
@l0rd Could you take a look at this one and triage it accordingly?

**Comment by ibuziuk** [comment]
osio team is planning to start working on this task in `7.2.0` 
@gorkem @l0rd am I correct that this issue is basically about creating a standalone REST api driven app with CRUD for `/plugin` and `/devfile` endpoints, that would be used as a backend for che marketplace in future?

**Comment by l0rd** [comment]
That's not about the marketplace. That's about merging the 2 services to make a better usage of resources (1 service vs 2 services) and make it simpler to manage (release/deploy/update). 

But to merge the 2 registries together we should move to a programmable REST backend first to keep backwards compatibility. We should move from a static JSON file served by an Apache HTTP server to a CRUD lightweight web service that would returns the same JSON objects.

**Comment by amisevsk** [comment]
I've thrown together a quick repo that combines the plugin and devfile registry [here](https://github.com/amisevsk/che-registry). 

Building:
1. `docker build -t <name>/che-registry:dev -f dockerfiles/Dockerfile .`
2. push image
3. Replace Che devfile registry with this image, and point Che plugin and devfile registry to the root path.

LMK if we want to go in this direction, I can work on adding build, CI, etc. scripts and pushing it to an eclipse repo.

**Comment by ibuziuk** [comment]
@amisevsk will let @l0rd & @gorkem comment, but my understanding was that the plan is to have a web app with CRUD functionality

**Comment by amisevsk** [comment]
I agree, but this was simple enough that it's worth taking a look at if what we want to do is merge the registries. The CRUD stuff could be added to a single repo instead of replicated between the two.

**Comment by l0rd** [comment]
@amisevsk does your solution break the existing registries API?

**Comment by amisevsk** [comment]
@l0rd No, the only change is that the plugins path does not include `v3`. On the Che side, it would work by specifying
- Plugin registry URL: `<Route to registry>`
- Devfile registry URL: `<Route to registry>`

I've got a built image `amisevsk/che-registry:dev` which can be dropped in-place for an existing **devfile** registry deployment [1], that works as expected when pointing `CHE_WORKSPACE_PLUGIN__REGISTRY_URL` to whatever the devfile registry route is.

[1] - It can't be dropped in for the plugin registry deployment because the readiness check still refers to `/v3/plugins`.

**Comment by benoitf** [comment]
would be nice to have `FROM scratch` image as well

**Comment by nickboldt** [comment]
can you do `FROM scratch` and then install httpd? 

or would this web app be a go or npm thing that runs in the otherwise empty container on an open port, to serve files (like httpd, but more lightweight) ?

**Comment by amisevsk** [comment]
I feel that this issue should be closed, as it is out of sync with the current direction.

1. We've decided that merging the registries doesn't make sense, since any end-user configuration would likely happen to one or the other (e.g. using the default plugin registry with a devfile registry specific to one's own projects)
2. The REST backend implementation, and how that is done, should be tackled as a separate issue/epic, rather than an add-on to the current issue. Improving the backend (i.e. not just serving directories via httpd) is still in a design phase, and I would look to architects/PMs for direction on where this should go, especially in light of more recent projects such as the [Eclipse Open VSX Registry](https://projects.eclipse.org/projects/ecd.openvsx).

**Comment by sleshchenko** [comment]
Closing it since we're not going merge devfile and plugin registry anymore. If somebody has a strong feeling that we must do it - please reopen it.
For another Plugin/Devfile Registry development directions: separate issues/epics are expected to be created.

**Comment by sleshchenko** [comment]
cc @l0rd @slemeur
