### ISSUE TITLE
How to add a new view?

### ISSUE THREAD

**Issue by wn092943** [eclipse-che/che#1433]
hi,
How to add a new view that likes the debuggerView? Could you give me some tips or tutorials? And I want to add an action or button which will switch perspective when pushed. How to create a new perspective?
Hope for your answer.

**Comment by ghost** [comment]
@wn092943 you may want to start with https://eclipse-che.readme.io/v4.3/docs/introduction-1 and then ask more specific questions.

**Comment by slemeur** [comment]
Hi @wn092943. 
We are actually adding documentation and tutorials about how to author extensions for Eclipse Che. It is the link, that @eivantsov gave you.

We are planning to add a section about Views and UI Components - and explain how to create a custom perspective. That is planned for a following iteration.

In the meantime, we'll be happy to give you guidance and help in order to get your perspective implemented. 
At this moment, we have 2 perspectives in the IDE: Dev and Ops 

![perspective-switcher](https://cloud.githubusercontent.com/assets/1636769/15819408/39d2af5c-2be3-11e6-965a-a766727e4a61.png)

You'll find the corresponding code into the [che-plugin-machine](https://github.com/eclipse/che/tree/master/plugins/plugin-machine). 
More specifically here: 
https://github.com/eclipse/che/tree/master/plugins/plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/perspective

**Comment by TylerJewell** [comment]
@wn092943 - we published new plugin resource center in the docs with explanations on how to do this.
