### ISSUE TITLE
Reconfigure existed CI jobs for using "eclipse/che-e2e:nightly" image

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14346]
### Is your task related to a problem? Please describe.
For now, on our testing jobs we use the third part image for launching tests. But according to this PR <https://github.com/eclipse/che/pull/14213> , now we have our own image with tests inside. So we should recofigure our testing CI jobs for using the "eclipse/che-e2e:nightly" image.

**Comment by dmytro-ndp** [comment]
@Ohrimenko1988: please, make sure that Happy path tests run successfully with one command changed only:
```
  CHE_HOST=$(kubectl get ingress che-ingress -n=che -o=jsonpath={'.spec.rules[0].host'})
  CHE_URL=http://${CHE_HOST}
  docker run --shm-size=256m --net=host --ipc=host \
   -e TS_SELENIUM_HEADLESS='true' \
   -e TS_SELENIUM_DEFAULT_TIMEOUT=300000 \
   -e TS_SELENIUM_LOAD_PAGE_TIMEOUT=240000 \
   -e TS_SELENIUM_WORKSPACE_STATUS_POLLING=20000 \
   -e TS_SELENIUM_BASE_URL=${CHE_URL} \
   -v ${WORKSPACE}/e2e:/tmp/e2e:Z \
   eclipse/che-e2e:nightly
```
It has turn actually out that it turned out that `che-e2e:nighlty` image doesn't work as expected on existed CI job https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/CHE-7-Happy-Path-Tests/1333/console:
```
12:24:07 09:24:06.531 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
12:24:07 Executing e2e tests from an image.
12:24:08 
12:24:08 > e2e@1.0.0 test-happy-path /tmp/e2e
12:24:08 > ./generateIndex.sh && npm run lint && npm run tsc && mocha --opts mocha-happy-path.opts
12:24:08 
12:24:08 Generating index.ts file...
12:24:08 
12:24:08 > e2e@1.0.0 lint /tmp/e2e
12:24:08 > tslint --fix -p .
12:24:08 
12:24:08 sh: 1: tslint: not found
```

**Comment by dmytro-ndp** [comment]
@Ohrimenko1988: thank you for fixing up *tslint* error. Happy path tests launched successfully with *bujhtr5555/che-e2e* https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/CHE-7-Happy-Path-Tests/1363/console. 
At the same time there was a regression appeared in Jenkins job:
```
1) Validation of debug functionality
14:10:00        Run debug and check application stop in the breakpoint:
14:10:00      TimeoutError: Waiting for element to be located By(xpath, //div[contains(@id, 'PetClinicApplication.java')]//div[@class='margin']//div[contains(@style, '608px')]//div[contains(@class, 'theia-debug-top-stack-frame')])
14:10:00 Wait timed out after 300013ms
```
It doesn't look like a flakiness, because there was the same error yesterday with the image `che-e2e:nightly` https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/CHE-7-Happy-Path-Tests/1339/console

IMHO, it could be related to fresh updates in `e2e-test` image, because there was no such an error with `cypress/browsers:node8.9.3-chrome73` image on the same job: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/CHE-7-Happy-Path-Tests/1367/console

**Comment by dmytro-ndp** [comment]
@Ohrimenko1988: Happy path tests had stuck on step on PR check job when being started on `eclipse/che-e2e:nightly` image:
- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/256/
```
00:10:13.791   Validation of debug functionality
00:35:28.924     ✓ Open file and activate breakpoint (1514505ms)
00:35:44.954 Application is ready for use. App url:
00:35:44.955     ✓ Launch debug (15931ms)
00:35:44.955     ✓ Check content of the launched application (976ms)
00:35:46.070     ✓ Open debug configuration file (1248ms)
00:35:52.000     ✓ Add debug configuration options (4465ms)
00:40:13.325 Sending interrupt signal to process
00:40:13.806 sh: line 1: 21162 Terminated              JENKINS_SERVER_COOKIE=$jsc '/bin/sh' -xe '/home/codenvy/workspace/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9@tmp/durable-cbd20d42/script.sh' > '/home/codenvy/workspace/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9@tmp/durable-cbd20d42/jenkins-log.txt' 2>&1
```
![02500428--(13_01_08 221)_ Run debug and check application stop in the breakpoint](https://user-images.githubusercontent.com/1197777/64027036-963a5580-cb48-11e9-8832-2f4829338cf0.png)

- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/258/

Please, take a look at it.
