### ISSUE TITLE
API: Ability to specify k8s namespace where a user wants to create his workspace

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14379]
### Is your task related to a problem? Please describe.
At this moment end-user has no control on which k8s namespace would be used. It calculated according to the configuration properties.

### Describe the solution you'd like
Rest API that will allow specifying k8s namespace where a user wants to create/start his workspace

### Describe alternatives you've considered
none

### Additional context
https://github.com/eclipse/che/issues/13484

**Comment by sleshchenko** [comment]
It would be better or at least easier at the beginning to provide an ability to specify an ability only during creation because changing a namespace on a start may lead to data losing (there is no way to migrate PVC between namespaces) and it's not a good thing.

Another quite important note:
Maybe we should allow it only when OpenShift AOauth if configured, otherwise a user would be able to access a foreign namespace for example when Che Server is configured with admin ClusterRole.

**Comment by metlos** [comment]
Let's split this into several tasks:

* [ ] - Store the target namespace in devfile - I propose `metadata.namespace` to conform with k8s.
* [ ] - Honor the namespace when starting the workspace
* [ ] - Make stopping workspace works even after changing the workspace namespace (e.g. the current workspace needs to be stored in the runtime)
* [ ] - add support for overriding the workspace in `/workspace/devfile`
* [ ] - add support for overridng the workspace in `/factory`

**Comment by sleshchenko** [comment]
>  Make stopping workspace work even after changing the workspace namespace (e.g. the current workspace needs to be stored in the runtime)

I'm not sure that we need to allow to change workspace namespace at all.
Once workspace is started - it may have some files in PVCs, and AFAIK there is no mechanism for moving PVCs from one namespace to another, so user will lose all files.
If a user wants the same workspace in another namespace, they should recreate it with the same configuration aka devfile.

K8s does not allow to change objects namespace as well https://docs.openshift.com/container-platform/3.5/rest_api/kubernetes_v1.html#v1-objectmeta

**Comment by metlos** [comment]
So after spending the two weeks on storing the namespace in the workspace, I think the list of tasks needed for this needs to be updated (in the order they need to be implemented):

* [ ] Add support for specifying the target namespace in devfile (partially done in my local branch)
* [ ] Use target namespace during workspace creation - use the one supplied in the devfile or figure it out using the mechanism implemented in PR https://github.com/eclipse/che/pull/14828)
* [ ] Propagate the namespace during workspace start (this is a big one due to the size of API change required)
* [ ] Add support for overriding the workspace in /workspace/devfile
* [ ] Add support for overridng the workspace in /factory

**Comment by sleshchenko** [comment]
I would like to leave one open question about introducing `metadata.namespace` into Devfile model:
1. Should it be mandatory? 
  1.1. From K8s API perpective it's mandatory, null value indicates that it must be created in a default namespace[1]. And the default namespace usually must not be available for ordinary users.
  1.2. From Che perspective, I can not imagine a situation when we need to create workspace objects in a k8s default namespace. So, we could understand the empty or absent value - that Che Server must resolve default namespace value according to Che configuration and the current user, like it can be `sleshche-che`(`<username>-che`).

#### 1.1 vs 1.2. 
1.1 is closer to k8s API behavior but in such case clients, like chectl, User Dashboard should contain some logic for resolving namespace value if it's not specified in the used template Devfile, like from Devfile Registry or stored in GitHub repository.

Personally I don't have a strong preference yet.

[1] https://kubernetes.io/docs/tasks/administer-cluster/namespaces-walkthrough/#understand-the-default-namespace

**Comment by metlos** [comment]
I favour **1.2** because it IMHO makes more sense in the context of Che.

**Comment by amisevsk** [comment]
FWIW I also think 1.2 is a better approach

**Comment by metlos** [comment]
Implemented in #15040.
