### ISSUE TITLE
Generate SSH keys when the user login for the first time

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#14411]
Majority of Che users require the SSH keys to work on their projects. For a first-time user, it can be a bit tricky to find a way to generate the keys.

The goal of this task is to generate a key pair automatically when the user login for the first time. So, after starting a workspace, in case if the user has no keys, he/she will see the notification about a key pair has been already generated automatically.

![image](https://user-images.githubusercontent.com/1636395/64183512-ab79f180-ce72-11e9-9c5f-0f0e414b1f44.png)

Uploading an SSH key to GitHub will be a separate task.

It's a part of Git+SSH flow epic https://github.com/eclipse/che/issues/13494

**Comment by azatsarynnyy** [comment]
@l0rd we need a priority for that.
Thanks!

**Comment by l0rd** [comment]
@azatsarynnyy  thanks for opening it. A few considerations:

1. Git + SSH (command line and vs code extensions) should work on the user first workspace: that may require the key to be generated che-server side and not via current theia plugin.
2. The message ("Key pair successfully generated, do you want to view the public key?") should become more explicit now since the user hasn't ask to generate it and doesn't have the context. For example: "An SSH key pair has been generated. It can be used to authenticate to remote services such as GitHub. Copy the public key and add it on your profile."
3. Instead of `View` the button should be `Copy to Clipboard`.

**Comment by gorkem** [comment]
I am not sure about this one. If I have no intention to use SSH keys on a workspace this will generate me a key and pop a notice to copy it to the clipboard. This is a confusing and since it involves SSH keys even an alarming experience for the user.

**Comment by l0rd** [comment]
@gorkem I agree: the message, if the users hasn't asked for any key generation, can be confusing/alarming. 

But current UX is awful: 

1) start a workspace and do some changes 
2) figure out that you cannot `git push` 
3) look into che docs to see that you need to generate an SSH key pair using a Theia plugin
4) generate the key pair
5) copy it in to your github profile 

Most of the new users will probably stop at 2). Some will get to 5) but there are chances that they made a mistake and `git push` will continue to fail.

We need to automate this as much as possible. What about generating a key pair silently at first login and, when a new workspace with a GitHub project is created, propose the user to copy/paste his Che workspaces public key to its GitHub profile?

**Comment by gorkem** [comment]
Agreed, let's not do the message to everyone thing, it is a step backwards. 

Considering we are trying to improve the flow through IDE on step 2 (not the git CLI), can we study if we can actually improve the git plugin at this point when it fails to push. Ideally we can hook our SSH key generation & upload logic at this point when the user really needs it. I think there is the beginnings of such a flow https://github.com/theia-ide/theia/issues/3397
