### ISSUE TITLE
Che plugin broker should persist logs.

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14412]
### Is your enhancement related to a problem? Please describe.
Currently, it is quite difficult to get logs from the Che plugin broker, apart from what is printed to  the output in the workspace panel. The broker is deleted right after it finishes, which means viewing the full logs often requires catching it in a quite short window. Additionally, it's not currently possible to view logs from the init broker without accessing them directly.

### Describe the solution you'd like
The Che plugin broker should also write its logs to a file in `/workspace_logs`, which is already mounted at startup. This would make it easier to get information from a previous run if there are any issues.

### Describe alternatives you've considered
Since plugin broker is in flux and may be reworked significantly, it may not be worth putting time into this.

### Additional context
https://github.com/eclipse/che/issues/14363

**Comment by l0rd** [comment]
> Since plugin broker is in flux and may be reworked significantly, it may not be worth putting time into this.

I agree

**Comment by sleshchenko** [comment]
Well, it's not really clear how then access workspaces logs... Some additional pod is needed just to read that logs. I think that debug mode should satisfy our needs regards get workspace-logs
![Screenshot_20201001_152214](https://user-images.githubusercontent.com/5887312/94808569-feb5cf00-03f9-11eb-9f0b-6068d1737264.png)
About devworkpace controller - storing logs will not help because:
1. metadata brokering is done on controller side which can't mount workspace PVC
2. artifacts brokering can store it's logs in PVC but again how users are able to access them.

So, I would close this issue and later when it becomes critical - create a new one for controller and solve it in possible for that case, like k8s events, propagate pods logs as workspace logs if or whatever is possible.
@amisevsk WDYT?

**Comment by amisevsk** [comment]
> So, I would close this issue and later when it becomes critical - create a new one for controller and solve it in possible for that case, like k8s events, propagate pods logs as workspace logs if or whatever is possible.

Makes sense to me. The original concern was for non-ephemeral workspaces, where the broker already mounts the workspace volume (in order to store plugins). The goal was to have the artifacts broker log to a file as well as to `stdout`.
