### ISSUE TITLE
It needs to be clarified how to login into the Che 7.1 using GitHub OAuth provider if there is OpenShift OAuth enabled

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14434]
Before Eclipse Che 7.1 it was possible to have OpenShift OAuth provider and GitHub OAuth provider setup at the same time in keycloak. At start, user was redirected to Che login page where two links were present:
![Selection_047](https://user-images.githubusercontent.com/1197777/64328018-691cf580-cfd5-11e9-9731-b32b83ce3100.png)

After [this changes](https://github.com/eclipse/che/issues/14012) in Eclipse Che 7.1 which installed on OKD 3.11 with OpenShift OAuth enabled, user is redirected to OpenShift login page at start:
![Selection_048](https://user-images.githubusercontent.com/1197777/64328113-8fdb2c00-cfd5-11e9-9928-589a86eeda0e.png)

So, it doesn't clear how to login into Che 7.1 using other providers like GitHub OAuth provider etc.

**Comment by tolusha** [comment]
It isn't a regression since it wasn't possible to login using GitHub before.

**Comment by davidfestal** [comment]
> it wasn't possible to login using GitHub before.

Well, I would say it wasn't **supported**, though you would still be able to configure Keycloak to do so.
But let me clearly state that until now the aim of adding the GitHub identity provider  into the Che Keycloak configuration was **not to use it for login**. It was mainly used to allow retrieving of the GitHub token from the Keycloak token in the Che server / Dashboard.
Sure, Keycloak allows using it for login, but this was not the main purpose.

**Comment by davidfestal** [comment]
> Before Eclipse Che 7.1 it was possible to have OpenShift OAuth provider and GitHub OAuth provider setup at the same time in keycloak.

**It is still possible**. You can still have both identity providers configured in the Keycloak federated identities. The only difference is that the main login page redirects to the Openshift login page *by default*.
Bear in mind that login is not the only purpose of federated identities (see comment here: https://github.com/eclipse/che/issues/14434#issuecomment-528336051)

Additionally, in order to install the GitHub identity provider, you have to go in the Keycloak admin configuration. And when you are there, it is very straightforward to change the identity provider you want to redirect to at login, or simply disable automatic redirect to an identity provider at login. I'll try to share a small video or screenshot asap.

> At start, user was redirected to Che login page where two links were present

As explained just above, it's very easy to restore this mechanism from the keycloak configuration. But we don't think it should be the default when Openshift OAuth is enabled in the Custom resource.

**Comment by davidfestal** [comment]
Let me add the steps to find back the login page you're speaking of @dmytro-ndp :

1. In the Che realm, click on the `Authentication` left tab
![Capture du 2019-09-05 14-46-26](https://user-images.githubusercontent.com/686586/64343301-94f7a580-cfec-11e9-975e-c37155eda17d.png)

![Capture du 2019-09-05 14-47-30](https://user-images.githubusercontent.com/686586/64343310-9aed8680-cfec-11e9-8398-d830be543525.png)

![Capture du 2019-09-05 14-48-07](https://user-images.githubusercontent.com/686586/64343325-9f19a400-cfec-11e9-8f36-411de2d61910.png)

**Comment by l0rd** [comment]
This looks like a documentation issue. @dmytro-ndp are you ok with that?

**Comment by dmytro-ndp** [comment]
@l0rd: yes, it sounds reasonable.

**Comment by dmytro-ndp** [comment]
@davidfestal: thank you for detailed explanation!
