### ISSUE TITLE
Each SSH keypair is mounted as a secret which is created after generation and workspace restart. Need to rework the implementation, so that all SSH keys would use single common secret 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14438]
### Is your task related to a problem? Please describe.
Each SSH keypair is mounted as a secret which is created after generation and workspace restart. Need to rework the implementation, so that all SSH keys would use single common secret. 

If there is a quota for secrets, e.g. Hosted Che case `20` [1] it is pretty easy to run out of secrets and workspace startup will fail with:

> Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. secrets "workspaceh9kzyha01on7ckzi-default-1567152246112" is forbidden: exceeded quota: object-counts, requested: secrets=1, used: secrets=20, limited: secrets=20. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.

[1] https://github.com/fabric8-services/fabric8-tenant/blob/master/environment/templates/fabric8-tenant-che-quotas.yml#L84

### Describe the solution you'd like
mount all SSH keys in a single secret

### Describe alternatives you've considered
N/A

**Comment by ibuziuk** [comment]
cc: @l0rd

**Comment by monaka** [comment]
Looks partly related on #14243.

I agree this issue should be resolved.
But it may decrease users' security to use a single SSH private key, IMO.

**Comment by ibuziuk** [comment]
@vparfonov wdyt?

**Comment by l0rd** [comment]
@ibuziuk what's the use case here: a user that creates 20 key pairs ? I understand that a user may have already some secrets but it's unlikey that a user create more than 1 or 2 SSH keypair for Che.

The urgent thing here is to show a meaningful error message that explains the error and the root cause.

**Comment by l0rd** [comment]
@ibuziuk set the priority to P2

**Comment by nickboldt** [comment]
Wondering if there is anything I can do as a user to solve this:

1. tried to load a devfile from factory in che.openshift. https://raw.githubusercontent.com/che-samples/che-theia-branding-example/master/devfile.yaml

2. got this instead:

###Error when starting workspace
Unable to start workspace. Error when trying to start the workspace: Failure executing: POST at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/nickboldt2-che/secrets. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. secrets "workspacebac631q0wqakgi3m-private-registries" is forbidden: exceeded quota: object-counts, requested: secrets=1, used: secrets=20, limited: secrets=20. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.

**Comment by ibuziuk** [comment]
@l0rd if we are not going to rework the SSH key implementation we probably need to increase the number of secrets (30-40 per che-namespace) and proceed with cluster update. Looking at the @nickboldt namespace: the following secrets have been created

> workspacebac631q0wqakgi3m-default-1570542122826   kubernetes.io/ssh-auth                1         1m
> workspacebac631q0wqakgi3m-default-1570630790538   kubernetes.io/ssh-auth                1         1m
> workspacebac631q0wqakgi3m-default-1570631157815   kubernetes.io/ssh-auth                1         1m
> workspacebac631q0wqakgi3m-github-com              kubernetes.io/ssh-auth                1         1m
> workspacebac631q0wqakgi3m-gitlab-cee-redhat-com   kubernetes.io/ssh-auth                1         1m

I'm not sure what are the  `workspacebac631q0wqakgi3m-defaul-*` @vinokurig  is it somehow related to the ssh ?

Other than that we have 15 secrets which include builder (3), deployer (3), default (3) and 6 che-related secrets:

> che-dockercfg-hwtg4                               kubernetes.io/dockercfg               1         27d
> che-token-w82gl                                   kubernetes.io/service-account-token   4         27d
> che-token-xnv8c                                   kubernetes.io/service-account-token   4         27d
> che-workspace-dockercfg-5g899                     kubernetes.io/dockercfg               1         27d
> che-workspace-token-gkxlm                         kubernetes.io/service-account-token   4         27d
> che-workspace-token-xqdjz                         kubernetes.io/service-account-token   4         27d

**Comment by l0rd** [comment]
A user should only need one SSH key pair (i.e. one secret).
