### ISSUE TITLE
Issue when building stack

### ISSUE THREAD

**Issue by jkuang-exploro** [eclipse-che/che#14454]
Get this red error message in the pop-up window when trying to create a stack from a recipe:

"Recipe should contain a kind section"

The "add" button won't turn clickable

**Comment by tolusha** [comment]
@JianKuang-NOAA 
Could you provide some more information? 
Che version, installation type, screenshots?

**Comment by ibuziuk** [comment]
@JianKuang-NOAA please,  follow up on the issue template when reporting the issue:



### Describe the bug


### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
