### ISSUE TITLE
Java Packages are not shown in the "Project Explorer"

### ISSUE THREAD

**Issue by wgbeckmann** [eclipse-che/che#14490]
Hi,
I want to convince my developers to use Eclipse Che. 

But there are some issues, and I'm not shure if they are misconfiguration problems or if there are open bogs or enhancements.

The most anoying thing is the explorer: There are only Folders no Packages and to create a Class I have to create a File and then write the sceleton of the class by my self.

Only Folders:
![image](https://user-images.githubusercontent.com/18114426/64539533-ee2e4480-d31e-11e9-8e0f-6258918bfd8a.png)

No Contextmenu for Class creation:
![image](https://user-images.githubusercontent.com/18114426/64539593-0c944000-d31f-11e9-9516-3cd72f80800e.png)

Is this a misconfiguration?

**Comment by tsmaeder** [comment]
@wgbeckmann Che 7 uses Theia as it's IDE, which is essentially a clone of VS Code designed for online use. For Java support we use VS Code-Java. 
Showing Java packages inside the regular project explorer is definitely not in the cards: there is no extension point to implement something like this AFAIK, and the project explorer is language-agnostic. I come from an Eclipse background myself, but because the explorer auto-expands empty directories, I don't miss the package view at all. Give it a chance!
As for class creation wizards, maybe what's described [here](https://github.com/redhat-developer/vscode-java/issues/579) could help you.

So to answer your question: this works as expected.

**Comment by wgbeckmann** [comment]
Ok, thanks. The class creation wizard is a solution, that is ok for me.
