### ISSUE TITLE
Dashboard: support importing devfiles

### ISSUE THREAD

**Issue by bryantson** [eclipse-che/che#14638]
### Is your enhancement related to a problem? Please describe.

Currently, Devfile can be either modified through Devfile registry or dynamically through the browser editor by going into the Workspace setting. However, due to different browser issue and autosaving feature, Devfile is difficult to change and the autosaving feature does not help

### Describe the solution you'd like

1. Provide the button to import the Devfile from a local computer. 
2. Replace the autosaving feature with the button to save, delete, etc.

**Comment by l0rd** [comment]
@bryantson thanks for raising it. I think we should separate the issues: allow devfile import is one issue and disabling the autosaving is a distinct one. 

There is no doubt that supporting a devfile import would be useful.

I have some doubts about disabling the autosaving. IMHO if there are issues with autosaving we should fix them instead of disabling it. Please open a separate issue for that.

**Comment by amisevsk** [comment]
For autosave, we already have https://github.com/eclipse/che/issues/13982 -- it can be an enormous pain.

**Comment by azatsarynnyy** [comment]
closing it as both features are already implemented
