### ISSUE TITLE
Linux installation fails to detect /usr/local/bin in PATH

### ISSUE THREAD

**Issue by AjitDingankar** [eclipse-che/che#14703]
## Summary 
The install script (also tried saving locally after curl piped into bash failed) doesn't detect the /usr/local/bin that's on the PATH (for ordinary user as well as root). 

## Relevant information
CentOS 7.6 Che 7.1.0

**Comment by tolusha** [comment]
@AjitDingankar 
It is not clear from the description what has been done.
Could you clarify some information?

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
