### ISSUE TITLE
Manual installation failures on Linux due to symlink errors 

### ISSUE THREAD

**Issue by AjitDingankar** [eclipse-che/che#14702]
## Summary
Got errors when trying to uncompress the archive. 

## Relevant information
CentOS 7.6 x64 chectl v7.1.0 

End of successful extraction followed by start of symlink errors shown below: 

> chectl/bin/chectl
> chectl/bin/chectl.cmd
> chectl/bin/node
> chectl/bin/run
> tar: chectl/node_modules/.bin/which: Cannot create symlink to `../which/bin/which`: Operation not supported
> tar: chectl/node_modules/.bin/uuid: Cannot create symlink to `../uuid/bin/uuid`: Operation not supported

**Comment by tolusha** [comment]
@AjitDingankar 
It is not clear from the description what has been done.
Could you clarify some information?

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
