### ISSUE TITLE
Workspace created, but stalls at last step to display it.

### ISSUE THREAD

**Issue by peidong-hu** [eclipse-che/che#14729]
I have successfully installed the che 7.2.0 on baremetal k8s, and can create workspace successfully. But the workspace failed to show up, even the green light already on for newly created worksapce.
This screenshot shows what error messages received on Chrome developer tool console,

![image](https://user-images.githubusercontent.com/7647371/65964572-dda35280-e422-11e9-8ee7-e057c7531cbd.png)

**Comment by peidong-hu** [comment]
I did a clean up in chrome developer tool console and refresh the page, I got the following error message,
![image](https://user-images.githubusercontent.com/7647371/65982282-9af07300-e440-11e9-9398-aa5fda0637cf.png)

**Comment by l0rd** [comment]
@peidong-hu to be able to help you we need to get some infos:
- how did you install Che (helm chart, chectl, other?)
- the version of kubernetes you are using
- [kubernetes events logs](https://www.eclipse.org/che/docs/che-7/viewing-kubernetes-events/) of the namespaces where che-server is deployed and where the workspace should be deployed
- [che-server logs](https://www.eclipse.org/che/docs/che-7/viewing-che-server-logs/) 
- [che workspace logs](https://www.eclipse.org/che/docs/che-7/viewing-che-workspaces-logs/) if any

**Comment by peidong-hu** [comment]
I installed with helm on baremetal k8s v1.11
Not sure how to get the k8s events logs on baremetal k8s,
che-server logs attached
[log3.log](https://github.com/eclipse/che/files/3679354/log3.log)

**Comment by davidwindell** [comment]
@peidong-hu what version of nginx-ingress are you running?

**Comment by peidong-hu** [comment]
I am using this nginex controller, quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0-beta.15

**Comment by skabashnyuk** [comment]
@peidong-hu can you please update issue description according to the bug report template


### Describe the bug


### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

**Comment by davidwindell** [comment]
@peidong-hu Che 7.1 and above only supports Nginx ingress 0.22+

**Comment by davidwindell** [comment]
See #14593

**Comment by peidong-hu** [comment]
Thanks. It seems that I have a problem with nginx since I am using external DNS module in my Bare metal k8s, it supports only nginx 0.9. 

Can I use traefik 1.7 with Che?

**Comment by davidwindell** [comment]
You can use earlier versions, see instructions in the linked issue above

**Comment by peidong-hu** [comment]
It works much better, after I set those two env vars for ingress version lower than 0.22 in che deployment,

But I still receive one error in developer tool,

**Comment by l0rd** [comment]
@evidolob does that ring a bell to you?
