### ISSUE TITLE
[TS_SELENIUM] Create image for the "Happy Path" tests based on the "quay.io/eclipse/che-java11-maven" image

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14737]
### Is your task related to a problem? Please describe.
Currently, for the "Happy Path" scenario used a docker image without real user. It may lead to the problem described in the issue https://github.com/eclipse/che/issues/14722 .

### Describe the solution you'd like
Create an image for the "Happy Path" tests based on the "quay.io/eclipse/che-java11-maven" image

**Comment by rhopp** [comment]
@Ohrimenko1988 @musienko-maxim Didn't we bundle mvn deps into this image to speed up the test exectuion? 
If yes, we need to rebuild the image and while doing that, we should push it to some "general" image registry, instead of `bujhtr5555` (whose is this anyway?).
And we need to rebuild this image with every version of `quay.io/eclipse/che-java11-maven` (as part of the che build/release process?)

**Comment by Ohrimenko1988** [comment]
@rhopp Yes, I described this at the comment 
https://github.com/eclipse/che/issues/14722#issuecomment-537365505

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/14779
