### ISSUE TITLE
Chectl doc does not mention user priviledge requirements

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14761]
The documentation at https://github.com/che-incubator/chectl/blob/master/README.md does not mention that the user needs to be logged into minishift, for example and that the user needs to have cluster admin priviledges.

**Comment by tsmaeder** [comment]
Improving failure diagnostics is a big ticket item and doc is part of it.

**Comment by l0rd** [comment]
That's a bug. User should not need admin privileges to install Che on minishift.

@sleshchenko @benoitf it looks to me that chectl is broken on minishift: when calling `checkKubeApi()` we are trying to [get token of the service account `default`](https://github.com/che-incubator/chectl/blob/master/src/api/kube.ts#L885) but the default user (developer) doesn't have access to this API. That's the command output:

```bash
./bin/run server:start --platform=minishift                                                                       minishift/myproject
  ✖ Verify Kubernetes API
    → Failed to connect to Kubernetes API. Error: [object Object]
    👀  Looking for an already existing Che instance
 ›   Error: Failed to connect to Kubernetes API. Error: [object Object]
``` 

The other problem is that the error message is not parsed correctly (`Error: [object Object]`) and makes it impossible to understand what's going on. I suspect that this can be due to an update to the kubernetes js client. What I have seen is that the function [wrapK8sClientError()](https://github.com/che-incubator/chectl/blob/db55f947c7230d12acd9d830c416040063ee76b0/src/api/kube.ts#L1057) tries to access `e.body.message` whereas it should look at `e.response.body.message`. When that is fixed the following error message is displayed:

```
  ✖ Verify Kubernetes API
    → Failed to connect to Kubernetes API. Error: Error: Unable to get default service account secret
    👀  Looking for an already existing Che instance
 ›   Error: Failed to connect to Kubernetes API. Error: Error: Unable to get default service account secret
```

**Comment by sleshchenko** [comment]
>  when calling checkKubeApi() we are trying to get token of the service account default but the default user (developer) doesn't have access to this API. That's the command output:

@l0rd the fix is already done but I was not able to set up secure K8s cluster and test it there https://github.com/che-incubator/chectl/pull/340

**Comment by l0rd** [comment]
Thanks @sleshchenko for the update.

**Comment by tolusha** [comment]
https://github.com/che-incubator/chectl/pull/524/ merged
Error messages are improved.
