### ISSUE TITLE
Test UX of an upgrade to Che7 from the running Che6 workspace perspective

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14810]
### Is your task related to a problem? Please describe.
The need to verify UX of running Che6 workspace when upgrade to che 7 has happened.
- What user will see?
- Does this screen contain a link to the documentation that explains what to do next?
- Does this link configurable?

### Describe the solution you'd like
- Setup che6
- Run workspace
- run an upgrade to che7
- Check UX.

### Describe alternatives you've considered
none

### Additional context
Continuation of https://github.com/eclipse/che/issues/14200

**Comment by mshaposhnik** [comment]
To perform tests,  **Che6** was started using Che operator , but some fields in CR was patched to use `6.19.0` version:
 - `cheImageTag: '6.19.0'`
 - `pluginRegistryImage: 'quay.io/eclipse/che-plugin-registry:92c7499'` (unfortunately we did not do releases of the che 6  plugin registry so need to use custom tag)

Start command:
`chectl server:start --installer=operator --platform=minishift --che-operator-cr-yaml=/home/Makis/projects/che/org_v1_che_cr.yaml`

After startup, pugin registry URL should be updated in the operator configuration to match current server (and does not include `/v3/` as it is was introduced in 7.0.0 release):
`oc edit checluster eclipse-che` and set
 - `pluginRegistryUrl: http://plugin-registry-che.192.168.99.108.nip.io/`

After that, Che6 was succesfully deployed and both Che6 and Che7-preview workspaces succesfully started.

**Upgrade to Che7**
Upgrade was executed using patch command to update necessary images:

`oc patch checluster eclipse-che --type=json -p '[{"op": "replace", "path": "/spec/server/cheImageTag", "value": "nightly"}, {"op": "replace", "path": "/spec/server/pluginRegistryImage", "value": "quay.io/eclipse/che-plugin-registry:nightly"}, {"op": "replace", "path": "/spec/server/pluginRegistryUrl", "value": "http://plugin-registry-che.192.168.99.108.nip.io/v3/"}]' -n che`

**UX after update:**
- Both workspaces was functional until  theirs stop, Che6 one has appropriate "need upgrade" warning on the UD:
![update_1](https://user-images.githubusercontent.com/1651062/66730914-2c0e1380-ee5d-11e9-9798-9a7215f40eef.png)

Some warnings appeared when entering Che6 workspace on UD:
![update_2](https://user-images.githubusercontent.com/1651062/66730955-64aded00-ee5d-11e9-8a47-5fc1ce66a661.png)


Che 7 preview workspace was **failed** to restart with the following error caused by old plugin id's format in configuration :
![update_3](https://user-images.githubusercontent.com/1651062/66730988-8909c980-ee5d-11e9-8ad3-a0cbccb2ad6a.png)

Newly created devfile-based Che7 workspaces are working just fine:
![update_4](https://user-images.githubusercontent.com/1651062/66732682-8d39e500-ee65-11e9-85b0-889645c562a6.png)

**Comment by mshaposhnik** [comment]
@nickboldt  About the docs link about workspace updgrate, it looks like the link can be overriden in 
https://github.com/eclipse/che/blob/master/dashboard/src/assets/branding/product.json#L26
