### ISSUE TITLE
Allow to use external JSON file to brand Che-Theia

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#14839]
### Is your enhancement related to a problem? Please describe.

Currently only local JSON file is allowed to use to brand Che-Theia.
```
PRODUCT_JSON=${HOME}/product.json
```
We can improve it and make it possible to use an external JSON
```
PRODUCT_JSON=http(s)://host/path/product.json
```

Improvement for https://github.com/eclipse/che/issues/14110

**Comment by benoitf** [comment]
Hi,

I think that we need a branding service instead of having to patch dashboard and che-theia.

Che-Theia, Dashboard or others would be consumer of the branding API (get product name, logo, etc)


Then, it allows dynamic configuration with classic REST API.
- Admin users could have a UI to configure branding fields.
- We can also provide a config map property to configure che server on start
