### ISSUE TITLE
Rare error on start workspace.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14859]
### Describe the bug
Sometimes workspace stops in a bad way and don't clean up some resources. And on new restart workspace you can find such error:
```
Error: Failed to run the workspace: "Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/che/configmaps. Message: configmaps "workspace47n4ojnzugm1jgd3-sshconfigmap" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=configmaps, name=workspace47n4ojnzugm1jgd3-sshconfigmap, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=configmaps "workspace47n4ojnzugm1jgd3-sshconfigmap" already exists, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
```
After one more restart error gone and workspace starts fine.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
- What is your chectl version?
- Did you use che-operator to install che?
- Do you know steps to reproduce this bug?
- What stack did you use?

**Comment by skabashnyuk** [comment]
Any messages in a che-server logs?

**Comment by lautou** [comment]
I don't know if it is related or not. I get this issue in 7.4.0 (was already the case in 7.3.0):
My workspace appears as not running in Eclipse Che console although workspace pods are runnings.
![image](https://user-images.githubusercontent.com/8274134/69544281-aa4af300-0f8f-11ea-96ed-56a078f92f9f.png)
![image](https://user-images.githubusercontent.com/8274134/69544450-06ae1280-0f90-11ea-88bb-7a3e2ead0461.png)
When i click on the workspace, it try to open the workspace instancing a new mkdir workspace pod
![image](https://user-images.githubusercontent.com/8274134/69544577-4ffe6200-0f90-11ea-8073-5f65b72983ef.png)
Of course this pod is stuck, because persistence  volume is still bound by the previous workspaces pods.
![image](https://user-images.githubusercontent.com/8274134/69544680-81772d80-0f90-11ea-9920-c383de15fa04.png)
Any clue why we have a discrepancy between the running pod and the fact they are marked as stopped in Eclipse Che?

**Comment by lautou** [comment]
Please finds the logs as attachment.
[Eclipse_Che_Logs.zip](https://github.com/eclipse/che/files/3886846/Eclipse_Che_Logs.zip)

**Comment by lautou** [comment]
Finally i found the root cause : #15312
