### ISSUE TITLE
[docs] Document airgap/offline Che deployment process/options

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14866]
### Is your task related to a problem? Please describe.
Issues https://github.com/eclipse/che/issues/14733, https://github.com/eclipse/che/issues/14733, https://github.com/eclipse/che-plugin-registry/pull/211, and https://github.com/eclipse/che-plugin-broker/pull/70 add offline functionality to Che registries and workspaces. This functionality is going to be supported by the operator (https://github.com/eclipse/che/issues/14734) and by chectl (https://github.com/eclipse/che/issues/14699)

We should add a new section to the Che documentation on how to use these options and how to deploy Che in an airgap environment.

**Comment by davidfestal** [comment]
How does this issue related to the following: https://github.com/eclipse/che/issues/14088#issuecomment-534174598 ? Maybe it should replace it ?

@l0rd @nickboldt wdyt ?

**Comment by nickboldt** [comment]
There are two types of doc required here:

a) how do I build an airgap-compliant image?
b) how do I use a previously-built airgap-compliant image?

Part (a) is about which flags to pass to `build.sh` or `docker build` to ensure you enable the offline caching mode when building and swap in the correct overrides for docker.io/quay.io with your own registry URL

Part (b) is... now that I have a build, how do I tell `chectl` to use MY images instead of the defaults? 

So it's either two documents or one two-part document.

**Comment by amisevsk** [comment]
PR merged.
