### ISSUE TITLE
Default-host - Some resources (css, js, images) in IDE does not work

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14883]
### Describe the bug
When running Che in default host, some resources, like images or css, do not work. I've found these affected components - welcome page, preview panel, about dialogue. Probably there is some more.

Url of affected resources does not include `path` part of the ingress.

As an example take logo image from `help > about`. It points to `/webview/home/theia/node_modules/@eclipse-che/theia-plugin-ext/src/resource/che-logo-dark.svg`, which does not exist. If I check `theia-ide` ingress for port 3100, I can see:
```
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: serverb1jyhrrt-theia-ideejo
          servicePort: server-3100
        path: /serverb1jyhrrt-theia-ideejo/server-3100/(.*)
```
So the correct path here is `/serverb1jyhrrt-theia-ideejo/server-3100/webview/home/theia/node_modules/@eclipse-che/theia-plugin-ext/src/resource/che-logo-dark.svg`.

### Che version
 - [x] latest

### Steps to reproduce
1. deploy che in default-host mode
1. start workspace
1. go to `help > about`
1. image is not loaded

### Expected behavior
Resources should have correct paths and should be properly loaded. Server is sending this url in workspace config so Theia should be able to construct it:
```
{
  "runtime": {
    "machines": {
      "theia-ideejo": {
        "servers": {
          "theia": {
            "url": "http://192.168.122.66/serverb1jyhrrt-theia-ideejo/server-3100/",
            "attributes": {
              "internal": "false",
              "port": "3100",
              "discoverable": "false",
              "cookiesAuthEnabled": "true",
              "type": "ide",
              "secure": "true"
            }
          }
          ...
```

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots
![defaulthost](https://user-images.githubusercontent.com/1160903/66753635-89718700-ee94-11e9-8d7a-1366712f79ff.png)

### Installation method
   - [x] helm
Be aware that registries deployment currently does not work with helm and default-host (#14881) so you have to deploy registries manually. Just follow https://github.com/eclipse/che-devfile-registry/#kubernetes and https://github.com/eclipse/che-plugin-registry#run-eclipse-che-plugin-registry-on-kubernetes and set urls to `DEVFILE_REGISTRY_URL` and `PLUGIN_REGISTRY_URL`. Now this command should work:
```
helm upgrade --install che --force --namespace che \
--set global.ingressDomain=$(minikube ip) --set global.serverStrategy=default-host --set cheImage=eclipse/che-server:nightly \
--set cheDevfileRegistry.deploy=false --set che.workspace.devfileRegistryUrl=${DEVFILE_REGISTRY_URL} \
--set chePluginRegistry.deploy=false --set che.workspace.pluginRegistryUrl=${PLUGIN_REGISTRY_URL} \
deploy/kubernetes/helm/che/
```

### Environment
       - [x] Linux

### Additional context
https://github.com/eclipse/che/issues/13647

**Comment by mmorhun** [comment]
All missing object on UI are supposed to be retrieved via webview mechanism.
At the moment all webview resources paths are absolute. Firstly I tried to change all paths to be relative and it worked for all the use-cases I've tested, but when I created PR in Eclipse Theia repo it turned out that such approach has pitfalls in some cases and has been tried (and then reverted) before.
Also there is [PR](https://github.com/eclipse-theia/theia/pull/6465) in Eclipse Theia which reimplements webview plugin API according to the changes in VSCode spec and security requirements. So, after the PR is merged, by default, each webview instance will have a separate host (`{{uuid}}.webview.{{hostname}}` if be more specific) which is not compatible with single host strategy.
However, webviews hosts are configurable by env variable and it is possible to make everything work on single host (despite requires changes in Che Theia meta.yaml, because at the moment we cannot set env variables for IDE container from devfile). But it is not a way to go, because such approach completely looses security and any plugin would be able to access main Theia (and other plugins) data like cookies, local storage, etc.
For now I do not see a good solution for the current situation. @evidolob @l0rd @skabashnyuk do you have some ideas how we can deal with it?

**Comment by skabashnyuk** [comment]
>However, webviews hosts are configurable by env variable and it is possible to make everything work on single hos

How do you see that?

**Comment by mmorhun** [comment]
@skabashnyuk there is a [small doc](https://github.com/eclipse-theia/theia/pull/6465/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR17) in the PR.

**Comment by skabashnyuk** [comment]
So how THEIA_WEBVIEW_EXTERNAL_ENDPOINT will look like in devfile on plugin.yaml?

**Comment by mmorhun** [comment]
For now the only way is to edit meta.yaml of Che Theia.
When I tested it, I set `THEIA_WEBVIEW_EXTERNAL_ENDPOINT` to `http://192.168.99.103.nip.io` (which is the 'single host')

**Comment by mmorhun** [comment]
Issue with logo in about dialog has been fixed.

For webview resources we have more specific issues:
 - [provide logo icon for plugin webview](https://github.com/eclipse/che/issues/15324)
 - [remote plugin webview resources](https://github.com/eclipse/che/issues/14444)
