### ISSUE TITLE
Is there a way to initialize workspace with a user specific private ssh key

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#14998]
I would like to set up workspaces, which can directly checkout sources from a access restricted GitHub repo. AFAIK, there is currently no way to "single sign on". Therefore, the idea would be to use ssh authentification and initialized the users workspace with her private key. Does that sound feasible and is there maybe a mechanism for that?

**Comment by tsmaeder** [comment]
I think we support this, right?

**Comment by skabashnyuk** [comment]
@vinokurig can you suggest some workaround?

**Comment by vinokurig** [comment]
@JonasHelming All workspaces already have a predefined SSH key. To view it's public part execute `F1 => SSH: View public key...` and upload the public key to the GitHub account.

**Comment by JonasHelming** [comment]
@vinokurig Thanks, but that does not really adress the scenario. I would like to preinitialized the workspace in a way that users can directly access a git repo without any additional setup steps...

**Comment by vinokurig** [comment]
Unfortunately it is not possible yet.

**Comment by Verenchen** [comment]
Is it planned to implement something that will enable this?

**Comment by vinokurig** [comment]
We are going to apply GitHUb oAuth and upload an ssh public key by pressing a single button

**Comment by Verenchen** [comment]
It would be great if there will be a solution that is independent from GitHub.

**Comment by vinokurig** [comment]
@Verenchen If you know both private and public part of the ssh key that is already uploaded to GitHub, you can **CREATE** (SSH: Create key pair...) the ssh key in the workspace and it should be enough.

**Comment by sorekz** [comment]
@vinokurig I think the problem here is that you need a workspace for that.
When your starting point is a devfile with a repository that requires authentication, this will not work. You need to upload the ssh key to github/bitbucket/etc. before the workspace is created because it is needed for the initial git clone.

Chicken and egg. If you can't get the ssh public key that is used in every workspace (for a user) from e.g. the che account page you have to create an empty workspace to get the public key and add the repository in a second step.
