### ISSUE TITLE
Provide a way to access logs of different containers of the running Che Workspace

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15048]
### Is your task related to a problem? Please describe.
For diagnostic purposes, it would be niche to provide an ability to end-users
to access logs of different containers of the running Che Workspace. This should be an analog of 
```kubectl logs my-pod -c my-container ``` command

### Describe the solution you'd like
REST API to get the content of the logs.

### Describe alternatives you've considered
chectl command.
```chectl logs workspacName  componentName/ContainerName```

### Additional context 
https://github.com/eclipse/che/issues/15047

**Comment by sleshchenko** [comment]
From retrieving logs implementation perspective - there should not be difficulties since there is `api.d.ts#readNamespacedPodLog` in @kubernetes/client-node typescript library.

But I believe UX should be elaborated more:
- Containers name has generated values, how user gets it when workspace fails to start and Containers View is not available with Theia?
- Does user really wants to start an investigation a workspace start failure with logs? 

Maybe it's better to start with like `chectl workspace:describe workspaceName --watch` and it would expose workspace status according to data fetched from k8s api, like
<pre>
component      | container  |     status   | Memory | restarts
theia                | theia23s   |      OOMKilled   |  10Mi | 3 
exec-machine | exec123   |      Running | 250Mi | 0
database         | postgres1w3 |  Completed  |  1Gi | 5
</pre>

And then user may be interested in fetching logs, is component name is needed? probably container name is enough `chectl workspace:logs workspacName -c ContainerName`

It's not complete workflow of investigation workspace start failure, I just shared my thought and I think that workflow should be elaborated more before implementing this issue.

**Comment by skabashnyuk** [comment]
closing in prefer of https://github.com/eclipse/che/issues/15134
