### ISSUE TITLE
[Devfile] define a format and capabilities of actions

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15050]
### Is your task related to a problem? Please describe.
The goal of this task is to summarise all experiences with Che6 action, OnAppLoad, OnProjectOpen, OnAppClose and make a proposal for how to adopt it in devfile.

### Describe the solution you'd like
TBD

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/12925

**Comment by mshaposhnik** [comment]
Does it makes sense to introduce an lifecycle binding of actions as it was in Che6? I mean `onAppLoaded` `onProjectLoaded` etc ? @slemeur what's your vision on that?

**Comment by mshaposhnik** [comment]
OK since for both exec and openfile actions we need project to be already present, so it seems we can omit the phases yet. 
To avoid collisions, i would propose to not add separate entity type  for IDE actions, but just reuse existing actions with slight modifications (add autorun flag):
```
commands:
- name: run outyet
  actions:
   - type: exec
     component: go-cli
     command: go get -d && go run main.go
     workdir: ${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet
---> autorun: true
```

For openfile, just add another action type:

```
   commands:
   - name: open main
     actions:
---> - type: openfile
       workdir: ${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet
--->   filename: main.go
--->   autorun: true
```
so it will be similar of how we have different component types now.

Alternatively, the autorun flag can be in the command attribute as follows:
```
  commands:
- name: run outyet
  actions:
   - type: exec
     component: go-cli
     command: go get -d && go run main.go
     workdir: ${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet
  attributes:
---> autorun: true
```

**Comment by benoitf** [comment]
hello, what is the meaning of `autorun` ?
When does it happen ? who is responsible to run these commands ?

**Comment by mshaposhnik** [comment]
@benoitf they will be auto run when che-theia finish loading  (probably, yes, only for the first time when workspace created from devfile via factory or chectl )

**Comment by benoitf** [comment]
ok then I've an issue where I want some actions be executed on the `first` step (like after clone of projects is done) (like doing post-cloning stuff)

and some of them, each time my workspace is started (like starting my run action every time)

so I was liking the idea of the attached lifecycle

**Comment by benoitf** [comment]
@mshaposhnik and for the order ?

basically there is choice of either defining set of actions for given lifecycle or adding lifecycle to each command
but in one case I found it less readable. (if I've 50 commands, it may be difficult to quickly read what commands will be executed, when and the order) while in another case, I can read all actions defined for a given lifecycle event easily.

**Comment by mshaposhnik** [comment]
Ordering is another big question, since it makes sense only for the exec type commands, IMO, as it's no sense to put an `openfile` between 2nd and 3rd `exec`. Also its unclear how the order should behave is previous command is failed etc and if it's possible to detect such a failures from theia side etc
As for the WS loading licefycle, IMO there is not a lot of actions that can be executed without project loaded, so for me it looks like unnecessary complication of the format.

**Comment by benoitf** [comment]
> IMO, as it's no sense to put an openfile between 2nd and 3rd exec
it depends, you may run a code generator and then only open the file after code is generated

> As for the WS loading licefycle, IMO there is not a lot of actions that can be executed without project loaded, so for me it looks like unnecessary complication of the format.

it's important to me to differentiate "first workspace creation" and "next workspace startup" for example
so there at least two bindings

If I look at some competitors https://www.gitpod.io/docs/44_config_start_tasks/
there are init and before, etc

**Comment by mshaposhnik** [comment]
I just want to avoid the mess of similar kind enitites in the format. We're already have `command` and `action` entities, so adding 3rd one (named `tasks` or anything else) will embarass things even more.
So for me , say, `runOnInit` plus `runOnStartup` attributes of each action sounds much simpler. (yes we can imagine the inconvenient usecases for every format we choice, but we should orientate to simplify most common ones IMO).

**Comment by slemeur** [comment]
Hi @mshaposhnik.

We have to be very careful here and we need to think about how we can keep the devfile generic. The purpose of the devfile is not to be "che specific" and I'm concerned that we are injecting old concepts into something that does fit.

I see the `devfile` as an abstract definition of a cloud developer environment and its instance is going to be a K8S `pod`. As such, there are lifecycle events that are at different levels:
- operator
- pod
- editor
- plugin

While the scope of this issue is not to cover all possible lifecycle events - we should still be thinking at those use cases to not be limiting the adoption of the devfile and its future capabilities (as generic cloud developer environment definition). 

I believe we should start by listing the different lifecycle events we might have and study them to define the proper structure. cc @l0rd @davidfestal @benoitf

**Comment by skabashnyuk** [comment]
Che Platfom team has stopped working on this task. It seems like @mshaposhnik  and I didn't fully understand the definition of this task from the beginning. We need more clarification about the scope and implementation of directions from @slemeur and @l0rd.

**Comment by skabashnyuk** [comment]
Closing since the definition is unclear.
