### ISSUE TITLE
Plugins should have ability to spawn processes

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#15087]
We have a `tslint`  plugins which spawns a process [1]
In case of local Theia `process.argv0` is `node`, in case of Theia running on minishift
it is `/remote-endpoint/plugin-remote-endpoint`.
So, as a result a new process hangs forever.

[1]  https://github.com/Microsoft/typescript-tslint-plugin/blob/master/src/runner/index.ts#L386

**Comment by benoitf** [comment]
I assume that in that case, you need a custom endpoint environment variable to specify `process.argv[0]`

so by using a nodejs image you could tell to use node runtime

**Comment by tolusha** [comment]
@benoitf 
I don't quite get it.
Does it imply to implement something or it is matter of a configuration of the devfile?

**Comment by benoitf** [comment]
hello @AndrienkoAleksandr @evidolob Could you add your proposas there ? AFAIK You told me that you'll write it down in the issue ?

**Comment by AndrienkoAleksandr** [comment]
hello @AndrienkoAleksandr @evidolob Could you add your proposal there ? AFAIK You told me that you'll write it down in the issue ?

Hello. Maybe it make sense to rework our plugin remote runtime init container and don't use remote binary. I guess we can use remote endpoint scripts from node_modules. We can tar these scripts to archive and apply to this archive node binary. Then on start workspace we can unpack node and scripts instead of remote binary and start remote plugin endpoint. @benoitf What do you think?

**Comment by benoitf** [comment]
@dariodsa are you facing the issue ?

**Comment by dariodsa** [comment]
Yes, i can't run tslint plugin in CodeReady workspace. There is an already
open issue #14070 which links to this. If this issue is resolved, ok, but i
think that was closed automatically and the issue remains.
