### ISSUE TITLE
Support `endpoints` for components of type kubernetes/openshift

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#15124]
### Is your task related to a problem? Please describe.
No support for `endpoints` on the kubernetes/openshift components makes it impossible to expose a service/port defined in the component.

### Describe the solution you'd like
There are 2 alternatives we need to consider:
1. exposing a service defined by the component
1. exposing a port on a pod

### Additional context
The handling of `previewUrl` of commands has a very similar logic where it tries to reuse a service/ingress of an endpoint or creates one anew if not present. It would be good if we could refactor the code to be able to reuse this logic also for the endpoints on the k8s/openshift components, because the logic will be close to identical.

**Comment by sparkoo** [comment]
I don't see much analogy with previewurl. Previewurl's job is to expose public url and does not care much how it will achieve that, so we can reuse existing Service/Ingress.

On contrary devfile's `endpoints` cares about how it is done, because it's job is to touch more layers from Pod port to exposed Ingress url. We're basically merged k8s Service and Ingress into our `endpoints` with config attributes. Thus I don't think we can reuse existing service/ingress here and we must always create everything. In theory we could reuse service if endpoint is set as `discoverable: false` and `public: true` and possibly some other cases, but it would be too fragile and hard to maintain such precise attributes combos to make sense for me.

Also I would not interact with defined services inside k8s/openshift recipe at all and handle them independently. Because our `endpoint` touches Service as well, so if user defines Service inside recipe and then an `endpoint` in the component, she should know what she's doing.

wdyt? @metlos @mshaposhnik @skabashnyuk 
cc: @sleshchenko @amisevsk

**Comment by sparkoo** [comment]
fixed by #16529
