### ISSUE TITLE
[che-operator] Install and setup grafana-operator/prometheus-operator

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15137]
### Is your task related to a problem? Please describe.
Setup monitoring stack with che-operator

### Describe the solution you'd like
Setup https://github.com/integr8ly/grafana-operator and https://github.com/coreos/prometheus-operator with che-operator and connect it to che-server

### Describe alternatives you've considered
Reimplement existed deployments https://github.com/eclipse/che/tree/master/deploy/openshift/templates/monitoring with che-operator.
### Additional context
https://github.com/eclipse/che/issues/15046

**Comment by sparkoo** [comment]
We're not going to install 3rd party operators, because we don't want to support them. Instead of that, we're going to create only CRs for the operators. We leave prometheus/grafana-operator installation and management to admins. These operators then will be able to use CRs created by our operator.
Because this approach is handled in several tasks (see the description https://github.com/eclipse/che/issues/15046), I'm closing this one
