### ISSUE TITLE
Cannot open command palette in Theia when using Firefox

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15145]
### Describe the bug
Theia doesn't / can't bind the key combination `ctrl + shift + p` on firefox; attempting to use this shortcut to open the command palette just opens a new private browsing window.

### Che version
 - [x] latest 7.3.1

### Steps to reproduce
Start a workspace in firefox and press `ctrl+shift+p`

### Expected behavior
Command palette opens.

### Runtime
   - [x] Openshift 3.11

### Installation method
   - [x] che.openshift.io

**Comment by tsmaeder** [comment]
Added to epic https://github.com/eclipse/che/issues/14015

**Comment by vzhukovskii** [comment]
Actually there is a duplicated issue created in theia: https://github.com/eclipse-theia/theia/issues/1696
Studying the mozilla sources shows that this shortcut can't be neither overwritten nor disabled. 

https://hg.mozilla.org/mozilla-central/file/tip/browser/base/content/browser-sets.inc#l289
```
    <key id="key_privatebrowsing" command="Tools:PrivateBrowsing" key="&privateBrowsingCmd.commandkey;"
         modifiers="accel,shift" reserved="true"/>
```

As a workaround, which provided in https://github.com/eclipse-theia/theia/issues/1696, we can rebind this shortcut to `F1`

**Comment by azatsarynnyy** [comment]
I want to summarize.

**Theia**
![image](https://user-images.githubusercontent.com/1636395/71268410-8d6acb00-2355-11ea-8cda-bd860cd31b49.png)

**VSCode Online**
![image](https://user-images.githubusercontent.com/1636395/71268425-9b205080-2355-11ea-9099-c92c644f15ec.png)

**VSCode Electron**
![image](https://user-images.githubusercontent.com/1636395/71268312-5399c480-2355-11ea-9612-eb1f24380cca.png)

As you can see, there are different hotkeys in all cases. Theia has its own hotkey `F1` for opening a Command Palette. It works well in all browsers. Also, it's supported by VSCode.

I don't see a reason why a hotkey from VSCode Electron version has to be supported by Che Theia.
Especially, taking into account that it's a FireFox reserved hotkey that can not be overridden.

I'd say `Ctrl+Shift+P` it's rather a "hidden" feature in Theia since this is not declared anywhere.
I guess that `F1` for opening Command Palette is more know and more spread hotkey.

WDYT guys?
cc/ @slemeur

**Comment by slemeur** [comment]
Adding @beaumorley for awarness.

Thanks for the precise analyze and studying the other alternates. I'm +1 for closing the issue. Eventually, we could add the support for `Alt+x`, depending on user feedbacks. Otherwise, I like having `F1` as being the hotkeys working for every browser.
