### ISSUE TITLE
Support Codicons in Command Palette

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15262]
### Describe the bug
When using the openshift connector in Che, in the command palette, we see strange characters in messages like `$(plus) Provide new URL.

![Selection_466](https://user-images.githubusercontent.com/650571/69268163-e74d6900-0bce-11ea-92db-b739e8efa0fb.png)

`$(plus)` should be a plus icon (as we can see in vscode)

![Selection_470](https://user-images.githubusercontent.com/650571/69268123-d69cf300-0bce-11ea-8b29-6e25a14c3c61.png)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

**Comment by benoitf** [comment]
I think it's theia upstream issue with handling octicons

**Comment by benoitf** [comment]
https://github.com/eclipse-theia/theia/issues/5412

**Comment by tsmaeder** [comment]
Unless this is important for release planning, we should not duplicate theia issues. Closing as duplicate.

**Comment by slemeur** [comment]
@tsmaeder An end-user, has no idea what theia is. If he is using Che, he is using Che and will report issue here. The fact that there is a issue on a component that is used in Che is "internal". Here you are forcing a user to track an issue on another repository, while the user will have no idea of when this will be fixed in Che.

**Comment by slemeur** [comment]
Once the issue upstream will be fixed and integrated in Che, this is an actual issue for Che and as such, should not be closed.
thanks.

**Comment by RomanNikitenko** [comment]
I investigated the issue and commented the result [here](https://github.com/eclipse-theia/theia/issues/5412#issuecomment-573559869)

We have to upgrade to the latest Moncao in order to get this support. See https://github.com/eclipse-theia/theia/issues/5412#issuecomment-574072885

So the issue depends on https://github.com/eclipse-theia/theia/issues/6900

**Comment by azatsarynnyy** [comment]
Fixed by upgrading Monaco editor upstream https://github.com/eclipse-theia/theia/pull/7149
![image](https://user-images.githubusercontent.com/1636395/77831506-42243d80-7138-11ea-9d03-5b62ac493167.png)
