### ISSUE TITLE
Enable chectl to install Che through OLM when appropriate

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#15279]
### Is your enhancement related to a problem? Please describe.

Currently, `chectl` allows installing, updating or deleting Che on an OpenShift 4.2 cluster. But it still uses the raw yaml method (deploy the operator, roles, service account etc ... through yaml files) instead of using the OLM (OperatorHub)-compatible method (by subscription to the OLM package channel.).

More than that, trying to update or delete, with `chectl`, a Che installation that was initially installed through OperatorHub, will not work propertly, and also lead to inconsistencies.  

### Describe the solution you'd like

In `chectl`, we should have an `olm` installer, and make it the default installer on Openshift 4.2 cluster.
Additionally, we should probably test whether an existing Che operator deployment was initially installed through OLM (easy to do through annotations) before trying to either update or delete it through alternate installers.  
With the new `olm` installer, users would also be able to install Che in a given namespace **without having admin rights** since it's mainly subscribing to an operator OLM package already available in one of the available OLM catalogs.

### Describe alternatives you've considered

For now it has been said that documentation should clearly state that, on OpenShift 4.2, OperatorHub and `chectl` installation methods should never be mixed.
However this doesn't fully remove the risk of getting errors due to this situation.

**Comment by nickboldt** [comment]
So this is a new install approach for OCP 4.2+? 

Questions for downstreaming:

* since crwctl is only recommended for OCP 3.11, we should either omit this option from crwctl, or include it but don't recommend it (since it would only be useful if a user is choosing to use crwctl instead of operatorhub on OCP 4 [not recommended], or the target OCP 3.11 has operatorhub installed in it manually).

* what happens if the olm approach is used on OCP 3.11 w/ operator hub installed and the operator metadata includes digests?? I have the impression that OCP 3.11 doesn't support image digests so... would that break?

**Comment by davidfestal** [comment]
@nickboldt
- As soon as this new OLM installation method will come from upstream chectl into downstream crwctl, we would be able to make crwctl a usable / recommended / supported installation method for OpenShift 4 as well, as long as crwctl installs with the new OLM installation method by default on this platform.
-  I assume OLM method would not be allowed on Openshift 3.11 in crwctl, and in such a case crwctl would issue an error message. Am I right @tolusha ?

**Comment by AndrienkoAleksandr** [comment]
> I assume OLM method would not be allowed on Openshift 3.11 in crwctl, and in such a case crwctl would issue an error message.

Yes, it is.
