### ISSUE TITLE
Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side.

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#15277]
### Is your enhancement related to a problem? Please describe.
The delay between "the user clicks on the task" and "the output terminal is getting shown". The user doesn't really know if the action (clicking on the task) has been taken into account. When the connectivity is not great, this lead to very inconvenient UX. 

### Describe the solution you'd like

We should look at how we can first open the terminal output, so it gives a visual feedback to the end-user, display an indicator inside of it (ex: "Task "{task-name}" - Connecting....") and then do the necessary background connection between the task running in the container and the output displayed in the IDE

**Comment by tolusha** [comment]
it sounds like a Theia issue

**Comment by vitaliy-guliy** [comment]
On che.openshift.io vanilla Theia runs tasks very fast. It looks like `eclipse-che-theia` extensions and `eclipse-che` plugins forces to have a 2 seconds delay in running of `shell` tasks and around 5 seconds for `che` tasks.

Will create a detailed report on the process of executing of `che` tasks, measuring the execution time.

**Comment by tsmaeder** [comment]
Making the UI async might also help with https://github.com/eclipse/che/issues/15541

**Comment by vitaliy-guliy** [comment]
Timings benchmarks of execution of Che and Theia (shell) commands on che.openshift.io

| **1. Theia task** | | |
|--|--|--|
|1st execution | getting workspace tasks, resolve task macroses          | 1.5 seconds |
|| launching task on the backend                                                            | 0.2 seconds |
|| **Appeparing the terminal in**                                                             | **1.7 seconds** |
2nd, 3rd execution | getting workspace tasks, resolve task macroses   | 1.3 seconds |
|| launching task on the backend                                                            | 0.2 seconds |
|| **Appeparing the terminal in**                                                             | **1.5 seconds** |
| **2. Che task** | | |
|1st execution | getting workspace tasks, resolve task macroses          | 1.5 seconds |
|| launching task on the backend                                                            | 2.7 seconds |
|| **Appeparing the terminal in**                                                             | **4.2 seconds** |
2nd, 3rd execution | getting workspace tasks, resolve task macroses   | 1.3 seconds |
|| launching task on the backend                                                            | 1.9 seconds |
|| **Appeparing the terminal in**                                                              | **3.2 seconds** |

The reasons of such big delay are:
- handler for Che tasks is located in `tasks-plugin`
- too many communications between Theia and plugins when executing a command
- Che terminal is opened from the `task-plugin` using `theia.window.createTerminal()` method of Plugin API, instead of being opened from Theia task service in task extension.

It was tested with a full set of plugins, with few plugins and without plugins. The conclusion: amount of plugins does not affect on the delay.

**Comment by tsmaeder** [comment]
@vitaliy-guliy all these measurements seem very long in comparison to running just plain Theia on my laptop. Do you think it's just the lower-powered environment compared to a laptop or some overhead introduced by OpenShift/Kubernetes/Storage?

**Comment by vitaliy-guliy** [comment]
That local Theia works fast enough could be because your laptop is quite powerful. But I think it's mostly because everything's running locally. In this case, there is no delay that network adds.
And yes, OpenShift/Kubernetes affects on the task running, but we need to investigate how we can test it.

**Comment by vitaliy-guliy** [comment]
Could potentially be related to  https://github.com/eclipse-theia/theia/issues/7496
