### ISSUE TITLE
"chectl server:delete" doesn't remove openshift project itself

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15280]
# Describe the bug

`chectl server:delete` (and `crwctl server:delete`) doesn't remove openshift project itself. As a result, you have to manually run `oc delete checluster codeready -n ${OPENSHIFT_PROJECT}; oc delete project ${OPENSHIFT_PROJECT} &` if you want to reuse the same project name for a redeployment.

Yet according to the inline help:

```
$➔ crwctl server
control 'CodeReady Workspaces' server

USAGE
  $ crwctl server:COMMAND

COMMANDS
  server:delete  delete any CodeReady Workspaces related resource << any? does that mean ALL?
  server:start   start CodeReady Workspaces Server
  server:stop    stop CodeReady Workspaces Server
  server:update  update CodeReady Workspaces Server
```

Two problems here:

a) start does more than start the server: it also creates the project namespace; yet stop only stops an existing server. So this feels like we're not using good parallelism. Perhaps we should have `server:create` (to create the project and deploy) as well as `server:start` (to just start an existing deployment) ?

b) `server:delete` won't remove the project? What's the usecase? "I don't want **this** Che/CRW but I do want the `che`/`workspaces` project so I can manually deploy a new Che/CRW operator?" Why not delete both, and let `server:create` create a new project again?

### Che version

7.3.2

### Steps to reproduce

`chectl server:delete`

### Expected behavior

Everything created by `server:start` should be deleted.

### Runtime
   - [x] Openshift (include output of `oc version`)

```
$➔ oc version
Client Version: openshift-clients-4.2.0-201910041700
Server Version: 4.2.0
Kubernetes Version: v1.14.6+2e5ed54
```

See also https://issues.jboss.org/browse/CRW-499

**Comment by sleshchenko** [comment]
> chectl server:delete (and crwctl server:delete) doesn't remove openshift project itself. As a result, you have to manually run oc delete checluster codeready -n ${OPENSHIFT_PROJECT}; oc delete project ${OPENSHIFT_PROJECT} &

`oc delete checluster codeready -n ${OPENSHIFT_PROJECT}` o_O
chectl, crwctl has the code that delete CheCluster CR https://github.com/che-incubator/chectl/blob/89a144420dbe0943ec3b5c09765d9fa3b851a43d/src/tasks/installers/operator.ts#L362
if CR is not deleted after `server:delete` -n ${OPENSHIFT_PROJECT} then it's a dedicated issue, please register it @nickboldt 

Also, I believe if namespace exists - it should not prevent `server:start` to do its work (until minishiftaddon is used as installer). So, if you have any issues with deploying Che in precreated namespace - please register a dedicated issue @nickboldt 

> a) start does more than start the server: it also creates the project namespace; yet stop only stops an existing server. So this feels like we're not using good parallelism.

If I'm not mistaken - helm chart works in exactly the same way, create namespace but do not remove it.
I think it may be related to the fact that you may have common stuff in the same namespace, and it would not make user happy if chectl would remove the whole namespace.
Not sure how real this use-case is, but we can imagine there is `tools` namespace that contains (Che deployed with kubernetes + Monitoring and Tracings stuffs like Gragana, Jaeger, ...). And now user wants to redeploy Che in the same namespace with operator instead of helm, but Tracing&Monitoring stuff should not be touched.
^ it may be no real use case, but we definitely must be carefully with removing whole namespace. Maybe we could go with a special option `--remove-namespace` with default value false, or we also can ask users if they want to remove namespace(something like confirmation dialog during server:update)

> Perhaps we should have server:create (to create the project and deploy) as well as server:start (to just start an existing deployment) ?

I agree that we might need to revise our server related commands. And just wanted to mentioned that minikube/minishift works in the same way. I mean `start` commands starts VM and creates it if missing. So, I'm not sure if we really need two commands for it.

**Comment by tolusha** [comment]
I close this issue as won't fix.
`server:delete` command is not designed to remove namespace.
