### ISSUE TITLE
[POC] TLS by default

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15313]
### Is your task related to a problem? Please describe.

There are several concerns raised here in comments https://github.com/eclipse/che/issues/14742 and we think
that during implementation we may identify quite a lot of corner cases.

### Describe the solution you'd like
The goal of this task is:
 -  to start the implementation of the task "TLS by default".
 - Identify as much as possible conner cases.
 - Create appropriate issues to implement this task completely.

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/14742

**Comment by l0rd** [comment]
Do we really need to have this second issue? I mean now you have this issue + #1472 in your backlog, both with P1, but it looks like the same issue no? I am trying to understand the benefits because from outside it's hard to understand the differences between the 2 issues whereas one single issue for this topic makes things clear.

**Comment by skabashnyuk** [comment]
@l0rd the idea is to have something that we can deliver in one sprint. PLF team think that we are not able to deliver https://github.com/eclipse/che/issues/14742 but we can try to handle https://github.com/eclipse/che/issues/15313

**Comment by l0rd** [comment]
@skabashnyuk got it

**Comment by tolusha** [comment]
Testing evn is minikube

**Comment by mmorhun** [comment]
I believe this PoC is done in https://github.com/che-incubator/chectl/pull/476.
Further work will be done in terms of https://github.com/eclipse/che/issues/16052.
