### ISSUE TITLE
Don't use marketplace in node/node2 Che plugins.

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15322]
We are currently referencing the VS Code marketplace in our node/node2 debug Che plugins. We need to host the vsix file on github.com/redhat-developer and reference it there.

See also: [plugin registry] Do not reference marketplace.visualstudio.com in plugin registry meta.yaml https://github.com/eclipse/che/issues/14573

**Comment by amisevsk** [comment]
Add [asciidoctor](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/joaompinto/vscode-asciidoctor/2.7.6/meta.yaml#L15) to the list.

**Comment by tsmaeder** [comment]
@amisevsk I created this issue as a task for the languages team for planning purposes. We know nothing about the asciidoctor plugin, so leaving that task for whoever added it to the registry.

**Comment by nickboldt** [comment]
I think we can close this because:

1. Node-debug is removed - https://github.com/eclipse/che-plugin-registry/pull/302
2. Node-debug2 old version is deprecated with auto-update to latest version which is NOT on VSC marketplace: https://github.com/eclipse/che-plugin-registry/commit/38b1387a96604f01ce989c135a850bfaa1cbd855
3. asciidoctor is now available from GH releases, and older version 2.7.6 is deprecated w/ auto-update - https://github.com/eclipse/che-plugin-registry/commit/e58ab674e9100958258985e7e6441a9ab18c080b and https://github.com/eclipse/che-plugin-registry/commit/4a4bb7241867045ca1eb53613b668d97885609f8

**Comment by nickboldt** [comment]
Note that instead of hosting files on GH we elected to host them on https://download.jboss.org/jbosstools/vscode/ as that's where a lot of existing RH-built projects publish their bits.
