### ISSUE TITLE
My image relies in root access with "/root" as home, Worked well in che 6. I can not make it work in Che 7

### ISSUE THREAD

**Issue by agocorona** [eclipse-che/che#15370]
I have all my devel. environment configured in /root/.* configuration files. It is difficult to make otherwise since the installers do it that way. If I move them to / it does not work since the user in Che 7 has no root privileges and the programs are hardcoded to find it in /root.,

**Comment by agocorona** [comment]
In the other side "su" does not work :
> su
su: must be run from a terminal

**Comment by agocorona** [comment]
After gaining access to terminal, [using python](https://www.reddit.com/r/AskNetsec/comments/7xxo85/su_must_be_run_from_a_terminal/):

$ su
su: Cannot determine your user name.

**Comment by agocorona** [comment]
\>whoami
whoami: cannot find name for user ID 1121490000

in my local docker box:
\> whoami
root

**Comment by ibuziuk** [comment]
Basically, it is not expected that anything will be run as a root in the general case due to security reasons. basically, the rule of thumb is that all the dependencies should be available in the dockerimage, so you will not need to install anything after workspace startup. Also, bear in mind that `installers` concept is deprecated in Che 7

**Comment by amisevsk** [comment]
From 
```
>whoami
whoami: cannot find name for user ID 1121490000
```
It looks like you're running on OpenShift. OpenShift does not allow containers to run as root, and instead assigns a semi-random UID to containers.

**Comment by filips123** [comment]
But why? If everything is on container, would there be any risk when running as root?

Also, is it possible to work around this with using custom container image which allows root?

And I wanted to ask another question related to custom images. If you create your own Devfile for your own stack, is it possible to point it directly to your Dockerfile on GitHub without publishing it do Docker Hub?

**Comment by amisevsk** [comment]
> But why? If everything is on container, would there be any risk when running as root?

If your container process is running as root, and there is any vulnerability in the container engine that allows escape, then that process has root access to the underlying system. It's described in the [OpenShift docs](https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines), and there are various articles, e.g. [here](https://americanexpress.io/do-not-run-dockerized-applications-as-root/) that explain why containers should not run as root.

> Also, is it possible to work around this with using custom container image which allows root?

On OpenShift, no, it's a platform restriction. On Kubernetes, you can run a privileged container or set UID as desired. If you're running locally, you can use minikube instead of minishift or crc and configure it as required.

> And I wanted to ask another question related to custom images. If you create your own Devfile for your own stack, is it possible to point it directly to your Dockerfile on GitHub without publishing it do Docker Hub?

In general, no, Che does not support building dockerfiles at runtime. If you are running locally (e.g. via minikube), you can build the image you want to use inside the local cluster and reference it as normal:
```bash
eval $(minikube docker-env)
docker build -t <your-image> ...
```
After this, you can reference `<your-image>` in a devfile and it will work.

**Comment by filips123** [comment]
And on OpenShift you have to publish image to Docker Hub?

**Comment by amisevsk** [comment]
@filips123 As far as I know, there are no plans to support building dockerfiles in Che -- that's rather out of scope and there are better tools for that (e.g. OpenShift supports [builds and image streams](https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/builds_and_image_streams.html)). If you are running a cluster locally using minishift you can do the same as with minikube: 

```
eval $(minishift docker-env)
```
