### ISSUE TITLE
Che plugin icons degrade under light theme - should just use icon (no wordmark)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15436]
### Describe the bug

Under the dark theme, all the Che icons say "Eclipse Che" when you open the Plugins view from CTRL-SHIFT-J or View > Plugins.

![image](https://user-images.githubusercontent.com/227597/70455635-a2ed1480-1a7a-11ea-88cb-50971760f235.png)

But on the light theme, the text nearly disappears (white text on light grey background), leaving a big space between the icon and the content.

![image](https://user-images.githubusercontent.com/227597/70455492-691c0e00-1a7a-11ea-85f8-48878a345ebd.png)

Perhaps we should remove the text from the icon used in Che's plugin view panel?

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.3.2, 7.3.3

### Steps to reproduce

Start a workspace. Switch to light theme. CTRl_SHIFT-J or View > Plugins to toggle the plugins view open/closed. Note icons. 

### Expected behavior

Should either have a wordmark that works on light theme, or JUST the Che icon (no text).

Removing text is simpler -- the text is not needed, since everyone using Che has seen its icon so the need to co-brand the icon w/ the wordmark should be non-existent.

**Comment by ibuziuk** [comment]
Adding P1 label since this affects CRW

**Comment by amisevsk** [comment]
Related: https://github.com/eclipse/che/issues/14510

**Comment by ericwill** [comment]
Chopping off the text would work, but does it really make sense (from a UX perspective) to show the same logo for every plugin?

I like the approach from #14510 because I think it makes more sense to store the icon of each plugin locally within the registry. Maybe have an `images` folder in every plugin folder that contains the icon? There was a concern about licensing of the images but if we are pulling them from the upstream extension's GitHub I don't think it's an issue.

**Comment by amisevsk** [comment]
@ericwill I agree that #14510 is the way to go eventually, but it also depends on being able to resolve the relative icon URLs -- if the plugin registry serves e.g. `/icons/jdt.svg`, Theia will need to make that reference absolute before showing it to the user.

This issue is somewhat separate, as we currently default to using the same svg everywhere: https://www.eclipse.org/che/images/logo-eclipseche.svg. Fixing this issue would be as simple finding a plain Che logo hosted somewhere statically and replacing the links in the plugin registry.

**Comment by ericwill** [comment]
In that case I suggest we merge the existing PR for #14510 and leave the question of icon serving/storing for another day. At least this way we get some interim benefit of not having the same icon for every plugin in the list.

**Comment by nickboldt** [comment]
This no longer affects downstream directly as we've removed the Che icons from CRW's plugin view.

https://issues.redhat.com/browse/CRW-561

So... if everyone is cool with the ugliness in the light theme as it stands today in Che, then we can close this in favour of #14510 

> In that case I suggest we merge the existing PR for #14510 and leave the question of icon serving/storing for another day.

I don't see a PR linked from that issue. Am I blind?

**Comment by ericwill** [comment]
> So... if everyone is cool with the ugliness in the light theme as it stands today in Che, then we can close this in favour of #14510
> 
> > In that case I suggest we merge the existing PR for #14510 and leave the question of icon serving/storing for another day.
> 
> I don't see a PR linked from that issue. Am I blind?

There is [one](https://github.com/eclipse/che-plugin-registry/pull/221) but it's closed. I should have been more clear, I meant adopting an approach similar to that PR.

I am fine with closing this issue if we are going to go with #14510.

**Comment by ericwill** [comment]
Closing in favour of #14510
