### ISSUE TITLE
New workspace is required for each user? 

### ISSUE THREAD

**Issue by sudheerherle** [eclipse-che/che#15442]
## Summary
Is new workspace required to be created for each user?
## Relevant information
I am sorry for my ignorance. I have a basic question. Is it necessary to create new workspace for each user in multi user mode? If so, it would take long time to load the workspace when a user logs in. Isn't it?

**Comment by amisevsk** [comment]
In general, each user manages their own workspaces, this allows each user to define the plugins/environment they need for their use-case. Che workspaces are intended to be quick reproducible environments (so if you and I use the same devfile to start a workspace, we're working in the same environment with the same dependencies). As an example, if you wanted to work on the Che plugin broker (one of our components), you could simply navigate to

```
<your-che-url>/f?url=https://github.com/eclipse/che-plugin-broker/
```
and have the same development environment I use to develop the plugin broker (this is because the github repo contains a [devfile](https://github.com/eclipse/che-plugin-broker/blob/master/devfile.yaml)).

From my experience, workspace startup is generally around 30 seconds, often faster depending on the cluster and images included.

**Comment by l0rd** [comment]
@sudheerherle your question ("Is new workspace required for each user") is not clear.

If you want to know if every user uses a distinct workspace or if a workspace is shared among multiple users the answer is that every user has his distinct workspace. He can more then one workspace and these will be available for himself only.

If the question is a user needs to spend time to manually create his first workspace the answer is not necessarily. As @amisevsk pointed out in previous comment a devfile can be used to automate the creation of a workspace.

Hopefully you will find helpful at least one of the answers we have provided.

**Comment by sudheerherle** [comment]
My use case is that I have to build a stack and make all of my customers use the same stack. So 100 users will have a workspace each with the same stack. Thanks! Both the answers have helped.
