### ISSUE TITLE
Latest plugin registry does not include theia/machine-exec versions 7.3.2, 7.3.3

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15444]
### Describe the bug
The master branch of the plugin registry does not include che-theia and che-machine-exec plugins for version `7.3.2` or `7.3.3`. This means any user who manually added these plugins to a devfile will not be able to start workspace after rolling out a new update.

### Che version

 - [x] latest (not present in 7.5.1 either)
 - [x] nightly

### Expected behavior
Release `x.x.x` > `y.y.y` should have all plugins in `y.y.y`.

### Additional info
Impact should be minimal since the editor and machine-exec are typically controlled via the default editor/plugins properties, so devfiles automatically "update" to the current release on rollout.

**Comment by amisevsk** [comment]
Fixed by PR https://github.com/eclipse/che-plugin-registry/pull/319 but this does not apply to 7.5.1 release.

**Comment by nickboldt** [comment]
Alternative idea...

can the plugin broker, if it is asked for a version that doesn't exist... simply grab /latest as a fallback behaviour? Better that than:
* forced hardcoding of old versions / dead boilerplate code
* breaking compatibility when we forget to push 7.y.z+1 versions into master

Because your fix only works for 7.3.2 and 7.3.2, and you're missing 7.5.1 which kinda proves my point -- it's easy to forget about point releases. 

So.. either have 7.3.z requests "fall back" to 7.3.0 if the zth plugin is not found, or fall back to `/latest` when zth plugin not found.

**Comment by amisevsk** [comment]
Maybe, I'd say create an issue for that feature request. Worth noting also that 7.5.1 is already in `master`. I'm reluctant to try to "magically" fix problems in devfiles.

**Comment by nickboldt** [comment]
related issue https://github.com/redhat-developer/rh-che/issues/1396
