### ISSUE TITLE
Make it possible to customise images for dev containers

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15476]
In this issue I want to discuss the way in which we would have an ability to customise images used in dev containers. 

Right now the whole list of images which are used in dev containers is located in https://github.com/eclipse/che-devfile-registry/blob/master/arbitrary-users-patch/base_images and we don't have a good way to patch/customise only one of them, for example, install `yarn` into registry.centos.org/che-stacks/centos-nodejs or unset some `env` in che-java11-maven.

I suggest to move all dockerfiles from che-devfiles-registry to https://github.com/che-dockerfiles as @benoitf  did for dockerfiles which are used in che remote plugins. For this we'd need to create a repository  for each of them in https://github.com/che-dockerfiles and add github actions to build and publish. In that case in che-devfile-registre we will have only devfiles.

WDYT @benoitf @amisevsk @tsmaeder @l0rd

**Comment by tsmaeder** [comment]
What kind of customizations do you have in mind? Can you give an example?

**Comment by svor** [comment]
> What kind of customizations do you have in mind? Can you give an example?

As I wrote in the description: for example install `yarn` into `che-nodejs8-centos` image (it has just npm) or unset `MAVEN_CONFIG` environment variable for maven based images.

**Comment by amisevsk** [comment]
I agree that we likely need some way to build customized (i.e. not plain community images) for Che workspaces, but I worry about centralizing it as we did for the stacks -- the repo to build stack devfiles was very complicated and full of undocumented fixes. Basically it was a fragile repo that nobody would want to touch. Since the arbitrary UID patch is image-agnostic, I would suggest our approach be
1. For any image that needs additional customization (java-maven when using community, a node image with yarn), we create a repo in `che-dockerfiles` with the necessary changes.
    - For images that do not need any customization, stick to community images
2. Update the arbitrary UID patch to use the `che-dockerfiles` images as a base, where necessary. 

I'd prefer to keep the images we use for workspaces as simple (and as close to community) as possible. Any dockerfiles we create in `che-dockerfiles` should solve a *specific* problem, such as 
- "the maven community image is incompatible with `mvnw` if you override the entrypoint", or
- "there is no node image commonly available that includes yarn"

One of the benefits with the way we're doing CI for the devfile registry is that if we want to swap out the base image used for e.g. `java-maven`, we need only update the `base_images` list and the change will automatically propagate.

**Comment by tsmaeder** [comment]
> Update the arbitrary UID patch to use the che-dockerfiles images as a base, where necessary

I would do it the other way around, t.b.h: the arbitrary-users-patch takes community images and makes them usable on OpenShift.  These OS-capable images can serve as a base for multiple other images, for example one including yarn, but maybe we have a second one that usese
