### ISSUE TITLE
Support Che tasks for multi-root workspaces

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15540]
### Is your enhancement related to a problem? Please describe.
At the moment by default user gets `/projects` as workspace folder.

![example_projects](https://user-images.githubusercontent.com/5676062/71125731-30a1d000-21f0-11ea-8c9a-bc6cfaf9d8a3.png)

As you can see there are `theia` and `che-theia` projects and all defined in `devfile` `che` tasks are stored to `/projects/.theia/tasks.json` file.   
  
### Describe the solution you'd like
We can consider the same example for case when user has multi-root workspace. For this case there are two workspace folders: `theia` and `che-theia`.  
According to https://code.visualstudio.com/docs/editor/multi-root-workspaces#_tasks each workspace folder can contain `tasks.json` file with the corresponding configurations.

So user can have a set of task configurations for `theia` project and a set of task configurations for `che-theia` project:
- only `theia` scope configurations are available for running if `theia` workspace folder is open
- only `che-theia` scope configurations are available for running if `che-theia` workspace folder is open
- `theia` and `che-theia` scope configurations are available for running in multi-root case

I think we should provide opportunity to define in a `devfile` `source` field for a `che` command to store this one as task in the corresponding `tasks.json` file.

**Comment by sunix** [comment]
Should this issue be part of https://github.com/eclipse/che/issues/15529 ?
If i understand we could have a kind of `project` target.

**Comment by tsmaeder** [comment]
Generally, is it ok to manipulate "tasks.json" directly? Isn't there API that might take care of multi-root issues?

**Comment by RomanNikitenko** [comment]
@tsmaeder 
I think using API doesn't help us to solve the issue.

I created the issue to provide the mechanism how we can match a task from a `devfile` to the corresponding workspace folder for multi-root workspace.
So we should have some field like `scope` or `source` for `che` command in a `devfile` to know which config file should be used to store a task.

**Comment by tsmaeder** [comment]
VS Code also allows to store tasks globally, into the workspace definition file.

**Comment by tsmaeder** [comment]
@tsmaeder actually, I don't think it does :-(

**Comment by tsmaeder** [comment]
Since we're trying to remove obstacles to "multi-root" workspaces, we're taking this on in this sprint.
My approach would be the following:

* Override TaskConfigurationManager to integrate the devfile as a source for global TaskConfigurations.
* Make the tasks in devfile accessible as a resource (tasks.json) that can be opened in the editor. Read-only until we are ready to sync back to the devfile.

Currently, all che tasks are global tasks. If we get support for project-specific tasks in the devfile, we will need to sync to the .theia/tasks.json file. 
What worries me a bit is that folks _will_ check that info into their code repo. Should we really replicate checked-in tasks to the devfile? Shouldn't we rather just leave that in the repo? If we check out the source again in another workspace (or the same workspace), the tasks will be there anyway, even if we don't replicate them to the devfile.
@RomanNikitenko what do you think?

**Comment by sunix** [comment]
To me we should avoid to confuse the user.
Exposing Che commands in tasks.json AND devfile (as workspace config) AND devfile.yaml (in source code in some case) IS CONFUSING FOR THE USER.

So rather than going further in multi-root workspaces support for task ...
... I suggest that we rethink how Che tasks works at the moment and make it easier to edit, view and share through the devfile.

**Comment by tsmaeder** [comment]
@sunix so what would are you suggesting concretely?

**Comment by sunix** [comment]
- do not show Che tasks in tasks.json but load it in memory from the devfile (as workspace config)
- from the IDE a way to dynamically edit the devfile (as workspace config) and particular the che tasks
- have a way to synch the devfile (as workspace config) into a devfile.yaml of a project

**Comment by tsmaeder** [comment]
I think the solution I sketched would fulfill point 1 and 2, no?

**Comment by sunix** [comment]
In your solution you are still using tasks.json, no ?

**Comment by tsmaeder** [comment]
No, I would just call the Resource tasks.json. It would be backed by the devfile directly, not a disk file.

**Comment by davidwindell** [comment]
I like the idea of hiding the devfile tasks in the workspace BUT I really think it should at least be possible to extend these tasks via a yml file in the project repo.

**Comment by tsmaeder** [comment]
@davidwindell would you agree that when you put a tasks file inside a project, it would make no sense to replicate those tasks to the devfile?

**Comment by davidwindell** [comment]
Yes, I agree as otherwise it would be a maintenance nightmare. The benefit of in-repo tasks is that we don't have to give our developers access to edit the devfile registry (where all of our ~50 projects are) just to add tasks that are re-useable.

**Comment by sunix** [comment]
Che tasks cannot be decouple from: 
- projects
- components/container where these are going to be executed

Storing just tasks (not devfile) in a project git is not a generic maintainable option in my opinion.
But you can have the devfile registry with a git repo(s) backend where your developers could have write access with moderations (PR) just like a normal git project.

The best option maybe could be to improve the devfile registry and be able to register projects that have devfile.yaml file in it.

**Comment by tsmaeder** [comment]
Once https://github.com/eclipse-theia/theia/pull/7620 is merged, we'll have to update che-theia because the type of TaskConfiguration._scope has changed and is no longer assignement-compatible with the type we're using in the che tasks API transport level. Just making it into `string | number`makes the code compile again.
