### ISSUE TITLE
Run E2E typescript selenium tests against Eclipse Che with OS OAuth support

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15585]
### Is your task related to a problem? Please describe.
We need to run E2E typescript selenium tests against Eclipse Che deployed to OCP with OS OAuth option enabled.

### Describe the solution you'd like
There are **RegularUserOcpCheLoginPage** object which should be adapted to first OS user login workflow in Eclipse Che with OAuth.

### Additional context
It's especially needed for downstream projects.

**Comment by dmytro-ndp** [comment]
The tests should be more flexible and not stick to certain provider name [like here](https://github.com/eclipse/che/blob/master/tests/e2e/pageobjects/openshift/OcpLoginPage.ts#L48), and work against OCP
1) with identity provider with title differ from `htpasswd`;
2) without page with list of identity providers at all.

**Comment by SkorikSergey** [comment]
> The tests should be more flexible and not stick to certain provider name [like here](https://github.com/eclipse/che/blob/master/tests/e2e/pageobjects/openshift/OcpLoginPage.ts#L48), and work against OCP
> 
> 1. with identity provider with title differ from `htpasswd`;
> 2. without page with list of identity providers at all.
 
I will update OcpLoginPage page object to use TS_OCP_LOGIN_PAGE_PROVIDER_TITLE property instead of "htpasswd".
Identity providers list is checked in RegularUserOcpCheLoginPage page object - https://github.com/eclipse/che/blob/4abe4c9d53a7af810998634edbd59a733f7e4dd5/tests/e2e/pageobjects/login/RegularUserOcpCheLoginPage.ts#L29
