### ISSUE TITLE
Add README for each plugin

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#1567]
To help people who want to contribute plugins, extend them, or just understand all features provided, having a short README per plugin describing the plug-in's main features would be helpful.

**Comment by wernight** [comment]
I see there is something already on https://eclipse-che.readme.io/docs/plug-ins. Possibly a README from the plugins directory pointing there would be the simplest solution.

**Comment by TylerJewell** [comment]
We are working to provide better docs in the wiki on these areas.  And then plugins that have detailed analysis are getting READMEs.  Since this request is a bit open ended, I am going to close this, as this is a practice that we are baking into our process, but it's not something that has a firm begin / end completion.
