### ISSUE TITLE
[devworkspace] Make CheRestAPI optional and depending on che-theia editor

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15790]
### Is your task related to a problem? Please describe.
Currently, DevWorkspace Controller always applies prerequisites during workspace start even if they are not needed, like in the case of CloudShell:
- It does not need emulated REST API
Note: we agreed to provision REST API only in cases when `eclipse/che-theia` editor is configured via Devfile.

**Comment by amisevsk** [comment]
This issue, along with https://github.com/eclipse/che/issues/16313, are something I think are best addressed by using a cloud-shell specific operator when the only object we want to deploy is the cloud-shell. Otherwise, we're adding a lot of complexity in the operator to support one specific use-case. Within the scope of *workspaces*, I don't see a good use-case for supporting optional PVC, rest APIs, and plugin registry; I think of cloud shell as related but separate from workspaces.

I have a proof-of-concept operator available [here](https://github.com/amisevsk/cloudshell-operator) that serves to create only what's needed for a cloudshell instance. Currently, oauth is enabled, but webhooks are not yet implemented. Worth noting also that it's only ~1k lines of code, even with the operator-sdk boilerplate.
