### ISSUE TITLE
Allow OLM installation through CatalogSource and related docker image

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#15802]
### Is your enhancement related to a problem? Please describe.

Currently we can only install Che on OLM with an OperatorSource that points to a related Quay.io application.
This makes automated testing of OLM installations / updates uneasy.

### Describe the solution you'd like

We should also build the required docker image of a dedicated catalog, in order to install directly through a CatalagSource, as described in https://github.com/operator-framework/operator-registry

**Comment by flacatus** [comment]
Inside of OLM folder we have some files whit this extension: ***.yaml.diff** and when we build the dockerfile with `operator-framework` failed because the operator is trying to read this files like a yaml files. Should keep this files or delete them? 
PD: EG (`https://github.com/eclipse/che-operator/blob/master/olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.8.0/eclipse-che-preview-kubernetes.v7.8.0.clusterserviceversion.yaml.diff`)

**Comment by tolusha** [comment]
we should keep them

**Comment by tolusha** [comment]
@flacatus 
Pls link all PRs related to this issue
