### ISSUE TITLE
Run `chectl` e2e tests on every PR check

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#15815]
### Is your task related to a problem? Please describe.
We have e2e tests [1] which are never executed. It is easy to break something without event noticed that.

### Describe the solution you'd like
Rework and run e2e tests on every PR check.

[1] https://github.com/che-incubator/chectl/tree/master/test/e2e

**Comment by dmytro-ndp** [comment]
@tolusha: we are actually running several chectl:next command on minikube every Happy path tests PR check:
- "[chectl server:start](https://github.com/eclipse/che/blob/master/tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile#L197)"
- "https://github.com/eclipse/che/blob/master/tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile#L267"

We are also fixing java selenium tests to use **chectl** instead of **ocp.sh** to deploy Che, so it will test `chectl server:start` on openshift as well.

**Comment by tolusha** [comment]
@dmytro-ndp 
Cool!
