### ISSUE TITLE
Java with MongoDB not starting

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15850]
### Describe the bug
The Java with Spring Boot and MongoDB is not started on a Hosted Che. There is error during pull of images, but pull continues even the error happens. Then the workspace fails on error message:

```
Error: Failed to run the workspace: "Waiting for Kubernetes environment 'default' of the workspace'workspacecgbxpl05gkz19aql' reached timeout"
```

Fails for both ephemeral and non-ephemeral mode.

### Che version

**7.7.1b**

### Steps to reproduce

1. Log in to che.openshift.io
2. Go to Worksapce -> Add Workspace
3. Choose Java with Spring Boot and MongoDB stack
4. Keep default settings and run the workspace

### Expected behavior

The workspace should be started.

### Runtime

https://che.openshift.io

### Screenshots
![Screenshot from 2020-01-28 13-39-42](https://user-images.githubusercontent.com/29278800/73266546-5bac1600-41d7-11ea-9c17-bac266e085bd.png)

**Comment by l0rd** [comment]
That's annoying. As already mentioned somewhereelse there are 2 issues here:

1 . We should not fail for timeout if the image is getting pulled and we don't have any evidence that pulling is going to fail. Image pulling may take a long time on some slow networks and we should support those scenarios.
2. We should pre-pull stacks images on all cluster nodes. @amisevsk is `docker.io/centos/mongodb-34-centos7` included in the image puller on che.openshift.io?

**Comment by amisevsk** [comment]
@l0rd The image puller is limited in terms of the number of images it can cache at the moment, due to a quotas on its namespace (each container takes `5Mi` memory, multiplied by the number of nodes in the cluster). There's an [open issue](https://github.com/redhat-developer/rh-che/issues/1550) to resolve this, but for now we just cache "the most common" images.

@Katka92 The reason the container cannot be started is because the docker image we're using [mounts `/var/lib/mongodb/data`](https://github.com/sclorg/mongodb-container/blob/master/3.4/Dockerfile#L56), which is forbidden in OpenShift without a corresponding volumeMount in the yaml. The quickest fix is to add a volume in the devfile.

**Comment by l0rd** [comment]
Thanks for the analysis @amisevsk. I have opened https://github.com/eclipse/che/issues/15863 as well to better handle image downloading that takes too long. But from your answer it looks like there is another enhancement we could do here: when a workspace pod status running but one of its container has state `Terminated` with reason `Error` we should fail and be explicit about it providing as much details as we can.

**Comment by sleshchenko** [comment]
> But from your answer it looks like there is another enhancement we could do here: when a workspace pod status is Running but one of its containers has state Terminated with reason Error we should fail and be explicit about it, providing as much details as we can.

@l0rd Exactly! And we already implemented such enhancement but maybe without to detailed information https://github.com/eclipse/che/pull/15449 ( non-zero exit code: Error: Failed to run the workspace: "The following containers have terminated: allocator: reason = 'Error', exit code = 5, message = 'null').
It's needed to test the described scenario on the latest Che and create another issue if needed. I believe we could propagate containers logs in such case
