### ISSUE TITLE
Cant run "Che run" on hyper-V (not using docker for windows, due windows 10 build)

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#1593]
Sorry for asking this

Eclipse Che : version 4.3.4

I'm running docker on hyper-v, and i can start docker but i cant start "che run" due to that "che.sh" only calling "vbox" extension

`C:\eclipse-che-4.3.4\bin>docker-machine create --driver hyperv --hyperv-virtual-switch "Che" Che
Running pre-create checks...
Creating machine...
(Che) Copying C:\Users\thomas.docker\machine\cache\boot2docker.iso to C:\Users\thomas.docker\machine\machines\Che\boot2docker.iso...
(Che) Creating SSH key...
(Che) Creating VM...
(Che) Using switch "Che"
(Che) Creating VHD
(Che) Starting VM...
(Che) Waiting for host to start...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env Che

C:\eclipse-che-4.3.4\bin>docker-machine env che
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.137.162:2376
SET DOCKER_CERT_PATH=C:\Users\thomas.docker\machine\machines\che
SET DOCKER_MACHINE_NAME=che
REM Run this command to configure your shell:
REM     FOR /f "tokens=*" %i IN ('docker-machine env che') DO %i`

![docker](https://cloud.githubusercontent.com/assets/1939446/16412933/67645cc4-3d61-11e6-9469-82c87cc758f3.JPG)

![hyper](https://cloud.githubusercontent.com/assets/1939446/16412962/96b07882-3d61-11e6-9b40-6a8c285e9309.JPG)

p/s : when i run "Che run" , it will deleted my VM "Che" inside hyper-v manager

**Comment by TylerJewell** [comment]
We have been busy with a conference this week.  We will get a proper response soon.

**Comment by TylerJewell** [comment]
Hi @thyeun - sorry it took some time to get back to you.  We haven't tested running Che with Hyper-V, but let me try and give you some pointers on what the script is doing to see if we can get it to recognize the alternative virtual machine that you have.

First, in the che startup scripts, the logic for how we go about creating a new VM is here:
https://github.com/eclipse/che/blob/master/assembly/assembly-main/src/assembly/bin/che.sh#L455-L482

You can see that there is different logic for vmware vs. vbox.  We have added a `--machine-driver` option which can either be `fusion` or `vbox`.  In that script, it is hard coded on windows to assume that vbox is being used.

If you replace the VM_CHECK_CMD, DOCKER_MACHINE_DRIVER, and DOCKER_MACHINE_DRIVER_OPTIONS variables with the appropriate command line properties for  HyperV, then the startup scripts will honor that.

However, a more elegant solution is that since you already have boot2docker running with docker-machine, you can just start that VM and go into the VM terminal. Once inside that terminal, you can run Che with our `docker run` syntax.  https://eclipse-che.readme.io/docs/usage-docker.

Separately, if you are on Windows 10, then you could install Docker for Windows - it is very fast and then you can just run Che from our Docker container.

**Comment by thyeun** [comment]
ok, thanks from your advised, will try it out

**Comment by thyeun** [comment]
Stop the Che server without stopping the container
docker exec che /home/user/che/bin/che.sh stop
![hyper-v](https://cloud.githubusercontent.com/assets/1939446/16491329/1cd16afc-3f10-11e6-9607-1b3c7b74f925.JPG)

After finish download the image (as from the picture), i try the below command line, but i still cant get Che work on http://localhost:8080 !!!

Stop the container running Che
docker stop che

Restart the container running Che and restart the Che server
docker restart che

Upgrade to a newer version
docker pull codenvy/che
docker restart che

so, which part am i make it wrong? 

p/s : i'm not taking the docker for windows, because that not the way to understand the technology behind of docker-che-condevy-hyper-v. sorry for trouble you.

**Comment by TylerJewell** [comment]
If you are running Che _inside_ of your VM, then the access URL is going to
be different.  It'll be http://<vm-ip>:8080.  You'll need to make sure that
you are forwarding ports.

You _may_ need to add the --remote:vm-ip to the end of the docker run
syntax as you are now running Che as a true server accessed by outside
clients instead of in localhost mode.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by ghost** [comment]
@thyeun yes, `-r:$IP` is mandatory here since I doubt that VM traffic is forwarded onto localhost.

**Comment by thyeun** [comment]
i still cant make the forwarding port work, but hyper-V with Che look very promising. i think you can close the topic, since the left over are the forwarding port. thanks for the advised and helping hands :)

**Comment by thyeun** [comment]
@TylerJewell , finally, by using your newer CLI, manage to use boot2docker run on hyper-v (with windows 10 build 10240)

![ss13](https://cloud.githubusercontent.com/assets/1939446/18333567/cccaac7a-75a2-11e6-80fb-5af8319c0f36.JPG)

![ss14](https://cloud.githubusercontent.com/assets/1939446/18333577/d98d4c6a-75a2-11e6-92dd-3d4d2cb150e0.JPG)

so, you really make it work, "any OS with any platform" using CLI. :)

**Comment by TylerJewell** [comment]
Yeah!!! Great work!
