### ISSUE TITLE
How can i deploy docker image (Python) in Eclipse Che Workspace

### ISSUE THREAD

**Issue by ChiragDosi** [eclipse-che/che#16111]
Hello,
I have an Docker image and i want to run it on workspace so can i achieve that ??
I have created the workspace and cloned the repo from terminal to the workspace and now i can see the repo including all the files (Docker file also) but how i can make this docker image run ??

Please let me know if anyone can help please.

Thanks

**Comment by ibuziuk** [comment]
@ChiragDosi `docker build` functionality is currently not supported, but we are planning to provide a similar functionality via buildah / podman. @ericwill is it smth. that in the backlog of the plugins team? maybe you can shed some light on this question

**Comment by ericwill** [comment]
I believe this is something you would need the Kubernetes plugin for, it supports building/running docker containers. Just FYI, we are currently working on an issue that affects building dockerfiles (#15035).

**Comment by ChiragDosi** [comment]
> I believe this is something you would need the Kubernetes plugin for, it supports building/running docker containers. Just FYI, we are currently working on an issue that affects building dockerfiles (#15035).

Ok thanks @ibuziuk and @ericwill but how i can use K8s plugin to deploy the docker image as i am using only one workspace for this and k8s cluster is not configured so kindly please let me know how i can achieve this ?? Thanks

**Comment by ericwill** [comment]
If you have a remote cluster set-up in the cloud (Azure, Amazon, etc.) you can use that. Otherwise, the workflow is to have a local Kubernetes cluster set up, which can then be injected into a running Che workspace. The app that's built via the Kubernetes plugin will be deployed to that local cluster.

You can find some docs about it here: https://github.com/azatsarynnyy/blog-files/blob/master/k8s-plugin/try.md#setting-up-the-access-to-the-local-cluster-from-che-workspace
