### ISSUE TITLE
Test for error highlighting failing

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#16166]
### Describe the bug
Test for error highlighting is failing from time to time. The failure was seen in e.g. Java Maven test. 

Error in test log:
`TimeoutError: Waiting for element to be located By(xpath, //div[contains(@style, 'top:190px')]//div[contains(@class, 'squiggly-error')])` 

The page source code of a fallen element:
![Screenshot from 2020-02-27 17-54-00](https://user-images.githubusercontent.com/29278800/75468140-09ecdc00-598d-11ea-93b4-b77da049f0fe.png)

You can see that in a log the parent element for an error highlighting should have `top:190px`, which is according to the screenshot the line above the wanted one.

**Comment by rhopp** [comment]
Update: 
This happens, because java language server decorates the file in editor with "Run|Debug" as shown on this screenshot:
![image](https://user-images.githubusercontent.com/1215011/75690231-c652e480-5ca2-11ea-863f-6ac0a8930bf4.png)

The problem is that this often happens in between getting the locator for the error marker and it's actual lookup (because this locator is sadly based on position).
This is apparent on this screencast in between 4:53 to 4:58 - https://youtu.be/UNn1WYf-oqE

Pull request is on it's way.

**Comment by ibuziuk** [comment]
@rhopp this one is fixed in 7.10.0 only, right? any plans to include this to 7.9.2 ?

**Comment by rhopp** [comment]
@ibuziuk No objection, your Honor (:smile:). It's just a simple test change, with practically zero chance of breaking something. 

@Katka92 Feel free to include this commit in 7.9.2.

**Comment by ibuziuk** [comment]
well, this affects Hosted Che tests at very least, so I suspected that CRW tests would be also affected with a false-positive test results
