### ISSUE TITLE
Inconsistent library versions notice.

### ISSUE THREAD

**Issue by kaifeng-h** [eclipse-che/che#16192]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 1 inconsistent library and 8 false consistent libraries.

Take junit:junit for example, this library is declared as version 3.8.1 in tests/legacy-e2e/che-selenium-test/src/test/resources/projects/check-maven-plugin-test/my-lib, 4.12 in tests/legacy-e2e/che-selenium-test/src/test/resources/projects/check-maven-plugin-test/my-webapp and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take junit:junit for example, if we harmonize all the library versions into 4.12. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table shows the overall harmonization cost on APIs. It seems your project have no API invokes on this library, which could be safely upgrade to 4.12

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|tests/legacy-e2e/che-selenium-test/src/test/resources/projects/check-maven-plugin-test/my-lib|0(0)|0(0)|0(0)|
|2|tests/legacy-e2e/che-selenium-test/src/test/resources/projects/check-maven-plugin-test/my-webapp|0(0)|0(0)|0(0)|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. 

As for false consistency, take junit junit jar for example. The library is declared in version 4.12 in all modules. However they are declared differently.  As components are developed in parallel, if one single library version is updated, which could become inconsistent as mentioned above, may cause above-mentioned inconsistency issues

If you are interested, you can have a more complete and detailed report in the attached PDF file.
[eclipse che.pdf](https://github.com/eclipse/che/files/4270525/eclipse.che.pdf)

**Comment by ibuziuk** [comment]
@calvinhkf thank you very much for reporting! Could you please tell a little bit more about the tool, that was used?

**Comment by ibuziuk** [comment]
@rhopp putting `area/qa` since the inconsistency is coming mostly from the `legacy-e2e` (is it planned to be deprecated?) according to the report.

**Comment by calvinhkf** [comment]
@ibuziuk The idea of the tool is much resembles _enforcer_ -the maven tool, but does much more than it, since _enforcer_ detects inconsistencies only inter-dependent modules and fails the build. Our tool takes a step further to get a whole picture of library version usages in projects, which could keep dependencies tidy and avoid inconsistency issues beforehand. Secondly, the next part of the tool, is to extract the usages of the library in the whole project, and therefore provides detailed information on API differences for developers to examine whether the pieces of code should be refactored, tested or not when trying to unifying versions.

Tool is planned to be developed into a maven build plugin or a CI plugin. And your comments on the tool matters to us. We will consider your opinions and improve the tool, thanks!
