### ISSUE TITLE
chectl: add a command to export CA for already deployed Che

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16278]
### Is your task related to a problem? Please describe.
For some reason, users may lose CA created by chectl during deploying.
It would be cool if chectl provide some command to extract CA for already deployed Che.
Then it would be a good option to use we could recommend users on Dashboard side, when browser is not configured properly.

**Comment by mmorhun** [comment]
The most general way to retrieve certificate from the server is to directly query the endpoint (in trusted network). But unfortunately we cannot use such approach, because server doesn't send root certificate in the response chain, see [this thread](https://mta.openssl.org/pipermail/openssl-users/2014-December/000113.html) in openssl-user mailing list.

**Comment by mmorhun** [comment]
Done. Now it is possible to retrieve Che self-signed certificate by using command: 
```sh
chectl cacert:export --platform=<platform>
```
