### ISSUE TITLE
insufficient memory

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#1631]
Version :  Eclipse Che 4.4
OS : Windows 10 pro build 10240

![memory-issue](https://cloud.githubusercontent.com/assets/1939446/16537817/24b56976-4041-11e6-849f-3d27246f8f62.JPG)

previously using version Eclipse Che 4.3.4, never encounter this issue.

**Comment by TylerJewell** [comment]
Interesting.  How big was the workspace ram that you allocated and does the issue still happen at larger amounts?

**Comment by ghost** [comment]
@thyeun please provide as many details as possible.

**Comment by thyeun** [comment]
sorry for late reply, try run on four projects at the same time, and workspace 1GB ram, for version 4.3.4, it never show insufficient memory. but once i ship/move my previous project (version 4.3.4) to newer version 4.4, it happen.

**Comment by TylerJewell** [comment]
Did you try the workspace with more ram?
We may have to increase some of the ram minimums.  The issue is that intellisense is run by language servers that we do not control and they can be memory aggressive at times.
-Tyler

On Sat, Jul 2, 2016 at 4:23 AM -0700, "Thomas Yeun" notifications@github.com wrote:

sorry for late reply, try run on four projects at the same time, and workspace 1GB ram, for version 4.3.4, it never show insufficient memory. but once i ship/move my previous project (version 4.3.4) to newer version 4.4, it happen.

**Comment by thyeun** [comment]
yes, i have increase the ram sizes, for the moment four workspaces, with 2GB ram, this issue no more happen, but i also notice that if i turn "on" four workspaces at the same time (but i only open one IDE project) this issue will happen, so what i'm concern is, if more workspace add-on later will it affected? and will it affected remotely/online sharing among the team? 

an example a team might using the four workspace differently (with the same moment), if this issue happen, than it might causing problem during remotely/online sharing.

**Comment by TylerJewell** [comment]
Yes, it will cause some problems.  These problems will not happen in Codenvy, which has a centralized resource management system for preventing the system from over utilizing memory across many workspaces running in a grid.

One of the things that we are investigating is allowing you (in Che) to configure various Docker Run parameters in the user dashboard before a workspace is started.  There are RAM limit and swap management flags that are part of Docker that can be set such that when a `docker run` command is launched by us we will honor those properties, and then you can put the containers into a state where they will not be using unlimited swap memory.

The default configuration of che has all workspaces sharing the same docker engine, and doing nothing to respect the other workspaces - so if the overall system breaches the RAM limit, you may see these errors.  So our approach will be to expose underlying Docker configuration features to help you manage this.

These issues will not affect remote sharing - just in the overall number of workspaces that you have running and their overall size.  So if you can fix the size of all workspaces and keep it a certain level then you should be ok.

**Comment by thyeun** [comment]
will it be in the future version, a memory ram status bar will be add-on at dashboard? so that all the related user/team/personal can notice how much ram are remain before reach out the ram limit.

**Comment by TylerJewell** [comment]
Yeah, definitely - working on resource management and controlling team-based resource consumption is a big part of what we are thinking about right now.  Of course, we accept pull requests, too, for those that want to get more involved.  

By the end of July, we will change all of our wiki stuff so that everyone can see our full year roadmap.  We have about 40 things related to team-based management that we are working on, and resource management is a big deal.  One of the first things we have to get done is how to run Che on a single nginx proxy so that all ports go through a single port, hiding all of the backend ports.

**Comment by thyeun** [comment]
interesting. if proxy are working too, than it will be good for a company user like me, due that a company always using proxy control.

And thanks for you explanation, and thank you so much.

**Comment by ghost** [comment]
We're going to handle OOM smarter. Looks like @thyeun has found a solution. I am closing the issue.

**Comment by ChiragDosi** [comment]
I am facing the same issue, i am running only one workspace but 90% of the time i am getting insufficient memory error and workspace is not starting. Kindly please suggest some solution thanks

**Comment by amisevsk** [comment]
@ChiragDosi please create a new issue, this issue refers to a quite old version of Che.

**Comment by ChiragDosi** [comment]
Ok thanks @amisevsk , i had created an issue "Workspace is not starting when enabling VSCode Editor #15576" if you can look into it and give some suggestions it would be very helpful for me
