### ISSUE TITLE
E2E operator hub installation tests failed being run against OCP 4.4

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16367]
### Describe the bug
`test-operatorhub-installation` tests [had failed downstream](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/crw-typescript-tests/2183/console) being run to install CRW on OCP 4.4:
```
11:29:41       ✓ Create Che Cluster  (832ms)
11:29:41     Check the Che is ready
11:29:41           ▼ OcpWebConsolePage.waitKeycloakAdminConsoleUrl
11:30:37       ✓ Wait Keycloak Admin Console URL (51230ms)
11:30:37           ▼ OcpWebConsolePage.waitInstalledAppUrl
11:32:58       ✓ Wait installed application URL (139651ms)
11:32:58     Logout from web console OpenShift
11:32:58           ▼ OcpWebConsolePage.logoutFromWebConsole
11:32:58           ▼ OcpWebConsolePage.waitDisappearanceNavpanelOpenShift
11:32:58       1) Logout from temp admin user
11:32:58 
11:32:58 
11:32:58   16 passing (4m)
11:32:58   1 failing
11:32:58 
11:32:58   1) E2E
11:32:58        Logout from web console OpenShift
11:32:58          Logout from temp admin user:
11:32:58      TimeoutError: Waiting attempts exceeded, element 'By(css selector, .pf-c-nav)' is still visible
```

### Screenshots
![screenshot-Logout_from_temp_admin_user](https://user-images.githubusercontent.com/1197777/76750357-cebd1c00-6786-11ea-8eb5-701ca93689dc.png)

**Comment by artaleks9** [comment]
* Really it happened because the method _waitDisappearanceNavpanelOpenShift_  is used inside method _waitDisappearance_ without timeout. Should be used the method _waitDisappearanceWithTimeout_ with enough timeout.

* But from other side the test-suite _Logout from web console OpenShift_ is redundant and should be deleted from the _InstallCheByOperatorHub.spec.ts_.

So, 
1) the __waitDisappearance__ will replaced on __waitDisappearanceWithTimeout__
2) the suite _Logout from web console OpenShift_ will be deleted from E2E test
