### ISSUE TITLE
Failing Loading All Resources

### ISSUE THREAD

**Issue by twolastnames** [eclipse-che/che#16483]
After a fresh install with chectl, it looks like I have an empty program running.

When I first launch the application, on the getting started tab, a "Failed to load devfiles meta list" error is shown.

When attempting to open a workspace, I get the errors "Failed to load plugins" and "Failed to load editors".

It's on minikube on Ubuntu 18.04.1.

**Comment by twolastnames** [comment]
When I try to start a workspace...

```
Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.1.1"

Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.1.1"

Created container che-plugin-metadata-broker-v3-1-1

Started container che-plugin-metadata-broker-v3-1-1

Starting plugin metadata broker

Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://plugin-registry-che.192.168.99.100.nip.io/v3/plugins/eclipse/che-machine-exec-plugin/7.10.0/meta.yaml': failed to get data from https://plugin-registry-che.192.168.99.100.nip.io/v3/plugins/eclipse/che-machine-exec-plugin/7.10.0/meta.yaml: Get https://plugin-registry-che.192.168.99.100.nip.io/v3/plugins/eclipse/che-machine-exec-plugin/7.10.0/meta.yaml: dial tcp: lookup plugin-registry-che.192.168.99.100.nip.io on 10.96.0.10:53: no such host

Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin brokering process for workspace workspacebhatun5iy6053soc failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://plugin-registry-che.192.168.99.100.nip.io/v3/plugins/eclipse/che-machine-exec-plugin/7.10.0/meta.yaml': failed to get data from https://plugin-registry-che.192.168.99.100.nip.io/v3/plugins/eclipse/che-machine-exec-plugin/7.10.0/meta.yaml: Get https://plugin-registry-che.192.168.99.100.nip.io/v3/plugins/eclipse/che-machine-exec-plugin/7.10.0/meta.yaml: dial tcp: lookup plugin-registry-che.192.168.99.100.nip.io on 10.96.0.10:53: no such host"
```

**Comment by twolastnames** [comment]
I'd guess that Ingress not running would do this?

When I enabled it with minikube, it didn't give an error.  But, I couldn't find it in the list of pods running.

I installed Ingress through helm, but it doesn't help.

**Comment by ibuziuk** [comment]
@twolastnames could you update the issue description based on a template? What is the version of che are you using? What was the installation method / chectl command etc.

**Comment by twolastnames** [comment]
Sorry I haven't answered.  The distribution install stopped booting.  The only thing I had installed on there was this, so I wiped it clean.

**Comment by adriendelsalle** [comment]
@ibuziuk @twolastnames 

I think I encounter a similar issue:
> When I first launch the application, on the getting started tab, a "Failed to load devfiles meta list" error is shown.

Fixed by adding the certificate in my browser as asked during Che start. Only working with Firefox, Chrome throws me the following error (translated from french):
> **Certificate error**
The private key of this certificate is missing or incorrect

![image](https://user-images.githubusercontent.com/27348745/78110470-4df35680-73fb-11ea-89d3-a90e89650cd0.png)

Then launching a new *Get Started* workspace fails.
![image](https://user-images.githubusercontent.com/27348745/78110674-b3dfde00-73fb-11ea-9c7d-d30d131e551d.png)
![image](https://user-images.githubusercontent.com/27348745/78110797-e7226d00-73fb-11ea-9f91-04cfa0e10499.png)

Is there anything also related with cert?
I'm a k8s beginner so don't hesitate to ask me more info.

---
My configuration:
O/S: 
- Host : Windows 10 Enterprise 2016 LTSB, Version 1607
- Guest: Ubuntu 19.10 in VirtualBox, with 2CPU, 4GB RAM, 20GB SSD disk

Install:
- Chectl: 7.10.0 linux-x64 node-v10.19.0
- minikube: v1.9.0
- helm: v3.1.2
- goVersion 1.13.8
- kubectl (client/server): v1.18.0

**Important**: because I'm not able to run a VM *inside* a VM, I launch minikube with the following command:

``` shell
sudo minikube start --vm-driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost
```

Do you also need any other information?
Thanks!

**Comment by tolusha** [comment]
> Chrome throws me the following error (translated from french):
> Certificate error
> The private key of this certificate is missing or incorrect

It is probably this issue. We are working on it right now
https://github.com/eclipse/che/issues/16366

**Comment by adriendelsalle** [comment]
> > Chrome throws me the following error (translated from french):
> > Certificate error
> > The private key of this certificate is missing or incorrect
> 
> It is probably this issue. We are working on it right now
> #16366

Thanks @tolusha !
Any hint for the second part of this issue (che-plugin-broker failing to start)?

**Comment by adriendelsalle** [comment]
Starting the server with the following command worked:
``` shell
chectl server:start --platform=minikube --self-signed-cert
```
@twolastnames  could you please try ?
Thanks!

**Comment by adriendelsalle** [comment]
> It is probably this issue. We are working on it right now
> #16366

It works by adding the certificate in the *Authorities* tab, not in the *Your certificates* one.
Sorry for that, thanks!
