### ISSUE TITLE
Git clone using private key with password is not working

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#16517]
### Describe the bug
When trying to clone git repository using `git@gitlab.com/something/something` using ssh key, which is protected by password, Che never asks me for a password and the clone fails with this error:
```
git clone git@gitlab.something/something/web-app.git /projects/web-app
Cloning into '/projects/web-app'...
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

### Che version
che.openshift.io
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
* Generate ssh keypair *with a password* (`ssh-keygen`)
* Upload public part of that key to gitlab/github
* Start any workspace
* upload private part of the key to the workspace
* try to clone some repo using this format -> `git@gitlab.something/something/web-app.git` 

### Expected behavior
Repo is cloned

**Comment by sleshchenko** [comment]
Reproduced with `Git: Clone` action as well.
![Screenshot_20200403_093902](https://user-images.githubusercontent.com/5887312/78331671-33ea7d00-758f-11ea-9936-78a5e728292a.png)
As a workaround, it's possible to clone project manually from terminal:
![Screenshot_20200403_093953](https://user-images.githubusercontent.com/5887312/78331683-39e05e00-758f-11ea-95ad-140de274863b.png)

putting p1 since it's typical to set passphrase for ssh keys
