### ISSUE TITLE
Permission denied at workspace creation after VM reboot

### ISSUE THREAD

**Issue by adriendelsalle** [eclipse-che/che#16543]
Thank you all for this amazing project!

### Description
A fresh Minikube + Che server works as expected but after VM reboot, I get a *permission denied* on any workspace available in the `Get Started` menu.

The following message is displayed in the web console during workspace creation:

*mkdir /plugins/sidecars: permission denied*

The pods are failing again and again:

``` shell
adrien@adrien-VirtualBox:~$ sudo kubectl get pods -n che-che
NAME                                                 READY   STATUS                  RESTARTS   AGE
workspace5bi66pacakr3449h.cpp-dev-7fffc75cc6-ddrl5   0/5     Init:CrashLoopBackOff   12         41m
workspaceadjgdj3ds0a841ar.cpp-dev-764445bd87-bxrhn   0/5     Init:CrashLoopBackOff   13         145m
```

This is perhaps related to #14330, I'm not able to understand all the concepts discussed.
I'm a k8s and Che beginner so please don't hesitate to ask for more details with the steps to get the appropriate information!
Thanks a lot!

---
#### Che version
latest : 7.10.0
#### O/S: Linux
Ubuntu 19.10 VirtualBox VM on top of host Windows 10 Enterprise 2016 LTSB, Version 1607

#### Runtime : minikube

Important: because I'm not able to run a VM inside a VM, I launch minikube with the following command:

``` shell
sudo minikube start --vm-driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost
```

`minikube version` 
``` shell
minikube version: v1.9.0
commit: 48fefd43444d2f8852f527c78f0141b377b1e42a
```

`kubectl version`
``` shell
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

#### Installation method: chectl
Started with command:
``` shell
sudo chectl server:start --platform=minikube --self-signed-cert
```
Ran with sudo because Minikube was started with sudo.

#### Additional context
helm: v3.1.2
goVersion 1.13.8

Do you need any other information?

**Comment by amisevsk** [comment]
Hi @adriendelsalle 

The message
> mkdir /plugins/sidecars: permission denied

suggests that in restarting minikube, the permissions for folders in PVCs are changed. The [docs](https://minikube.sigs.k8s.io/docs/reference/drivers/none/) page for the `none` driver states:

> minikube with the none driver has a confusing permissions model, as some commands need to be run as root (“start”), and others by a regular user (“dashboard”)

which may be relevant, but I cannot find additional information about this.

For context, Che runs workspaces without root, as a security precaution. During workspace start up, we mount a PVC to the workspace pod and execute `mkdir` commands to prepare folders as required by plugins, etc. This is the step that is failing and causing the crashloop for pods.

Does this occur for *all* workspaces (including new ones) after restarting the VM, or only for existing workspaces that you're attempting to restart?

For debugging information, it would be helpful to have the permissions and owners for the directories mounted by the workspace: 

```bash
$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: workspace-storage
  namespace: che-che
spec:
  containers:
  - name: workspace-storage
    image: centos
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
      - mountPath: /workspaces
        name: claim-che-workspace
  volumes:
  - name: claim-che-workspace
    persistentVolumeClaim:
      claimName: claim-che-workspace
$ kubectl apply -f pod.yaml
$ kubectl exec workspace-storage find /workspaces -type d -ls
```
though I suspect there won't be much we can do unless the problem is obvious -- we don't support vm-driver=none since the configuration is much less consistent.

As a workaround, you could try setting workspaces to use [ephemeral storage](https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/#attribute-persistvolumes-ephemeral-mode) (this can be done via a toggle in the dashboard), but note that all data in the workspace will be lost whenever the workspace is stopped.

**Comment by adriendelsalle** [comment]
Hi @amisevsk !
Thanks a lot for your response!!

I have tested on Ubuntu 19.10 with minikube running in virtual box `driver` and it supports reboot without any problem.
I also noticed the `--self-signed-cert` was not required to make it work. See #16483. Is there any relation? 

I will further test/debug the none driver config in few days and add some feedback on this issue.
I close it since you don't support this not usual config.

Thanks again!
