### ISSUE TITLE
sonarlint plugin doesn't work 

### ISSUE THREAD

**Issue by yshcoffee** [eclipse-che/che#16589]
sonarlint plugin doesn't work (eclipse che version: 7.7.0)

Soanrlint is not visible, but javalint is visible. 

Please, tell me how to use Sonarlint plugin. 

sonarlint plugin test order:
1. create workspace: Java Maven Stack
2. Eclipse Che UI Workspaces > configure workspace > Plugins > vscode-sonarlint Enable > Apply
3. File > Settings > Open Preferences > input
{
   "sonarlint.connectedMode.servers": [
      {
         "serverId": "my_sonarqube",
         "serverUrl": "http://172.22.11.2:9000",
         "token": "457be3c16b703110e68380bcc7f53b2727b2771c"
      }
   ],
   "sonarlint.ls.javaHome": "/usr/lib/jvm/java-1.8-openjdk",
   "sonarlint.connectedMode.project": {
      "serverId": "my_sonarqube",
      "projectKey": "petclinic"
   }
}

4. F1 > Update Sonarlint binding to SonarQube/SonarCloud 

5. Result: Solarlint seems unapplied
![image](https://user-images.githubusercontent.com/47413947/79094668-35882200-7d93-11ea-9e9f-1275e876a6e0.png)

Is there anything else I need to set up?

**Comment by ericwill** [comment]
Something isn't working, unless I am missing some step. It works fine in VS Code but fails on Che.

**Comment by tsmaeder** [comment]
Well, sonarlint simply does not support Java in the version we have in the plugin registry: these are the activation events:

```
"activationEvents": [
    "onLanguage:javascript",
    "onLanguage:javascriptreact",
    "onLanguage:typescript",
    "onLanguage:typescriptreact",
    "onLanguage:python",
    "onLanguage:php",
    "onLanguage:vue",
    "onLanguage:html",
    "onLanguage:jsp",
    "onLanguage:apex",
    "onLanguage:plsql",
    "onCommand:SonarLint.UpdateAllBindings",
    "onView:SonarLint.AllRules"
  ],
```

**Comment by tsmaeder** [comment]
I was able to make V 1.16.0 of the extension work for Java if I include the Java extension in the Che plugin.

**Comment by tsmaeder** [comment]
Seems if I just activate the Java Che plugin, Java support in does not work for sonarlint. Same with typescript support: 
> Unable to locate TypeScript extension. TypeScript support in SonarLint might not work.

**Comment by benoitf** [comment]
I think there are couple of issues

1. bug in extensionDependency/extensionDependencies handling (upstream theia)
  - we're not handling extensionDependency field (only extensionDependencies) (extensionDependency is deprecated)
but then it means that extensions might search for `typescript` while it should be `vscode.typescript` (always a prefix)

so sonalint could be updated to match the correct/new way of searching extensions with the identifier or we need to add prefix `vscode.` on missing requests

2. bug in remote calls of che-theia. vscode-java is not exporting objects in the same way than other extensions does (like yaml/kubernetes). Needs to be fixed in che-theia/remote stuff.
For now we're able to find `redhat.java` extension but not all of its exported members.

**Comment by benoitf** [comment]
For java support, meta.yaml of latest sonarlint (1.16.0) version should contain as well

```
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
```

as it tries to load m2 dependencies

**Comment by benoitf** [comment]
After https://github.com/eclipse/che-theia/pull/794 is merged, there is one remaining problem for `typescript`

it's because sonarlint VS Code plug-in, grab the extension path named `vscode.typescript-language-features`
```
const tsExt = VSCode.extensions.getExtension('vscode.typescript-language-features');
..
const bundledTypeScriptPath = Path.resolve(tsExt.extensionPath, '..', 'node_modules', 'typescript', 'lib');
```

but as it's in another container, filesystem access is not OK

so either, we need to:
- copy typescript lib into a `sonarlint` plug-in with exact same path (difficult as there is a random name generated by the plugin-broker)
- having sonarlint running in the typescript sidecar (but then it's require both java and typescript)
- update sonarlint to specify an absolute path for typescript and provide sidecar with this lib

**Comment by tsmaeder** [comment]
Sonarlint looking up the typescript libs is conceptually the same problem as https://github.com/eclipse/che/issues/16851: it's trying to pick up a target environment.

**Comment by tsmaeder** [comment]
When I fixed the field `extensionDependency` to the correct `extensionDependencies`, the plugin activation of the sonarlint plugin now fails saying 
> Activating extension 'SonarLint' failed: Dependent extension 'typescript' is not installed.

Seems the correct name is `vscode.typescript`

**Comment by benoitf** [comment]
in fact the real name is `vscode.typescript-language-features`
see https://github.com/SonarSource/sonarlint-vscode/pull/97

**Comment by tsmaeder** [comment]
Sonarlint would already pickup the setting `typescript.tsdk`. Maybe we can weasel up something around that.

**Comment by benoitf** [comment]
it looks like I don't see anymore one of my comment on this issue I paste few hour ago.

This is what I was instructing `typescript.tsd`  in the devfile, to specify that value so that Sonarlint can find it. 
To use local typescript install instead of typescript version bundled in the sidecar.

**Comment by benoitf** [comment]
this preference in devfile
```
  - id: che-incubator/typescript/latest
    type: chePlugin
    memoryLimit: 1512Mi
    preferences:
      typescript.tsdk: "/projects/react-web-app/node_modules/typescript/lib"
```

then add node runtime in the sidecar of sonarlint

and then it worked
![sonarlint-typescript](https://user-images.githubusercontent.com/436777/87161870-678f1e80-c2c5-11ea-9864-40bcf276cdd0.gif)

**Comment by tsmaeder** [comment]
We'd have to do the same for the typescript plugin, as well, though: preferences are shared among sidecars.

**Comment by benoitf** [comment]
@tsmaeder I'm doing that on the typescript plug-in

**Comment by benoitf** [comment]
what would be nice is to be able to specify it in the meta.yaml and not in the devfile.yaml (maybe it's what you were saying) ?

but for that it means we should have multi-workspace root enabled to always have the relative `./node_modules/typescript/lib` path 

BTW it's nice to have the typescript really used by the project but extension switch to default if `node_modules` is not there
