### ISSUE TITLE
Cloud shell reconnection feature

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#16607]
### Is your enhancement related to a problem? Please describe.
It would be nice to provide restore previous output feature for Eclipse Che Cloud Shell.

### Describe the solution you'd like
We can store execId in the browser storage and use it to reconnect to the che-machine-exec server side.

**Comment by sleshchenko** [comment]
Well, instead of storing execId in the browser storage, che-machine-exec could provide all running execs, and then user would be able to restore sessions whatever browser they use, or even anonymous tab. Cloud Shell UI could provide the same functionality as typical terminal provides with multiple tabs 
![Screenshot_20200415_134351](https://user-images.githubusercontent.com/5887312/79328696-2930d000-7f1f-11ea-99c0-cead2c785eb3.png)

But it for sure requires even more work, so it can be considered to be implemented after implemented the feature described in the issue description.

**Comment by AndrienkoAleksandr** [comment]
POC moved in another direction, looks like it's not actual any more.
