### ISSUE TITLE
Links to raw github moved

### ISSUE THREAD

**Issue by rfojta** [eclipse-che/che#16634]
https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud/deploy.yaml

**Comment by sleshchenko** [comment]
@rfojta Thanks for letting us know, could you clarify is `https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml` moved to `https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud/deploy.yaml` ?
Do you have in mind that we should update it in chectl, che-docs, another place?

**Comment by rfojta** [comment]
I'm sorry. I was referring to this article. https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1

The links I've posted are replacing these 
`$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml`
`$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/cloud-generic.yaml`

**Comment by benoitf** [comment]
I've updated my article, thanks @rfojta

**Comment by adriendelsalle** [comment]
Hi @benoitf @sleshchenko !

The Che documentation also has to be updated in several places:
- [GCP](https://www.eclipse.org/che/docs/che-7/installing-che-on-google-cloud-platform/#installing-ingress-on-kubernetes_preparing-google-cloud-platform-for-installing-che)
- [Azure](https://www.eclipse.org/che/docs/che-7/installing-eclipse-che-on-microsoft-azure/#installing-ingress-on-kubernetes_installing-che-on-microsoft-azure)
- [AWS](https://www.eclipse.org/che/docs/che-7/deploying-che-on-kubernetes-on-aws/#installing-ingress-nginx)

It seems that AWS needs a special treatment since there are `aws` and `cloud` providers.

@benoitf 
From your blog, the link https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml is broken.
Sounds from [this commit](https://github.com/kubernetes/ingress-nginx/commit/efbb3f9fc868f8e69d892017f672c7bfc00e7201) that this manifest is not necessary anymore.

Thanks!
