### ISSUE TITLE
[devworkspace] Reconcile loop does not work correctly after updating routing class

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16639]
### Describe the bug
Reconcile loop does not work correctly after updating routing class.

### Steps to reproduce
1. Use basic routing by default with disabled cookies.
2. Create a cloud-shell workspace.
3. Check that cloud-shell workspace is created and working.
4. Modify created workspace and set `routtigClass: openshfit-oauth` explicitly.
5. Check that workspace is still Running, the new routingClass is provisioned into workspaceRouting object but workspace is working without any authentication.

6. Update controller config with openshift-oauth routing by default with enabled cookies.
7. Check that workspace is still running but now not working.

The last message controller prints:
```
{"level":"info","ts":1587118816.23889,"logger":"controller_workspacerouting","msg":"Services not in sync","Request.Namespace":"che-workspace-controller","Request.Name":"routing-workspace309a978a3a194ff0"}
```

### Expected behavior
Workspace is successfully restarted after updating routingClass

**Comment by amisevsk** [comment]
The issue here is that we're applying the service update wrong -- I have the patch logic reversed, and so any updates to services are not actually propagated to the cluster. Updating routingClass causes the controller to get stuck on a loop of trying to update the service but pushing no changes.

However, using `client.Patch` also seems to not work correctly as the empty value for `clusterIP` is not overwritten with the existing `clusterIP` (perhaps because `clusterIP` is `string` instead of `*string`

Fixed by https://github.com/che-incubator/che-workspace-operator/pull/66, which just makes sure we don't modify clusterIP.
