### ISSUE TITLE
[chectl] operator should be a default way to deploy Eclipse Che instead of helm

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16648]
### Is your task related to a problem? Please describe.
For some infrastructures helm is used as a default installer.
In this case it is not possible to update Eclipse Che using `server:update` command.

### Describe the solution you'd like
Use `operator` as a default installer for all infrastructures.

**Comment by sleshchenko** [comment]
> In this case it is not possible to update Eclipse Che using server:update command.

There is the issue to implement server:update for helm chart as well https://github.com/eclipse/che/issues/14973, but is there any plan for it? It seems not very difficult.
Just to clarify - it's +1 to make operator as a default installer, but since we support helm chart for installing, it's needed to support server:update as well, and it does not seem to be difficult to implement.

**Comment by tolusha** [comment]
`server:update` for helm is in plans but not an important one

**Comment by tolusha** [comment]
https://github.com/che-incubator/chectl/pull/679
