### ISSUE TITLE
[new UD] MVP for Workspaces List

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#16646]
### Is your task related to a problem? Please describe.
Desired design

![image26](https://user-images.githubusercontent.com/5887312/99667165-ab184700-2a74-11eb-9014-5ecdd16ceb66.png)

CPU and RAM should be missed at this time since Che Server does not provide such information and Dashboard is not able to evaluate it.

**Comment by parvathyvr** [comment]
Hi @olexii4 I have updated the workspace Card and list views in the doc with the new changes-Please see the new updates [here](https://docs.google.com/document/d/1Ao0mfcqA41dv_h8SVgsVV7sPbO57opSuplL0331_xwM/edit?ts=5f185cf5#heading=h.eh3aszv7mrc6) and add your reviews! Thanks!

**Comment by parvathyvr** [comment]
@akurinnoy @olexii4 @sleshchenko here is the marvel link for workspace view https://marvelapp.com/prototype/6e5cjhj/screen/74882131 with the updated screens based on the feed backs we got from sprint 190 and 191 sprint reviews.
Main new changes:
1. Added a new column 'Last Accessed' and the whole workspace list is sorted by latest to oldest.Other columns also have sorting option-Name,RAM,CPU
2. Project(s) column is showing the project URLs instead of project name
3. Removed the 'Devfile Template' column
4. Added the label to show uncommitted changes with tooltip (there are some discussions ongoing that needs to be resolved in this [design doc](https://docs.google.com/document/d/1Ao0mfcqA41dv_h8SVgsVV7sPbO57opSuplL0331_xwM/edit?disco=AAAAKrapFrU)
5. Action menu from the kebab in the table has 'Open in verbose mode' added.This is the action which is  'Run in Debug mode' in the current UI.
Let me know if you have any questions/comments.Thanks!
