### ISSUE TITLE
Che Theia release script should get upstream Theia version from yarn.lock or npmjs.org

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16691]
### Is your enhancement related to a problem? Please describe.

Currently, Che Theia release script [reads](https://github.com/eclipse/che-theia/blob/6ab9cb89f044ba6322be4dcdda5bd5d3c6103bf4/make-release.sh#L69) upstream Theia version from [THEIA_VERSION](https://github.com/eclipse/che-theia/blob/master/THEIA_VERSION) file that has to be manually updated in master branch before doing a release.
We should avoid this manual update.

### Describe the solution you'd like

It can be automated by reading it from [yarn.lock](https://github.com/eclipse/che-theia/blob/6ab9cb89f044ba6322be4dcdda5bd5d3c6103bf4/yarn.lock#L1523) file.

### Describe alternatives you've considered

It can be automated by reading it from npmjs.org.

**Comment by benoitf** [comment]
Hi

I was thinking that it could be nice is that if ./build.sh could
- by default (or with a flag) grab the current “upstream tag” by looking at npmjs for the next1.1.0-next.669ad8b7 version
- have a way to specify this version so that we can easily build theia using a previous sha1
- release mode where we use for example THEIA_VERSION or in that case yarn.lock @theia/core.

so let say someone is blocked with current upstream, he can used a previous tag easily like
`./build.sh --upstream-commit-tag 66dd2bc6`
and then that we don’t have to provide git-refs stuff, THEIA_VERSION , --branch or git-refs on build.sh script (all being handled)

then make-release would just call build.sh or something different

**Comment by benoitf** [comment]
to grab from npmjs:

```bash
$ curl --silent http://registry.npmjs.org/-/package/@theia/core/dist-tags | sed 's/.*"next":"\(.*\)".*/\1/'
1.1.0-next.669ad8b7
```

**Comment by azatsarynnyy** [comment]
good idea to parametrize upstream version
I'll work on it. Thx!
