### ISSUE TITLE
[Study] Possible implementations for single-host strategy on OpenShift

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16702]
### Is your task related to a problem? Please describe.
There are multiple requests for single-host strategy which is not available at this moment on OpenShift.
The main reason for that is the wildcard-free SSL certificate mode.
There is a discussion about the pros/cons https://www.eclipse.org/lists/che-dev/msg03710.html

### Describe the solution you'd like
Here we would like to investigate how exactly we can do http(s) traffic routing.
Possible alternatives
- Reuse some OpenShift internals.
- nginx
 - haproxy
 - traefik

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/12914

**Comment by metlos** [comment]
After some investigation, I'd like to share some preliminary results.

## Motivation

The main reason for single-host not working on OpenShift is that OS doesn't support path rewriting 
in routes (while ingresses in k8s don't support that either officially, many ingress controller 
impls handle that using annotations on ingresses). We need path rewriting so that we don't force 
servers and user applications within the workspaces to be able to accept requests on configurable 
(and ever changing) subpaths (e.g. 
`https://<che-host>/ws-15/<component>/<server>/<server-specific-part>` should ideally be seen by the 
server as `https://<internal-host>/<server-specific-part>`).

Because path rewriting cannot be achieved with OpenShift routes, we need to look for a different 
solution. This is going to be some kind of http gateway (aka reverse proxy) that will ideally 
support dynamic reconfiguration or at least the support for being reloaded after configuration 
changes.


## The Controller

The dynamic reconfiguration or gateway reloading will most probably have to be done by some kind of 
controller. This can vary from very simple to very complex based on the solution we choose.

Regardless of whether the controller is a standalone application, embedded in the Che server or in 
the workspace controller, it needs to do these things:

* Establish the gateway configuration changes needed to expose the components in the workspace.
* Express the configuration changes in the configuration format understood by the gateway.
* Make the gateway load the configuration changes.

## Configuration representation

There is a couple of ways how to deliver the configuration changes to the http gateway.

### Custom CRD
We could use some kind of CRD similar to Ingress/Route that would express the desired configuration 
for the workspace component exposure. The workspace controller/che server would emit CRs of this 
type and the controller would somehow apply them to the gateway.

#### Pros
* Identical to how the openshift router or any ingress controller operate with the exception that we 
could not use Ingress/Route but use some custom resource of our own making.
* We can abstract away the concrete configuration file format of the chosen gateway.

#### Cons
* The CR is another level of indirection between Che and the gateway.
* The CR doesn't solve the problem of syncing the config to the gateway.

### ConfigMap
Config maps are used to store configuration or even a whole set of configuration files so they are 
an excellent candidate. The role of controller would be much simpler because we could just mount the 
config map into the gateway pod.

#### Pros
* is directly mountable to the filesystem of the gateway pod.

#### Cons
* The configuration needs to be in the format understood by the gateway thus coupling Che strongly to the single gateway solution.

## Applying the configuration

Regardless of whether we use a CRD or just config map, we need to somehow make the configuration visible to the gateway. Ideally we could just "send" the configuration to the gateway but that is not a common way of handling configuration. The more common option is to modify the configuration files on the filesystem of the pod running the gateway.

Again, this can be done in a couple of ways.

### OTA updates
We could implement the controller as a sidecar that would live in the gateway's pod and would receive the configuration updates, apply them locally and persuade the gateway to reload it.

#### Pros
* Sidecar would be the coupling of our configuration reqs to the concrete format required by the gateway. The sidecar is a natural fit for this coupling.

#### Cons
* We need to think about security. Sending the config over the wire to the sidecar is possibly vulnerable, forcing us to deal with the whole enchilada of securing the access - certificates, possibly tokens, making the solution much more heavyweight.

### ConfigMap + "touch" of the gateway pod
Changes to config map are eventually reflected in the local filesystems of the pods that mount the config map. This can take a long time (>1min) and doesn't work for mounts using the `subPath` attribute. Nevertheless, if we can avoid the `subPath` we could achieve immediate updates of the config map mount by "touching" the gateway pod. This would mean updating some kind of annotation on the pod for example (e.g. "config-update-toggle" annotation being updated to a random value each time we need to apply the configuration updates from the config map).

#### Pros
* Conceptually simple, controller can live outside of the gateway pod. Its role would be to update the config map and touch the gateway pod.

#### Cons
* None?

## Experiments done so far

https://github.com/metlos/che-singlehost-poc is an implementation of the above ideas using Traefik as the gateway. Between Traefik, nginx and HAProxy, Traefik is the only solution capable of dynamic configuration loading from a directory. The POC takes advantage of that and mounts a configmap representing the configuration of traefik for all workspaces into a directory watched by Traefik for config changes.

The controller in the POC sits between the chair and the keyboard, following the algorithm outlined in the readme ;)

**Comment by metlos** [comment]
We're concluding this study and will continue on the subtasks of the parent issue #12914.
