### ISSUE TITLE
[object Object] when loading che

### ISSUE THREAD

**Issue by ia3andy** [eclipse-che/che#16719]
### Describe the bug
I wasn't able to reproduce but the first time I opened che.openshift.io, I've got this screen:
![image](https://user-images.githubusercontent.com/2223984/80001876-315cb280-84bf-11ea-9799-a861c34ff078.png)

I also got an infinite redirect loop at some point.

After a few refresh all went back to normal..

### Che version
Che-Theia@62718c1 using Theia@9481af8e

**Comment by ibuziuk** [comment]
@ia3andy if you hit it again, could you please post the console logs?

**Comment by ia3andy** [comment]
Sure!

**Comment by ia3andy** [comment]
ok same error today @ibuziuk. Here is the console logs:

```
auth.openshift.io/api/token:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
VM18:627 Refused to get unsafe header "WWW-Authenticate"
req.onreadystatechange @ VM18:627
app-23c0ba19e9.js:296487 Can't GET "/api". Error:  Objectstatus: 500response: "{"errors":[{"code":"unknown_error","detail":"unable to get user profile Get https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/userinfo: net/http: request canceled (Client.Timeout exceeded while awaiting headers)","status":"500","title":"Unknown error"}]}↵"__proto__: Object
(anonymous) @ app-23c0ba19e9.js:296487
che.openshift.io/:1 Uncaught (in promise) Objecterror: "invalid_request"error_description: "{"status":500,"response":"{\"errors\":[{\"code\":\"unknown_error\",\"detail\":\"unable to get user profile Get https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/userinfo: net/http: request canceled (Client.Timeout exceeded while awaiting headers)\",\"status\":\"500\",\"title\":\"Unknown error\"}]}\n"}"__proto__: Object
che.openshift.io/:1 Uncaught (in promise) Objecterror: "invalid_request"error_description: "{"status":500,"response":"{\"errors\":[{\"code\":\"unknown_error\",\"detail\":\"unable to get user profile Get https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/userinfo: net/http: request canceled (Client.Timeout exceeded while awaiting headers)\",\"status\":\"500\",\"title\":\"Unknown error\"}]}\n"}"__proto__: Object
```

**Comment by ibuziuk** [comment]
@alexeykazakov this looks like auth / sso issue. Could you please take a look?

**Comment by alexeykazakov** [comment]
@xcoulon could you please take a look when you have time?
I see a bunch of errors like this around the time when that problem was reproduce: https://logs.dsaas.openshift.com/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),index:'project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:%22jPxnZWeC8o-973101%22)),sort:!('@timestamp',desc))

**Comment by xcoulon** [comment]
Doing a bit of research, the errors seems to happen when the client initiates an OAuth request with a `state` query param that was already stored in our database. This results in a `pq: duplicate key value violates unique constraint "oauth_state_references_state_key"` error.
This error does not happen too often, and may be related to the same set of accounts.

**Comment by ibuziuk** [comment]
@xcoulon thanks for investigation, so what would be the next steps? I noticed that according to logs this failure happened multiple times for the same `req_id`. Is it expected or the violation is too strick e.g. it should not happen for the same req ?

**Comment by alexeykazakov** [comment]
A few errors for the the same req id is most likely due to logging specifics. I think it’s just the same error logged a few times.
Regarding that constraint it’s not too strict. “state” represents an unique login request.
When the client (it’s Che in this case) sends an auth request to the auth service it must generate a unique state param. Auth service stores this incoming state. This state now represents that login request and is always present during all the following redirects and http requests (as part of the Oauth2 login flow) and finally a token is generated and the state is removed from the auth service.

But if the client re-uses the same state for another login request (for another user or even for the same user when trying to re-login again) then it will cause that issue. This is how OAuth spec works and we can’t/should not change it.

What we can do next:
1. In auth we can check if there is some very old states still present in the DB. If a login flow was interrupted and didn’t finish for whatever reason we might not clean up the outdated states. States should have expiry. Let’s check if we do the cleanup for such failed logins. If the client uses some strings which have a good chance to be repeated (not something like UUID for example) then overtime it can cause issues if we have too many “dirty” states in auth DB.
2. Worth checking if there were any changes in Che related to the auth client. Is there a chance of reusing the same state for different requests?

**Comment by ibuziuk** [comment]
@alexeykazakov  @xcoulon was able to reproduce today with 500 error on auth end
![image](https://user-images.githubusercontent.com/1461122/81261940-3f710e00-903d-11ea-97cf-aa05a335b732.png)

> But if the client re-uses the same state for another login request (for another user or even for the same user when trying to re-login again) then it will cause that issue.

I do not think we are reusing another state. Basically here is my steps to repro:
- in the morning I navigated to che.openshift.io
- was redirected to the RH login page
- after setting credentials I got the error
- page refresh helps and I was redirected to UD

**Comment by alexeykazakov** [comment]
If Keycloak JS adapter uses some short strings as state params then overtime there is a good chance that that string has been already used for some unsuccessful login. We are working on a fix which will cleanup old states from DB.
Just to be clear. If login is successful then we delete the used state from our DB. But if the login was interrupted then the used state is stuck in the DB. And it can't be used anymore.
The fix should be rolled out to prod today. I hope it will fix the issue.

**Comment by ibuziuk** [comment]
> If Keycloak JS adapter uses some short strings as state params then over time there is a good chance that that string has been already used for some unsuccessful login.

I checked the `state` query parameter on Hosted Che and this is a fairly random UUID

@skabashnyuk @mshaposhnik folks, do you happen to know how `state` query parameter is generated? I suspect via the js adapter, right?

**Comment by skabashnyuk** [comment]
>@skabashnyuk @mshaposhnik folks, do you happen to know how state query parameter is generated? I suspect via the js adapter, right?

I don't know.

**Comment by akurinnoy** [comment]
@ibuziuk I'm pretty sure that `state` is generated via adapter [here](https://github.com/keycloak/keycloak/blob/master/adapters/oidc/js/src/main/resources/keycloak.js#L419)

**Comment by davidfestal** [comment]
@akurinnoy Yes, that's also what I think. So I assume that cleaning old states as mentioned by @alexeykazakov would help.

**Comment by ibuziuk** [comment]
>  So I assume that cleaning old states as mentioned by @alexeykazakov would help.

@davidfestal this does not seem to help cc: @xcoulon could there be some auth internals logic that leads to those errors? As I understand on Che end state is generated on every login

**Comment by Macorreag** [comment]
I have the same problem, I think it is an inconsistency in the IDs to log into the RedHat account. In the case on the left, I accessed through my email and password of the RedHat account and it generates the error. In the case on the right, I accessed using Google OAuth authentication and it allows me to enter Eclipse Che without problems. I hope I can help with something, I don't know much about Eclipse, I'm sorry if this is irrelevant.

![image](https://user-images.githubusercontent.com/32028541/85498746-e7b74380-b5a5-11ea-9b3a-c4288ad8fb98.png)

**Comment by themr0c** [comment]
Hi, I had the following errors, successively, this morning. It started with the same error as in the issue. I am adding the next ones as they may be related. Fixed by refreshing (sometimes multiple refresh were necessary). I hope the screeshots help a little:

![Screenshot from 2020-06-25 08-45-16](https://user-images.githubusercontent.com/243761/85672896-a4eb8d80-b6c3-11ea-9434-c0077f064ff3.png)

![Screenshot from 2020-06-25 08-48-58](https://user-images.githubusercontent.com/243761/85672918-aae16e80-b6c3-11ea-9877-905db5b1ba87.png)

![Screenshot from 2020-06-25 08-51-27](https://user-images.githubusercontent.com/243761/85672947-b339a980-b6c3-11ea-8bb1-ff54145644bc.png)

![Screenshot from 2020-06-25 08-52-49](https://user-images.githubusercontent.com/243761/85672976-baf94e00-b6c3-11ea-88f3-7db4cbed420b.png)

**Comment by ibuziuk** [comment]
the failure is related to sso related issue. @themr0c can you still repro?

**Comment by sunix** [comment]
hey could reproduce many time this WE and this morning ... :(
Is it related to https://github.com/eclipse/che/issues/17154?
If yes, we should have a fix for it ASAP.
Here are the things to consider:
- Have a error message for the user describing the error and the origin and to try again (refresh? alt f5?)
- Consider an alternative SSO: eclipse foundation one?
- Maybe have an automatic retry.

**Comment by ibuziuk** [comment]
> Have a error message for the user describing the error and the origin and ask to try again (refresh? shift f5?)

@sleshchenko would be nice to have a message with refresh recommendation as part of #17154

**Comment by nickboldt** [comment]
Dumb question... why Eclipse Foundation SSO when we could use RH SSO? Then you'd be dogfooding the same stuff we use in CRW, instead of adding Yet Another Configuration To Test.

**Comment by alexeykazakov** [comment]
Hosted Che can't use anything but RH SSO because we have to use the same SSO as OSO.

**Comment by sunix** [comment]
@nickboldt the reason is that if this instance is a community instance, there is a conflict in the neutrality where a community user would need to give to RedHat, personal informations to use Che. Eclipse Foundation is neutral.
