### ISSUE TITLE
'node-debug' broken due to removal of legacy 'node-debug2'

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#16728]
In https://github.com/eclipse/che-plugin-registry/pull/380 we removed the node-debug2 extension form the plugin registry.
However, the "legacy" debugger contributes a couple of things like the launch configuration for attaching to a node process. In brief: it is an integral part of the VS Code debugging story.
We should really add it into the same Che plugin as the node-debug extension

**Comment by tsmaeder** [comment]
Both extensions are available from the openvsx registry: 
  - "http://open-vsx.org/api/ms-vscode/node-debug/1.44.2/file/ms-vscode.node-debug-1.44.2.vsix",
  - "http://open-vsx.org/api/ms-vscode/node-debug2/1.33.0/file/ms-vscode.node-debug2-1.33.0.vsix"

**Comment by tsmaeder** [comment]
Once again, but with the correct URIs:

- "https://open-vsx.org/api/ms-vscode/node-debug/1.41.1/file/ms-vscode.node-debug-1.41.1.vsix"
- "https://open-vsx.org/api/ms-vscode/node-debug2/1.33.0/file/ms-vscode.node-debug2-1.33.0.vsix"

**Comment by tsmaeder** [comment]
@ericwill @nickboldt proposing a fix that points to open-vsx is trivial, but I guess you'll want to have our own build of the plugin? Note that this is a VS Code built-in plugin, sourcewise.

**Comment by nickboldt** [comment]
> In brief: it is an integral part of the VS Code debugging story.

So integral that it took 2 months for anyone to notice? :D 

Snark aside, the latest node-debug2 for Node.js >=8 is 
* https://open-vsx.org/extension/ms-vscode/node-debug2 --> 1.42.1 
* (latest in sources https://github.com/microsoft/vscode-node-debug2/releases -> 1.42.2)

And the latest node-debug for Node.js < 8 is 
* https://open-vsx.org/extension/ms-vscode/node-debug -> 1.41.1 
* (latest in sources is https://github.com/microsoft/vscode-node-debug/releases -> 1.44.5)

So... if we have to bring this back we have two requirements:

a) sources and binary need to be on the same site (eg., download.jboss.org)
b) binary should be built from sources using https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/vscode-extensions-packaging/

After that I'll let you or @ericwill tell me if it makes sense to have one plugin in the registry which includes BOTH extensions, or have TWO plugins (each one with a single extension). I'm leaning toward the 2:1 approach since it would make the devfiles simpler (only need to enable one plugin).

THAT BEING SAID I'd like to see a bit more info about "a couple of things like the launch configuration" ... could we not just add that to our devfiles and therefore not have to depend on a plugin that's meant to used for Node.js 6 and earlier, which is EOL and dead?

**Comment by ericwill** [comment]
> > In brief: it is an integral part of the VS Code debugging story.
> 
> So integral that it took 2 months for anyone to notice? :D
> 
> Snark aside, the latest node-debug2 for Node.js >=8 is
> 
>     * https://open-vsx.org/extension/ms-vscode/node-debug2 --> 1.42.1
> 
>     * (latest in sources https://github.com/microsoft/vscode-node-debug2/releases -> 1.42.2)
> 
> 
> And the latest node-debug for Node.js < 8 is
> 
>     * https://open-vsx.org/extension/ms-vscode/node-debug -> 1.41.1
> 
>     * (latest in sources is https://github.com/microsoft/vscode-node-debug/releases -> 1.44.5)
> 
> 
> So... if we have to bring this back we have two requirements:
> 
> a) sources and binary need to be on the same site (eg., download.jboss.org)
> b) binary should be built from sources using https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/vscode-extensions-packaging/
> 
> After that I'll let you or @ericwill tell me if it makes sense to have one plugin in the registry which includes BOTH extensions, or have TWO plugins (each one with a single extension). I'm leaning toward the 2:1 approach since it would make the devfiles simpler (only need to enable one plugin).
> 
> THAT BEING SAID I'd like to see a bit more info about "a couple of things like the launch configuration" ... could we not just add that to our devfiles and therefore not have to depend on a plugin that's meant to used for Node.js 6 and earlier, which is EOL and dead?
> 
> And I'm wondering why you said we need debug2 1.33.0? Why not pull the latest?

Looking at the PR that broke the workflow, I don't see anything about node-debug? Only node-debug2, or am I missing something?

**Comment by tsmaeder** [comment]
1.33 is what's used in theia currently. You want to use a newer version, you'll have to test.
