### ISSUE TITLE
Can che-e2e image provide multi-arch support?

### ISSUE THREAD

**Issue by abhay1722** [eclipse-che/che#16872]
## Summary

The che-e2e image, is currently built using the base image `selenium/standalone-chrome:latest`, which is supported only on `amd64`.
Conclusively, the `che-e2e` fails on other architectures during build.
Is there a possibility that this can be made multi-arch?
Or are there any other ways with which we can execute tests for testing Che 7 happy path.

## Relevant information

https://github.com/eclipse/che/tree/master/dockerfiles/e2e

**Comment by rkratky** [comment]
@rhopp, could you please confirm?

**Comment by rhopp** [comment]
Hello @abhay1722 ,
We were not planning to have che-e2e image to be build for different architectures. Mainly because our testing infrastructure is purely amd64 arch. We can run this image with tests on amd64 even if the Che "under test" is running on different arch (s390/ppc).

If you need to have che-e2e image running on different arch, feel free to work on this issue and provide a PR.
If you need help/guidance from our side, you can contact us on mattermost.eclipse.org in `Eclipse Che QE` room.
