### ISSUE TITLE
Cannot create workspace for organization

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#16916]
### Describe the bug
Organization list not exists on ```Create Workspace``` page after [Redesign "Create Custom Workspace" page](https://github.com/eclipse/che/issues/15662) changes.

### Che version

 - [ ] latest
 - [x] nightly (7.14)
 - [ ] other: please specify

### Steps to reproduce
1. Open Dashboard.
2. Create an organization
3. Click on Workspaces link 
4. Open ```Create Custom Workspace``` page by ```Add Workspace``` button

### Expected behavior
Organizations list exists on the page

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
Organizations list on old create workspace page
![Selection_115](https://user-images.githubusercontent.com/7760565/81814997-2206dd00-9532-11ea-91b9-cd3dafb35f94.png)

### Installation method
   - [x] chectl
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
Potentially, it's not very difficult to fix this issue but there is a question if we really should not it.

According to yesterday's Che Internal Call: we agreed that we should consider disabling organization functionalities until it won't be revised within https://github.com/eclipse/che/issues/15304.

The main motivation - Organizations were designed to docker infrastructure and the main their purpose was limiting users RAM usage, but on K8s/OpenShift infrastructure RAM Resource API model does not work correctly anymore. The tip of the iceberg is https://github.com/eclipse/che/issues/11424, but then Che Resource API should be probably redesigned to be consistent with OpenShift Resource Quotas model.

In addition, some time ago we disabled the functionality of sharing workspaces to avoid the leak of user's personal data, like ssh keys. AFAIS with the organization this functionality is available without proper message for users that it's not really safe thing to do.

Once user is added to the organization - they are not able to create a workspace in their personal space anymore.

Despite of that fact that something works - like limit organization workspaces, running workspaces numbers, an ability for admin to see all members workspaces (possibly removing and stopping them but not sure). It's better to disable this feature which is partially working for a long time with a lot of inconsistency.

So, this issue is going to be discussed again on Che Community Call.

**Comment by sleshchenko** [comment]
It's P2 now since organizations are disabled by default.
