### ISSUE TITLE
I would like to see the list of my recent workspaces from che-theia

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17034]
### Is your enhancement related to a problem? Please describe.

I am not able to see the list of my recent workspaces from che-theia 

![image](https://user-images.githubusercontent.com/606959/83120429-57cec880-a0d1-11ea-8f3c-ca0800d8466a.png)

![image](https://user-images.githubusercontent.com/606959/83120480-6917d500-a0d1-11ea-999c-bf266cb34222.png)

**Comment by sunix** [comment]
@l0rd how is the developer flow behind this?

**Comment by azatsarynnyy** [comment]
Since Workspace term is very popular nowadays, there's an inconsistency started appearing between two different concepts of Workspace: `Theia/VS Code Workspace` and `Che Workspace`.

Currently, there're several Workspace related commands in Che Theia. All of them are referring to Theia/VS Code Workspace except `Toggle My Workspace View` which is referring to Che Workspace.
![image](https://user-images.githubusercontent.com/1636395/83735842-8a406e80-a659-11ea-840c-a05197b5b7d3.png)
These commands are used in different parts of the UI: main menu, command palette, context menus, etc. Besides that, Theia/VS Code Workspace concept is present in such key elements as Preferences.
![image](https://user-images.githubusercontent.com/1636395/83745868-e1007500-a666-11ea-8f4a-b461f6792469.png)

Today in Che Theia we have just one UI element (+command) that's referring to Che Workspace - `My Workspace` panel. That already may confuse the users, especially those who aren't familiar enough with both Workspace concepts.

Undoubtedly, we'll bring more Che Workspace related functionality into Che Theia through the different UI elements/commands. Which may lead to even to more confusion in the future.

So, first, we should decide **how we'll distinguish different Workspace concepts** in Che Theia. And **how they should coexist**.

While we can get rid of two Theia commands that make little sense in Che context (`Create/Close Workspace`), we cannot refuse to use the entire Theia/VS Code Workspaces functionality as it's very important one, especially for multi-root Workspaces support.
One of the possible approaches can be using different naming for referring to the different Workspace concepts.

Are there any other opinions on this?

**Comment by l0rd** [comment]
> @l0rd how is the developer flow behind this?

I am not sure I understand your question.

**Comment by benoitf** [comment]
VS Code assumes that all projects are on the filesystem while with Eclipse Che, you only have a set of projects per workspace (you switch from Che workspace instead of opening/closing folders)

As Mario said, we shouldn't get rid of close workspace.
Close Workspace = close the Che workspace
Open Recent workspaces =  list of like 5 recent workspaces (like in dashboard)
Open workspaces = list of all Eclipse Che workspaces

you may rename open workspace(theia) to open folder or from the "open..."

**Comment by azatsarynnyy** [comment]
> As Mario said, we shouldn't get rid of close workspace.
Close Workspace = close the Che workspace
Open Recent workspaces = list of like 5 recent workspaces (like in dashboard)
Open workspaces = list of all Eclipse Che workspaces

@benoitf does that mean we should replace the existing commands with our own Che specific?
I believe we should keep the existing (Theia Workspace related) commands as is. But add additional commands - specific to Che Workspace. WDYT?

**Comment by azatsarynnyy** [comment]
> why Create/Close Workspace doesn't make sense in Che context?

Because it's useless in Che Theia IMO. After closing Che Theia Workspace, the user will see the empty file explorer:
![image](https://user-images.githubusercontent.com/1636395/83885707-68291800-a74f-11ea-8ceb-81be88b5163c.png)

> In general, from an end user point of view, there should be no difference between Theia an Che Theia workspaces.

@l0rd well, it depends on what we mean by `Che Theia workspaces`.
In my understanding, Theia Workspace, Che Theia Workspace, VS Code Workspace are equal concepts. But they are different from Che Workspace, of course.

**Comment by azatsarynnyy** [comment]
Just to make sure we're on the same page, let me clarify my vision.
(Che)Theia Workspace allows me to work with one or multiple project folders in Che Theia within the same Che Workspace. So, within my single Che Workspace, I can have many (Che)Theia Workspaces that are actually the different virtual views to my project sources.

For example, in my Che Workspace, I have Che project sources imported. If I'm working with tests only I may be interested just in two folders:
- `/projects/che/tests`
- `/projects/che/dockerfiles/e2e`.

In Che Theia, I can set up a (Che)Theia Workspace with only these two folders included. And switch between the "full tree" and Tests view when I need to.
In such case, `File - Open Recent Workspace...` allows me to choose (Che)Theia Workspace to switch to:
![image](https://user-images.githubusercontent.com/1636395/83880970-aa029000-a748-11ea-8268-e09e857b41ec.png)

---

Another example. In my Che Workspace, I have both projects' sources imported: upstream Theia and Che Theia. If I'm currently focused on Plugin system only, instead of seeing the entire trees of both monorepos I may want to see just several folders in Che Theia:
- `/projects/theia/plugin-ext`
- `/projects/che-theia/eclipse-che-theia-plugin-ext`
- `/projects/che-theia/eclipse-che-theia-plugin-remote`

I can save such setup as (Che)Theia Workspace and switch to it whenever I need:
![image](https://user-images.githubusercontent.com/1636395/83884424-8a219b00-a74d-11ea-8ef7-7b4882d26f04.png)

---

I propose to keep this functionality as is but add the additional commands to work with Che Workspaces.

@l0rd @benoitf please, let me know if that's not the behavior you expect.

**Comment by azatsarynnyy** [comment]
Another question is what's expected to be done after choosing any Che Workspace from the list when calling `Open Recent Workspace...` command? There are two options I see:
1. Open a Che Workspace in another browser tab
2. Ask the user whether to stop the current Che Workspace and navigate the browser to the chosen Che Workspace

I'd prefer the 2'nd option as running >1 Che Workspace isn't allowed by default.

**Comment by benoitf** [comment]
> Open Recent Workspace:

- Detect the number of allowed running workspaces
- if limit is reached, ask to confirm to close the current one
- I'm not sure about opening a new window. Maybe it's an option

**Comment by l0rd** [comment]
Ok thanks for the explanation @azatsarynnyy. The value of the concept of Theia workspace is evident from your examples.

The probolem is that Che and Theia workspaces are different things. Right now Che uses the term "Workspace" in his editor to refer to Theia workspaces. That's confusing. I think we agree that we need to fix it.

A Che workspace is set of tooling and runtime containers that together form an IDE. We can continue calling it workspace or use an alternative names: `devpod`, `IDE`, `devspace`...

A Theia workspace is a set of local source code folders, alternative names (in a Che context) are `environment`, `sources`, `project`...

Imo we should not consider the option to rename Che workspaces into something else: it would have the benefit to make Che and upstream Theia consistent but it would have a huge impact in terms of code to change, it would confuse existing users and conflict with our current model where the dev environment is not defined by projects AND sidecars (not by projects only).

Anyway that should be discussed and pondered carefully. That's why I am proposing in this issue to be pragmatic and start replacing some Theia workspace commands with Che workspaces commands. We may loose some functionality related to Theia workspaces in the process but current inconsitencies are more urgent to fix. And as soon as we have a good name replacement for Theia workspaces we will resume the Theia workspaces commands. 

Does that sounds good?

**Comment by azatsarynnyy** [comment]
> Does that sounds good?

I agree. "Workspace" term should be used in Che Theia to refer to Che Workspaces only.

It may confuse the experienced VS Code users, that VS Code-like editor has well-known commands with completely different behavior. But we'll think about how to make it more consistent in the future.

**Comment by azatsarynnyy** [comment]
I've opened an epic for Workspace related commands consistency and finding a good name replacement for Theia Workspaces related commands https://github.com/eclipse/che/issues/17106

**Comment by azatsarynnyy** [comment]
This is currently blocked by https://github.com/eclipse/che/issues/17246
Investigating how to get a user token in Che Theia for accessing Che Workspace API.

**Comment by sunix** [comment]
I think renaming would be good:
- it will clarify things for the users
- renaming to a cool name could be turn into a buzz that would promotes Che in some ways

we could start with labels in the front end and rename bits by bits, it is ok to say that a Che workspace is a Devspace ...

**Comment by azatsarynnyy** [comment]
#17246 is fixed
the next blocker for this issue is #17361

**Comment by vzhukovskii** [comment]
Following PR for #17361 : https://github.com/eclipse/che-dashboard/pull/66

**Comment by tsmaeder** [comment]
I'm late to this discussion, but IMO replacing some of the "Workspace" commands in Theia with workspace commands is ultra-confusing. Also, the Theia workspace commands are important when developing che-theia (can't rely on the devfile to set up the Theia workpace, it needs to be different from the "outer" workspace).
Can't we just add a "Che" main menu and then we'd have  Che=>Open Workspace..., Che=>Open Recent...

**Comment by azatsarynnyy** [comment]
@tsmaeder it was decided to have both sets of commands: Theia Workspace related and Che Workspace related.
And rename Theia ones to something else, e.g. https://github.com/eclipse/che/issues/17106#issuecomment-648644809

**Comment by azatsarynnyy** [comment]
closed by https://github.com/eclipse/che-theia/pull/800
