### ISSUE TITLE
How to create custom stack in eclipse che 7

### ISSUE THREAD

**Issue by sushant08** [eclipse-che/che#17050]
## Summary
I want to create a custom che stack having all my required packages installed found only document in a blog by "Doug Tidwell" but seems it is for different version  as many option is not. present in che 7. Can Anyone help me in finding documentation.

**Comment by ericwill** [comment]
I believe you are looking to create a devfile, is that what you mean by "stack"? Check out this article: https://che.eclipse.org/discover-che-7-devfile-85a8cc83d860

**Comment by sushant08** [comment]
> I believe you are looking to create a devfile, is that what you mean by "stack"? Check out this article: https://che.eclipse.org/discover-che-7-devfile-85a8cc83d860

I have seen that and tried it also but it not giving me option to save it as stack so that other che users can also use that stack like any other default one.

**Comment by l0rd** [comment]
@sushant08 you want to:

1. Write a [custom devfile](https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/)
2. [Include it in the devfile registry](https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/) so that it appears in the Dashboard Getting started
