### ISSUE TITLE
Docs still mention manual creation of ssl secrets but that's not needed anymore

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17150]
### Describe the bug

Section `Installing Che in TLS mode with self-signed certificates` of [the doc](https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates) needs to be reviewed. 

In particular:
- [Deploying Che with self-signed TLS certificates on OpenShift 4 using Operator](https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#deploying-che-with-self-signed-tls-on-openshift4-using-operator_installing-che-in-tls-mode-with-self-signed-certificates) can be removed since it's now automated and doesn't require any action from the user.
- [Generating self-signed TLS certificates](https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#generating-self-signed-certificates_installing-che-in-tls-mode-with-self-signed-certificates) should be move out from installation section: it's about usage of a Che workspace, not about installation.

The other sections needs to be reviewed by deploy team.

**Comment by l0rd** [comment]
Some details [here](https://github.com/eclipse/che/issues/17302#issuecomment-653945468)

**Comment by themr0c** [comment]
Is it still necessary for Kubernetes and OpenShift 3? https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#deploying-che-with-self-signed-tls-certificates-on-kubernetes_installing-che-in-tls-mode-with-self-signed-certificates and https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#deploying-che-with-self-signed-tls-certificates-on-kubernetes_installing-che-in-tls-mode-with-self-signed-certificates

**Comment by themr0c** [comment]
Reading https://github.com/eclipse/che/issues/17302#issuecomment-653945468, the OpenShift 3 section can move out also.

**Comment by amisevsk** [comment]
To summarize the discussion here: it looks like the entire 

> Installing Che in TLS mode with self-signed certificates

section should be removed. Currently it lists 
- How to generate certs (suggested to move out, but what's the point in having it when nothing requires it)
- Deploying on Kubernetes (not required, since it's done automatically)
- Deploying on OpenShift 4 (not required, generated automatically)
- Deploying on OpenShift 3 (only required when using `minishift`: https://github.com/eclipse/che/issues/17302#issuecomment-654065845
- Importing self-signed certs into browsers: not a Che-specific doc, should be moved elsewhere?

I suppose a similar section should be added that explains how cert-generation works and how to import self-signed certs to your browser?

Where should a doc on generating certs for minishift be stored? Putting it at the top level in the sidebar clutters the view with something 95% of users will never use.
