### ISSUE TITLE
Clarify behaviour of chectl/crwctl 's default installer mode in inline docs

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17165]
I've heard that when using chectl/crwctl to install, different behaviours are the default.

* OCP 3.11 :: `-a operator`
* OCP 4.x :: `-a olm`

Yet in the inline help:

```
$➔ crwctl server:start --help
start CodeReady Workspaces server

USAGE
  $ crwctl server:start

OPTIONS
  -a, --installer=operator|olm
      [default: operator] Installer type
```

There is no mention of this platform-specific default behaviour.

Furthermore, what happens if you're installing on OCP 3.11 BUT you have OLM installed on that cluster? Will OLM mode be the default? Or will it still be operator? 

Is this behaviour driven by detection of OLM, or by OCP version? (IMHO it should be driven by the presence of OLM in the target cluster, so we can use OLM installer mode on OCP 3 if OLM is present.)

Also, since we do not want to support the old operator method on OCP 4, what happens if a user EXPLICITLY asks for `-a operator` on OCP 4.4? I would expect this:

* an error is thrown preventing install because operator is not supported on OCP 4, or
* a warning is thrown, telling the user that operator method is not supported and we've automatically switched them to `olm` mode

Personally, I would prefer an **error** since it forces the user to fix their mistake, but UX team might feel that an approach of "we know you asked for `operator` but we know you really want `olm` so that's what you're getting instead" might be acceptable too. 

cc: @RickJWagner

**Comment by nickboldt** [comment]
Related to:

* OLM should be the default chectl installer on OpenShift 4.x #16861
* Make the new `olm` chectl installer easier to use downstream #16862

**Comment by tolusha** [comment]
1. platform-specific default behaviour.

In general case the default installer type depends on `chectl` flags.
We just can mention, that `olm` is used for openshift 4.x
https://github.com/che-incubator/chectl/blob/master/src/commands/server/start.ts#L431-L446

2.  Furthermore, what happens if you're installing on OCP 3.11 BUT you have OLM installed on that cluster? Will OLM mode be the default? Or will it still be operator?

operator will be used

3. Also, since we do not want to support the old operator method on OCP 4, what happens if a user EXPLICITLY asks for -a operator on OCP 4.4? I would expect this.

operator will be used. 
In case not supporting something, that an issue for downstream project. And only there we should have restrict using operator for OCP4.x

**Comment by tolusha** [comment]
Currently:
1. the default value for `operator` flag is empty
2. autodetection is used for installer type https://github.com/che-incubator/chectl/blob/master/src/commands/server/start.ts#L431-L446
3. the installer type is printed in the log
`› Installer type is set to: <...>`

/cc @nickboldt

**Comment by tolusha** [comment]
Fixed https://github.com/che-incubator/chectl/pull/796/commits/b7719daf79dde0d1727c7f0fdef0cefd54d667c6
