### ISSUE TITLE
Write documentation, how to generate certificates for Che on Windows

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#17302]
### Is your enhancement related to a problem? Please describe.
We have some feedback https://github.com/eclipse/che-operator/pull/186#issuecomment-652376243, that there is a knowledge and documentation lack how to generate certificates for Che on Windows.

### Describe the solution you'd like
It would be nice to have a docs section for Windows users how to generate and use certificates for Che.

**Comment by l0rd** [comment]
What is not clear is in what circumstances does a user need to generate a certificate? I thought that users do not need to manually generate the certs anymore. Isn't it the case @tolusha ?

**Comment by tolusha** [comment]
It is the case for minishift only when outdated certificate is used in minishift infrastructure.

**Comment by l0rd** [comment]
Any OCP 3.11 or minishift only?

**Comment by tolusha** [comment]
Just minishift

**Comment by l0rd** [comment]
Ok so that need to be super clear. Minishift is probably the less used platform and we do not want that users spend their time generating certificates if not needed.

**Comment by erlansan** [comment]
@l0rd what would be your suggestion instead of minishift for windows? I've went with it because RedHat is hosting Che on minishift. At the beginning, i've tried setting it up on docker, but since the instructions were written the technologies have changed, as well as the commands. At the end i couldn't do it with docker. Then i decided to move on minishift and it worked right away(ca. February). After that i updated the chectl and since then i can't get my Che pod to start, it always times out. So i've tried setting up certificates and couldn't get it done. All the commands were written for linux, and i lack knowledge and experience to do it on my own. 
My question would be: What platform is the best for hosting Eclipse Che? 
I'm currently in the process of creating a custom build Che-Theia and hosting it on Che for my bachelor thesis. I would really appreciate if you could help me out with getting past Che pod timing out on minishift, or advice on what platform to choose instead.

**Comment by tolusha** [comment]
@erlansan 
For local testing you can use minikube.
In this case a certificate will be created automatically for you.

**Comment by l0rd** [comment]
If you want to test Che locally (on your laptop) I would suggest minikube or CodeReady Containers. The latter requires much more memory.

**Comment by boczkowska** [comment]
Docs Jira issue: https://issues.redhat.com/browse/RHDEVDOCS-2575

**Comment by themr0c** [comment]
@l0rd given you last comment we believe we can safely close this issue.
