### ISSUE TITLE
What does "Project git url" be used?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#174]
In the "git" menu of a project, there is a "Project git url":

![image](https://cloud.githubusercontent.com/assets/333781/12221044/0343ec6c-b7c6-11e5-886c-b23587e940a6.png)

If I click on it, it will show a dialog with a local project url:

![image](https://cloud.githubusercontent.com/assets/333781/12221046/21978840-b7c6-11e5-81b9-b13e971e47ae.png)

I tried to visit it from browser or `git clone` it, neither works. Just be curious what is that?

**Comment by ghost** [comment]
There's no Git server running there, so this is a bug.

**Comment by TylerJewell** [comment]
Also - on the topic of the REST API - we are close to having a commit where there will be embedded swagger server within Che for browsing & testing the internal REST APIs. The docs will be updated after that is available.

**Comment by TylerJewell** [comment]
This is logged as issue.
https://jira.codenvycorp.com/browse/IDEX-4043?jql=text%20~%20%22git%20URL%22%20ORDER%20BY%20created%20DESC

This issue will be trackable on GitHub after we have exported our Jira database to GitHub.  Going to close this issue for now as the product provides expected behavior. This is -- instead -- a UI cleanup issue as while the URL exists & is valid, it is not remotely accessible. Che is not a git repo server at this time.
