### ISSUE TITLE
[Memory] Should language server be run multiple times for multiple browser tabs?

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse-che/che#17415]
## Summary
I can't understand why for the same workspace I can see language servers being run several times. If I accidentally opened several tabs in a browser I would get a message about the crash because of memory. And memory limit cannot be controlled. I can understand It if several users share workspace and they could see different errors for unsaved files. What do you think of It? Might be It is reasonable to prevent opening several tabs for the same workspace in the same browser? 

## Case (also can be reproduced here https://che.openshift.io)
* Create "Java + Maven" workspace
* Enable auxiliary plugins, e. g. yaml, xml or some else
* Open several files in workspace, e. g. Java, Yaml, XML....
* Duplicate tab several time

AR:
```
Plugin runtime crashed unexpectedly, all plugins are not working, please reload the page. Probably there is not enough memory for the plugins. If it doesn't help, please check Theia server logs.
```

**Comment by l0rd** [comment]
@tsmaeder should be able to provide you a good explanation for this.

**Comment by tsmaeder** [comment]
@gorshkov-leonid when you open a second tab, you're effectively starting a second copy of the Theia IDE, including many back-end services and all plugins. You can, for example, easily open a different set of folders in the second tab. This is a basic design decision in Theia and I think trying to change that in Che would be very hard for limited gain.
Limiting a Theia back-end to a single front end is something that might be feasible. I have no idea right now how we would do that, though, and how hard it is. The downside is that we would remove a feature that might be useful to some users. We can never guarantee that some plugin container does not run out of memory. Just add enough source code and you _will_ run into out of memory conditions. So IMO the issue boils down to the following two questions:

1. How often do users run out of memory because of multiple tabs "in the wild"
2. How obvious is it to the user what the problem is and how to fix it (in that case, it's easy: don't open multiple tabs).

**Comment by gorshkov-leonid** [comment]
@tsmaeder, thank you. I agree, in my opinion "in the wild" users usually do not open several tabs.  But this also could happen when users in a group share workspace to collaborate work.  

Might be this is a question of what on the server and client can be shared but what not to be. I understand case when a user could be wanted to have a second tab with different contexts - this cannot be limited. 

And I do not know what on a server could be shared, but may be It can be applied to language servers? Or at least a developer could choose if LS shares its state or not. For example
1. Some LS is fully stateless and there is no reasons start different instances 
2. LS has a state, error validation depends on some unsaved contents in a cache. But I can set "autosave" thereby not using cache unsaved documents and making LS shared. 
On which level I could have prevented to start extra instances and use the same LS per workspace?

**Comment by tsmaeder** [comment]
> Or at least a developer could choose if LS shares its state or not. For example

We simply don't have access to the language servers at this level: we're using the language servers via the VS code extension API, and therefore we're not even aware that there _is_ a language server inside the extension. What this comes down to is that if language servers could be reused across instances of the IDE, that sharing would have to be inside the extension, or even the language server.
I've looked at the case of vscode-java in the past and one interesting fact there is that for usual project sizes, a lot of the memory consumption is just for running the language server process (class files, etc.), not heap memory: so having a shared language server process seems more important than sharing the data it holds. However, since we're building upon a large technology stack (involving a headless copy of Eclipse Java IDE), it's not simple to make this stack multi-tenant.

**Comment by gorshkov-leonid** [comment]
Really, I got it. This should be done on vscode plugin's level. But I think it feasible to wrap plugin where wrapper creates a proxy, maybe even in build time. It's in the plans.

What you said about Java. I can say the same about Yaml for example. But memory consumption of YANG plugin (Yangster) very depends on project size because of the cache and could be large.

@tsmaederThank you, I have no more questions
