### ISSUE TITLE
Could milestones for PRs be handled automatically?

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17421]
### Is your enhancement related to a problem? Please describe.

Today, milestones are created in the eclipse/che project manually by yours truly in blocks of 4 (once a quarter).

But if we want to use milestones for PRs too, we need those to be added to all the other 20? 30? other repos, including...

[ ] [https://github.com/eclipse/che-*](https://github.com/eclipse/?q=che&type=&language=)
[ ] https://github.com/che-incubator/ *
[ ] https://github.com/che-dockerfiles/ *

### Describe the solution you'd like

a) tooling that runs at intervals to add new milestones (once a sprint, keeping current + 4 future milestones always available)
b) tooling that can be triggered when a PR is merged to automatically compute the milestone in which a PR was merged, with a comment posted on the PR and the linked issue

We likely also need a manifest file with all the repos to be watched/updated, so that the tooling knows where to search & where to add milestones / update PRs. This might be a .github/PR_AUTOMATION_REPOS file for example

### Describe alternatives you've considered

The current approach is to attempt to tell developers to write better commit messages on PRs with links to issues, and to continue to manually add milestones to ONLY the eclipse/che repo where the issues are tracked.

But bear in mind that the che-docs repo also contains issues and PRs separate from che, and that repo does NOT today have up to date milestones to set as fixversions. Docs team has asked for milestones so they can better identify when something is planned and/or actually delivered. 

### Additional context

See discussions in Che internal call: https://docs.google.com/document/d/1lbLCFhP1WAbTK3RGcPrucggv7GFOIaeplkFE8Rsy8M0/edit
See Defintion of Done discussion in https://docs.google.com/document/d/1Zu7l-KkYxTdXEXF_3wePufQHHSTrD12envZHOXRmUxc/edit
(apologies if links are private)

**Comment by ericwill** [comment]
> ### Describe alternatives you've considered
> 
> The current approach is to attempt to tell developers to write better commit messages on PRs with links to issues, and to continue to manually add milestones to ONLY the eclipse/che repo where the issues are tracked.
> 
> But bear in mind that the che-docs repo also contains issues and PRs separate from che, and that repo does NOT today have up to date milestones to set as fixversions. Docs team has asked for milestones so they can better identify when something is planned and/or actually delivered.

IMO the milestone/type/label metadata is best set at the issue level, and limited to issues in one or two places (`che` and `che-docs`) repos. Setting this data for all PR's is:
* Far too granular for anyone looking at it, as there are often multiple PRs per issue
* Double handling of work, as the milestone is set `x` times, where `x` is the number of PRs needed for an issue to be closed
* Doesn't take into account PRs on outside repos, like `eclipse/theia`

Instead I propose that:
* All PRs need to be linked to a corresponding issue in either `che` or `che-docs`
* All issues need metadata set correctly (milestone, type, labels, etc.)

This allows for easy viewing of all release deliverables in one place (2 repos instead of 10+), saves developer time (metadata set once), and is easy to maintain (no milestones needing to be added to 10+ repos).

**Comment by l0rd** [comment]
I would love to see milestone associated to PRs because that's the only way to know the precise content of a release (the problem with issues is that they can last multiple releases, be associated to multiple PRs or they may not exist for some PRs). 

But I don't think we have an agreement on that yet. So for now I would rather:
- think about how we can automate the milestones creation every 3 weeks (cc @benoitf)
- make sure that the right milestones are associated to WIP issues

**Comment by benoitf** [comment]
automation is not a problem as long as there is agreement on what to do :-)
Current suggestion of Mario is easily doable

**Comment by ericwill** [comment]
It seems redundant to me to add milestones to every PR, issue, and then on-top of it have the sprint plan umbrella bug (which by definition is a summary of the work for a release).

If we are trying to better track work that goes into a release, maybe we should ask team leads to better update their sprint plans, on top of requiring issues (with milestones) to be attached to PR's. This way you can query the work that has been done by looking at the sprint plans, and looking at issues in the main Che repo. Seems more manageable than checking multiple repos, even if it's automated.


> automation is not a problem as long as there is agreement on what to do :-)
> Current suggestion of Mario is easily doable

Well it doesn't capture/ignores work done outside of Che repos, like theia API (which our team spends a decent chunk of time on), as well as "soft" tasks that aren't represented in PR's (PR reviews in upstream theia, for example).

**Comment by benoitf** [comment]
here is a PR to introduce a yaml file containing the list of repositories: https://github.com/eclipse/che/pull/17464

**Comment by benoitf** [comment]
hello, some updates:

since one week:
- milestones are automatically set on all merged PRs when being merged.
- milestone details from che repository (name, description, dueDate, state, etc) are also automatically replicated to other repositories

note: this is applied only for repositories listed here https://github.com/eclipse/che/blob/master/.repositories.yaml when `useCheReleaseLifecycle: true`

**Comment by ericwill** [comment]
Sounds like we can close this ticket, no?

**Comment by nickboldt** [comment]
Closing. But we would love to also have milestones assigned to issues (and when backported, re-assigned to the earlier milestone), so https://github.com/eclipse/che/issues/19223
