### ISSUE TITLE
Support object array preferences in a devfile

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#17481]
### Is your task related to a problem? Please describe.
As part of #16851 we need to be able to set the jdt-ls `"java.configuration.runtimes"` settings, which accepts an array of JSON objects. Currently this is not support in a devfile.

You can find an example of such a preference [here](https://github.com/redhat-developer/vscode-java#setting-the-jdk).

Some similar work was already done in #16594. Someone from our team would be able to help with the review + test effort.

**Comment by tsmaeder** [comment]
Hmh...I really think we need a solution that can include _any_ valid VS Code preference in JSON Format. Since we probably don't want to start validating the preference schema in the devfile, that would mean any valid JSON structure. Anything less and we'll just be playing catch-up with the next VS Code extensions that uses weird preferences.

**Comment by skabashnyuk** [comment]
The simplest solution at this moment is to put the whole JSON to the "java.configuration.runtimes" as a string.

**Comment by tsmaeder** [comment]
@skabashnyuk that does not seem to have worked for https://github.com/eclipse/che/issues/16594...has anything changed?

**Comment by skabashnyuk** [comment]
>@skabashnyuk that does not seem to have worked for #16594 ... has anything changed?

Yes. You can use an array of strings.

**Comment by tsmaeder** [comment]
But we need arrays of json object, not arrays of strings.

**Comment by tsmaeder** [comment]
Since the devfile parses the preferences, it needs to understand what we want to pass through. An alternative would be to just pass through the text unchanged:
```
- preferences
   referenceContents: "any json here to be interpreted by Theia"
```

**Comment by gattytto** [comment]
related https://github.com/eclipse/che/issues/15577

**Comment by skabashnyuk** [comment]
>But we need arrays of json object, not arrays of strings. 


I get that. And we can't do that because of concrete reason. Unstructured data is not supported at this moment. And my proposal to solve this issue on plugin side. Also, I doubt that that possible on Devfile 2.x side too.

```
- preferences
   referenceContents: "any json here to be interpreted by Theia"
```

If  "any json here to be interpreted by Theia"  is a string  - you can do that already. 
CC @davidfestal @l0rd

**Comment by tsmaeder** [comment]
> Unstructured data is not supported at this moment. 

I don't get it: we have plenty of sections in the devfile that support "referenceContent", which is exactly unstructured JSON, in many cases.
Since the preference data is specific to Theia anyway, why not just stop interpreting the data altogether and handle it like we do for "vscode-tasks" command actions?

**Comment by skabashnyuk** [comment]
>I don't get it: we have plenty of sections in the devfile that support "referenceContent", which is exactly unstructured JSON, in many cases.
Since the preference data is specific to Theia anyway, why not just stop interpreting the data altogether and handle it like we do for "vscode-tasks" command actions?

It's a bit different story,  not the one that is requested in the description.
You are talking about "propertiesReferenceContent" for the component.?

```yaml
  id: redhat/java/0.38.0
  type: chePlugin
  propertiesReferenceContent : "any json here to be interpreted by Theia" 
```
?

**Comment by tsmaeder** [comment]
Do we have that?

**Comment by skabashnyuk** [comment]
no. But it's an equivalent of 
```yaml
- preferences
   referenceContents: "any json here to be interpreted by Theia"

```
that is already possible to define AFAIK.

**Comment by tsmaeder** [comment]
@skabashnyuk it's not equivalent to interpreting a particular value as being a settings.json. For one thing, we need a policy to handle clashes if someone defines the same preference in both the settings.json property and as it's own property. Also, the "magic" property needs to be documented and known by the user.
Generally, I think this would be much cleaner if we just handled it at the devfile level: either support some general transliteration of yaml properties into structured preference values or just support encoded json.
I can hack it for now, though.

**Comment by tsmaeder** [comment]
The fix I've proposed handles all preference string values as JSON to be parsed. In order to be non-breaking, the fix treats stuff that is not parseable as strings. So while correctly we would have to write
```
foo: '"this is a string"'
```
it will fall back to using using `this is a string` as the preference value.

**Comment by ericwill** [comment]
We can close this one now, right @tsmaeder?
