### ISSUE TITLE
[telemetry] Creating Woopra / Segment sidecar plugin  

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17543]
### Is your task related to a problem? Please describe.

Telemetry plugin for Woopra / Segment CDP that could be enabled in every workspace as a sidecar

### Describe alternatives you've considered
N/A

### Additional context
Docs - https://www.eclipse.org/che/docs/che-7/telemetry/
Plugin example - https://github.com/che-incubator/che-workspace-telemetry-example
Hosted Che telemetry plugin - https://github.com/redhat-developer/che-workspace-telemetry-woopra-backend

**Comment by ibuziuk** [comment]
The plugin should have an option enabled by default to encrypt user sensitive data like usernames / emails (email domains should still be unencrypted).

**Comment by tomgeorge** [comment]
Depends on https://github.com/redhat-developer/rh-che/issues/1989

**Comment by tomgeorge** [comment]
@ibuziuk Currently, the woopra backend does not have any knowledge of names and e-mail addresses.  The process decodes a UID from `$CHE_MACHINE_TOKEN` and uses that to send events to Woopra.  I assume on the back-end that UID is correlated with postgres/keycloak and the name/email is grabbed that way.

The segment API has an [identify](https://segment.com/docs/connections/sources/catalog/libraries/server/java/#identify) message, but it looks like you are only supposed to call that when an account is created/modified.  I'm guessing this `identify` message is sent at some point in the flow, otherwise how would Woopra know the mapping of UIDs -> Names and E-mail addresses? 

I think we need more information about that piece of the flow before this can be worked on further.

**Comment by ibuziuk** [comment]
> I'm guessing this identify message is sent at some point in the flow, otherwise, how would Woopra know the mapping of UIDs -> Names and E-mail addresses?

@tomgeorge I believe we are doing it during the e2e registration flow - https://github.com/redhat-developer/rh-che/blob/master/plugins/fabric8-end2end-flow/src/main/resources/end2end/files/RhCheKeycloak.js#L360-L398

**Comment by tomgeorge** [comment]
@ibuziuk so during the registration flow should we hash the payload of the identify message?

For existing users, we can probably run a one-off process to get the names and e-mails of existing UIDs, and make a new `identify` message that has their information hashed.

**Comment by ibuziuk** [comment]
>  so during the registration flow should we hash the payload of the identify message?

yes, but this should be done on the Toolchain registration step when the  `identify` will be called - so, no hashing on the Che / Crw plugin end.

**Comment by tomgeorge** [comment]
This has been deployed on prod-preview, deploying to prod today.

**Comment by ibuziuk** [comment]
I believe we can close this issue once the doc PR is merged - https://github.com/eclipse/che-docs/pull/1636
