### ISSUE TITLE
[operator / docs] Eclipse Che installed via operator should use the "common" PVC strategy by default 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17654]
### Is your task related to a problem? Please describe.
Currently, `per-workspace` is used by default which is resource aggressive.

This issue is follow up on the discussion started in https://github.com/eclipse/che/issues/17648

**Comment by tolusha** [comment]
If it is needed to tune something administrator can set the pvc strategy that reflects the requirements.
But the default value should allow to start workspaces in most cases, because `common` pvc strategy has the following limitation:
```
If PV does not support ReadWriteMany (RWX) access mode, the configuration will work only if one or both of the following apply:
* Workspaces are in separate Kubernetes namespaces
* Only one workspace is running per Kubernetes namespace at the same time
```

**Comment by ibuziuk** [comment]
Only one workspace is running per Kubernetes namespace at the same time - is already enabled by default everywhere no?

**Comment by l0rd** [comment]
Current default configuration:
- [users are NOT allowed to run more than one workspace at the time](https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties#L65)
- [PVC strategy is `common`](https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml#L102).

And it makes a lot of sense. But then I am not sure what this issue is about then. The only thing is that we should probably update [the documentation guide to run more than one workspace at a time](https://www.eclipse.org/che/docs/che-7/installation-guide/running-more-than-one-workspace-at-a-time/): the PVC strategy should be changed to per-workspace to run more than one workspace at a time.

**Comment by ibuziuk** [comment]
checked the default CR and indeed atm `common` is the default (when the issue was created it was not the case):

![image](https://user-images.githubusercontent.com/1461122/109024341-f10d2880-76bd-11eb-89ac-56d957ea73a9.png)

@tolusha could you clarify when this was changed?

> the PVC strategy should be changed to per-workspace to run more than one workspace at a time.

yup, this makes sense

**Comment by tolusha** [comment]
That's strange. I've checked recent versions and all of them contained 
```yaml
    pvcStrategy: 'common'
```

**Comment by ibuziuk** [comment]
that is also a surprise for me, but I checked against `7.26.1`, and indeed the `common` is the default: 
![image](https://user-images.githubusercontent.com/1461122/109025626-2f571780-76bf-11eb-9030-9e9bbecd7829.png)

**Comment by ibuziuk** [comment]
> The only thing is that we should probably update the documentation guide to run more than one workspace at a time: the PVC strategy should be changed to per-workspace to run more than one workspace at a time.

going to update the docs and close the issue

**Comment by ibuziuk** [comment]
@l0rd @tolusha please, review - https://github.com/eclipse/che-docs/pull/1902
Once merged, I believe we can close the issue

**Comment by ibuziuk** [comment]
PR has been merged closing
