### ISSUE TITLE
Generate branches every sprint for jwtproxy

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17743]
### Is your enhancement related to a problem? Please describe.

Today, jwtproxy has only 2 tags, one using the "v" convention, and one without:

https://github.com/eclipse/che-jwtproxy/tree/v0.10.0
https://github.com/eclipse/che-jwtproxy/tree/0.0.1

(plus 2 that I created to make it easier to build CRW.)

Also today, I manually create 7.16.x or 7.18.x branches so that I'm not required to use master or a random commit SHA.

https://github.com/eclipse/che-jwtproxy/tree/7.18.x
https://github.com/eclipse/che-jwtproxy/tree/7.16.x

### Describe the solution you'd like

So... should the jwtproxy project start generating a once-per-sprint branch? We can script that and do it as part of the overall Che release process. Or we could do a weekly tag. Or both. 

WDYT @skabashnyuk  ?

**Comment by skabashnyuk** [comment]
That is a nice proposal @nickboldt . How over its not very cleary what for?
I think we should be more close to GO traditions in go-based projects. That is why I've used `v0.10.0` in the latest tag.
Also, I think we should be more community-friendly and use well know Github Actions to build images instead of custom script. Since the number of changes in this repository is low I don't see a reason to create 7.x branches or use 7.x versioning. 

Can you explain the motivation if this task?

**Comment by nickboldt** [comment]
New branch creation action created: https://github.com/eclipse/che-jwtproxy/actions?query=workflow%3A%22Create+branch%22
