### ISSUE TITLE
 Pre-created by admin k8s namespaces

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#17842]
### Is your task related to a problem? Please describe.
We would like to handle use case when admins of k8s cluster want to pre-create namespaces for users

### Describe the solution you'd like
- Use parameter from this issue https://github.com/eclipse/che/issues/17841 that is telling che
 that k8s namespaces are going to be pre-crated.
- introduce new parameter some like che.infra.kubernetes.namespace.labels=app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspace,che.eclipse.org/created-for=<userid>
  by this parameter, we can filter available k8s namespaces and use it for che workspace
	

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/15323

**Comment by sparkoo** [comment]
few questions here:
 - > Use parameter from this issue #17841 that is telling che that k8s namespaces are going to be pre-crated.

   The parameter is `che.infra.kubernetes.namespace.creation_allowed=true`. Does it mean if it is set to false, we should ignore all the current logic and search for labeled namespace? If not found exactly 1, error? This does not feel right, especially with how parameter is named. Next questions assume that `creation_allowed=false` does not shut off completely the current logic.
 - If there is labeled namespace, do we ignore the default namespace template completely? That would mean that the namespace strategy can be different for two users.
 - If there are namespace that matches the default namespace template AND labeled namespace. Which one to prefer?
 - What if there are namespace stored in user preferences AND labeled namespace. Which one to use?
 - What if we find more labeled namespace? Which one to use? Error?

To me it feels like labeled namespace should have highest priority, because it's intentionally manually created by the admins. So if we find it, ignore everything else. So the only question is what to do if there are more properly labeled workspaces.

**Comment by skabashnyuk** [comment]
>.the labeled namespace should have the highest priority because it's intentionally manually created by the admins. So if we find it, ignore everything else, if not, use current logic.

Sound good

>If so, I guess the only question is what to do if there are more properly labeled workspaces.

use the first one :)

**Comment by sparkoo** [comment]
closing with https://github.com/eclipse/che/pull/18090 https://github.com/eclipse/che-docs/pull/1643 merged
