### ISSUE TITLE
Add "Reload" button to the message panel from "GitHub authenticate".

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#17889]
### Is your enhancement related to a problem? Please describe.

There is no "Reload" button in the message panel generated  by the "GitHub authenticate" command.

![Screenshot 2020-09-15 at 09 09 55](https://user-images.githubusercontent.com/101795/93403853-988e5f80-f8c3-11ea-9238-38cf4b92d0b1.png)

They can reload by their browser's menu or keybind for now. But it's better to provide "Reload" button for their user experience.

### Describe the solution you'd like

"Reload" button is added. Like this.

![Screenshot 2020-09-17 at 08 52 26](https://user-images.githubusercontent.com/101795/93404065-2f5b1c00-f8c4-11ea-94ed-5bcf63982691.png)

It calls `navigator.window.reload(false)` inside. 

### Describe alternatives you've considered

Providing "Reload" menu. (Probably the sub-menu in "File" section.)

### Additional context

I've already implemented it on my PizzaFactory instance and tested by hand. I'm going to send PR.

**Comment by azatsarynnyy** [comment]
Nice UX improvement!

**Comment by vinokurig** [comment]
The vscode GitHub Pull Request plugin is going to be updated to the latest version: https://github.com/eclipse/che/issues/16741. In the latest version the authentication works through the authentication plugin API which is already introduced in theia: https://github.com/eclipse-theia/theia/pull/8402. It means that we will register our own GitHub authentication provider instead of injecting token to preferences so this notification will be removed.

I am OK to have it as a temporary improvement.

**Comment by monaka** [comment]
@vinokurig Thank you for the good news.
I keep this PR ass it will take a little time applying the authentication plugin API  to Che-Theia.

**Comment by monaka** [comment]
As #16741 was closed, this issue is deprecated. I close this.
