### ISSUE TITLE
chectl certificate path should be linked somehow to the install platform

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17920]
### Is your enhancement related to a problem? Please describe.
When installing Eclipse Che with chectl I've the message

` ✔ ❗[MANUAL ACTION REQUIRED] Please add Che self-signed CA certificate into your browser: /$HOME/cheCA.crt.`

but if I install che on minikube then on minishift, then on a remote server, I still have the same message and the public cert is written in the same file

### Describe the solution you'd like
- Prefix/Suffix to the file of the certificate with the host of che like `che-ca-192.168.64.24.nip.io.crt`
- If using minikube, storing it in `$HOME/.minkube/` , `$HOME/.minishift/` for minishift etc

### Describe alternatives you've considered
- a new random name every time I launch the install inside `/tmp` folder

**Comment by mmorhun** [comment]
I was thinking about this issue and come up with a thought that maybe we don't need the link to cluster in certificate file name. First, user can always export Che TLS certificate using `chectl cacert:export` command. Second, when user got exported certificate and added it into browser(s), the user doesn't need the certificate file any more and the file becomes a candidate for removal. Third (and very subjective), it is easier to add the cert into browser from the same file (as browser remembers previous location) many times while developing Che instead of picking it from a custom location. @benoitf WDYT?

**Comment by tolusha** [comment]
@mmorhun 
+1
