### ISSUE TITLE
Language Server Protocol: ShowMessage Request feature

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1794]
New: The show message request is sent from a server to a client to ask the client to display a particular message in the user interface. In addition to the show message notification the request allows to pass actions and to wait for an answer from the client.
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#showmessage-request

**Comment by slemeur** [comment]
This issue has been discussed with @xcoulon who wanted to work on it.

After studying the specification https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#showmessage-request we think that there is some missing parts in order for the IDE to properly handle the `MessageActionItem`.

The specification is mentioning certain actions: retry, show logs. This list of actions is not exhaustive and not normalized (meaning, all LS implementation are supposely able to send different type of actions).

In order to move forward, we have studied existing LS (for JDT + sourcegraph), but we have not found any use of this.

For the time being - in order to start the implementation this issue needs:
- more detailed specification
- samples
- actually be used in some LS

**Comment by slemeur** [comment]
Linked to question: https://github.com/Microsoft/language-server-protocol/issues/130

**Comment by tsmaeder** [comment]
I'm starting work on this.
