### ISSUE TITLE
Language Server Protocol: Document Highlights

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1802]
The document highlight request is sent from the client to the server to resolve a document highlights for a given text document position.
Changed:: in 2.0 the requests uses TextDocumentPositionParams with a proper textDocument and position property. In 1.0 the uri of the referenced text document was inlined into the params object.
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-highlights

**Comment by vparfonov** [comment]
A document highlight is a range inside a text document which deserves special attention. Usually a document highlight is visualized by changing  the background color of its range.

**Comment by xcoulon** [comment]
Looks like the link to the `Document Highlights` section (as it appears in the issue description) is broken. It could be replaced with: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-highlights-request

**Comment by xcoulon** [comment]
It seems like the current `io.typefox.lsapi.services` jar contains erroneous methods. For example: 
```
TextDocumentService {
  ...
  /**
    * The document highlight request is sent from the client to the server to to resolve a document highlights for a
    * given text document position.
    */
  def CompletableFuture<DocumentHighlight> documentHighlight(TextDocumentPositionParams position)
    ...
}
```

This method returns a single `DocumentHighlight` (ie, a single occurrence of a selected word to highlight in the editor), which is wrong. This was fixed in https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/services/TextDocumentService.java#L96

```
/**
  * The document highlight request is sent from the client to the server to
  * to resolve a document highlights for a given text document position.
  */
@JsonRequest
CompletableFuture<List<? extends DocumentHighlight>> documentHighlight(TextDocumentPositionParams position);
```
but Che 5.0.0 is not using the new lsp4j library yet. For the mean time, I can return the first occurence of text to highlight, but I think that Che would need to integrate the Lsp4j lib as soon as a release is published.

**Comment by gorkem** [comment]
@vparfonov @evidolob Can we close this now? Is there anything else that needs to be done?
