### ISSUE TITLE
OpenShift Pro Purchased, Che still redirects to "starter" / "trial" account.

### ISSUE THREAD

**Issue by Wisedemic** [eclipse-che/che#18036]
Hello!

Steps to reproduce:

Create a redhat account...

Deploy che to OpenShift via 'openshift.io' , using any 'free' account options and any stack of choice.

You'll now have a redhat OpenShift cluster with Che deployed.

If you purchase a subscription to OpenShift Pro (gives you 10 workspaces), and attempt to open the che dashboard... You are always redirected to the free account version. 

I'm unable to redeploy or delete che from OpenShift , and there for cannot use my Pro subscription with Che. 

Please correct me if I'm taking the wrong steps..

I tried the service. I liked it. I purchased pro, now I'm having an issue access che Pro. 

Thank you !

**Comment by sleshchenko** [comment]
cc @ibuziuk

**Comment by ibuziuk** [comment]
@Wisedemic hello, thank you for your interest in Hosted Che. Some questions inlined:

> Deploy che to OpenShift via 'openshift.io' , using any 'free' account options and any stack of choice.

you do not need to deploy Hosted Che on OpenShift , since it is already deployed and managed by Red Hat. Please, find the terms of service in the official documentation - https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/#terms-of-service_hosted-che

> If you purchase a subscription to OpenShift Pro (gives you 10 workspaces), and attempt to open the che dashboard... You are always redirected to the free account version.

Sorry, but I'm not sure where have you got this information. Could you please clarify? Hosted Che is free for everyone and we only support the free tier 

> I'm unable to redeploy or delete che from OpenShift , and there for cannot use my Pro subscription with Che.

There is no Pro subscription for Hosted Che. Could you please clarify where have you got this information?

**Comment by ibuziuk** [comment]
@Wisedemic hello, any updates? Can we help somehow?

**Comment by ibuziuk** [comment]
@Wisedemic closing, for now, feel free to reopen with extra details - we will be glad to help
