### ISSUE TITLE
Does Eclipse Che has plugins to support JUNIT and TestNG

### ISSUE THREAD

**Issue by AbhiAuto** [eclipse-che/che#18112]
Hi Team,

Please let us know whether Current Eclipse CHE version 17.8.2 version supports JUnit and TestNG.

Thanks,
Abhilash G

**Comment by ericwill** [comment]
We have [Java Test Runner](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) support in Che, which supports JUnit and TestNG. However it is part of Che `7.19`, not Che `7.18.x`

**Comment by benoitf** [comment]
hi @AbhiAuto are you sure about the che version ? 17.8.2 

When enabling `java plug-in` inside che you've the test runner https://github.com/Microsoft/vscode-java-test

**Comment by Manou80096** [comment]
Hi Team,

We are using the eclipse che version 7.20.0 and using vscode as editor but when i tried installing java test runner getting below error,
"Unable to install 'vscjava.vscode-java-test' extension because it is not compatible with the current version of VS Code (version 1.39.2)."

couldnt update the latest version of vscode as well.

Could you please let us know any solution available for above issue.

Thanks,
Mano

**Comment by ericwill** [comment]
> Hi Team,
> 
> We are using the eclipse che version 7.20.0 and using vscode as editor but when i tried installing java test runner getting below error,
> "Unable to install 'vscjava.vscode-java-test' extension because it is not compatible with the current version of VS Code (version 1.39.2)."
> 
> couldnt update the latest version of vscode as well.
> 
> Could you please let us know any solution available for above issue.
> 
> Thanks,
> Mano

How did you install the test runner? It should be part of the Java plugin available in Che -- no need to install it separately.

**Comment by Manou80096** [comment]
I'm using code-server(vscode) IDE as editor in my workspace and tried installing vscode extension of java-test-runner.

**Comment by ericwill** [comment]
The java test runner plugin has been in Che for awhile now, as part of the `redhat/java` plugin in the plugin registry.
