### ISSUE TITLE
Ws-agent has stopped in some case

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1817]
Steps to reproduce:
1. Import Che-project
2. Wait till resolving project
3. Open a java class
4. Run 'Maven/Reimport'
5. Open another java class
Actual result: ws-agent has stopped
![ws_agent_error](https://cloud.githubusercontent.com/assets/1636592/16914807/e46a4c74-4cfc-11e6-8bf5-da28e8c3aa57.png)

**Comment by bmicklea** [comment]
The client should check the status of ws-agent and print out a helpful message to let the user know that the memory has run out. Suggest that they add more memory to Che and try again.

Had been filed as CHE-14

**Comment by riuvshin** [comment]
This issue actual only with disabled swap for docker containers. On nightly we disabled swap to be able to reproduce and work on those issues, when ws agent is dead we should explain user what was happened, why and what to do.
So to summarize it is not actually blocker because we will keep beta with enabled swap until we will properly manage that failure.
@bmicklea @TylerJewell @vparfonov WDYT?

**Comment by vparfonov** [comment]
Workaround #2369
