### ISSUE TITLE
Login to Keycloak using API

### ISSUE THREAD

**Issue by chinukrish** [eclipse-che/che#18221]
I have an application: say Application1 without keycloak

I have integrated Eclipse Che into Application1.
Now what I want is, if I login to my Application1 (without keycloak), I should be able to call some API of keycloak to login to Eclipse Che (without rendering keycloak's login page).

Is this feasible? If yes, how?

Any help will be highly appreciated.

**Comment by tolusha** [comment]
@AndrienkoAleksandr 
Maybe you know answer.

**Comment by chinukrish** [comment]
@AndrienkoAleksandr Could you please help with your response.

**Comment by chinukrish** [comment]
@AndrienkoAleksandr Could you please help if you have a solution for this integration.

**Comment by AndrienkoAleksandr** [comment]
Hello. I guess your application after user login could login to the keycloak and retrieve token https://www.keycloak.org/docs/6.0/server_development/#example-using-curl , then you can create new user in the keycloak with this token. Then using this token you can make requests to the Che api or you can make redirection to the user dashboard with this token. User dashboard should not render login if valid token exists. I think some confusing thing could be if login session is expired since some time. User dashboard in this case will render login page. @akurinnoy what do you think can we change login page redirection when keycloak token is expired?

**Comment by chinukrish** [comment]
@AndrienkoAleksandr Thanks for your response!
So is it not necessary to have keycloak implementation in application1?
The following API can be used to get the access token
"http://localhost:8080/auth/realms/master/protocol/openid-connect/token"
Using this Token if I redirect to  the dashboard URL "https://<hostname>/dashboard/", the login page will be skipped?
Also, while redirecting to an URL, do we really require to set an access token. Its for an API call we set the access token.

Also I was checking if there is a way we can authenticate the eclipse che via any available API and then do the redirection to the required page within Eclipe Che.

**Comment by akurinnoy** [comment]
@AndrienkoAleksandr not sure I've completely got what you mean about changing login page redirection. Keycloak adapter checks token and either refreshes it if it's possible or redirects to keycloak's login page.

@chinukrish AFAIK if user is authenticated in Keycloak then UD is not supposed to redirect to login page. Unfortunately I can suggest nothing on how do you authenticate user.
