### ISSUE TITLE
[che-theia] Some asset files aren't zipped.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#18279]
### Describe the bug

I found an exeception on my original build version of che-theia.

```
promiseRejection in /home/theia/node_modules/universalify/index.js:9
  7       return new Promise((resolve, reject) => {
  8         arguments[arguments.length] = (err, res) => {
> 9           if (err) return reject(err)
 10           resolve(res)
 11         }
debug> exec("err")
{ errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/home/theia/lib/e817279537a0417d042f62fbb1b99eea.gif.gz',
  stack: "Error: ENOENT: no such file or directory, access '…heia/lib/e817279537a0417d042f62fbb1b99eea.gif.gz'",
  ... }
```

```
$ ls /home/theia/lib/e817279537a0417d042f62fbb1b99eea.*
/home/theia/lib/e817279537a0417d042f62fbb1b99eea.gif
```
GIF exists but no Gzipped available.
 
Probably the official `next` image have the same issue. (see "Step to reproduce" below)

### Che version

 - [] latest
 - [ ] nightly
 - [x] other: The original build from the master branch.

### Steps to reproduce

1. `docker run -it --entrypoint=/bin/sh quay.io/eclipse/che-theia:next`
2. `/home/theia/lib/*.gif` ---> exists.
3. `/home/theia/lib/*.gif.gz`  ---> not exists.

### Expected behavior

Zipped file should exist.

**Comment by davidfestal** [comment]
@monaka Could you please precise the command line that produced the error you quote in the issue description, and the complete stacktrace ?

In the `che-theia:next` docker image, the gzipped versions are omitted only for `.woff`, `.woff2` and `.gif` files, which all have a size < 100kb.

Additionally I checked in the `7.18.0` tag of `che-theia` docker image, and the gzip versions are omitted for the exact same files.

Knowing that the gzip versions are only there to optimize network communications for big files, it doesn't seem critical nor a high priority, so that I'll put it as P2.

cc @benoitf

**Comment by monaka** [comment]
I inspect a little bit deeper.
The rejection is happened but my browser gets `e817279537a0417d042f62fbb1b99eea.gif` (with no `.gz`)
I couldn't find the place but I think there may have the recovery code to get unzipped assets.

I close this. Thank you for the support.

p.s. additional logs on my build image is below.

```
promiseRejection in /home/theia/node_modules/universalify/index.js:9
  7       return new Promise((resolve, reject) => {
  8         arguments[arguments.length] = (err, res) => {
> 9           if (err) return reject(err)
 10           resolve(res)
 11         }
debug> exec('err')
{ errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/home/theia/lib/e817279537a0417d042f62fbb1b99eea.gif.gz',
  stack: "Error: ENOENT: no such file or directory, access '…heia/lib/e817279537a0417d042f62fbb1b99eea.gif.gz'",
  ... }
```

```
debug> backtrace
#0 arguments.<computed> /home/theia/node_modules/universalify/index.js:9:26
#1 (anonymous) fs.js:155:22
```
