### ISSUE TITLE
Android Studio as editor

### ISSUE THREAD

**Issue by Cryptolover248** [eclipse-che/che#18283]
### Is your enhancement related to a problem? Please describe.
Using eclipse che as development environment is hard without android studio 

### Describe the solution you'd like
Can we implement android studio as editor? If yes, does using emulator is possible?

**Comment by gattytto** [comment]
the [flutter extension](https://github.com/eclipse/che/issues/17731) has recently been added to che (if you go to the link you can see the process and some other details about the extension), its sidecar includes the android SDK and all the tools needed to dev android and web apps. As for running the emulator in che, there is an open issue around this subject, because this would require to have [nested virtualization](https://github.com/eclipse/che/issues/17761) enabled in the flutter sidecar.

for the specific case of "android studio" as editor in che, this would require there to be a "web" version of android studio so it can be added to che as editor, an example of a candidate like this one is [libreoffice](https://github.com/eclipse/che/issues/17730).

**Comment by Cryptolover248** [comment]
> the [flutter extension](https://github.com/eclipse/che/issues/17731) has recently been added to che (if you go to the link you can see the process and some other details about the extension), its sidecar includes the android SDK and all the tools needed to dev android and web apps. As for running the emulator in che, there is an open issue around this subject, because this would require to have [nested virtualization](https://github.com/eclipse/che/issues/17761) enabled in the flutter sidecar. Meanwhile you could run the emulator somewhere else and use adb to connect to it.
> 
> for the specific case of "android studio" as editor in che, this would require there to be a "web" version of android studio so it can be added to che as editor, an example of a candidate like this one is [libreoffice](https://github.com/eclipse/che/issues/17730).
> 
> I'm guessing you mean android studio as for the XML layout files preview and interactive design widget. That is not available as a vscode extension as of yet so that is only possible within android studio.

Thanks!! I'm just new into android development and my laptop can't run android studio, do you have any idea how to configure a stack or workspace specifically for android development? My primary language is java.

**Comment by vzhukovs** [comment]
Hi @Cryptolover248, theoretically it's possible to run. There are some work has been done according to IntelliJ Idea (Ultimate and Community Edition) and WebStorm [here](https://github.com/che-incubator/jetbrains-editor-images), with [developer-guide](https://github.com/che-incubator/jetbrains-editor-images/blob/master/doc/Developer-Guide.md). And now there are some work performs to make a base image which will allow run any application in desktop environment [here](https://github.com/che-incubator/custom-native-editor-base-image).

**Comment by azatsarynnyy** [comment]
Hello @Cryptolover248 
adding more IntelliJ-based editors, like Android Studio, etc. should be relatively easy now.
Please, follow the links @vzhukovs has provided above, for more details.

Here's what I've got by making some quick modification in https://github.com/che-incubator/jetbrains-editor-images

![image](https://user-images.githubusercontent.com/1636395/98141511-5fd83300-1ecf-11eb-9181-8ec92d08d95b.png)

You can test it by [this link.](https://che.openshift.io/f?url=https://gist.githubusercontent.com/azatsarynnyy/71451fb045ef8b6cc9d96db452ad2006/raw/b6bcf5eb7ff2ead092d8549ddef650209fb78876/devfile.yaml)

---

Note, it's just a quick PoC. So, it's not fully functional because of, for example:

![image](https://user-images.githubusercontent.com/1636395/98142333-58fdf000-1ed0-11eb-95d7-909b05d1a4a5.png)

---

Answering your original questions:
> Can we implement android studio as editor?

it's obviously possible :wink: 

If you're interested in investigating it and possibly providing a PR - we're happy to guide you in this direction.

> If yes, does using emulator is possible?

I'm not familiar with using emulators in Android Studio, but I suppose nothing can prevent do it :smile:

**Comment by gattytto** [comment]
this looks very nice, it'll be easy to add the required android sdk and emulator images to the editor but there's still the need of nested virtualization for the editor image if one wants to actually run the emulator inside the editor's environment, this is because the android sdk uses qemu to run the emulator images

**Comment by gattytto** [comment]
the quickest workaround is to run the emulator somewhere else and use "adb connect" to hook your editor's adb to a running emulator or even a real device.

**Comment by Cryptolover248** [comment]
> Hi @Cryptolover248, theoretically it's possible to run. There are some work has been done according to IntelliJ Idea (Ultimate and Community Edition) and WebStorm [here](https://github.com/che-incubator/jetbrains-editor-images), with [developer-guide](https://github.com/che-incubator/jetbrains-editor-images/blob/master/doc/Developer-Guide.md). And now there are some work performs to make a base image which will allow to run any application in desktop environment [here](https://github.com/che-incubator/custom-native-editor-base-image).

Thanks man! Gotta try it. 

> Hello @Cryptolover248
> adding more IntelliJ-based editors, like Android Studio, etc. should be relatively easy now.
> Please, follow the links @vzhukovs has provided above, for more details.
> 
> Here's what I've got by making some quick modification in https://github.com/che-incubator/jetbrains-editor-images
> 
> ![image](https://user-images.githubusercontent.com/1636395/98141511-5fd83300-1ecf-11eb-9181-8ec92d08d95b.png)
> 
> You can test it by [this link.](https://che.openshift.io/f?url=https://gist.githubusercontent.com/azatsarynnyy/71451fb045ef8b6cc9d96db452ad2006/raw/b6bcf5eb7ff2ead092d8549ddef650209fb78876/devfile.yaml)
> 
> Note, it's just a quick PoC. So, it's not fully functional because of, for example:
> 
> ![image](https://user-images.githubusercontent.com/1636395/98142333-58fdf000-1ed0-11eb-95d7-909b05d1a4a5.png)
> 
> Answering your original questions:
> 
> > Can we implement android studio as editor?
> 
> it's obviously possible 😉
> 
> If you're interested in investigating it and possibly providing a PR - we're happy to guide you in this direction.
> 
> > If yes, does using emulator is possible?
> 
> I'm not familiar with using emulators in Android Studio, but I suppose nothing can prevent do it 😄

Thanks!! I'll try that too

**Comment by Cryptolover248** [comment]
@vzhukovs, @azatsarynnyy, @gattytto I tried building apk files on Intellij Community Edition but it requires some packages that was not installed. Do you have any idea how to install it? I tried with apt but it requires root access. 
![Screenshot_20201105_063822](https://user-images.githubusercontent.com/73702737/98175631-ec1b4200-1f31-11eb-98f9-cbf64bd1871b.jpg)

**Comment by vzhukovs** [comment]
It is not allowed to install packages in runtime container. Because image is configured to run unders user not the root. To quickly fix this I can suggest to add `libsecret` library to install packages list here: https://github.com/che-incubator/jetbrains-editor-images/blob/master/Dockerfile#L28 and rebuild image for IntelliJ Idea Community Edition. This might help in this case.

**Comment by azatsarynnyy** [comment]
I believe this question is answered. If you don't think so, feel free to reopen it.
