### ISSUE TITLE
switch from ephemeral to persistant workspace lets the database beeing ephemeral

### ISSUE THREAD

**Issue by MaggusK** [eclipse-che/che#18322]
Not sure, if this is really a bug, or could be handled as enhancement.
This came out from discussion on: https://mattermost.eclipse.org/eclipse/channels/eclipse-che/kj1j3g5eap8dudpbfo5ceu3tyw

### Che version
20.7.1

### Expected behavior
If you, for excample, use a sample Devfile in a workspace and you switch from ephemeral mode to persistant mode, the Devfile should be automaticly edited, making the database also persistant. 

### Runtime
   - [x] Openshift (`oc version` ??)

### Environment
   - [ ] my computer
       - [x] Linux
   - [ ] Cloud
       - [x] Redhat openshift.io

@ericwill

**Comment by ibuziuk** [comment]
@ericwill looks like all the devfiles from the registry always use ephemeral db which is not persisted between restarts. I believe it would be a nice idea to update the devfiles with dbs to allow persistence by default e.g. - https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-mysql/devfile.yaml#L63

**Comment by ericwill** [comment]
> @ericwill looks like all the devfiles from the registry always use ephemeral db which is not persisted between restarts. I believe it would be a nice idea to update the devfiles with dbs to allow persistence by default e.g. - https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-mysql/devfile.yaml#L63

Thanks for the investigation, we'll look into it.

**Comment by vitaliy-guliy** [comment]
We merged a [PR](https://github.com/eclipse/che-devfile-registry/pull/308/files) that enables database persistence for some devfiles, that was tested on hosted Che.

There is some issues with [nodejs-mongo](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/nodejs-mongo/devfile.yaml) devfile. They are not related to database persistence, but to building the sample project.

The workspace that created from this devfile has persistent storage, which is attached as PVC.
With PVC we cannot build the node/typescript projects because of well known issues with permissions. It's the same problem that blocks us in developing of Che-Theia on hosted Che.

In case of ephemeral workspace, it become possible to build the sample, but the database is not persistent.
But to test the database persistence on persistent workspace, it's always possible to clone the sample to `/tmp`, which is not persistent, build and launch.
