### ISSUE TITLE
Is it possible to display graph in che?

### ISSUE THREAD

**Issue by michiboo** [eclipse-che/che#18331]
## Summary
Hi, I was trying to develop a python backend on che, and it would be really useful if I can display matplotlib plot in the IDE or in a popup. Would that be a possible future extension for che?

**Comment by mmorhun** [comment]
Hello @michahirsch. Could you please elaborate more on what you are implementing and want to accomplish?

**Comment by michiboo** [comment]
Basically I am trying to develop a flask application that send graph to the client side for display. It would be useful if che can display the graph after running plt.show()

**Comment by mmorhun** [comment]
@michahirsch in case of web application the graph should be displayed on client side, so you cannot do `plt.show()` as it would be run on server side. You need to send the graph (image) to client side and display it there. Please refer to [matplotlib docs](https://matplotlib.org/3.3.2/faq/howto_faq.html#how-to-use-matplotlib-in-a-web-application-server) how to do it.
When that is done, just open your web app in the preview window or a separate tab. In order to do so, you have to open corresponding port in advance (Che [docs](https://www.eclipse.org/che/docs/che-7/end-user-guide/making-a-workspace-portable-using-a-devfile/#endpoints_making-a-workspace-portable-using-a-devfile)). Alternatively, you may just start your application and the port plugin should ask you if you want to open the port.

**Comment by michiboo** [comment]
ok thank you for your advise. I will close this issue now
