### ISSUE TITLE
[che-operator] consider usage of quay.io/eclipse/che-postgres instead of centos/postgresql-96-centos7 image to work around pull limits

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18353]
### Is your enhancement related to a problem? Please describe.
We are often observing Eclipse Che installation error related to 100pulls/6hours dockerhub limitation:
```
08:25:16 [03:25:14] → Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "centos/postgresql-96-centos7:9.6".
08:25:16  ›   Error: Error: Failed to download image, reason: ImagePullBackOff, message:
08:25:16  ›    Back-off pulling image "centos/postgresql-96-centos7:9.6".
08:25:16  ›   Installation failed. Error log: /home/hudson/.cache/chectl/error.log. 
08:25:16  ›   Eclipse Che logs: /tmp/chectl-logs/1605169464360
```
centos/postgresql-96-centos7:9.6 image address hard coded in CSV files, for example, in https://github.com/eclipse/che-operator/blob/d27ddb008546b98ba0fd3318cb45058b0f88ac05/olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.21.1/eclipse-che-preview-kubernetes.v7.21.1.clusterserviceversion.yaml#L265

### Describe the solution you'd like
@nickboldt proposed to use https://quay.io/repository/eclipse/che-postgres instead of centos/postgresql-96-centos7:9.6.

We might do the same for mongodb, mysql, and others. 

### Additional context
Issue partly fixes https://github.com/eclipse/che/issues/18292

**Comment by nickboldt** [comment]
I don't know if https://quay.io/repository/eclipse/che-postgres is a drop-in replacement for centos/postgresql-96-centos7:9.6, so we'd need some validation from whoever's building (and from QE) it that it's safe to use instead. 

I also proposed that we could use the same image from the RHEC catalog instead, which would have the added bonus of being the same one in CRW and in Che, but the issue there is that registry.redhat.io requires authentication, so there'd be an extra hurdle to get over when building/deploying/using the **registry.redhat.io/rhel8/postgresql-96** image.

**Comment by tolusha** [comment]
For Eclipse Che we should not use any images from Red Hat registry.
To replace PostgresSQL image we have to be 200% sure we won't break anything after upgrading...

**Comment by tolusha** [comment]
BTW I don't see 7.9.6 tag there ^(

**Comment by skabashnyuk** [comment]
@nickboldt @dmytro-ndp I believe in this case it's important to clarify the goal. Do we want to migrate from dockerhub to quay.io  https://github.com/eclipse/che/issues/18292 or we want to have a new postgresql image for upstream.
I think  https://github.com/eclipse/che/issues/18292 way is much simpler. We just need to ensure `eclipse/che-postgres` is what we want. However, migration to another base `PostgreSQL` image is not that simple. Mainly because of backward compatibility and migration. And should be well tested before.  I would say better to do that after we introduce backup/restore abilities for the operator https://github.com/eclipse/che/issues/18043

**Comment by dmytro-ndp** [comment]
@skabashnyuk, @tolusha: I see you concerns, and would agree that the movement from **centos/postgresql-96-centos7:9.6** to quay.io/eclipse/che-postgres should bring the value for product as well, not just to tests. 
To address that point, it's needed to understand:
1) what is the propose of quay.io/eclipse/che-postgres ?
2) why Eclipse Che operator doesn't use quay.io/eclipse/che-postgres?
3) why are we releasing quay.io/eclipse/che-postgres regularly together with other Eclipse Che images?
![Screenshot from 2020-11-13 19-54-07](https://user-images.githubusercontent.com/1197777/99105134-ab36c380-25ea-11eb-94be-e213c7c6b989.png)

**Comment by tolusha** [comment]
@dmytro-ndp 
To be honest I don't know what is that ^(

/cc @benoitf

**Comment by benoitf** [comment]
https://github.com/eclipse/che/blob/master/dockerfiles/postgres/Dockerfile

**Comment by benoitf** [comment]
it was used by previous Eclipse Che installer (che-init, etc container images)

as suggested, we could just remove this docker folder from `che/dockerfiles` and copy `centos/postgresql-96-centos7:9.6` to `quay.io/eclipse/che-postgres`

**Comment by l0rd** [comment]
@skabashnyuk @nickboldt adding label `area/wsmaster` as that's a subtask of https://github.com/eclipse/che/issues/18292 that you have started to look at

**Comment by nickboldt** [comment]
> To address that point, it's needed to know what is the propose of quay.io/eclipse/che-postgres if Eclipse Che operator doesn't use it

and

> as suggested, we could just remove this docker folder from che/dockerfiles and copy centos/postgresql-96-centos7:9.6 to quay.io/eclipse/che-postgres

So... this? 

* https://github.com/eclipse/che/pull/18555
* https://github.com/eclipse/che-release/pull/11/files

Do we actually need to copy the docker.io/centos/postgresql-96-centos7:9.6 image to quay.io/eclipse/che-postgres ? 

Can we juse use https://quay.io/repository/eclipse/che--centos--postgresql-96-centos7?tab=tags ? 

Or are you suggesting you want a new step in the Che release process that will:

* with every release of Che 7.y.z, perform a skopeo copy of docker.io/centos/postgresql-96-centos7:9.6 image to quay.io/eclipse/che-postgres:7.7.z ? If so that's easy to implement, if we want a fresh tag every 3 weeks.

**Comment by nickboldt** [comment]
Sounds like we need to keep creating the che-postgres image:

https://github.com/eclipse/che-release/pull/11#issuecomment-746218552

So closing

**Comment by dmytro-ndp** [comment]
Eclipse Che is now using quay.io/eclipse/che--centos--postgresql-96-centos7:9.6-b681d78125361519180a6ac05242c296f8906c11eab7e207b5ca9a89b6344392 [1].

[1] https://github.com/eclipse/che-operator/blob/master/deploy/operator.yaml#L60
