### ISSUE TITLE
Adapt telemetry functionality in Che Theia to single-host

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18503]
### Is your task related to a problem? Please describe.
For telemetry purposes, Che Theia makes the requests to `/che/client-ip` service.
It should be adapted to single-host mode as the browser goes to the wrong service URL.

### Describe the solution you'd like
Make Che Theia going to the correct URL for `/che/client-ip` requests.

**Comment by azatsarynnyy** [comment]
Thanks @sleshchenko for reporting it.
@ibuziuk I'm not sure if it's a critical one for 7.23 or it can wait for 7.24?

**Comment by ibuziuk** [comment]
@azatsarynnyy yeah, I believe this is a fairly important one

**Comment by azatsarynnyy** [comment]
Thanks @ibuziuk. Then, we'll try to make it for 7.23

**Comment by ibuziuk** [comment]
@azatsarynnyy thanks, but could you please what exactly is broken? it is overall telemetry events or only the ip identification?

**Comment by azatsarynnyy** [comment]
@ibuziuk only the ip identification

**Comment by sleshchenko** [comment]
Good to see the draft for fix already in place.
It's really critical since it makes tab loading all available resources and Theia Webview seems does not work because of that
![Screenshot_20201208_130204](https://user-images.githubusercontent.com/5887312/101475943-acdb7900-3955-11eb-8990-8122c00f00ad.png)
