### ISSUE TITLE
Endpoints don't work in Quarkus workspaces

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#18512]
### Describe the bug

Predefined endpoints don't work in Quarkus workspaces

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Go to che.openshift.io and create Quarkus REST API workspace
2. Execute `Package` and `Start Development mode (Hot reload + debug)` commands
3. Try to click on `hello-greeting-endpoint` endpoint

### Expected behavior
New tab should be opened with the application

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![screenshot-che openshift io-2020 12 02-17_28_24](https://user-images.githubusercontent.com/1271546/100893971-9dc37980-34c4-11eb-965b-f1b2d9c531c4.png)
![screenshot-routej60zdvi5-vsvydenk-che 8a09 starter-us-east-2 openshiftapps com-2020 12 02-17_34_52](https://user-images.githubusercontent.com/1271546/100894047-b92e8480-34c4-11eb-9332-158a2be890e4.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] che.openshift.io
   - [ ] other: please specify

**Comment by l0rd** [comment]
It looks like the port plugin is asking if we want to expose the port even if it's already exposed cc @benoitf

**Comment by benoitf** [comment]
@l0rd 
port plugin is asking because the process is listening only on `::ffff:7f00:1` which is the loopback URL so it's not 'exposed' at all, it should listen on all interfaces '0.0.0.0' to be reached from the outside (without jwt proxy)

If I accept the redirect it's working
![image](https://user-images.githubusercontent.com/436777/101042217-361d3500-357d-11eb-8bab-ca73f05135ed.png)

So it's how quarkus is configured that is wrong there.
https://github.com/quarkusio/quarkus/commit/ac8b99c0d022e7e26eb18834e39282821933c31f

22 days ago it has been changed to not listen on all interfaces anymore

And Max didn't wanted that we use a specific commit of quarkus repository it's what is happening with breaking changes.


Adding `-Dquarkus.http.host=0.0.0.0` fixes the issue.
![image](https://user-images.githubusercontent.com/436777/101043379-8d6fd500-357e-11eb-91dd-1e9e0d6f0038.png)

![image](https://user-images.githubusercontent.com/436777/101043400-92cd1f80-357e-11eb-9a64-673b6aa88172.png)
