### ISSUE TITLE
Dashboard Next Add Make a wish, Documentation, FAQ, Community, About

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18567]
When the user clicks on the ‘?’ icon on the masthead,a menu is shown with the following options :
1. Make a wish-Opens the mail client where the user can make a request
2. Documentation-Opens the documentation in another browser tab
3. FAQ-Opens the FAQ section of documentation in another browser tab
4. Community-Takes the user to the https://www.eclipse.org/che/ site in another tab.
5. About- when the user clicks on About ,a modal with the information about Che is shown.

![image20](https://user-images.githubusercontent.com/5887312/101629491-1c229d00-3a2a-11eb-9610-b1a2b4d44304.png)

![image11](https://user-images.githubusercontent.com/5887312/101629475-162cbc00-3a2a-11eb-9bfe-1bf987968ef3.png)

**Comment by nickboldt** [comment]
@beaumorley WDYT about the fact that the project (and later the Product) appears 5 times in this screenshot? 

Should we reduce the duplication a little? 

Suggestions:
* remove the additional logotype from the About dialog, as it's already present in the top-left corner, and the icon is already present in the browser tab
* move the line "Eclipse Che Version  7.18.1" into the title line, as "Eclipse Che 7.18.1"
* do we really need a description ? 

![image](https://user-images.githubusercontent.com/227597/101664287-ac0c1b00-3a19-11eb-8a53-f504fda9c10e.png)

**Comment by beaumorley** [comment]
@nickboldt @sleshchenko  Agree there is a lot of redundancy in the about modal. I believe we created a recommendation for this in our Dashboard Next mockups. @parvathyvr can we provide a design for this?

**Comment by parvathyvr** [comment]
Hi @nickboldt @sleshchenko Here is the new proposal for the about modal.I have removed the title and description,but retained the Logo with the product name. Also modified the first line to say 'Version' instead of 'Eclipse Che Version'.
![Che-About Modal](https://user-images.githubusercontent.com/33114242/101801093-05686d00-3b34-11eb-81c2-37721f43633a.png)
We reached this new design after referring the PF ['About modal' design guidelines](https://www.patternfly.org/v4/components/about-modal/design-guidelines) and also after comparing how we currently show info in about modals in OCP and in [cloud.redhat.com](https://cloud.redhat.com/) portals. This new design matches how we show info in about modal in these other RH portals.
CC @beaumorley

**Comment by sleshchenko** [comment]
It should be fixed by https://github.com/che-incubator/che-dashboard-next/pull/97
![Screenshot_20201224_144758](https://user-images.githubusercontent.com/5887312/103089576-0bac1e00-45f7-11eb-941d-0d24851557c7.png)

@JPinkney Can we, does it make sense to add browser name as well?

**Comment by JPinkney** [comment]
Yeah, there shouldn't be an issue showing browser name

**Comment by sleshchenko** [comment]
It's fully fixed after https://github.com/che-incubator/che-dashboard-next/pull/101 is merged
