### ISSUE TITLE
Profile Che-Theia to determine the correct memory/cpu resources

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18565]
### Is your task related to a problem? Please describe.
When starting a Workspace, Che-Theia shows it’s in Offline mode.
Offline indicator is displayed for a short period of time, but it makes a bad UX.
Offline indicator means that Che-Theia backend didn’t respond to a ping request within the timeout.
Most likely, it’s because we don’t have the `memoryRequest`/`cpuLimit` specified for Che-Theia sidecar.

### Describe the solution you'd like
We need to profile Che-Theia to determine the correct `memoryRequest`/`cpuLimit` values to set for Che-Theia sidecar.

### Additional context
- docs on calculating Che resources requirements https://www.eclipse.org/che/docs/che-7/administration-guide/calculating-che-resource-requirements/
- `kubectl top` can be used for profiling a sidecar.
- See more details in https://github.com/eclipse/che/issues/18472#issuecomment-734872527 and https://github.com/eclipse/che-plugin-registry/pull/716

**Comment by azatsarynnyy** [comment]
After the detailed investigation, we figured out that Che-Theia's `Offline` mode is more related to the issues in Theia's connection status check mechanism rather than the requested/limited cluster resources.
So, the `Offline` mode issue will be fixed within a separate issue.

@vzhukovs please provide more details on your investigation results.

**Comment by vzhukovs** [comment]
Here are some investigations around memory and cpu configuration:

In all workspace configurations were used workspace based on [eclipse/che-devfile-registry/devfiles/java-mysql/devfile.yaml](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-mysql/devfile.yaml)

Metrics gathered from Prometheus & Grafana.
Che deployed on minikube v1.16.0 using hyperkit with CPUs=2, Memory=6000MB, Disk=20000MB.

**Measurement 1 (with default configuration):**
- Theia container
  - memoryLimit: 512m
  - memoryRequested: default
  - cpuLimit: default
  - cpuRequest: default

Here we can observe general resource usage for the whole workspace:
![screencapture-localhost-3000-d-85a562078cdf77779eaa1add43ccec1e-kubernetes-compute-resources-namespace-pods-2021-01-03-21_42_14](https://user-images.githubusercontent.com/1968177/103489142-f915be00-4e1a-11eb-978a-95897937019a.png)

Here we can observe resource usage for Theia container:
![screencapture-localhost-3000-d-6581e46e4e5c7ba40a07646395ef7b23-kubernetes-compute-resources-pod-2021-01-03-21_43_22](https://user-images.githubusercontent.com/1968177/103489146-fd41db80-4e1a-11eb-96eb-76e5471dead7.png)

At workspace startup we can see, that Theia sometimes goes into offline mode.


**Measurement 2:**
- Theia container
  - memoryLimit: 512m
  - memoryRequest: 512m
  - cpuLimit: default
  - cpuRequest: default

Here we can observe general resource usage for the whole workspace:
![screencapture-localhost-3000-d-85a562078cdf77779eaa1add43ccec1e-kubernetes-compute-resources-namespace-pods-2021-01-03-21_42_14](https://user-images.githubusercontent.com/1968177/103489281-172fee00-4e1c-11eb-8752-f78f22061487.png)

Here we can observe resource usage for Theia container:
![screencapture-localhost-3000-d-6581e46e4e5c7ba40a07646395ef7b23-kubernetes-compute-resources-pod-2021-01-03-21_43_22](https://user-images.githubusercontent.com/1968177/103489289-2c0c8180-4e1c-11eb-843d-7e7103cb4db8.png)

The same situation with the offline mode as in the first measurement. Memory request doesn't influence on web socket connection.


**Measurement 3:**
- Theia container
  - memoryLimit: 512m
  - memoryRequest: 512m
  - cpuLimit: 100m or 0.1 cpu
  - cpuRequest: default

Here we can observe resource usage for the whole workspace:
![screencapture-localhost-3000-d-85a562078cdf77779eaa1add43ccec1e-kubernetes-compute-resources-namespace-pods-2021-01-03-22_37_33](https://user-images.githubusercontent.com/1968177/103489426-27949880-4e1d-11eb-93e8-25c6f744a93e.png)
> General CPU Limit grew to 0.6 with the current configuration.

Here we can observe how Theia container throttles at workspace startup:
![screencapture-localhost-3000-d-6581e46e4e5c7ba40a07646395ef7b23-kubernetes-compute-resources-pod-2021-01-03-22_39_19](https://user-images.githubusercontent.com/1968177/103489463-5a3e9100-4e1d-11eb-9dc3-4733cd9292bb.png)

Theia starts really slow. Throttling influences on web socket connection by increasing the time on sending/receiving web socket messages through the channel, so we can get offline message more than usual.


**Measurement 4:**
- Theia container
  - memoryLimit: 512m
  - memoryRequest: 512m
  - cpuLimit: 500m or 0.5 cpu
  - cpuRequest: default

Here we can see, that setting up CPU Limit to 0.5 influences the Theia container:
![screencapture-localhost-3000-d-6581e46e4e5c7ba40a07646395ef7b23-kubernetes-compute-resources-pod-2021-01-03-23_11_21](https://user-images.githubusercontent.com/1968177/103489569-29ab2700-4e1e-11eb-88cc-e1a94f25c633.png)
> This also influences on web socket connection. Web socket channel becomes really slow with this configuration.


**Measurement 5:**
- Theia container
  - memoryLimit: 512m
  - memoryRequest: 512m
  - cpuLimit: 500m or 0.5cpu
  - cpuRequest: 500m or 0.5cpu

The same situation with throttling as we have in **Measurement 4**:
![screencapture-localhost-3000-d-6581e46e4e5c7ba40a07646395ef7b23-kubernetes-compute-resources-pod-2021-01-03-23_03_03](https://user-images.githubusercontent.com/1968177/103489682-ca99e200-4e1e-11eb-9df8-f56525113a6a.png)


**Measurement 6:**
- Theia container
  - memoryLimit: 512m
  - memoryRequest: 512m
  - cpuLimit: 900m or 0.9cpu
  - cpuRequest: default

Workspace wasn't started with such configuration. Got error:
```
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedScheduling', '0/1 nodes are available: 1 Insufficient cpu.', 'workspaceb907x975ac3h2bmz.workspace-7b9654c89c-xqmz8'"
```

----
During the measurement the ping request was measured.
Here are some values for the ping requests when Theia went to offline mode at workspace start up.

- **Measurement 1**
  - 1553ms
  - 1882ms
  - 1040ms
- **Measurement 2**
  - 1616ms
  - 1791ms
- **Measurement 3**
  - 2101ms
  - 1904ms
  - 6695ms
  - 4301ms
  - 4848ms
  - 7910ms
  - 4463ms
  - 2057ms
- **Measurement 4**
  - 1122ms
  - 3694ms
  - 2887ms
  - 2674ms
  - 1906ms
- **Measurement 5**
  - 2101ms
  - 1904ms
  - 6695ms
  - 4301ms
  - 4848ms
  - 7910ms
  - 4463ms
  - 2057ms

As we can see, tuning `cpuLimit` property doesn't get proper effect on ping service.

Digging into connection status service revealed the following problem. There is a [web socket activity handler](https://github.com/eclipse-theia/theia/blob/deb57187a120d4c631f5542e6f0affda85c12f2b/packages/core/src/browser/connection-status-service.ts#L150-L154) which [sets up a timer](https://github.com/eclipse-theia/theia/blob/deb57187a120d4c631f5542e6f0affda85c12f2b/packages/core/src/browser/connection-status-service.ts#L161-L172) [1]. When first message comes in the channel function after 4 second calls the ping and if ping successful, connection status server [sets up another timer](https://github.com/eclipse-theia/theia/blob/deb57187a120d4c631f5542e6f0affda85c12f2b/packages/core/src/browser/connection-status-service.ts#L118-L121) [2] for 5 second to trigger connection to offline. In the meantime we receive another web socket message and connection status sets up timer for another ping request and this ping request might be slow (over 1 second). During this one second timer [2] triggers and Theia goes to offline mode. After that we finally receive response from second iteration from timer [1] and Theia immediately switches to online mode. 

So the problem is in two timers that doesn't track activity for promise.

This issue can be reproduced on vanilla Theia when user tries to open large file in the editor (> 5-7mb, it depends on user's host). In this case websocket channel is busy by transmitting the file content and ping service can't operate well.

----
There are two possible solutions:
1. Increase offlineTimeout parameter from default 5 second to 7-8 second. This requires creating extension of [ConnectionStatusOptions](https://github.com/eclipse-theia/theia/blob/deb57187a120d4c631f5542e6f0affda85c12f2b/packages/core/src/browser/connection-status-service.ts#L60-L71) class and bind it in DI container.
2. Refactor [AbstractConnectionStatusService](https://github.com/eclipse-theia/theia/blob/deb57187a120d4c631f5542e6f0affda85c12f2b/packages/core/src/browser/connection-status-service.ts#L79) by taking into account promise that ping service produces each time when ping is performed.

**Comment by azatsarynnyy** [comment]
Thank you @vzhukovs for the great benchmarking!

So, setting cpuLimit to any of 100m, 500m, or 900m slows down Che-Theia significantly.
But it seems it worked well with 1500m, in @l0rd's tests here https://github.com/eclipse/che/issues/18472 (see the issue description).
@vzhukovs does it make sense to check it on minikube as well?
To determine the correct request/limit values we can set in the plugin registry.

**Comment by azatsarynnyy** [comment]
As we've figured out, Offline mode issue cannot be fixed by tuning the cpu/mem resources,
@vzhukovs could you please register a separate issue in upstream Theia regarding an offline timeout?
Since it's reproduced upstream as well.

---
> Increase offlineTimeout parameter from default 5 second to 7-8 second. This requires creating extension of ConnectionStatusOptions class and bind it in DI container.

I believe a better option would be to introduce Theia configuration parameter upstream and just set it in Che-Theia, e.g. [here](https://github.com/eclipse/che-theia/blob/4d30e359c4d1bd39b52c12dbf747f6d6deb86ff6/generator/src/templates/assembly-package.mst#L7). It would give us more flexibility.
This is fair enough taking into account the current connection status check method in Theia really depends on the infrastructure/environment the real application is running on.

**Comment by vzhukovs** [comment]
>@vzhukovs does it make sense to check it on minikube as well?

On minikube this configuration doesn't work:
![Eclipse Che | java-mysql-8-j4rzn 2021-01-04 16-25-43](https://user-images.githubusercontent.com/1968177/103545040-ad5e2580-4ea9-11eb-8792-5b2ec244860c.jpg)

**Comment by vzhukovs** [comment]
>@vzhukovs could you please register a separate issue in upstream Theia regarding an offline timeout?

I've created a linked issue for this problem: https://github.com/eclipse/che/issues/18723

**Comment by l0rd** [comment]
What I observe is that:

1. In your test you haven't been able to find good CPU request/limit values because you always get some CPU throttling. Good values for CPU request and CPU limit would be the minimum values that guarantee no throttling.
2. You are specifying CPU limit but not CPU request and in this case Kubernetes automatically assigns a CPU request that matches the limit. On "measurement 6" for example you could try setting a CPU request to 0.5 and CPU limit to 1.
3. The error you get in measurement 6 is due to a CPU request higher than the CPU available in minikube. To verify what's going on here you should get the real CPU request and CPU limit that set for every container of the workspace pod. Besides Theia, other container may request a CPU value that is exhagerated and that we can lower down. I was using this snippet to get those values at workspace startup:
```bash
kubectl get po -l 'che.original_name=workspace' -o json -w |
   jq -r 'if .spec then .spec.containers[] |
             "---", .name, .resources.requests.cpu,  .resources.limits.cpu
          else "no pod yet" end'
```

**Comment by vzhukovs** [comment]
>You are specifying CPU limit but not CPU request and in this case Kubernetes automatically assigns a CPU request that matches the limit. On "measurement 6" for example you could try setting a CPU request to 0.5 and CPU limit to 1.

I've tried to apply different configurations to Theia container with mixed outcomes:

1. cpuLimit: 1, cpuRequest: 0.1
![cpuLimit-1-cpuRequest-0 1](https://user-images.githubusercontent.com/1968177/104103414-aae53c80-52aa-11eb-8fa5-c089a8f52e67.png)
CPU throttling around 70%

2. cpuLimit: 1, cpuRequest: 0.3
![cpuLimit-1-cpuRequest-0 3](https://user-images.githubusercontent.com/1968177/104103454-de27cb80-52aa-11eb-8540-3e87576cbe5c.png)
CPU throttling around 60%

3. cpuLimit: 1, cpuRequest: 0.5
![cpuLimit-1-cpuRequest-0 5](https://user-images.githubusercontent.com/1968177/104103497-1a5b2c00-52ab-11eb-8074-db44677d1d4e.png)
CPU throttling around 75%

4. cpuLimit: 1, cpuRequest: 0.7
![cpuLimit-1-cpuRequest-0 7](https://user-images.githubusercontent.com/1968177/104103515-352da080-52ab-11eb-8bb5-a82514a14b44.png)
CPU throttling around 75%

5. cpuLimit: 1.5, cpuRequest: 0.75
![cpuLimit-1 5-cpuRequest-0 75](https://user-images.githubusercontent.com/1968177/104103542-4ecee800-52ab-11eb-8f73-b97d928197f1.png)
CPU throttling is minimal, around 7-10%

But visually, setting up the cpuLimit to 1.5 causes to the case, that it somehow influences to the web socket communication and Theia continues to show offline mode. We can setup by default cpuLimit to **1.5** and cpuRequest to **0.5-0.75**, but this won't get proper feedback on web socket communication channel. Communication status checker mechanism should be reviewed in upstream.

Setting cpuLimit or cpuRequest more than 2 I suppose won't be a good idea, because usually Che is starting on default minikube configuration (if developer starts it on host machine) and default configuration tries to allocate cpuLimit to 2 for the whole local cluster. This might be also somehow related with the amount of physical cores, but not sure about it.

>To verify what's going on here you should get the real CPU request and CPU limit that set for every container of the workspace pod.

I tried the provided command and I saw no difference in output from this command and what grafana shows on charts in realtime.

**Comment by l0rd** [comment]
@vzhukovs what's your conclusion? What are the CPU request and limit values for Che Theia?

**Comment by vzhukovs** [comment]
@l0rd sorry, for the late response. From what I've got, using the local installation and che.openshift.io, configuration with `cpuLimit: 1500m` and `cpuRequest: 500m` would be enough to have a comfortable work. There was the smallest throttling that was able to get with this configuration. I'll contact @vitaliy-guliy to decide who will update the limits on Theia container, because there is a [parallel issue](https://github.com/eclipse/che/issues/16685) for that.

**Comment by azatsarynnyy** [comment]
@vzhukovs please provide a PR for setting the resources for Che-Theia based on your investigations within this issue.
Vitalii works on all the other Plug-ins except Che-Theia.

**Comment by azatsarynnyy** [comment]
The `cpuRequest` and `cpuLimit` are set by https://github.com/eclipse/che-plugin-registry/pull/796. It makes the situation with Che-Theia Offline mode a bit better but to fix it completely we'll continue working on https://github.com/eclipse/che/issues/18723.
