### ISSUE TITLE
Panels are collapsed in Che-Theia in a brand new workspace, after refreshing the page

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18564]
### Describe the bug
After refreshing the browser's page all panels are collapsed in Che-Theia.
I’m not able to reproduce it with upstream Theia. But it stable reproducible on che.openshift.io.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Spin up a Workspace from the following Defile:
```yaml
apiVersion: 1.0.0
metadata:
 name: java-gradle-1usq7
attributes:
 persistVolumes: 'false'
projects:
 - name: console-java-simple
   source:
     location: 'https://github.com/che-samples/console-java-simple.git'
     type: git
     branch: master
```
2. Refresh the page.

All panels are collapsed.

### Expected behavior
All panels must keep the same state as it was before reloading the page.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/1636395/101593233-4c514800-39f8-11eb-8cc9-77eae9e1bcdf.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] che.openshift.io

**Comment by azatsarynnyy** [comment]
It's interesting that it is reproduced on Hosted Che but not on the dogfooding instance.
Both have the same Che version - 7.24.2.

**Comment by azatsarynnyy** [comment]
Another interesting finding is that views of the `Explorer` view-container are collapsed starting from Che-Theia 7.22.0.
In Che-Theia 7.21.2, the bug is reproducible with the `Debug` view-container, but not with the `Explorer`.

**Comment by azatsarynnyy** [comment]
This commit from upstream https://github.com/eclipse-theia/theia/pull/8680/files
was merged on Nov 17, 2020.
Che-Theia 7.22.0 was released on Nov 18, 2020.

Since the mentioned Theia commit touches the shell layout code and it has been included in 7.22,
I suppose it may be related.

**Comment by vzhukovs** [comment]
Have some results based on the recent investigation. 
There are some existed problems described below:

**Problem 1.**
Current implementation of [LayoutChangeListener](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-frontend-contribution.ts#L22) has four subscriptions for [onDidAddWidget](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-frontend-contribution.ts#L37), [onDidRemoveWidget](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-frontend-contribution.ts#L38), [onDidChangeActiveWidget](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-frontend-contribution.ts#L39), [onDidChangeCurrentWidget](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-frontend-contribution.ts#L40), which schedule the timer [to persist application layout state](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-frontend-contribution.ts#L49). 

This approach has some limitations:

- developer or automated end-to-end tests have to wait particular period of time provided in `workbench.layout.saveTimeout` preference to trigger layout persistence. This can cause the problem, that some changes can be applied to the UI and page is immediately refreshed before triggering layout persistence. As an expected result, layout is not restored properly.

- this approach does not tracked cursor position in opened editor, so the changing cursor position in the editor will not affect on persistence state.

This can be fixed by subscribing to different types of user activity, for example to listen to the websocket activity e.g. [onIncomingMessageActivity](https://github.com/eclipse-theia/theia/blob/master/packages/core/src/browser/connection-status-service.ts#L150-L154). As an alternative, there can be a subscription only for keyboard and mouse activity.
This obviously can trigger a big amount of persistent layout requests, but there can be implemented some caching mechanism on the client side to prevent sequentially saving the same layout state to the server side.

Intermediate level for file persistence provided by [StorageServer](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-user-preferences/src/common/storage-server.ts#L13-L16) is redundant because it can be implemented via FileService on the client side.

**Problem 2.**

Frontend application has [a subscription](https://github.com/eclipse-theia/theia/blob/master/packages/core/src/browser/frontend-application.ts#L189-L193) to unload browser window event. It [calls under the hood](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/shell/shell-layout-restorer.ts#L153) layout persistence. 

So we have the following flow:

- Actor opens the Theia
- Theia tries to persist layout state
- Actor perform page reloading
- Theia tries to persist layout state [1]
- Browser window reloads

On step [1] we have another situation. As we can not control Theia and DOM on this step we have an unexpected behavior related to the Phosphor widgets and its positioning inside the DOM. [ShellLayoutRestorer](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/shell/shell-layout-restorer.ts#L119) performs persistence of layout by calling the chain of methods [storeLayout](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/shell/shell-layout-restorer.ts#L147) > [deflate](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/shell/shell-layout-restorer.ts#L186) > [convertToDescription](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/shell/shell-layout-restorer.ts#L205) > [storeState](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/shell/shell-layout-restorer.ts#L37) which is handled by [ViewContainer](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/view-container.ts#L354). [ViewContainer](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/view-container.ts#L354) by calling [containerLayout](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/view-container.ts#L336) getter tries [to calculate available size](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/view-container.ts#L1132) for rendered widgets in the DOM. In this case property [this.parent.node.offsetHeight](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/view-container.ts#L1142) returns a zero value. 

Below provided two logs from debugging application:

<details>
  <summary>log from regular layout persistence scheduled by the timer</summary>

  ```
bundle.js:31 root INFO $$$ doStoreState for view container started.
bundle.js:31 root INFO $$$ parts count: 3
bundle.js:31 root INFO $$$ getAvailableSize(): visiblePartCount: 2
bundle.js:31 root INFO $$$ getAvailableSize(): 2: availableSize: 464
bundle.js:31 root INFO $$$ getAvailableSize(): 2: this.parent.node.offsetHeight: 464
bundle.js:31 root INFO $$$ getAvailableSize(): 3: availableSize: 420
bundle.js:31 root INFO $$$ getAvailableSize(): 3: this.options.headerSize: 22
bundle.js:31 root INFO $$$ getAvailableSize(): 4: availableSize: 418
bundle.js:31 root INFO $$$ getAvailableSize(): final value for availableSize: 418
bundle.js:31 root INFO $$$ availableSize: 418
bundle.js:31 root INFO $$$ orientation: vertical
bundle.js:31 root INFO $$$ part id: {"factoryId":"files"}, size: 440
bundle.js:31 root INFO $$$ part id: {"factoryId":"files"}, collapsed: false, hidden: false
bundle.js:31 root INFO $$$ calculated size: 418, availableSize: 418, relSize: 1
bundle.js:31 root INFO $$$ part id: {"factoryId":"plugin-view","options":{"id":"plugin-view:npm","viewId":"npm"}}, size: undefined
bundle.js:31 root INFO $$$ part id: {"factoryId":"plugin-view","options":{"id":"plugin-view:npm","viewId":"npm"}}, collapsed: true, hidden: true
bundle.js:31 root INFO $$$ calculated size: undefined, availableSize: 418, relSize: undefined
bundle.js:31 root INFO $$$ part id: {"factoryId":"timeline-view"}, size: undefined
bundle.js:31 root INFO $$$ part id: {"factoryId":"timeline-view"}, collapsed: true, hidden: false
bundle.js:31 root INFO $$$ calculated size: undefined, availableSize: 418, relSize: undefined
bundle.js:31 root INFO $$$ doStoreState for view container ended.
```
</details>
<details>
  <summary>log from layout persistence which called right before page reload</summary>
  
```
bundle.js:31 root INFO $$$ doStoreState for view container started.
bundle.js:31 root INFO $$$ parts count: 3
bundle.js:31 root INFO $$$ getAvailableSize(): visiblePartCount: 2
bundle.js:31 root INFO $$$ getAvailableSize(): 2: availableSize: 0       <<<<
bundle.js:31 root INFO $$$ getAvailableSize(): 2: this.parent.node.offsetHeight: 0       <<<<
bundle.js:31 root INFO $$$ getAvailableSize(): 3: availableSize: -44       <<<<
bundle.js:31 root INFO $$$ getAvailableSize(): 3: this.options.headerSize: 22       <<<<
bundle.js:31 root INFO $$$ getAvailableSize(): 4: availableSize: -46       <<<<
bundle.js:31 root INFO $$$ getAvailableSize() availableSize < 0       <<<<
bundle.js:31 root INFO $$$ availableSize: 0
bundle.js:31 root INFO $$$ orientation: vertical
bundle.js:31 root INFO $$$ part id: {"factoryId":"files"}, size: 0
bundle.js:31 root INFO $$$ part id: {"factoryId":"files"}, collapsed: false, hidden: false
bundle.js:31 root INFO $$$ calculated size: 0, availableSize: 0, relSize: undefined
bundle.js:31 root INFO $$$ part id: {"factoryId":"plugin-view","options":{"id":"plugin-view:npm","viewId":"npm"}}, size: undefined
bundle.js:31 root INFO $$$ part id: {"factoryId":"plugin-view","options":{"id":"plugin-view:npm","viewId":"npm"}}, collapsed: true, hidden: true
bundle.js:31 root INFO $$$ calculated size: undefined, availableSize: 0, relSize: undefined
bundle.js:31 root INFO $$$ part id: {"factoryId":"timeline-view"}, size: undefined
bundle.js:31 root INFO $$$ part id: {"factoryId":"timeline-view"}, collapsed: true, hidden: false
bundle.js:31 root INFO $$$ calculated size: undefined, availableSize: 0, relSize: undefined
bundle.js:31 root INFO $$$ doStoreState for view container ended.

```
</details>

This case reproduces only on OSIO. It can not be reproduced on vanilla Theia, Dogfooding environment and minikube installation. 

But from the other hand Che-Theia's [implementation](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-service.ts#L19-L54) of [StorageService](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/storage-service.ts#L27-L39) operates with websocket connection and right before page reload websocket message might be not sent to the server because channel might be closed early.

This can be fixed by adding to the [CheStorageService](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-service.ts#L19-L54) additional checks whether is [FrontendApplicationStateService](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/frontend-application-state.ts#L31) does not have [closing_window](https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/core/src/browser/frontend-application-state.ts#L28) state at this moment.

**Comment by azatsarynnyy** [comment]
The issue is still reproducing. See the screencast:

![gradle](https://user-images.githubusercontent.com/1636395/107466681-23227480-6b6d-11eb-9cce-adc9853ae59c.gif)

I've used the following Devfile:
```yaml
apiVersion: 1.0.0
metadata:
  name: java-gradle-1usq7
attributes:
  persistVolumes: 'false'
projects:
  - name: console-java-simple
    source:
      location: 'https://github.com/che-samples/console-java-simple.git'
      type: git
      branch: master
components:
  - id: eclipse/che-theia/next
    type: cheEditor
    alias: theia-editor

```

**Note**, it's reproducing with a brand new workspace only.

**Comment by vzhukovs** [comment]
> ```yaml
> apiVersion: 1.0.0
> metadata:
>   name: java-gradle-1usq7
> attributes:
>   persistVolumes: 'false'
> projects:
>   - name: console-java-simple
>     source:
>       location: 'https://github.com/che-samples/console-java-simple.git'
>       type: git
>       branch: master
> components:
>   - id: eclipse/che-theia/next
>     type: cheEditor
>     alias: theia-editor
> ```

This use case (with debugger views) reproduces using vanilla Theia also:
![debugger](https://user-images.githubusercontent.com/1968177/107506795-4cf88d00-6ba7-11eb-936c-c49802a634b7.gif)

**Comment by azatsarynnyy** [comment]
Thank you @vzhukovs for checking that!
Closing this as it's just a default state of the `Debug` view container.
