### ISSUE TITLE
Multi Arch support for automatic devfiles images published on quay.io

### ISSUE THREAD

**Issue by prietyc123** [eclipse-che/che#18610]
### Is your enhancement related to a problem? Please describe.
I want multiarch build to be available in quay registry. Recently I was trying to execute `quay.io/eclipse/che-java11-maven:nightly
` on `s390x` but unfortunately, it seems only to be working with `x86_64` arch

### Describe the solution you'd like
Multiarch build should be supported in quay registry.

**Comment by tsmaeder** [comment]
@prietyc123 not quite sure what you're asking for: would you like to be a container image for che-java11-maven:nightly to be available for the s390 architecture on quay.io/eclipse/ ?

**Comment by benoitf** [comment]
@prietyc123 Hello, quay.io/eclipse/che-java11-maven is based from docker.io/maven:3.6.3-jdk-11 [1]
but this image is only available for amd64 and arm64 so I think it would need to pick up first a maven image being available on more multi-arch (like `3.6.3-adoptopenjdk-11` or `3.6.3-jdk-11-openj9`) and make the copy being multi-arch as well (for now it's using a single arch in the script [3] instead of docker buildx


[1] https://github.com/eclipse/che-devfile-registry/blob/master/arbitrary-users-patch/base_images#L8 

[2] https://hub.docker.com/layers/maven/library/maven/3.6.3-jdk-11/images/sha256-91106ec848713e12f79352a2572f5b74c2cddecef66f795bb306ad8e5635c79f?context=explore

[3] https://github.com/eclipse/che-devfile-registry/blob/master/arbitrary-users-patch/build_images.sh#L35

**Comment by sarveshtamba** [comment]
@prietyc123 we will need multi arch images for ppc64le too.

**Comment by tsmaeder** [comment]
Removed area "devfile-registry": supporting multiple archs goes way beyond that.

**Comment by benoitf** [comment]
we're already moving to multi arch across all repositories so let's keep label as it's related to the devfile area on this case.
