### ISSUE TITLE
[Spike] Intro in Multi cluster support

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18711]
### Is your task related to a problem? Please describe.
This epic https://github.com/eclipse/che/issues/18617 looks quite big.

### Describe the solution you'd like
We need  to take some time to 
 - clarify the scope 
 - make the initial study 
 - Discuss with the stakeholders implementation plan.

### Describe alternatives you've considered
n/a

### Additional context
https://github.com/eclipse/che/issues/18617

**Comment by sparkoo** [comment]
I've managed to prepare working POC (proof of concept) with using 2 OpenShift 4 Clusters as 2 different identity providers managed by keycloak. This diagram describes how it works on high level:
![Untitled Diagram](https://user-images.githubusercontent.com/1160903/104915941-a77c4000-5991-11eb-868b-b4e214ca2d88.png)



#### For this setup to work, several steps are needed:
 - add 2 OpenShift identity providers into the keycloak
 - setup OAuthClients on all the clusters
 - add tls certs of all used clusters into Keycloak's Java keystore
 - include identity provider in jwt token
 - update Che logic creating OpenShift Client to connect to correct cluster
#### Open questions
 - We'd like to get rid of user manually choosing the cluster to use. It should be possible to introduce some logic by asking user for username/email first, then some service will decide to what cluster to redirect to authenticate the user. I didn't find any support for something like this in keycloak.

### 2 OpenShift Identity providers in Keycloak
It is not possible to do this in UI, because it won't allow to add 2 Identity Providers of same type. The option simply dissapears from dropdown list, when OpenShift 4 IDP is already there.

There are 2 ways how to workaround this. Use Admin REST API or Import. I've used import with this template:
```
{
  "identityProviders": [
    {
      "alias": "<cluster-alias>",
      "providerId": "openshift-v4",
      "enabled": false,
      "updateProfileFirstLoginMode": "on",
      "trustEmail": false,
      "storeToken": true,
      "addReadTokenRoleOnCreate": true,
      "authenticateByDefault": false,
      "linkOnly": false,
      "firstBrokerLoginFlowAlias": "first broker login",
      "config": {
        "hideOnLoginPage": "",
        "baseUrl": "<cluster-url>",
        "clientId": "<cluster-client-name>",
        "disableUserInfo": "",
        "clientSecret": "<cluster-client-secret>",
        "defaultScope": "user:full",
        "useJwksUrl": "true"
      }
    }
  ]
}
```
where `<cluster-alias>` is the name this IDP will be referenced with, `<cluster-url>` is API url of the OpenShift cluster, `<cluster-client-name>` is the name of `OAuthClient` object configured in the cluster and `<cluster-client-secret>` is the secret configured in `OAuthClient`.

Like this, you can add as many OpenShift IDPs as you wish, they only have to differ with `alias`.


### Setup OAuthClients on the clusters
All clusters must have setup OAuthClient and it must match with IDP configuration in the Keycloak. It looks like this:
```
apiVersion: oauth.openshift.io/v1
grantMethod: prompt
kind: OAuthClient
metadata:
  labels:
    app: che
  name: eclipse-che-openshift-identity-provider-pg70sd
redirectURIs:
- <redirect-url>
secret: <secret>
```
where `<redirect-url>` is taken from keycloak IDP configuration and `<secret>` is some secret string that must match `clientSecret` in the Keycloak IDP configuration.


### Add tls certs of all used clusters into Keycloak's Java keystore
Currently in Che, the cluster tls cert is stored as a secret, then included in Keycloak pod as environment variable and imported into Java keystore in the container arguments, which is one nasty long chained command generated in che-operator (https://github.com/eclipse/che-operator/blob/master/pkg/deploy/identity-provider/deployment_keycloak.go) which looks something like this:
![20210118_131638_1659x971_scrot](https://user-images.githubusercontent.com/1160903/104915991-b9f67980-5991-11eb-88ca-961c8f4f1d95.png)


For POC I've only added second secret and deciphered the entrypoint of the deployment and included 2nd certificate there so it's imported.


### Include identity provider in jwt token
Che needs to know what cluster it should forward the request. For that I've included identity provider into the JWT token. It is then `identity_provider` field in the token which holds the `alias` value of the IDP. It's configured in Keycloak by simple client mapper:
![20210118_132232_812x528_scrot](https://user-images.githubusercontent.com/1160903/104916010-c11d8780-5991-11eb-94b6-f7039afaeb6b.png)


### Update Che logic creating OpenShift Client to connect to correct cluster
Che can grab the `identity_provider` and decide against which cluster it should create client. Currently Che uses 2 configuration values `master_url` and `che.infra.openshift.oauth_identity_provider`, which needs to be dynamic. We get the `oauth_identity_provider` from the token. We can then use this as a key to either some configured map of `idp` => `cluster_url`, or somehow automatically resolve this by asking keycloak.

**Comment by sparkoo** [comment]
The feature of automatically choosing the IDP for user is not baked in the Keycloak. However, it is possible to extend the Keycloak to have this functionality. 
See mail-list thread https://groups.google.com/g/keycloak-user/c/vRNnueuOCrQ
The example of such extension https://github.com/thomasdarimont/keycloak-extension-playground/tree/master/auth-dynamic-idp-redirector-extension
