### ISSUE TITLE
Enable multiarch builds for che-devfile-registry

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18943]
### Is your task related to a problem? Please describe.

As discovered in https://issues.redhat.com/browse/CRW-1475 the che registries are still publishing as single-arch amd64 images. We need ppc64le and s390x, too.

### Describe the solution you'd like

Borrowing code from:
* https://github.com/eclipse/che-plugin-registry/blob/master/.ci/sidecar-build-publish.sh#L28-L35 and 
* https://github.com/eclipse/che-plugin-registry/blob/master/.github/workflows/sidecar-build-push.yaml#L35-L48

we can enable buildx builds for the registry for both nightly and release, allowing it to be easier to test Che on other arches.

**Comment by aditijadhav38** [comment]
@nickboldt We had raised [PR](https://github.com/eclipse/che-devfile-registry/pull/321) and it was merged for adding multiarch support using docker buildx in GA. However, Changes have been reverted in [PR](https://github.com/eclipse/che-devfile-registry/pull/327) because the changes were failed for release [build](https://github.com/eclipse/che-devfile-registry/runs/1734763378?check_suite_focus=true). However before raising PR changes were tested on all the specified architectures.

**Comment by nickboldt** [comment]
Well, this clearly isn't an urgent priority. Closing.
