### ISSUE TITLE
Enable multiarch builds for che-server

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18944]
### Is your task related to a problem? Please describe.

As discovered in https://issues.redhat.com/browse/CRW-1475 the che server is still publishing as single-arch amd64 images. We need ppc64le and s390x, too.

### Describe the solution you'd like

Borrowing code from:
* https://github.com/eclipse/che-plugin-registry/blob/master/.ci/sidecar-build-publish.sh#L28-L35 and 
* https://github.com/eclipse/che-plugin-registry/blob/master/.github/workflows/sidecar-build-push.yaml#L35-L48

we can enable buildx builds for the server images for both nightly and release, allowing it to be easier to test Che on other arches.

**Comment by aditijadhav38** [comment]
@nickboldt For workspaces to work properly on other archs like s390x, we need to change workspace image in [che.properties](https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties) file which is currently centos:centos7 because it is not available for s390x. However registry.access.redhat.com/ubi8-minimal image worked fine and is multiarch. Hence can we use this image in che.properties to make it multiarch.
Also in GA workflow of che-server, che-postgres image is getting build in [nightly-build](https://github.com/eclipse/che/blob/master/.github/workflows/nightly-build.yml) workflow. However as per discussion in [PR](https://github.com/eclipse/che/pull/16903#issuecomment-740214596), postgres db dependency removal from Che is currently in discussion, could you please give us some pointers regarding the same.

**Comment by nickboldt** [comment]
https://github.com/eclipse-che/che-server/blob/main/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L402 now has ubi-minimal. 

But the postgres thing is still a blocker. Moving to postgres 13 is in progress in Che 7.37 https://github.com/eclipse-che/che-server/pull/74 but looks like the image chosen is still single arch. :face_with_head_bandage: 

So this might never happen. 

On the plus side, Che server is nearing its EOL as DevWorkspace Engine will replace it soon.

**Comment by nickboldt** [comment]
Well, this clearly isn't an urgent priority. Closing.
