### ISSUE TITLE
SVN extension for VScode editor

### ISSUE THREAD

**Issue by RenDhark-star** [eclipse-che/che#19037]
Hi,
i am trying to install SVN on my workspace.  I use the guide https://www.eclipse.org/che/docs/che-7/end-user-guide/testing-a-visual-studio-code-extension-in-che/ and this extensions for VScode https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm .
This is my custom devile: https://gist.github.com/RenDhark-star/8e44c277814903374a387291fac78289 .
How do i install the dependencies in the sidecar?

**Comment by ericwill** [comment]
You have to create your own sidecar with SVN and any other dependencies installed. We already have several sidecars in the [che-plugin-registry](https://github.com/eclipse/che-plugin-registry), you can take a look at the [asciidoc sidecar](https://github.com/eclipse/che-plugin-registry/tree/master/sidecars/asciidoc) to get an example.

After that you have a few options:
* Build/push your sidecar to your own container registry, and reference it in your own `meta.yaml` file and devfile
* Open a PR to the che-plugin-registry so that the SVN plugin is included in Che's plugin registry by default. Some instructions on how to do this are located [here](https://github.com/eclipse/che-plugin-registry/blob/master/CONTRIBUTE.md)
