### ISSUE TITLE
[UD] Sort alphabetically samples cards on Get Started

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#19092]
### Is your task related to a problem? Please describe.

Tiles on the workspace creation page are not sorted.
We need to sort them by name.

![Screenshot from 2021-02-18 12-39-34](https://user-images.githubusercontent.com/1655894/108345215-afc0d880-71e6-11eb-984a-48ae90983ff3.png)

**Comment by sleshchenko** [comment]
> We need to sort them by name.

Who told you that?
I think we may but I'm not sure that we should.
Dashboard displays samples in the way, devfile registry returns them.
Devfile owner could decide which stacks are more used and move them up, which are rarely used, and move them down.
But since we don't order stack on devfile registry side, it's just generated, I agree it's logical to order them alphabetically.

**Comment by vitaliy-guliy** [comment]
The list looks a bit strange. The same when you browse the unsorted directory.

**Comment by sleshchenko** [comment]
Here is a prove that it's registry who should care about devfiles order, CRW achieves it with folders names: https://github.com/redhat-developer/codeready-workspaces/tree/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles

Moving this issue to devfile registry side.
cc @ericwill
