### ISSUE TITLE
Decide what features devworkspace-che-client should have

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#19219]
### Is your task related to a problem? Please describe.

Right now we have a [new typescript library](https://github.com/che-incubator/devworkspace-client) for managing devworkspaces and devworkspace templates but it has some che specific code. If we ever want to contribute the devworkspace-client to the cncf then we have to make the library more general and extract che specific functionality to a devworkspace-che-client library. This issue is to list all the features that we should have in the devworkspace-che-client

For example,
- devworkspace-che-client should take care of creating projects/namespaces instead of that being done in devworkspace-client
- potentially we can extract devworkspacetemplate creation/ownerref specifying from the dashboard into devworkspace-che-client so chectl can re-use this functionality

### Describe the solution you'd like

Have two librarys, a generic devworkspace/devworkspacetemplate library for typescript and a che specific devworkspace/devworkspacetemplate library

### Describe alternatives you've considered

None

**Comment by sleshchenko** [comment]
> Have two librarys, a generic devworkspace/devworkspacetemplate library for typescript and a che specific devworkspace/devworkspacetemplate library

For time being, until we don't need two libraries, we just may separate DevWorkspace and Che DevWorkspace logic into separate interfaces. 
Che DevWorkspaces will reuse DevWorkspace interface.

**Comment by sleshchenko** [comment]
So, on call with Florent and Josh we agreed that:
- we need to have separate interfaces for DevWorkspace and Che DevWorkspace logic;

DevWorkspace client would handle some basic CRUD for devworkspaces and devworkspace templates (along with tricky ownerRef logic we have on dashboard now)

Che DevWorkspace should provide an ability to resolve the DevWorkspace and DevWorkspaceTemplates where input is (devfile or repo URL).
There is a place for DevWorkspaceTemplate resolver logic, which is editor dependent, where Che Theia can provide their implementation and let Che DevWorkspace lib keep theia plugins/sidecars free.

So, Che Theia contributes DevWorkspace Templates into DevWorkspace depending on the .folder/* files (like che-theia-plugins.yaml file or .vscode/extensions.json)
Che Theia can as a first step consume devfile url and if it’s GITHUB url, it resolves needed files from there.
The draft from Florent https://gist.github.com/benoitf/fd11011cc3f89629ce7256ca5ecead47

Eventually, that resolve logic will be done by DevWorkspace Resolver component, which will do git projects cloning and will be able to access cloned project file system, instead of SVC http API.
