### ISSUE TITLE
Factory acceptance fails if there is no k8s namespace yet

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19236]
### Is your task related to a problem? Please describe.
The PR https://github.com/eclipse/che-dashboard/pull/183 integrates dashboard with Che Server Bitbucket OAuth flow implemented recently. But there is one drawback: oauth flow can't be finished is namespace does not exists and Dashboard can do nothing with it.

Che Server should try to precreate namespace when it does not exist on `/api/kubernetes/namespaces` method or on try to store bitbucket secret.

I'm open to discuss alternative if any.

**Comment by sleshchenko** [comment]
Dashboard workaround introduced in https://github.com/eclipse-che/che-dashboard/pull/183 is broken, probably due changes on Che Server side https://github.com/eclipse/che/pull/19518

It's how now the dashboard notifies users about namespace absence:
![Screenshot_20210430_190820](https://user-images.githubusercontent.com/5887312/116723656-6bbd3180-a9e8-11eb-9d9d-032a051ee38d.png)

**Comment by cccs-eric** [comment]
I also ran into this issue while testing my [GitHub integration with OAuth](https://github.com/eclipse-che/che-server/pull/28).  Once my PR gets merged, we might see more and more occurrences of this problem since a lot of people are using GitHub.  So this doesn't only apply to BitBucket, but also to GitHub eventually.

**Comment by mshaposhnik** [comment]
Honestly, i don't like idea that `factory/resolve` must create namespace. But twice much as that, i don't like the idea that `factory/resolve` must do a decision what exacly to create (namings etc). 

Since dashb already doing the request to figure out list of user-s namespaces (and theirs existence),
my proposal is to send desired namespace name as the parameter of `factory/resolve` (which can take an unlimited number of parameters).  In that case we can just do the usual routine using `KubernetesNamespaceFactory` with minimal modifications.

@skabashnyuk @sleshchenko WDYT ?

**Comment by skabashnyuk** [comment]
>Since dashb already doing the request to figure out list of user-s namespaces (and theirs existence),
my proposal is to send desired namespace name as the parameter of factory/resolve (which can take an unlimited number of parameters).

Dashboard does not know it. In that case, we need to provide a service that will tell what the namespace names should be.


>That will also help if user have multiple NS

Users can have one and only one NS.

**Comment by mshaposhnik** [comment]
Service is already present and dashboard making requests to it. [Link](https://github.com/eclipse-che/che-server/blob/main/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/api/server/KubernetesNamespaceService.java#L52)

**Comment by skabashnyuk** [comment]
@mshaposhnik I think it's better to rethink/refact che-server internals and create k8s namespace when it's needed.

**Comment by skabashnyuk** [comment]
should be covered by 
 - https://github.com/eclipse/che/issues/20165
-  https://github.com/eclipse/che/issues/20167

**Comment by skabashnyuk** [comment]
Fixed https://github.com/eclipse/che/issues/20165 and https://github.com/eclipse/che/issues/20167
