### ISSUE TITLE
Failed to stop a starting workspace

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19254]
### Che version

 - [x] nightly

### Steps to reproduce
1. Start a workspace with Recent workspaces on left-nav bar or from workspaces list.
2. While it’s starting, perform Stop action on workspaces list or workspace details.
3. Check workspace start is interrupted.
Actually workspace is indicated as a starting and `stop` action isn't available anymore

### Runtime
   - [x] Openshift (include output of `oc version`)

### Screenshots
![screencast-che-eclipse-che apps cluster-4237 4237 sandbox422 opentlc com-2021 03 10-12_53_47](https://user-images.githubusercontent.com/1640675/110619585-a81aa100-81a0-11eb-9eff-c80d30e214c7.gif)

### Installation method
   - [x] I don't know

### Environment
   - [x] Cloud

**Comment by sleshchenko** [comment]
The cause of confusion is fact that Starting and Stopping has the same icon. Thanks for reporting it.

**Comment by parvathyvr** [comment]
Hi @sleshchenko I agree that in the redesign there is no way to verify the status of the workspace whether it is starting/stopping because both uses the same icon and spinning animation.
-Immediate solution would be to add tooltips to the status icons in the left nav (we used to show the same animation for stating/stopping in the old interface,but when user hovers the status was shown) and in the table view of workspace list view( [refer this screen](https://docs.google.com/document/d/1Ao0mfcqA41dv_h8SVgsVV7sPbO57opSuplL0331_xwM/edit?ts=5f185cf5#heading=h.fuxqk74l06kz)) when the user hovers.
-The other quick fix could be to have the STOPPING state be represented by the same icon-but use a different colour-eg:the grey color we use for the stopped state and even may be for the animation-spin in the opposite direction.
@tolusha

**Comment by sleshchenko** [comment]
I fully misunderstood that described issue, what we can do on Dashboard side: use a different icon for stopping workspaces, how tooltip for workspace status to provide it clear meaning, but don't expect users know which colors means what.

But this issue is really about that workspace hangs on STOPPING state, but it's Che Server issue.
The way interruption was implemented, interruption is check when startup move to next step, like mkdir to plugin-brokering. If it hangs on some state - user will need to wait timeout until workspace gets STOPPED with error. Here are two way to improve situation:
- give user power to kill a workspace https://github.com/eclipse/che/issues/17651
- investigate and prevent situations when workspace is hangs on one of the phase, or simply decrease timeout to something like 30 seconds.
