### ISSUE TITLE
Running DAST on eclipse che

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#19256]
## Summary
Which tool should be used to run Dynamic Application Security Testing (DAST)  on our eclipse che installation?  
## Relevant information

We have Eclipse che setup on Kubernetes and configured as a Multiuser setup.   We have also added custom extensions for our specific functionalities. Now we have been asked to run DAST starting with the eclipse che url. We tried using a few Tools like HCL AppScan and OWASP Zap. but we see them failing to load the IDE.  Its possibly due to eclipse che using Websockets and those tools not supporting that protocol.  

Do we have a recommended tool to run DAST on Eclipse che?

**Comment by davidfestal** [comment]
cc @ericwill

**Comment by pgirishibm** [comment]
@davidfestal With regard to security scans, in quay.io I see some images do have Vulnerabilities reported. and its been there across versions. for eg che-keycloak. 
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/17478559/111635975-0e956400-881e-11eb-9eef-54cbb00c9262.png">

How are such vulnerabilties handled?

**Comment by romankurnovskii** [comment]
i get the same:
`
✗ Medium severity vulnerability found in systemd/libsystemd0
  Description: Information Exposure
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-SYSTEMD-582552
  Introduced through: systemd/libsystemd0@245.4-4ubuntu3.2, apt@2.0.2ubuntu0.1, procps/libprocps8@2:3.3.16-1ubuntu2, util-linux/bsdutils@1:2.34-0.1ubuntu9.1, util-linux/mount@2.34-0.1ubuntu9.1, systemd/libudev1@245.4-4ubuntu3.2
  From: systemd/libsystemd0@245.4-4ubuntu3.2
  From: apt@2.0.2ubuntu0.1 > systemd/libsystemd0@245.4-4ubuntu3.2
  From: procps/libprocps8@2:3.3.16-1ubuntu2 > systemd/libsystemd0@245.4-4ubuntu3.2
  and 6 more...

✗ Medium severity vulnerability found in sqlite3/libsqlite3-0
  Description: Out-of-bounds Read
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-SQLITE3-581593
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > heimdal/libgssapi3-heimdal@7.7.0+dfsg-1ubuntu1 > heimdal/libheimntlm0-heimdal@7.7.0+dfsg-1ubuntu1 > heimdal/libkrb5-26-heimdal@7.7.0+dfsg-1ubuntu1 > sqlite3/libsqlite3-0@3.31.1-4ubuntu0.2

✗ Medium severity vulnerability found in p11-kit/libp11-kit0
  Description: Out-of-bounds Read
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-P11KIT-1052982
  Introduced through: p11-kit/libp11-kit0@0.23.20-1build1, apt@2.0.2ubuntu0.1
  From: p11-kit/libp11-kit0@0.23.20-1build1
  From: apt@2.0.2ubuntu0.1 > gnutls28/libgnutls30@3.6.13-2ubuntu1.3 > p11-kit/libp11-kit0@0.23.20-1build1
  Fixed in: 0.23.20-1ubuntu0.1

✗ Medium severity vulnerability found in p11-kit/libp11-kit0
  Description: Out-of-bounds Write
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-P11KIT-1052991
  Introduced through: p11-kit/libp11-kit0@0.23.20-1build1, apt@2.0.2ubuntu0.1
  From: p11-kit/libp11-kit0@0.23.20-1build1
  From: apt@2.0.2ubuntu0.1 > gnutls28/libgnutls30@3.6.13-2ubuntu1.3 > p11-kit/libp11-kit0@0.23.20-1build1
  Fixed in: 0.23.20-1ubuntu0.1

✗ Medium severity vulnerability found in p11-kit/libp11-kit0
  Description: Integer Overflow or Wraparound
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-P11KIT-1052996
  Introduced through: p11-kit/libp11-kit0@0.23.20-1build1, apt@2.0.2ubuntu0.1
  From: p11-kit/libp11-kit0@0.23.20-1build1
  From: apt@2.0.2ubuntu0.1 > gnutls28/libgnutls30@3.6.13-2ubuntu1.3 > p11-kit/libp11-kit0@0.23.20-1build1
  Fixed in: 0.23.20-1ubuntu0.1

✗ Medium severity vulnerability found in openssl/libssl1.1
  Description: Integer Overflow or Wraparound
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENSSL-1075558
  Introduced through: ca-certificates@20190110ubuntu1.1, curl@7.68.0-1ubuntu2.2
  From: ca-certificates@20190110ubuntu1.1 > openssl@1.1.1f-1ubuntu2 > openssl/libssl1.1@1.1.1f-1ubuntu2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openssl/libssl1.1@1.1.1f-1ubuntu2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > libssh/libssh-4@0.9.3-2ubuntu2.1 > openssl/libssl1.1@1.1.1f-1ubuntu2
  and 2 more...
  Fixed in: 1.1.1f-1ubuntu2.2

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: NULL Pointer Dereference
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1035737
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.4

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: CVE-2020-25710
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1040477
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.5

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: CVE-2020-25709
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1040481
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.5

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: Reachable Assertion
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1064802
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.6

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: Access of Resource Using Incompatible Type ('Type Confusion')
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1064808
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.6

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: Integer Underflow
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1064814
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.6

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: Loop with Unreachable Exit Condition ('Infinite Loop')
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1064820
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.6

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: CVE-2020-36226
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1064826
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.6

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: Release of Invalid Pointer or Reference
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1064832
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.6

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: Reachable Assertion
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1064838
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.6

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: Double Free
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1064844
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.6

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: Out-of-bounds Read
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1064850
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.6

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: Integer Underflow
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1064856
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.6

✗ Medium severity vulnerability found in openldap/libldap-common
  Description: Reachable Assertion
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENLDAP-1075544
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3 > openldap/libldap-common@2.4.49+dfsg-2ubuntu1.3
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.3
  Fixed in: 2.4.49+dfsg-2ubuntu1.7

✗ Medium severity vulnerability found in libzstd/libzstd1
  Description: Incorrect Default Permissions
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-LIBZSTD-1082292
  Introduced through: meta-common-packages@meta
  From: meta-common-packages@meta > libzstd/libzstd1@1.4.4+dfsg-3
  Fixed in: 1.4.4+dfsg-3ubuntu0.1

✗ Medium severity vulnerability found in libzstd/libzstd1
  Description: Incorrect Default Permissions
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-LIBZSTD-1082296
  Introduced through: meta-common-packages@meta
  From: meta-common-packages@meta > libzstd/libzstd1@1.4.4+dfsg-3
  Fixed in: 1.4.4+dfsg-3ubuntu0.1

✗ Medium severity vulnerability found in krb5/libkrb5support0
  Description: Uncontrolled Recursion
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-KRB5-1038545
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > krb5/libgssapi-krb5-2@1.17-6ubuntu4 > krb5/libkrb5support0@1.17-6ubuntu4
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > krb5/libgssapi-krb5-2@1.17-6ubuntu4 > krb5/libk5crypto3@1.17-6ubuntu4 > krb5/libkrb5support0@1.17-6ubuntu4
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > krb5/libgssapi-krb5-2@1.17-6ubuntu4 > krb5/libkrb5-3@1.17-6ubuntu4 > krb5/libkrb5support0@1.17-6ubuntu4
  and 5 more...
  Fixed in: 1.17-6ubuntu4.1

✗ Medium severity vulnerability found in curl/libcurl4
  Description: Out-of-bounds Write
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-CURL-1049516
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2
  Fixed in: 7.68.0-1ubuntu2.4

✗ Medium severity vulnerability found in curl/libcurl4
  Description: Improper Certificate Validation
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-CURL-1049522
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2
  Fixed in: 7.68.0-1ubuntu2.4

✗ Medium severity vulnerability found in curl/libcurl4
  Description: Man-in-the-Middle (MitM)
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-CURL-1090012
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2
  Fixed in: 7.68.0-1ubuntu2.5

✗ Medium severity vulnerability found in curl/libcurl4
  Description: Exposure of Private Information ('Privacy Violation')
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-CURL-1090018
  Introduced through: curl@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2
  From: curl@7.68.0-1ubuntu2.2
  Fixed in: 7.68.0-1ubuntu2.5

✗ Medium severity vulnerability found in apt/libapt-pkg6.0
  Description: Integer Overflow or Wraparound
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-APT-1050038
  Introduced through: apt/libapt-pkg6.0@2.0.2ubuntu0.1, apt@2.0.2ubuntu0.1
  From: apt/libapt-pkg6.0@2.0.2ubuntu0.1
  From: apt@2.0.2ubuntu0.1 > apt/libapt-pkg6.0@2.0.2ubuntu0.1
  From: apt@2.0.2ubuntu0.1
  Fixed in: 2.0.2ubuntu0.2

✗ High severity vulnerability found in openssl/libssl1.1
  Description: NULL Pointer Dereference
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENSSL-1049132
  Introduced through: ca-certificates@20190110ubuntu1.1, curl@7.68.0-1ubuntu2.2
  From: ca-certificates@20190110ubuntu1.1 > openssl@1.1.1f-1ubuntu2 > openssl/libssl1.1@1.1.1f-1ubuntu2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openssl/libssl1.1@1.1.1f-1ubuntu2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > libssh/libssh-4@0.9.3-2ubuntu2.1 > openssl/libssl1.1@1.1.1f-1ubuntu2
  and 2 more...
  Fixed in: 1.1.1f-1ubuntu2.1

✗ High severity vulnerability found in openssl/libssl1.1
  Description: NULL Pointer Dereference
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-OPENSSL-1089071
  Introduced through: ca-certificates@20190110ubuntu1.1, curl@7.68.0-1ubuntu2.2
  From: ca-certificates@20190110ubuntu1.1 > openssl@1.1.1f-1ubuntu2 > openssl/libssl1.1@1.1.1f-1ubuntu2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > openssl/libssl1.1@1.1.1f-1ubuntu2
  From: curl@7.68.0-1ubuntu2.2 > curl/libcurl4@7.68.0-1ubuntu2.2 > libssh/libssh-4@0.9.3-2ubuntu2.1 > openssl/libssl1.1@1.1.1f-1ubuntu2
  and 2 more...
  Fixed in: 1.1.1f-1ubuntu2.3
`
