### ISSUE TITLE
VS Code builtin extensions used in che should be compiled with nodejs 12

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19342]
### Is your task related to a problem? Please describe.
Despite saying it should be compiled using nodejs12, nodejs10 has been used to compile builtin extensions.
https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/pull/19#pullrequestreview-614288572

### Describe the solution you'd like
nodejs 12 should be used

### Describe alternatives you've considered
nodejs12 is the version used by VS Code to compile its extensions, thus it should be using that one

### Additional context
nodejs10 is no longer LTS release of nodejs

**Comment by ericwill** [comment]
I'm not really sure what the problem is, all theia built-ins are using node 10 so we are just following their process:

https://github.com/eclipse-theia/vscode-builtin-extensions/blob/master/.github/workflows/publish-next.yml#L33
https://github.com/eclipse-theia/vscode-builtin-extensions/blob/master/.github/workflows/publish-vsx-latest.yml#L33
https://github.com/eclipse-theia/vscode-builtin-extensions/blob/master/.github/workflows/publish-vsx-next.yml#L33
https://github.com/eclipse-theia/vscode-builtin-extensions/blob/master/.github/workflows/publish-vsx-specific-latest.yml#L31
https://github.com/eclipse-theia/vscode-builtin-extensions/blob/master/.github/workflows/publish-vsx-specific-next.yml#L31

This is something we should likely solve upstream.
