### ISSUE TITLE
External access to Eclipse-Che in Minikube

### ISSUE THREAD

**Issue by fredcsfaria** [eclipse-che/che#19404]
## Summary

I  installed  Eclipse-Che in Minikube running in  a Linux box.

In that box I add an entry to  "/etc/hosts"  file  and I can with success to run the curl against the Che ingress hostname:
    curl --cacert /tmp/cheCA.crt  https://che-eclipse-che.x.x.x.x.nip.io:443   ( where x.x.x.x  is the Minikube Ip )
 
But I would like to access this URL from remote  hosts  in the local network. 
Then I run "kubectl port-forward"  to  map  the container port  in linux box port  ( hostname=abc.com and  port 8090 ) . 
From a local shell I can query  via curl  the URL  https://abc.com:8090.
        
But this is not enough to run remotely because when I open  the URL   "https://abc.com:8090" in browser   Eclipse Che starts loading until  it fails in a call to "https://keycloak-eclipse-che.192.168.49.2.nip.io/auth/js/keycloak.js".

How can I succeed to get remote access to Eclipse-Che in this configuration (  Minikube ) ? 
 Do I need to configure virtual routing in linux box to reach all endpoints ( che, keycloak, etc )  ?

**Comment by gattytto** [comment]
@fredcsfaria there must be more than 1 way around this, the one I found is probably not the easiest. in your dns panel for the domain:
1: create a A entry for your public facing host in your domain (say cheendpoint) with your public ip 
2: delegate a dns zone for all che subdomains to a subdomain of the master domain (say chetest)
```
MASTER DOMAIN (abc.com)
IN A cheendpoint 1.2.3.4#subdomain: cheendpoint.abc.com = PIBLIC IP OF KVM VM 
IN NS CHETEST.ABC.COM CHEENDPOINT.ABC.COM
```
then in your host you must run a dns server with a wildcard entry for the chetest.abc.com zone
``` 
IN CNAME * CHETEST.ABC.COM
IN A  CHETEST.ABC.COM 1.2.3.4
```

then in your host you expose the https port from minikube and add the ingress-dns plugin to minikube. 

with the ingress-dns plugin you can make all the che pods resolve your domains to the local-ip, thus allowing the setup of che using real public domain and not nip.io ones (in this example, abc.com), so it will create a dns record in coreDNS pod (minikube's internal dns solver) for each ingress che creates at startup. 

now the trick is to edit coreDNS configmap in minikube using kubectl and set it as:
```
chetest.abc.com:53
  forward . your-host-LAN-ip:53
```

and set this in your host /etc/resolv.conf:
```
nameserver 10.96.0.10
nameserver 1.1.1.1
```
10.96.0.10 is the ip given to coreDNS pod inside kubernetes. So your host should find its way to it without any config changes. 

how this works:
in a common home-lab setup, you have a computer with a LAN address and a home router providing internet with a public IP.

minikube ingress-dns plugin will create che dns records in coreDNS using the LAN ip from your host, since your host actually doesn't "own" the public ip, but only has some default route to get to wherever the internet is. 

when parties outside of your lan query for any of the subdomains that belong to chetest zone, they get redirected to the public ip of your host (your home router's public facing ip), so dns queries resolve to your public ip but actual connections to the https port (443) get rerouted when they get to your host's lan, because *.chetest.abc.com is 1.2.3.4(your router's ip) but eclipse-che or keycloack.chetest.abc.com will be your hosts's LAN ip thanks to ingress-dns plugin in minikube and coreDNS being the first nameserver responding to your host resolution requests over those *.chetest.abc.com hosts, so when all is good, keycloack-eclipse-che.chetest.abc.com will resolv to 1.2.3.4 from the outside but will be routed to minikube, hitting the right endpoint inside your cluster.

when the request is made from inside the cluster, we will go to che host and the che server will try to contact keycloack.chetest.abc.com which will resolve to a LAN ip thanks to coreDNS and ingress-dns plugin, so the request from the che server pod will hit your host and be rerouted straight back into the cluster and hit the keycloack pod in its in-cluster ip accordingly (this is setup automatically in your host by minikube and ingress-controller plugin). 

if you want other hosts in your lan to be able to correctly stay inside the LAN for that domain, you can set your host ip as the first dns resolver in your dhcp zone for your LAN. This way your LAN parties will query your host as the first nameserver of your LAN.

![che self host](https://user-images.githubusercontent.com/407397/112554674-06619980-8dc7-11eb-89e0-af791e37ffa1.png)

**Comment by l0rd** [comment]
@fredcsfaria have you tried to follow this doc https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-che-hostname/ to change the hostname? @tolusha any idea?
