### ISSUE TITLE
Flags in attributes should use 'true' and 'false'

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#19440]
### Is your enhancement related to a problem? Please describe.
I've noticed that we have the line `multiRoot: 'off'` in some of our devfiles. That value is hard to guess, and since there is no code assist for attribute values, the tools don't help.

### Describe the solution you'd like
We should always use 'true' and 'false' to designate flags. It will lead to the least config errors.

**Comment by RomanNikitenko** [comment]
I see your point of view about `true` and `false` for the attributes.
thanks!

About the `multiRoot` attribute - AFAIK - starting from the `7.30.0` there should be no way to use the previous mode.
So, I guess, the problem go away with `7.30.0` version.

Do you know other attributes with the similar problem which should be fixed?

**Comment by tsmaeder** [comment]
@RomanNikitenko this is not just about the "multiRoot" attribute. More important than the concrete value is that we always use the same one.

**Comment by RomanNikitenko** [comment]
>  this is not just about the "multiRoot" attribute.

I understand. That's why I asked:
> Do you know other attributes with the similar problem which should be fixed?

So, I expected that we have some list of attributes which should be reconsidered.

If the issue is more about `not provide in future` or like a `bad practice` then we should have a mechanism how to bring it to contributors. Maybe something like `theia` has [here](https://github.com/eclipse-theia/theia/wiki/Coding-Guidelines)
