### ISSUE TITLE
Singleuser: Failed to create new workspace from the devfile: cannot read property "send" of undefined

### ISSUE THREAD

**Issue by Kerdanyy** [eclipse-che/che#19499]
### Che version
 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Click on any sample

### Expected behavior
Sample should be created

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/18310499/113514054-c93a9b80-956c-11eb-9954-217291057b79.png)

### Installation method
   - [x] chectl
     * chectl server:deploy --platform=docker-desktop --installer=helm
     * chectl/0.0.20210402-next.4e59edd win32-x64 node-v12.21.0
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ x] my computer
       - [ x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Eclipse Che Logs
    √ Eclipse Che 7.29.0-SNAPSHOT has been successfully deployed.
    √ Documentation             : https://www.eclipse.org/che/docs/
    √ -------------------------------------------------------------------------------
    √ Users Dashboard           : https://che-eclipse-che.10.67.85.22.nip.io
    √ Admin user login          : "admin:admin". NOTE: must change after first login.
    √ -------------------------------------------------------------------------------
    √ Plug-in Registry          : https://plugin-registry-eclipse-che.10.67.85.22.nip.io/v3
    √ Devfile Registry          : https://devfile-registry-eclipse-che.10.67.85.22.nip.io
    √ -------------------------------------------------------------------------------
    √ -------------------------------------------------------------------------------

**Comment by svor** [comment]
@Kerdanyy Hello, thank you for reporting! Could you please share logs from the browser console and all logs from che server: `chectl server:logs`

**Comment by Kerdanyy** [comment]
Browser console log:
![image](https://user-images.githubusercontent.com/18310499/113592919-10409380-9636-11eb-81cd-2d662b386de5.png)

Che server log:

[1617637353677.zip](https://github.com/eclipse/che/files/6259093/1617637353677.zip)

**Comment by Kerdanyy** [comment]
Is there any workaround available until this issue is fixed?

**Comment by Walt9819** [comment]
Same issue with me. Here are the details and logs:

### Che version
- [x] latest
- [ ] nightly
- [ ] other: please specify

### Steps to reproduce
Click on any sample

### Expected behavior
Sample should be created

### Runtime
- [ ] kubernetes (include output of kubectl version)
- [ ] Openshift (include output of oc version)
- [ ] minikube (include output of minikube version and kubectl version)
- [ ] minishift (include output of minishift version and oc version)
- [x] docker-desktop + K8S (include output of docker version and kubectl version)
- [ ] other: (please specify)

Screenshots
image

### Installation method: 
- [x] chectl
  - `chectl server:deploy --platform=docker-desktop --installer=helm`
  - chectl/0.0.20210413-next.950a1f6 win32-x64 node-v12.22.0
- [ ] OperatorHub
- [ ] I don't know

### Environment
- [ x] my computer
   - [ x] Windows
   - [ ] Linux
   - [ ] macOS
- [ ] Cloud
- [ ] Amazon
- [ ] Azure
- [ ] GCE
- [ ] other (please specify)
- [ ] Dev Sandbox (workspaces.openshift.com)
- [ ] other: please specify


### Eclipse Che Logs
```
√ Show important messages
    √ Eclipse Che 7.29.0-SNAPSHOT has been successfully deployed.
    √ Documentation             : https://www.eclipse.org/che/docs/
    √ -------------------------------------------------------------------------------
    √ Users Dashboard           : https://che-eclipse-che.172.20.176.1.nip.io
    √ Admin user login          : "admin:admin". NOTE: must change after first login.
    √ -------------------------------------------------------------------------------
    √ Plug-in Registry          : https://plugin-registry-eclipse-che.172.20.176.1.nip.io/v3
    √ Devfile Registry          : https://devfile-registry-eclipse-che.172.20.176.1.nip.io
    √ -------------------------------------------------------------------------------
    √ -------------------------------------------------------------------------------
Command server:deploy has completed successfully in 00:56.
```
### Logs
Logs inside [this zip](https://github.com/eclipse/che/files/6307345/eclipse_che.zip).

**Comment by sleshchenko** [comment]
I can reproduce it on linux + minikube, my dashboard fails to load the workspaces list due to:
```
Failed to request workspaces:
TypeError: Cannot read property 'send' of undefined
```

**Comment by sleshchenko** [comment]
@Kerdanyy I think the workaround would be to deploy MultiUser Che: `chectl server:deploy --platform=docker-desktop --installer=helm --multiuser`.
SingleUser is not even officially supported.
