### ISSUE TITLE
factory resolver misses volume component from devfile 2.0

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19563]
### Describe the bug
Factory resolver misses volume component from devfile 2.0 with leads invalid devfile:
>   "message": "DevWorkspace.workspace.devfile.io \"spring-petclinic\" is invalid: [\u003cnil\u003e: Invalid value: \"\": \"spec.template.components\" must validate one and only one schema (oneOf). Found none valid, spec.template.components.container: Required value]",
Resolved devfile: mavenrepo component has only name.
```json
{
  "v": "4.0",
  "devfile": {
    "schemaVersion": "2.0.0",
    "metadata": {
      "name": "spring-petclinic"
    },
    "components": [
      {
        "name": "maven",
        "container": {
          "image": "quay.io/eclipse/che-java8-maven:nightly",
          "volumeMounts": [
            {
              "name": "mavenrepo",
              "path": "/root/.m2"
            }
          ],
          "env": [
            {
              "name": "ENV_VAR",
              "value": "value"
            }
          ],
          "memoryLimit": "1536M"
        }
      },
      {
        "name": "mavenrepo"
      }
    ]
  }
}
```
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Che with devworkspace support enabled.
2. Accept factory from devfile with volume component, like $CHE_HOST#https://gist.githubusercontent.com/sleshchenko/e6382a45094b520118db2e5a318cc050/raw/b7d445c943c512092fea28206108d234aa761478/devfile2.yaml

### Expected behavior
Che Server returns a valid devfile, which is a valid, so it's possible to create devworkspace from it.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by mshaposhnik** [comment]
So since we didn't have model for Devfile v2, we serialize it as just a `Map<String, Object>` where inner objects are also Maps etc.
And due to [this](https://github.com/eclipse/che/blob/master/core/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/DtoFactory.java#L506) code, since legacy mode seems to be turned off, 
the `NullOrEmptyCollectionAdapter` removes empty fields.  cc @skabashnyuk @sparkoo any ideas how to fix ?

**Comment by sparkoo** [comment]
So when is this information lost? When parsing the json into Map? Or when translating the Map into json content when creating the response for api call?

Is `NullOrEmptyCollectionAdapter` still relevant? Do we really need it?

What about parsing the devfile into JsonObject (or whatever is the class) instead of Map? Would it help? What about keep it as raw string and parse to Map only for validation?

**Comment by mshaposhnik** [comment]
when converting FactoryV2Dto into `json` type responce.

**Comment by skabashnyuk** [comment]
At this point, we can't fix this issue for `factory.resolve` method without massive compatibility registration. Reason for that https://github.com/eclipse/che/pull/13515 when we do not serialize maps for all DTO. alternative fo that 1. Do not add a component with empty content or sooner we are going to implement an alternative method to get content of the file `Allow resolver API to resolve other files than [.]devfile.yaml`  https://github.com/eclipse/che/issues/19540
