### ISSUE TITLE
Failing unit test KubernetesNamespaceFactoryTest when building Che server

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#19641]
### Describe the bug
Nightly build, as well as several other PR build checks are now failing on the same unit test in kubernetes/infrastructure module.
https://github.com/eclipse/che/runs/2395903653?check_suite_focus=true

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Build the project with `mvn clean install -Pintegration`.
The module infrastructure-kubernetes will fail

### Expected behavior
All projects should be built successfully

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (GitHub Actions
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
It also blocks PR merging since PR checks are failing like here https://github.com/eclipse/che/pull/19606

**Comment by skabashnyuk** [comment]
The source of the problem is TLS1.0 that was used in  https://github.com/fabric8io/kubernetes-client/issues/3038 and removed in java 11.0.11 https://bugs.openjdk.java.net/browse/JDK-8202343 Since we used `actions/setup-java@v1` on github actions we got the latest version of java 11. At this point the safest thing to wait for fix https://github.com/fabric8io/kubernetes-client/issues/3038 and backport if needed to kubernetes-client 4.x after that align github action version with the version of java that we use for che-server docker image build

**Comment by skabashnyuk** [comment]
Followup https://github.com/eclipse/che/issues/19743
