### ISSUE TITLE
Enhancement: When a workspace has no projects show welcome buttons in the file explorer

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19645]
### Is your task related to a problem? Please describe.
Today, If I open CheTheia with a devfile without any projects I've a empty project explorer
![image](https://user-images.githubusercontent.com/436777/115664001-96045480-a341-11eb-9de2-9ee4b66eff3c.png)

I can't create new files until I open/add `/projects` as workspace folder for example so it may be hard to figure out for newcomers

### Describe the solution you'd like
If there is no project, add PROJECT_ROOT as default workspace folder

### Describe alternatives you've considered
N/A

### Additional context
related to multi-root

https://issues.redhat.com/browse/CRW-2051

### Release Notes Text

Before this update, when a workspace contained no projects, the Che-Theia editor was displaying an empty file explorer.
For the user it was not obvious how to create a file or clone a repository. 
With this update, when a workspace contains no project, the Che-Theia editor displays *Open Folder* and *Clone Repository* buttons in the file explorer.

**Comment by RomanNikitenko** [comment]
@benoitf 
Hello!
I see some problems related to adding `/projects` as  default workspace folder.
It's due to `/projects` is projects root, but we are going to use it as a workspace folder for the case when a devfile has empty list of projects.
Taking into account that a user can face with some confusing state of projects tree.

For example:
-  we automatically add `/projects` as workspace folder after starting a workspace from a devfile without projects
- `/projects` is default directory when user goes to a terminal
- a user clones a project using a terminal
- the project is placed in `/projects`
- `/projects` - is projects root - we track it using file watchers
-  the system detects that a new project appears - the systems adds it as a workspace folder to a config file

As result the user can see in projects tree:
![projects_clone](https://user-images.githubusercontent.com/5676062/120979747-92f0e680-c77e-11eb-840d-4acd535a8621.gif)

I think we could consider another way to resolve the problem related to workspaces which starts from a devfile without projects.

For example, we could automatically create a folder in `projects` and add it to workspace config file. It allows to avoid conflicts at using `/projects` as projects root and as workspace folder at the same time - `/projects` - is always projects root, never - workspace folder, we use another `hello` folder (btw - I'm not sure what's name we should use for it) as workspace folder. 

Another way which I see - we could display two buttons in the projects tree view for such use case:
- Create Folder
- Clone Repository

VS Code has something similar if there are no projects:
![open_clode](https://user-images.githubusercontent.com/5676062/120985506-5a540b80-c784-11eb-938a-f67e263b8aef.png)

But I think we should:
- use `Create Folder` instead of `Open Folder` - otherwise - which folder a user can open for a workspace without projects?
- has own behavior for `Clone Repository` - to have an ability to add a project as workspace folder to `Che` workspace after cloning.

So, I have described above 2 ways how we could handle the use case: 
- `hello` folder
- 2 buttons

Any other ideas are welcome!
@benoitf @azatsarynnyy

**Comment by benoitf** [comment]
hello, I'm unsure about the dummy folder just to not have a /projects as project root folder. It looks more confusing to me.

About actions yes it's helpful as well. The idea is really to not see a blank tree explorer because today it's that you don't know what to do to see files, explorer being empty (so opening /projects was a quick workaround)

About Open folder, maybe users want to still open /projects and clone there as well. Forcing to use create may be a problem as well. Also create does not imply to open it after.
Probably in che the clone button should be first.

**Comment by azatsarynnyy** [comment]
The solution with 2 buttons sounds well to me.

**Comment by RomanNikitenko** [comment]
thank you, Florent and Artem, for the feedback!

About
> About Open folder, maybe users want to still open / projects and clone there as well.

I would like to clarify the following to be sure that we are on the same page.
As far as I understand - our direction - is `Che` **multi** root workspace.
But using `Open Folder` button by a user leads to a **single** root workspace. 
![single-root-workspace](https://user-images.githubusercontent.com/5676062/121021743-5c30c580-c7aa-11eb-9087-3e64e4cc804b.gif)

or 

Do you mean we should have some custom button `Open Folder` which will actually  **add** a folder to the `Che` multi-root workspace?
It can be confusing for VS Code users...

Also - I believe we should add some logic for the use case when a user adds `/projects` as a workspace folder. 
As far as I understand for this use case:
-  user should have only one workspace folder - `projects`, other projects will be placed inside `projects` workspace folder and they will not be considered as workspace folders. 
- otherwise, they can be added to multi-root workspace as workspace folders, but they will be duplicated in the `Projects Tree` view: one time - as workspace folders within multi-root workspace and the second one - as items under `projects` workspace folder.

**Comment by RomanNikitenko** [comment]
@benoitf @azatsarynnyy 

Hello!
I'm still looking for the good solution for the use case when a devfile doesn't contain projects.

I described in the comments above my concerns related to:
- `Open Folder` action, 
- `multi-root` vs `single` root modes
- `/projects` as default workspace folder and as root at the same time

Now I'm trying the case when two buttons are displayed for a user:
- `New Folder` with a description: `You can add a new folder to the Che workspace.`
- `Clone Repository` with a description `You can also clone a repository from a URL`

For the `New Folder`action the behavior looks like:

![NewFolder_multi-root](https://user-images.githubusercontent.com/5676062/121684991-133d8180-cac8-11eb-8cbb-fc6441df398a.gif)
 
I haven't worked yet on the behavior for the `Clone Repository` action. 
I guess there is no problem when a user clones a project by `https`. But probably there is a problem when a user clones a project by `ssh`. 

Please share your opinion about such behavior (`New Folder` and `Clone Repository` when a devfile doesn't contain projects).
Any ideas are welcome!
thanks in advance!

**Comment by azatsarynnyy** [comment]
I'm okay with such an approach.

**Comment by benoitf** [comment]
AFAIK for cloning with ssh, user is prompted to upload ssh key if it's not there.
so we should be good.

**Comment by RomanNikitenko** [comment]
> AFAIK for cloning with ssh, user is prompted to upload ssh key if it's not there.
> so we should be good.

yes, I checked - there is some flow which should be OK for cloning with ssh.

@benoitf 
does it looks good for you `New Folder` behavior?

**Comment by benoitf** [comment]
@RomanNikitenko yes, most of people want to open files that are inside /projects (that are already auto-added)
Opening files in theia filesystem is a corner case and we can do that with proper commands as well

And if they start from blank devfiles, etc then it's fine to ask them to create a new folder

Maybe I would add the clone first (in VS code user may have tons of repositories cloned on its local filesystem while in che probably you may want to start by importing an existing project)

Maybe we should have also a terminal widget open on the user container as well (if there is one) but it's a different story not related to the current issue
