### ISSUE TITLE
Vulnerability found in che-server image

### ISSUE THREAD

**Issue by jenia90** [eclipse-che/che#19650]
### Describe the bug
In addition to issues #19646 and #19649 there's another vulnerability found in che-server image:
      Type:            VULNERABILITY
      Name:            CVE-2016-3720
      CVSS Score v3:   9.8
      Severity:        critical
      Description:     XML external entity (XXE) vulnerability in XmlMapper in the Data format extension for Jackson (aka jackson-dataformat-xml) allows attackers to have unspecified impact via unknown vectors.. Impacted Image File(s): /home/user/eclipse-che/tomcat/webapps/api.war:WEB-INF/lib/swagger-core-1.5.9.jar

**Comment by skabashnyuk** [comment]
Che is not affected because we override `com.fasterxml.jackson.dataformat:jackson-dataformat-xml` https://github.com/eclipse/che/blob/7035a9d2115054178628db25b2b32c4731eabb5c/pom.xml#L487-L490 to  https://github.com/eclipse/che/blob/7035a9d2115054178628db25b2b32c4731eabb5c/pom.xml#L52 2.10.3.
CVE-2016-3720 is about 2.7.4.

**Comment by skabashnyuk** [comment]
Anyway, I believe it's a good time to get 1.5.x or 1.6.x  swagger

**Comment by skabashnyuk** [comment]
Explained and upgraded.
