### ISSUE TITLE
Clipboard of IDEA Che Editor should share the content with the local system clipboard

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19669]
### Is your task related to a problem? Please describe.
In the IDEA Che Editor, when I try to copy any content to the clipboard it's not possible to paste it on the local system.

### Describe the solution you'd like
The IDEA Che Editor clipboard should share the content with the local system clipboard.

### Additional context
When copying text content inside the IDEA Che Editor, there's an error in the browser's console:
`
[ERROR] :: ServerEventsProcessor :: Error writing clipboard: NotAllowedError: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
`

There's some info is provided in the doc https://jetbrains.github.io/projector-client/mkdocs/latest/ij_user_guide/accessing/#incomplete-clipboard-synchronization

This issue is part of the epic #19596

#### Related upstream issues
1. [PRJ-355 Projector launcher not supporting paste from outside IDE](https://youtrack.jetbrains.com/issue/PRJ-355)
2. [PRJ-189 Must enter paste twice when pasting external clipboard content](https://youtrack.jetbrains.com/issue/PRJ-189)

**Comment by azatsarynnyy** [comment]
Status update, after talking with Vlad.
After investigating this issue, it turned out that it's not a problem of an incorrect running the Projector on Che side, but it's actually a problem of the Projector itself. To move forward with this issue it requires digging into the Projector sources. That's a Kotlin code where we have no expertise. So, it will require much more time during the next several sprints. 
@vzhukovs please provide more technical details once you have them.

**Comment by vzhukovs** [comment]
Yep, the main reason of stuck on this issue is the wrong behaviour clipboard, especially on the server side of Projector framework. As far as full support of clipboard requires secure browser context, this appears in that Projector Client needs to be opened from HTTPS connection. This problem has been resolved. But, there are a few limitations in Projector itself, that described in official docs: https://jetbrains.github.io/projector-client/mkdocs/latest/ij_user_guide/accessing/#incomplete-clipboard-synchronization

Also, there are a few issues registered in upstream, that require not easy solution to fix them in upstream:

1. [PRJ-355 Projector launcher not supporting paste from outside IDE](https://youtrack.jetbrains.com/issue/PRJ-355)
2. [PRJ-189 Must enter paste twice when pasting external clipboard content](https://youtrack.jetbrains.com/issue/PRJ-189)

What issues are appeared during testing. When we try to copy text from editor, the selected text goes from editor _copy action_ to the system clipboard (in the container), then this clipboard syncs with the mechanism which sends events through the websocket to the client to "copy" the container clipboard content into browser ones. This part works well, but when we tries to paste some text again, into editor, not moving the cursor to that selected region, the text is not pasted and event is not generated to the Projector server side (method [handleClipboardChange](https://github.com/JetBrains/projector-client/blob/master/projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/input/InputController.kt#L244-L250) on Projector Client fires, but from the Projector Server [ClientClipboardEvent](https://github.com/JetBrains/projector-server/blob/master/projector-server/src/main/kotlin/org/jetbrains/projector/server/ProjectorServer.kt#L386-L405) is not handled), but when we try to change the cursor position, text can be pasted w/o problem. This is described on the following screencast:

https://user-images.githubusercontent.com/1968177/121529552-2fc4b580-ca05-11eb-836e-5d418200b1fb.mov

Tried approaches:

1. Use https configuration provided in FAQ https://github.com/JetBrains/projector-docker#faq to see how clipboard works on localhost, the result was the same as described above.
2. Tried to apply attributes to iframe `allow="clipboard-read; clipboard-write"` in dashboard page. No luck.
3. Debug the flow how of handling `paste` event. Client side works as expected, but for some reason, event not fires to the server side. As far as all source code written in Kotlin (client side in Kotlin -> JS) this took some time to see what happens under the hood. From what I saw on the instance run on localhost, every event sent to the server, but in the cloud, under https it is tricky to debug this code.

Possible solution, that needs to be checked is to setup timer, that watches clipboard change on the Projector Client (browser part) and pushes the changed content to the Projector Server.

**Comment by azatsarynnyy** [comment]
Thanks Vlad! Currently, we're postponing work on this issue until we finish the productization for CRW https://issues.redhat.com/browse/CRW-1358.

**Comment by vzhukovs** [comment]
> Thanks Vlad! Currently, we're postponing work on this issue until we finish the productization for CRW https://issues.redhat.com/browse/CRW-1358.

Got it

**Comment by vzhukovs** [comment]
Issue doesn't reproduce anymore. Checked on the workspaces.openshift.com with the following devfile:
```yaml
metadata:
  name: che-idea
components:
  - type: cheEditor
    reference: 'https://raw.githubusercontent.com/che-incubator/jetbrains-editor-images/meta/che-idea/next/2020.3.3.meta.yaml'
    alias: che-idea
apiVersion: 1.0.0
```

**Comment by Mbd06b** [comment]
I seem to be having this problem.

**Comment by azatsarynnyy** [comment]
I've just tested it on 7.78.0-next where I don't see the problem with the clipboard:

https://github.com/eclipse/che/assets/1636395/9b42ceec-e1cb-4037-ad94-a26a368d76ad

@Mbd06b could you please share a Devfile to reproduce the problem?

**Comment by Mbd06b** [comment]
> I've just tested it on 7.78.0-next where I don't see the problem with the clipboard:
> 
>  Screen.Recording.2023-11-15.at.11.25.27.mov 
> @Mbd06b could you please share a Devfile to reproduce the problem?

I found the Root Cause of my issue. https://github.com/eclipse/che/issues/22609  I've opened this ticket here.
