### ISSUE TITLE
build che-theia throw error after che-theia init

### ISSUE THREAD

**Issue by zWingz** [eclipse-che/che#19897]
### Describe the bug

follow the document, 

- clone `theia`
- cd `theia`
- run `che-theia init`
- run `yarn`

it throw error 

`[webpack-cli] Error: Unknown option '--env.cdn=./cdn.json'`

![image](https://user-images.githubusercontent.com/13031838/120256289-604b7780-c2c0-11eb-9e65-e12278de4cf9.png)

### Che version

 - [+] latest

### Expected behavior
run correctly

### Screenshots

![image](https://user-images.githubusercontent.com/13031838/120289623-12e8fd80-c2f4-11eb-80dc-594cccf56842.png)

### Environment
   - [+] my computer
       - [+] macOS

**Comment by azatsarynnyy** [comment]
Hello @zWingz 
currently, Che-Theia isn't compatible with the latest Theia commit due to https://github.com/eclipse/che/issues/19804
So, before running `che-theia init`, you need to checkout to a specific commit SHA in your Theia copy. See https://github.com/eclipse-che/che-theia/blob/f0ce9a40dbdf3cd05454b465ef58477d82cdace3/build.include#L17

**Comment by azatsarynnyy** [comment]
Feef free to reopen if more help is needed.

**Comment by zWingz** [comment]
thx @azatsarynnyy
