### ISSUE TITLE
workbench.action.splitEditorLeft is not working when an editor is in the preview mode 

### ISSUE THREAD

**Issue by gautam-borkar** [eclipse-che/che#20042]
I am trying to run command `workbench.action.splitEditorLeft`. However, it seems that the command is not working.

I am running eclipse-che on chrome browser in Mac.

**Comment by RomanNikitenko** [comment]
@gautam-borkar 
Could you provide more details:

1. Are you trying to `run command workbench.action.splitEditorLeft` from a plugin side or an extension side?
2. about:
> I am running eclipse-che on chrome browser in Mac

Does the command work for you when you run the corresponding action manually (not from code)?
`F1` => `View: Split Editor Left`

**Comment by gautam-borkar** [comment]
@RomanNikitenko 
> @gautam-borkar
> Could you provide more details:
> 
> 1. Are you trying to `run command workbench.action.splitEditorLeft` from a plugin side or an extension side?

We need to run this command from within the extension. 

> 2. about:
> 
> > I am running eclipse-che on chrome browser in Mac
> 
> Does the command work for you when you run the corresponding action manually (not from code)?
> `F1` => `View: Split Editor Left`

I don't see split option when I press `F1` or `Ctrl+Shift+P`.

**Comment by RomanNikitenko** [comment]
> @RomanNikitenko
> 
> > @gautam-borkar
> > Could you provide more details:
> > 
> > 1. Are you trying to `run command workbench.action.splitEditorLeft` from a plugin side or an extension side?
> 
> We need to run this command from within the extension.
> 
> > 1. about:
> > 
> > > I am running eclipse-che on chrome browser in Mac
> > 
> > 
> > Does the command work for you when you run the corresponding action manually (not from code)?
> > `F1` => `View: Split Editor Left`
> 
> I don't see split option when I press `F1` or `Ctrl+Shift+P`.

You are right...
I checked as well:
- the command is available for running for the vanilla theia
- but it doesn't for the che-theia assembly

So, something wrong on the che-theia side, thank you for reporting the issue!

**Comment by gautam-borkar** [comment]
> What's version of che you are using?

Eclipse Che Version: 7.32.0

> Do you have an active file when you are trying F1 => View: Split Editor Left?

Steps I followed :- 
1. Open a  `.md` file and then `F1 => View: Split Editor Left`. `F1 => View: Split Editor Left` not visible.
2. Open a `app.js` file  and then `F1 => View: Split Editor Left`. `F1 => View: Split Editor Left` visible and working.
3. Open a  `.md` file and then `F1 => View: Split Editor Left`. `F1 => View: Split Editor Left` visible and working.

Is there a way to split `.md` file during #Step 1?

**Comment by RomanNikitenko** [comment]
> Is there a way to split .md file during #Step 1?

The command is available for execution when there is at least one editor.
The corresponding logic is placed on the `theia` side, [please see here](https://github.com/eclipse-theia/theia/blob/87b5b526d4aea461a54cc5f9111184b86e9be422/packages/editor/src/browser/editor-contribution.ts#L137-L138)

I think the problem is: the `.md` file is open in the preview mode. For such use case `Show All Opened Editors` displays an empty list. So, there is no `currentEditor`. You can try to open the same file NOT in preview mode - `Show All Opened Editors` and `split` actions work well.

![split_preview](https://user-images.githubusercontent.com/5676062/124077399-29e45200-da50-11eb-9c22-11679ba2a3a7.gif)

I tried to split an editor in the preview mode for VS Code and have got an empty area on the left:

![VSCode_split](https://user-images.githubusercontent.com/5676062/124078670-d6263880-da50-11eb-9333-3a8d5c3cfae3.gif)
