### ISSUE TITLE
Telemetry Plugin support in DevWorkspaces (workspaces started with the DevWorkspace engine)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20090]
### Is your task related to a problem? Please describe.
As part of this task, we need to make sure that the telemetry plugin that is possible to enable for Che 7 workspaces can be re-used, or need to be adapted,  for the DevWorkspaces - https://www.eclipse.org/che/docs/che-7/extensions/telemetry/

### Describe the solution you'd like
It should be possible to enable telemetry plugin for all DevWorkspaces running on a cluster.
Currently, in Che 7 plugin the can be enabled via 

```
spec:
  server:
    customCheProperties:
      CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS: 'eclipse/che-machine-exec-plugin/7.32.0,https://your-web-server/meta.yaml'
```

### Describe alternatives you've considered
N/A

### Additional context
telemetry -  https://www.eclipse.org/che/docs/che-7/extensions/telemetry/
Devfile v2 and IDE plug-ins - https://che.eclipseprojects.io/2021/06/23/@florent.benoit-devfile-v2-and-ide-plug-ins.html

**Comment by ibuziuk** [comment]
@sleshchenko I have created this issue in order to start the discussion regarding telemetry for the new type of workspaces. Basically, before the DevWorkspace becomes a default engine we need to make sure that the telemetry plugin can be enabled for this type of workspace. In case you already have some input on the telemetry https://www.eclipse.org/che/docs/che-7/extensions/telemetry/ for DevWorskapce, please share it in the issue

**Comment by amisevsk** [comment]
Is there a sample (testing) meta.yaml or similar for the telemetry plugin? If there is, then I can help in preparing a devfile 2.0-formatted version of it (as a DevWorkspaceTemplate CR), which we can use to start testing telemetry in DevWorkspaces. 

A URL that serves the DWT maps fairly nicely onto how plugins are defined for DevWorkspaces. For example, it's possible to add the Che-Theia editor to a DevWorkspace using the yaml below:

```yaml
spec:
  template:
    components:
      - name: theia
        plugin:
          uri: https://che-plugin-registry-main.surge.sh/v3/plugins/eclipse/che-theia/next/devfile.yaml
```

a similar approach could be used to get the telemetry plugin.

**Comment by sleshchenko** [comment]
The current blocker for this to make it live - provision telemetry plugin info as an environment variable into all other containers since devfile 2.x spec does not provide such an ability.
Possible ways:
1. using variable mechanism from devfile 2.x spec.

**pros:**
- it's mechanism from devfile 2.x spec;

**cons:**
- all components which needs telemetry info, should be adapted to:
	- be ready that value can be empty;
	- inject it into their containers with using of variable;
2. introduce a special attribute on devworkspace level, which would behave as workspaceEnv from devfile 1.x, if it's present in devfile - it's propagated to all the containers of dev workspace;

**pros:**
- Che components do not need to be adapted;

**cons:**
- it's devworkspace specific feature we may introduce while it may make sense to keep close to devfile 2.x as much as possible.

@amisevsk please review and let me know if there is a place for inaccuracy or I missed anything.

**Comment by sleshchenko** [comment]
it's done from DWO point of view.
Now dashboard needs to support default plugin from URL and maybe should provision it for existing DW instances?

**Comment by sleshchenko** [comment]
Just to clarify and verify it's good enough:
- with Che Server, it is Che Server that provisions telemetry plugin and there was not way for users to disable it;
- with DevWorkspaces, it's going to be Dashboard (see https://github.com/eclipse-che/blog/blob/main/assets/img/devfile-v2-and-ide-plugins/devfile2-workflow.png) and users may access OpenShift cluster and modify DevWorkspace/DevWorkspaceTemplates there. Dashboard may try to recover the state when it detects the missing plugin, but users are able to start/stop DevWorkspaces without dashboard at all.

@ibuziuk please confirm that it's OK that users may do tricks to disable telemetry plugin for concrete DevWorkspace instances for some time.

**Comment by ibuziuk** [comment]
we discussed ^ with @l0rd  on the cabal call. Basically, this is fine if a user explicitly disables telemetry on the DevWorkspace level by manipulating k8s objects. 

@sleshchenko could you please clarify who is working on the support default plugin from URL + provisioning the plugin for all existing DW instances?

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by ibuziuk** [comment]
> Will the outcome require any changes to the relevant content of the Installation Guide or Administration Guide or End-user Guide?

@max-cx yes, plus we will need to document the new telemetry mechanism in https://www.eclipse.org/che/docs/che-7/extensions/telemetry/

Discussed the implementation details with @olexii4 and @akurinnoy 
The proposal is the following:

1. introduce a new property in CRD 'defaultPlugins' which could contain plugin id references from the registry or raw links to the plugin yaml e.g.
```
  devWorkspace:
    enable: true
    defaultPlugins: github/vscode-pull-request-github/latest, https://your-web-server/meta.yaml
```
in this case, two plugins defined in the `defaultPlugins` will be injected in every single devWorkspace started from UD.

2. `dashboard-backend` is able to get the `defaultPlugins` property and pass it to `dashboard-frontend`
3. `dashboard-frontend` injects the list of default plugins during DW / DWT creation - https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts#L237

@amisevsk @l0rd wdyt?

**Comment by benoitf** [comment]
AFAIK all meta.yaml will. be removed from plugin registry once we switch to DevWorkspace.
so you should not rely on meta.yaml

**Comment by ibuziuk** [comment]
yeah, good point - we need to reference URL with the device 2.0 formatted version, instead of meta.yaml
plugins ids e.g. `github/vscode-pull-request-github/latest` should be still ok to use as references, right?

**Comment by l0rd** [comment]
@ibuziuk I am ok with this approach but consider a couple of things:

1. `devWorkspace` section in the CRD should disappear because everything will be devWorkspace
2. The default plugins will depend on the editor, so maybe it would be better 

So maybe something like 

```yaml
  server:
    workspacesDefaultPlugins:
      - editor: 'che-theia'
        plugins: ['github/vscode-pull-request-github/latest', ...]
      - editor: 'vscode'
        plugins: ...  
```

**Comment by dkwon17** [comment]
Hello, after a discussion with @benoitf , the default plugins that are specified using a v2 devfile uri can be added to new devworkspaces by creating a devworkspace template from the v2 devfile, and referencing the template on newly created devworkspaces.

The devworkspace templates should be managed on the che-operator side, is that right? Every time the CR is updated with new default plugins, the devworkspace templates would be created accordingly by the che-operator? 

Also, should the default plugins be also injected on workspace start too, instead of only on workspace create?

**Comment by amisevsk** [comment]
For managing default plugin templates, we can do what the Web Terminal Operator does in order to avoid maintaining DWTs across the cluster. If we create DevWorkspaceTemplates in a known namespace (WTO uses its current namespace) and add the annotation
```yaml
controller.devfile.io/allow-import-from: "*"
```
then these DWTs can be used in any workspace on the cluster via
```yaml
spec:
  template:
    components:
      - name: my-default-plugin
        plugin:
          kubernetes:
            name: k8s-dwt-object-name
            namespace: k8s-dwt-namespace
```

**Comment by benoitf** [comment]
moving issue to 7.42 milestone as this issue is part of the endgame

**Comment by l0rd** [comment]
Moving to 7.44 as 7.43 has been released.

**Comment by ibuziuk** [comment]
@dkwon17 going to close the issue since the initial plugin is contributed to the https://github.com/che-incubator/devworkspace-telemetry-woopra-plugin

Documentation is tracked as part of the https://github.com/che-incubator/devworkspace-telemetry-woopra-plugin

**Comment by dkwon17** [comment]
@l0rd , yes, we don't need to backport anything.
