### ISSUE TITLE
As a user, I want to have a possibility to quickly switch from User Dashboard to the cluster Web UI

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20106]
### Is your task related to a problem? Please describe.
Currently, it is not possible to switch from the User Dashboard to the k8s / OpenShift Web UI.
User needs to know the cluster URL and explicitly navigate to it.
 
### Describe the solution you'd like
As a user, I want to have the possibility to quickly switch from User Dashboard to the cluster console Web UI e.g. from the user menu or a dedicated button:

![image](https://user-images.githubusercontent.com/1461122/124922851-32adc880-dffa-11eb-8f3e-80cbd7ab9c9a.png)

### Describe alternatives you've considered
N/A

### Additional context
OpenShift devconsole provides a ConsoleLink for navigating to Eclipse Che / CodeReady Workspaces.
 Eclipse Che / CodeReady Workspaces should provide a similar mechanism for navigating from the Dashboard to the cluster for the proper cross-linking between the IDE & cluster.

### Release Notes Text

Title: Added a link to the OpenShift console from Che dashboard

**Comment by parvathyvr** [comment]
In Openshift since we already have the 'App launcher icon' -<img width="36" alt="app launcher icon" src="https://user-images.githubusercontent.com/33114242/130094497-b82e6665-cec6-4a65-8251-862662a5a3d4.png">
 as a place to navigate to other applications in the masthead,we could introduce the same icon to the CRW masthead.When the user clicks on it we could show them the cluster they could navigate to.
 
 Sample screen from Devsandbox OSD cluster how we use the 'App launcher' is below:
 
<img width="1427" alt="DevSandbox-OSD" src="https://user-images.githubusercontent.com/33114242/130094103-c19e02c9-3ece-4073-8c79-9574ff12aa6b.png">

Sample mock up with 'App launcher icon' introduced in CRW masthead and the associated menu shown below:
![#20106 CRW Masthead](https://user-images.githubusercontent.com/33114242/130094202-a7f9e18e-2584-459d-bfc9-c3efe719d8e3.png)

**Comment by nickboldt** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-2554
