### ISSUE TITLE
REST Service on the Che server-side that will manage user secrets

### ISSUE THREAD

**Issue by disaster37** [eclipse-che/che#20222]
### Is your enhancement related to a problem? Please describe.
Some che users need to have some secrets on personal workspace. Secrets can be:
 - github / SCM token
 - files that contain secrets
 - Environnment variables

Eclipse CHE provide some function to handle this. All of them consume existings secrets from user namespace on K8s (with some labels/annotations).

The problem is that major of user don't have direct access on kubernetes (or knowledge) to create this secrets.
Moreover, is not really user friendly to know all annotations/labels needed (depend of why we want).

### Describe the solution you'd like
Create user secrets on k8s from chectl (like we can manage workspace) and/or from Eclpise Che UI.
This wrapper must handle the right labels/annotions needed (secret as env, secret as file, secret as github token, etc ...)

To do that, we need some new api to handle secrets from Eclpise che server.

**Comment by sleshchenko** [comment]
> The problem is that major of user don't have direct access on kubernetes

If it's the case, it's not going to work since we're going to require user's identity with which we'll work for most for K8s Objects.

> Create user secrets on k8s from chectl

chectl even now should be able to do it after logging against K8s/OS cluster.

> Create user secrets on k8s from from Eclpise Che UI.

It's what we'll have even without additional API on Che Server side.
Che Dashboard will have a backend to access k8s API and provides UI for all the supported secrets/types and annotates/labels objects properly. No ETA yet
Could you clarify which kind of secrets you need most?

**Comment by disaster37** [comment]
We need this:
  - https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/
  - https://www.eclipse.org/che/docs/che-7/end-user-guide/authenticating-on-scm-server-with-a-personal-access-token/

That I look, eclipse che use internal Service account `che` to create some k8s objects. I have thinking about use the same way to create personal secrets from chectl / UI. User auth on che server, and che server (via api), create, delete, get/list secrets from user namespace...
