### ISSUE TITLE
Unable to start devworkspace with sample Java spring boot

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20271]
### Describe the bug

Unable to start devworkspace with sample

### Che version

7.34@latest

### Steps to reproduce

1. Try to start a devworkspace with sample.
check that it's created but then error is shown

### Expected behavior

DevWorkspace is created and started

### Runtime

OpenShift

### Screenshots

![Screenshot_20210806_174240](https://user-images.githubusercontent.com/5887312/128540373-b47bafda-d296-4f7a-a0dc-67156a29d9d3.png)

### Installation method

chectl/latest, OperatorHub

### Environment

Linux

**Comment by sparkoo** [comment]
is quarkus sample working? https://github.com/eclipse/che/issues/20211

**Comment by sleshchenko** [comment]
@sparkoo quarkus is working but spring boot does not.

**Comment by sparkoo** [comment]
> @sparkoo quarkus is working but spring boot does not.

yes, see https://github.com/eclipse/che/issues/20211

**Comment by sleshchenko** [comment]
In anycase, error must be clearer )

**Comment by benoitf** [comment]
should be fixed by https://github.com/eclipse-che/che-dashboard/pull/321

Axios is returning JSON object instead of a raw content when finding out url is providing JSON.

It's working in Quarkus sample because the file has comments (JSONC and not JSON compliant) so JSON.parse fail on it and return raw content.

While I've fixed the bug with related PR I've also added comments in petclinic sample so it should work even without the fix in dashboard right now
https://github.com/che-samples/java-spring-petclinic/pull/1
