### ISSUE TITLE
Question: WEB UI Authentication

### ISSUE THREAD

**Issue by romans127** [eclipse-che/che#2028]
Is it possible to have authentication to access the WEB UI. 

Currently i've installed CHE on my server via docker and It appears that anyone that finds the url will be able to access the site. I'm wondering if there is a known way to lock this down and force a username and password to proceed or accounts.

**Comment by TylerJewell** [comment]
@rwatts3 - my company, codenvy, makes an enterprise version of Che that includes authentication, permission controls, and so on. It's got a fair source 5 license, which lets you use it for free up to five people.

Others with che have started to use nginx or other reverse proxies, such as traefik, to setup authenticated access to the user dashboard.

We have not put authentication into che itself because of the complexity of the problem.  In order to lock down access, we have to lock down the user dashboard AND each workspace.  And the workspace is its own running system with servers inside of it, such as web terminal and SSH.  Each one of those surface area points have to be locked down and permissions enforced.  Codenvy depends upon a user database and HA proxy to do a lot of this work, and we have not wanted to introduce this complexity into Che.

**Comment by romans127** [comment]
Thank you Tyler. It was my understanding that codenvy only allows for 20
hours of development time ?
I would be the only person developing so it would only be 1 account.

**Comment by TylerJewell** [comment]
Codenvy.com has limits for users, yes. But I was talking about Codenvy Enterprise, which is a more advanced version of Che that you can install anywhere.  See: docs.codenvy.com.  That version has fair source license and free for 5 users.  You can set up a system of your own on a server somewhere.  It's got more heft to it, but it is totally locked down.

**Comment by ghost** [comment]
@rwatts3 http://codenvy.readme.io/docs/installation you may give it a try right away

**Comment by JamesDrummond** [comment]
@rwatts3 You can also provide firewall definitions to only allow certain ipaddress to access the che server/ports for minimal "lock down". This is not done through che but can be done in the operating system system running che server.
