### ISSUE TITLE
Usage of JWT token

### ISSUE THREAD

**Issue by sgraband** [eclipse-che/che#20351]
### Summary

In order to be able to distinguish between different user groups inside of a Che workspace, we would like to be able to retrieve user rules/permissions from an (external) keycloak instance. We already found out about the CHE_MACHINE_TOKEN environment variable, which contains a JWT-Token for the authenticated user. However, the usage of this token is not really clear to us.

Can this token only be used to retrieve information from the Che API? Or can it also be used to retrieve information from the keycloak instance? This way we could trigger the REST API of keycloak to get the needed information.

Thanks in advance.

**Comment by skabashnyuk** [comment]
Hello.


>Can this token only be used to retrieve information from the Che API?

Yes. But only part of it see more https://github.com/eclipse-che/che-server/blob/fa87ca07728dd57c53d88ace6a059cb9d92d8e24/multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java#L49-L78


> Or can it also be used to retrieve information from the keycloak instance?

One of the main ideas of machine token is to distinguish it from keycloak and limit it to the pair user-workspace.

**Comment by sgraband** [comment]
Thanks for the quick clarification @skabashnyuk!

In your opinion what would be the easiest way to retrieve information from keycloak inside a workspace? Is there any way to get access to the che user that has started the workspace?

**Comment by skabashnyuk** [comment]
>In your opinion what would be the easiest way to retrieve information from keycloak inside a workspace? Is there any way to get access to the che user that has started the workspace?

It would be nice to understand the problem you are trying to solve first.

FYI. In the next releases, Keycloak can become an optional element in context of https://github.com/eclipse/che/issues/19182.

**Comment by sgraband** [comment]
We would need it in the theia-container to retrieve the information using an extension/plugin.

**Comment by skabashnyuk** [comment]
I would say you should create a custom controller/operator that will have access to keycloak's user groups and reconcile that information to user's namespaces as a file https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/#mounting-a-secret-as-a-file-into-a-workspace-container_che


CC @l0rd @benoitf

**Comment by l0rd** [comment]
I would like to learn more about the use case @sgraband. What's your extension for? What user information does it require that is not availble from the che-server API? In the short term [Keycloak won't be an hard dependency for Che anymore](https://github.com/eclipse/che/issues/19182), how does that affect your use case?

**Comment by planger** [comment]
Hi @l0rd, thanks for asking! I'll chime in.

We use Che as a _workspace manager for custom Theia applications_ -- typically on-premise. Usually there is a _custom dashboard or portal_ allowing users to start, stop, create, delete and open workspaces via the Che REST API. Such applications typically also involve accessing proprietary services (build servers, artifact stores, repositories, REST APIs) that require authentication.

As users usually authenticate with Keycloak when accessing the custom dashboard -- they need access to the Che REST API anyway, we were hoping that we'd be able to have access to Che's user tokens from inside of the Theia application so that we can get SSO access to other services or to create machine-to-machine tokens from it.

However, also given that Che removes the hard dependency to Keycloak, we now mostly went the route that the custom Theia application is an own oauth client at the same OIDC provider used by Che. This way, the custom Theia application can request tokens independently. As long as the same OIDC provider is used, SSO works, but of course may require a popup being opened from the users' browsers.

While this adds a bit of overhead to the custom Theia application instance of each workspace, as it needs to independently handle all the authentication tasks, I guess this is fine. Or do you foresee any plans to involve the editor getting access to Che's authenticated user token?

Removing the hard dependency to Keykloak in Che sounds like a good idea and likely wouldn't impact our use case, as long as we can wire up Che (and the custom Theia applications) with any other OIDC provider.
