### ISSUE TITLE
Adapt devfile v2 happy-path tests to verify editors and extensions functionalities

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#20385]
### Is your enhancement related to a problem? Please describe

This was initially part of this epic https://github.com/eclipse/che/issues/18668

Now that the work to support theia running vs code extensions for workspaces started using devfile v2 has been completed, the happy path test should be updated if hasn't yet.

### Describe the solution you'd like

The happy path test should use a factory link to a che-sample as https://github.com/che-samples/java-spring-petclinic/tree/devfilev2 (**branch is devfilev2**) :heavy_check_mark: 
and verify that:
- the workspace is started successfully
- the Java LS works properly

**Comment by benoitf** [comment]
some notes:

step1: replace gist with che-samples repository
step2: Add tests on language server (like it's done on devfile v1)

**Comment by dmytro-ndp** [comment]
Scope of E2E Happy path tests:
- Che Operator Happy Path tests: https://prow.ci.openshift.org/?repo=eclipse-che%2Fche-operator
- Che Theia Happy Path PR check: https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-theia-pr-check/
(TODO)

**Comment by sleshchenko** [comment]
After discussion with QE team.
Statements:
- We can't reuse devfile v1 happy path test scenario since it uses workspace created with chectl;
- We can't reuse pieces from devfile v1 happy path test since QE has conversion that test scenario must be in one file;

The plan we agreed on:
- @musienko-maxim will copy-paste everything above https://github.com/eclipse/che/blob/main/tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts#L90 into https://github.com/eclipse/che/blob/main/tests/e2e/tests/e2e_happy_path/DevWorkspaceHappyPath.spec.ts and check how it works.

Later possible action item for QE:
1. refactor tests to be able to use suites without copying-pasting;
2. or fully align Devfile v1 and Devfile v2 happy path tests;

Personally, I prefer the first a bit more since I assume at some stage we can have different features needed to be verified.

@dmytro-ndp please verify and let me now if inaccuracies present;

P.S. Also we identified the following issue that should be handled separately Centralize DevWorkspace Happy Path test https://github.com/eclipse/che/issues/20421

**Comment by dmytro-ndp** [comment]
@sleshchenko: it looks accurate, thanks for summary!

**Comment by rhopp** [comment]
> refactor tests to be able to use suites without copying-pasting;

As for this point - we already have something like this. It's being adapted by Devfile tests, but HappyPath test (devfile.v1) is not using this.
We have generalized (and parameterized) test steps for common workspace verification in folder `testsLibrary`. You can see how it's used for example here: https://github.com/eclipse/che/blob/main/tests/e2e/tests/devfiles/JavaMaven.spec.ts#L50-L60

**Comment by musienko-maxim** [comment]
The steps until **Display source code changes in the running application** and **Validation of debug functionality** were adapted. It was merged in PR: https://github.com/eclipse/che/pull/20476
Currently we adpting: **Display source code changes in the running application**, **Validation of debug functionality** and

**Comment by sleshchenko** [comment]
`Validation of debug functionality` can't be added due https://github.com/eclipse/che/issues/20536

it will be added into happy path test along with `Display source code changes in the running application` in the scope of https://github.com/eclipse/che/issues/20537
