### ISSUE TITLE
Can't load project types outside localhost

### ISSUE THREAD

**Issue by Klentzy12** [eclipse-che/che#2058]
`Error: Can't load project types: Error at Object.window.IDE.eventHandlers.initializationFailed (http://*server_public_ip*/che/default?uid=188643:39:27) at urb (_app-0.js:1936:168)    at Irb (_app-0.js:1942:57)    at _.Bp (_app-0.js:4115:319)    at eval (_app-0.js:938:86)`

Happens with yatta install and codeenvy wizard - works on the windows server itself, as soon as I connect to it from my computer, it can't get the project types anymore. Tried all solutions suggested so far in the issues section.

**Comment by JamesDrummond** [comment]
@Klentzy12 Seems like external ports are being blocked or you maybe didn't provide an `--remote:<external-ip>` when launching. Can fill out the following so we can better diagnose your problem?

[Short description of problem here]

**Reproduction Steps:**
1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Che version:**    [Enter Che version here]  
**OS and version:** [Enter OS name and version here]  
**Docker version:** [Enter your Docker version here `docker version` on CLI]  
**Che install:**    [Vagrant, Docker container, server (zip), Bitnami, Yatta, or Codenvy?]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by ghost** [comment]
@Klentzy12 that is most certainly a remote Che issue. Please, run it with -r:$IP parameter where $IP is IP address of a server that is running Che. Also, take note that the ephemeral port range should be accessible for inbound connections.

**Comment by TylerJewell** [comment]
@Klentzy12 - also we are just about to ship a new form of launcher that addresses the remote management a lot smoother.  You can try the syntax with 4.6.1 and Docker for Windows.  https://eclipse-che.readme.io/docs/usage-docker#

**Comment by ghost** [comment]
@TylerJewell not entirely. When you are on windows, you need to make sure your VM has an external IP (not just your localhost). `-r` works for Linux where Docker runs in the same environment as the server. With Windows, even if you reach the server by an external IP it does not mean you necessarily reach Docker that runs either in VirtualBox or Hyper-V

**Comment by JamesDrummond** [comment]
@eivantsov Docker runs natively now in windows for 4.6.1. Does Virtualbox or Hyper-V effect docker or are you talking about the alternate setups?

**Comment by JamesDrummond** [comment]
@eivantsov Sorry just installed docker for Windows. Docker either is on virtualbox or hyper-v.

**Comment by TylerJewell** [comment]
@eivantsov - the new docker launcher has logic inside to handle the differences between virtualbox and docker for windows - and makes sure the _right_ IP address is provided with the --remote:<ip> command.  So this is why I would like to encourage @Klentzy12 to give this a try first.  It's a good possibility that any networking issue is then resolved for him.

**Comment by ghost** [comment]
@TylerJewell it does not matter if it is VBox or Hyper-V or any other VM. Its IP HAS to be reachable in the network. This is the only problem here, and che-launcher does not resolve it in any way.

Solutions are:
- make VM IP externally accessible
- forward traffic from localhost to VM for a range of ports (the beginning of the ephemeral port range)

**Comment by TylerJewell** [comment]
There hasn't been a response from OP in a month - so closing the issue.
