### ISSUE TITLE
How do I write a custom recipe that uses scripts?

### ISSUE THREAD

**Issue by linuxd3v** [eclipse-che/che#2084]
My dockerfile looks like example below.  
obviously when I run it locally on my host where I have all of the dependencies -> everything works.
But when I paste that as a custom recipe -> it predictably fails to find dependencies.
How would I rewrite my dockerfile to fix this?

> FROM ubuntu:trusty
> # Add image configuration and scripts
> 
> COPY . /tmp/docker
> WORKDIR /tmp/docker
> RUN /tmp/docker/installer.sh
> # this should start apache on docker run.
> 
> CMD ["/tmp/docker/run.sh"]
> 
> EXPOSE 80

**Comment by TylerJewell** [comment]
You have a couple choices:
1: Some people pre-build their images and then host them on dockerhub.  So then your custom workspace / stack recipe is just "FROM myorg/image".  There is nothing else to do at that point.  And since you build it locally, it will include your local files.

2: Have the files hosted on a server, or at github, and then you can have them curl'd in with a RUN command inside of the Dockerfile.  So that when we build the file, we do not depend upon any other local files.

**Comment by linuxd3v** [comment]
@TylerJewell 

> 1: Some people pre-build their images and then host them on dockerhub. So then your custom workspace / stack recipe is just "FROM myorg/image". There is nothing else to do at that point. And since you build it locally, it will include your local files.

Awesome! Yeah - that's exactly what I do. Those are in private dockers though -> will it still work?

**Comment by TylerJewell** [comment]
Yeah - we support access to private docker registries.  Shouldn't be a problem.  As long as your other issue gets resolved where we retain those credentials permanently :)

**Comment by ghost** [comment]
@loganto since we use Docker API but not Docker CLI to build and run images, there's no build context that is sent to Docker daemon when the image is built.
