### ISSUE TITLE
Docker out of docker

### ISSUE THREAD

**Issue by jgroom33** [eclipse-che/che#2086]
The process for our dev environment requires a docker build.

It might be beneficial to execute that from the ide without embedding the docker daemon in the stack.

Would it be possible to allow command execution using the host daemon?

**Comment by ddementieva** [comment]
@jgroom33 There are several options:
1. Export DOCKER_HOST variable in your container: `ENV DOCKER_HOST=tcp://$IP:2375`, where $IP is your local machine IP. Set this environment variable in your custom recipe.
   You need to make your docker daemon listens on tcp. Add the following to your Docker configuration file (on Ubuntu it's `/etc/default/docker`):
   `DOCKER_OPTS=" -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"`
   Verify that the Docker API is responding at: http://$IP:2375/containers/json
2. Mount /var/run/docker.sock

In /conf/che.properties add the following:
`machine.server.extra.volume=/var/run/docker.sock:/var/run/docker.sock`
You may need to set up permissions for /var/run/docker.sock on the host to let a user in the container use this file:
`sudo chmod 777 /var/run/docker.sock`

**Comment by TylerJewell** [comment]
@jgroom33 - in the 4.7 release coming out tomorrow, we have a new codenvy/alpine_jdk8 image that has Docker client built into it. You can start your che with the property of `machine.server.extra.volume=/var/run/docker.sock:/var/run/docker.sock` so that your worksapces can gain access to your host daemon.  We are using this to provide a che-in-che stack so that you can compile and run Che within a Che workspace.  

Also, in a pull request that is about to get merged, you can specify custom che.properties with an environment variable.  So when using the Che CLI you can set `CHE_PROPERTY_machine_server_extra_volume=/var/run/docker.sock:/var/run/docker.sock` and the CLI will create a temporary che.properties file that uses that value to simplify the startup configuration.

**Comment by davidwindell** [comment]
Just to add for anyone coming across this via Google (like me!)

The correct variable is now `che.workspace.volume` OR `CHE_WORKSPACE_VOLUME`

**Comment by davidwindell** [comment]
@TylerJewell docs here need updating http://www.eclipse.org/che/docs/ide/docker/index.html#mount-docker-socket
