### ISSUE TITLE
Better DTO Generation

### ISSUE THREAD

**Issue by tareksha** [eclipse-che/che#210]
Hi,

In this thread I would like to address the architectural issues of the current approach for providing DTO functionality in Che.

The current approach relies on reflection which requires a fully compiled DTO definition interfaces before generating the DTO implementations. This forces Che extensions that generate DTOs to explicitly add sources re-compile during the maven build process in order to get consistent results. The result is a complex non-standard configuration and dependencies in pom.xml.

A better approach is using Java Annotation Processing which allows integrating into the compilation phase seamlessly with minimal configuration. APT also provides native methods for adding resources to the compilation, without any need for ad-hoc maven configurations.

Another major issue is the code generation method. Currently the DTO generation generates code by appending hundreds of string token. This is very hazardous and hard to maintain/develop. The standard way for code generation is using text templating engines such as StringTemplate or FreeMarker. Such tools allow defining the code templates externally and simplify the operation greatly.

I have a POC for a DTO processor that generates sever code. Many feature are already supported well and some tests with example use are included
https://github.com/tareqhs/che-core/tree/dto_processor
This change is required in the dependency mangement
https://github.com/tareqhs/che-depmgt/tree/st4_version

Please review my suggestion and provide any insights,
thank you

**Comment by TylerJewell** [comment]
@skabashnyuk - was this discussed in the roadmap meeting?

**Comment by slemeur** [comment]
Yes it was and it is taken in the current sprint: IDEX-4273

**Comment by tareksha** [comment]
Hi @slemeur , can you please share more information about item IDEX-4273? is it connected to my contribution?

**Comment by TylerJewell** [comment]
@slemeur @skabashnyuk - I see that there are two open items for better DTO generation that are open on Codenvy's systems and nothing included in GitHub.  What is the status of this improvement?  @tareqhs - were your pull requests accepted?

**Comment by tareqhs** [comment]
hi @TylerJewell ,

I did not open a pull request due to lack of technical feedback. The change itself is still there and open for discussions and pull request evaluation.

BTW, since then I moved to a method that requires no compile-time configuration at all and relies on generating bytecode during runtime.

**Comment by tareksha** [comment]
hi @TylerJewell , I did not open a pull request due to lack of technical feedback. The change itself is still there and open for discussions and pull request evaluation.

**Comment by TylerJewell** [comment]
@skabashnyuk - please have someone review & comment in the next sprint.

**Comment by TylerJewell** [comment]
@tareqhs @skabashnyuk - this issue is now officially the oldest one for Che!   What is our plan here?

**Comment by skabashnyuk** [comment]
We made our analysis and  concluded that:

The basic idea of the @tareqhs  request pretty nice. Use annotation processor and string templates instead of current realization carries several positive moments makes the process of generating a more scalable, more obvious(due templates), easier to support(do not need custom Maven plugins). However, since the proposed implementation is not completed (no client-side templates) to the end and it is outdated. Also we need to bring the general idea and make our own implementation this issue.

List of issues 
- [ ] Rework dto generator with string templates https://github.com/eclipse/che/issues/2242
- [ ] Get rid of custom maven plugin in dto generator https://github.com/eclipse/che/issues/2243

**Comment by TylerJewell** [comment]
@skabashnyuk - is this still in your backlog?  Wondering what the prioirty of this should be relative to your other backlog items.  Will you offer a suggestion?

**Comment by skabashnyuk** [comment]
we have this pr in our current sprint backlog.

**Comment by TylerJewell** [comment]
Crosslinked - is this the one:
https://github.com/eclipse/che/pull/3103

**Comment by skabashnyuk** [comment]
Sorry I was wrong. We are working on #3103
