### ISSUE TITLE
Eclipse che doesn't read the workspaces created when executed as a container

### ISSUE THREAD

**Issue by Alexpud** [eclipse-che/che#2120]
Hi,
I am running eclipse che as a container on ubuntu, i manage to start workspaces and run project without a problem. When i restart the container, i can't see the previously created workspaces, but when i create and execute a new  workspace on the same stack as the one i created the previous projects, i can see and execute the previous projects.
And the same problem with workspace happen after i restart the container again.

The command that i executed was this one:

docker run --net=host --name $1 -v $CHE_FILES_PATH/workspaces:/home/user/che/workspaces -v $CHE_FILES_PATH/storage:/home/user/che/storage -v $CHE_FILES_PATH/conf:/home/user/che/conf -v $CHE_FILES_PATH/lib:/home/user/che/lib-copy -v /var/run/docker.sock:/var/run/docker.sock -v $CHE_FILES_PATH/conf-tomcat:/home/user/che/tomcat/conf -v $CHE_FILES_PATH/bin:/home/user/che/bin codenvy/che

**Comment by TylerJewell** [comment]
This run syntaxis now deprecated.  Please use the new Che launcher - which has instructions for how to mount folders for different OS.  Please note that if you are using boot2docker on windows, then due to limitations of virtualbox, che's saving of files from inside the VM to your windows host can only take place in a limited location buried underneath %userprofile%.

If there is any way that you can do docker for windows - this limitation does not exist with it.
https://eclipse-che.readme.io/docs/usage-docker

**Comment by Alexpud** [comment]
Oh i see, thanks. 
A question:  is it possible to create multiple instances of che as a container using the che launcher?

**Comment by TylerJewell** [comment]
Yes - but not easily.  It will be easier once this pull request is merged. 
https://github.com/eclipse/che/pull/2119

Today, the che-launcher always assumes that the che-server container is named `che-server`.  So if you change the port and then tell the launcher to start che, you will get a Docker error message saying that `che-server` exists.  The pull request lets you set the name of the che-server instance with an environment variable so that you can change variable and then manage different che instances.

In the meantime, after you start a che server you can use `docker rename che-server <new-name>` to avoid that conflict.  It would be better in the long run to have the concept of a che server profile that contains a collection of environment variables such as PORT and container name, and then that profile is used for start / info / stop commands.

**Comment by Alexpud** [comment]
Ok, thanks. I will look forward for the merge then!
In the meantime, i will checkout the option that you suggested.
Thanks @TylerJewell  for your time and sorry for any trouble.

**Comment by TylerJewell** [comment]
No problem.  What do you think of the problem and of the product so far?

**Comment by Alexpud** [comment]
Well the product is very good. This problem with che-launcher is not upsetting at all, since it appears to  makes easier to change configurations on che without having to create and mount files. I look forward to see how it deals with multiple instances and persistence of the workspaces and projects in it.
