### ISSUE TITLE
Rework dto generator with string templates

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#2242]
In current state our dto generator builds the objects using the string builder, but it is not effective so we should replace the current implementation on string templates for server and client dtos. Here https://github.com/tareqhs/che-core/commit/ee365e6734689696396e17bea0349a5e6bb062b8  you can see the example.

**Comment by tareksha** [comment]
Hi @skabashnyuk ,
I have a question regarding the current implementation that can be thought as incremental. Why does the DTO generator generate code that explicitly builds the JSON tree, creating individual `JsonElement` values and combining them into trees, instead of simply passing the DTO objects as-is to Gson and asking it to do all the work?

**Comment by skabashnyuk** [comment]
I think it's  just because it will be faster

**Comment by tareksha** [comment]
@skabashnyuk Gson writes JSONs using the iterative `JsonWriter` which prints text directly from the java objects, only when an actual `JsonElement` is needed a dedicated `JsonTreeWriter` is used for building a tree. So basically the generated code is actually slower than direct Gson usage. 

JSON serialization/de-serialize JSON makes up the major part (and complication) of the generated DTO code. I think this should be addressed regradless of the code generation method that is used eventually.

**Comment by tareksha** [comment]
Hi @skabashnyuk ,
please have a look at my pull request that addresses these issues
https://github.com/eclipse/che/pull/3103
