### ISSUE TITLE
Get rid of custom maven plugin in dto generator

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#2243]
There are many variants to adjust the launch of dto generator, one of them is use the  annotation processing tool that was actually asked in @tareqhs  request, so it is necessary to develop an appropriate mechanism for the generation of dto objects instead of custom maven plugin. Also see example here https://github.com/tareqhs/che-core/commit/ee365e6734689696396e17bea0349a5e6bb062b8

**Comment by tareksha** [comment]
Hi,
I can take this a step further in two possible directions:
- Use Gson mappers and factories directly instead of generating thousands of JSON tree manipulation code.
- Generate bean bytecode during runtime. This completely eliminates any compile-time requirements and leaves it to the runtime to generate class bytecode on-demand. We use this approach in several areas and it is very convenient.

**Comment by benoitf** [comment]
I'm adding to this thead about DTO that
I would generate DTO for another language : Typescript.
The idea is these Java DTO objects could be used in clients that are not based on Java but with typesafe struct.
For example, if server code is updated (like DTO) we ensure the clients is still working by using same "model"

note that it will include not only "implementation classes" but also Java DTO interface --> Typescript DTO interface

if there is a model with templates, then I may plug typescript generation as part of the generator.
I may as well use a different way (like grabbing all DTOs of Che and generating a single file) so it is more "assembly/produced artifact" than internal artifact
We should then have one TS file per project using DTOs, like one for Che, one for Codenvy, etc
