### ISSUE TITLE
Prompt is blinking

### ISSUE THREAD

**Issue by xVampiRx** [eclipse-che/che#2342]
Gif better explain problem than words: https://gyazo.com/f18f17ef67ed481603aebf45f2542ea1
Clean install of Che. Everything is default. 
Docker: 1.11.1
Che: Version :4.7.0 Revision :36311ea4c8e5402e

**Comment by TylerJewell** [comment]
Wow.  Yes thanks for providing a video.  Would have never believed that if I hadn't seen it.  Can you provide OS, browser versions as well?

Any change if you resize the tree width on the left of the terminal!

**Comment by xVampiRx** [comment]
Resize indeed resolved the problem.  Win7, chrome 52.0.2743.116 m

**Comment by JamesDrummond** [comment]
@TylerJewell Can we reproduce this to fix or do you know someone to ask to see if they could identify the possible problem?

**Comment by TylerJewell** [comment]
Unable to reproduce at this time.  Deifnitely a bug - need sto be scheduled for investigation. Scheduling depends upon whether others encounter issue.

**Comment by jc776** [comment]
I get the same issue. [http://i.imgur.com/14sDeF5.png](http://i.imgur.com/14sDeF5.png)
Unreliably caused by reopening the terminal and typing the command.
When it happens, shrinking the tree makes it one line, extending the tree has the line break, middle has the issue. The point where it changes depends on the tree size at the point of first opening the terminal.

Using Win10, Chrome, 1920x1080. My DPI/font smoothing settings are messed up, though. I'm using the 'Codenvy Beta' site, not local-host.

**Comment by ghost** [comment]
@oxplayru @TylerJewell i have seen this one with 4.7.

**Comment by vparfonov** [comment]
fixed here https://github.com/eclipse/che/issues/2353
