### ISSUE TITLE
Init git repository at workspace level

### ISSUE THREAD

**Issue by vlad-tury** [eclipse-che/che#2357]
At this moment the user is obligated to initialize the  GIT repository for every project.
This means that several projects with the same structure cannot exist in the same repo, because one will override the other.
Having multiple projects with the same structure in a repo is a common use case and should be supported.

**Reproduction Steps:**
1. Make the necessary steps to connect from Che to GitHub. Steps are provided here: https://eclipse-che.readme.io/docs/git . SSH configuration will suffice. No need for OAuth configuration
2. In a workspace create the project Test1. This should have only a src folder inside with a Main.java
3. For Test1, select from the Git menu: "Initialize repository"
4. Do the following steps: from the Git Menu:
4.1 Add to index
4.2 Commit
4.3 Push
5. Changes are pushed to the repo where the root is the "src" folder
6. Create the project Test2. This should have only a src folder inside with a Main.java as well
7. Make some changes to Main.java.
8. Repeat steps 3-4.3
9. After the code is pushed to the repo it will overwrite the src of Test1

Therefore Test1 and Test2 cannot coexist in the same repository

**Expected behavior:**
- we need a way to init the repo at a workspace level. 
- this init should propagate to all the children so that the Menu items from the Git Menu are enabled and operations such as Commit, Pull, Push, etc... are available

**Che version:**    4.6.2
**OS and version:** Windows 7
**Docker version:** 1.10.3

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
@vlad-tury - when you performed this sequence, do you recall if you had the context set to the appropriate project in the project explorer (the tree on the left panel)?  I want to see if this issue happens no matter which project is selected (ie, which project has the current context).  If the current context was Test2 and Test1 was over written, it's an issue.  If Test2 was not having the context, then the issue is about making it clearer which project has the git menu context at any point in time.

**Comment by ghost** [comment]
@vlad-tury I cannot reproduce it. 2 different projects are 2 different repos. You mentioned that you push to a remote. Should I import a project first? Or add a remote?

**Comment by vlad-tury** [comment]
@TylerJewell - when I made the Git actions on Test2, Test2 had the context
@eivantsov you do not need the import a project. You just create the project and then follow the steps I mentioned in my description. The challenge I face is that I want to push both projects to the **same** remote, i.e to the same Git repo.

When I push the first project to the remote, the project info (i.e the project name is "lost"). In the repo src is the root folder.

That is why when push to the repo a project with the same structure, Test2's src will overwrite Test1's src or there will be merge conflicts. Either way it is NOK.

Also if I add a new folder to Test2 and push it to the remote, if I do a pull on Test1 afterwards the new folder will be brought also in Test1 project.

Thank you for the support!

**Comment by ghost** [comment]
@vlad-tury Isn't this expected Git behavior? Projects have the same remote - what do you expect when you pull from a remote where you pushed a new folder?

**Comment by vlad-tury** [comment]
@eivantsov I expect to have the possibility to have multiple projects in my workspace with the same folder structure and push them to the same remote without any problems (overwriting one another). Is that possible at this moment in Eclipse Che?

**Comment by ghost** [comment]
@vlad-tury can you record a video of what you are trying to do. So far, I failed to understand the use case.

**Comment by TylerJewell** [comment]
I think that we have assumed in this model that a project can be mapped to a single remote.  But you can have two projects imported with different names pointing to the same remote.   It is just a double setup process.  You achieve your goal then no?

**Comment by TylerJewell** [comment]
I think you maybe are hoping the system would do something that it is not supposed to do.  I appreciate you showing me the graphics, so that we can explain it a bit better.

1: In the scenario that you provide, the "Test1" is the project name.  It should not show up in your git repository.  Your git repository is valid-tury/demo.  If you were to take this repository and clone it on your normal desktop it would be something like:

```
git clone http://github.com/vlad-tury/demo
# resulting folder structure would look like
/demo
  /myOwnFolder
    myOwnFile.txt
```

That is exactly what we are doing within Che, though instead of your project being named "demo" we assign the project name to the name that you give it - which is "Test1`".  To get the same thing on your local computer it would be`git clone http://github.com/vlad-tury/demo Test1`.

2: If you were starting from within Che and you had created a proejct inside of Che with some files and then wanted to push that project as a set of files into a remote repository, the behavior would be somewhat similar. Git assumes that each repository locally is in a folder.  So you would have to be in a folder first, and then can push to the remote. In Che these folders are a sub-directory of `/projects` where each folder maps to a single remote.  Git handles the details of mapping the local folder name like Test1 to the name of the remote repository.

**Comment by ghost** [comment]
@vlad-tury test1 and test2 are two different git repos, each having .git and a common remote.

If I follow your steps locally with git, I will have the same result.

**Comment by TylerJewell** [comment]
@vlad-tury - going to close this issue for now, as I think the system is performing to specification.  And that we just have to help you structure your repos the right way.
