### ISSUE TITLE
How to run a Che farm behind an nginx router

### ISSUE THREAD

**Issue by rajasekaran07** [eclipse-che/che#2383]
We are trying to create Eclipse Che for multiple user with their own che server. We tried with OpenShift but unlucky there is some known issues are there so I cant start my workspace and IDE. ref: #2368.
Hence, I am going for next option Eclipse Che farm. 
I have gone through this page: https://eclipse-che.readme.io/docs/scaling here they didnt explain how to make this setup.
Can someone tell me how to run che form behind an nginix router for multiple access.

Regards,
Raja

**Comment by ghost** [comment]
@rajasekaran07 I haven't tried to do it myself, and we do not have a step by step guide on how to do it. 

You may run multiple instances of che as docker containers on different ports, and setup redirects for nginx to forward to those ports.

**Comment by TylerJewell** [comment]
@rajasekaran07 - here is a filter of the issues where configuring nginx proxy has been discussed in the past. We would very much like it if someone could include a contribution to our docs on how they set it up for their particular configuration.  https://github.com/eclipse/che/search?q=nginx&type=Issues&utf8=%E2%9C%93.

Absent doing nginx with Che, we do want people to consider Codenvy as a single-install, securely managed system for teams and large groups of Che developers.

**Comment by rajasekaran07** [comment]
@eivantsov and @TylerJewell thanks for your valuable commands. I will try my self and let you people know the status.

**Comment by monaka** [comment]
I'm trying to build a front-end account manager for Che 4.7.2. (I'm looking forward to Codenvy's improvements but I want them just now ;-)
My PaaS farm is Deis Workflow which uses Nginx as their application routing.
So I'm using Nginx implicate.

Sometimes there have  strange behaviors like deis/router#265 (unfortunately I don't get the root cause).
But basically we can run Che behind Nginx with normal WebSocket proxy settings.

**Comment by monaka** [comment]
Probably I close to the root cause that Che behind Nginx can't run sometimes.
It will be caused in case the CPU/disk load on Docker node is not low.
I'm inspecting now.

**Comment by monaka** [comment]
In failure case, Nginx returns to my browser like this.

```
WebSocket connection to 'ws://eclipse-che.{censored}.com/api/ws/workspace1lmqf8tixwdlr03f' failed: Error during WebSocket handshake: Unexpected response code: 502
```

The exception place is `new Socket` in Angular-Websocket.

I suspect the root cause is related on the blog entry http://otiai10.hatenablog.com/entry/2013/10/10/095213 (It's written in Japanese with slang)
Shortly, Nginx returns 502 error then the endpoint is not exist.
I suspect this is a kind of timing issue.

Regardless of Che will be a single securely multi-user system, some users want to use with Nginx.
I think this issue should be fixed.
(I'm still using Che 4.7.2. It's good if it was fixed newer version...)

**Comment by monaka** [comment]
I got it. It's not by timing issue but `Host:` header in HTTP request.
/api/ws/\* in Che returns 404 without `Host: localhost`.
(But Che accepts normal HTTP request from any `Host: anywhere.everywhere.com`)

So the quick and dirty hack is adding host directive to `nginx.conf`.
The another plan is to use [nginx_ajp_module](https://github.com/yaoweibin/nginx_ajp_module). I've not used but may be work.

It may not be show stopper as workarounds available. It's better to fix Che (everrest?), IMO.

**Comment by TylerJewell** [comment]
@gazarenkov perhaps we should ask Andrey to take a look?

**Comment by monaka** [comment]
Good news. I tried with a 5.x nightly build. It was fixed the issues I commented above.

Connections in my cluster is like below. It works fine to me.

[SSO gateway (written by me in Node-http-proxy)] - [Nginx (Reverse proxy)] - [Che server]
