### ISSUE TITLE
Add authentication for accessing workspace in private cloud

### ISSUE THREAD

**Issue by amitkverma** [eclipse-che/che#2390]
Currently, anyone can access my workspace if he/she knows the IP of my workspace and they are also able to add, modify and delete. We need some authentication for users accessing workspace.

**Comment by TylerJewell** [comment]
Hi Amit.  We have no plans to add this capability.  You can consider Bitnami which provides a reverse router with some light authentication, installing your own nginx reverse router or Codenvy which provides an enterprise system with authentication for Che.

There are many issues that discuss the reasons why this is not added to Che due to the architecture complexity that you can review in the archives and in the docs.
