### ISSUE TITLE
Command for opening a file

### ISSUE THREAD

**Issue by Foorack** [eclipse-che/che#2412]
Hello
Is there a command for opening a file in the editor once you are in the environment?
Something similar to "c9 open" which would open a file or directory in the IDE.

**Comment by TylerJewell** [comment]
@Foorack - we have it on Codenvy factories - there is a syntax when it is fully hosted.  We haven't added it into Che yet - there are some challenges there around persisting the client-side state within the server-side, and then having various clients reactivate that state.

This particular request is also being tracked in this epic for work.
https://github.com/eclipse/che/issues/2266

If you don't mind, I'm going to close this issue since it is cross tracked in another currently.
