### ISSUE TITLE
consume eclipse che api from jquery/c#

### ISSUE THREAD

**Issue by worksamp** [eclipse-che/che#2475]
[Short description of problem here]
I am using bitnami eclipse che.
Now I have running eclipse che dashboard,from which i am successfully created a workspace and project.

My query is: I need to create eclipse che workspace through code.

Is there any way to create it?

**Comment by TylerJewell** [comment]
Hi. 

Yes, everything in Che is programmable through REST interfaces. In fact, the IDE, the user dashboard, and Chedir capability are all clients of the workspace REST API. I recommend that you go through the code bases for each of those areas to see where we make certain types of REST calls.  The UD is authored in JavaScript and Angular, so that will be closest to your jquery needs.

There is also our docs on our REST API
https://eclipse-che.readme.io/docs/rest-api

And you can also look at the swagger interface for the Che server and each workspace - also documented on how to do it in our docs.  If there are specific use cases that are more challenging, our docs team would like to understand those so that they can get documented into the docs.
