### ISSUE TITLE
Port Eclipse Che for POWER (ppc64le)

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2510]
I would like to be able to successfully install and run Eclipse Che on Ubuntu 16.04 running on POWER. 

So for I was able to build it from scratch (consuming the basic parts from its remote build server) and start the server without any modifications. I see that it is highly coupled with x86_64 and probably tries to use containers for this architecture - here we have the first blocker. Also I, when trying to compile the dashboard, I got issues with PhantomJS, which does not compile on POWER.

Is there any other clear visible problem that I could face on porting Che to another  #architecture? 

BTW: It is possible to request a free POWER VM at http://openpower.ic.unicamp.br/minicloud/

**Comment by benoitf** [comment]
@rpsene phantomjs is for unit test so you may skip tests or you could skip dashboard compilation as well and grab it from automatic continuous integration server.

```
mvn -pl '!dashboard' clean install
```

**Comment by TylerJewell** [comment]
Hi @rpsene.  Yes, you are correct that when Che starts itself, it depends upon a Tomcat server to run the Che server itself, and then it requires a "runtime" to operate each workspace. By default, Che uses Docker as the "runtime" provider for each workspace. This, then, requires that the Docker engine be installed on any platform where the workspace will run.  We have had some groups get Che to run on one device where Docker is not present, but then have the workspaces created on a different system where Docker is present.  But I doubt that is your objective.

So, the longer answer is that there are a couple ways to handle what you are seeking:
1: The "machine" implementation that we provide of Docker is actually an SPI.  Different machine implementations can be provided as a set of extensions. One that we did was an SSH implementation where the workspace is launched and synchronized with another server that is remotely connected over an IP address. You can provide your own implementation of machines. We don't have superb docs on how to write a custom machine, but we do have fantastic examples with SSH and Docker, so the pattern can be reused to implement one for your system.

2: Later this year, before the end of the year, we are likely to work on what we call "localhost" machines, which will be a new machine implementation that bypasses Docker and installs the workspace software directly onto the same operating system that the Che server is running on.  Effectively, it would make Che start to operate like a traditional IDE where all IDE services are installed into the host OS.  The benefit here is that it's super lightweight and should run anywhere.  The downside is that you lose workspace portability, because we use Docker to allow us to move a workspace from one location to another. We would not be able to do that anymore with localhost machines.

We don't have a firm timeframe on it yet.  We have some tracking issues on it, however.  You can see this issue. https://github.com/eclipse/che/issues/476.  It's also a bullet in our 6-9 month roadmap.  https://github.com/eclipse/che/wiki/Roadmap.

**Comment by rpsene** [comment]
@TylerJewell @benoitf we are looking at getting Che on Power again. Is there anything you consider very complicated to be ported/enabled to a new architecture? I've seen some arm7 references in the source code and other several references to amd64, what replaced phantomjs that is now dead?

**Comment by skabashnyuk** [comment]
@rpsene I think the biggest challenge today would be the fact that Che7 targets on OpenShift/K8s infrastructures. I'm not sure they are compatible with POWER (ppc64le). WDYT?

**Comment by benoitf** [comment]
@skabashnyuk AFAIK k8s is compliant with ppc64le ( kubernetes-server-linux-ppc64le.tar.gz )

@rpsene AFAIK it should be possible to port it. Maybe it would be easier if you describe the references that are not working so we can check how to handle it.

About phantomjs it's only used by tests but it can use other browsers as well.
