### ISSUE TITLE
Initialization Language Server loader  should be non-blocking and allow user to edit the file while it is processing

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#2525]
When user opens a file with the right file extension initialization loader for language server with progress bar in lower corner of IDE similar to how we resolve maven dependencies.
The message should be "Starting language server for csharp."

**Comment by xcoulon** [comment]
Furthermore, when the language support fails to start, the dialog remains open and blocks the UI. So having a non-blocking message displayed in the progress bar would be much better, indeed.

**Comment by bmicklea** [comment]
@vparfonov what's the status on this issue?

**Comment by tsmaeder** [comment]
I've looked into this and it is relatively simple to remove the blocking behaviour (I have a branch that implements this here: https://github.com/tsmaeder/che/tree/2525_dont_block_on_ls_init). However, one big problem remains: that the language servers and the IDE don't agree on the contents of the files. This does not necessarily have anything to do with the blocking behaviour. Imagine this scenario:
1. A file foo.test is opened in the editor
2. The test language server gets a "didOpen" notification
3. The user makes some changes in foo.test
4. The test language server gets some "didChange" events for foo.test, updating it's internal model of foo.test
5. The user presses refresh in the browser. All unsaved change in the IDE are lost.

The additional case that async initialization introduces is the one where open/change events are lost because the server is not yet done starting.

I've asked for some clarification on the protocol level: https://github.com/Microsoft/language-server-protocol/issues/216

**Comment by tsmaeder** [comment]
I've looked into this and it is relatively simple to remove the blocking behaviour (I have a branch that implements this here: https://github.com/tsmaeder/che/tree/2525_dont_block_on_ls_init). However, one big problem remains: that the language servers and the IDE don't agree on the contents of the files. This does not necessarily have anything to do with the blocking behaviour. Imagine this scenario:
1. A file foo.test is opened in the editor
2. The test language server gets a "didOpen" notification
3. The user makes some changes in foo.test
4. The test language server gets some "didChange" events for foo.test, updating it's internal model of foo.test
5. The user presses refresh in the browser. All unsaved change in the IDE are lost.

The additional case that async initialization introduces is the one where open/change events are lost because the server is not yet done starting.

I've asked for some clarification on the protocol level: https://github.com/Microsoft/language-server-protocol/issues/216

**Comment by tsmaeder** [comment]
Got an answer from @dbaeumer: 
> So in the current protocol the sequence should always be:
>
> didOpen(foo, content)
> didChange(foo){n}
> didClose(foo)

This means the client LSP client implementation is broken in that respect in Che. The only way around this I see is managing open documents in the workspace agent. Note that this would be necessary anyway when we have multiple language servers for the same file, because the may have different document sync policies.
As I understand it, Che does no currently manage unsaved document state in the workspace agent, so that a bit of a contradiction. Not sure how to resolve this...maybe only report saved changes to the language server agents?

**Comment by benoitf** [comment]
For now, all language servers are required to be initialized before opening the editor.
With the lazy mode, language server could come later than the editor is opened
We should ensure that when a language server is coming after editor is opened, it receives the `didOpen`event.

**Comment by skabashnyuk** [comment]
Not relevant anymore. Please consider opening a new issue if you think it is up to date.
