### ISSUE TITLE
Use `volumes-from` when starting a workspace

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#2598]
To share file `ws-agent.zip` between che-server and its workspaces, host folder `/home/user/che/lib` is bind-mounted when a workspace container is started:

`docker run -v /home/user/che/lib/ws-agent.zip:/mnt/che/ws-agent.zip  ...`

However if `--volumes-from che-server` is used instead of bind-mounting, the dependency to host folder `/home/user/che/lib/` would be removed and Che would be more flexible (e.g. we could use it even when folder `/home/user/che/lib` is not accessible).

`--volumes-from` could be used in conjunction with a named volume (`docker volume create`). The whole workflow could be something like:

``` bash
# Create a named volume
docker volume create --name che-lib-wsagent

# Start the che-server
docker run ... -name che-server -v che-lib-wsagent:/home/user/che/lib-copy codenvy/che-server ...

# Start a workspace
docker run ... --volumes-from che-server
# or
docker run ... -v che-lib-wsagent:/home/user/che/lib ....
```

Anyway `--volumes-from` cannot be used in every scenario. If che-server and the workspaces are on different hosts the old behaviour or a named volume should be used instead. 

A new property (`machine.docker.volumes.lib`) and an environment variable (`CHE_DOCKER_MACHINE_VOLUMES_LIB`) could be used to specify if `--volumes-from` should be used or not. If the property or the environment var are not set che-server behaves as before. If the property is set, its value correspond to name of the volume.

**Comment by l0rd** [comment]
@sbryzak will work on that. We have discussed with @garagatyi about that issue and he recommended to look at [this class](https://github.com/garagatyi/che/blob/405422c6dbbd60f295c5e1f76fada53250cd0adb/plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/MachineProviderImpl.java#L99-L99) to add `volumes-from` when starting a workspace.

**Comment by wernight** [comment]
Should work but it feels wrong. `--volumes-from` is mostly to add persistence and it's actually less and less used in favor of real data volumes (and not container volumes).

Since Che already opened and HTTP port and since even the hostname is known, why not simply serve those files and do a `wget` or `curl` to retrieve them when starting a workspace container? This would seem more robust.

**Comment by TylerJewell** [comment]
wget and curl for loading of agents turns into a burden when running a large distributed system.  It's possible that a single workspace could load up to 10 different agents, and some of them can be as large as 150MB.  The ws-agent.zip that we mandate for dev machines is 54MB.  Imagine running 1000 workspaces that are starting / stopping continuously.

**Comment by wernight** [comment]
If the same container may want to do it multiple times, a `rsync` would work. If these files change relatively infrequently there could be even some version initially in the container being boostrapped (reducing initial rsync).

```
[host]$ docker run ...
[container]$ rsync http://che/agent?hash=123456789 /home/user/che/lib
```

If a `Dockerfile` can be built, then a `RUN wget ...` from within a `Dockerfile` could make use of Docker caching to avoid pulling again resources. The wget URL could include a hash of those files to always get the latest.

```
[docker-host]$ docker build -t foo .
[Dockerfile]$ rsync http://che/agent?hash=123456789 /home/user/che/lib
[docker-host]$ docker run foo
```

(since here `foo` would be in the local cache it wouldn't be pulled and doesn't need a Docker Registry).

Those are only suggestions. If you feel none work, go on with `--volumes-from`, I'll test if it works fine on my setup.

**Comment by TylerJewell** [comment]
We are having a week long hackathon looking at a number of these architectural concepts.  @benoitf is working on a proof of concept that will have both scenarios - the agents hosted from within the Che server avaialble for download to any workspace AND also volumes-from.  The workspace will go through a check sequence where it first looks for a volume, and if not, then can download the agent fro the che server.  Works pretty good in the labs so far.

**Comment by benoitf** [comment]
Che server is now able to either download agents (from workspace master) or use them if they're volume mounted
