### ISSUE TITLE
Documentation not clear enough

### ISSUE THREAD

**Issue by tikaa** [eclipse-che/che#260]
The eclipe che documentation should contain either a recommended link to install docker, or a separate guide of your own on how to install docker. 

For a person who has never used docker before it is difficult to go through different guides and figure out the correct one to install docker when their primary goal is to run Che and not install docker.

Appreciate if you could append this in your docs..

**Comment by TylerJewell** [comment]
@tikaa Our docs cover the pre-requisites here and have a reference to Docker's landing page for how to install Docker for different operating systems.
https://eclipse-che.readme.io/docs/install-pre-reqs

Because Docker has a wide variance of how it should be installed and configured on different systems, it would be quite onerous to maintain the appropriate linkages to every Docker configuration page, as it can vary quite widely by different Linux operating systems.  

It is best left to Docker to provide instructions for this setup.
