### ISSUE TITLE
Sometimes, commands are not added correctly on workspace creation from stack

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2680]
**Reproduction Steps:**
1. Create workspace from 'Bitnami Codeigniter' stack with 'codeigniter' project
2. Go to 'Run' -> 'Edit Commands...'

**Expected behavior:**
 **"codeigniter: 1. Create and run project"** and  **"codeigniter: 2. Run"**  are presented in the 'command' widget
**Observed behavior:**
Sometimes, only the **"codeigniter: 1. Create and run project"**  command is presented  in the 'commands' widget
![commands](https://cloud.githubusercontent.com/assets/8051404/19031822/0269ddc2-895f-11e6-8153-6b03b1d2918d.png)

**Che version:**    5.0.0-M5-SNAPSHOT
**OS and version:**  Ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**  Docker container

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: No

**Comment by kaloyan-raev** [comment]
This also happened to me several times with the 'Bitnami Laravel' stack. Command No.1 is missing, the rest are available. 

No reliable way to reproduce it.

**Comment by ashumilova** [comment]
Will try to fix it ASAP.

**Comment by olexii4** [comment]
Cannot reproduce

**Comment by kaloyan-raev** [comment]
This issue still happens to me very often with variety of stacks and project templates.

I debugged the problem and found the root cause.

The Dashboard's [Create Project Controller](https://github.com/eclipse/che/blob/master/dashboard/src/app/projects/create-project/create-project.controller.ts) sends addCommand and updateProject requests in parallel. This results in calling the respective [addCommand](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java#L413) and [updateProject](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java#L619) methods in the WorkspaceService, which both try to update the workspace's config object in a race condition.

There are two ways to fix this issue:
1. (Easier) Avoid calling `addCommand` and `updateProject` in parallel. Instead, call them `updateProject` after receiving the response from all `addCommand` requests.
2. (Better) Implement appropriate synchronization in the WorkspaceService.

Please reopen the issue.

**Comment by ashumilova** [comment]
@olexii4 : Try to use update workspace service for adding bunch of commands at once instead of adding it one by one. 
@kaloyan-raev : thank you for pointing it out.

**Comment by kaloyan-raev** [comment]
I created PR #2928 that fixes the issue.
