### ISSUE TITLE
We have an empty  name and email fields in .git/config file after import an existing project

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#2682]
We have an empty  name and email fields in .git/config file after import an existing project  before add a git committer.

**Reproduction Steps:**
1. Build and Run CHE.
2. Import an existing project from github(Workspace/Import project) before add a git committer.
3. Add a git committer(profile/preferences/git/committer). Try to make some changes and commit.

**Expected behavior:**
It committed successfully.

**Observed behavior:**

It added empty name and empty email during import.  And it's overrides the global one. 

**Che version:**    5.0.0-M5   

**Additional information:**

We have empty name and email fields in .git/config file:
..
[user]
<------>name =
<------>email =
...

It is unacceptable behavior for the import widget. We should check committer before import and show message if necessary.
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by vinokurig** [comment]
Can not reproduse when commiting from Git menu.
This issue appears when commiting from console by native git in container. We can not controll such use case because Git in container can be different version and even it can not be installed in container. We use JGit when performin git actions from menu and it works fine.
