### ISSUE TITLE
Unable to access eclipseche from host system

### ISSUE THREAD

**Issue by leelamanoranjan** [eclipse-che/che#272]
Hi,

I have installed eclipseche on  a centos 7 image running on virtual box. I have configured everything as described in the document. I am able to start eclipseche and access http://localhost:8080 and http://<IPAddress>:8080 from the virtual machine. 

However I am unable to access the url http://<IPAddress>:8080 from external systems. I am able to connect to the IP Address from external systems.

Is there additional configuration that needs to be done to access eclipseche from other systems.

Thanks and Regards,
Leela

**Comment by ghost** [comment]
This is expected behavior with any process running inside a VM. You should either setup port forwarding in a VM so that when you go to localhost:8080 on the host you are forwarded to 8080 port in your VM. However, there's a port range that Che uses for communications between browser and a workspace agent: 32768-65535. You may want to forward a smaller range though, say 32768-32798

Why is it an issue to access Eclipse Che by IP?

Also, have you started Che server with -r:${IP} parameter where ${IP} is your VM IP?

**Comment by leelamanoranjan** [comment]
Thanks I was able to access after starting the che server with -r:${IP}

Thanks and Regards,
Leela

**Comment by TylerJewell** [comment]
@leelamanoranjan Glad to hear this.  We have had a couple dozen people get tripped up on this.  We have tried to provide some guidance in the startup scripts - and of course, the docs.  Any suggestions on additional areas where we can detect this and / or recommend it to users?
