### ISSUE TITLE
Build assembly-ide-war failed on Window7

### ISSUE THREAD

**Issue by laralijuan** [eclipse-che/che#2739]
[Short description of problem here]
When I try to build che's assembly-ide-war on Win7, there is a  fatal error detected by Java Runtime Environment

**Reproduction Steps:**
1. $cd che\assembly\assembly-ide-war
2. $mvn -DskipTests=true -Dfindbugs.skip=true -Dskip-validate-sources -Dmdep.analyze.skip=true -Dlicense.skip=true -Dgwt.compiler.localWorkers=2 -T 1C clean install

**Observed behavior:**
failed at " --- gwt-maven-plugin:2.7.0:compile (default) @ assembly-ide-war ---"
Below are the error messages:
_

> [INFO] --- gwt-maven-plugin:2.7.0:compile (default) @ assembly-ide-war ---
> [INFO] #
> [INFO] # A fatal error has been detected by the Java Runtime Environment:
> [INFO] #
> [INFO] #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007758e44b, pid=8720, tid=340
> [INFO] #
> [INFO] # JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
> [INFO] # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode windows-amd64 compressed oops)
> [INFO] # Problematic frame:
> [INFO] # C  [ntdll.dll+0x6e44b]
> [INFO] [error occurred during error reporting (printing problematic frame), id 0xc0000005]
> [INFO]
> [INFO] # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
> [INFO] #
> [INFO] # An error report file with more information is saved as:
> [INFO] # D:\artik_ide\github\che\assembly\assembly-ide-war\hs_err_pid8720.log
> [INFO] #
> [INFO] # If you would like to submit a bug report, please visit:
> [INFO] #   http://bugreport.java.com/bugreport/crash.jsp
> [INFO] #
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 05:47 min (Wall Clock)
> [INFO] Finished at: 2016-10-08T19:52:02+08:00
> [INFO] Final Memory: 81M/1258M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.7.0:compile (default) on project assembly-ide-war: Command [[

_

**Che version:**    4.7.0  
**OS and version:** Window7  
**Docker version:** 1.12.0  
**Che install:**    N/A
- Problem started happening recently, didn't happen in an older version of Che: [N/A]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by laralijuan** [comment]
on Ubuntu 14.04， I build it success. Could you give me some suggestion? Thanks ahead.

**Comment by TylerJewell** [comment]
In doing some research online, this sort of error seems to happen when there is a bug in your Java installation.  It usually happens when there is some underlying hardware library incompatibility with the jvm.

I would suggest trying to upgrade the JVM, change the jvm to openjdk to try something different, or use our docker image for compilation (see how in the Che wiki).

**Comment by ghost** [comment]
@laralijuan do you want to compile this particular module? You may build assembly-main and the war will be just downloaded from the remote maven repo.

The closes I could get is to compile on Windows 8. No issues here:

![image](https://cloud.githubusercontent.com/assets/5337267/19218927/ac1fba54-8e0e-11e6-9108-214f4a90b86b.png)

**Comment by laralijuan** [comment]
@TylerJewell Thanks for your suggestions
I upgrade the JVM and still fail. And find Java error report at:[exception_access on Win 7](https://java.com/en/download/help/exception_access.xml)

And according to the [Che wiki)](https://github.com/eclipse/che/wiki/Development-Workflow#build-che-using-docker)， I still in trying.

**Comment by laralijuan** [comment]
@eivantsov I want to build assembly-ide-war, because I am setting up the supperdevmode for eclipse, and blocked at launching super dev mode. [https://eclipse-che.readme.io/v5.0/docs/setup-che-workspace#gwt-super-dev-mode-for-eclipse](https://eclipse-che.readme.io/v5.0/docs/setup-che-workspace#gwt-super-dev-mode-for-eclipse). Eclipse popup the error message: “errors exist in assemly-ide-war” and error log:“che-core-commons-gwt does not exist”

**Comment by TylerJewell** [comment]
This is a very odd situation.  IT will be challenging for us to help you diagnose this, as this is likely some sort of JVM bug for your particular OS + internationalization + GWT.  So some tests to try:
1. Can you remove the Oracle JVM and instead try OpenJDK - are the results the same?
2. Can you try installing Windows 10 or another operating system?

One other thing that you may try is the following.  We provide a Docker container which has its own operating system and can compile che as well.  It's slower than doing it on your host computer, but it does everything in a properly configured Docker container.  We give [instructions here](https://github.com/eclipse/che/wiki/Development-Workflow#build-che-using-docker).  However, if your objective is super dev mode, then I suspect that while this container provides nice compilation of the IDE, it will not allow super dev mode, because that is a mode where Eclipse is doing incremental compilation natively for you.

**Comment by laralijuan** [comment]
I will focus on build works on Ubuntu to avoid cost too much time of building issues on Win7.
Many thanks for your kindly suggestions.
