### ISSUE TITLE
Improvements for building and running projects in Che that use docker & docker-compose

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#2771]
Currently from within a workspace the PWD is `/project` but those files on the Docker host are `/home/user/che/workspaces` (by default, depending on `CHE_WORKSPACE_STORAGE` and such).
## The issue

The problem is that often people develop their project by building multiple docker images, linked together, and mounting local files on them to have changes apply instantly. For example (from within a development workspace):

```
$ docker build --pull -t frontend .
$ docker run --rm -v $PWD:/code:ro frontend
```

Supposing either the docker socket or `DOCKER_HOST` is set up, this is possible but would not work because it'd try to mount `/project` **from the docker host** and not the `/project` from the Che workspace).
## Suggested solution

Instead of `project`, set PWD to `CHE_WORKSPACE_STORAGE/$WORKSPACE_NAME` (e.g. `/home/user/che/workspaces/foo`). This way it'll be the same path on the Docker host since workspaces should be mounted already anyway.

Preferably have `/home/user/che/workspaces` under a simpler directory like `/storage/workspaces` (see #2755).
## Alternatives
- Mounting using the known real path, but this makes it Che-specific and the code development isn't portable anymore and it's specific to Che (should be the other way around).
- Have everything you need inside your Che workspace: This means duplicating your deployment environment of multiple docker images locally, which is not only hard to do, but hard to maintain, and may likely break when deployed because you're not testing the way it's deployment. For example a mount or link is different, or a binary changed, or...
- Support `docker-compose.yml` to build workspaces (see #1580) but then it's hard to restart/reload containers, and there would be multiple "shells" so cannot just start a shell, and tons of issues. It's possible and good to avoid exposing docker directly but it's a lot harder for everyone/everything.

**Comment by JamesDrummond** [comment]
@wernight Not sure I follow you completely on this issue. There is currently an environment variable `CHE_PROPERTY_che_machine_projects_internal_storage` that can be set to `/home/user/che/code` that will change where the project code is stored in the workspace machine. Also note for others viewing this we now use `CHE_DATA_FOLDER` in lieu of environment variable `CHE_WORKSPACE_STORAGE`.

**Comment by TylerJewell** [comment]
@wernight - thanks for the suggestion.  Though I think more information is needed.  I am not following the issue with workspaces that are mounting /home/user/che/workspaces into /project.  In particular, this statement loses me.  

"Supposing either the docker socket or DOCKER_HOST is set up, this is possible but would not work because it'd try to mount /project from the docker host and not the /project from the Che workspace)."

We mount into Che the host projects and we mount them into /projects inside the container that is designated with the dev-machine agent.  You can change the name of the location that is hosted inside the container with a Che property.

**Comment by wernight** [comment]
`CHE_PROPERTY_che_machine_projects_internal_storage` sounds like a good place to start, however it looks like it would still not work. Let me explain the issue a bit more first.

## Use case detail

I migrated (like many Docker users) my projects to be docker-based, possibly like you also working on Che. This means that for production I build some Docker images, push them, and deploy them on a server. During development I build them once and deploy them locally (usually using `docker-compose.yml`) but I override the source code by mounting my local source code to the place it's normally in the image (I'm mostly talking for HTML/Python/CSS/PHP/... development so uncompiled).

Example `Dockerfile`:

```
FROM nginx
COPY . /srv/www
```

Now for development I'd do:

```
$ docker build -t nginx .
$ docker run -v $PWD:/srv/www:ro nginx
```

This means I've very close to production environment during development and simpler to maintain, and the only requirement to develop is having Docker installed (usually along `docker-compose` for me).

For compiled stuff it's similar but a bit more complex so I'll skip it.

## Issue details

So now I'd like to achieve the same but on the cloud. I cannot build a Che workspace just using that `Dockerfile` because it's not a single `Dockerfile` but multiple (following good Docker practices).

Let's assume we've a working `docker` client on the Che workspace connected to the Docker daemon used by Che to start workspaces. It actually doesn't matter if it's `docker:dind` or the host docker, exposed via `DOCKER_HOST` or `/var/run/docker.sock`; the issue remains the same.

Supposing `PWD` is `/workspace`, as I'm on a Che workspace (or whatever `CHE_PROPERTY_che_machine_projects_internal_storage` has been set to), if I do `docker run -v $PWD:/srv/www`, then on the docker daemon file system it'll try to mount `/workspace`. However `/workspace` will not exist. The reason is that it's actually at `/home/user/che/workspaces/WORKSPACE_NAME` on the docker daemon FS.

So even if I set `CHE_PROPERTY_che_machine_projects_internal_storage` to `/home/user/che/workspaces/`, it'll still be wrong because it'll miss that `WORKSPACE_NAME`.

## (Ugly) Workaround

I said it doesn't matter how `docker` is running but that's not fully true. It's theoretically possible to build a Che workspace which runs directly docker:dind within that workspace but that means that Che must start that container in privileged mode and it'd be even slower, not able to use a good Docker cache, etc. So I only assume that on the Che workspace there is only a `docker` **client** that actually uses the Docker daemon that is also used by Che to start workspaces.

**Comment by TylerJewell** [comment]
I think I get it.  May I summarize what you are suggesting.  I think what you are thinking about is that you want to find a way to mount host-level source code but from inside the workspace container.  Something like:

1: Start Che
2: Start new workspaces
3: Go into terminal in the workspace
4: Got to `/projects` directory, which is the `CHE_PROPERTY` value
5: Volume mount a directory with the source code from the host into the `/projects` directory, thereby creating a new project within the workspace

If this is what you are thinking, we have been thinking of a different concept on how to handle that.  We think the Vagrantfile approach is a way to address that, and we have built a similar sort of system called Chefiles / Chedir which does a similar sort of thing.  But the Chefile's primary purpose is to take an existing directory with your source code locally, and then turn it into a proper workspace.  If Che is already running, great, it will reuse that.  If Che is not running it will start a new one.  It will create a workspace, volume mount the local folder into the right location for you.  And then set the project type.  Any changes made locally are then saved to disk as it's a proper volume mount.

These are the [chedir docs](https://eclipse-che.readme.io/v5.0/docs/getting-started-chedir).  We have more work to do on this. But it is designed to work without a Chefile.  You can go into any directory and just say "che dir up" and we will convert it into a hosted workspace.  If you have the right syntax, we will reuse your Dockerfile or docker-compose.yml file that is in the root of the host directory as the recipe to create the Che workspace runtime.

We have some more work to do - as in this epic here.  But one of the improvements that we are making are:
1:  Today the che server must be local to the host working directory so that volume mount works.  We will also make this work with any remote Che as well, so you can have a local directory but we will remotely connect to a che, create the workspce, and then rsync the contents locally to remote.
2: We also have a Codenvy capability that will let any Codenvy system to factory a remote repo with a Chefile.  You just tell codenvy "onboard this repo" and we will execute the che-dir sequence against that repo, but in the codenvy system.  This has more work still.

We have a tracking epic for this [here](https://github.com/eclipse/che/issues/2266)

@benoitf - FYI.

**Comment by wernight** [comment]
I don't quite understand how Che Dir works. What I'm trying to do is build a cloud IDE where I can run projects, not something requiring a local computer to fire up something. So only need a web browser. Also you talk about Vagrant which confuses me even more. Vagrant is for VM and not Docker.

What I want is close to your steps until step 5. Step 5 would be to use a custom Che command like:
- commandLine: `cd ${current.project.path} && docker-compose up --build`.
- previewUrl: `http://${server.port.8080}/`

This command would start some containers, not some Che projects, not some Che workspaces.

**Comment by gazarenkov** [comment]
@TylerJewell what the kind/planning mean here?

**Comment by roynasser** [comment]
I think what I'm trying to do is something similar... I would also like to use Che to edit existing code, for the time being not using the creation/scaffolding of containers within it per se...  Would there be a way for me to just add a PHP project, and ignore the runner container, and just use the development container and IDE pointed to a volume on the server?

Is there any documentation about that?  Or how I can persist the workplaces?  I've been unable to get it to work correctly... I think there is something im doing wrong as even when I map the volume drives to what I bellieve is the workplaces directory, its always empty... Also, would it be possible to do this using the docker launcher, or should I download che to the server and set it up differently?

**Comment by JamesDrummond** [comment]
@wernight If you called your workspace a particular name such as "php",  and set host environment variables `export CHE_PROPERTY_machine_server_extra_volume=/var/run/docker.sock:/var/run/docker.sock`  you could provide the following command:

```
commandLine: docker-compose up --build
previewUrl: http://<server-ip>:<port>/
```

You would have to manually provide previewUrl with the host server external ipaddress and port number defined in compose file mentioned below.

Since the docker.sock file is for the host's Docker daemon the compose command is executed on the host not in che-server. This allows the use of local build and host port binding compose syntax. When defining the compose file you would use something like this

```
build:
  context: /home/user/che/workspaces/php/<name of project>/
ports:
  - "80:80"
```

**Comment by wernight** [comment]
@JamesDrummond 
- Giving access to docker isn't an issue here (just assume it's working)
- Giving the `previewUrl` isn't an issue here either (the Che UI is pretty good)

You're right that I could mount `/home/user/che/workspaces/php`, but that my point of issue. It'd hardcode and make the project adapted to Che, and not Che work with my project.

My suggestion of a fix is to **include the workspace name** in the `CHE_PROPERTY_che_machine_projects_internal_storage`. For example supposing I kept the default `CHE_PROPERTY_che_machine_projects_internal_storage=/project` and my workspace is called `php`, then I'd my project to at `/project/php` from within the Che workspace CLI. This way I could set `CHE_DATA_FOLDER` (previously `CHE_WORKSPACE_STORAGE`) to `/project` as well.

Once we have that, a "standard" `docker-compose.yml` would work on my Che workspace terminal:

```
build: .
volumes:
  - ./:/code
ports:
  - 80:80
```

PS: Your `docker-compose.yml` example is actually wrong because the `context` is taken by the client, so it'd always work. What does _not_ work are mounted volumes because they are mounted by the docker server.

**Comment by JamesDrummond** [comment]
@wernight Sorry I was unaware the build was done by the client. Providing the workspace name in the CHE_PROPERTY_che_machine_projects_internal_storage automatically I think would effect others who have hardcoded their code/commands to this path. Could you create a symbolic link in the workspace's project directory like `ln -s /projects /projects/php` in your stack's recipe. Then `cd /projects/php/<project name> && docker-compose up`. The only issue would be your workspace name would need to be unique and not match a projects name. For example if your workspace is called "php" then you could not have a project called "php".

You could also click on the folder container the compose file and provide a command with `[ -e /projects/${workspace.name} ] && echo "Symbolic link/folder exists skipping." || ln -sf /projects /projects/${workspace.name} && cd /projects/${workspace.name}${current.project.relpath} && sudo docker-compose up`

**Comment by wernight** [comment]
That's a good idea. It means to make a recipt that depends on the workspace name but that's not so crazy.

May I suggest that you check:
- How many dev would like this ability to use docker/docker-compose as I am on Che (what I'm asking here but simplified), among those using docker/docker-compose?
- How many dev hardcoded their path to `/project` and would not like this breaking change?

The reason I ask is that among people using Docker this method is rather popular as far as I can tell. I don't have large sample size however.

**Comment by TylerJewell** [comment]
@wernight - virtually everyone we are talking to is building systems where there are Dockerfiles and / or docker-compose files in the root of their source code repository.  We are certainly not perfect here, but our general direction is the following:
1. In the primary case, when you import a project that has docker-compose or a Dockerfile in the root of the repository, our first attempt is to provide that as the runtime environment, if the user wants to configure it that way.  That is for reflecting the runtime environment for the code itself.
1. The secondary approach is that within the workspace, developers will want to make use of their Dockerfiles and docker-compose scripts to build + run their projects from within the workspace itself.  In this case, we are much weaker.  But the basic ideas are:
   a: Require users to volume mount /var/run/docker.sock for their workspace volume mount.
   b: Perhaps let the admin provide a custom DOCKER_HOST: which is passed along to the workspace.
   c: Improving the command infrastructure so that command are a lot easier to edit / run.  There are some amazing specifications drafted from @vparfonov and @slemeur on how we will improve this.

A first step on this journey has been to expand the command macro list so that from within a workspace you can use macros to discover the name of the workspace, and the name of the project - and the name of the contextually selected items in the tree or the editor.

It seems like we should add an improvement that would allow users to have a macro for the name of the mounted folder `/projects`, which is configurable in the che.properties file.  This would allow people to write macros from within Che that have total environment contextual awareness.

I think in re-reading everything here, this would be satisfying to the expectations that you are outlining.  I'm going to adjust the title of this issue to reflect the nature of the conversation which is about improvements about how to run projects that are docker-based from within a workspace, so that readers do not get confused about this being the Docker runtime itself.

**Comment by wernight** [comment]
So I got it to work (finally!!!!).

 1. I'm running on Kubernetes using a version of https://github.com/wernight/kubernetes-che/ with docker running on the same machine as Che (like most people I guess).
 2. Make sure that within a Che workspace `DOCKER_HOST=tcp://che-host:2375` (this would be valid if Docker daemon is running on that port like in my kubernetes setup). At this point you should be able to build docker images from within workspaces.
 3. Set the real path of your workspace from within the host machine, using for example `export DOCKER_HOST_PROJECT_DIR=/data/workspaces/${workspace.name}/${explorer.current.project.name}` and then replace `docker run -v ./foo:/foo ...` by `docker run -v ${DOCKER_HOST_PROJECT_DIR}/foo:/foo ...`.

A first helper would be to have a Che-provided variable which contains the correct path to the workspace on the che-host like `/data/workspaces/${workspace.name}` in my case.

One important issue is that `${server.8080}` and similar port macro will not work because they point to the workspace IP instead of pointing to `che-host` IP. So one much handle that manually. To improve on that, it'd be helpful if one could generate a preview URL from the run command. It may also help to show that URL only once the server actually started. So one idea if a magic command like `che-preview-url http://che:8080/`.

**Comment by davidwindell** [comment]
Hey @wernight, I'm working through a very similar setup to you (only on Docker Cloud instead). A few years ago, our team switched to building Docker images with an automation tool we wrote 
https://github.com/outeredge/dredger. We build PHP base images and then run these/mount a project folder into `/var/www` and do our development work (in desktop IDEs).

Our compose looks like this https://github.com/eclipse/che/issues/4878#issuecomment-297589303

The awesome thing with a proxy like that is that for each docker image that is built *within* Che and run, all it needs is a unique `VIRTUAL_HOST` and you can access like `http://VIRTUAL_HOST.user-1.eclipse-che.server.com`. This also means that (as we run everything on port 80 in our images at the moment) we don't have to worry at all about port exposure of the built/running images. 

I'm now wrapping this up by sorting out the volume mounts and came across your post above (thanks for helping point me in the right direction!). One way I've been able to automate it a little more more is by doing this:

```sh
export DOCKER_HOST_PROJECT_DIR=$(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "'"$CHE_PROJECTS_ROOT"'" }}{{ .Source }}{{ end }}{{ end }}' $HOSTNAME)
```

Which returns the host path of /projects. 

@TylerJewell can the above export be added as an environment variable into the runtime container automatically by Che and also allow us to use environment variables in the preview URL - which ties in to @wernight last paragraph? (see #4932)

**Comment by TylerJewell** [comment]
@davidwindell - I am not entirely clear on the ask for the "above export added as an environment variable into the runtime container".  Can you provide an example of what should happen, where it should be configured at each step of the way?

As for passing environment varialbes into preview URLs, we may have a more flexible component which allows for configuration of the server evaluation strategy.  In particular, from @benoitf in this proposed PR, he introduces the ability to run a reverse proxy as an embedded docker container, and we subsequently route all traffic through a single port / URL, and then use a che.env configuration parameter to define how the incoming URL is then routed to a back-end workspace.

https://github.com/eclipse/che/pull/4440

This would apply to servers running in workspaces, but I don't think it applies to SSH in a workspace because the embedded proxy that he used doesn't have TCP support yet (HTTP only).

**Comment by davidwindell** [comment]
@TylerJewell I don't think the work in #4440 will help us as Docker images are built and run inside Che so Che has no awareness of the ports exposed. That's fine though, we've got that all working nicely with jwilder/nginx-proxy by simply setting a `VIRTUAL_HOST` env var on the images we run within Che. This means we just access the web server running in the built images via port 80 along with che, etc by hostname/virtual host mapping.

As far as mounting the project volume, the idea of having DOCKER_HOST_PROJECT_DIR set for us is just that our commands wouldn't have to do the first line of this;

```sh
export DOCKER_HOST_PROJECT_DIR=$(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "'"$CHE_PROJECTS_ROOT"'" }}{{ .Source }}{{ end }}{{ end }}' $HOSTNAME)  <<<<<<<<<<<<
docker run -v DOCKER_HOST_PROJECT_DIR:/var/www ...etc
```

Finally, what we, and I think @wernight are looking for with the preview URLs its to avoid having to set a hard coded FQDN in our stack files like so (extract from our working stack);

```
"previewUrl": "http://${explorer.current.project.name}.${machine.dev.hostname}.che.ourdomain.com"
```

All we really need is access to the Che Server hostname (CHE_HOST or CHE_DOCKER_IP_EXTERNAL) in the preview URL (I've mentioned this here https://github.com/eclipse/che/issues/4932#issuecomment-297679600).

Does that make sense?

**Comment by wernight** [comment]
My main issues are, in order of importance:

 1. A Che-provided variable which contains the correct path to the workspace on the docker's host which is also che's host for single machines (e.g. `DOCKER_HOST_WORKSPACE_DIR=/data/workspaces/workspace_name`); as this only would work if docker's host is on the same machine as the workspace, else mounts will not work.
 2. Have a way to show a more dynamic preview URL. I was suggesting the ability to run a command like `che-preview-url http://${che.host}:8080/` as any part of the commands. The issue with the current preview URL is that it's not only too static, but also shown before the server is actually up and running. May be simply parsing the output and looking for a URL would be good enough as it would solve both these issues. Using Dredger is also possible as it would could avoid port conflicts, but it seems hard to set up (on top of something already pretty hard to set up to easy to break).

**Comment by davidwindell** [comment]
Dredger now has fully automated support for Che! https://github.com/outeredge/dredger/blob/master/dredger

**Comment by skabashnyuk** [comment]
Not relevant anymore.
