### ISSUE TITLE
Where to specify credentials for subversion

### ISSUE THREAD

**Issue by levjason** [eclipse-che/che#2852]
I'd like to import a project from subversion.  Our subversion repositories are accessed with user and password. Can these be specified somewhere in Che?

**Reproduction Steps:**
1. Workspace -> import project
2. Select subversion in the import project dialog. Enter the svn url. 
3. Click on import

Expected Behavior
Project is imported into the workspace

**Observed behavior:**
java.lang.IllegalStateException: org.eclipse.che.ide.websocket.rest.exceptions.ServerException: svn: E170001: Unable to connect to a repository at URL 'http://<hostname>/svn/sagtest/playground/InsurancePremiumsPackage/trunk' svn: E170001: OPTIONS of 'http://<hostname>/svn/sagtest/playground/InsurancePremiumsPackage/trunk': authorization failed: Could not authenticate to server: rejected Basic challenge (http://<hostname>:1818)

5.0.0-M5    [Enter Che version here]  
Ubuntu 16.04 [Enter OS name and version here]  
 1.12.1 [Enter your Docker version here `docker version` on CLI]  
running from a Che assemble that I built.\*    [Vagrant, Docker container, server (zip), Bitnami, Yatta, or Codenvy?]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by JamesDrummond** [comment]
@levjason When you got this error did the username and password prompt come up? When importing a project with svn is attempted, it will check the workspace dev-machine's "~/.subversion/auth/svn.simple/" folder for authentication information. Try erasing the contents inside `rm -r ~/.subversion/auth/svn.simple/*` in the dev-machine terminal and try again.

If it still does not work after entering your credentials, create a new workspace and issue svn command on the dev-machine terminal `svn checkout http://<hostname>/svn/sagtest/playground/InsurancePremiumsPackage/trunk` to see check that the repo and username/password are working correctly. Let us know if the terminal command is successful.

**Comment by JamesDrummond** [comment]
@levjason Was the docker image you tried that didn't include svn a custom image or a Codenvy image? 

When you tried it from the terminal first it created the authentication information in the `~/.subversion/auth/svn.simple/` folder. That is why when you next tried to use the UI it did not prompt you for credentials since the UI runs the svn command on dev-machine and found the authentication information you entered earlier when you used the terminal.

Please close this issue if the issue is resolved for you. 

@bmicklea I spoke with Eugene about getting the UI to use java to issue svn commands so that the UI would not be dependent on svn being installed on the dev-machine. I am going to add the issue and link it back here.

**Comment by levjason** [comment]
@JamesDrummond It was a custom image.  Thanks.
