### ISSUE TITLE
Switching editor tabs should move the highlight in the project explorer

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2934]
When I select an editor tab the project explorer should automatically highlight that file in the project explorer so I can see where the file is in the repo's structure.

We may want this to be an option the user can set in preferences so they can choose this behavior or the current behavior.

**Comment by slemeur** [comment]
Should definitely be an option because it can have bother some developers and in certain use cases.
BTW - it's what Eclipse IDE is doing.

"Linking Editor" option from the project explorer.

![explorer-link-editor](https://cloud.githubusercontent.com/assets/1636769/19811350/44c8de80-9d31-11e6-9d24-cf06d9c17995.gif)
