### ISSUE TITLE
Command Editor - Preview URL view

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2999]
This issue is sub-task of #2898 

Issue dedicated to the Command Editor for defining the Preview URL.

![commands explorer - previewurl](https://cloud.githubusercontent.com/assets/1636769/20053898/e2cc837e-a4da-11e6-990d-a9b08d3b1afe.png)

**Comment by Rubyleaf-MBarton** [comment]
Is this Issue the same for everybody? I seem to be suffering from it.

**Comment by wernight** [comment]
I've issues with the preview URL of custom commands in version 5.5.0:

 - Doesn't detect changes:
     1. Open Commands editor > Select an existing custom command
     2. Fill in the Preview URL field
     3. Expected "Save" button to be enabled, but it's still disabled.
 - Doesn't save the Preview URL: Even clicking save after doing previous steps and changing the command for example, and reloading the page, the Preview URL remains empty.
  - Pressing Del key while editing the command line, prompts to delete the entire custom command (instead of deleting a character in the text field)
