### ISSUE TITLE
Does Iresource Model supported in Che? How to achieve Iresource features ?

### ISSUE THREAD

**Issue by chetanladdha** [eclipse-che/che#3099]
I know Iresource model is very tightly coupled with the Eclipse, Iresource model is not separated even as library but still I have below questions:

1. Does Che have support for the Iresource model from Eclipse? 
2. How we can achieve Iresource capabilities in Eclipse Che?  Is there any similar model/framework supported which acheive Iresource capabilities.

I can see Iresource related code in che-plugin-java-ext-jdt, 
1. Is the support provided only for a specific language? 
2. How we can do it for the domain specific languages for example Xtext base languages?

**Comment by TylerJewell** [comment]
We do not support the iresource model of the eclipse IDE.  We use a different platform that we have built.   Maybe @dkuleshov can share some of the concepts around file system watchers that we have built.

**Comment by gazarenkov** [comment]
Hi @chetanladdha,

Yes, you are right, we use Eclipse Resources API (same as several others Eclipse artifacts you can find in our sources) exclusively as a dependency for JDT for supporting Java intellisense which is a part of our java plugin.
They are repackaged and some of them are also some modified/extended (you can find org.eclipse.che.\* packages inside). 
You can try to reuse our artifact if it fit your goals or use original Eclipse's things in your plugin (in second case I think you should exclude Che's Java plugin from the bundle to avoid conflicts).

**Comment by chetanladdha** [comment]
Thanks @gazarenkov . Could you please describe more info on Che File watcher ?

**Comment by dkulieshov** [comment]
Hi, we use implementation based on java [WatchService](https://docs.oracle.com/javase/8/docs/api/java/nio/file/WatchService.html) to detect events related to server-side file system items (file/directory creation, removal and modification). In order to be able to detect such events you need to create a specific implementation of [HiEventDetector](https://github.com/dkuleshov/che/blob/435bbd5505e9103e358ecbfcba0a0956f3df2fad/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/impl/file/event/HiEventDetector.java) interface and register it in a dependency injection framework (Guice). Please take a look at [PomModifiedHiEventDetector](https://github.com/dkuleshov/che/blob/5d267fe305dce3d151baf0c866393fbf733216f2/plugins/plugin-maven/che-plugin-maven-server/src/main/java/org/eclipse/che/plugin/maven/server/PomModifiedHiEventDetector.java) as an example of such detector. 

After detection and analysis is done you can proceed further by addressing the event or data to a corresponding server-side (using [HiEventServerPublisher](https://github.com/dkuleshov/che/blob/435bbd5505e9103e358ecbfcba0a0956f3df2fad/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/impl/file/event/HiEventServerPublisher.java) and [EventService](https://github.com/dkuleshov/che/blob/2cb89534380ac8558a1461d28419ee62ab48b0a7/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/notification/EventService.java)) or client-side (via [JsonRpcRequestTransmitter](https://github.com/dkuleshov/che/blob/75a7297c21bd6d232d07730c46f933298175d82e/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/JsonRpcRequestTransmitter.java) or any other convenient way) consumer.
