### ISSUE TITLE
Unexpected server error after refactoring with rename and move operations

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#3104]
**Preconditions**: create  a new package in the Spring project

**Reproduction Steps:**

1. Create the Spring project. Open GreetingController class. Do rename class in the editor trough Assistant ->Refactoring->Rename menu.
2. After renaming, select the just renamed class in the Project tree and do:  Assistant->  Refactoring-> Move

![anim](https://cloud.githubusercontent.com/assets/1640058/20388717/d6592ab0-acce-11e6-8c1f-b69b43c8f73f.gif)

**Related selenium test test:** RefactoringFeatureTest

**Expected behavior:**
The class should be moved
**Observed behavior:**
Internal server error

**Che version:**    5.0.0-M8
**OS and version:** Ubuntu 14.0 TLS
**Docker version:** 1.12.3

**Comment by evidolob** [comment]
The problem is that AppContextImpl doesn't correctly handle rename of the file. It holds previous file in `currentResources` after rename refactoring. I think that this [method]( https://github.com/evidolob/che/blob/0e8b21ad3ff5da80a7a03ddf3f0b281cc3594dcb/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/context/AppContextImpl.java#L237-L305) should be changed to handle rename refactoring

**Comment by musienko-maxim** [comment]
In version 5.6.0 is not actual
