### ISSUE TITLE
Failed to inject orion editor

### ISSUE THREAD

**Issue by nipobhsnro** [eclipse-che/che#3118]
I am opening che workspace url(http://ip-address/dashboard/#/ide/che/wksp-3h29) and the trying to open project file bur getting an error "failed to inject orion editor"

Is there any ip address getting blocked??

**Comment by benoitf** [comment]
@nipobhsnro please follow guidelines when creating issues

[Short description of problem here]

**Reproduction Steps:**
1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Che version:**    [Enter Che version here]  
**OS and version:** [Enter OS name and version here]  
**Docker version:** [Enter your Docker version here `docker version` on CLI]  
**Che install:**    [Vagrant, Docker container, server (zip), Bitnami, Yatta, or Codenvy?]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by nipobhsnro** [comment]
Reproduction Steps:

```
I have created dot net workspace from stack and trying to open file (program.cs) but getting an error failed to inject orion editor
```

Expected behavior:

File actually need to open

Observed behavior:

[Describe observed behavior here]

Che version: 4.5.1
OS and version: Windows 7 Enterprise

Docker version: 1.11.2

Che install: Bitnami

**Comment by shadowcodex** [comment]
@nipobhsnro are you hosting it on bitnami or did you download it to your local machine?

**Edit:**

I downloaded the vm from bitnami and booted it up using virtualbox. Logged in, created .net workspace, and opened program.cs without error.

I have a few more questions to get down to your issue:
1. Is this a new install?
2. Do you have logs? Browser logs, che logs, anything?

**Comment by nipobhsnro** [comment]
I have installed it from bitnami stack.
I am facing this issue when i am trying to connect from LAN, on wifi or dongal its working.
So is there any settings in configuration file which i need to do?

**Comment by nipobhsnro** [comment]
Do we need to enable some firewall settings or ports?

**Comment by TylerJewell** [comment]
If you have a firewall setup, then yes, you will run into issues.  You need to have port 8080 (or whatever other port you are running Che on) open, and also ports 32768+ opened for the ephemeral port range.

**Comment by nipobhsnro** [comment]
@TylerJewell I tried opeing ports which u have mentioned but still getting same issue

**Comment by TylerJewell** [comment]
The error messages are not really helpful.  You need to provide a much deeper level of inspection and log reports from Che and browser in order for anyone to guess.

**Comment by nipobhsnro** [comment]
@TylerJewell  i have attached screen shot of console for the same:
![orioneditor](https://cloud.githubusercontent.com/assets/23380460/20957048/8872752c-bc73-11e6-932e-4ee94055165f.PNG)
