### ISSUE TITLE
Moderator as a Contributor

### ISSUE THREAD

**Issue by shadowcodex** [eclipse-che/che#3147]
I would like to open discussion for the possibility of having a moderator role. Things that a moderator would do are organization oriented and for issues and PRs. 

*  Close old issues with no recent responses.
*  Edit postings from English as a second language speakers. This would make issues or PRs easier to read. Which in turn helps others who come in later to reread an issue or PR to fix a problem they are having.
* Help assign labels to issues or PRs.
* Lock issues so that only contributors can comment (For giving updates but not dragging out conversations).

A moderator would need to know the labeling system and best practices as determined by the core team. 

Thoughts?

**Comment by TylerJewell** [comment]
All of those rights are afforded to anyone with committer rights. It is not obvious, but the GitHub rights that we have on this repository are not controlled by us, but actually the Eclipse Foundation. First, merges of code + docs are only permitted if a valid Eclipse CLA is filed.  The pull request system in GitHub has hooks to check and will allow / not allow a merge based upon the email address of the submitter.

Then, anyone whose email address is matched up with Eclipse Foundation committer rights on this particular project, then gets rights to the GitHub repository - merge pull requests, commit code, make branches, delete commons, lock conversations.  Our understanding is that there isn't levels of rights - it's an all or nothing thing.

But our committer policy as a project is pretty straight forward. Get two significant PRs merged, and then we initiate committer status on the project itself.

I think if GitHub offered more flexibility, having a moderator role would make a lot of sense.

**Comment by shadowcodex** [comment]
I think that makes a lot of sense, and githubs permissions do need some more granularity. 

However contributions to the docs, wiki, activity on issues, etc aren't reflected in the list contributors are they? Since those are non-pull related activities.

**Comment by TylerJewell** [comment]
We are in the process of converting all of the docs to be a markdown that is part of the repo.  We just need a weekend to finalize it one of these days.  And the wiki is governed by commit rights, but there is no PR process for that.  Activity on issues is open to anyone.

So yes, today, those things all are tracked through value contributions.  I mean if you wanted to take from @jamesdrummond over the final stages of the docs conversion project from readme.io to our GitHub repo, offering a PR, that would definitely count as a major PR>

I wrote a converter that transforms readme.io into GitHub markdown, but it needs to be run against a lot of docs, and then there are some items which need manual conversion.

Also, I am working this weekend to finalize the new Che CLI, so that the CLI format for Codenvy will now work for Che.  That is a massive project, and once that is done, getting started with Che will be 2x easier.

**Comment by shadowcodex** [comment]
Moving from readme.io to github makes those contributions show better for sure. I did make a wiki change today so that works as well. 

Well my thoughts are over so I'll close this thread.
