### ISSUE TITLE
Improve buttons on the part toolbar

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#3152]
As it was discussed buttons on the part toolbar have to be improved.

![improve toolbar buttons](https://cloud.githubusercontent.com/assets/1655894/20559607/0a04d98c-b17e-11e6-9e77-75adfe2d56ea.png)

@slemeur could you please provide details for the issue?

**Comment by slemeur** [comment]
The buttons should be:
- closer from each others
- remove the border when hover

Also we want to provide a default mecanism, so that each panel, can have as many options as possible. For that we need to avoid displaying all the options in the header of the panel, we consistently display the following buttons:
- more options : to display all the options of the panel
- fullscreen : to maximize the size of the panel
- collapse/expand

![screen shot 2016-11-23 at 12 37 28](https://cloud.githubusercontent.com/assets/1636769/20560439/a77d9e06-b179-11e6-8cf9-55140faba876.png)
