### ISSUE TITLE
Why is there connections between port 4411 and the host where the web browser is opened? 

### ISSUE THREAD

**Issue by agnesagnes** [eclipse-che/che#3211]
I'm currently trying to understand how the che-websocket-terminal works. And, to first understand the communications done, I wrote lsof -i:4411. 
I would like to know why you need to open ports on the host where the web page is opened? (By the way I'm using Eclipse Che 4.7.0 but I see the che-websocket-terminal project didn't change since).

Result of lsof -i:4411:
```
COMMAND ...   NAME 
che-webso   .... xxxx:4411->ip.of.first.computer:57280 (ESTABLISHED)
che-webso   .... xxxx:4411->ip.of.first.computer:57288 (ESTABLISHED)
che-webso   .... xxxx:4411->ip.of.second.computer:59689 (ESTABLISHED)
che-webso   .... xxxx:4411->ip.of.second.computer:59691 (ESTABLISHED)
che-webso   .... xxxx:4411->ip.of.second.computer:57280 (ESTABLISHED)
```
ip.of.first.computer/ip.of.second.computer is the ip of the first/second host where I opened an Eclipse Che workspace in a web browser.
Each time I click on "New terminal" that inputs a new terminal, a new connection is established. (by the way, when I close the terminal, the connection is still there).

**Comment by TylerJewell** [comment]
@vkuznyetsov - can you please ask someone about the details of this?

**Comment by AndrienkoAleksandr** [comment]
Hi @agnesagnes . For now we didn't implement yet restore terminal, so we create separated terminal process for every new one websocket connection. We can kill terminal process and it's child processes on closing websocket connection, but it has bad side effect: if user started some long time background process (for example started tomcat server with some application) after refreshing browser page, user will see that his process was killed.  We can detaches child processes and kill terminal process, but it worse and it is not safe operation, some child processes can  not be detached at all, some of them become unstable state (and user won't be know what happen) and detaching process operation is OS dependent.  I think good desing it will be implement terminal restore. And about "connection is still" alive. I think  it should be fixed by https://github.com/eclipse/che-lib/pull/11. Can you get me more detail about this? And about open port, we have authentification on the Codenvy terminal, but for CHE terminal it is not implemented.

**Comment by AndrienkoAleksandr** [comment]
https://github.com/eclipse/che/issues/3216  maybe it's related.
