### ISSUE TITLE
Using Eclipse Che for developing apps on Raspberry pi

### ISSUE THREAD

**Issue by vijaypa1** [eclipse-che/che#3273]
Hi ,
 I was wondering if there is any information available on  - how to configure Eclipse Che IDE(running on a desktop/laptop) to cross-compile code for raspberry pi (kernel/apps). i saw an article on how to run Eclipse Che on Raspberry pi (native compilation), but that is different from my need. Thanks in advance.

regards
Vijay

**Comment by olexii4** [comment]
Hi @Vijay
It shouldn't be a problem because standard stack for C++ could be with needed configuration. 
You need to take care about cross compilation tools yourself. For example: 
https://github.com/codenvy/dockerfiles/blob/master/artik/Dockerfile

Here we install cross compilation tools for Artik ARM7 based devices. You may use the same approach and create a custom stack with these tools installed. Or maybe use codenvy/artik image.

Then check GDB settings for your workspace according to https://sourceware.org/gdb/wiki/BuildingCrossGDBandGDBserver.
Send result your binaries(helloworld) into target device and run it with gdbserver (it can be a new custom command)
for example:  
scp ./helloworld root@172.19.20.223:/root/che
gdbserver 172.19.20.223:9001 che/helloworld
Then open the helloworld.cpp file and try debugging (Run/Debug configuration — set target host and port).

We have experience  with devices for OpenWrt (C/C++ Development) such as router with MIPS32 processor.

-- 
Sincerely,
Oleksii Orel
oorel@codenvy.com

**Comment by vijaypa1** [comment]
Hi @olexii4 ,
 Thank you for the inputs. Shall try it out and post my experience.

regards
vijay

**Comment by ghost** [comment]
@vijaypa1 you need to create a custom stack with the following recipe:

`FROM codenvy/artik`

There are two envs that call cross compilation tools:

```
$CC for arm-linux-gnueabi-gcc
$$ for arm-linux-gnueabi-g++
```

**Comment by vijaypa1** [comment]
was able to lauch che ide and cross compile for ARM architecture.
