### ISSUE TITLE
Privileged mode does not work

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#3549]
**Reproduction Steps:**

1. Edit che.env to make sure `CHE_DOCKER_PRIVILEGE__MODE=true`
2. Restart Che

**Expected behavior:**

Workspace container is started in a privileged mode

**Observed behavior:**

Workspace container does not start in privileged mode.

**Comment by TylerJewell** [comment]
Is the var spelled correctly?  Try privileged.

**Comment by ghost** [comment]
@TylerJewell I tried it but all in vain - containers start in a non privileged mode.

**Comment by TylerJewell** [comment]
BUMMER - worth a try.  @eivantsov - for whomever gets assigned this issue, @bmicklea and I noticed an inconsistency in the variables.  Let's fix that as well.  In che.properties and in che.env, we have seen different spellings of this variable.  Let's make sure that all spellings are always PRIVILEGED__MODE instead of PRIVILGE__MODE, which is an incorrect grammar spelling.

**Comment by ghost** [comment]
var name is identical to property name - https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L131

Yes, privilegED is the right way to spell.

**Comment by mmorhun** [comment]
Done
