### ISSUE TITLE
Problems when building new dockerfiles

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#3559]
I'm using: 
- Che version 5.0.0
- Mac OSX 10.11.6
- Docker 1.13.0-rc4

Trying to build centOS based Che I came up against some problems that I'm listing below.

**1/ Bulding dockerfiles/lib fails**
The error is 
```
./lib-typescript/src/api/dto/che-dto.ts(10126,9): error TS2393: Duplicate function implementation.
The command '/bin/sh -c cd /lib-typescript/ && npm install && cd /runtime && npm install && /lib-typescript/node_modules/.bin/tsc --project /lib-typescript/ && mv /lib-typescript/lib /che-lib && cd /lib-typescript/src && find . -name "*.properties" -exec install -D {} /che-lib/{} \;    && rm -rf /lib-typescript && mv /runtime/node_modules /che-lib && rm -rf /runtime' returned a non-zero code: 2
```
to reproduce it run
```bash
cd dockerfiles/lib
./build.sh
```

**2/ Version `nightly` of `che-base` is used when building che-cli `latest`**
Running `dockerfiles/cli/build.sh <tag>` builds image `eclipse/che-cli:<tag>`. But the base image used to build it is always `eclipse/che-base:nightly`. There is no way to use `eclipse/che-base:<tag>` instead.

**3/ I wasn't able to run Che with a version that is not in dockerfiles/cli/version/**
Running `dockerfiles/build-all.sh latest-centos` builds all images with tag `latest-centos`. When I try to start Che using that version I get an error:
```bash
docker run -ti --rm -v /Users/mloriedo/.che:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che-cli:latest-centos start
INFO: (che cli): Checking registry for version 'latest-centos' images

We could not find version 'latest-centos'. Available versions:
 4.7.2
 5.0.0-M5
 5.0.0-M6
 5.0.0-M7
 5.0.0-M8
 latest
 latest.ver
 nightly

Set CHE_VERSION=<version> and rerun.
```
And setting CHE_VERSION doesn't help:
```bash 
docker run -e CHE_VERSION=latest-centos -ti --rm -v /Users/mloriedo/.che:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che-cli:latest-centos start
```

NOTE: None of these issue is blocking (i.e. I've been able to build a CentOS based Che). I'm sorry if these have already been reported: I've briefly searched for similar problems among existing issues but haven't found anything.

**Comment by TylerJewell** [comment]
@l0rd - We will need Florent to return from maternity leave (he just had his first child) to help us diagnose the /lib/ issue.

We will also need Florent to comment on the intention of building a particular tag of the CLI and whether the expectation is that it also builds an identical tag (or inherits from the same base image) of che-base. He did the refactoring, so we need to be clear on the expectation.  I've only ever seen eclipse/che-base:nightly referenced in all of the other images, so we need to find out if he expected eclipse/che-base to be versioned.

As to the last part, i can answer that question. That is behaving as expected. There is no longer version setting based upon CHE_VERSION environment variable. All version information is inherited from the tag of the image.  So if you ran eclipse/che:nightly, then that is the version of the software that is expected. It is now *required* that the version information that the Docker container will look up be located *within* the same image that was referenced in the /version/ folder. The information in the `/version` folder is information that the CLI needs in order to do its job for tihs particular version. In particular, it has information about the images that must be downloaded by the CLI for this version to work. The formulation of the content of `/version` is now handled as part of a CI sysystem during the release and nightly build process. 

The CLI also now has built in checks to compare the version of the image and the version of Che that you have installed on disk using the `init()` method. When you initialize a directory, we insert a version.do_not_modify file in that folder. On every execution of the CLI, we compare the image version with the version on disk. If they do not match, then we stop execution. This is how we keep integrity of the CLI image that you are running with the version that you have on disk. The only exception to this rule is if you are using the `upgrade()` command. In this case, the CLI image MUST be newer than the image on disk, otherwise the command will terminate.

**Comment by l0rd** [comment]
@TylerJewell No problem, I'm ok with **3/** as being "work as expected". I will need to change my current workflow to use/build Che locally but that's not a big deal. The new cli has a lot of cool stuff so if this is the price to pay I'll buy it 😄

**Comment by benoitf** [comment]
@l0rd about issue 1/
 - do you have more details ?
       On CI system it's building fine: https://ci.codenvycorp.com/view/nightly-builds/job/che-lib-docker-image-nightly/
    Could you provide me the file `./lib-typescript/src/api/dto/che-dto.ts` that is generated ?

about issue 2/
 - AFAIK we can't use parametrized build (--build-arg) for the FROM instruction
so build.sh could replace the parent tag with a "parent" parameter to build.sh ? (or use parent = provided tag by default)

**Comment by l0rd** [comment]
@benoitf thanks for your feedback.

Issue 1/ has been fixed. I've just verified it with version 5.0.0.

For issue 2/ I haven't found a better solution neither: `build.sh` should replace the tag of `che-cli` parent image on the fly (`FROM eclipse/che-base:nightly` => `FROM eclipse/che-base:<parent-tag>`). I would prefer to set `<parent-tag>=<che-cli-tag>` by default.

**Comment by benoitf** [comment]
I think this issue can be closed now as build.sh is overriding the FROM image in PR https://github.com/eclipse/che/issues/4336

**Comment by benoitf** [comment]
@l0rd Please reopen if not working for you but now parent image is replaced on the fly
