### ISSUE TITLE
eclipse 'bin' in gitignore ignores nessacery path of che/assembly/assembly-main/src/assembly/bin/

### ISSUE THREAD

**Issue by elpddev** [eclipse-che/che#3733]
Not sure if this is a correct workflow for che.

1. Cloning the project.
2. Checking out the desired version tag. ex 5.0.0.
3. Removing .git folder in order to start fresh without all the history commits.
4. Git add all.

Here the git add is skipping the `che/assembly/assembly-main/src/assembly/bin/` path.
That is because the main `gitignore` includes `bin` as a directory to igonore in all level (eclipse).
https://github.com/eclipse/che/blob/master/.gitignore#L9

I the desire is to ignore eclipse generated bin folders then maybe there could be a .gitignore in the `assembly-main/src/assembly/` path that include a negate line for the `bin` folder

```gitignore
!bin/
```

**Comment by TylerJewell** [comment]
Hello Eyal:

Thanks for opening an issue to discuss.  First a grain of salt in that I am not a git expert so please take my probing lightly.

Could you comment a little bit on why your proposed workflow is important?  I haven't heard of anyone wanting to delete the default git files from a clone of our repo before. What is the advantage of removing the history?

Your proposal for how to solve the problem seems fine.  We will need sergey Kabashniuk to comment on it, but we would likely accept a pr for it from you if you wanted.

**Comment by elpddev** [comment]
Its a convenience issue without forking. When trying to write a plugin. The plugin itself can reside on different repository but current plugin installation into CHE is only through code pom xml changes so the CHE repo iself needs to be part of my project. For now I kept the history but renamed the master branch and the origin remote.

**Comment by TylerJewell** [comment]
Thanks for the explanation. We are starting this quarter in thinking about how to build better utilities related to generating and maintaining custom assemblies.  @skabashnyuk - would you like this improvement to be added as a PR from @elpddev or would you prefer to include it within this issue: https://github.com/eclipse/che/issues/3697
