### ISSUE TITLE
Support: Help Getting Che Master & Agent To Connect

### ISSUE THREAD

**Issue by johnlabarge** [eclipse-che/che#3737]
I'm trying to override the api URL in che to use my host ip address (eventually host dns name).  I'm trying to run che behind an nginx reverse proxy.  It is partially successful, but the api calls are failing to get the stack icons. 

I followed the directions in the overriding internals and made every effort to override the HOSTNAME and IP properties with that of my compute instance here represented as (IP):

#!/bin/sh
docker run -d \
-p 8080:8080 \
--name che \
--restart always \
-e CHE_IP=(IP) \
-e CHE_HOSTNAME=(IP) \
-e CHE_HOST_IP=(IP) \
-e CHE_DOCKER_MACHINE_HOST=(IP) \
-e CHE_CONF_FOLDER=/conf \
-v /home/johnlabarge/che:/conf \
-v /var/run/docker.sock:/var/run/docker.sock eclipse/che-server:5.0.0-latest 

In my che.properties (whose directory I verified is mounted correctly) I overrode:
che.api=http://(IP)/wsmaster/api
che.workspace.che_server_endpoint=http://(IP)/wsmaster/api

In the browser my container images are broken and I see the following errors: 

127.0.0.1:8080/wsmaster/api/stack/php-default/icon:1 GET http://127.0.0.1:8080/wsmaster/api/stack/php-default/icon net::ERR_CONNECTION_REFUSED

**Che version:**  5.0.0-latest

**OS and version:** 
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie

**Docker version:**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:17:57 2017
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:17:57 2017
 OS/Arch:      linux/amd64

**Comment by TylerJewell** [comment]
Hi John:

Sorry you are having this problem.  I would discourage you from using that syntax as it is a lower level docker syntax which allows for a lot of overrides but at times what you override and the expected behavior is not entirely well explained

Can you try the new cli which is a launcher for this container with a dramatically simpler interface?  Start by running docker run eclipse/che to get the syntax of what to run next.  

The only value you should have to override is CHE_HOST.

**Comment by johnlabarge** [comment]
Thanks! I'm trying that now and I've got the following, but no container seems to be started.
johnlabarge@eclipse-che-buildup:~$ docker run -it --rm -e CHE_HOST=(IP) -v /var/run/docker.sock:/var/run/docker.sock -v data:/data -v instance:/data/instance -v backup:/data/backup eclipse/che-cli:latest start 
WARN: You are using CLI image version 'latest' which is set to '5.0.1'.
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
INFO: (che cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
INFO: (che cli): Loading cli...
INFO: (che cli): Checking registry for version '5.0.1' images
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
         port 8080 (http):       [AVAILABLE] 
INFO: (che start): Starting containers...

**Comment by TylerJewell** [comment]
Can you tail the cli.log file in the :/data folder?

**Comment by TylerJewell** [comment]
Also why are you mounting folders that are optional?  Let's do just the minimal options to start.

**Comment by johnlabarge** [comment]
It's requiring me to mount them. And my bad I didn't use full paths.

**Comment by TylerJewell** [comment]
The only mandatory mount is the :/data not the instance and backup folders.

**Comment by johnlabarge** [comment]
That's right.  It starts only requiring the :/data mount.  However, I still have the same icon problem with wsmaster  @ 127.0.0.1:8080 and further have the following exception: 

Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace b
oot.
java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout. The Che server is unable to pin
g your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_111]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$startAsync$1(WorkspaceManager.java:623) ~[che-core-api-workspace-5.0.1.jar:5.0.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.0.1.jar:5.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
Caused by: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout. The Che server is unable to ping your workspace. This implies
 a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:705) ~[che-core-api-workspace-5.0.1.jar:5.0.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:249) ~[che-core-api-workspace-5.0.1.jar:5.0.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.0.1.jar:5.0.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
        ... 3 common frames omitted

**Comment by TylerJewell** [comment]
What happens if you run it without CHE HOST being set?  We should detect the right IP address.

**Comment by johnlabarge** [comment]
Same.

**Comment by TylerJewell** [comment]
Ok it is now either a firewall configuration that is blocking traffic or the nature of the IP address exposed.  You can override networking parameters with instructions in the Che.env file.

Also what does ifconfig show and the output of 'docker run --net=host eclipse/che-ip:nightly'?

**Comment by johnlabarge** [comment]
internal IP address: 10.128.0.2

But the dashboard is still trying to get the stack icons from e.g. http://127.0.0.1:8080/wsmaster/api/stack/node-default/icon 

I tried passing in the public IP and Port=80. 

Still the same result.  I started down the above path in the first post because I couldn't seem to get wsmaster calls to use the right ip address.

**Comment by TylerJewell** [comment]
I think you are making some assumptions here that are making it challenging for me to diagnose.  Try to ignore what the browser is doing internally - we make certain optimizations because of docker.

Can you let me know about the ifconfig output and the Che IP utility?  We need to see that and then look at the network paths between Che and docker.

**Comment by johnlabarge** [comment]
br-8a8e0b40de76 Link encap:Ethernet  HWaddr 02:42:db:b3:96:26  
          inet addr:172.18.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:536 (536.0 B)  TX bytes:0 (0.0 B)
docker0   Link encap:Ethernet  HWaddr 02:42:76:20:84:fe  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13296 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12819 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:68078949 (64.9 MiB)  TX bytes:37130976 (35.4 MiB)
eth0      Link encap:Ethernet  HWaddr 42:01:0a:80:00:02  
          inet addr:10.128.0.2  Bcast:10.128.0.2  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:192265 errors:0 dropped:0 overruns:0 frame:0
          TX packets:131357 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2084621011 (1.9 GiB)  TX bytes:81657628 (77.8 MiB)
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:16173 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16173 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:68417579 (65.2 MiB)  TX bytes:68417579 (65.2 MiB)
veth7197496 Link encap:Ethernet  HWaddr ba:e1:1a:e6:f9:fc  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1697 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1599 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:11134021 (10.6 MiB)  TX bytes:181972 (177.7 KiB)

veth077861f Link encap:Ethernet  HWaddr d2:68:9e:c4:e0:03  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:49 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:4691 (4.5 KiB)  TX bytes:28564 (27.8 KiB)

vethceaa345 Link encap:Ethernet  HWaddr e2:ec:d0:c8:4c:09  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:648 (648.0 B)  TX bytes:0 (0.0 B)

johnlabarge@eclipse-che-buildup:~/data$ 
johnlabarge@eclipse-che-buildup:~/data$ docker run --net=host eclipse/che-ip:nightly
10.128.0.2

**Comment by TylerJewell** [comment]
Ok - legitimately stumped.  I have to get on my home computer and investigate the options in the config for routing between Che and your workspaces.  There is a network option you set in Che.env

**Comment by johnlabarge** [comment]
Ahhh each and every problem was due to me not having configured web sockets through nginx correctly. I thought I could address that afterwards, but it must use that to get the hostnames correct.

**Comment by johnlabarge** [comment]
Oh no.   Actually all the browser problems were related to websockets. Workspace creation still failing because : "The Che server is unable to ping your workspace." But at least the UI is working now.

**Comment by johnlabarge** [comment]
Ok now the problem is that the che server is actually using the external IP (no longer supplied CHE_HOST) to connect to the workspace - which will not work because of the firewall.   I tried supplying -e CHE_DOCKER_MACHINE_HOST=localhost (my perhaps incorrect interpretation of https://eclipse-che.readme.io/docs/networking)

**Comment by TylerJewell** [comment]
Hi - can you let me know how you got to that page?  

We (this week) replaced the readme.io with all new docs hosted at www.eclipse.org/che/docs.  All of the site links (and links in the product to docs) should be pointing only to this new address.  So if you got to the old one somehow, then we need to find it and remove it.

As for setting CHE_DOCKER_MACHINE_HOST. With 5.0, we dramatically simplified how properties are set.  After you do your first run, in the folder where the cli.log is, there is a `che.env` file. You just edit the appropriate property in that file and restart Che.  There is a section on networking that gives you instructions on the properties that you want to change there, and the ones that affect Che server -> workspace communications.  Can you give that a go, please.

**Comment by TylerJewell** [comment]
One more test, too - we have in the CLI an "info --network" command that you can run which will simulate a configuration test between browser and agent, browser and che, and che -> agent.  Can you also run this and provide output?

**Comment by ghost** [comment]
@johnlabarge perhaps you need to override just CHE_DOCKER_IP_EXTERNAL. This is what your browser will use to connect to workspace agent, while server will reach it over docker0 IP. You can change CHE_DOCKER_IP_EXTERNAL value in che.env.)

**Comment by johnlabarge** [comment]
I got to that page from here: https://eclipse-che.readme.io/docs/.  It's the one linked from the left hand side menu.  
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: Browser    => Workspace Agent (localhost): Connection failed
INFO: Browser    => Workspace Agent (10.128.0.2): Connection succeeded
INFO: Server     => Workspace Agent (External IP): Connection succeeded
INFO: Server     => Workspace Agent (Internal IP): Connection succeeded

Since I'm using a cloud instance (which I'm trying to provision myself) that 10.128.0.2 address will not be available to the browser.  

Am I reading this right that I  need to expose all ports above 32768 to the internet?  Could this be the problem the workspace agent isn't accessible?

**Comment by johnlabarge** [comment]
Opening up the upper ports seems to resolve the workspace creation issue (though it's concerning).   The only issue I have now is that the UI now hangs at "starting workspace" though it is successful in doing so (If I click out and then click on the workspace it works).  It also used to show a console with docker starting a container etc. but no longer does that :/ . This is a very cool project I must say.

**Comment by TylerJewell** [comment]
Could you elaborate just a bit more on the statement, "it's the one linked from the left hand side menu".  If you are talking about the menu in the product, it should be pointing to a set of docs that are deployed within Che itself - and not to that link. So that just may mean that you are deploying an older version unexpectedly, or you have stumbled into a bug that we have with one of our links pointing to an old location.  Thanks for helping us chase this part down.

Ok, so the outputs from the connectivity test are a good sign. It's rarely that both Browser => workspace agent works for both `localhost` and your external IP address.  So, I believe that Eugene's suggestion of modifying `che.env` to have `CHE_DOCKER_MACHINE_HOST` point to 10.128.0.2 is the right configuration so that browsers can connect directly to each workspace.

As to the question about the necessity of opening ports.  In addition to port 8080 and a couple others used by the Che server itself, we also require ports opened from 32768+.  You can start at one, but it goes up to potentially 10000 more depending upon how many workspaces you are running and how many servers you are running within those workspaces.

Ports 32768+ are the ephemeral port range. When you run servers inside of your workspace, those bind to an internal port, say `900` or whatever you start the mon.  Docker then maps those internal ports into the ephemeral port range, and this is what is publicly exposed.  When you run a command in the workspace, we will show you the preview URL which is the dynamic URL of your workspace with the ephemeral port that the service inside was mapped to.  We don't let your internal port map to 900 on the outside because there would be port conflicts.  Imagine a world where you had two workspaces deployed at the same time on the same server and each user of each workspace runs a server both binding to port 900.  It's ok for them to internally bind at port 900 but externally, there is only a single port 900 available.  So Docker starts by giving the first process to port 32768 and then increments from there.

We will be working with Red Hat throughout 2017 to implement a port forwarding system so that all traffic will run through a single port on a proxy.  It will slow performance, but for security-sensitive deployments this may be a nice option.  I think we would have something by end of Q2 - it's rather tricky to implement.

**Comment by johnlabarge** [comment]
Left hand side list of links on this page: https://eclipse-che.readme.io/docs which is different than http://www.eclipse.org/che/doc.  Also it pops up on google at a higher ranking.

**Comment by TylerJewell** [comment]
But how did you find the readme.io site to begin with?  We had that linked off of the Che home page until about a week ago.  So if you began your explanation over a week ago then that explains how you found the link.  However if you just started a couple days ago then there shouldn't be any more evidence of that site unless you enter ts address directly.

**Comment by johnlabarge** [comment]
Google: eclipse che networking.

**Comment by TylerJewell** [comment]
@bmicklea @JamesDrummond - maybe the solution to address Google history is that we setup redirects in the old readme.io pages over to eclipse.org/che/docs so that we can avoid this issue?  I think what @johnlabarge did would not be uncommon. 

Or can we get google to update all of its search index to only point to eclipse?

**Comment by bmicklea** [comment]
We're investigating this.

**Comment by TylerJewell** [comment]
Closing this as the original issue was resolved.
