### ISSUE TITLE
the commands from samples.json don't appear

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3794]
I have created a blank workspace and in it I have created an angular-patternfly-starter project (from the sample group). It appeared in the project explorer, but the commands  assigned for this sample 
```
"commands": [
      {
        "name": "install dependencies",
        "type": "custom",
        "commandLine": "cd ${current.project.path} && npm install --no-bin-links && bower install",
        "attributes": {
          "previewUrl": ""
        }
      },
      {
        "name": "run",
        "type": "custom",
        "commandLine": "cd ${current.project.path} && grunt server",
        "attributes": {
          "previewUrl": "http://${server.port.8003}"
        }
      }
    ],
```
did not appear in the CMD dropbox.

**Che version:**  5.0.0
**OS and version:**    Ubuntu 16.04
**Docker version:** 1.12.5

**Comment by ghost** [comment]
@aleksei-burakov this happens when you create a project from within an IDE.

If you create projects from User Dashboard, then it is UD that updates the workspace with commands that a sample provides.

**Comment by aleksei-burlakov** [comment]
@eivantsov Will it be changed in future, or is it a normal behaviour?

**Comment by TylerJewell** [comment]
Right now this is expected behavior.  Commands created outside the ide in a template or stack flow into the ws when it is created.

We don't yet have a way to capture new commands built while the workspace is running and then saved back into the stack that the ws was created from.  But we will eventually....  check out the epic on intelligent commands.
