### ISSUE TITLE
Help securing the websocket calls from the browser? 

### ISSUE THREAD

**Issue by johnlabarge** [eclipse-che/che#3861]
I'm trying to secure my own IDE on the cloud behind nginx and looking for any ideas on doing so.  Currently it appears that the browser code is trying to connect through to the workspace on the 30XXX port using "ws://" instead of "wss://".  I'm also relatively sure I haven't set up nginx to properly proxy those connections.  I'm wondering if there is a proxied mode or something I can use to fix the websocket calls or if there is some other approach.

**Comment by TylerJewell** [comment]
Right now the recommended path is for you to install Codenvy.  We have free 3 user license for those that are looking to set up their own cloud system. Codenvy has the security and routing built in.

Securing the workspaces are more challenging than just handling nginx routing. The surface area of attack vectors is the Che server, each workspace's API, their terminal servers, and any agents that are deployed within those, along with the file systems for each of the workspaces.  So there is tokenization of the access that has to be intercepted for each of these surface area points.  And then this problem is compounded a bit more when your users start running their own servers in the workspaces, which get their own ports and attack vectors.

Then there is the layering of HTTP vs. HTTPS and the same for ws vs. wss://.  The SSL layer is only implemented within Codenvy right now, as it requires a different certificate management infrastructure (and as you have seen routing).

So the Codenvy deployment of Che has the same CLI syntax, but takes care to set up haproxy, nginx, and the security certificates.

There are multiple people that have set up the nginx routing for unsecured protocols.  And we are going to be making this simpler throughout this calendar year by embedding an nginx router that channels the traffic through a more narrow set of ports.  But this is going to take us (Codenvy and Red Hat) a few quarters to get it sorted out.

**Comment by vinokurig** [comment]
@johnlabarge Do you have more questions about this?

**Comment by ghost** [comment]
@johnlabarge we're closing the issue. https support isn't implemented for Che. If you have questions or contributions in this regard, feel free to reopen.
