### ISSUE TITLE
Closing many files shows an ugly blocking loaders

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#3890]
See the attached gifs

![closing-lot-of-files](https://cloud.githubusercontent.com/assets/1636769/22268773/041e2a00-e289-11e6-9a43-ccb4ea905c97.gif)

When you are closing many files at the same time, it shows "Upload files" and it probably shows it for as many files were opened.

We should display a single loader, even if in background multiple operations are triggered.

**Reproduction Steps:**
Open many files and ask the editor to close them all.

**Che version:**  5.1.2
**OS and version:** MAC OS X 10.12.2
**Docker version:** 1.12.3

**Comment by slemeur** [comment]
@dkuleshov do you have an idea?

**Comment by sr229** [comment]
seems every tab has their own loading dialogues/overlays and they overlap to each other

**Comment by dkulieshov** [comment]
@slemeur of course I do, this erroneous behavior happens because of not well optimized save/update project tree/resources, there is an issue which is not directly related but should fix this problem as well: https://github.com/eclipse/che/issues/3467

@sr229 you're right, in fact each tab closing requires project tree update and each such operation may result in a loader. In most cases you don't see any loader because the operations take too little time, while in our case we have extraordinary long operations so loaders stacks.

**Comment by vzhukovs** [comment]
Fixed with https://github.com/eclipse/che/commit/194f044aa2c2ff409ba088db24ab14e80e4935db
