### ISSUE TITLE
The links in Readme files of plugin samples are not actual 

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4036]
**Reproduction Steps:** Open for instance file of the plugin by path like: che/samples/sample-plugin-actions/README.md. Try to use link from `Read the tutorial at: https://eclipse-che.readme.io/v5.0/docs/actions` section. 
 We have: 404 Page Not Found.

**Comment by TylerJewell** [comment]
I am including Sergii and Stevan LeMeur in this conversation.  @skabashnyuk - question for you.  If we release the che-archetypes capability, should we still have these samples?  Or, would it be better for us to remove all of these samples and to only support them through archetypes?

If we are going to keep the samples, we should update the README and leave this as a bug.  If we are going to replace these examples with archetypes, then we should make sure that those archetypes cover all of these scenarios so that our docs work, and this is more of a kind/task on the conversion.

**Comment by slemeur** [comment]
@skabashnyuk I think we should revisit those documentation according to the new maven archetype you built.

**Comment by ghost** [comment]
@TylerJewell @slemeur why do we need samples if che-archetypes do a perfect job of generating custom assemblies with custom plugins?

**Comment by TylerJewell** [comment]
@eivantsov - can you point me to what you are thinking are samples?  I am worried the term is overloaded. So I want to make sure we are thinking about the same concept.

**Comment by TylerJewell** [comment]
Yep @eivantsov is correct.  We should remove these from the repository, make sure our docs have no references to them, and only use archetypes instead.

**Comment by skabashnyuk** [comment]
Depends on https://github.com/eclipse/che/issues/6280
