### ISSUE TITLE
CHE_SERVER_IMAGE_NAME in 4.7.0 changed for 5.2.2?

### ISSUE THREAD

**Issue by agnesagnes** [eclipse-che/che#4047]
Hello,

I need an information: until now I was using version 4.7.0, but just switched for the 5.2.2. I was previously using -e CHE_SERVER_IMAGE_NAME=name_custom_image in order to have a custom che-server image. However, this variable seems to have no effect with version 5.2.2. I tried to find documentation about it but only found this: https://www.eclipse.org/che/docs/setup/docker/index.html that does not refer to it.

**Comment by TylerJewell** [comment]
See - https://www.eclipse.org/che/docs/setup/getting-started/index.html#multiple-containers

Syntax is changed, please use the new CLI.

**Comment by agnesagnes** [comment]
Thank you!

**Comment by agnesagnes** [comment]
Sorry to bother you again but if I understand correctly the link you sent me is about giving a name to a container launched from the image eclipse/che-server.
But what I would like is to specify that I don't want to use eclipse/che-server but another image (with custom changes).

**Comment by TylerJewell** [comment]
Ok - I haven't tested this, but if you pass in `-e IMAGE_CHE=<new-image-name>`, then this should replace eclipse/che-server with the image you want to use.  

You can verify this by running "config" command and then inspecting the docker.compose.yml file generated in the /instance folder.

**Comment by agnesagnes** [comment]
It seems IMAGE_CHE doesn't work, I still have eclipse/che-server:5.2.2 in docker-compose.yml. And I have another question: By directly launching che-server, we can specify CHE_LOCAL_CONF_DIR. What about the cli eclipse/che ?

**Comment by TylerJewell** [comment]
@agnesagnes - sorry it is taking me some time to response.  I am doing battle with a head cold.  It's an epic war.

I think it didn't change because we are not iterating through command line parameters to add them to the che.env.  What happens if you just add `IMAGE_CHE=<name>` directly into the `che.env` file as a line (you can put the line anywhere).  This will guarantee that the parameter is passed into our puppet engine which generates the `docker.compose.yml` file used to start che.

As for `CHE_LOCAL_CONF_DIR`, we are now discouraging people from providing their own custom che.properties that is mounted into `eclipse/che-server` as the model for doing that is not great as an admin lifecycle.  You can:

1. Any parameter in che.env can be passed into the che.properties.  So, "che.property_full" would be `CHE_PROPERTY__FULL=<value>` in the che.env.  We document how this [works here](https://www.eclipse.org/che/docs/setup/configuration/index.html#internal-configuration).

2. At the end of the day, it's still the same `eclipse/che-server` container that is run as a compose service.  So any variables you put into che.env will be passed directly in as variables into this container.  So you can also add CHE_LOCAL_CONF_DIR into the che.env.  But I haven't tested this configuration.  You'll want to run the CLI's "config" command and then go into `/instance/docker-compose-container.yml` and make sure that the compose syntax that is generated is the right one.

**Comment by agnesagnes** [comment]
@TylerJewell  I hope your energy and health came back to normal!  (20 days, I hope so)

Unfortunately IMAGE_CHE=<name> did nothing. it seems that the variable is not transmitted to the che.env inside the container (other variables are modified thanks to che.env as you told me, so I guess this is a specific problem with IMAGE_CHE).  For information, I modified /data/che.env. And in the end /data/instance/config/che.env didn't take into account IMAGE_CHE. 

I have a last question: In order to change variables, I directly modified /data/che.env, is there an environment variable to specify another che.env location?

**Comment by TylerJewell** [comment]
@agnesagnes - I am feeling much better - thank you for thinking of me that way.

I see what the issue is.  It has to do with the way that the CLI was structured.  

The CLI loads a series of images that are defined inside of the eclipse/che-cli image under `/version/<version>/images`. This file is updated for every version that we have and it includes a `NAME=VALUE` list of the exact Docker images and tags that must be used. This way we can guarantee that users aren't messing around and providing the wrong tags.  Inside this file is `IMAGE_CHE=eclipse/che-server:<version>`.  And this file is loaded at the last minute when generating the configuration.  So this is why your `IMAGE_CHE` is not getting taken.

We have had (quite a few) requests from our internal engineers to allow on the command line some sort of way to override this capability. For example, if we want to run unit tests across a branch, we may generate custom images with tags for that branch and then want to make use of a different registry set instead of the ones that we have provided embedded within the image.

I'll need some time to think about how to provide this functionality properly as I would want to do it generically so that our CI systems can really handle custom registry lists.

In the mean time, there is a slight work around:
1. You can install and configure Che with `config` command.
2. You can go into `/instance/docker-compose-container.yml` and physically change the container or image you want to use.
3. When you run `start` with the CLI add the `--skip:config` hidden parameter. This will skip the configuration step which overwrites things that are in `/instance` folder.  This flag was added a couple days ago, so it's probably only in nightly.
