### ISSUE TITLE
The "Delete"  widget appears when editing the "Commands" form.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4059]
**Reproduction Steps:**

- Open any project in the IDE.
- In the "Project Explorer" set selection on any file or folder. 
- Toolbar -> Command Widget -> Edit commands...
- Create the "Custom" command, in the "command line" press "Delete" button.

**Expected behavior:**

- Current symbol should be deleted.

**Observed behavior:**

-  The dialog widget appears with proposition to delete the selected file or folder in "Project Explorer".

Che version: 5.3.0-SNAPSHOT
OS and version: Ubuntu 16.04  LTS
Docker version: 1.12.3
Che install: Docker container

**Additional information:**

Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![anim](https://cloud.githubusercontent.com/assets/7760565/22740498/b28e1074-ee18-11e6-93bb-eebd3162424d.gif)

**Comment by TylerJewell** [comment]
@SkorikSergey - thank you for reporting this bug.  It's an actual bug - just confirmed it.  

You may not be aware, but for a number of months, we have been working on a concept called Intelligent Commands.  This new concept is much more flexible and will replace the current command editor that we provide. It will make commands edited the same way that you do files. We have had this in a branch for awhile and will be releasing it soon.  Since this would be the preferred approach, we would not work to resolve this bug.

We will close this bug once we release Intelligent Commands.  The epic for it is:
https://github.com/eclipse/che/issues/2681

**Comment by vzhukovs** [comment]
I'll take a look on it and will try to fix this bug. Thanks for the reporting.
