### ISSUE TITLE
Make che.sh to work again

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4090]
We should get engineer to investigate to generate a list of requirements related to what we need to modify in that so that it properly starts a Che server.

**Comment by skabashnyuk** [comment]
@TylerJewell  what is you plan for this issue. How we will handle default properties configuration. From CLI or without? Without looks simpler for me.

**Comment by TylerJewell** [comment]
There are two choices:
1. We make the defualt che.properties file a Puppet template that is generated as part of the `config` phase of the CLI, or:
2. We leave it inside of the assembly built by maven.

I would prefer #1 because we can optionally templatize the che.properties file with Puppet variables that are based upon the values of the CLI entered by the end user.  So we could pass along a custom port, for example if a user has set `CHE_PORT=9000` into the CLI into the `che.properties`, if that was necessary.
