### ISSUE TITLE
[cli] Implement backward compatible way to rename a property in che.env file

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#4190]
It's needed to have backward compatible way to rename a property in `che.env` file.
Proposed next ways to implement it:
- implement supporting old properties and using them in following priority: use old property if it's configured, otherwise use new property it is configured otherwise use default value.
- fail `che` start if there is any deprecated property, notify user about property deprecation and provide him instructions for reconfiguring system according to a new property.

**Comment by benoitf** [comment]
discussion was

`aliases.properties` file with 
CHE_OLD_VAR=CHE_NEW_VAR property

`deprecated.properties` file with 
CHE_OLD_VAR=”Text to display when we have this deprecated”

`pruned.properties` file with 
CHE_OLD_VAR=”Text to display when we have this property removed (and exit as we need to update property names)”


or only one file
`deprecated.properties`
CHE_OLD_VAR_ALIAS=CHE_NEW_VAR
CHE_OLD_VAR_TEXT="text to display when we have the deprecated property or if property is no longer supported (no _ALIAS)"

**Comment by benoitf** [comment]
@TylerJewell do you have preferences ? ideas ? comments ?

**Comment by TylerJewell** [comment]
@benoitf - I have taken some time to comment because all of the options were functionally acceptable but none of them very clean.  They all feel like a small compromise and somehow we are missing the more elegant answer.

In the absence of that clairvoyance, I think having both "alias.env" and "deprecated.env" files would make the most sense.  Which folder would they live within?
