### ISSUE TITLE
A workspace doesn't restart automatically after stopping the process(regression)

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4437]
**Reproduction Steps:**

- Start any wokrspace
- Run in the terminal a next command  
```shell 
kill -9 $(ps ax | grep java | grep ws-agent | grep conf | grep -v grep | awk '{print $1}')
```

**Expected behavior:**
The workspace should restarts

**Observed behavior:**
Nothing changed

**Failed test:** CheckRestoringWorkspaceAfterStoppingWsAgentProcess

**OS and version:**
Che(Che6 branch) 6.0.0-M5; Chrome 63.0; Fedora 25

**Additional information:**
![nimbus-record-video-2018-01-17-13-53-17](https://user-images.githubusercontent.com/7760565/35041619-04f9e2a6-fb8e-11e7-88b8-3da95688fa68.gif)

**Comment by riuvshin** [comment]
@vparfonov please take a look this is regression

**Comment by ghost** [comment]
Cannot be reproduced in 5.15-SNAPSHOT

**Comment by SkorikSergey** [comment]
This bug sometimes is reproduced on CHE.

**Comment by skabashnyuk** [comment]
is it up to date?

**Comment by ghost** [comment]
I haven't seen this one for quite a while

**Comment by riuvshin** [comment]
close ?:) @SkorikSergey do you have steps to reproduce?

**Comment by ghost** [comment]
Let's close. If the error pops up again either in tests or it's reported by users here, we'll reopen.

**Comment by SkorikSergey** [comment]
For now this issue reproduces on che-integration-tests last 5 days. https://ci.codenvycorp.com/view/qa/job/che-integration-tests/
![org eclipse che selenium miscellaneous checkwsagentafterstopprocesstest checkdialogafterkillingprocess_py8y6w5m](https://user-images.githubusercontent.com/7760565/30642545-f93e311a-9e13-11e7-9a97-2bcc341c4542.png)

**Comment by vparfonov** [comment]
@SkorikSergey and @musienko-maxim  Please check you test it fail in line 85. According flow described in your test you check Project Explorer on displaying project [(CheckWsAgentAfterStopProcessTest.java:85)](https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/CheckWsAgentAfterStopProcessTest.java#L85) for checking workspace state i think this is not correct because actually workspace started well. And yes project not displayed but in other reason described here #6314

**Comment by musienko-maxim** [comment]
It issue is not depended with #6314, the error with displaying project - this is a consequence of the error described above. According to screenshot above i don't see, that workspace started correctly.
