### ISSUE TITLE
override double click in project explorer

### ISSUE THREAD

**Issue by eladc898** [eclipse-che/che#4488]
Hello
I want to implement other action instead of opening the text editor for specific file in my custom project.
How can i achieve this?

Thanks

**Comment by vzhukovs** [comment]
Hello @eladc898. Thanks for your question. Unfortunately, there is no any mechanism to override mechanism of double clicking in project tree, because each node has own implementation of `org.eclipse.che.ide.api.data.tree.HasAction` interface. For _leaf_ nodes it usually opens the editor. So you can modify the body of this method in nodes, which extend `org.eclipse.che.ide.api.data.tree.Node`. This is the simplest way to do this. 

But this is a good question to make an enhancement in code base to implement this feature. @vparfonov wdyt of it? This is not hard to implement it.

**Comment by elpddev** [comment]
@vzhukovskii Hi, If we were to implement a custom node, how to go about it ? For now, we see that the Java plugin project implement a custom tree and node factory and then implements custom nodes.

**Comment by vzhukovs** [comment]
@eladc898 Hi, your custom node should implement a `org.eclipse.che.ide.api.data.tree.HasAction` interface for proceed custom logic for double click.

**Comment by eladc898** [comment]
Hi
How can i register the custom node in the project tree?

**Comment by vzhukovs** [comment]
@eladc898, you may create your own implementation of `org.eclipse.che.ide.api.data.tree.NodeInterceptor`, then register it in gin module `GinMultibinder.newSetBinder(binder(), NodeInterceptor.class).addBinding().to(YourNodeInterceptor.class);`. And in the implementation you can intercept any node by checking `parent` node and modify the nodes given by `children`, then return the modified list of `children` via `return`. That's all.

**Comment by ghost** [comment]
@eladc898 any update please? have you got help you have been asking for?

**Comment by ghost** [comment]
Closed due to inactivity
