### ISSUE TITLE
After deleting project with related process - process still presents

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4512]
This is issue related with epic https://github.com/eclipse/che/issues/4511
After deleting project with related process - process still presents (after refresh page - disappear)

**Reproduction Steps:**
- Go to spring project
- Run any command by command toolbar
- Stop this process
- Delete project
- Pay attention to the process bar 

**Expected behavior :**
The process bar will be clear after deleting project .

**Observed behavior :**
The process stay in the process bar after deleting project .

**See attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24198580/1de0bf18-0f0f-11e7-8d94-0c2eb274fd87.gif)

**Comment by slemeur** [comment]
This is not a bug.

A command is a process that is injected inside of the workspace's runtimes in order to be executed. A command can be linked to a project - or not. 

But if user started a command which is building a project and deploying it in a tomcat for example - even if the project is deleted, the process is still running in the workspace's runtime.

So this is actually not a bug, and by the way, today the current version is working like this.
