### ISSUE TITLE
For large project, changes on parent pom.xml is freezing the IDE

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#4757]
When I change pom.xml of a large maven project (for instance Che) IDE is freezing
 

**Reproduction Steps:**
- Import eclipse che project as maven project
- open parent/root pom.xml
- replace in dependencyManagement one of the ${che.version} with the current version (5.8.0-SNAPSHOT at the this time) for one of the che dependencies
- browser tab is freezing

**OS and version:**    

**Diagnostics:**

**Comment by sunix** [comment]
Most of the time, it happens during maven resolution phase 
![eclipse che che-master - google chrome_004](https://cloud.githubusercontent.com/assets/650571/24872166/ad74cb44-1e1c-11e7-8fa1-26bb0d347dc3.png)

**Comment by slemeur** [comment]
@vparfonov: I consider this issue as really problematic which needs to be investigated now. Could you please add it into your sprint plan.

**Comment by sunix** [comment]
hello any update on this ?

**Comment by slemeur** [comment]
@vparfonov : have you got any news on this issue?

**Comment by slemeur** [comment]
@vparfonov : Could you please give an update on this issue?

**Comment by vparfonov** [comment]
@slemeur we have more information on next few days, we started work on in last Friday

**Comment by sunix** [comment]
Hi there, I'm not sure this is a good fix.
Modifying the parent project is the cause and updating "child" projects (projects that has parent project as parent/grand parent) is necessary in some case:
If we change a dependencyManagement section in a parent pom it make sense to update child projects.
The problem is not the fact that it updates the "child" children: this is how we reproduce the freeze. The problem is that it is freezing at some point and it happens not only when you update the parent project.

**Comment by vparfonov** [comment]
@sunix so you still reproduce this issue?

**Comment by sunix** [comment]
@vparfonov Yes I have Che still freezing from times to times but it hard to reproduce. It's freezing less then before but still.

**Comment by svor** [comment]
Hi @sunix !
By "updating", I mean updating the project tree, it is not related to updating maven model. 
The problem was that after changing something in a pom.xml, maven server gives to the client (IDE) list of projects (modules and projects) where changes were made and then we sent requests to update project tree for each of them but it was unnecessary, so as a result the client was overloaded - and that was a mistake I’m talking about. So as a result the client was overloaded. 
For updating project tree we need to send a request only for the parent and all children will be updated automatically. 

The procedure of resolving a big project like a che is very heavy. So during project resolving the ide can't work as quickly as in the quiet state. If the browser is freezing in some usecases it isn't OK and I need to have steps to reproduce the problem, if you can provide their for me it will be nice.

**Comment by sunix** [comment]
@svor ok then, thanks for the explantation. I'm closing this issue and will create a new one if I find a way to reproduce the new problems.
