### ISSUE TITLE
ANSI coloring support for commands output

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#4779]
Instead of outputting the color it outputs the ANSI characters like:

![image](https://cloud.githubusercontent.com/assets/145667/24912041/38d162dc-1ecd-11e7-978b-4e6b5000a35f.png)

**Reproduction Steps:**
 1. Run a workspace running (for example Blank, in my case it was based on `codenvy/alpine_jdk8` but in my tests it looks like it's independant of the workspace image)
 2. Either run a some commands on in this case in the terminal simply type `git log` (enter).

Note that running `ls` for example, correctly shows colors. Not sure what is done differently. `echo -e "\e[31mHello World\e[0m"` also works. The same command ran in the terminal may show colors but if ran from a pre-configured "Command" it'll incorrectly render the ANSI colors.

**OS and version:**    5.7.2 Docker image (I recall this issue also affecting older versions).

**Comment by ghost** [comment]
@AndrienkoAleksandr can you comment on this one please?

**Comment by AndrienkoAleksandr** [comment]
@eivantsov, our "Command" widget this is not "Terminal" widget. So it doesn't support display color command sequence and doesn't display "text graphics" (for example to display download progressor). If we really want support such thing in the "Command" widget, we can use terminal widget in the "output mode" instead of current command widget. "ouput mode" - I mean "Terminal" widget without activation typing text, only for display output. I don't think this is difficult to realize this feature, but we need issue with correct description. Thank you, you voiced very useful question.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
