### ISSUE TITLE
Factories runCommand should validate more

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#4780]
Factories UI shows:
![image](https://cloud.githubusercontent.com/assets/145667/24912434/61bee2a4-1ece-11e7-8d96-434ec4f0543b.png)

 - Placeholder text should be "Name of a command" instead of "Enter value"
 - UI could show a drop-down list (including per-project commands)
 - Should report errors if this field is invalid even after starting a workspace from this factory.

**OS and version:**    5.7.2

**Comment by ghost** [comment]
@wernight I think a dropdown with command list makes sense. Not sure about any errors after starting a workspace, but we should definitely not let a user make any mistakes when in UD.

@slemeur @TylerJewell what do you think?

**Comment by TylerJewell** [comment]
+1

@eivantsov - where would you source the list of commands for a drop down?  If the factory being generated is templated from an existing workspace, then we could list all of those.  Another option could be that we just grab the list of all commands from all workspaces (running or otherwise) in your account and list those.  I am thinking of the use case where a person is writing a factory from scratch, and it is not being sourced from a workspace definition to start with.

**Comment by wernight** [comment]
I think it should parse the json, but first need to [fix the issue that it loses the per-project commands](https://github.com/eclipse/che/issues/4778).
