### ISSUE TITLE
Recommended hosting priorities

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#4879]
We are looking to host on AWS although this *question* will apply to any environment. I appreciate there are many variables to take into account but I'm looking for a good starting point.

What sort of instance type will serve Che best and make the most economic sense, i.e. what is the order of priority? Is it;

1. Memory
2. CPU
3. Storage

For example, if memory is the priority - we would be looking at memory optimised instances (r4), or, if storage was the priority - SSD-backed instances, etc.

My guess is that memory probably is the first priority?

**Comment by TylerJewell** [comment]
Hi @davidwindell - yes great questions. Our systems are bottlenecked in the following ways:

1. The size of workspaces are RAM-driven. So the number of workspaces that you want running at the same time is a function of total system RAM. At codenvy.io, we run 32 GB RAM nodes in a Swarm cluster. We prefer to go smaller than larger because it makes adding new and removing unused nodes easier. If you have a 256GB node and then only 1 user with 8 GB RAM on it, there is no easy way to move that user to another node if you want to deprovision it to save money.  So we go with lots of smaller nodes to make it easier to cleanup at scale. We are running sometimes 100s of nodes, so we are at a different scale.

2. CPU is the primary activity for users who are doing compilation events. If you are heavy compilation all at hte same time and you have multiple users on different workspaces on the same node, you can become CPU constrained. So manage this properly.

3. Storage size is needed for snapshot images and your stack images and your offline storage of code projects. Some stacks can be huge, so make sure you have a disk allocated for all of the docker images and the `/data` mount.

Tyler

**Comment by davidwindell** [comment]
This is awesome, thanks @TylerJewell.

Storage wise I was approaching this from an I/O perspective but thinking about it that will depend entirely on the sort of workspaces/tools users have setup.
