### ISSUE TITLE
Support private repositories in Factories

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#4908]
It would be really useful to be able to use private repositories in factory URLs so you could do this:

`/f?url=git@my.git.server:private/repository.git`

Alternatively, is there a way to somehow share factories between multiple Che instances on the same server?

**Comment by ghost** [comment]
@davidwindell currently, a Factory is valid for one installation as it is has ID and that ID should be searchable.

As to using a private git repo, it is not possible at the moment. Current implementation of this service gets Dockerfile or workspace definition via http.

**Comment by davidwindell** [comment]
@eivantsov It looks like we can't use factories anyway as each of our projects contain a changing Dockerfile that we need to build and run during the dev lifecycle.

I still think it would be a cool feature request for others who might want to factory in private repos.

I'll close for now.

**Comment by TylerJewell** [comment]
The Dockerfile inside the repository is another kind of issue that we have
documented ideas around.  The issue is that today, we only perform a clone
of a repository from inside a running workspace. The workspace's runtime
has all of the git utilities inside of it.  But what happens if the
workspace's recipe is defined in a git repo and it is needed before the
workspace is running?

to solve this, we have to make a version of our git capabilities into the
Che master server, so that the server has ability to gain visibility
pre-workspace creation.


Tyler Jewell // CEO // tyler@​codenvy.​com // 978.884.5355

**Comment by davidwindell** [comment]
@TylerJewell Yep, that makes a lot of sense and I can't wait to see it become a reality. Users could then configure VCS keys without having to launch a workspace.

"Dynamic runtimes" based on the repositories Dockerfile, all wrapped up nicely and automated with volumes etc will be so awesome.

My only additional request for that, if it happens, is that there is a rebuild option in the IDE to regenerate the runtime easily when the Dockerfile changes ☺️

**Comment by TylerJewell** [comment]
Yes, we agree entirely on the benefit of it.  It is a challenging fix but a necessary improvement.

Interesting to see if various fit providers have webhooks to show events for single files.  We could automatically rebuild in that way.

Tyler
