### ISSUE TITLE
Build a custom assembly for each platform

### ISSUE THREAD

**Issue by vnea** [eclipse-che/che#5072]
Hello,

I just want to know if I have to build a custom assembly for each platform or not.

For example if I am on Windows and I run this [command](https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html#build):
```
docker run -it --rm
      ...
      archetype build
```

Now I have a generated custom assembly that can be executed (on my Windows machine).

If I want to execute this generated custom assembly on a Linux machine, do I have to re-build it on Linux to have a new custom assembly specially for Linux or can I re-used the generated custom assembly and just run it ?

**Comment by ghost** [comment]
@vnea it is quite possible that an assembly built on Windows may not run ok on Linux due to file permissions, even though everything happens in a Docker container. However, volume mounts, and especially those on Win 7 and 8 systems with boot2docker installed, may do weird things to files, permissions, file endings etc.

I'd recommend that you build your assembly on Linux if it eventually runs on Linux too. With that being said, I am 99% certain that if you have an assembly generated on Win 10 and Docker for Windows (not Docker Toolbox) it is highly improbable that you face any issues with running such an assembly on Linux.

I might be mistaken though :)

**Comment by vnea** [comment]
@eivantsov I asked this question because I successfully built an assembly on Windows 10 but I didn't success on Linux.

I tried to generate an assembly on Linux but it didn't work (with the command **archetype generate**). Then I took my generated archetype from Windows and I put it on Linux and I tried to build it (with the command  **archetype build**).

As it didn't work, I took the custom assembly built on Windows and I put on Linux and then run it (with the command  **archetype run**).

As you said, I had a **[Permission denied]** log error (**docker logs -f che**) about the file **.../archetype/assembly/assembly-che/assembly-main/target/eclipse-che-5.10.0/eclipse-che-5.10.0/tomcat/bin/catalina.sh**  .
I added the exectution permission with the command **chmod +x ../catalina.sh** and then it worked !

I will maybe open a new issue If I try to built a custom assembly on Linux another time.

Thank you for your help again, you're very reactive !
