### ISSUE TITLE
Create and run a customized docker image based on a custom assembly

### ISSUE THREAD

**Issue by bs-matil** [eclipse-che/che#5076]
Current workflow. 
- build a custom assembly
- mv the assembly with scp to the target runtime
- run the assembly as -v :/assembly mount with eclipse che

What I want 
- build a custom assembly and create a docker image from it
- run the custom dockerimage on the target runtime without mounting /assembly

Would that be possible at all, can I create just a che-server image somehow?
How could I integrate this with the CLI?
Can I run the server without the CLI?

**Comment by ghost** [comment]
@bsukramlitt all good questions!

1. This is how che-server image is built: https://github.com/eclipse/che/blob/master/dockerfiles/che/Dockerfile

Once built, start Che cli with `--fast` which is a flag for CLI not to pull che-server (or any other utility images) from DockerHub.

2. We're working on docs on how to build own CLI that references own images so that your run syntax may look like `docker run .... bsukramlitt/che-cli start `

3. Yes, you can run Che server image alone, however, this will make updates impossible since configs will be mounted into server container and there won't be any way to use the nice che.env:

`docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v ~/che-data:/data -p 8080:8080 eclipse/che-server start`

**Comment by ghost** [comment]
@bsukramlitt here you go https://github.com/eclipse/che-docs/blob/9c780343e7d6fceac45bd6dbed74103155454607/src/main/_docs/assemblies/assemblies-assembly-lifecycle.md#production-mode

Closing the issue. Feel free to reopen if you face some issues along the way.
