### ISSUE TITLE
Add server health concept into infrastructure workflow.

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#5093]
Add health-check concept into the model of server conf. Add health status into the model of runtime server. Add implementation of server health-checking in Docker SPI impl.

**Comment by gorkem** [comment]
I think @amisevsk can give some insights to how Openshift/K8s handles these.

**Comment by gazarenkov** [comment]
Yea, I think we need more information about how it already implemented.
Ideally, we may let infrastructure to implement it or reuse it (the case of Openshift/K8s AFAIK) to not to reinvent the wheel. Though, not sure yet.
So, @gorkem good idea, thanks.
@amisevsk any suggestions/insights as for Openshift/K8s impl?

**Comment by amisevsk** [comment]
@gazarenkov sorry about the delay. 

I haven't put as much thought into this as will probably be necessary, but I'm pretty sure on the Openshift/K8s side we can manage to monitor workspace health through the built-in functionality. I haven't tested it though, so a Che-side implementation may still be necessary. In short, health checks on Openshift should probably be implemented to use Openshift liveness probes and an event listener -- this looks quite different from the docker implementation. On Openshift (if we went with this implementation), we would not probably not be requesting health checks directly, and instead listening for 'unhealthy' events. In terms of an abstract SPI model, I would prefer to have an assumption of "machine is healthy unless notified otherwise". 

What I would say regarding the SPI is that ideally it's high level enough that it is not responsible for workspace health/readiness, and instead listens for e.g. "workspace unhealthy" events, etc. I think it should be up to the SPI implementation-side on how this is done -- the current implementation for docker is likely redundant when running on Openshift (although we don't currently have a solution and instead use the docker listener anyways).

For Openshift, we can include liveness/readiness probes in the workspace pod spec, and listen for events to detect issues. I think the [available options](https://docs.openshift.org/latest/dev_guide/application_health.html) should be sufficient for Che's uses, and might even be cleaner on the Openshift side, since currently we are working around a lot of Docker specific implementation stuff. 

Feel free to ping me on Slack/github/email if this isn't clear or if I'm misunderstanding the root problem.

**Comment by gazarenkov** [comment]
@amisevsk sorry for delay (something with GH notification on my side :( )

Thanks for the info!
It looks like we can reuse "Readiness probe" to let Infrastructure (SPI implementation) know when Server (or Machine) is up and "Liveness" when it down...

Did I understand correct that we can create a callback (web hook) procedure (Java code) which would be able to react on either/both of ready/unhealth generating SPI specific event?

Thanks a lot 
yes, lets try to talk later this week

**Comment by amisevsk** [comment]
@gazarenkov 

Yeah, that all should be possible. We haven't tried using lifecycle hooks yet, but we should be able to specify a post-start and pre-stop hooks for workspaces, which might make some implementation details easier (iirc the pre stop hook also includes the reason for stopping, so we could maybe detect wsagent issues too). I'm not 100% on whether this will suit our needs though -- I need to test the idea more.

Another factor worth considering for the SPI is that we could use a kubernetes liveness probe instead of pinging the workspace from che server (e.g. in WsAgentHealthChecker). Even without a lifecycle hook, we could listen for workspace events and work from there, potentially.

**Comment by gazarenkov** [comment]
Exactly, it can be considered as implementation specific thing which we can transform to "known" events, that's the idea.
Says, we specify that Infrastructure MAY support Servers' states (simple STOPPED/RUNNING) and it is Infra's matter how to perform that. 
I.e WsAgentHealthChecker (and others, if any) like this may be moved to Docker(/Swarm) infra module and Kubernetes/OpenShift implementation will use internal events and then transform to events defined by SPI

**Comment by amisevsk** [comment]
Sounds good to me, let me know if you would like to talk further.

**Comment by garagatyi** [comment]
For now, we postponed extension of the model with liveness checks and decided to implement minimal checks workflow with sending server statuses events to allow IDE team to use events for the interactive load of the client.

**Comment by garagatyi** [comment]
I added hardcoded server status checks to Docker implementation to allow to continue work on client side

**Comment by gazarenkov** [comment]
Will be implemented on per-infra-impl basis as a:
- reaction on MachineEvent example for Docker infra: #6021
- or somehow natively
