### ISSUE TITLE
No error or indicator if file can't be written

### ISSUE THREAD

**Issue by siliconalchemy** [eclipse-che/che#515]
If a file can't be written to in the editor - eg. if permissions aren't correct - there is no indicator or error.

**Comment by ghost** [comment]
Can you elaborate please?

**Comment by siliconalchemy** [comment]
Not sure how else I can put this.  If changes can't be written to the file, the ui should clearly tell you.

**Comment by ghost** [comment]
What is a typical situation when you face this problem?

**Comment by siliconalchemy** [comment]
I give up..

**Comment by ghost** [comment]
Yes, I can see `ERROR (org.eclipse.che.ide.jseditor.client.reconciler.ReconcilerWithAutoSave): 
org.eclipse.che.ide.commons.exception.ServerException: Unable set content of '/web-php-simple/index.php'` in the console when file permissions change. I just wanted to learn more about the use case.

Reopening and labeling as Improvement.

**Comment by TylerJewell** [comment]
I think @siliconalchemy Eugene wasn't being obtuse. The problem is multiple levels. There is the file system inside the workspace, which is running in a Docker container. We should surface into the project tree the permissions, or just an icon if the file is not editable.  Separately, we have had issues with users placing project files (outside of the containers) into file systems with permission issues. So, he was probably just thinking through what kind of message we provide to users - just indicate within the workspace permissions, or also try and detect an issue with the file system that the files were volume mounted from.

**Comment by siliconalchemy** [comment]
My apologies guys, long day.  If I'm changing code in a file in a project and I go to save it, and if the backend has any issue whatsoever with the act of saving that change to the backend file, as a coder I want to absolutely know that that save has failed otherwise I'm going to spend the next ten minutes tearing my hair out refreshing browsers and looking through consoles/source trying to find the problem.  An indicator in the tab header (like a red circle or red flashing/pulsating error icon), or a growl like alert would be good, but it's real important from a ux point of view that this failure gets back to the coder in an obvious fashion.

**Comment by TylerJewell** [comment]
+1000 - This is an excellent point, and it's clear now.

**Comment by TylerJewell** [comment]
@dkuleshov - can you please review this issue?  Does your issue relating to VFS improvements also solve this?  https://github.com/eclipse/che/pull/1634.  Imagine a situation where a Che workspace is backed by volume mounted storage controlled by admins that may alter the file permissions in some unplanned way.

**Comment by dkulieshov** [comment]
Hi guys,

@siliconalchemy accurately emphasized the real life use case so the situation is clear for me. For this issue I see the technical background as a three major challenges.
- Client (IDE) UI components to support FS items access properties (detection, indication, etc.)
- Client (IDE) save and auto-save routines should properly respect FS access attributes
- Server VFS support for access attributes of FS items

In general though the problem seems to be quite clear and simple in fact the complexity may be more than meets the eye. I foresee file _R/W_ access attributes support won't be enough as we have other item type (directory) for FS that should also be properly treated. That will involve considerations over project tree explorer and probably some other UI elements along with server side components.

https://github.com/eclipse/che/pull/1634 not really helps here because at the moment of this writing, VFS itself and correspondingly VFS-based event handling system do not support any modification tracking except related to creation, removal and content update. That actually does not allow us to see if access attributes are changed.

**Comment by vparfonov** [comment]
not actual anymore
