### ISSUE TITLE
Broken links in CUSTOMIZING.md

### ISSUE THREAD

**Issue by vnea** [eclipse-che/che#5276]
Hello,

All links in [CUSTOMIZING.md](https://github.com/eclipse/che/blob/master/CUSTOMIZING.md) are broken.

**Comment by slemeur** [comment]
Thanks @vnea. 
I'll take that.

**Comment by Anne369** [comment]
@slemeur I also face the problem, could you fix it asap

**Comment by slemeur** [comment]
Hi @Anne369. That issue is prioritized. The page needs to be refactored and simplified since we introduced archetypes and refactored the structure of the docs - but the docs are existing.

Have you explored them? 
https://www.eclipse.org/che/docs/

More particularly, sections regarding extending Che: https://www.eclipse.org/che/docs/assemblies/intro/index.html

You can also find documentation about development workflow here:
https://github.com/eclipse/che/wiki/Development-Workflow

**Comment by qi-min** [comment]
@slemeur Besides the instruction in https://www.eclipse.org/che/docs/, is there any other documents for Che developers. 
I want to extend editor to support new file type. I see examples about how to support code completion and highlight, but I do not see any sample or API about formatting and syntax validation on Editor part https://www.eclipse.org/che/docs/assemblies/sdk-code-editors/index.html

**Comment by slemeur** [comment]
Hi @m7luffy. 
There are various approaches for that:
- You can create a dedicated Language Server which will provide intellisense capabilities: https://www.eclipse.org/che/docs/assemblies/sdk-language-server-protocol/index.html
- Otherwise, you should explorer the various Editor API and apply the same principles you did for code completion and highlighting: https://github.com/eclipse/che/tree/master/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/editor . Here is how the java formatter is done for example: https://github.com/eclipse/che/blob/master/plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/editor/JavaFormatter.java
