### ISSUE TITLE
CHE_SINGLE_PORT enabled but ephemeral ports still used?

### ISSUE THREAD

**Issue by levjason** [eclipse-che/che#5284]
I enabled CHE_SINGLE_PORT using the default port of 8080. I opened port 8080 in the firewall. But CHE does not start. In the log it looks like browser -> WS and server-> WS are trying to use the port 32768.  I understood CHE_SINGLE_PORT to mean that all http traffic would go through the single port. This is from cli.log:

INFO: (che config):  Customizing docker-compose for running in a container
INFO: (che start):  Preflight checks
         mem (1.5 GiB):           ^[[0;32m[OK]^[[0m
         disk (100 MB):           ^[[0;32m[OK]^[[0m
         port 8080 (http):        ^[[0;32m[AVAILABLE]^[[0m
eebb36d5f0e2897220efe81688b8a7182a6c17b372a31214b214573fd22bfd36
/usr/bin/curl  "-I localhost:32768/alpine-release -s -o /dev/null --connect-timeout 5 --write-out %{http_code}"
28
/usr/bin/curl  "-I 11.111.11.111:32768/alpine-release -s -o /dev/null --connect-timeout 5 --write-out %{http_code}"
28
         conn (browser => ws):    ^[[0;31m[NOT OK]^[[0m
         conn (server => ws):     ^[[0;31m[NOT OK]^[[0m
fakeagent-8080

**Reproduction Steps:**
1. Set CHE_SINGLE_PORT=true
  2. Enable firewall. Open port 8080

**OS and version:**    
Ubuntu Linux 16.04

**Diagnostics:** 

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che:nightly
 Version:        nightly
 Command:        info
 Parameters:     info
Mounts:
 /data:          /home/theUser/che_data_5.12
 /data/instance: not set

 /data/backup:   not set                                                                                              [0/1887]
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    nightly
 CHE_HOST:       11.111.11.111
 CHE_INSTANCE:   /home/theUser/che_data_5.12/instance
 CHE_CONFIG:     /home/theUser/che_data_5.12
 CHE_BACKUP:     /home/theUser/che_data_5.12/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   11.111.11.111
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:nightly
 IMAGE_CHE=eclipse/che-server:nightly
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc3
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:nightly
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:nightly
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:nightly
 UTILITY_IMAGE_CHETEST=eclipse/che-test:nightly
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:nightly
che.env:
 CHE_SINGLE_PORT=true

**Comment by benoitf** [comment]
Hello, the 'single port' is only opened for communication between the browser and the workspace master, communications between workspace master and workspace agents are done through the random ports

**Comment by ghost** [comment]
@levjason the ephemeral port range should be opened internally to enable communication between containers.

**Comment by levjason** [comment]
@benoitf @eivantsov The documentation states that "By enabling single-port, using CHE_SINGLE_PORT=true in che.env file , all browser traffic to Che or any workspace will be routed through the value that you have set to CHE_PORT, or 8080 if not set. What's the use case for CHE_SINGLE_PORT? Thanks.

**Comment by TylerJewell** [comment]
The primary use case is to narrow the number of ports that admins have to configure for external traffic coming into the system, which is perceived to be the biggest risk factor for security. The implementation provided to date only covers that external routing for all traffic other than SSH due to a temporary limitation within the Traefik proxy.

In the future, with a Kubernetes-based infrastructure, we will get manual control over routes and we can use that routing flexibility to mask URL names and ports to end user along with controlling internal inter-container traffic.  Once we have true routing at that level, we could even apply permissions and group access policies to individual URLs representing servers launched in a container by the end user!

**Comment by ghost** [comment]
> The documentation states that "By enabling single-port, using CHE_SINGLE_PORT=true in che.env file , all browser traffic to Che or any workspace will be routed through the value that you have set to CHE_PORT, or 8080 if not set. What's the use case for CHE_SINGLE_PORT? Thanks.

@levjason right now, you if you want your users to start and use workspaces, as well as have previews to web servers running inside them, you need to make sure the ephemeral port range is not filtered for outbound connections. In other words, this port range should be opened to the world.

With a single port policy, the ephemeral port range can be closed externally but still available internally to enable communication between containers. Users browsers and ws-master will reach ws agent and all services running in a workspace container through one port.

**Comment by ghost** [comment]
one solution is to setup a socks proxy on the server running using ssh and then tunneling traffic over ssh like @TylerJewell said.  Here is a great example using putty.  Be careful on step 2, they mix up the ports.  If you use 8123 on the server side, use 8123 on the client side.  The example shows 1337 in putty which is wrong.  [https://www.digitalocean.com/community/tutorials/how-to-route-web-traffic-securely-without-a-vpn-using-a-socks-tunnel](https://www.digitalocean.com/community/tutorials/how-to-route-web-traffic-securely-without-a-vpn-using-a-socks-tunnel)

**Comment by ghost** [comment]
Closed due to inactivity. The question has been answered as well.

**Comment by CharlyRipp** [comment]
I am curious - with the single-port setting on 6.9.0, the workspace services are exposed with the wildcard as well as the ephemeral port. After reading this issue chain, it sounds like this functionality has changed since last year.

For example:

```
http://node-angular-workspace3x4mp13id.my.domain.com:32978/
```

Taking the ephemeral port on the end off still routes to the service. So my question might be if there's a way to change that URL presented in the `servers` listing to remove the ephemeral port as to not confuse users. 

Note that our network policies are strict on port exposures across our networks, which has lead to implementing this.
