### ISSUE TITLE
Show current git branch in the IDE

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#5335]
Show current git branch name in the editors bottom info panel.
![git_branch](https://user-images.githubusercontent.com/7668752/27026121-67f2a74c-4f65-11e7-95e8-8b88153eb645.jpg)
Clicking on the branch name must show Git branches dialog.

This issue is a part of epic: https://github.com/eclipse/che/issues/5128 
![new git panel](https://cloud.githubusercontent.com/assets/1636769/26213265/b13531d4-3bf8-11e7-9516-8217c68a6af8.png)

**Comment by slemeur** [comment]
Please note the integration in the project explorer too.
And refer to the following mockup:
https://cloud.githubusercontent.com/assets/1636769/26213265/b13531d4-3bf8-11e7-9516-8217c68a6af8.png

**Comment by vinokurig** [comment]
@slemeur Do you mean that the integration in the project explorer is coloured files in project explorer? If so, I have created a separate issue for that: https://github.com/eclipse/che/issues/5339. If you mean viewing Git branch in project explorer near project's folder, so this field is already used to display the name of maven module.

**Comment by slemeur** [comment]
I meant following the specification:
- styles and icons used in the mockups
- displaying coloured files in project explorer
- displaying branch near project's folder.

When you are working on multiple projects in your workspace, you don't want to open multiple files in order to know which branches are checkout. 
So the goal of displaying the current branch for each project in project explorer is to give a quick way for the user to know on which branches he is working on. 
(Note: that could be an option in user preferences to enable/disable displaying branch in project explorer)

Now about your note on maven module - maven is a specific project type and our Che users are not all doing maven. The proportion of Che users who are using Git is bigger than the ones who are doing maven. So maven plugin must be adapted in order to handle this properly.

We can handle it in different ways and quite easily, example:
<img width="540" alt="screen shot 2017-06-22 at 10 21 55" src="https://user-images.githubusercontent.com/1636769/27424476-747c4f4a-5735-11e7-9c9b-03558220101f.png">

Also, we could have displaying modules could be activable in user preferences.

**Comment by vinokurig** [comment]
I am -1 to have git branch near project name because project name can be long and the git branch can be hidden in the project explorer panel.
I agree that it is not good to have git branch in the editor part, so my proposal is to place git branch to the bottom panel of the IDE and to make it depend from project explorer selection. 
![screenshot-172 17 0 1-8080-2017-06-22-12-23-36](https://user-images.githubusercontent.com/7668752/27427060-4f6cfb30-5746-11e7-929e-fa41af43a689.png)

**Comment by vinokurig** [comment]
@vparfonov WDYT about placing the git-branch to the bottom panel?

**Comment by slemeur** [comment]
@vinokurig : That is not a proper approach for the end-user. You want to put the information too far from where the user actually needs it.
If the name of the project is long and the user wants to see the branch name, he will resize the panel.

There are different aspects and use cases which have to be handled:
- When you are editing a file, user could want to know on which branch he is working. The closest place to put that information is in the editor footer. We have place for that and it will be handy.
- When you are browsing the projects you are working on in your workspace, you could want to know which branches are checkout. If you want to know that information for each of your project, you want to get them at a glance, without having to click on each of the projects to know that. 

Moreover: the solution you are proposing will not work with IDE 6 designs - as the footer will be removed. (Note: It will be removed, because it is used only for maven plugin - and most of the time there is no information displayed in this footer. The space used by the footer will be better to increase editor area.)

**Comment by sunix** [comment]
@vinokurig
-1 for git-branch to the bottom panel. Would be better in editor footer.
+1 for displaying the branch name in the top project level (the one that contains .git folder). It's completely fine to resize the panel if too long

**Comment by vparfonov** [comment]
@sunix and @slemeur 
i have "Vice versa" vision and totally agree with @vinokurig. 
I think will be enough show  branch in bottom panel it allow us switch branch. BWT Idea do the same

**Comment by slemeur** [comment]
@vparfonov the footer bar at the bottom of the IDE is gone with Che 6. The solution will not work.

Those information have to be as close as possible to where the user need them, as explained in: https://github.com/eclipse/che/issues/5335#issuecomment-310609128

I would add that we are expecting to display the git status with colorized filenames, to give to the user a way to instantly knows his git status from the project explorer. So it is logical that the branch name is displayed close to where we allow the user to see the git status.

In a multi-repo use case, the IntelliJ approach does not allow to get the branch information without either selecting each project or clicking on the "branch" to then get another popup to scroll in. I would add, that I did a quick search and found 2 plugins for intellij which are allowing to display the git branch in the project explorer ;)

**Comment by TylerJewell** [comment]
@slemeur - maybe it will help to update the designs to make use of the Che 6 IDE experience instead of using the older design that has the footer.  That may make it clearer as to why it needs to go next to the project name.

It's not related to this issue, but I am still of the mindset that we need a general purpose footer that spans the entire bottom of the IDE itself.  There is a lot of IDE-wide information that we probably should display continuously.

**Comment by sunix** [comment]
@TylerJewell @vparfonov IDEA has their reason to put that information in the footer, but here it is not what we would expect. Branch name is not related to the entire IDE but just to 1 project among multiple ones.
When I use Che day to day, I have several git projects in my workspace and it will be confusing to have one branch name in the bottom which i don't know to which project it refers.

**Comment by slemeur** [comment]
@TylerJewell : The mockup is not the one that is displayed in the issue but @vinokurig added it and included it in the description of the issue. (I can update that)

Today the footer is useless for 98% of use cases. I prefer to give that space to other useful areas - and revise when we will have other important information.

**Comment by vkuznyetsov** [comment]
I agree with @vinokurig [comment](https://github.com/eclipse/che/issues/5335#issuecomment-310329408)
It will not be useful to have branch name next to project name.
For example: 
![branch name](https://user-images.githubusercontent.com/2101815/27685452-e3b173ee-5cd6-11e7-9179-726258267cc6.png)
The project name with a maven module name + git branch name take much place in project explorer and in some cases git branch will be hidden.
I propose to to show branch name above the project name or below it.

**Comment by slemeur** [comment]
The developer is having the ability to resize the project explorer. It works like this even now, when:
- project name is long
- project name is long and it's a maven project and the module name is long
- ...

So this problem is already here, regarding or not the add of the branch name.

The solution would be to truncate the information and show the complete information on hover in a tooltip.

**Comment by vinokurig** [comment]
@slemeur If the footer bar at the bottom of the IDE is gone with Che 6, where current widgets from that panel (maven loader) will be placed? May be it will be possible to place there the git-branch?

**Comment by slemeur** [comment]
@vinokurig: There is only one widget which is using it and you are correct it is the maven loader. The proposal we choose is to use a toast notification which will be displayed in bottom right corner for the time maven loader will process.

**Comment by slemeur** [comment]
@vinokurig : The information has to go as close as possible to where it'll be needed to the developer. 
The project explorer must reflect:
- what codebase you are working on
- which branch you are
- what files are changed

It would be illogical to get only partial information in the project explorer (show only file changes) and have to go to a completely different area to know on which branch you are - and then have only a unique information related to the selected project in project explorer (another area).

If it's really bothering you - make it optional and let the user being able to remove the display of the branches from the project explorer from his preferences.

**Comment by vparfonov** [comment]
Who decide remove bottom bar (status bar)?

**Comment by slemeur** [comment]
Separate topic but I'll just reply by who decided to add it ;)

**Comment by vparfonov** [comment]
BWT it was added long-long time ago and exist now that reason remove it?

**Comment by slemeur** [comment]
The reason to remove it are quite logical:
- it takes place for all users in all workspaces even when it is not used. All users who are not doing maven are losing 20px for no valuable reason.

**Comment by vinokurig** [comment]
Having 3 names ( project name [maven module] (git - branch) ) in project explorer item is confusing. It will be difficult to understand which is maven module and which is git branch

**Comment by slemeur** [comment]
All projects are not Maven!

**Comment by slemeur** [comment]
I don't think the confusion will be that frequent, because you usually don't name a branch with the name of a module!

**Comment by sunix** [comment]
The maven module name should NOT be display by default (maybe tooltip). It never ( rarely ) change, and it's useless for the day to day flow whereas the branch name is really useful.

**Comment by vinokurig** [comment]
So first we need to decide the future of maven module info in a separate issue.

**Comment by slemeur** [comment]
Displaying the branch name in the footer is not possible because of:
- footer removed to free unused space and benefits to the editor
- it creates wrong UX, as you'll display an information in the bottom right corner, while this information is depending on the selected project in the project explorer
- it does not provide a proper interaction to see the branches of multiple projects in a workspaces

There is a logic to display the information in the project explorer as the project explorer goals are to: 
- show project files you are working on
- reflect what files are changed
Logically, showing on which branch the developer is working on, is important - and we want to put this information as close as possible to where the user needs it. 

There can be situation where it leads to need a large space to display:
- project name + maven module + branch name
BUT:
- all developers are not doing only maven projects
- user will still be able to resize the panel
**- we can truncate the information and use a tooltip to show all the information**

Finally, as we can see in the thread here, all of this comes to developer's tastes. To handle that, the best tradeoff is to provide the mechanism to allow configurability and personalisation:
**- we can add in the preferences, an option for the user to "display or not" the git branch name in the project explorer**
**- we can add in the preferences, an option to display the maven module or not in the project explorer**

**Comment by slemeur** [comment]
@vinokurig : It's part of the work that @vitaliy-guliy is handling with the design of Che 6.

**Comment by vitaliy-guliy** [comment]
I have already removed the status bar in CHE-4929 branch, but it's not a problem to restore it.
As for me the second screenshot looks nice

![](https://cloud.githubusercontent.com/assets/1636769/26213265/b13531d4-3bf8-11e7-9516-8217c68a6af8.png)

**Comment by vkuznyetsov** [comment]
@slemeur the question [here](https://github.com/eclipse/che/issues/5335#issuecomment-311960131) was about how user may know there where is the branch name and where is the maven module name.

In my opinion it would be better (in the sense that it prevent misunderstanding) to place git branch name only, and remove maven module name from project explorer.

**Comment by vinokurig** [comment]
@slemeur Having git branch in a panel will give an ability to call a popup that will allow to show all branches per project and quickly checkout to another branch, but in project explorer it will be only a label

**Comment by vitaliy-guliy** [comment]
@vinokurig It could be a hyperlink.

**Comment by vinokurig** [comment]
@vitaliy-guliy agree but it is still a question what to do with maven module info, I am -1 to setup this items in preferences because I gess they will be turned on by default and the problem will be actual if they are present together.

**Comment by vitaliy-guliy** [comment]
@vinokurig It's useless as for me

**Comment by vkuznyetsov** [comment]
We decided to make displaying a maven module name in the project explorer panel as optional.
https://github.com/eclipse/che/issues/5792

**Comment by gazarenkov** [comment]
@vitaliy-guliy 
" I have already removed the status bar in CHE-4929 branch, but it's not a problem to restore it."

I believe we should do as following:
- status bar should be in the app layout but
- if there are no components to show there, it should not be shown up.

Is that the behavior you have in mind?
