### ISSUE TITLE
[Regression] PHP language server fails on code completion apply

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#5377]
**Reproduction Steps:**
Open any *php* file, call code completion and try to apply any, nothing is inserted in editor and error message appears in browser console:
`org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Warning: Missing argument 4 for LanguageServer\Server\CompletionItemResolver::resolve(), called in /home/user/che/ls-php/php-language-server/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php on line 164 and defined`

**Comment by evidolob** [comment]
@kaloyan-raev I check Che side, it's seams to all work fine, can you check LS side.
I'm not so good in PHP to look on it.
Another thing, can you provide link to PHP LS repository, which we are using?

**Comment by kaloyan-raev** [comment]
@evidolob I am working on updating the PHP LS agent with the latest official version of the PHP LS. It will hopefully resolve #5334 too. Currently we have quite old (at least 6 months old) version of the PHP LS in Che.

The GitHub repo for the PHP LS is here: https://github.com/felixfbecker/php-language-server

**Comment by kaloyan-raev** [comment]
@evidolob Attached is an update of the PHP LS to the latest version 4.4.1. The above error message does not appear for me with it.
[php-language-server.tar.gz](https://github.com/eclipse/che/files/1076987/php-language-server.tar.gz)

However, inserting the text of the code completion should be improved. For example, if I type "ec" and select "echo" from the code completion then the result in the editor is "ececho" instead of "echo".

#5334 still occurs with this version of PHP LS. So it requires further investigation.

**Comment by davidwindell** [comment]
Also related #5017

**Comment by ghost** [comment]
@vparfonov have we updated php LS on our side?

**Comment by tsmaeder** [comment]
> However, inserting the text of the code completion should be improved. For example, if I type "ec" and select "echo" from the code completion then the result in the editor is "ececho" instead of "echo".

@kaloyan-raev this might be fixed with https://github.com/eclipse/che/pull/6339

**Comment by SkorikSergey** [comment]
Is this still an issue?
