### ISSUE TITLE
Upgrade PHP Language Server 

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#5382]
The new version is attached to this comment https://github.com/eclipse/che/issues/5377#issuecomment-308663852 
Also need to use version in LS URL, so we can provide different version of the LS for different version of Che.

**Comment by gazarenkov** [comment]
@evidolob Could you please specify what exactly you mean by:
"Also need to use version in LS URL, so we can provide different version of the LS for different version of Che."

**Comment by benoitf** [comment]
my understanding is that for now we are hosting language servers and these files are hosted under a given name. The issue is that the filenames are always the same even when we update them
So for exemple che 5.1 will download the newly updated LS server file from a URL that may not work due to LS evolutions

Hosting them with a version scheme in the filename would allow to have different versions of a given LS implementation

**Comment by gazarenkov** [comment]
Ah, yes, remember this, thanks.
Just could not put it in "php" context.
If it is it, then nevermind, forget my question.

**Comment by gorkem** [comment]
@kaloyan-raev Can you help with this one?

**Comment by kaloyan-raev** [comment]
@gorkem What help exactly do you expect from me?

**Comment by gorkem** [comment]
@kaloyan-raev I was hoping that you could take the ownership of these updates, going forward. We are going to restructure Che in the coming weeks/months so that you can do independent updates, hence I started to look for owners to different areas.

**Comment by kaloyan-raev** [comment]
Unless anything changed, language server binaries are uploaded to a server hosted at codenvy.com. I have no permission to do anything on that server.

So, I am still not sure what else I can do.
