### ISSUE TITLE
Communicate directly with language server api

### ISSUE THREAD

**Issue by philipp-lein** [eclipse-che/che#5389]
I have a question. I want to use the language server from extern. Before I updated my Che version I did this with http://localhost:{agent_port}/api/languageserver/{command}/
Now this path is not valid.
Is there any possibility to this in another way?

Hope someone can help me.

Thanks

**Comment by ghost** [comment]
@phill1234 here's, for example, how I initialize a Python language server for a particular file:

`http://172.19.20.16:32814/api/languageserver/initialize?path=/console-python3_5-simple/main.py`

What exact calls fail on your side?

**Comment by philipp-lein** [comment]
Thanks for the fast answer 👍 

I've reading you changed the connection to an json-rpc client. The languageserver runs but i have no chance to call something like http://localhost:{agent_port}/api/languageserver/hover/
to get an response because the TextDocumentService isn't able to call over an url. 
Is it possible for me to implement my own Service? Or is there a problem because lsp4j is working asynchron ? 

My goal is to use eclipse Che as workspace server. And I wrote my own "IDE" using eclipse Orion code edit. I use the Che File API to save and load files into my widget and the Command Api to execute the written code. Before changing the LanguageServerService I was able to call http://localhost:{agent_port}/api/languageserver/hover/ for example to get the response for my hover functionality. 
Now the great palantir python language server is used in Che but I'm not able to communicate with.

**Comment by ghost** [comment]
@dkuleshov will help here

**Comment by dkulieshov** [comment]
Hi @phill1234 

Yes we're switching the communication to JSON-RPC protocol, please see this [issue](https://github.com/eclipse/che/issues/5075) to get more broad understanding of the reasons that stands by that decision.

If I understand your problem correct for current variant of [`TextDocumentService`](https://github.com/eclipse/che/blob/2d260702d8bf6e3a337267e837f03d765318c352/wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/service/TextDocumentService.java#L63-L63) in order to call hover you need to have a websocket connection to workspace agent where this service is hosted ([this ](https://github.com/eclipse/che/blob/3deb16ea974c2b1e1f87ae43403352eac06bc4a9/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/event/ng/JsonRpcWebSocketAgentEventListener.java#L87-L87) looks a bit messy but should help you in understanding the way we do it), the url in our case should be similar to this: [ws://localhost:{agent_port}/websocket/{client_id}](url), than you can send JSON-RPC compliant request over that websocket connection, should be something like this:
```json
{  
   "jsonrpc" : "2.0",
   "method" : "textDocument/hover",
   "params" : "...",
   "id" : 0
}
```
Where params are a JSON representation of [`TextDocumentPositionParams`](https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/main/xtend-gen/org/eclipse/lsp4j/TextDocumentPositionParams.java). The response is also a JSON-RPC compliant JSON message. 

It might be also useful to check our implementation of remote [`TextDocumentServiceClient`](https://github.com/eclipse/che/blob/cc8fd2473a66d614bb498534d4124d6bae8d13b0/plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/service/TextDocumentServiceClient.java#L49-L49)

**Comment by philipp-lein** [comment]
@dkuleshov Thanks for the fast answer 

I understand why this decision was chosen. iT is an improvement of Che and needed to be done. Good work.

I already tried to start the websocket connection but I stumble over the two parameters
 - agent_port should be the wsagent started in the workspace?
 - client_id which parameter is this ? Can I choose my own?

**Comment by dkulieshov** [comment]
> agent_port should be the wsagent started in the workspace?

Yes

> client_id which parameter is this ? Can I choose my own?

This is actually used to uniquely identify on server side a client that establishes the websocket connection. It would be nice if we could provide those IDs in some centralized way (for example generate on server side) but we're not there yet with our current implementation so yes - you can choose the unique ID by your own.

**Comment by philipp-lein** [comment]
Thanks a lot
 It works - you saved my day

👍

**Comment by phill1234** [comment]
@dkuleshov sorry I have one last question.
When I start the workspace but doesn't open the file in Che IDE the hover command returns only an error.

So how is the setup for an file ?
I tried:
- languageServer/initialize for project
- after that I call textDocument/didOpen over web socket json-rpc but I get an error: "Something went wrong trying to find out handler category"

**Comment by phill1234** [comment]
okay when I want no response I should send without id in the json-rpc request. 

So now had another problem. When I close the File in IDE of eclipse Che and I send an hover request from my editor I get an java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Server error caused by this line
`positionParams.getTextDocument().setUri(prefixURI(positionParams.getTextDocument().getUri()));`

So i debugged the TextDocumentService in Workspace Agent I never jumped into the didOpen method. Why I can't get access to the File ? 

I'm appreciative of all the help I can get. 

Thanks

**Comment by sleshchenko** [comment]
> This is actually used to uniquely identify on server side a client that establishes the websocket connection. It would be nice if we could provide those IDs in some centralized way (for example generate on server side) but we're not there yet with our current implementation so yes - you can choose the unique ID by your own.

Created [issue](https://github.com/eclipse/che/issues/5439) for implementing a centralized way for receiving identifiers by clients.
