### ISSUE TITLE
Python 2.7 Syntax Highlighting Fails on Multi-Line Strings

### ISSUE THREAD

**Issue by platinumzr0** [eclipse-che/che#5426]
**Reproduction Steps:**
In a python workspace, entering the following line fools the syntax highlighter into thinking the word "see?" should be highlighted, when in fact it is not part of the string.
''' failed syntax highlighting\'''' see?
**OS and version:**    
Che version 5.8.1

**Comment by ghost** [comment]
@platinumzr0 two things: a) can you see the same with the latest Che version (5.12.0)? b) can you share a piece of code that causes erroneous syntax coloring.

Fyi, Eclipse Che uses Orion editor with built in syntax highlighting for a number of languages. It might be an Orion issue.

**Comment by platinumzr0** [comment]
a.) will get back to you on that
b.)
```
x = "syntax highlighting works fine here"

y1  = ''' This is a multi-line string.
syntax highlighting will work here \' ''' #syntax highlighting works as expected here

y2  = ''' This is a multi-line string.
syntax highlighting will fail here \''''  #syntax highlighting fails here
#syntax highlighting resumes normal function here

**Comment by ghost** [comment]
This is default behavior in Orion editor which Che uses as is. I have just checked it at orionhub.org and got the same results.

![image](https://user-images.githubusercontent.com/5337267/27946680-7e6f5174-62fb-11e7-824b-5369eced73cd.png)

Since I don;t think there's something to be done on Che side, I will close the issue. Hopefully, Orion fixes it in future updates, or Che will use a different editor such as Monaco.
