### ISSUE TITLE
Investigate if we need to limit amount of threads which are used for processing of JSON-RPC messages

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#5443]
I've noticed that in ServerSideRequestProcessor we use cached thread pool and I'm afraid that it may be a problem in future when we will start publishing logs via JSON-RPC. This may result in a huge number of JSON-RPC requests which potentially may cause uncontrolled grows of threads in the pool. 

I believe we should investigate if such indeed may occur and take all necessary measures, for example change cached thread pull to fixed thread pool or something similar.

**Comment by dkulieshov** [comment]
Good point, Sergey. 

From what I know cached thread pool was used here to make JSON-RPC service responsive when we run heavy requests that may last a long time. 

Your brilliant assumption indeed is worthy of a closer look. I absolutely agree that potentially there can be a problem when we transmit great number of requests, but what I believe you are talking about is short-living logging messages so here I would not be so categorical here because cached thread pool regularly reuses previously constructed threads if available and terminate and remove idle threads from the cache and in general is designed for programs that execute many short-lived asynchronous task so for a huge number of logging requests it should probably work just fine. Thats the theory and do you have practical results?

However the most important point that I see in your message is that in general case it is very possible that we may have huge problems because of a great number of long-living requests so for long term perspective we will definitely need to find the way we can control the size of thread pool yet make request processing responsive enough. From the other hand when we have fixed thread pool for such situation (a great amount of long living tasks) we will cause JSON-RPC service just to stop responding at all. So I would say that both options are quite arguable. 

WDYT @vparfonov @skabashnyuk

**Comment by skabashnyuk** [comment]
@dkuleshov ```ExecutorServiceSince``` way throw ```RejectedExecutionException``` please make sure you at least add log notification, at best do some intelligent actions.

**Comment by skabashnyuk** [comment]
Regular oom noticed at some production environments.
I saw
```
"ServerSideRequestProcessor" #4556 daemon prio=5 os_prio=0 tid=0x00007f07d4bae800 nid=0x12dd waiting on condition [0x00007f078a682000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d170a9a0> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
825 threads like this.

**Comment by skabashnyuk** [comment]
proposal 

````
    ThreadFactory factory =
        new ThreadFactoryBuilder()
            .setUncaughtExceptionHandler(LoggingUncaughtExceptionHandler.getInstance())
            .setNameFormat(ServerSideRequestProcessor.class.getSimpleName())
            .setDaemon(true)
            .build();

    executorService = new ThreadPoolExecutor(0, 100,
            60L, TimeUnit.SECONDS,
            new LinkedBlockingQueue<>(1000),
            factory);
```
NOTE
corePoolSize = 0
If fewer than corePoolSize threads are running, the Executor always prefers adding a new thread rather than queuing.
If corePoolSize or more threads are running, the Executor always prefers queuing a request rather than adding a new thread.
If a request cannot be queued, a new thread is created unless this would exceed maximumPoolSize, in which case, the task will be rejected.

**Comment by garagatyi** [comment]
As we discussed f2f usage of the queue of 1000 tasks is not the best approach since ann the JSON_RPC messages can involve sync execution of some code that can take an unknown amount of time. Which leads to a situation when the queue would make some task delayed for dozens of minutes which is not acceptable in some cases. But the PR you have provided fixes this issue.

**Comment by tsmaeder** [comment]
Open J9 has variable stack size. Perhaps we should give it another good look?

**Comment by skabashnyuk** [comment]
@tsmaeder  For agent->jt.ls topic I see no value to do that in long-term because of Theia(or maybe I don't know something and JSON/RPC is used somewhere outside of ws-agent). For ws-master, I prefer to invest in something like this https://github.com/eclipse/che/issues/11459. Migration to Open J9 quite a big story without no BV.
