### ISSUE TITLE
Deprecate and Remove Subversion support 

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#5484]
Let's start the retirement of the subversion support.

**Comment by gazarenkov** [comment]
Agree in general but not sure it's time to remove, it seems there are enterprises which still support only SVN.
I would start with removing SVN from default Che assembly instead.

**Comment by TylerJewell** [comment]
It is time to remove, Gennady. Gorkem added this issue as a business requirement that he discussed with PM.

**Comment by gazarenkov** [comment]
@TylerJewell could you please elaborate a bit. thanks

**Comment by TylerJewell** [comment]
You said that you are not sure that it is time to remove because some enterprises use it. And I am saying that the business has considered that and still wants to remove the plugin so that it is not part of our standard support packaging.  We could target this for Che 6 only, if it's easier.

**Comment by gazarenkov** [comment]
Yes, as I said, I have no issue of removing it (and I suppose it is quite easy technically), but when you told "it's time" I'd like to understand why that urgently (I do not think it was mentioned before).

**Comment by TylerJewell** [comment]
I think the urgency came from looking at and analyzing the UX for the Che 6 IDE. The Subversion menu was taking up an unrealistic amount of real estate on the menu bar vs. the number of companies that value it and the cost to maintain it. So that was the driver - that if we are improving the IDE in Che 6, then we should kill off that plugin in the default packaging.

**Comment by bmicklea** [comment]
Wouldn't it make more sense for us to move the SVN plugin to it's own repo and open source it?  That way we can direct anyone interested to it.

Separately, is the only way to get SVN support in Che after this change is made via a custom assembly as per https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html?

**Comment by skabashnyuk** [comment]
I can propose such option.
We can move it to separate repo. (BTW where?)
Plugin will be based on custom assembly (what set of plugins?)
Will be based on Che tag ()? 
What will be release cycle?

**Comment by skabashnyuk** [comment]
What if we create archetype with svn plugin. Looks like it answers all the questions above.
@slemeur @bmicklea wdyt?

**Comment by gazarenkov** [comment]
I think we need this experience (I mean having plugins on dedicated repos) also to be able to show how to do that for others.

@skabashnyuk good questions

I would answer as following: 
Q: We can move it to separate repo. (BTW where?)
A: For simplicity we can put it under codenvy org and will see then
Q: Plugin will be based on custom assembly (what set of plugins?)
A: Ideally on bare Che (no plugins, no other than "blank" PTs)  or only ones this plugins depends on - if any 
A: Will be based on Che tag ()?
Q: Yes, some of most recent version (5.18 for ex)
A: What will be release cycle?
Q: No obligations, frozen state, will see how demanded it is and try to have community support from ones who interested in.

Makes sense?

**Comment by bmicklea** [comment]
The enterprise customer will need one version of Che with MT and OS support plus SVN. Not sure if it's easiest to do this change after that's released or cut them a special assembly.

The archetype seems to make sense to me but I'd like @slemeur to comment.

**Comment by gazarenkov** [comment]
@bmicklea that means that motivation to remove, which sounded (see above) like: "the business has considered that and still wants to remove the plugin so that it is not part of our standard support packaging" is not valid anymore. 
If so, I see no reason to deprecate and remove it from supported package.
Thoughts?

**Comment by slemeur** [comment]
It is still a goal to decrease our efforts to support it. But this does not mean that we want to make it completely disappearing in a lost land: 
1- we might have customers obligations on it
2- we can't remove things like this outside a major version release, without a removal plan
3- we still want people to be able to get it and use it

We don't need the SVN plugin to be by default in Che, but since there are no ways to easily get it added (without rebuilding a custom Che) we keep it:
- The user who is **not** using SVN, will **always** have the SVN entries in the top menu - there is no way to disable it. 
- If a user needs it, we don't want to force him to build his custom-che.

This points the problems we have with the current approach of the extensibility and plugin model.

Unfortunately, for now, I don't see better approach than the archetype one, but:
- let's plan the removal with proper notification to the community
- let's create clear instructions on how to get it on our docs

**Comment by gazarenkov** [comment]
I do not see how "archetype approach" answers supportability issue.
Decision we need to make is - whether we want/need to release/QA/upgrade/ship it like we do for supported package or we move it to community/on-demand support.

**Comment by bmicklea** [comment]
@gazarenkov we can move it to community/on-demand support, I just need to be able to provide the one enterprise customer a build with it in. Then I have satisfied our support obligations.

**Comment by gazarenkov** [comment]
Thanks, that makes sense, will discuss details privately.

**Comment by slemeur** [comment]
What does that mean to move it to community/on-demand support? 

How do you imagine someone from the community being able to find it, install it and eventually supporting it?

**Comment by bmicklea** [comment]
There are two questions here:
1) How will we support SVN going forward: questions will be answered by the community (which includes us) and updates will be provided by the community. We have no current plans to enhance this ourselves.
2) How will we package SVN: as a plugin?  as an arhectype?  Who can get it?  How do they use it?  Is it easy or hard?

Gennady and I were talking about (1) but I agree we still need to sort out (2).

**Comment by skabashnyuk** [comment]
@bmicklea @slemeur I think @gazarenkov idea was 
1. to move plugin + assembly+ cli to run to separate repo. Let's say codenvy/plugin-svn. 
2. Connect plugin to some stable Eclipse Che version ex 5.17.0. Make sure tests is passed.
3. Put best efforts without obligation on answering questions.
4. If business or community will be interesting in it then they will push it forward.
5. Everybody happy.

**Comment by bmicklea** [comment]
Yes and my point (Stevan has others I think) was that for (2) we'd have to be ready to connect the plugin to a version of Che that had MT and OCP support in the event the enterprise customer (who still has a valid contract) wants to move from Codenvy to Che as they're entitled. This of course means that for that specific customer (3) is not best effort, it's mandatory while they have a contract.

**Comment by skabashnyuk** [comment]
@bmicklea @slemeur  I propose such plan
- Step 1. Move svn plugin to https://github.com/eclipse/che-plugin-svn
- Step 2. Remove svn plugin from default assembly https://github.com/eclipse/che/pull/6144 
- Step 3 Become ready to connect the plugin to a version of Che that had MT and OCP support in the event the enterprise customer (who still has a valid contract) wants to move from Codenvy to Che as they're entitled.

**Comment by bmicklea** [comment]
That provides the continuity a customer may need. Thanks.

**Comment by slemeur** [comment]
That works.

We need to notify that we are going to remove the SVN plugin from the default assembly and we'll need to keep it during a certain period of time (2 releases) before actually removing it.

Also please consider the docs which will need:
- Move the svn part from https://www.eclipse.org/che/docs/ide/git-svn/index.html to the new plugin repository: https://github.com/eclipse/che-plugin-svn
- Create a new page for "SVN", where we will provide instructions on how to get the SVN plugin.

**Comment by skabashnyuk** [comment]
Can we include in 5.19 release notes a warning that we are going to remove it in 6.x for example?

**Comment by slemeur** [comment]
sure
