### ISSUE TITLE
The last line in the console output may be lost (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5513]
**Reproduction Steps:** 
This problem can be reproduced in the next usecase:

1. import the project:[web-gwt-java-simple.zip](https://github.com/eclipse/che/files/1118896/web-gwt-java-simple.zip) as maven
2. create command ```cd /projects/web-gwt-java-simple && mvn clean install -DskipTests``` for building the project and launch it. Wait while the project will built properly
3. create command ```mvn clean gwt:run-codeserver -f web-gwt-java-simple -Dgwt.bindAddress=0.0.0.0```. 
Launch the command.
**Expected result:** Should be present message like: **[INFO] The code server is ready at http://05b1dbee7077:9876/**
**Actual result:** The message is absent
**OS and version:**  Fedora 25, Chrome browser, https://nightly.codenvy-stg.com server
**Additional information:** related selenium test: CheckSimpleGwtAppTest

**Comment by riuvshin** [comment]
@vparfonov please take a look.

**Comment by vrubezhny** [comment]
I believe the issue is already fixed by #5534 
See: Issue #5546

![screenshot from 2017-07-12 23-47-02](https://user-images.githubusercontent.com/620781/28141347-7e2f55f0-675c-11e7-8591-ed1638cde767.png)

The PR has improved the RegEx pattern detection on output console line. Before the fix a NumberFormatException may happen on lines that consist of text like  '... at ...'.

**Comment by musienko-maxim** [comment]
The dependent test has passed on all Codenvy assemblies
