### ISSUE TITLE
External operation notification workflow improvement

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#5514]
Currently in situations when we multiple times within short duration or constantly externally edit file we get a flood of notifications about that. It would be nice to improve that in some way so a user would not be bothered so much by useless notifications.

**Comment by slemeur** [comment]
Labelled as bug - as I consider the notification we are using as providing a wrong experience to the user. 

I think we need to consider:
- displaying notification only once per file
- displaying notification only for the files that are opened in the editor
- changing the notification, instead of using the 3sec notification bubble, use a notification inside of the editor.

Proposed the following:
Would a notification in the editor be more efficient? We could display "This file has been updated from another editing operation". We would display it at first change from an external operation and until the user acknowledge it with a "OK" button?

**Comment by dkulieshov** [comment]
> displaying notification only for the files that are opened in the editor

already implemented

> Proposed the following:
> Would a notification in the editor be more efficient? We could display "This file has been updated from another editing operation". We would display it at first change from an external operation and until the user acknowledge it with a "OK" button?

That is a very nice idea, however I'm afraid that it may not be useful for situations when we constantly change file outside of editor and a user accept those changes:
1. File is changed
2. We display notification
3. User acknowledge it, pressing OK
4. File is changed, again
5. We display notification, again
6. User acknowledge it, pressing OK, again

Eventually a user will be frustrated, depressed, will have suicidal thoughts.

I think we can just show a single notification with a message "File is being changed outside of IDE" or something with a similar meaning. Without confirmation. As long as file will be idle (no outside modification) for some time we disable the notification. 

I also thing it would be interesting to highlight in the editor the part of a file that has been modified, however that would probably require more technical effort.

**Comment by slemeur** [comment]
> Eventually a user will be frustrated, depressed, will have suicidal thoughts.

LOL ! Of course, we don't what that :) 

For the use cases you are mentioning, I think it's a question of regrouping the events. If you have a notif displayed continuously each 1 second during one minute, what ever the way we choose to display it, the UX will be bad.

Just thinking loud but:
- What if we display notification, only once we are almost sure that the external edits are done? This way, if 100 edits are done in 10sec, we don't display 100 notifications:
 - We could have a buffer period of 3 seconds between the time we receive an "external operation event" and we display the notification to the user. 
 - If during those 3 seconds, we receive another "external operation event", we wait 3 seconds more. 
 - Repeat until we don't receive another "external operation event".

Another thing, is the notification itself. Should we force refresh the content of the file automatically? If I'm taking the following use case on my local computer:
- I'm opening a file with editorA
- I'm opening a file with editorB
- I'm adding some edits using the editorB
- I'm coming back to editorA, I have a message "The file has been edited since it was opened - Do you want to reload it?" 


>I also thing it would be interesting to highlight in the editor the part of a file that has been modified, however that would probably require more technical effort.

Agree, but that is much more work - very interesting but would need a dedicated effort in order to handle that.

**Comment by dkulieshov** [comment]
> - What if we display notification, only once we are almost sure that the external edits are done? This way, if 100 edits are done in 10sec, we don't display 100 notifications:
> - We could have a buffer period of 3 seconds between the time we receive an "external operation event" and we display the notification to the user.
> - If during those 3 seconds, we receive another "external operation event", we wait 3 seconds more.
> - Repeat until we don't receive another "external operation event".

Sounds good to me.

> - I'm opening a file with editorA
> - I'm opening a file with editorB
> - I'm adding some edits using the editorB
> - I'm coming back to editorA, I have a message "The file has been edited since it was opened - Do you want to reload it?"

That is similar to how IntelliJ IDEA does it, while we simply replace file with a new content and throw notification on that - which is the simplest option we had but obviously not the most convenient for an end user. I think it is an important thing but it is also more a question about editor's behavior.

From what I see now we will probably need a more complex solution here to catch both notifications and editor behavior in case of multiple sources of modifications. My concern is that the IDE editor in general was not initially designed for concurrent work so we may have unexpected behavior in other related components (refactoring, project importing, etc.) so we should proceed carefully here.
