### ISSUE TITLE
The synchronize project skips project type updation

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5545]
When use synchronize projects method - it works fine for the projects list, but doesn't update/figure out project type, though the corresponding request is made and contains correct project type information.

**Comment by ashumilova** [comment]
Fixed for samples - https://github.com/eclipse/che/pull/5717/files#diff-7779332c332c76d3f488b5b42790c34cR158
Keep working on cases when import is done by provided URL.

**Comment by riuvshin** [comment]
removed 5.15.0 milestone as it is not blocker we will ship fix as it will be ready as bugfix

**Comment by SkorikSergey** [comment]
**For now we have next issues:**

 - [ ] After creating a workspace with two or more projects in the Project Explorer appears the first selected.
 - [ ] A project created from github doesn't have commands.
- [x] The commands from context menu is duplicated after restarting workspace and creating a project https://github.com/eclipse/che/issues/5733.
- [ ] Maven project folders aren't grouped into packages after project configuration https://github.com/eclipse/che/issues/5752. Similar -> Java packages are not displayed in the new created java project https://github.com/eclipse/che/issues/5624.

**Comment by Ohrimenko1988** [comment]
I confirm , problem https://github.com/eclipse/che/issues/5624 is still actual

**Comment by riuvshin** [comment]
@vzhukovskii can you please update the status on that?

**Comment by vzhukovs** [comment]
There is a possibility to change the algorithm of creating projects in the workspace after create using the common method as in the accepting factories. With this ability we'll be able to track logs from the git. Because at the moment dashboard starts a workspace and call create batch projects, then updates project configuration. This is not a good way. Lets IDE will do it. Imaging, with small projects all works fine, but when we're trying to create a workspace with _che-in-che_ project, project service will be frozen for a couple of minutes during the project import.
