### ISSUE TITLE
DefaultOutputCustomizer#customize() throws NumberFormatException on some inputs

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#5546]
The following input throw NumberFormatException on the following line:
`                int lineNumber = Integer.valueOf(text.substring(column + ":".length(), closingBracket).trim());
`

Original message:

"[STDOUT] 2017-07-06 08:58:34,647 [ForkJoinPool.commonPool-worker-3] DEBUG o.j.t.l.t.DocumentManager.findSelectedWord - Looking for word at Position 2 in 'textDocument/badWord:Warning:name:So bad!  '"

Html-Escaped (actual input to the "customize" method): 

"[STDOUT] 2017-07-06 08:58:34,647 [ForkJoinPool.commonPool-worker-3] DEBUG o.j.t.l.t.DocumentManager.findSelectedWord - Looking for word at Position 2 in &#39;textDocument/badWord:Warning:name:So bad!  &#39;"

**Comment by vrubezhny** [comment]
This should be fixed with PR #5534. 
I'll add these console messages to DefaultOutputCustomizer's JUnit test 
I saw similar exceptions, but they were reproduced on dotnet's stacktraces printed out to the console.And I've fixed that in PR #5534, but I didn't see any messages as yours... So, I think its worth to add them to the test.

One question: are original and HTML-escaped message versions anyhow different? Or: should they be anyhow different?
