### ISSUE TITLE
Implement cleanup mechanism for che docker infrastructure

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#5573]
The implementation of docker infrastructure in che does not provide proper cleanup mechanism for abandoned containers / networks / volumes, so it may produce the problems with resources for che users. This also leads to the inoperability of che because docker has resource limits as well so if you will try to start che workspace(with already reached networks limit) you will recieve response with 500 status.

**Comment by davidwindell** [comment]
@akorneta please can you make sure the cleanup is tied to the server instance that launched the containers in question? Even if that just means adding a unique string to the container names that are launched so only those are cleaned up. Users might want to run multiple che/servers on one docker daemon so we wouldn't want the cleanup interfering with those it didn't launch.

**Comment by TylerJewell** [comment]
@davidwindell - with Che 6 it is a non-goal to allow running multiple Che servers on a single daemon. Instead, we are going to add support for running Che on Kubernetes for scalability, and this will be the preferred way for scaling and multi-user support.  You can still run Che on Docker for single server mode or development, but multiple Che servers on a single Docker daemon is a non-goal.

**Comment by davidwindell** [comment]
Sure, it's a non goal. But if you're working on this issue to improve cleanup, why not add this simple feature. It makes sense to only cleanup containers you can guarantee you've launched.

**Comment by TylerJewell** [comment]
This issue is not well documented, but it's tied to the implementation of Che 6 SPI branch, and not the master itself.  

But I am careful to not extend the scope / expectation to suggest that we will be setting up a QA matrix that tests the range of issues that can exist with running multiple Che servers on a single daemon.  We already have a huge QA matrix and to test it properly would probably uncover other issues beyond just cleaning up containers.  Whereas we are committed to supporting k8s, and that will be the supported way for running users at scale on Che with a full QA certification matrix.

**Comment by davidwindell** [comment]
Out of interest, is this being built as a plugin system so somewhere in the future Swarm (and even Mesos and Cattle) support could theoretically be added?

**Comment by garagatyi** [comment]
Yes, different infrastructures implementation will be pluggable

**Comment by TylerJewell** [comment]
Absolutely - it's the fundamental underpinning in the new architecture. @gazarenkov actually has a sample adapter that made Che work on localhost without containers.  It was just four methods to be implemented.

**Comment by davidwindell** [comment]
Beautiful, keep up the awesome work guys!

**Comment by garagatyi** [comment]
This issue is not actual anymore.
