### ISSUE TITLE
Filters widget improving

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5599]
* Add possibility closing of the Filters widget by Esc button
* Close the filters widget after setting focus into other place
* Unexpected resetting in the input dags field after type `,` symbol
* Add selecting of the Suggestions: items by mouse clicking
* Use left narrow and right narrow buttons instead of up and down narrows for selecting of Suggestions
* The widget does not respect special symbols like `.` for example **.NET** searching

**Comment by akurinnoy** [comment]
@musienko-maxim :

> Unexpected resetting in the input dags field after type , symbol

It's made by purpose because widget's design doesn't allow us to use md-chips' md-require-match attribute to prevent the creation of new chips, hence we have to drop chip which doesn't match a tag.


> Use left narrow and right narrow buttons instead of up and down narrows for selecting of Suggestions

Left arrow and right arrow buttons are used to move text cursor inside the input field.


> The widget does not respect special symbols like . for example .NET searching

It works just fine.
