### ISSUE TITLE
Creating workspaces/stacks from a custom recipe is missing from UD

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5616]
With the introduction of a new create workspace flow, I am unable to create and start a workspace from a custom recipe (Dockerfile or Composefile).

When creating a stack, I do not have this option either. This is a regression versus 5.14.0 and should be fixed.

**Comment by slemeur** [comment]
We want to enforce the user to create their stack. so this will need to be added into stacks.

**Comment by slemeur** [comment]
@ashumilova : We have the import button from list of Stacks. It shows this popup.
I think the popup is broken at this moment, but should allow to handle that use case.

We could rename the "Import" by "Create from recipe"
![screen shot 2017-07-12 at 11 23 24](https://user-images.githubusercontent.com/1636769/28111126-bc86b4fa-66f4-11e7-8a21-39d2cbccd0a0.png)

**Comment by ghost** [comment]
Well, it does not seem intuitive. Or maybe the wrong word is used. Import implies import from outside, url or smth. That's the first problem.

The second problem is that if I want to run a workspace from a custom recipe you force me to do dozens of clicks - first create a stack and then create and run a workspace from this stack.

**Comment by slemeur** [comment]
Yes, we wanted to enforce people creating a stack.

**Comment by ghost** [comment]
OK, closing the issue.

**Comment by slemeur** [comment]
Your issue is accurate @eivantsov - definitely agree with you. The use case you are describing is not possible and need to be revisited. 

1- We need to rename the "Import" button to be more meaningful - I propose "Create from recipe".
2- The popup is broken.
3- Is there any opportunities to make it clearer from the create workspace. "Add Stack" redirects to new stack flow and does not allow the user to understand that he could also create from his recipe. We need to improve that.

My point about enforcing people to create a stack - is that, I don't want to mix the two capabilities. Creating a workspace / creating a stack are different operations. In the previous flow, we mixed a lot of different capabilities: it was harder for people to understand the concepts and harder to maintain mixed logic. 

With the new flow, it is clear that - you want to create a workspace, you need to pick a stack. You don't find the stack you want - create your own stack first.

Even if the model allows to create a workspace without creating a stack - I want to avoid a situation where the user will create a workspace, but that workspace will have an exotic runtime definition which can't be managed and easily shared. Stacks are allowing the user to keep a reference to runtime definition, edit it, share it.

That's why, I want to enforce people creating a stack first.
