### ISSUE TITLE
Disable workspace creation if there are no available resources

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5667]
_From @ashumilova on January 30, 2017 13:27_

When the number of the workspaces limit is set and user do not have available resources - need to disable workspace creation in the this very team.

_Copied from original issue: codenvy/codenvy#1648_

**Comment by gorkem** [comment]
@skabashnyuk Is there an API on SPI that can provide such information. Especially with the OpenShift quotas ?

**Comment by sleshchenko** [comment]
@gorkem In `master` branch of `Codenvy` project we have a service for providing such information. 
You can take a look it on [codenvy.io#swagger](https://codenvy.io/swagger/#!/resource/getAvailableResources). You should use organization id from https://codenvy.io/api/organization as account id.
Example of response:
```
[
  {
    "type": "workspace",
    "unit": "item",
    "amount": 30
  },
  {
    "type": "runtime",
    "unit": "item",
    "amount": 10
  }
]
```
Where `workspace` resource is limiting of created workspaces. And `runtime` resource is limiting of running workspaces.
Che MultiUser will have the same functionality when https://github.com/eclipse/che/issues/6041 will be done.

As for SPI and OpenShift quotas, there is no any using OpenShift quotas by OpenShift Infrastructure. So at first Che and OpenShift resources will be independent, and if we will need it then I guess we can rework Che resources limits to use OpenShift quotas to reuse configuration of OpenShift instance instead of own Che configuration.
