### ISSUE TITLE
[REGRESSION] Progress of the importing project is not displayed

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5718]
**Reproduction Steps:**
 - Create java stack with CHE project ("che-in-che")
 - Wait until WS will be ran
 - Pay attention that project folder exists in the project explorer but without files. Files are importing in the background (fone) but progress of this process is not shown .

**OS and version:**    
CHE 5.15.0 ; Chrome 59.0 ; Fedora 25

**Comment by vzhukovs** [comment]
Its probable because of the creating project outside the IDE. (Used batch operation to create the last one) When IDE has been loaded, it doesn't know that there is any importing operation performed on the server and thats why there isn't any notification on the UI. Old behavior imported project and showed the crane page, and after that showed IDE. New behavior shows IDE immediately and waits when project is cloned. 

So, actually its not a bug. Its a kind of enhancement.

**Comment by ghost** [comment]
@vzhukovskii I think the behavior here should be identical to that of Factory, when we DO show project import progress.

**Comment by vzhukovs** [comment]
@eivantsov in case of accepting the factory IDE already knows what to do and what projects it should import, so it shows a progress of accepting the factory. But in case of this issue, IDE should be somehow notified from the server, that server is importing a bunch of projects.
