### ISSUE TITLE
The commands from context menu is duplicated after restarting workspace and creating a project

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5733]
**Reproduction Steps:**
1. Create a workspace based on java stack. Create the Spring project from IDE. 
2. Invoke context menu on project and select Commands and open dropdown with commands.
**Expected result:**
![selection_004](https://user-images.githubusercontent.com/1640058/28357765-2d3d021e-6c75-11e7-8e32-cd433dbb034b.png)

**Actual result:**
![selection_003](https://user-images.githubusercontent.com/1640058/28357773-31dd5530-6c75-11e7-843a-864742440e39.png)

**Additional information:** we have the same problem after stopping and starting a workspace.

Failed test: **CheckSimpleGwtAppTest**

**Comment by azatsarynnyy** [comment]
A tip: as a quick fix, try to remove [this](https://github.com/eclipse/che/blob/master/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/execute/ExecuteCommandActionManager.java#L104) line of code because context menu already populated [here](https://github.com/eclipse/che/blob/master/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/execute/ExecuteCommandActionManager.java#L90).

**Comment by SkorikSergey** [comment]
Duplicated commands will be added if go to the Commands Explorer after starting the workspace.
