### ISSUE TITLE
Creating a file/folder with '%' in the name returns 400 Bad Request

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5810]
_From @balzer814 on July 25, 2017 15:3_

When adding a file/folder with '%' in the name codenvy returns 400 Bad Request.
It is possible to create a folder with such a name using the terminal, but this folder can later not be opened in the ide.
When creating such a file over the terminal and than open it in the IDE the opened Editor only says 'An error occoured while loading the file.'

**Reproduction Steps:**

1. open new...-> folder dialog
2. type in '%name' as directory name
3. click ok
4. codenvy shows an error message:
![image](https://user-images.githubusercontent.com/23092994/28578382-e436d2d6-7159-11e7-860b-fa1e27455394.png)

**Codenvy version:**    
5.15.0

_Copied from original issue: codenvy/codenvy#2337_

**Comment by koppor** [comment]
This is necessary for [Eclipse Winery](http://www.eclipse.org/winery/) to be able to code files in the browser.

Example folder: https://github.com/winery/test-repository/tree/black/nodetypes/http%253A%252F%252Fwinery.opentosca.org%252Ftest%252Fponyuniverse/unicorn

We use double encoding, because of security counter-measurements at Web servers. See http://eclipse.github.io/winery/dev/Encoding for more links.

**Comment by balzer814** [comment]
This issue also exists with already existing folders that are cloned into che from a git repository

Example:

1. create Git repository "issue5810Repo" on GitHub
2. add folder "problematic%folder"
3. add File "unreachable.txt"
4. import the repo in che using the factory link http://codenvy.io/f?url=https://github.com/balzer814/issue5810Repo
5. after importing the folder can't be opened, deleted or renamed and "unreachable.txt" can't be accessed

**Comment by slemeur** [comment]
thanks @ashumilova !

**Comment by AndrienkoAleksandr** [comment]
QA cycle https://github.com/eclipse/che/tree/CHE-5810-3.

**Comment by mmorhun** [comment]
Merged.
