### ISSUE TITLE
"Git" menu items sometimes disabled after workspace creation

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#5831]
Originally reported - https://github.com/redhat-developer/rh-che/issues/230
Demo: https://screencast.com/t/IGLhwJwnTfO

Comment from the original issue:
```
one thing we have noticed today...if you wait a while...the menus become available
if you refresh the browser, the menus become available
it is apparently an async process that happens after the workspace comes up
```

**Comment by ibuziuk** [comment]
@eivantsov I also can not reproduce this bug, but it happens very often for @burrsutter
Environment: Mac OS, Safari / Chrome

**Comment by ghost** [comment]
@ibuziuk just one particular workspace and one particular project?

**Comment by ibuziuk** [comment]
@eivantsov I think @burrsutter can give more details but as I understand it is **not** workspace / project specific

**Comment by ibuziuk** [comment]
@burrsutter could you please provide more details about environment, workspace, project etc., so that IDE team could start investigating? neither me nor Eugene were not able to reproduce so far

**Comment by ibuziuk** [comment]
@eivantsov could this potentially be related to - https://github.com/eclipse/che/issues/4479 ?

**Comment by ghost** [comment]
@ibuziuk I don't think so.

I managed to reproduce the state that @burrsutter had:

![image](https://user-images.githubusercontent.com/5337267/28711902-cdff2452-7391-11e7-9d59-1516930116ca.png)

And browser refresh did the trick for me as well.

What I did:

1. Removed project sources on my local machine (where it's mounted into a ws)
2. Stopped a workspace.
3. Ran a workspace. The IDE offered me to import a project since the project is in a workspace config but there are no sources. I accepted the offer.
4. Project sources showed up in project explorer.
5. The project however remains misconfigured.

**Comment by burrsutter** [comment]
I hope you are all testing by using the Helloworld flow in Openshift.IO

New Space
Quickstart
Vertx Basic
Create Workspace
since this takes a few minutes, go watch the pipeline run or explore the openshift.com console  
no git menus (unless you refresh or sometimes it happens magically by waiting)

**Comment by SkorikSergey** [comment]
Is this still an issue?

**Comment by ibuziuk** [comment]
I believe we could close it. It was verified in downstream - https://github.com/redhat-developer/rh-che/issues/230
