### ISSUE TITLE
Add the option to have one distinct PV per workspace when running on OpenShift

### ISSUE THREAD

**Issue by hbhargav** [eclipse-che/che#5920]
I have Eclipse Che nightly deployed on Openshift Origin v3.5.
I'm running Openshift Origin v3.5 on AWS deployed using Openshift Ansible.

I'm able to access the dashboard, launch one workspace & run projects.

However when I launch a second workspace, I see the following errors reported on the workspace pod.

Unable to mount volumes for pod "che-ws-a0jbaaf7pc2d17xq-3830681139-0pqj2_eclipse-che(987ec1a9-7b4c-11e7-b81c-0acab7e8d909)": timeout expired waiting for volumes to attach/mount for pod "eclipse-che"/"che-ws-a0jbaaf7pc2d17xq-3830681139-0pqj2". list of unattached/unmounted volumes=[claim-che-workspace default-token-wjrr3]

Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "eclipse-che"/"che-ws-a0jbaaf7pc2d17xq-3830681139-0pqj2". list of unattached/unmounted volumes=[claim-che-workspace default-token-wjrr3]

**Reproduction Steps:**
Deploy Openshift v3.5 on AWS using the following 
https://github.com/openshift/openshift-ansible/blob/master/README_AWS.md 

Configure Openshift to use AWS EBS 
https://docs.openshift.org/1.5/install_config/configuring_aws.html

Create Create EBS Volumes, for creating Persistent Volumes using the script below

apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv0001
    labels:
      type: ebs 
  spec:
    capacity:
      storage: 100Gi 
    accessModes:
      - "ReadWriteOnce"
    awsElasticBlockStore: 
      fsType: "ext4" 
      volumeID: "vol-0dcf676ae1030edbc"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv0002
    labels:
      type: ebs 
  spec:
    capacity:
      storage: 100Gi 
    accessModes:
      - "ReadWriteOnce"
    awsElasticBlockStore: 
      fsType: "ext4" 
      volumeID: "vol-002b8064e1bd287a1"
    persistentVolumeReclaimPolicy: Recycle

Run eclipse che using, after changing OPENSHIFT_FLAVOR=osio in get-che.sh
curl -fsSL http://bit.ly/2v0getche -o get-che.sh 
sh get-che.sh

**OS and version:**    
EC2 machine running ami : CentOS 7.3 (ami-40a4d42f)

**Diagnostics:** 
AWS EBS does not support Persistent Volume creation with access mode ReadWriteMany (RWX), it either supports ReadWriteOnce (RWO), ReadOnlyMany(ROX).

On launch of second workspace, when pod tries to mount volume claim-che-workspace throws an error saying Unable to mount volumes for pod "che-ws-a0jbaaf7pc2d17xq-3830681139-0pqj2_eclipse-che(987ec1a9-7b4c-11e7-b81c-0acab7e8d909)", because this volume is already mounted by the pod running first workspace.

**Comment by hbhargav** [comment]
@eivantsov 
Could you please let me know if my analysis is correct & possible workaround for the issue.
I believe this is more to do with Openshift/AWS EBS configuration than Che.

**Comment by ghost** [comment]
@hbhargav yes, this is OpenShift/Kubernetes error. @l0rd @ibuziuk can you comment please? I have seen such errors on OSIO but despite volume troubles workspace pods DO start.

**Comment by l0rd** [comment]
@eivantsov @hbhargav currently for openshift.io we limit the number of volumes used by che: one for wsmaster and one for all the workspaces (i.e. all the workspaces share the same PV). As a result, if PVs are RWO (that's pretty common for an OpenShift cluster), Che cannot have more than one workspace running at once. 

That's not to be considered a bug. This was intended by design to limit the number of OpenShiftOnline resources used by the OpenShift.io IDE. But of course that's an important feature now because we want to support Che on any OpenShift cluster.

**Comment by hbhargav** [comment]
@l0rd @eivantsov 
Thanks for the update. 
Will this issue be treated as a task, for any upcoming release ?

**Comment by ghost** [comment]
@l0rd but when one workspace is started the other one is stopped, right? It's che-starter that does it?

**Comment by l0rd** [comment]
@eivantsov yes in OSIO Che starter stops the running workspace first.

Il 10 ago 2017 12:46 PM, "Eugene Ivantsov" <notifications@github.com> ha
scritto:

@l0rd <https://github.com/l0rd> but when one workspace is started the other
one is stopped, right? It's che-starter that does it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/eclipse/che/issues/5920#issuecomment-321517343>, or mute
the thread

**Comment by ghost** [comment]
Closing this one as expected behavior.
