### ISSUE TITLE
[Proposal] Keycloak theme for Eclipse Che

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#6116]
I've noticed that Eclipse Che would borrow the same design from Codenvy's Login, however, I felt like it needs a little refresh

### Login Screen (Inactive)

![image](https://user-images.githubusercontent.com/14976516/29995293-c5c44e22-9018-11e7-98f6-bfe14e2da43b.png)

### Login Screen (With fields filled)

![image](https://user-images.githubusercontent.com/14976516/29995530-bf2b2f5e-901d-11e7-8e57-baa79718d87c.png)

Because Eclipse Che uses mostly Material Design on its Dashboard and such, it would be nice if the login too is Material-like

I did not make the registration portion as the following fields design can be used throughout too.

_(Note: This is just a mockup and does not reflect the actual product)_

**Comment by gorkem** [comment]
@sr229 LGTM. Can you send a PR for this after the mandatory blessing of @slemeur ?

**Comment by sr229** [comment]
@gorkem sure, although the plans for it for an actual implementation from me is remote since I still have IRL stuff to accomplish

**Comment by slemeur** [comment]
Hi @sr229 ! Thanks for the proposal. Really like the refresh!

Few things to consider:
- there are few alignements that needs to be fixed (it seems the header with the logo and title, are not vertically aligned with the other parts of the screen)
![29995293-c5c44e22-9018-11e7-98f6-bfe14e2da43b](https://user-images.githubusercontent.com/1636769/30020882-c15488d6-9165-11e7-8d7a-f76523fd9e02.png)

- we generally use rounded corner buttons (in project's website and dashboard). I think it would be more consistent to use a matching style on those pages too. 

- the orange, should match the color of the orange in Che's logo. (#F3B449)

- we'll have other pages to consider: login, create account, recover password and reset password.

- what do you think about changing the background color to be a dark gray?

**Comment by sr229** [comment]
@slemeur Thanks for pointing out the alignment issues, I think the problem was on the rulers I was using because they were not centered

Anyways, here's the updated version

### Inactive
![image](https://user-images.githubusercontent.com/14976516/30027495-db18597a-91b3-11e7-8d9e-f1d06b362b26.png)

### With Fields filled
![image](https://user-images.githubusercontent.com/14976516/30027514-ed61f1fe-91b3-11e7-8b86-95807d2e6c43.png)

So what changed was:

- Log In button has been rounded to 5px (to still comply with Google's Material Style guide)
- Realigned the content to be truly centered
- It's now a shiny gray color

**Comment by slemeur** [comment]
Great work ! This is looking pretty nice.

**Comment by sr229** [comment]
can I ask where is the implementation of Keycloak located at Che? i'm still lost here :/

**Comment by benoitf** [comment]
@sr229 it's in a branch for now:
https://github.com/eclipse/che/tree/che-multiuser/dockerfiles/init/modules/keycloak/files/che/login

**Comment by skabashnyuk** [comment]
@sr229 If you need any help @mmorhun can assist you.

**Comment by sr229** [comment]
I'll probably wait for master implementation before doing this

**Comment by mmorhun** [comment]
@sr229 it is up to you, of course.
Just a few notes how to deal with current state:
1. Checkout to `che-multiuser` branch. Create your own branch from it.

2. To develop Keycloak theme more comfortable will be good to [disable caching in jboss](http://www.keycloak.org/docs/3.3/server_development/topics/themes.html#_creating_a_theme) (to changes to be served immediately after a theme file is changed, and a user just has to refresh the page in browser). To do this, we have to change JBoss config which is inside docker container. The simplest way here just mount it as a docker volume. Lets temporary add the volume. Open `docker-compose.yml.erb` and add this line
```
- '<%= scope.lookupvar('che::che_instance') -%>/config/keycloak/jbossconf:/opt/jboss/keycloak/standalone/configuration/'
```
to the keycloak service, volumes section.

3. Compile Che.

4. Build Che multiuser docker images. Go to Che sources, `dockerfiles` directory. Run `build.sh` script from `base`, `che`, `init` and `cli` folders.

5. Start Che multiuser to generate config with command:
```
docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=<your ip> -e CHE_KEYCLOAK_AUTH-SERVER-URL=http://<your ip>:5050/auth -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che:nightly start --skip:pull --skip:nightly
```
Note, your ip should be real, not `127.0.0.1`
(It will fail to start because of missing JBoss config, but this is ok for now)
Then stop it:
```
docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=<your ip> -e CHE_KEYCLOAK_AUTH-SERVER-URL=http://<your ip>:5050/auth -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che:nightly stop --skip:pull --skip:nightly --skip:graceful
```

6. To change JBoss config, it is requred to have default one. A way to achieve this is to start keycloak docker image and grab it:
```
docker run --rm -it  --entrypoint "sh" jboss/keycloak-postgres:3.2.1.Final
```
then inside container navigate to `/opt/jboss/keycloak/standalone/` and tar the config with command:
```
tar -zcvf conf.tar configuration/
```
Then retrieve the archive. From host (not from container, but leave it alive):
```
docker cp <container id>:/opt/jboss/keycloak/standalone/conf.tar ~
```
where container id can be obtained with `docker ps` command.
Now just exit from the container, we do not need it any more.

7. Untar the config, change settings as shown in the docs (link in 2) and then move into the mounted folder: `~/.che-multiuser/instance/config/keycloak/jbossconf`.
Note, Che configs is owned by root.
Go to `~/.che-multiuser/instance/config/keycloak/`.
Then change rights of `che` and `jbossconf` directories to `rwx` for all (I know it is not good, but for this case is ok) with commands:
```
chmod -R 0777 jbossconf/
chmod -R 0777 che/
```
to JBoss be able to deal with its config and we could edit theme files.

8. Finally start Che with command from 5. Open in browser: `<your ip>:8080`.
Go to `.che-multiuser/instance/config/keycloak/che`. There you'll find Che Keycloak theme files. 
Edit them, then refresh page in browser and they should be applied.
For more details see Keycloak [docs](http://www.keycloak.org/docs/3.3/server_development/topics/themes.html).

9. After finishing of your work, replace old theme files in Che sources directory, `dockerfiles/init/modules/keycloak/files/che` with new from `~/.che-multiuser/instance/config/keycloak/che`. Do not forget to remove temporary mount from `docker-compose.yml.erb`. Commit, push, create PR into `che-multiuser` branch :)

P.S. Hope it doesn't look complicated. Feel free to ask questions.

**Comment by sr229** [comment]
@mmorhun thanks for the instructions. We have two implications however:

- Since we would be developing Che in Che, any ignored files or files starting with a ``.`` are hidden and ignored. At this time of writing, there is no option to show hidden files.

- We might heavily use Polymer Paper Elements due to the fact the theme is Material-based, we might canvas for other options. I think Eclipse Che has standards against using frameworks for Keycloak themes

This won't be a hindrance, however, we'll look for other solutions on this limitations

**Comment by devcomb** [comment]
@sr229 What do you mean by ignored files starting with a `.` ? If you are talking about inside the workspace GUI you can turn on show hidden files via "Project->Show/Hide Hidden Files".

![image](https://user-images.githubusercontent.com/29362989/32466232-d9d1a09c-c30b-11e7-9ee7-5ddf7d5e9fb7.png)

**Comment by skabashnyuk** [comment]
closing due to the lack of activity.
