### ISSUE TITLE
Clean up subscriptions for expired websocket sessions

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#6177]
We should handle expired sessions and clean up subscriptions on events by JSON RPC on server side.

For example, we have subscription to track file watcher events for a opened file.
Client subscribe on these events every time we open/refresh page.
So on server side number of subscriptions for the same event will be increase with every opening/refreshing page.

**Comment by vinokurig** [comment]
This issue is reproduced in `ProjectTreeTracker`:
https://github.com/eclipse/che/blob/9ac86356329ec095b02a48ca9ea35ac20aa37ad4/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/watcher/server/detectors/ProjectTreeTracker.java#L78
`ProjectExplorerPresenter` fires this handler each time browser is refreshed.

**Comment by vparfonov** [comment]
not actual
