### ISSUE TITLE
Define format for writing guides

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#6292]
The goal of this task is to figure out the best format for guides.

Consider:
* extensibility
* easy to use
* popularity
* render library that we allowed to use

Issue also requires specification concerning Che actions format.
Format has to be intuitively understand for __Technology provider__ and any person who wants to write guide. 

@eivantsov 's suggestion:
```
[action type=ide actionID=helpAboutAction]
[action type=openFile path=/path/to/file scroll=23 highlight=23:25]
[action type=command name=build and run]
```

Epic: https://github.com/eclipse/che/issues/6150

DoD:
- [ ] Parser in question has to cover at least `MD` format
- [ ] Performance tests performed to compare client side parser vs server side parser
- [ ] Proposed format for custom actions can be parsed and relatively easy to use
- [ ] License checked

Sources to look at:
https://code.visualstudio.com/docs/languages/markdown

@benoitf already has made investigation, see details in comments

**Comment by tolusha** [comment]
> asciidoc looks like the better way. Also rendering is supported on github.

**Comment by tolusha** [comment]
> Asciidoc provides extensibility with macros while markdown is not (there are different markdown renderer so you don't know what you can use or not)
> BTW Asciidoc can render default markdown as well so even if you write markdown syntax it should work.

> about toolchain, Asciidoctor provides rendering with also binding in Java but in our case it's the javascript port that is interesting
> https://github.com/asciidoctor/asciidoctor.js

> An example of what we could do with live editing: https://espadrine.github.io/AsciiDocBox/

**Comment by garagatyi** [comment]
@tolusha can you describe how we can parse asciidoc files and use them as guide config files?

**Comment by benoitf** [comment]
@garagatyi with asciidoctor ?
https://github.com/asciidoctor/asciidoctor.js/blob/master/manual.adoc#how-to-parse-a-file-into-an-asciidoctor-document-object

**Comment by garagatyi** [comment]
Thanks for the link. I still can't get how this file is supposed to work as a guide that is automatically parsed by Che and used to push a user through several steps to use something. Is there any document that describes how it will work?

**Comment by AndrienkoAleksandr** [comment]
I investigated ability to use asciidoc format for quick guide and using asciidoctor libs for parsing this format.
Asciidoctor has two potentionally interesting for us libs: acsiidoctor.js for client side or asciidoctorj for server side.

Review usage exprience:
===================

acsiidoctorj and acsiidoctor.js doesn't cover correct rendering very popular markdown format https://github.com/asciidoctor/asciidoctorj/issues/574.

acsidoctor.js in the docs marked like experimental. It contains issue with script minification. Developers promised fix this issue, but without minification, script is a quite big (about 1.7Mb).

acsiidoctorj and acsiidoctor.js used inside parser written on the Ruby. Inside acsiidoctor.js used opal.js script to create javascript layer with ruby parser. Inside asciidoctorj used jRuby to create java layer with ruby parser. I am really not sure, but seems it will be quite complicated CQ with such difficult dependencies... @skabashnyuk fix me if I mistakes.

Format definition
=============

@eivantsov proposed format: 

```
[action type=ide actionID=helpAboutAction]
[action type=openFile path=/path/to/file scroll=23 highlight=23:25]
[action type=command name=build and run]
```

I checked all extension parser processors, but I didn't find the way how to parse such syntax. But I found, we can modificate this syntax and we can write extension to render action button. Proposed syntax:
```
action:open-file[label="Open some file", line=33, path="/path/to/file"]
```
where is "open-file" - action id, unique for each action; 
label - it's an action button text; 
"line" and "path" it's an action specific properties (list of such properties depends on concrete action).

Like alternative variant can be (I think even a bit pretty) :
```
che:action[id="open-file", label="Some text", line=33, path="/path/to/some/file"]
```

Such syntaxes normal works even inside a lot of another acsiidoc blocks(list, tables, paragrapths...). 

For parsing this syntax we can use inlineMacro processor.

Little code mockup for asciidoctorj (version 1.6.0-alpha.6) :

```
import org.asciidoctor.ast.ContentNode;
import org.asciidoctor.extension.InlineMacroProcessor;
import org.eclipse.che.api.factory.shared.dto.IdeActionDto;
import org.eclipse.che.dto.server.DtoFactory;

import java.util.Map;

import static java.util.stream.Collectors.toMap;

/**
 * Custom ASCIIDoc processor. This component uses for parsing IDE action syntax.
 * Asciidoctorj parser uses this processor to parse founded action button syntax fragments.
 * Like result this processor returns "html action button" content
 * and save parsed action to accumulate all actions from the document.
 * "Html action button" should has mapping with "IDE action" by id.
 * 
 * Todo: store parsed action to accumulate all parsed actions from asciidoc document.
 * Todo: Define id generation for mapping "html action button" and "IDE action".
 *
 */
public class CheActionButtonProcessor extends InlineMacroProcessor {
    
    private static final String BUTTON_LABEL_ATTR = "label";

    @Override
    public Object process(ContentNode parent, String target, Map<String, Object> attributes) {
        String actionId = target;
        
        //get IDE action properties
        Map<String, String> properties = attributes.entrySet()
                                                   .stream()
                                                   .filter(elem -> elem.getValue() instanceof String)
                                                   .collect(toMap(Map.Entry::getKey, elem -> (String)elem.getValue()));


        // TODO: In the full implementation we should accumulate parsed actions.
        IdeActionDto parsedAction = DtoFactory.getInstance().createDto(IdeActionDto.class).withId(actionId).withProperties(properties);

        String buttonText = properties.get(BUTTON_LABEL_ATTR);
        
        // Return action button html representation. Todo: in the full implementation we can generate for this button unique Id to mapping with parsed action.
        // When user clicks action button in the client side we can find IDE action by this Id and launch this action.
        return "<input type=\"button\" id=\"some_id_for_mapping\" class=\"quick-guide-action\" value=\"" + buttonText + "\"/>";
    }
}

// Register processor:
// Asciidoctor asciidoctor = Asciidoctor.Factory.create();
// JavaExtensionRegistry extensionRegistry = this.asciidoctor.javaExtensionRegistry();
// extensionRegistry.inlineMacro("action", CheActionButtonProcessor.class);
```

Little code mockup for asciidoctor.js (version asciidoctor.js@1.5.6-preview.4):

```
var asciidoctor = Asciidoctor();

asciidoctor.Extensions.register(function () {
this.inlineMacro(function () {
    const self = this;
    self.named('action');

    self.process(function (parent, target, properties) {

        //todo with help target (which is equal to action id) and properties we can create and save IDE action

        var actionBtnText = Opal.hash_get(properties, "label");

        //return html action button content
        return "<input type=\"button\" class=\"quick-guide-action\" value=\"" + actionBtnText + "\"/>";
    });
});
});
```

Comparison server and client lib parsers performance: parsing adoc file with 500 lines: not more than 0.3 sec both in my local machine. It's not bad, but I think for live edit very big documents it should be faster.
Repository with test code: https://github.com/AndrienkoAleksandr/AcsiiDoctorJavaPrj

**Comment by gorkem** [comment]
I think asciidoctor is already CQed see https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9720

**Comment by AndrienkoAleksandr** [comment]
@gorkem, this CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9720 contains only css files.

**Comment by gorkem** [comment]
You are right. @maxandersen does wikitext use asciidoctor?

**Comment by gorkem** [comment]
Latest on CQ for asciidoctor. There is only a `workswith`CQ and that is not sufficient for shipping. Since asciidoctor is fairly large I think we should start the CQ process ASAP.

**Comment by AndrienkoAleksandr** [comment]
Hi, @gorkem , asciidoctor libs doesn't support correctly rendering markdown format. And we are investigating using markdown format and lib "markdown-it" for now. But if asciidoc is ok , I think we can create CQ. Should we use ascdoctor?

**Comment by benoitf** [comment]
@AndrienkoAleksandr based on feedback provided on https://github.com/asciidoctor/asciidoctorj/issues/574 I would still say that AsciiDoc is looking great.

**Comment by gorkem** [comment]
@AndrienkoAleksandr Would markdown-it support asciidoc? I come across asciidoc more commonly for documentation.

**Comment by maxandersen** [comment]
> asciidoctor libs doesn't support correctly rendering markdown format

what are you missing specifically ? it should support basic markdown syntax but still allow you to use the much more powerful support for tables, figures and just in general more extendable rendering -  especially when it comes to adding custom things like macros and custom syntax as I think you'll be wanting for doing link to actions in the IDE.

**Comment by AndrienkoAleksandr** [comment]
I completed investigation using markdown format for che guide. Like nice candidate I chose js library 
 [markdown-it](https://github.com/markdown-it/markdown-it).
 It quite small (106.4 Kb), quite fast and it supports extending markdown syntax with help plugins. Microsoft use this library in their vscode markdown extension. 
I've got this syntax:
```
[action, id="open-file", path="/path", line=30]
```
I wrote mockup plugin for markdown-it to support rendering che action buttons. Source code here: [MarkDownItTest](https://github.com/AndrienkoAleksandr/MarkDownItTest)
Github demo where is you can see rendering action buttons inside different markdown elements here:
[che actions plugin demo](https://andrienkoaleksandr.github.io/MarkDownItTest/demo/index.html)

**Comment by AndrienkoAleksandr** [comment]
@gorkem  @benoitf  @tolusha please review my investigation markdown. I created github demo for asciidoctor.js  too: 

[asciidoctor.js with che actions syntax plugin](https://andrienkoaleksandr.github.io/AcsiiDoctorJavaPrj/src/js.implementation/parse/extension/custom/index.html)

I read http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#markdown-compatibility, but I think that's absolutly not anougth for rendering markdown. asciidoc and markdown are quite similar, but none of them is not back compatable with another. 
And asciidoctor libs really bad renders markdown. Let's compare(I used the same content, only che actions syntax different) links to compare:

[Markdown-it](https://andrienkoaleksandr.github.io/MarkDownItTest/demo/index.html)
[asciidoctor.js with the almost the same markdown content](https://andrienkoaleksandr.github.io/AcsiiDoctorJavaPrj/src/js.implementation/parse/extension/custom/pageWithMarkDown.html)

What I found incorrect: 
* incorrect rendred text style "Strikethrough"; 
* Blockquotes rendered incorrectly; 
* "Unordered" list rendered incorrect;
* Start numbering with offset rendered with incorrect ordering; 
* Table rendred incorrectly;
And this is uncompleted list...

And I think it's a bad idea to use some new one dependency for converation markdown to asciidoc (https://github.com/bodiam/markdown-to-asciidoc), because it  dicrease performance and kills "live edit" markdown document feature. And we need one more CQ.

Let's, make a question: How github renders asciidoc and markdown? This service cover both formats and do it quite well...
Answer: Github has own quite impressive big library (it was written in the Ruby) https://github.com/github/markup. And this library for CORRECT rendering markdown uses separated dependensy: commonmarker (on the Ruby too). For rendering asciidoc lib uses asciidoctor dependencies (original parser written on the Ruby too; asciidoctorj and asciidoctor.js are wrappers for Ruby parser). So github uses special dependency per format. And such way doesn't confuse users. All format renders correctly.

So I think we should shoose for quick guide only one format: asciidoc or markdown. For selected format we should provide plugin for custom che actions syntax (I've already created mockups ), for another one we can create separated issue, pass CQ for lib, and use this lib for rendering without quick guide syntax. Support both formats for quick quide actions will be to much overhead.
P.S.: I propose markdown format like most popular. There are a lot projects which contains markdown files.

**Comment by slemeur** [comment]
@AndrienkoAleksandr : you did a really great analysis - excellent work!

In term of format - Asciidoc is best to support first because it supports most of the markdown syntax but provides more flexibility for custom actions and for special contents. 

We could still improve the support for markdown in the future.

**Comment by AndrienkoAleksandr** [comment]
Ok. guys. I'll create CQ for asciidoctor.js lib.

**Comment by benoitf** [comment]
yes congrats @AndrienkoAleksandr
