### ISSUE TITLE
UI performance tests

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#6357]
We have to start investigate ability to step up UI performance tests. Since the project is complex and changes in one component can effect others there is necessity to track performance changes.

This is an epic issue where we can start discussing it. I can see several fields on investigation:
- frameworks 
- infrastructure
- tests result stability
- run automatically for PR

We should start from a single test and then continuously extends coverage.

**Comment by garagatyi** [comment]
Such tests can be handled by special test suite of selenium tests. WDYT?
Can you elaborate on what do you mean by `infrastructure` entry here?

**Comment by riuvshin** [comment]
Im not sure that selenium is capable to measure performance. @tolusha do you have any examples of such tests?

**Comment by tolusha** [comment]
@garagatyi 
> Such tests can be handled by special test suite of selenium tests

Dedicated test suite

> Can you elaborate on what do you mean by infrastructure entry here?

I am not sure, that AWS instances can provide stable performance results. So, it might require physical machines 

@riuvshin 
> Im not sure that selenium is capable to measure performance.

Definitely no selenium. It is matter of investigation. May be [JMetter](http://jmeter.apache.org/)

**Comment by riuvshin** [comment]
@tolusha JMeter is absolutely not UI testing framework.

**Comment by dmytro-ndp** [comment]
QE team discussed the proposal and here the conclusion:
1. It's hard to test Eclipse Che UI separately from server because UI behaves mostly basing on responses from server, and it's hard to isolate UI from server.
2. Eclipse Che selenium tests operate with reasonable timeouts when check web element appearance/disappearance. As a result, we have regression in case of any lag of reaction.
3. All selenium test execution duration could be treated as kind of Eclipse Che performance estimation and be used to compare separate builds.

So, actually we don't need to have dedicated _Eclipse Che UI performance tests_ because we can use all selenium test execution duration to track _Eclipse Che_ performance regression.
