### ISSUE TITLE
Add more support for docker-machine drivers

### ISSUE THREAD

**Issue by sanglt** [eclipse-che/che#655]
docker-machine have many drivers, not just only Virtualbox. Can we just use the docker-machine and its support drivers, so i can run its on EC2, Fusion and other.

<img width="1257" alt="screen shot 2016-03-09 at 8 31 18 am" src="https://cloud.githubusercontent.com/assets/128535/13622447/5eaf3da2-e5d1-11e5-902f-9ba86e634113.png">

**Comment by ghost** [comment]
Indeed, we have tried it both with a remote docker or Windows Hyper-V for example. VirtualBox is the most common though since it's part of a Docker Toolbox for Win and Mac offering.

Your suggestion does sound reasonable. Labeling it enhancement. I think an additional flag, smth like `--skip:vbox` will solve the problem and add flexibility. 

For now, you may simply comment the following lines in `che.sh` https://github.com/eclipse/che/blob/master/assembly/assembly-main/src/assembly/bin/che.sh#L325-328

**Comment by TylerJewell** [comment]
@sanglt - thanks for reporting.  We are not going to pursue this strategy. Instead, we will be moving Che to launch as Docker containers.  You'll be able to use any machine that you want. This will simplify the usage for many users.

https://github.com/eclipse/che/pull/1683
