### ISSUE TITLE
File watcher service does not invoke consumer on create file event at first time after starting the workspace

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#6575]
File watcher service does not invoke consumer on create file event at first time after starting the workspace.

**Reproduction Steps:**
1. Register a watcher by matcher with create consumer.
2. Start workspace.
3 Create a file with the name that registered in the watcher.

Expected: Create consumer must be invoked.
Actual: Create consumer is invoked only after deleting the file and creating it again.

**OS and version:**    
Ubuntu 16.0.4  CHE 5.19.0-SNAPSHOT
**Diagnostics:**

**Comment by tsmaeder** [comment]
From chat:

tsmaeder
@dkulieshov I have a question about file watching:
The class FileWatcherByPathMatcher is added as a create and delete consumer for dirs and files, but not as an update consumer. Is there a reason for that?

dkulieshov
@tsmaeder Hi, yeah, the class adds/removes matching files/directories to inotify based WatchService. It does not track business events related to those items itself, just registers/unregisters them.

tsmaeder
@dkulieshov but why not forward content updates, but only add/remove?
sorry, I'm being unclear, I'm talking about ProjectApiModule, lines 140-149

dkulieshov
That's mostly becuase FileTreeWalker runs the file tree only each 10 secs while watch service detects fs events almost simultaneously
The idea here is that FileWatcherByPathMatcher only finds files that are to be tracked and pass them to watch service
Do you see what I mean?

tsmaeder
That does not seem to work when I start watching for pom.xml AFTER the first tree walk is over.

dkulieshov
Might be quite possible, there is a bug report https://github.com/eclipse/che/issues/6575
However as I know there are no bug reports for example for org.eclipse.che.plugin.maven.server.PomModificationDetector so it might be something else

tsmaeder
The PomModificationDetector is registered via dep injections, so very likely runs before the first run of the FileTreeWalker. 
The first time the tree is walked, ALL files are considered "created", and thus it works.

dkulieshov
I see
Then the bug is probably related to FileTreeWalker not FileWatcherByPathMatcher (edited)

**Comment by RomanNikitenko** [comment]
I faced the similar problem. My use case is:
- register some matcher [here](https://github.com/eclipse/che/blob/5b373e6cf5bfeb16f278c4d750fe64361445eeb4/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherManager.java#L122)
- create some item which matches the registered pattern

As result, create consumer is not invoked, but [this method](https://github.com/eclipse/che/blob/5b373e6cf5bfeb16f278c4d750fe64361445eeb4/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherByPathMatcher.java#L53) is called.
After execution code above consumers will be work as expected.

**Comment by slemeur** [comment]
@vparfonov: Could you prioritize this issue in your next sprint please?
