### ISSUE TITLE
replace everrest with jersey

### ISSUE THREAD

**Issue by tareksha** [eclipse-che/che#6756]
Hi,

Aside from the ammount of effort, are there any known legal/organizational blockers that would hold back a contribution that replaces Everrest with Jersey as the JAX-RS prover for Che ?

Jersey is used widely and maintained continuously by an active open-source community. More importantly, it is more JAX-RS - complete being the reference implamentation.

thank you

**Comment by gazarenkov** [comment]
I do not think we have legal issue there.

BUT, I predict next question can be - why not to replace then and I'd like to understand the rational reason in terms of our project needs (it is clear that Jersey is much more widely used and has active community). 
- EverRest is integrated on very core level, 
- it works very stable for years, and 
- replacing it with other engine will require very big effort (up to dedicated Major version)
- we own and support EverRest, which is quite cheap since it is very stable

So, I guess we need some better reason to replace - like current implementation blocks or makes difficult implementing some features or makes it difficult to use our project etc

**Comment by gorkem** [comment]
@gazarenkov where does EverRest live. On Eclipse repos?

**Comment by benoitf** [comment]
https://github.com/codenvy/everrest

**Comment by tareqhs** [comment]
Hi @gazarenkov ,

Apologies for the delayed response, seems I missed it down the notifications.

The main reason (in addition to the reasons above) is that we try to integrate various components/extensions that use JAX-RS Client API. We go a step further and manage various central facilities (filters, writers, readers, ...). Jersey provides an excellent client implementation as a part of the all-in-one solution. EverRest has no client implementation which is forcing us to apply numerous ad-hoc fixes/overrides in order to avoid conflicts between the client API and the server API.

Another issue is that EverRest has been frozen in terms of specification adoption. The recent JAX-RS 2.1, which adds the useful Reactice Client API, causes severe conflicts with EverRest such that it is not usable.

thank you

**Comment by tareqhs** [comment]
hi,
any thoughts on this?
thank you

**Comment by tareqhs** [comment]
hi,
any thoughts on this?

**Comment by skabashnyuk** [comment]
@gorkem 
> I do not see any issues with replacing EverRest with a mainstream implementation.

No issues.  It makes sense to do on workspace master. Since workspace agent will be retired with Theia ide it doesn't make sense to change something on ws-agent


>@skabashnyuk @vparfonov Can you see any reason?
>Do you have any idea how big the effort would be?

I guess we are missing only one bridge websocket->jsonrpc. But I don't think it would be too hard to implement

**Comment by tareqhs** [comment]
hi @skabashnyuk , @vparfonov ,
I am beginning to research and write a POC for using Jersey Servlet Container instead of EverRest . Initially I will focus on writing a drop-in adaptive replacement for EverRests's the HTTP REST components only leaving WebSockets and other features as-is.

The code in ``che-core-api-core`` and ``che-core-commons-inject`` is pretty much self-explanatory given EverRest's source. Do you have any wikis/documents/discussions that I should look at?

thank you

**Comment by skabashnyuk** [comment]
https://www.eclipse.org/che/docs/guice.html that is all I found

**Comment by eivantsov** [comment]
@tareqhs is this still smth that you are interested in?

**Comment by tareqhs** [comment]
Of course.
I've made a simple POC and the fundamental things seem to work. Some inconsistencies in Guice injection on top of jersey's hk2 ( or alternatively writing a native guice injection provider for jersey) and the async request processing are the two main issues I faced.

**Comment by skabashnyuk** [comment]
@tareqhs afaik we replaced async request processing with json/rpc. Can you elaborate where did you see this issue?

**Comment by tareqhs** [comment]
@skabashnyuk I've went over all the feature that Everrest supports, async is still in the source code

**Comment by tareqhs** [comment]
@skabashnyuk I've went over all the features that Everrest supports, async is still in the source code

**Comment by skabashnyuk** [comment]
Yes. However, Che is not supposed to use it.

**Comment by skabashnyuk** [comment]
@tareqhs do you have any updates on this? Is it still on your roadmap?
