### ISSUE TITLE
Chedir - Mount volume into workspace

### ISSUE THREAD

**Issue by filipef9** [eclipse-che/che#6769]
Hi,

Running Che (**eclipse/che start**), if I want to mount some volume to be imported into any workspace (e.g. .m2 folder), I override de variable **CHE_WORKSPACE_VOLUME** inside che.env. How I accomplish the same running Chedir (**eclipse/che dir up**)?

Che Version: 5.19.0

**Comment by ghost** [comment]
@filipef9 unfortunately, it looks like in case of Che Dir, this particular env is hardcoded - https://github.com/eclipse/che/blob/ee01b2998feac77f3408a80ee6e5386e09e23b9f/dockerfiles/lib/src/internal/dir/che-dir.ts#L1012

Others in `$data_dir/.che/cli/che.env` work though.

@benoitf do you happen to remember if it hardcoding CHE_WORKSPACE_VOLUME was intentional?

**Comment by filipef9** [comment]
Hi, @eivantsov and @benoitf,
There is a workaround for this issue?

**Comment by benoitf** [comment]
@eivantsov I dont think it was intentional
I don't see a workaround right now but adding option for handling this usecase should be straightforward

**Comment by ghost** [comment]
@benoitf what if we get value for CHE_WORKSPACE_VOLUME and add it to server properties then? So a user can either pass env in docker run syntax or in che.env? So, must-haves+user provided.

**Comment by benoitf** [comment]
yes it should handle:
- docker run env variable to override
- but also the Chefile CHE_WORKSPACE_VOLUME

**Comment by benoitf** [comment]
won't fix
