### ISSUE TITLE
Item ${projectName} already exists

### ISSUE THREAD

**Issue by exceptionplayer** [eclipse-che/che#693]
each time when i try to created a project, it tells me "Item ${projectName} already exists" , really difficult to use!!!

**Comment by exceptionplayer** [comment]
[look at this](http://7xo4v8.com1.z0.glb.clouddn.com/github/exists.png)

no matter what project name i change to , it does not work~

**Comment by ghost** [comment]
What is your local UID? If you run Che as root or your UID is not 1000, this issue occurs.

**Comment by exceptionplayer** [comment]
wow,thank you so much for replying me, yes ,that's right ,i was running Che as root,  but, how to solve this problem if i really need to run Che was root?

**Comment by TylerJewell** [comment]
@eivantsov Can you elaborate more about why Che cannot run as root?  I was aware that Che must run as UID 1000, but surprised about the root issue.

@Medusar The reason that Che requires UID 1000 is that this UID is passed along into the workspaces that are created by Che itself. Che creates workspaces as Docker containers. Inside those Docker containers, they inherit certain properties from the Che system.  And in order for users in the workspace to have proper write permissions, we have to pass along a UID of 1000 from Che to inside of the container itself.

So that is the UID part.  I was just surprised by the root requirement so interested to hear Eugene's description of the circumstances.

**Comment by ghost** [comment]
Che can be run as a root, but as a result there's a permission issue. We mount a local directory into `/projects` inside a container and local permissions are inherited. If a local dir is owned by root, `/projects` inside a container will be owned by root as well. A user in the container has UID 1000, thus there are problems with writing to `/projects` directory.

**Comment by TylerJewell** [comment]
Ahh, thank you that is quite clear.  So let me restate in my own words.
1. If Che is run as root, then the project files inside of the workspace are owned by root as well.
2. However, when the workspace is launched, the user in the container as UID = 1000.
3. So the user in the container will have insufficient permissions to write to the files - the user will need root privileges.

Question - is there a way for Che to give the user root permissions?  Is there a way to grant sudo rights when we first create the workspace?

**Comment by ghost** [comment]
Theoretically, we may grab UID of a current local user and run `chown` on `projects` dir in the container.

@Medusar after you have started the workspace, run `sudo chown -R user:user /projects` in Consoles - Terminal

This will fix the problems. Sure, it's a workaround.

**Comment by TylerJewell** [comment]
Would this be something we could inject into our base Dockerfiles?

**Comment by ghost** [comment]
Local folder permissions stil override the CMD. Besides, we do not know UID of a workspace user. I mean we do not know it for sure, unless this is a Che certified image. We'll discuss this with engineers.

**Comment by ghost** [comment]
https://github.com/eclipse/che/pull/754 This pull request addresses the problem. I'm closing the issue. Feel free to reopen if the problem is still there (you may try the latest nightly build in ~24 hrs)
