### ISSUE TITLE
Common commands are not available in the dropdown

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6930]
### Description
Common commands are not available in the drop-down. Stack che-in-che.
<img width="1280" alt="2017-10-24 09 03 05" src="https://user-images.githubusercontent.com/1614429/31926919-4e4909be-b89a-11e7-8b45-e30170306115.png">

**Comment by azatsarynnyy** [comment]
FYI `EXEC` drop-down displays running processes but not the commands )

**Comment by vparfonov** [comment]
@slemeur What do you think about that, looks like current implementation of command/process panel not clear for user?

**Comment by slemeur** [comment]
I believe there is a "Run" and a "Debug" buttons with a small dropdown too, which are most natural place to do those actions. 

Here the confusion is mostly due to way commands were handled in the past. 

Still, there are few things we can do to improve:
- The placeholder "Ready - Start command" can be misleading. We can have a better language like "Ready - Hit Run, Debug or Browse All to start a command".
- When there is no command running, we could display a message first row in the dropdown "Nothing running".
- The last item of the dropdown is "Create new command", I think we can add another item "Browse commands"

**Comment by slemeur** [comment]
@azatsarynnyy WDYT ?

**Comment by azatsarynnyy** [comment]
I also think that the problem is the misleading placeholder "Start command".
We should tell the user somehow that `EXEC` drop-down displays the currently running commands (and those which were run) but not all existing ones.
The placeholder with the text like "Nothing running" should be much better and enough I guess.

**Comment by skabashnyuk** [comment]
I propose to close this issue because I actually don't correctly understand the concept.
We have a right issue with an improvement of that entire place. https://github.com/eclipse/che/issues/4993 I propose to move commenting there.
