### ISSUE TITLE
Make current file location more obvious 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6932]
### Description
Many times I'm navigating to file with help of search function. After that
I open it in the editor. But it's not really clear what is the file location. And
there is no obvious way to open tree in the same location

![2017-10-24 09 14 45](https://user-images.githubusercontent.com/1614429/31927299-2483ebe2-b89c-11e7-87fd-5c47d4e00d7c.png)

**Comment by vitaliy-guliy** [comment]
@slemeur I know you have a mockup with a fantastic breadcrumb

**Comment by RomanNikitenko** [comment]
We already have Link with Editor feature
![linkwitheditor](https://user-images.githubusercontent.com/5676062/33704574-b6ec4a40-db35-11e7-92a9-4c4ba3905c28.png)
I think this issue implies implementation of Scroll from Source and Navigation Bar 
![scrollfromsource_navbar](https://user-images.githubusercontent.com/5676062/33704742-484f043c-db36-11e7-84f6-c43990178d21.png)
So I'm removing 'Link with Editor feature' from title

**Comment by RomanNikitenko** [comment]
We already have Scroll from Source feature too. But it has another name: "Reveal Resource" and it's placed in Edit menu.
![revealresource](https://user-images.githubusercontent.com/5676062/33759310-8c5a281c-dc0a-11e7-89a5-c4e93b14fd5c.png)

Looks like it's placed not very obvious. May be it makes sense to place icons for "Reveal Resource" and "Collapse All" actions here
![toolbar](https://user-images.githubusercontent.com/5676062/33759701-f09aacec-dc0b-11e7-809b-6c8ea7cc811f.png)
@slemeur WDYT?

So we need to implement Navigation Bar only and consider new place for "Reveal Resource" and "Collapse All" actions.

**Comment by slemeur** [comment]
Hi @RomanNikitenko !

There are multiple issues in one here.
First, about the "Reveal Resource", "Collapse All", "Expand All":
- We should have keyboard shortcuts for those actions.
- We removed those actions from the panel's header, because that does not scale well if there 10 different actions and panel's width is small. We wanted to enforce the use of the "Panel options", which are available with the "cog" icon. If you click on it, you'll find those actions. I believe we can find a better icon, more meaningful than the "cog" one. 
- Those actions should be available from the right-click menu too.

It's important to not overload panel's header and use a consistent way to find the panel options. 

Second, the breadcrumb. Would be wonderful to add it! Is that what you are suggesting with "Navigation Bar"? We will need to provide the ability for the user to enable/disable the display of the the breabcrumb (not all users find that useful, it's a user's preference).

I had an old design for it:
<img width="1031" alt="screen shot 2017-12-08 at 11 12 48" src="https://user-images.githubusercontent.com/1636769/33761404-2c307456-dc09-11e7-993e-8c8ffa961056.png">
If you are going to implement it - I can adapt it to the new layout.

**Comment by skabashnyuk** [comment]
@slemeur Can we "Scroll from Source" separate from "Panel options". I mean as a dedicated button.
![screenshot at dec 08 12-40-38](https://user-images.githubusercontent.com/1614429/33762423-10f3dad2-dc15-11e7-9df3-4cbd500e3f77.png)
I think it's quite often used button in such use cases: 
- Navigate to file with a search.
- Take a look around for other files that are located in same folder or module.

**Comment by slemeur** [comment]
@skabashnyuk : I agree that "Reveal in project explorer" is a sweet and useful featurel but we should be very cautious about adding that action in the panel's header! 
I understand that you are used, in IntelliJ, to get this button in the panel's header, but if we add it in Che, it will break the consistency of panel's header, add one more icon that is barely understandable.

Moreover, I do think that, the more efficient and natural ways to use the "Reveal in project explorer" feature are:
- with a keyboard shortcut
- with a right-click from the editor

So I think if we handle that, we could keep the action behind the "Panel Option" menu. 

@RomanNikitenko : Please note to rename the feature "Reveal resource" to "Reveal in project explorer".

**Comment by RomanNikitenko** [comment]
@slemeur yes, I'm going to implement the breabcrumb, so would be cool if you could adapt it to the new layout.
So we should to do:
- Provide the ability for the user to enable/disable the display of the the breabcrumb 
- Rename the feature "Reveal resource" to "Reveal in project explorer"
- Provide keyboard shortcut for corresponding actions

**Comment by skabashnyuk** [comment]
@RomanNikitenko will "Reveal in project explorer" feature act like "Scroll from Source"?

**Comment by RomanNikitenko** [comment]
@skabashnyuk "Reveal resource" works like "Scroll from Source", but it's placed in Edit menu

**Comment by RomanNikitenko** [comment]
We have a separate issue for "Scroll from Source" feature https://github.com/eclipse/che/issues/7163

**Comment by vparfonov** [comment]
So here we will done with "Scroll from Source" feature #7163 other improvement related to UI/UX changes

**Comment by skabashnyuk** [comment]
Not needed anymore.
