### ISSUE TITLE
Poor performance running JGit Maven build in Che workspace

### ISSUE THREAD

**Issue by msohn** [eclipse-che/che#694]
- install Che 4.0.0 RC11 on Mac OS X 10.11.3
- create a new project for jgit, choose 2GB RAM for the workspace, this should be sufficient since the local maven build says it used 470MB
- clone jgit git repository from https://git.eclipse.org/r/jgit/jgit
- open project in Che
- open terminal in Che
- run $mvn install in root folder of jgit's source tree
  -> build and tests take ~54min, directly on my Mac this takes around 4min !

Default machine configuration for the VirtualBox machine seems to be 1 core.
I tried to change that to 4 cores in order to see if this changes performance.
Verified in che terminal that cat /proc/cpuinfo now shows 4 cores.
It seems this doesn't improve performance for the Maven build

Another issue is that after restarting the workspace the Maven repository located in the docker image is lost. This means the next build after restarting the image has to again download a lot of dependencies which takes a while. How could I change the configuration to mount the Maven repository on the host similarly like /projects is mounted ?

**Comment by TylerJewell** [comment]
I am hoping that @gazarenkov will comment more here.  But we have been working on a new virtual file system that is now in QA and should be committed to the main stream branch this week. We have seen that the system can take an increasingly longer time to build for projects that have many files. There are operations that require recursive tree functions that are pointless.  The virtual file system introduces two concepts:
1. Selective tree operations, so that you can perform certain functions against targeted nodes without recursion.
2. File watchers, where you can target selective tree nodes and then register events against them.  For example, if you add a new file through the terminal today, you have to refresh the project tree for it to appear, such as closing / opening a folder.  That is kind of silly.  With file system watchers, our tree can watch for those VFS events and then update itself.

I know that it takes a much longer time to clone che with che, just like you are seeing with jgit.  And I think that the new VFS was designed to solve the same problems you are running into.

**Comment by TylerJewell** [comment]
On a separate topic, right now to preserve the maven repository state that is within the container, you are correct in that there are two approaches:
1. Snapshot the workspace into an image.  This gets stored into a registry.  Then you can restart the workspace with that image, keeping its state.  You can also create a default workspace stack that contains a baseline maven repository that you want others to use. If you create a workspace with that baseline image, then the initial project setup time would be reduced.
1. Have a local maven repository mounted into the container.  I will need to tap some other engineers, but I believe that the only thing we automatically mount are folders in your project storage (which goes into /projects), the web socket terminal application, and the workspace's agent.  The location of where each of these items are is stored in `che.properties`. 

So I think there should be a way to have your maven repo be a directory of your projects so that it is mounted into /projects.  Once inside of the container, you could further define the container configuration to use the maven repository in that directory.

Though I think this is not a good long term option, and the best one is for us to resolve the performance issues that you are seeing and / or have you build a base workspace image that is your own.

**Comment by ghost** [comment]
@msohn , does the time change after you build the project a second time without restarting the workspace? I mean that building a project with a clean local Maven repo will always be longer vs having a maven repo with all the deps in there.

I have run a short experiment - fired up a 8GB node on Digital Ocean, installed Java and Maven and tried to build jgit. Tests failed for some reason.. but it took ~8mins to get to that point.

**Comment by ghost** [comment]
@msohn can you provide more information please? Will mounting a local maven repo help the situation? WDYT?

**Comment by ddementieva** [comment]
@msohn any update on this? Did you get a chance to try it with a latest nightly version?
