### ISSUE TITLE
Single-port routing with multi-user mode: Gateway Timeout

### ISSUE THREAD

**Issue by tr-01** [eclipse-che/che#7059]
### Description
 
When enabling single port routing on a multi user instance of Che, loading Che in browser fails. It needs some time and returns the error `Gateway Timeout`. Single port routing on a single user instance works fine.

### Reproduction Steps
- Creating Che conf with `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /data/che:/data eclipse/che`
- Setting the following parameters in `che.env`:
    - `CHE_SINGLE_PORT=true`
    - `CHE_MULTIUSER=true`
- Starting Che with `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /data/che:/data eclipse/che start (--debug)`

**OS and version:**  Docker stable on Debian stretch amd64, lastest Che version from Docker Hub. I'm running this in my local network, so there's no firewall inbetween.

**Diagnostics:** 
- Log of `che_traefik_1` container: 

      time="2017-10-27T17:13:08Z" level=warning msg="Error forwarding to http://172.20.0.2:8080, err: dial tcp 172.20.0.2:8080: i/o timeout"

- Traefik's status page:
![screenshot from 2017-10-27 18-41-37](https://user-images.githubusercontent.com/30830304/32117207-d2fb57ce-bb4d-11e7-83d6-4581480ac614.png)

- `docker inspect` of containers `che` and `che_traefik_1`: https://gist.github.com/anonymous/a3828d3405d8824c4d1040a52b14d567

**Comment by ghost** [comment]
@tr-01 I suspect that Che multi-user has not been yet certified to run in a single port mode. Investigating.

**Comment by hickey** [comment]
This sounds a lot like the problems we are seeing, but I can not confirm that Traefik is getting setup correctly. How does one get to the Traefik dashboard?

**Comment by benoitf** [comment]
add `--debug` on the cli start it will enable this part https://github.com/eclipse/che/blob/5.20.0/dockerfiles/init/modules/compose/templates/docker-compose.yml.erb#L90-L92  (so you can have traefik console available on 7070 port)

**Comment by ghost** [comment]
@benoitf i think I found out what the problem is. Traefik and che containers end up in different networks. To be exact, che container is in both networks, but traefik tries to route traffic to the one that is in a different network.

**Comment by hickey** [comment]
What is really interesting about this issue is I think that Traefik is doing the right thing..... I can see the correct connections in sysdig when looking at the Traefik container. 

![image](https://user-images.githubusercontent.com/39609/32349883-cfa97dda-bfd5-11e7-89f6-4f41a432ae7d.png)

Just for completeness, here is a tcpdump of the connection. Traefik container is sending SYN packets, but not getting a response. 

![image](https://user-images.githubusercontent.com/39609/32350045-4ddc4ed0-bfd6-11e7-9f73-460447c6685f.png)

Ah..... @eivantsov is sort of on the right track. Jumping in the che container, I see two network interfaces (eth0 and eth1). eth0 has 172.19.0.2 and eth1 has 172.18.0.3. Traefik is picking up the IP on the first interface on the box. More specifically I think that this is because the docker is adding the che_che-network (172.19.0.0/16) and che_default (172.18.0.0/16) networks to the container and they are added in alphabetical order. 

Looking at the Traefik docs, one can set the traefik.docker.network label to force the connection to use one or the other networks. It would be great if there is a way we can shoehorn this into the existing settings to cause the routing to work correctly and validate this. Any of the che developers have an idea how to get this label set?

**Comment by hickey** [comment]
Or either that give me a rough idea where in the code the labels are getting set and I will go write a fix and submit a PR and try to get on a release in the near future.

**Comment by ghost** [comment]
@hickey nice investigation!

As to the PR, this is one way to fix it. What interests me though is why there are 2 networks anyway. I am working with @riuvshin to find it out. So, the fix may be no using `che-network` anyway, and remove it from composefile.

**Comment by hickey** [comment]
I think that the che-network is specifically set up for the workspace docker containers when in multiuser mode. This would allow a large amount of workspaced to be created without interfering with the base che containers.

**Comment by ghost** [comment]
@hickey quite possible. I tried it without this network though and was able to run a workspace. Just one though :)

**Comment by ghost** [comment]
PR's merged. Closing the issue. @hickey thanks for contribution!
