### ISSUE TITLE
Keycloak high memory usage

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#7063]
We're seeing keycloak utilising a consistent 1GB of memory in idle state (compare that to 40mb used by postgres).

This seems like a waste of resource as we only have a small number of users in multi-user mode. 

Are there any flags or work that needs to be done upstream to minimise idle memory usage?

**Comment by skabashnyuk** [comment]
Maybe @davidfestal  has some thoughts. If not, I would suggest asking that in Keycloak community. http://www.keycloak.org/community.html

**Comment by thyeun** [comment]
@skabashnyuk , issue like this better internal contributor ask, due to that we go to the community ask, the outcome will be "who are you?" or "this is not keycloak issue, should be Che issue", the ball will keep on throw here and there without any solution.

i been facing the same situation on docker last time, asking at docker community, they said it is che issue, and asking at che community, they said it is docker issue, ending result, i been throw here and there, to get a solution.

**Comment by skabashnyuk** [comment]
@thyeun ok let's try to see what we can do.
@davidfestal  are you able to make a thread or heap dump? Can you share you keycloak logs.?
How do you run it? How we can reproduce it?

**Comment by davidwindell** [comment]
I've now tried running a core version of keycloak (non openshift/no realms) and seeing similar high memory usage so think it's a property of keycloak itself.

Looking in the container, it's the Java process that reserves 1GB.

I'll close for now as it's not really affecting us.

**Comment by skabashnyuk** [comment]
You can experiment with different images 3.2.x or 3.1.x . As I remember we also noticed memory usage increase during the last upgrade to 3.3.x
