### ISSUE TITLE
Make bootstrapping of OpenShift machines parallel

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7067]
OpenShift infrastructure starts machines parallel but bootstraps them one by one. Make bootstrapping parallel should speed up the start of multimachine workspaces.

**Comment by skabashnyuk** [comment]
won't fix.  Current solution is good enough.

**Comment by skabashnyuk** [comment]
The current level of parallelism  - is workspace. We can't just simple multiple numbers of running threads by a number of machines because this wouldn't give us any profit. Too many threads will concurrently fight with other resources like a disk or network io.  Making some limits below workspaces *  number of machines we are considering as too complex to implement.

**Comment by gorkem** [comment]
@skabashnyuk what do you mean by `The current level of parallelism - is workspace.`. I thought this one was about starting containers on a multi-container workspace without waiting for each other.
