### ISSUE TITLE
Check whether we can run rh-che6 multi-user on OSIO in a multi-cluster manner

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7155]
### Description
Che5 is supposed to run on OSIO in a multi-cluster way in multi-user mode. 
We need to check whether Che6 may be run in the same way and if not create issues to accomplish this.

**Comment by sleshchenko** [comment]
#### What does rh-che assembly contain?
1. Workspace Master
Replaced default che stacks, added bayesian-agent
2. Workspace Agent
Added bayesian language server
3. GWT IDE
Replaced Che product info plugin
4. Dashboard
There are two packaging of Che Server - with and without dashboard. It is needed because OSIO doesn't provide and ability to remove workspaces. Packaging with Che Server with dashboard will be removed when OSIO will has such functionality.

#### Discovered tasks

- [x] Create new branch che6 in [rh-che](https://github.com/redhat-developer/rh-che) repository based on  [multi-tenant-rh-che](https://github.com/redhat-developer/rh-che/tree/multi-tenant-rh-che) branch.
-  [x] Adapt gwt packaging to new gwt assembling approach that was introduced in che6 branch.
- [x] Remove deprecated components that were needed to extending OpenShiftConnector. Extend OpenShift infrastructure to use OpenShift project and connection config(master url, token) which are provided by Fabric8 user service.
- [x] Remove excluding of svn plugin as it is removed in che6 branch
- [ ] Override logs folders for agents https://github.com/eclipse/che/issues/7807
- [x] Implement caching of token per workspace or investigate another way for interaction with OpenShift cluster without user (idle timeout stop, Bayesian plugin).
- [x] Update `deploy_script.sh`
- [x] BuildInfo in not packaged into che-ide war archive. So it is needed to take a look `assembly/aseembly-build-info` which unpacked BuildInfo.properties for ci scripts
- [ ] Prepare migration for workspace files https://github.com/redhat-developer/rh-che/issues/477

**Comment by sleshchenko** [comment]
Most of the required changes are made and will be merged soon. 
Then it will be possible to run workspace with Che6 on OSIO. See Demo:
![rh-che6](https://user-images.githubusercontent.com/5887312/33375453-9e98b72c-d512-11e7-8de6-6d90d2855e13.gif)

Few of tasks will be done in separated issues.
