### ISSUE TITLE
Failed to update git index notification

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#7220]
### Description
Sometime, when try to add a new file to index a weird notification with error is shown.

### Reproduction Steps
1. Open a workspace from java stack
2. Create `web-java-spring` project from samples
3. Open `README.md`, edit it. Wait until its status is set to edited.
4. Delete `README.md`
5. Open `org.eclipse.che.examples` package and create a java class here (`context menu` -> `new` -> `Java Class`)
6. Select just created file in project explorer and try to add it to index with `Main Menu` -> `Git` -> `Add To Index...`. Then click `Add`.

The notification with an error is shown.
![screenshot from 2017-11-07 10-56-49](https://user-images.githubusercontent.com/15607393/32484979-63ce4ba8-c3aa-11e7-88d3-1192fbd415e3.png)

**Comment by tolusha** [comment]
After adding to the index a newly created file we try to add to the index removed files:
https://github.com/eclipse/che/blob/46ddf5e8403cde5a2c9e827b8916ae94f52830a4/wsagent/che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitConnection.java#L335

And removal command fails since there are no files matching the pattern:
https://github.com/eclipse/che/blob/46ddf5e8403cde5a2c9e827b8916ae94f52830a4/wsagent/che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitConnection.java#L356

Either we don't have to call command or revise the logic:
https://github.com/eclipse/che/blob/46ddf5e8403cde5a2c9e827b8916ae94f52830a4/wsagent/che-core-git-impl-jgit/src/main/java/org/eclipse/che/git/impl/jgit/JGitConnection.java#L353
