### ISSUE TITLE
Openshift 3.5 Multi Machine workspace || DB Service name conflict

### ISSUE THREAD

**Issue by hbhargav** [eclipse-che/che#7232]
### Description
On launching Java-MySQL multi-machine workspace on Openshift, service name for db machine is generated as '**db**', everything works as expected.

However, on launching another Java-MySQL multi-machine workspace, Openshift spits out an error saying services '**db**' already exists, kills the running DB pod of first workspace.

### Reproduction Steps
Deploy Che on Openshift 3.5
Launch Java-MySQL workspace
Launch another Java-MySQL workspace

**OS and version:**    
CentOS 7.3

**Diagnostics:** 
I see the issue is coming from OpenShiftConnect.

if (isDevMachine(createContainerParams)) {
      serviceName = deploymentName = CHE_OPENSHIFT_RESOURCES_PREFIX + workspaceID;
    } else {
      if (endpointAliases.length > 0) {
        **serviceName = endpointAliases[0];**  
        deploymentName = CHE_OPENSHIFT_RESOURCES_PREFIX + serviceName;
      } else {
        // Should never happen
        serviceName =
            deploymentName =
                CHE_OPENSHIFT_RESOURCES_PREFIX + KubernetesStringUtils.generateWorkspaceID();
      }
    }

In the above code block **endpointAliases[0]** is always **db**

**Comment by ghost** [comment]
@hbhargav that should be fixed in che6 branch.

@sleshchenko @akorneta  can you confirm? Are there any prefixes for service names?

**Comment by sleshchenko** [comment]
No, I can't. There are no any prefixes for service names in che6. Because service name can be used by users for communication between containers. In case of `Java-MySQL` stack, application inside of `dev-machine` can access the database by alias `db`. Like our `petclinic` sample https://github.com/che-samples/web-java-spring-petclinic/blob/mysql/src/main/resources/spring/data-access.properties#L28
Otherwise, we should provide an ability for a user to get real access URL(for example via an environment variable) and it's not good because user's application should be modified according to specific of launching compose files on Che.

**Comment by ghost** [comment]
@sleshchenko so, we will see the same behavior with Che6?

**Comment by sleshchenko** [comment]
We haven't implemented support of `compose` recipes by OpenShift infra yet. But quite similar behavior will be in case of using OpenShift service in OpenShift recipe. See [OpenShift SQL stack](https://github.com/eclipse/che/blob/che6/ide/che-core-ide-stacks/src/main/resources/stacks.json#L2938) in che6 branch.

**Comment by garagatyi** [comment]
I suppose we may have another behavior in case multiple OS projects are allowed for each user. @sleshchenko Am I right?

**Comment by ghost** [comment]
Yes, in case of namespace per workspace this issue is gone

**Comment by ghost** [comment]
Closing as fixed. Workspace pods are started in their own namespaces in Che6.
