### ISSUE TITLE
GitHub plugin

### ISSUE THREAD

**Issue by MitchK** [eclipse-che/che#738]
Hi!

I'd be interested whether there will be a GitHub plugin. 
Something like being able to check out various pull requests in an own workspace, give line comments, create issues, etc. Would simplify code reviews dramatically. 

There could be also a `.cherc` file (not GitHub-specific), basically a shell script that executes all steps on workspace startup to configure project-specific configuration. This would enable to check out and run/test any commit.

**Comment by TylerJewell** [comment]
@MitchK: We provide a GitHub plugin as part of Codenvy, but it's not yet in Eclipse Che. It's not for any sort of commercial reasons, as it has more to do with the nature of configuration that is required. We try to keep Eclipse Che minimal in its configuration (thus no embedded user database to install).

In Che we do have GitHub oAuth support, the ability to browse and navigate repositories within the Dashboard, and all the traditional git command line options. We have some nice features to auto upload SSH keys to GitHub, too.

The Codenvy GitHub plugin only does a little of what you are seeking.  It's core capabilties include:
We have a pull request panel directly within the IDE.  It's really nice. You can create multiple pull requests. Since you can have many projects mapped to many repositories in a single workspace, you can have pull requests for different projects. If you issue the pull request from within Codenvy, we will either take your existing branch, or we'll do a fork of the source repository into your account, create a local branch there, and then push your workspace changes onto that branch and issue the pull requests from that point.  Finally - and this is the best part, in the GitHub pull request chat window on GitHub, we inject a Codenvy Factory badge.  Any reviewer who clicks on that badge will get their own custom workspace, in their own Codenvy account that has exactly the runtime and source code that lines up with the pull request.  They can then build and run it if they want - all without having to set up any extra configuration.

**Comment by TylerJewell** [comment]
@MitchK - we now provide Chedir (see the docs), which is exactly the sort of workflow that you are seeking. We started shipping this as part of 4.7.2.
