### ISSUE TITLE
POC for  IDE Part API for the JavaScript endpoint

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#7411]
### Description
We need to develop a mechanism for injecting custom UI widgets to the IDE Part. 
New widgets should be represented by an IDE Plugin.

**Comment by benoitf** [comment]
should it be added to https://github.com/eclipse/che/issues/6647 ?

**Comment by benoitf** [comment]
Hello, I don't know what it your next item on the list for the POC but I think it would be nice then to have the events.
Because most of the plugins are reacting on events, it would allow to create fully functional plugins very easily if events are there

For example : events when keyboard is pressed in the editor, when file is saved, etc.

with action/theme/part API we could then have a widget displaying the current position of the cursor or counting the words of the current document.

**Comment by vparfonov** [comment]
@benoitf Yes, it will be our next step. Next issue will be JS API for Even System and Application Context

**Comment by benoitf** [comment]
@vparfonov nice !
