### ISSUE TITLE
Browser's size in the selenium chrome node is not set properly

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7602]
*Related test:*
CheckErrorsWarningsTabTest

 In the current state selenium tests run in "grid" mode without defined browser size.
 So probably we can have different browser sizes in the different tests. 
    For resolving this problem we need provide next environment variables when our "chromenode" starts: 
```
-e SCREEN_HEIGHT=1080
-e SCREEN_WIDTH=1920
-e SCREEN_DEPTH=24

**Comment by dmytro-ndp** [comment]
According to the resolution of captured screenshots the resolution of browser's window inside the selenium chrome node is about **1920x1080** due to the command [`driver.manage().window().setSize(new Dimension(1920, 1080))`](https://github.com/eclipse/che/blob/5.21.0/selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/SeleniumWebDriver.java#L268):
![screenshot from 2017-12-04 14-09-44](https://user-images.githubusercontent.com/1197777/33552215-d65828ee-d8fc-11e7-9790-8d95c65d8fce.png)

Environment variables `SCREEN_HEIGHT` and `SCREEN_WIDTH` just set the resolution of container's desktop itself. It can be proved by entering selenium chrome node remotely:
- with default desktop screen size **1360x1020**:
![screenshot from 2017-12-04 14-38-27](https://user-images.githubusercontent.com/1197777/33553408-4f2fa2d4-d901-11e7-8304-892784f870aa.png)

- with desktop screen size **1920x1080**:
![screenshot from 2017-12-04 18-35-09](https://user-images.githubusercontent.com/1197777/33563933-e70e3df2-d921-11e7-8144-d16bca44a180.png)
