### ISSUE TITLE
Add an ability to configure logs dir for agents

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7807]
### Description
Che 5 on OSIO have an ability to configure logs dir for agents (like workspace agent and exec agent). 
But agents in Che 6 hold own logs in their default logs folders and there is no ability to configure that.
So it is needed to have an ability to configure logs dir for agents https://github.com/redhat-developer/rh-che/pull/461#issuecomment-347820591

**Comment by garagatyi** [comment]
The idea I'm going to implement is following:
1. Che master adds an env var to machines which says base dir for all logs of any software interested in persisting logs between workspace restarts. Let's call it CHE_LOGS_BASE_DIR
1. Che may mount this folder somewhere to persist its content between workspace restarts
1. Any agent or installer that is running inside of a workspace machine can read this env variable and store its logs there. It is better if each interested software creates its own subfolder of folder provided by env var and stores logs files in this subfolder.
1. If folder specified by that env variable doesn't exist or agent, for example,  doesn't have rights to write logs there it can fail or write logs into another directory (should we choose single strategy here?)
1. If environment variable is missing or empty then agent, for example, should use another folder for storing logs

@sleshchenko @skabashnyuk @l0rd Do you think guys this strategy is OK?

**Comment by garagatyi** [comment]
One thing suggested by @sleshchenko is that I'm not going to add an obligation for the infrastructure implementation to persist those logs. But infrastructure may do that if it will.

**Comment by l0rd** [comment]
@garagatyi that looks of for me. We should probably also define a default value for `CHE_LOGS_BASE_DIR` that would be used in case the var is empty or missing (point 5.). For point 4 the simpler the better. 

Ideally agents should log on stdout and the [infrastructure should take care of the logs delivery/backup](https://docs.docker.com/engine/admin/logging/overview/). But that's not possible now because we run multiple agents per container. As a workaround we need to log to a volume.
