### ISSUE TITLE
Implement supporting of compose based recipes by OpenShift infrastructure

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7860]
### Description
Implement supporting of compose based recipes by OpenShift infrastructure.

**Comment by dmytro-ndp** [comment]
It makes it impossible to create workspace of **Java-MySQL** types
![screenshot from 2018-01-19 11-33-51](https://user-images.githubusercontent.com/1197777/35144256-b4c6f4a6-fd0c-11e7-9d95-5c4537fb9bea.png)

**Comment by slemeur** [comment]
agreed for the time being.

**Comment by garagatyi** [comment]
In case someone wants to contribute it here are a couple of tips:
Here is an example of a converter that converts one environment into another https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/convert/DockerImageEnvironmentConverter.java
This is a very simple one, a converter of compose would be more complex because compose recipe contains a lot of syntax constructs.
Here is an example of a compose converter https://github.com/eclipse/che/blob/master/infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/convert/ComposeEnvironmentConverter.java
It shows pretty well how it can be implemented on the k8s infra. 
After implementing such a converter it is needed to apply it, so here is a place and an example where/how to do it https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfrastructure.java#L76

This is it. I hope it would be enough to implement such a feature. If not, do not hesitate to ask me for more details.

**Comment by tgrall** [comment]
> agreed for the time being.

If this is not working why not hiding this option until it works?

**Comment by garagatyi** [comment]
We can hide it. But not sure which part should do that. API can avoid returning is, but I'm not sure we need this behavior. The client can skip it. Or client can ask for only supported ones from the API.
On the other hand, stacks might not make sense in Che 7, so we can avoid investing in that.

**Comment by skabashnyuk** [comment]
@l0rd is this issue still relevant for Che7?

**Comment by l0rd** [comment]
I guess this is still relevant. @slemeur?

**Comment by ibuziuk** [comment]
@gorkem @slemeur any plans to invest into this or can we close this one?
