### ISSUE TITLE
Save Option

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#789]
Save Option in IDE:

I need to do customization for saving a file. I found that, there is only three listeners and one filter in web.xml file. There is no any other servlets mapping over there. How is it mapped for saving a file? Which file does it refers when i save a file ? 

I was not able to get an idea from web.xml file to find the rool level structure of the code for all functionality .
Can you please assist me how to check the functionally without web.xml file entries.

**Comment by ddementieva** [comment]
If you are looking for the REST service, which is responsible for the update file process, you can find it here https://github.com/eclipse/che/blob/master/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java#L474

**Comment by SangeethaSivanesan11** [comment]
Thanks much for the reply.

 I will go through the rest api class file which was shared by you.
 Also, please share the file which is referred for content assist.

 But how it is mapped via client. Because,  there is no servlets mapping in web.xml file.  

Which file will be referred for the immediate request of content assist/save option from IDE/client ?

Web.xml file consists of three listeners (CodenvyBootstrap,ServerContainerInitializeListener,WSConnectionTracker) and one filter(Guice).

Which file will be invoked, when I save/request for content assist from IDE. 

I had gone through the concept of guice filter and CodenvyBootstrap listener. I have noticed @Inject annotations used in plugin and core source files. But, I didn't notice where the instance are created and invoked  via IDE.  Where the instance are created and how they are injected ?

I didn't get an idea without servlets mapping in web.xml file. Which is the base files that will refer for all the request? Please share the outline view to check the functionality without web.xml file. 

Please clarify !!

Thanks in Advance.

**Comment by SangeethaSivanesan11** [comment]
I have been waiting for your reply.

Please assist me to proceed further.

**Comment by ddementieva** [comment]
All classes with [@DynaModule annotation](https://github.com/eclipse/che/blob/0a14fd9bc7e329a485ed1d3551c30cbffeb2e759/core/commons/che-core-commons-inject/src/main/java/org/eclipse/che/inject/DynaModule.java#L26-26) are deployed to the container automatically. 

Base class for all the REST services you can find here https://github.com/eclipse/che/blob/e9c4c4901cf45d0cd9cb3f919d16c42eee872b01/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/Service.java#L55-55

**Comment by SangeethaSivanesan11** [comment]
Thanks for your reply.  

Please share the Rest api service file which is referred for content assist.

**Comment by TylerJewell** [comment]
@SangeethaSivanesan - can you please share details on the project that you are working on.  What is the objectives of the project, the requirements, its packaging, how it will be sold.  It will be easier to help with the various SDK questions if the engineers understand what is being built.  

The engineers will be building a plugin resource and SDK center over the next many months - so a lot of best practices to go into those documents.

**Comment by SangeethaSivanesan11** [comment]
Hi Tyler,

I was trying to create my own IDE for my personal project purpose. When I was analyzing related to IDE, I had come across CHE and its architecture seemed to be interesting and different one. 

So, I would like to build my IDE with Che. I think Che is the open source for all new ide developers. 

I had gone through the open source code of CHE which is available in this link (https://github.com/codenvy/che.git). I was not able to understand the full flow and structure of the code, as it seemed to be little diffcult.

 I would like to know about the complete structure from the starting point. Can you please help to get through the code from the starting base point (i.e where it gets starts from and it triggers request), its flow which is mapped in web.xml, where and how it is mapped . 

Now, I have an idea about which is the base point of all rest api service. Its base class is Service.java as daria shared in previous thread. But, I  don't know how it is mapped when i request for content assist and save option.

*_My requirement is to do customization in content assist (Code Completion)  and save option. *_

Please assist me to get through the code which will be helpful to proceed further.

Thanks in Advance. Awaiting for your reply.

**Comment by TylerJewell** [comment]
@SangeethaSivanesan:  That sounds like an exciting project.

We are documenting how the product works for extension developers in our docs.  We discuss the startup capabilities in [Developing Extensions](https://eclipse-che.readme.io/docs/developing-extensions) and in [Assemblies](https://eclipse-che.readme.io/docs/assemblies).  We are starting to build out additional docs in the [building extensions](https://eclipse-che.readme.io/docs/calling-workspace-apis) section including how extensions call server-side JAX-RS services.

We are going to work on creating a proper set of plug-in and extension development docs for advanced developers over the next 3-5 months.  So each week we do expect additional examples and information to appear.

In the mean time, our Java plugin is the most advanced plugin and does most of the content assist intelligence.  It's that plug-in that shows how various editor calls are then mapped to server-side calls and back.

**Comment by SangeethaSivanesan11** [comment]
Hi Tyler,

Thanks for your reply. 

I will go through the basic startup documents as you referred in previous comment. 

I had a doubt related to plugin. I came to know that we can add a new plugin (https://eclipse-che.readme.io/docs/developing-extensions). I had gone through the link for developing new extensions. 

Is it possible to edit with existing extension (i.e  existing plugins. To enhance the existing plugins) ? 

If so, please share the details to modify/enhance the existing plugins.

Thanks in Advance. Awaiting for your reply.

**Comment by TylerJewell** [comment]
Sanjeeva:

Yes, you can build the existing extensions using the same steps that we
have in the tutorial.  You just build in the /plugins directory.  All of
the extensions included in /plugins are already linked into the assembly.
So any changes you make there will be automaticlaly reflected in the
product.

Tyler

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by SangeethaSivanesan11** [comment]
Hi Tyler,

Thanks much for your reply. 

I found all existing extensions were mapped in pom.xml (assembly-ide-war (Client) and assembly-machine-war(Server)). It will download as a dependency when che assembly is built. I had a query related to gin and guice injection (Dependency Injection).

Plug-in can have as many Gin and Guice modules as I would like. The Che plug-in packaging tools will add all modules so that they are injected at the right time.
1. What is che plugin-in packaging tools ?
2. How will it be injected in right time ? will it inject automatically ? If so, please clarify.

When the Che assembly is built, it will download your extension as a dependency and compile it into the Che IDE application. Then, the jar will be updated in web-inf/lib folder .  is my understanding right ? 

"When the Che IDE application is activated your GIN modules are invoked for dependency injection". Where it is mapped and how it is invoked automatically?   

Thanks In Advance.

Sangeetha.S

**Comment by TylerJewell** [comment]
See below.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

On Thu, Apr 7, 2016 at 6:03 AM, Sangeetha notifications@github.com wrote:

> Hi Tyler,
> 
> Thanks much for your reply.
> 
> I found the existing extensions mapped in pom.xml. It will download as a
> dependency when che assembly is built. I had a query related in gin and
> guice injection (Dependency Injection).
> 
> Plug-in can have as many Gin and Guice modules as I would like. The Che
> plug-in packaging tools will add your modules so that they are injected at
> the right time.
> 1. What is che plugin-in packaging tools ?
> 
> ​It is the simple tool that is documented in this section - it just
> automates some of aspects of adding extensions as dependencies:​

​https://eclipse-che.readme.io/docs/developing-extensions#package-extensions
​

​https://eclipse-che.readme.io/docs/assemblies#custom-assemblies​
https://eclipse-che.readme.io/docs/plug-ins#section-create-packages-and-assemblies
1. How it will be injected in right time ? will it inject automatically ?
   > If so, please clarify!
   >
   ​The install-che-plugin just takes care to update the pom.xml and any GWT
   xml files for you.  But the docs outline how you can do this manually as
   well.​

**Comment by SangeethaSivanesan11** [comment]
Hi Tyler,

Thanks much for the clarification. I will go through the links which you have shared. 

Sangeetha.S

**Comment by SangeethaSivanesan11** [comment]
Hi Tyler,

What is the use and advantage of GWT (Google Webtool Kit) which is used in CHE?

Why cant we go for html files rather than GWT?  Is there any advantage of using GWT over html files?

Will the GWT be invoked once the application is deployed or during maven build time? 

Please clarify.

Awaiting for your reply.
Thanks in advance !

Sangeetha.S

**Comment by TylerJewell** [comment]
We use GWT to generate cross-browser JavaScript. It is small, optimized, and makes the application into a single page Web application.  GWT compilation happens at maven build time.  We use dependency injection with Guice that allows us to inject different kinds of Java classes into the compilation and into the configuration when the Web application starts.  Dependency injection is what allows us to have a clean plug-in abstraction.

A plugin within Che must be in GWT.  You cannot bypass it.  You can create a plugin in GWT that invokes JavaScript or HTML, though.

**Comment by SangeethaSivanesan11** [comment]
Hi Tyler,

Thanks much for the clarification. 

Sangeetha.S

**Comment by SangeethaSivanesan11** [comment]
Hi,

What is the usage of che-core using in che?  How che-core and plugins are interrelated.
Is there any mapping to interrelate both? 
Where and how is it mapped ? Can I use plugins without che-core ?

Please clarify. Thanks in Advance.

Sangeetha.S

**Comment by ghost** [comment]
che-core, as its name suggest is a core part of Eclipse Che. Plugins are build on top of it. core modules container all of the REST APIs, the IDE UI, models for such entities as workspace or project etc.

Plugins use core artifacts as dependencies.
