### ISSUE TITLE
Unnecessary notification about repository checkout during importing a big project

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#7997]
### Description
Discovered while cloning https://github.com/eclipse/che repository into Che. The problem is so user is getting a notification about git checkout operation before project is imported. See on the bellow screenshot:
![image](https://user-images.githubusercontent.com/1968177/34255601-1a8fb2d8-e65a-11e7-9bfb-e8a729bc85c1.png)

Checkout operation at 12:56 PM
Import finished at 1:03 PM

### Reproduction Steps
Try to import https://github.com/eclipse/che into Che.

**Comment by vinokurig** [comment]
The problem is that `GitCheckoutDetector` send's checkout event when `HEAD` file from `.git` directory is created. This is done so because when native Git or JGit making a checkout they do not modify the `HEAD` file, they re-create it. So catching create events works good, but cloning a repository also causes creation of `HEAD` file and that's why this notification appears.

**Comment by tolusha** [comment]
Until clone operation isn't finished, `.git/refs/heads` directory is empty.
We have to improve GitCheckoutDetector taking into account that fact.

**Comment by vzhukovskii** [comment]
Not actual
