### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by gorbunkov** [eclipse-che/che#802]
Hi! Do you have any plans to implement a gradle support? I found a description how to create a project on your site (https://eclipse-che.readme.io/docs/che-and-gradle), but code completion and dependency refreshing seem not to work in this project. Are there any plans to implement it?

**Comment by TylerJewell** [comment]
@gorbunkov Code completion should be present for any Java / JavaScript related file, regardless of the build system. Can you provide specifics on the project type, project structure, version - so that engineers can take a look at whether there is an issue with language services?

As for a proper gradle plugin, we are continuing to advance the maven plugin for the forseeable future - there are another couple dozen features that are getting built into it.  The most notable is that we are creating an internal maven repository structure within our object model and this allows us to generate unified POMs, dynamic classpaths (essential for things like OSGi or GWT), and the so forth.

We would eventually need an evolving level of support for a similar type of capability stack for Gradle. We started on a plug-in a year ago and it got partially complete. It needs to be refreshed for this generation of the system and numerous issues needs to be worked through.  We are seeking interest and help from the community to consider picking up this plugin and working on it.

**Comment by gorbunkov** [comment]
@TylerJewell About the language service issue: I just followed the instructions from https://eclipse-che.readme.io/docs/che-and-gradle.
I selected to import a project from the source: https://github.com/che-samples/console-java-gradle
Then I defined a custom stack: FROM codenvy/ubuntu_gradle
After the project was created I went to the HelloWorld.java file and content assistant didn't work there. 

Che version: 4.0.0.RC13
Che install directory: D:\Che\eclipse-che-4.0.0-RC13
Docker version: 1.10.3
Java version: 1.8.0_66
Environment details: Windows 7 (x64), VirtualBox v5.0.16 r105871

**Comment by ghost** [comment]
Yes, this is expected behavior, since at the moment content assist works only for Java projects which in their turn can only be Maven projects.

**Comment by TylerJewell** [comment]
We are talking to the engineering team about the way to make language services work for any project type.  I was mistaken in that I thought we supported others than maven but it turns out that right now it is a limitation.

Two ways we will solve this.  First, if you have a maven Pom that lists your dependencies you can add that to your project directory and that will trigger the intellisense.

Second we will add a classpsath configurable that lets non maven projects specify their jar list which is the input we need to provide those intellisense services.

**Comment by TylerJewell** [comment]
@gorbunkov - this is now in specification design.  We will definitely see this available in Q2.  We don't think this is a lot of work, so you can expect it in a near term release.

**Comment by gorbunkov** [comment]
@TylerJewell Do you mean that gradle projects support is in specification design now? Or the ability to configure classpath you mentioned in the previuos comment?

**Comment by TylerJewell** [comment]
It was about the classpath element so that non Maven projects can configure themselves to gain intellisense for Java.

**Comment by TylerJewell** [comment]
@gorbunkov - we added a new java plugin that supports providing intellisense for gradle projects now. This was offered in 4.3.

**Comment by gorbunkov** [comment]
@TylerJewell Great news! We will definitely try that. Thank you.

**Comment by vorburger** [comment]
Issue https://github.com/eclipse/che/issues/2669 clarifies that, as of 20 Nov 2016 (after above), Che _"does not yet have a complete native Gradle project type like it does for maven, which can inspect the dependencies list and automatically download them."_

**Comment by marioplumbarius** [comment]
Any plans to give support to Gradle-based projects?

**Comment by ghost** [comment]
Yes, as soon as jdt language server replaces current java tooling.

**Comment by vorburger** [comment]
@marioluan you may like [the workaround](https://github.com/che-samples/console-java-gradle/pull/1/files) of [getting Gradle to write a POM which Che can use](https://github.com/eclipse/che/issues/2669#issuecomment-282495814).

**Comment by marioplumbarius** [comment]
@vorburger Cool. Might be enough for now. Thanks for the tip!

**Comment by nickboldt** [comment]
There's a new Gradle 5.2.1 / JDK 11 stack available OOTB in Che 7 RC1, which appears to sort of work w/ the sample gradle project.

![image](https://user-images.githubusercontent.com/227597/59536235-25788b00-8ec1-11e9-8698-18268d5f7b6d.png)
