### ISSUE TITLE
Unexpected fails selenium tests on login page

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8095]
We have a bug which reproduced in the selenium tests on the "openshift" platform and in "multiuser" mode.  Each run, several tests are failed with this problem. 

*Screenshot:*
![screenshot from 2017-12-28 15-10-41](https://user-images.githubusercontent.com/22724619/34411731-67f6e67c-ebe1-11e7-98dd-e9e65f6ef13c.png)

*Report with reproduced problem:*
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/63/Selenium_tests_report/

**Comment by dmytro-ndp** [comment]
It usually happens if timeout on waiting of login page is opened is too short. I would suggest to increase wait login page opened timeout in [**CheLoginPage#waitOnOpen()** method](https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/site/CheLoginPage.java#L98).

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8098
