### ISSUE TITLE
Workspace always run after creation

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#8167]
### Description
It is no way now to not to start workspace after creation.
Sometimes it is very useful to adjust some parameters after creation, for example add a server (expose port), add an installer (a language server), etc. And in this situation a user have to go to dashboard, stop workspace(interrupt starting) then change extra configuration and again start the workspace.

### Reproduction Steps
1. Open dashboard, `Workspaces` tab, click `Add Workspace`
2. Select some stack and other parameters
3. Click `Create` button

**Comment by tolusha** [comment]
@mmorhun 
It is supposed to create a new stack from existed one and adjust any parameters you want

**Comment by ghost** [comment]
@mmorhun I tend to agree with @mmorhun If I want to use a ready to go stack but just need to create a ws and then edit its config, the only way to do so is to run and stop it, or create a new stack :(

**Comment by ashumilova** [comment]
The proposal to solve this problem is the following: 
1. Change create button in the workspace creation page toolbar to dropdown button with two options: 
- Create and Open - creates workspace and opens it in IDE 
- Create and Edit - creates workspace and redirects to the workspace details page

2. Create button on the very bottom of the page - leads to the option dialog with 2 options: 
"Workspace is successfully created. " (title - Workspace is created.)
- Edit Workspace
- Open Workspace
