### ISSUE TITLE
Determine Che-in-Che Resource Requirements with jdt.ls

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8335]
We should experiment with the -Xmx parameter when launching the jdt.ls LS to determine when adding memory stops leading to significantly better performance. At this setting, get numbers for importing Che in Che.
Also, we should determine the minimum amount of RAM jdt.ls needs to import Che. When I tried with the default 1 Gig, the import failed after a long time.

**Comment by bdshadow** [comment]
i'm working on it

**Comment by tsmaeder** [comment]
@bdshadow I was able to import Che into VSCode in about 12 min with 3 Gb RAM. Code assist, references, etc. work fine. What are we doing wrong?

**Comment by bdshadow** [comment]
The only way to import che into che without OutOfMemory error is to do the following steps:

1. Run Che from scratch (remove `data` directory, check that you're creating a new workspace container and not using the stopped previous one)
2. Add Workspace
3. Choose "Eclipse Che" stack. Right here import Che into workspace 
4.  Click "Create"
5. In popup window click "Edit" (not "Open Workspace"). So now we have a created workspace, but not started. 
6. Go to Installers tab and switch on JLS.
7. Click open to start and see the workspace. 
8. Wait and see the log.

However, after we see that all projects are updated in the logs and LS is started, it looks like it doesn't work. Every attempt to use LS ends with a stack trace in the dev-machine log (e.g. auto completion).

If you change the step 5 and open the workspace first and then start LS (with workspace restart), you'll get and OutOfMemory while updating projects.

Here are the stack traces which i caught with OutOfMemory errors: https://pastebin.com/PFGZF3v7
Also before getting OutOfMemory error, i always had the following: https://pastebin.com/p8Zvgb2P

From these exceptions it seemed to me that problem is in the cache (`com.google.common.cache.LocalCache`), used by m2e `ProjectRegistryManager`: https://github.com/eclipse/m2e-core/blob/11922879173b8516103e935c574be289bc1cbe9c/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/ProjectRegistryManager.java#L1088. I tried to make this value less down to 0. And got OutOfMememory later and later while making it less. Anyway this hardcoded capacity of the cache seems suspicious to me.

Also i tried to change properties `che.workspace.java_options`, `che.workspace.maven_options,` `che.workspace.wsagent_java_options`, `che.workspace.maven_server_java_options` here: https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L72, but haven't noticed any effect, though tried to set `XX:MaxRAM` up to 4GB.

Via profiler i found that at the moment of OutOfMemory error multiple works do their job, trying to update\refresh projects or parse `pom.xml`s.

**Comment by bdshadow** [comment]
@tsmaeder @fbricon @mmorhun ^

**Comment by bdshadow** [comment]
also @mmorhun and me tried to increase the amount of memory available for language server in the `org.eclipse.che.ls.java.script.sh`. As far as i remember @mmorhun was able to import che when he set it to 20Gb, but anyway had lots of problems after

**Comment by fbricon** [comment]
Rationale behind the hardcoded limit to 5 in m2e cache:

> As I explained in the past, m2e requires about 1M+ of memory
for each opened workspace maven project. Although memory is cheap and
getting cheaper, using large heap results in noticeable garbage
collection overhead, which becomes apparent with very large workspaces
that require 2G+ of heap. This was getting rather annoying for my nexus
development workspace where I have 300+ projects, so I decided to rework
how m2e manages its various memory caches.
The first change I just pushed limits number of long-lived MavenProject
instances to just 5 (five). For my workspace and development
habits this reduced Eclipse heap requirements from ~2.5G to well under
1G without any noticeable side affects. This, of course, does not mean
there are no problems with this change and I'd like to see if other
users with large workspaces can give it a try and provide any feedback,
good or otherwise.

https://dev.eclipse.org/mhonarc/lists/m2e-dev/msg01389.html

See also https://dev.eclipse.org/mhonarc/lists/m2e-users/msg05095.html

**Comment by tsmaeder** [comment]
I've looked at the dump and the root of all evil (aka retention of around 1.8 gig each) is a workspace job from ProjectsManager$3
Which is the job created in ProjectsManager#updateProject(IProject). Should be easy to find out where it is coming from.

**Comment by tsmaeder** [comment]
Looking at the heap dump, there seems to be around 8meg retained per MavenProject instance, not 1.

**Comment by skabashnyuk** [comment]
@tsmaeder  I would suggest to start with ```-XX:MaxRAM=600m -XX:MaxRAMFraction=1 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms50m -Djava.security.egd=file:/dev/./urandom```  according to my studies it https://github.com/eclipse/che/pull/8023 should be enaught

**Comment by bdshadow** [comment]
@skabashnyuk already tried. see [my comment above](https://github.com/eclipse/che/issues/8335#issuecomment-363062536)

**Comment by skabashnyuk** [comment]
Can see in your comment about what JVM settings were used. Are you able to connect to JDT LS with Jvisualvm or jprofiler? are you running it as sidecar or as part of workspace agent?

**Comment by fbricon** [comment]
@bdshadow in vscode-java, we launch jdt.ls with `-XX:+UseG1GC -XX:+UseStringDeduplication`, it might have quite an impact on memory usage, given the large amount of String instances in the heapdump I saw

**Comment by bdshadow** [comment]
@fbricon tried with `-XX:+UseG1GC -XX:+UseStringDeduplication` - didn't help

**Comment by skabashnyuk** [comment]
@bdshadow are you using this https://github.com/eclipse/che/blob/5730_java_ls_poc/agents/ls-java/src/main/resources/installers/1.0.1/org.eclipse.che.ls.java.script.sh#L138 installer to run java.ls?

**Comment by bdshadow** [comment]
@skabashnyuk yes

**Comment by skabashnyuk** [comment]
are you modifying script itself to test new settings?  As far as I can see ```-Xmx1G``` is hardcoded.   
AFAIK ```che.workspace.java_options``` is not designed to be used in installers.

**Comment by bdshadow** [comment]
@skabashnyuk 
yes i'm

1. Modifying this line
2. rebuild the whole che
3. delete data directory
4. remove all old che containers
5. start che

**Comment by skabashnyuk** [comment]
Have you checked ```cat /proc/<pid>/environ``` of the java.ls process, is it used jvm settings as you expect?

**Comment by fbricon** [comment]
So I think I found a bunch of areas where we could improve things:
- heapdump shows 2 competing threads trying to update project configuration, retaining 1.8GB in the maven execution context. It should probably not be allowed to have concurrent jobs running project update configuration. Taking a workspace lock would probably be a last resort measure. BTW, those 2 requests should not be happening. Seems like che is issuing commands to update the projects on startup (or the user did)
- right after import, if the project already exists we always call "update project configuration". Instead we should check of the project pom is more recent than the last time the project state was saved
- the download sources job actually loads all maven projects, so their classpath can be updated after the sources have been downloaded. There's probably room to limit what's loaded there, on the m2e side

That's the easy part.
Then I need to figure out why we have such large MavenProject instances loaded in the 1st place.

**Comment by tsmaeder** [comment]
@fbricon @bdshadow folks, we might very well get a reduction of the 1.8Gig per thread by passing vm options (and we should do that). HOWEVER, the heap dump is from an OutOfMemoryException, which means the VM tried hard to find free memory and it could not. No amount of GC option fiddling will fix that.
The REAL problem here is that we're rebuilding everything 4 times (in the case of the heap dump provided). I have determined that the root of that rebuild is in ProjectsManager#updateProject(). @bdshadow can you put a breakpoint in that method and find out what Che is doing to cause this? I'm fine with needing 3Gig for Che-in-Che, but not with an unknown amount of RAM needed.

**Comment by bdshadow** [comment]
Looks like i found the root of the problem, and trying to solve it now. It's something like @fbricon explained in the second item in his comment: https://github.com/eclipse/che/issues/8335#issuecomment-363819694.

While initializing language server, we register `LanguageServerFileWatcher`. When the LS is initialized this watcher sends messages to the LS, that `pom.xml` files are created.  It leads to `org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.fileChanged(String, CHANGE_TYPE)` is fired with `CHANGE_TYPE=Created` which `updateProject(resource.getProject());` on line 193. Look inside this `org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.updateProject(IProject)` it runs in separate `WorkspaceJob`. It means we're trying to update all 56 (or how many ? :) ) projects simultaneously. 

Moreover we don't neeed to this. Because we've just imported this projects as Maven ones. It means everything is already updated and imported correctly. So we need not to call this file watcher when we just imported a project or we should check how long ago we did this

**Comment by bdshadow** [comment]
Sorry, missed that Fred has already created an issue https://github.com/eclipse/eclipse.jdt.ls/issues/544. I think it's a good way for improvement, but in my opinion the current  issue must fixed on Che side too. See my comment above

**Comment by fbricon** [comment]
@bdshadow actually, the problem in che you're referring to is my 1st point :-)

> BTW, those 2 requests should not be happening. Seems like che is issuing commands to update the projects on startup (or the user did)

eclipse/eclipse.jdt.ls#544 is about NOT issuing the command from a jdt.ls perspective. I got something working, just need to add integration tests now.

**Comment by bdshadow** [comment]
ok :)

> @bdshadow actually, the problem in che you're referring to is my 1st point :-)

hah, i also started fixing https://github.com/eclipse/eclipse.jdt.ls/issues/544 :) so waiting for your PR. If you already have something to look at \ test , it'd be great to have a look without review nitpicking

**Comment by tsmaeder** [comment]
@bdshadow @fbricon free beers if you get me to renounce Eclipse IDE :-)

**Comment by bdshadow** [comment]
offered one more solution to the eclipse.jdt.ls: https://github.com/eclipse/eclipse.jdt.ls/pull/547

**Comment by tsmaeder** [comment]
Update on the current state of this effort:
1. Discovered that che wksp sends "created" notifications for every file at startup https://github.com/eclipse/che/issues/9294
2. Updated https://github.com/eclipse/eclipse.jdt.ls/pull/547/files to not update projects for pom.xml that has not yet been imported. This should take care of issue that we have 290 concurrent "update project" tasks in addition to the single "import projects" task when starting up.
3. With these things fixed, we're down to around 25 minutes when starting the workspace.
4. The eclipse workspace are currently stored in /home/user/che/ls-java, which seems to be non-persistant. As such, we're always importing projects at workspace startup.
5. The local maven repo is at /home/user/.m2, wich is also not persistent. This means we're always downloading all dependencies upon workspace startup.
