### ISSUE TITLE
[OCP] Cannot stop a process in the Terminal by Ctrl+C 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#8390]
**Reproduction Steps:**
1. Create a workspace from the **Java** stack with the **web-java-spring** project 
2. In the **Terminal** open the project folder and start a process by "**mvn clean install**" 
3. Press **Ctrl+C** buttons

**Expected behavior:**
The process is stopped

**Observed behavior:**
Nothing changed

**Failed test:** WorkingWithTerminalTest

**OS and version:**
**[OCP]** Che 6.0.0-M5; Chrome 63.0; Fedora 25

**Additional information:**
![nimbus-record-video-2018-01-22-11-37-19](https://user-images.githubusercontent.com/7760565/35214097-b15a8bc6-ff68-11e7-9a10-e62e53b63a57.gif)

**Comment by vinokurig** [comment]
I found some use-cases when this bug is not reproduced:
1. launch `mc` and then press `Ctrl + O` to hide the mc. After that all works fine until the mc is lounched.
2. `read` command interrupts with `CTRL + C`.
3. `ping` command interrupts with `CTRL + C`.

Xterm.js image launched on OCP doesn't have this problem.
The bug is reproduced on earlier (3.6) version of OCP and earlier version of Che (6.0.0-M4 tag)

Updating pty (https://github.com/eclipse/che-lib/tree/master/pty) to newer version **might** resolve this problem, but the newest version from scratch is not competeble with our terminal-agent.

**Comment by SkorikSergey** [comment]
This issue will be fixed by updating xterm.js version(Update xterm.js to the newer version - eclipse/che-lib#57).

**Comment by dmytro-ndp** [comment]
@SkorikSergey: the issue reproduced in terminal with xterm of newer version 3.3.0.

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
