### ISSUE TITLE
Uploading zip file corrupts file

### ISSUE THREAD

**Issue by minlare** [eclipse-che/che#8416]
### Description
Uploading zip file corrupts file

### Reproduction Steps
Upload zip file via "Project -> Upload File"
Download file again and it cannot be opened (I am using windows)

**Comment by ghost** [comment]
@minlare I think just downloading zip and trying to unzip it on Windows causes the same issue

**Comment by davidwindell** [comment]
This seems to be affecting images for us too, can this be labelled as a bug?

**Comment by ghost** [comment]
@davidwindell can you reproduce it on Linux?

**Comment by davidwindell** [comment]
@eivantsov Yes, on 16.04 LTS

**Comment by ghost** [comment]
@davidwindell what's your steps to reproduce? Just download a zip?

**Comment by davidwindell** [comment]
Upload any .zip (I've only test > 2mb) then use the right click download option in the file tree. The resulting file will be corrupted.

**Comment by davidwindell** [comment]
This should be marked as a bug

**Comment by davidwindell** [comment]
This is causing major issues for our team, can it be looked at with priority? It seems blocking to me

**Comment by slemeur** [comment]
@vparfonov : Could you take this issue as part of your upcoming sprint?

**Comment by dkuleshov** [comment]
Hi, 

Seems like the issue appeared after https://github.com/eclipse/che/pull/7380 pull request was merged. 

The way uploaded file data is transformed to file system item is okay for text files while for binary files it failes because of [this](https://github.com/eclipse/che/blob/master/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/fs/server/impl/FsOperations.java#L172) line in `org.eclipse.che.api.fs.server.impl.FsOperations`:
```java
byte[] bytes = readStream(content).getBytes();
```
because `readStream(content)` transforms binary data to java **`String`** that causes data mutation.

https://github.com/eclipse/che/pull/8800  pull request should fix the issue, will be merged after all CI tests are passed.

**Comment by slemeur** [comment]
Excellent. Thanks @dkuleshov
