### ISSUE TITLE
Plugin Repository/Plugin Manager for 3rd Party Enchancements

### ISSUE THREAD

**Issue by meatflavourdev** [eclipse-che/che#846]
# In order to leverage the developer community in accelerating the development of Che as a mature code editor, I'd really like to see a Plugin Manager which allows users to install and enable/disable/update plugins which 3rd party developers have listed in a public plugin repository.

As mentioned, there was plenty of developer interest at EclipseCon:

> During the Con, we had numbers of people coming to us to ask about how to build custom plugins. They are seeing us as a platform that their own tools need to be integrated with and which can provide advanced set of new features and use cases.

Perhaps something to consider for the next sprint?

**Comment by TylerJewell** [comment]
Hi @jeremyfelixd.

You can see the planned roadmap for Eclipse Che in the wiki.
https://github.com/eclipse/che/wiki/Roadmap

Also, it's possible for additional engineers to join our sprints and participate.  We plan out our weekly meetings and they are open to the community for participation and commitment into the sprint.

As far as plugins go, we have a long road ahead of us. The plugins for Che are in a variety of different types - there are server-side plugins, IDE plugins (which are compiled into the application), che server plugins, Orion editor plugins, custom stacks, and custom templates.

Last year we experimented with a drag and drop interface in the dashboard that would allow different types of plugins to be dynamically added into Che.  You could then host plugin JARs on remote repositories and drop them into the IDE.

So the list of activities that we need to do include: a) additional simplification and refactoring of the plugin system so that plugins have a smaller footprint, b) bringing the drag and drop interface back into che, c) building out a plugin resource center to provide tools and utilities for plugin developers to create advanced systems (see CUSTOMIZING.md as a starting point), d) providing ways for people to advertise various plugins.

As a starting point, we'll create a wiki that let's people list the plugins that they are working on.  People can then add / remove their work directly from that document.  Once there is a large amount of activity that occurs from natural teams working together, we can then look at formalizing Che in Eclipse's marketplace or within a Yatta profile.
