### ISSUE TITLE
[multi-user] Other user's workspaces visible

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#8544]
### Description

When clicking on "Add Workspace" in a multi-user setup (and some of the other menu options) the workspace count jumps to include ALL users workspaces (instead of the current user). Further, the "Recent Workspaces" sidebar then shows all running workspaces from other users.

Clicking on any of these correctly prevents the action but this should not be happening and is a security issue as other users workspace names are being revealed.

![web image 2018-01-31 13-12-22](https://user-images.githubusercontent.com/1720090/35625409-2ea06254-068a-11e8-9f50-8b241a4c8ad6.png)

**OS and version:**    
Che 6 (nightly 30-01-18)

**Comment by ghost** [comment]
@davidwindell I have never seen such behavior. Is it just you who can view all workspaces? Or do all users see each other's workspaces too?

**Comment by davidwindell** [comment]
All the users in our team can see that happening (i'm the admin). Ping @digiltd

**Comment by ghost** [comment]
@davidwindell I cannot reproduce it just by running multi user Che and registering 2 users. Any additional steps perhaps?

**Comment by digiltd** [comment]
the two users have workspaces running?

**Comment by digiltd** [comment]
![che-workspace-config](https://user-images.githubusercontent.com/5680968/35671353-097ffd00-0733-11e8-8eaf-c5c4319b3d4f.png)

Just to document, it happens when going into an existing workspace config as well, not just when setting up a new one.

And here is a shot of how it looks once I click/start a workspace, you can see it just shows my 13 workspaces.

![che-workspace-started](https://user-images.githubusercontent.com/5680968/35671813-75222956-0734-11e8-9ff0-e9d36327df99.png)
