### ISSUE TITLE
Che mount broken in Che6

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#8569]
There are multiple problems:

1. Root user being used to default
`let user : string = "root";`
2. Error in extracting the url
`let address: Array<string> = sshAgentServer.getUrl().replace("/", "").split(":");`
3. docker syntax being used without any multi-user flags. It's fixed for che actions but not for che mount that calls che actions commands.

**Comment by slemeur** [comment]
@skabashnyuk : Can your team give a look at this issue ?

**Comment by jakgsl** [comment]
Is this issue being looked at in the near future? Our team is having a few problems with the built in IDE; and for some projects we need a fully fledged local IDE so sync is essential for us. We could have a look at fixing it as it's a blocking issue for us, it seems it could be a quite simple fix as it was already fixed for list workspaces?

**Comment by davidwindell** [comment]
@jakgsl you might be interested in our https://github.com/outeredge/che-sync tool - our team of 5 uses it for all our projects

**Comment by jakgsl** [comment]
@davidwindell That looks great, I did see it earlier but preferred to use built in Che functionality where possible. Can I ask why you made that instead of using, improving or fixing the sync functionality within Che?

I do find it a bit odd Che sync seems to have been broken for 8+ months when the issue seems fairly simple to fix (from looking at other issues), it's local IDE selling point is mentioned on the home page as a "core capability" so I'm wondering why it's been left broken for so long, or if I'm missing part of the puzzle as a new (ish) user.

I've just given che-sync a go, and getting an unable to authenticate with server. We are running Che multi user via Docker on a DO box with keycloak on 5050, Che on 8080 - looking at entrypoint.sh it looks like it's compatible with that setup. I'll investigate further and post on your repository if I find an issue, rather than clutter this thread with non Che stuff. Thanks!

**Comment by saulide** [comment]
@davidwindell  i also get auth problems as @jakgsl , but the idea is great.

@jakgsl did you found any workaround for mounting?

**Comment by davidwindell** [comment]
@saulide any errors?
