### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#877]
I am setting up eclipse che on my home computer and want to work on it remotely. However, how do I setup a login requirement to make sure only I can access it from the internet? Might be able to do this but I have not figured out how.

**Comment by TylerJewell** [comment]
@james10174 - Right now you have the following choices:
1. Place an nginx router in front of your Che server with restricted access.
2. Install Codenvy, which has a multi-user, multi-tenant system for managing resources, permissions, users and organizations.
3. Wait until Che 4.2 or 4.3.  Codenvy is going to move their security API implementation into Che with a basic form-based authentication method.  We have to wait for this as there is still some work that is being done in the core that is needed so that workspace runtimes + terminals + agents can be locked down by user identity.  We can do this easily in Codenvy because we install a router as part of the system to help manage these details.  But with Che, your workspace has to be locked down independent of a router.

**Comment by james10174** [comment]
Is there a way to only allow one ipaddress to access a certain port with my router? Might be a good temporary fix until 4.2 or 4.3 gets these features.

**Comment by TylerJewell** [comment]
Probably - but that would be configured on your home router.  And every router is different.

**Comment by james10174** [comment]
Okay I figured out how to secure it to certain IP addresses. Using windows 8 enable firewall and add inbound rules. Add remote ip address for remote computer you want to let access via internet. Protocol type is TCP and Local port is 8080.
