### ISSUE TITLE
How to disable downloading the project

### ISSUE THREAD

**Issue by venkattarigopula** [eclipse-che/che#8826]
### Description
I would like to disable the download as zip from Workspace menu as a matter of securing the code. Is there any option in eclipse che to disable to download the project code. 
![image](https://user-images.githubusercontent.com/30365377/36348250-88cb9e78-1491-11e8-9568-7d8eca122045.png)

**Comment by eivantsov** [comment]
@venkattarigopula you need to build your own assembly of Che and remove the corresponding IDE action which should be `DownloadProjectAction`

**Comment by KOSSOKO** [comment]
@eivantsov I'm in the same situation, I would like to disable or add new features on che. How could I build my own assembly of Che with these features removed or added ? Is there any tutorial that explains how to do ?

**Comment by KOSSOKO** [comment]
@eivantsov I followed the link you have suggested but it seems that this documentation is outdated. For example I was not able to find files SampleMenuGinModule.java, SampleMenuExtension.java in the project. But these files are listed in the documentation as GIN modules file and IDE extension class

**Comment by eivantsov** [comment]
@KOSSOKO are you referring to this page https://www.eclipse.org/che/docs/6/che/docs/ide-extensions-gwt.html?

**Comment by KOSSOKO** [comment]
@eivantsov yes. I started to learn the structure of the extension, so I checked these files in the entire project without finding them

**Comment by KOSSOKO** [comment]
@eivantsov thanks. The link you provided explains well how to add a new menu item. But how to remove for example all subversion menu ? I ask all these questions because, i'm developing a solution for European Spatial Agency scientists and I have to simplify codenvy IDE in order to keep the minimum required. They said that codenvy IDE is to complex, too many features.

**Comment by eivantsov** [comment]
@KOSSOKO svn menu isn't par of the default Che assembly.

Can you clarify what exactly you are trying to achieve? Just remove Download as ZIP menu item?

**Comment by KOSSOKO** [comment]
We have to develop a tool like Google earth engine : https://code.earthengine.google.com/. In the idea, scientists wants to have an IDE to develop their code source, then  to execute it. These codes are used to process images (filtering, plot comparison...) retrieved from a satelite.
For us Eclipse che is the best solution, but we have to customize it a little bit. We need to remove unecessary features and keep simple, just the code editor, the folders hierarchy, git menu and consoles. We need also to add a panel inside che in order to view directly the image processed by the code developed by the scientists.
For the moment it's really hard to understand che and to customize it.

**Comment by eivantsov** [comment]
Closed due to inactivity. @KOSSOKO the best way is to remove the IDE action, or both IDE action and REST service.

**Comment by alphabbet** [comment]
@venkattarigopula  hello sir，do you fixed your problem of how to disable downloading the project in the eclipse-che?
