### ISSUE TITLE
Theia Command Palette Improvement 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#8976]
### Description
- [x] Ability to see all the commands in the palette
- [x] Ability to filter the commands with :
  -   `>:` allow to search only in the actions.
  -  ` #:` allow to search in the workspace commands.
  -   `... :` allow to search only for files.

**Comment by azatsarynnyy** [comment]
Theia upstream issue for the required changes in QuickOpen API: https://github.com/theia-ide/theia/issues/1680

**Comment by slemeur** [comment]
What is the progress on this issue ?

**Comment by azatsarynnyy** [comment]
Hello Stevan,
I've done with the mechanism of handling the shortcut symbols/strings by Theia's Quick Open service. Also, the API for providing the Quick Open handlers is done, so the extensions would be able to contribute its own shortcut symbols/strings with the the corresponded handlers.
In the next spring I'm going to work on the improvements to fuzzy search because currently, it can't differentiate the shortcut symbol from the actual search string. Also, I'm going to rework several Theia's Quick Open services to work with a new handler API.
Now it looks like on this screencast:
![cmd_plt](https://user-images.githubusercontent.com/1636395/43521501-b624e4c0-9596-11e8-9991-8f6a22d6a94b.gif)

**Comment by slemeur** [comment]
Thanks for the heads up !

**Comment by azatsarynnyy** [comment]
The PR https://github.com/theia-ide/theia/pull/2607 is almost ready to be merged into the Theia upstream.
Most likely, it will go into the next Theia release (0.3.14) on Aug 30.
