### ISSUE TITLE
Security for the Dashboard and Workspaces

### ISSUE THREAD

**Issue by Alex1607** [eclipse-che/che#9082]
Hey,
I have Che installed on my server and want to use it on the go. However, I'm afraid that anyone can access the server with the URL and do whatever they want. How can I secure the dashboard and the individual workspaces with a password and/or username? I have already searched for something and found some but nothing that is really easy and fast.
Or is such a feature perhaps planned?
If the possible solution is a bit more complex I would be very grateful if you could send me a link to a step-by-step tutorial because I don't have so much experience in the backend.

**Comment by gorkem** [comment]
Are you using a multi-user Che? See the following for differences. https://www.eclipse.org/che/docs/6/che/docs/single-multi-user.html

**Comment by Kavatch** [comment]
Currently I use this for only one user. (Because I'm the only one) But I think multi user would be better. Is it possible to change this setting later or would you have to reinstall the complete software and if so, what should I pay attention to in order to be able to use it in the multi-user environment?

**Comment by eivantsov** [comment]
@Kavatch there's no migration path from single to multi user.

**Comment by Kavatch** [comment]
Hey, thanks for the answer:)
But I have to ask again now, because I am not quite sure. If I want to install the software in multi-user mode, do I use these two commands?
`docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /local/path:/data eclipse/che start`

`docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=${EXTERNAL_IP} -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start`
and then the login etc. via keycloak?
Or is it another way?

**Comment by eivantsov** [comment]
No, Just the 2nd command

**Comment by Kavatch** [comment]
Okay Thank you very much :)
