### ISSUE TITLE
Get all users admin feature doesn't work properly

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#9191]
### Description
It seems that we have inconsistent admin features, cause dashboard expects that the `admin/user` service is present for che multiuser assembly, but in fact that service wasn't moved from codenvy repo.
### Reproduction Steps
see attachments:
![inconsistency](https://user-images.githubusercontent.com/12269156/37781940-666ece40-2dfa-11e8-9edb-2d69d9e7ea1c.gif)

**env:**
`che-multiuser` deployed on OpenShift instance

**Comment by skabashnyuk** [comment]
@slemeur @ashumilova I guess this is something that has to be revised. Because
- In single user mode, it doesn't make sense.
- In multi-user mode, we can't tell you the truth because we don't know it since a whole user database either on Keyclok either in LDAP connected to Keycloak either somewhere else.
