### ISSUE TITLE
Run separate instance of Theia server with plugin that is developing

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9212]
When user develops Theia plugin in Che - there are should be an ability to configure and run separate instance of Theia with current plugin inside. For such development mode -  a new “tab browser” with a new instance of Theia running should be opened.

**Comment by benoitf** [comment]
workflow is when developping a theia plugin new theia plugin model (not an extension) ?

**Comment by mmorhun** [comment]
Small clarification about implementation. This is supposed to work with new plugin model, as was said above. Because new plugin model is an extension (not plugin) of Theia we have to do this issue on the same level, i.e. extension. Theia supports both browser and electron versions, so we have to do the same here.
As about Che specific implementation (will be another extension not for Theia upstream) which will be added only in Theia inside Che workspaces, we may (for now it's the plan) do only browser implementation.

**Comment by benoitf** [comment]
Hello,
I'm not sure to fully understand "Because new plugin model is an extension (not plugin) of Theia we have to do this issue on the same level, i.e. extension." 

plugin is new isolated model, extension is the inversify extension (current theia extension model)

**Comment by benoitf** [comment]
I'm not sure to see why we're forced to use extension model instead of plugin model.
Writing plugin model requires to use extension model but plugin model will be part of theia (not che) so AFAIK we can pickup any model that we want when we want to provide stuff on top of Theia

**Comment by mmorhun** [comment]
> Writing plugin model requires to use extension

That's what I wanted to say there:
> Because new plugin model is an extension (not plugin) of Theia we have to do this issue on the same level, i.e. extension

**Comment by mmorhun** [comment]
> AFAIK we can pickup any model that we want when we want to provide stuff on top of Theia

In general yes, but when we are working on plugin model (this issue):
> Writing plugin model requires to use extension

**Comment by sunix** [comment]
I think there is something missing between this issue and the plugin model implementation. This issue is about running another theia with development plugin to be tested in the browser:

>  For such development mode - a new “tab browser” with a new instance of Theia running should be opened.

if you are working on the plugin model implementation you should create a subtask or link to the related issue.
if you are working in the electron flow, it needs to be done as part of another issue as well IMHO

**Comment by mmorhun** [comment]
Done for Theia without Che.
For OCP we have separate issue: https://github.com/eclipse/che/issues/9676
