### ISSUE TITLE
How to recreate workspace image outside che using stack and configuration files

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#9213]
I'm starting with Che. I develop a platform for ESA scientists with two uses cases : 
- **Some scientits (c1) want to develop algorithms** and test it online. So we decide to use Che for this use case.
- **Others scientits (c2) want to use these algorithms** without having to use Che because they have their own infrastucture.

To provide a solution for the second use case, we would like to recreate image of workspace with projects inside, using workspace stack and configuration file, outside of che. 

We tried to create a workspace using just stack but the Projects folder is always empty. 

How could we recreate our workspace Image with all projects inside, using docker commands ?

Thanks for the answer.

**Comment by eivantsov** [comment]
@KOSSOKO `/projects` will always be empty since when a workspace container starts, `/projects` is a volume.

You can build own images though and `ADD` or `COPY` or even git clone them in your RUN instructions.

```
FROM eclipse/ubuntu_jdk8
ADD my-project /projects/my-project
```
You can go through Docker docs to find a lot of examples. The example above implies that you have project sources locally in the same directory with a Dockerfile.

**Comment by KOSSOKO** [comment]
Thanks a lot for your answer. It helps me to understand well how che works and to find a solution for our problem. Is it possible to retrieve Dockerfile created by che ?
