### ISSUE TITLE
Disable autosave in Theia 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#9245]

**Comment by gorkem** [comment]
Looking at the demo. I think this needs to go into the settings instead of being a menu item.

**Comment by vinokurig** [comment]
It is already in the settings. This menu item just handles the settings.

**Comment by vinokurig** [comment]
Pull request to Theia upstream: https://github.com/theia-ide/theia/pull/1648
It includes menu action with toggling (similar to VScode). The problem is that the electron app doesn't view this menu action as toggled because Theia electron doesn't support dinamic menus: https://github.com/theia-ide/theia/issues/446.
To merge this PR to Theia we need to find a way to view toggled menu items in Theia electron.
May be this can be helpful: https://github.com/electron/electron/issues/528#issuecomment-267576538
