### ISSUE TITLE
"504 Gateway Time-out" error when debug of web application which is running in Eclipse Che workspace on OCP

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9251]
### Description
There is 30 sec timeout of waiting response from Web application when we stop application at the breakpoint in debug mode in Eclipse Che which is run on OCP infrastructure:
![screenshot from 2018-03-26 20-13-32](https://user-images.githubusercontent.com/1197777/37921356-4344e5e0-3132-11e8-9fb4-b018d95eb332.png)

![out](https://user-images.githubusercontent.com/1197777/37921557-d2d0cd1e-3132-11e8-8ffa-7ded9c775bac.gif)

Server response:
```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

java.lang.RuntimeException: java.lang.Exception: Cannot do request for application: 504<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

### Reproduction Steps
Steps to reproduce: look at the selenium test [StepIntoStepOverStepReturnWithChangeVariableTest#changeVariableTest()](https://github.com/eclipse/che/blob/6.2.0/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/debugger/StepIntoStepOverStepReturnWithChangeVariableTest.java#L114).

This issue is reproducing both in browser and with java client library **HttpURLConnection**.

**OS and version:**    
Eclipse Che Multiuser 6.3.0-SNAPSHOT which is run on OCP

It works correctly on Docker.

**Diagnostics:**

**Comment by eivantsov** [comment]
@dmytro-ndp @vkuznyetsov I think there is a simple workaround here:

https://docs.openshift.com/container-platform/3.7/install_config/configuring_routing.html

You can annotate web app route and the problem is solved. 

@riuvshin @sleshchenko do you think that we should annotate routes automatically? This basically makes webapp debugging with Che on OpenShift impossible.

And I removed ide label - it's definitely not the team to solve this one.

**Comment by dmytro-ndp** [comment]
Thank you for response, @eivantsov. I agree that debug ought to have meaningful timeout automatically without manual setup.

**Comment by eivantsov** [comment]
@dmytro-ndp meaningful is an arguable term. I have checked the solution outlined in OpenShift docs, and it worked for course.

The question is whether or not this is a real dev scenario and if or not a developer cares about what's in his browser. Since the debug session itself is not broken, this is only an HAProxy thing, once again, it is arguable that we need to interfere with the default 30s read time out.

**Comment by garagatyi** [comment]
@eivantsov @dmytro-ndp Personally I, as a full-time engineer don't see this as a big problem for a developer. Usually, debugging is not about changing something in debug and watching how it appears on the client side. 
But this is an important thing for some cases and definitely for demos of Che on OS. But only for certain people in certain cases, so I believe that we should not set it to something like 1h for all the workspaces of all the users. 
We can do something for particular workspaces or servers. For example, add an ability to configure this behavior in an infrastructure agnostic way in workspace attributes or server attributes. In this case, we can even provide UI to enable this.
