### ISSUE TITLE
Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: LINUX

### ISSUE THREAD

**Issue by anand853** [eclipse-che/che#926]
Hi, when am trying to execute maven project for selenium webdirver am getting below error.

**logs::**

Tests run: 11, Failures: 5, Errors: 0, Skipped: 6, Time elapsed: 2.097 sec <<< FAILURE! - in TestSuite
accessToSite(UserRegistrationTest)  Time elapsed: 0.506 sec  <<< FAILURE!
org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: LINUX
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: '977554c0778e', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.1.19-boot2docker', java.version: '1.8.0_45'
Driver info: driver.version: FirefoxDriver
    at org.openqa.selenium.firefox.internal.Executable.<init>(Executable.java:75)

Pls. let me know how to / where to change the configuration for FF, the code woks fine with out any issues in normal eclipse
[](https://github.com/anand853/MatchingWithMaven)

**Comment by TylerJewell** [comment]
@anand853: Did you install the firefox binaries into your workspace?

The workspace when it is first created is an Ubuntu workspace.  It's off in the cloud, so after that, you need to install additional software into the workspace that your projects will require.  There are two ways to do this:
1. Open a terminal and just install the software you need on the command line, or:
2. Create a custom stack as a Dockerfile, which you then use when creating a workspace.  The Dockerfile will have the software you need inside of it.  You could look for a selenium Web Dockerfile that makes sense on DockerHub.  And then there are some modifications you make to it so that Eclipse Che will do its magic:  https://eclipse-che.readme.io/docs/stacks

**Comment by ghost** [comment]
If you want to launch selenium tests in a Che workspace you will need a custom environment with x server, selenium and firefox installed.

We do have an image that our QA engineers use internally but it's for Chrome only.
