### ISSUE TITLE
Default profile of an integration-tests module should not depend on tests artifacts

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#9462]
### Description
The infrastructure mechanism in Che desired as pluggable, it's mean that you are able to provide your own implementation of the contract to run the workspaces in a different container / VM platforms. This, in turn, implies that you do not need to have artefacts of all infrastructures that are placed in Che to build `ws-master` module, but at the moment it is not so. You need at least  Kubernetes artefacts that are required for `postgresql-tck` module.
The possible ways to avoid dependence on infrastructure it's to make maven profile with dependencies and move it from the default lifecycle(e.g. in existing integration profile).

**Comment by sleshchenko** [comment]
I like the idea with moving dependencies into `integration` profile, it will fix an issue with building Che project without test compiling (-Dmaven.test.skip=true).

But I think moving dependencies into `integration` profile won't fix an issue with optional Kubernetes infrastructure. We have the same issue with multiuser dependencies in integration module like `che-multiuser-machine-authentication` module. Since multiuser may be an option in custom assembly.
I think the easiest solution here will be moving `integration-tests` module outside of `wsmaster` module.
