### ISSUE TITLE
Workspaces can not be started after change image in the "Machine" section

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#9542]
### Reproduction Steps
 - Create workspace from default "Java" stack 
 - Open "Workspaces" page
 - In the workspaces list select just created workspace and click on it
 - In the opened "workspace details" page click on the "Machine" button
 - Click on the "Edit" button 
 - In the "Recipe" text field delete several letters in the image name, it should be "eclipse/ubuntu_jd"
 - Click on the "Save" button
 - Click on the "Run" button
 - Pay attention to the error message
 - Try to create and run workspace with any stack
 - Pay attention to the errors

**Expected conditions:**
  Workspace with wrong image is not started but test workspace is started successfully 

**Observed behavior:**
Workspace with wrong image is not started and test workspace has the same error  

**Attachment:**
![screencast-6_1](https://user-images.githubusercontent.com/22724619/39252751-01f3123a-48af-11e8-82d3-fd3d93263e7a.gif)

**OS and version:**    
Che 6.5.0 ; Fedora 25 ; Chrome 63.0

**Comment by sleshchenko** [comment]
I think it is a server side issue. It is related to https://github.com/eclipse/che/pull/9426.
There is an issue with container watching when all workspaces' objects are created in one namespace: In such case, it is required to filter pods and propagate only events which are related a particular workspace.

A similar scenario but with one workspace has two issues:
<details>
<summary>Reproduction Steps</summary>

1. Create workspace from default "Java" stack.
2. Open "Workspaces" page.
3. In the workspaces list select just created workspace and click on it.
4. In the opened "workspace details" page click on the "Machine" button.
5. Click on the "Edit" button.
6. In the "Recipe" text field delete several letters in the image name, it should be "eclipse/ubuntu_jd".
7. Click on the "Save" button.
8. Click on the "Run" button.
9. Pay attention to the error message.
10. Fix machine's image to a correct one.
11. Rerun the workspace.
12. Pay attention to the errors.
</details>

1. OpenShift Infrastructure doesn't support start interruption, because of that the second start try fails with error message: `Runtime is already started`. Also because of that, it is not possible to delete failed workspace. Will be fixed by https://github.com/eclipse/che/issues/5918.
2. OpenShift sends events that happened before (like 20 minutes ago). It means that even when image reference will be fixed workspace start will fails because of an old event from history. In this way, Che Server considers workspace as failed to start when it receives old events. REST API allows specifying resource version or time (I'm not sure what exactly) for filtering old events. But Fabric8 client has deprecated method [watch(String resourceVerion, W watcher)](https://github.com/fabric8io/kubernetes-client/blob/v3.1.0/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Watchable.java). Need to investigate how to fix it.

@ibuziuk  I think it would be better to comment unrecoverable events listener until these issues are not fixed.

**Comment by garagatyi** [comment]
@ibuziuk @l0rd I think we should not include unrecoverable events commit in 6.4.1 to avoid blocker bug on OSIO prod.

**Comment by eivantsov** [comment]
Will this issues be taken care of in upcoming sprints? The ability to show why exactly pod failed to start is a very helpful feature both for Che admin and users on OpenShift.

**Comment by garagatyi** [comment]
And since it is blocker should we fix it right away with even stopping work on other issues?

**Comment by eivantsov** [comment]
I agree, we should at least disable the feature @ibuziuk added until we investigate a proper fix.

@l0rd @skabashnyuk can you agree on whose sprint it is going to land in?

**Comment by garagatyi** [comment]
I've disabled unrecoverable events handling till we have a proper fix. Downgrading the priority from blocker to P1

**Comment by SkorikSergey** [comment]
Still actual for CHE ver.  6.5.0.

**Comment by ibuziuk** [comment]
PR is sent - https://github.com/eclipse/che/pull/9703

**Comment by ibuziuk** [comment]
Fix is merged to master

**Comment by Ohrimenko1988** [comment]
This issue may be closed because the main problem was resolved. But bug with deleting of the workspace is still actual. It is described in the next issue:
https://github.com/eclipse/che/issues/9905
