### ISSUE TITLE
Quick start documentation for openshift-ansible installation?

### ISSUE THREAD

**Issue by dneary** [eclipse-che/che#9568]
## Description

To try Che, I installed OpenShift on a small 2-node cluster of Intel NUCs. I used openshift-ansible, as my understanding is that minishift is for a single-host deployment only.

The issue is, on the Che website, almost all of the documentation says how to install Che with Minishift. What is the recommended quick start method if I am running a different Kubernetes to OpenShift, or if I have used a different tool to install OpenShift? I am looking for a single-user, simple install - are the instructions I should follow on the ["Multi-user: Deploy to OpenShift"](https://www.eclipse.org/che/docs/openshift-multi-user.html) web page?

**Comment by dneary** [comment]
I would not normally consider this an issue, but I was told this was a good place to ask questions. Is there a more appropriate forum for questions like these?

**Comment by dneary** [comment]
I followed the instructions on https://www.eclipse.org/che/docs/openshift-multi-user.html for OpenShift Container Platform -> HTTP. How can I reach Che now? It is using the routing prefix of test-che.router.default.svc.cluster.local and my laptop does not know how to route there.

**Comment by eivantsov** [comment]
@dneary https://www.eclipse.org/che/docs/openshift-single-user.html#openshift-container-platform

When deploying to OCP, you had to provide your cluster routing suffix as a param to oc new-app command. `test-che.router.default.svc.cluster.local` can be resolved only in the cluster. Since I don't know how you installed OpenShift and deployed Che, I cannot help more now.

Also, when executing commands to deploy, oc should have responded back with URLs that an app is accessible at.
