### ISSUE TITLE
Option to disable search index?

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#9605]
Is it possible to disable Lucene indexing?

We don't use the search in the IDE but when launching workspaces, there is significant CPU usage for over a minute whilst the index is built:

`2018-05-04 00:59:28,352[rcherInitThread]  [INFO ] [o.e.c.a.s.s.i.LuceneSearcher 158]    - Initial indexing complete after 91476 msec `

Alternatively, is it possible to declare folders to ignore for search?

**OS and version:**    
Che 6.4.1

**Comment by skabashnyuk** [comment]
I would suggest taking a look on this property ```vfs.index_filter_matcher``` https://github.com/eclipse/che/blob/master/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/search/server/impl/LuceneSearcher.java#L117

**Comment by skabashnyuk** [comment]
No. 
1. Because there is no one who can transfer it to ws-agent.
2. Even if someone transfers it to ws_agent it has to be transformed to ```CHE_``` prefixed format to pass this filter https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-inject/src/main/java/org/eclipse/che/inject/CheBootstrap.java#L279

The only way what I can see is to create file assembly-wsagent-war/src/main/webapp/WEB-INF/classes/che/che.properties and put a value  ``` vfs.index_filter_matcher=sdfsdfzz```

**Comment by davidwindell** [comment]
Ok, I'll close for now as don't want to build a custom assembly. It would be good on the future to have a flag to disable indexing to reduce resource when it's not needed. Or at least wait until the first file is opened
