### ISSUE TITLE
No "ProjectDeletedEvent" when a project is deleted

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#9635]
### Description

In my code (working on 5.22.1) I subscribe to the event `org.eclipse.che.api.project.server.notification.ProjectDeletedEvent` using       `org.eclipse.che.api.core.notification.EventService.subscribe()`.

In 6.x this event is not fired any more.

When searching the che master, I can see that the event-class (`ProjectDeletedEvent`) is still there and that  `org.eclipse.che.plugin.maven.server.core.MavenWorkspace` also subscribes to it in order to clean up the maven project.

But the event is not published any more at all,  so either this code should be removed completely (and a new mechanism to react to the deletion of a project needs to be introduced), or the event has to be published.

Note: In 5.22.1 it was published by `org.eclipse.che.api.project.server.ProjectRegistry.removeProjects()`.

**Comment by eivantsov** [comment]
@vparfonov can you help?

**Comment by vparfonov** [comment]
Ok I will check it

**Comment by vzhukovskii** [comment]
Hello @ChristianSchenk711, can you pull new changes from the master branch? This problem has been fixed with this commit https://github.com/eclipse/che/blob/db8c142dfa24f53b1b22febfc8a38da910ab95a8/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java#L231-L235
Now, when project is removing, missed event is fired.

**Comment by ChristianSchenk711** [comment]
Thanks! I will test that when we integrate the new version. Issue can be closed from my point of view.

**Comment by vzhukovskii** [comment]
No problem, in any case feel free to ask questions!
