### ISSUE TITLE
Make LSP client proxy support dynamicRegistration for client capabilities

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#9797]
Actual implementation does not support dynamic client capabilities registration. In order to make the workflow more flexible we should support it. Seems like depending on the implementation some servers can provide capabilities dynamically (e.g. Golang server).

See `WorkspaceClientCapabilities` and `TextDocumentClientCapabilities` in [LSP Specification](https://microsoft.github.io/language-server-protocol/specification).

**Comment by gorkem** [comment]
@dkuleshov Is this a blocker for Golang server? jdt.ls also supports dynamic capabilities however if a client does not support it the server should be able to fall-back to fixed capability reporting. If this is not the case for Golang we should report it.

**Comment by dkuleshov** [comment]
@gorkem According to what I see golang LS ignores `dynamicRegistration` set to false and tries to register a new capability. The bug is reported here https://github.com/eclipse/che/issues/979, we will report the golang LS bug if it is confirmed during the work on our bug.

I'm not yet sure if that's a blocker for https://github.com/eclipse/che/issues/9781 but if it is than it will be mentioned here as well.

**Comment by vparfonov** [comment]
Will take to the nearest sprint for analyzing this ability for our client

**Comment by vparfonov** [comment]
I think it's just nice to have, not critical. Firstly we need to upgrade lsp4j (#9864), and fix several technical impediments. Which mainly comes from our feature for supporting multi language server for on opened file.
