### ISSUE TITLE
Ide cannot run with che-samples/che-plugin-json

### ISSUE THREAD

**Issue by cenkce** [eclipse-che/che#9810]
### Description
 

https://github.com/che-samples/che-plugin-json/issues/8

**Comment by cenkce** [comment]
Is there any idea what problem is? I create new file extension plugin using it but I can't. Or You have any recommendations?

**Comment by mkuznyetsov** [comment]
yes, there's some assembly packaging problems right now, I will make a fix soon

**Comment by cenkce** [comment]
Can I fix it locally? It's important to me.

**Comment by mkuznyetsov** [comment]
Yes, you can make it launchable, by opening assembly/assembly-ide-war/pom.xml
and removing the following line#169:
`<packagingExcludes>%regex[WEB-INF\\lib\\(?!.*j2ee).*.jar]</packagingExcludes>`
then rebuild assemblies and you can start the IDE
Ther are still some things that are broken, like DashboardRedirectionFilter, because of which you will need to use URL `http://<che.ip>:8080/dashboard/` to access the Dashboard, and not just `http://<che.ip>:8080/` . I work on that right now as well. 
But other than that, the assemply and the plugin should be working.

**Comment by cenkce** [comment]
Yeah it worked, big thanks :)
