### ISSUE TITLE
org.eclipse.che.api.languageserver.RegistryContainer makes it hard to track usages

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9829]
With recent changes, the Class org.eclipse.che.api.languageserver.RegistryContainer has been introduced. The instance variables defined there are assigned to instance variables in other classes. This makes it very hard to track down all instances where those registries are modified or accessed. 
Data should be owned by a single class and in general hidden from other classes. This make systems easier to understand.

**Comment by dkuleshov** [comment]
> This makes it very hard to track down all instances where those registries are modified or accessed.

That is a subjective opinion, because I don't find it very hard, for example. So if you don't mind I will consider this statement as an unreasonable assumption until you provide more objective reasoning or examples. 

> Data should be owned by a single class and in general hidden from other classes.

This is true for normal java classes with state and behavior. `RegistryContainer` is a container for other instances, technically it is a class but functionally it is a container, it is package private class and all registry instances inside are final, so an assumption of encapsulation violation is inappropriate here.

**Comment by vparfonov** [comment]
not actual
