### ISSUE TITLE
Study: Authentication with jwtproxy

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9843]
### Description
Study concept of authentification based on jwtproxy container https://github.com/coreos/jwtproxy.
Basic idea: if authentification is needed we start additional container with jwtproxy as part of the workspace. Goal of this container is to check jwt token to access to Theia server-side and sign each request with jwt tokens to workspace master.

**Comment by mshaposhnik** [comment]
After some research in authentication proxy, the following scheme is may be considered as an inital plan:
![proxy-diagram2 2](https://user-images.githubusercontent.com/1651062/41035246-bd8ceeb6-6994-11e8-9576-ccbee3e754c5.jpg)

In brief, Theia client-side code will request the JWT token from Che master, and use it to communicate with the serverside. Verification of tokens signatures wll be done by reverse proxy, which will use preallocated or (IMO better option) fetch the public keys from master. Valid requests are propagated to the Theia serverside.  

The still unsolved question, is when the Theia servserside need to additionally request the master.
If it need that as a reaction for an user request, than it can probably use the same token which came from client. But if Theia SS needs to do some requests independently, than another signing proxy should be used and master will perform another kind of validation with requesting public key from the signer. (dotted way on the image). jwtproxy signer seems to be not very convenient way to implement this, because it is not an transparent proxy, so no simple way to always reroute those requests to the master.

**Comment by mshaposhnik** [comment]
@gorkem Yep. Explicit (non-transparent) proxy means that client (browser or cURL or wget etc) must define proxy explicitly, i.e. asking `192.168.100.99:8080/api/user` using proxy `127.0.0.1:3128` for example. While transparent proxy does need that, you're simply requesting directly `127.0.0.1:3128/api/user` and it will be rerouted to the original host just by predefined rules inside of the proxy (very similarly how haproxy doing that)

**Comment by mshaposhnik** [comment]
IMO as the first step we can start without the signer proxy at all, since there is no known cases at this moment when Theia server-side must request master by his own initiative (i.e. without underlying user request which can be used as authoeship source). Does anyone has doubts on that ?

**Comment by mshaposhnik** [comment]
So i see the following tasks list for the initial implementation:
1) Create REST endpoint for publishing JWT keys and signatures public key parts;
2) Create & configure & execute proxy verifier pod\container;
3) Write Theia client-side plugin  to fetch key and sign outbound http requests;
4) Write Theia server-side module to tranparently forward keys from incoming client requests to outgoing master requests if needed;
5) Organize keys rotation (single key per whole workspace lifetime does not seems very reliably);

**Comment by gorkem** [comment]
@mshaposhnik We are [discussing](https://github.com/eclipse/che/issues/9913) retrieving the connection parameters for Language servers from che-server during workspace startup , I guess we are going to need the no-user authentication scenario.

**Comment by mshaposhnik** [comment]
@gerkan Not sure i'm fully understand those "not-user-driven" requests scenario.  We expect that conversations between Theia and LS will ocur inside the same network and will not pass throuth the auth proxy. Did i miss something?

**Comment by gorkem** [comment]
@mshaposhnik This is from Theia backend to wsmaster APIs, @skabashnyuk  correct?

**Comment by mshaposhnik** [comment]
Yes, we expect to sign requests from Theia frontent to backend, and Theia backend to wsmaster.  But inside the workspace we're not expect to sign anything (i.e. theia back to LS for example)

**Comment by mshaposhnik** [comment]
Example of memory consumption (10 req/sec load):
![screenshot_20180611_183105](https://user-images.githubusercontent.com/1651062/41277421-e9338ea4-6e2f-11e8-8680-8a529c895045.png)
