### ISSUE TITLE
Fix selenium test after update xterm.js from 2.4.0 to 3.3.0 version.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#9909]
### Description
Fix selenium test after update xterm.js from 2.4.0 to 3.3.0 version.
Related issue: https://github.com/eclipse/che-lib/issues/57

**Comment by AndrienkoAleksandr** [comment]
Related to the pull requests:
https://github.com/eclipse/che-lib/pull/87 and https://github.com/eclipse/che/pull/10037

**Comment by AndrienkoAleksandr** [comment]
@musienko-maxim Could somebody from QA team give this issue?

**Comment by dmytro-ndp** [comment]
Tests of _Terminal_ on _Docker_ fail because of there is different command line prompt inside the _Terminal_ https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-docker/311/Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.miscellaneousWorkingWithTerminalTest
![org eclipse che selenium miscellaneous workingwithterminaltest shouldbeclear_04itq2f1](https://user-images.githubusercontent.com/1197777/44336409-04e9cb00-a480-11e8-9184-c112247f581e.png)
